declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00002/certs"
declare -x AZ_BATCH_JOB_ID="svm"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/svm/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/svm/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_10-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00002"
declare -x AZ_BATCH_TASK_ID="task-00002"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00002/wd"
declare -x HOME="/mnt/batch/tasks/workitems/svm/job-1/task-00002/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/svm/job-1/task-00002/wd"
declare -x PWD="/mnt/batch/tasks/workitems/svm/job-1/task-00002/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 20:32:09] Results will not be logged locally.
[2018-04-11 20:32:09] Retrieving tasks...
[2018-04-11 20:32:09] Tasks will be retrieved based on provided task ids.
[2018-04-11 20:32:09] The following tasks were retrieved: [45].
[2018-04-11 20:32:16] Downloaded task 45.
[2018-04-11 20:32:16] Prepared pipelines.
[2018-04-11 20:32:16] Started run 1 on task 45, dataset 'splice'.
[2018-04-11 20:32:16] Started run 3 on task 45, dataset 'splice'.
[2018-04-11 20:32:16] Started run 2 on task 45, dataset 'splice'.
[2018-04-11 20:32:16] Started run 4 on task 45, dataset 'splice'.
[2018-04-11 20:32:16] Started run 5 on task 45, dataset 'splice'.
[2018-04-11 20:32:16] Started run 6 on task 45, dataset 'splice'.
[2018-04-11 20:32:16] Started run 7 on task 45, dataset 'splice'.
[2018-04-11 20:32:16] Started run 8 on task 45, dataset 'splice'.
[2018-04-11 20:32:21] Error in run 2: Run already exists in server. Run id(s): {8923373}
[2018-04-11 20:32:21] Started run 9 on task 45, dataset 'splice'.
[2018-04-11 20:32:21] Error in run 1: Run already exists in server. Run id(s): {8923372}
[2018-04-11 20:32:21] Started run 10 on task 45, dataset 'splice'.
[2018-04-11 20:32:21] Error in run 5: Run already exists in server. Run id(s): {8923375}
[2018-04-11 20:32:21] Started run 11 on task 45, dataset 'splice'.
[2018-04-11 20:32:21] Error in run 3: Run already exists in server. Run id(s): {8923362}
[2018-04-11 20:32:21] Started run 12 on task 45, dataset 'splice'.
[2018-04-11 20:32:21] Error in run 6: Run already exists in server. Run id(s): {8923386}
[2018-04-11 20:32:21] Error in run 4: Run already exists in server. Run id(s): {8923368}
[2018-04-11 20:32:21] Started run 13 on task 45, dataset 'splice'.
[2018-04-11 20:32:21] Error in run 7: Run already exists in server. Run id(s): {8923388}
[2018-04-11 20:32:21] Started run 14 on task 45, dataset 'splice'.
[2018-04-11 20:32:21] Started run 15 on task 45, dataset 'splice'.
[2018-04-11 20:32:22] Error in run 8: Run already exists in server. Run id(s): {8923389}
[2018-04-11 20:32:22] Started run 16 on task 45, dataset 'splice'.
[2018-04-11 20:32:26] Error in run 10: Run already exists in server. Run id(s): {8923404}
[2018-04-11 20:32:26] Started run 17 on task 45, dataset 'splice'.
[2018-04-11 20:32:26] Error in run 9: Run already exists in server. Run id(s): {8923391}
[2018-04-11 20:32:26] Started run 18 on task 45, dataset 'splice'.
[2018-04-11 20:32:26] Error in run 11: Run already exists in server. Run id(s): {8923407}
[2018-04-11 20:32:26] Started run 19 on task 45, dataset 'splice'.
[2018-04-11 20:32:26] Error in run 15: Run already exists in server. Run id(s): {8923427}
[2018-04-11 20:32:26] Started run 20 on task 45, dataset 'splice'.
[2018-04-11 20:32:26] Error in run 12: Run already exists in server. Run id(s): {8923406}
[2018-04-11 20:32:26] Error in run 13: Run already exists in server. Run id(s): {8923411}
[2018-04-11 20:32:26] Started run 21 on task 45, dataset 'splice'.
[2018-04-11 20:32:26] Error in run 14: Run already exists in server. Run id(s): {8923423}
[2018-04-11 20:32:26] Started run 23 on task 45, dataset 'splice'.
[2018-04-11 20:32:26] Started run 22 on task 45, dataset 'splice'.
[2018-04-11 20:32:27] Error in run 16: Run already exists in server. Run id(s): {8923417}
[2018-04-11 20:32:27] Started run 24 on task 45, dataset 'splice'.
[2018-04-11 20:32:30] Error in run 18: Run already exists in server. Run id(s): {8923436}
[2018-04-11 20:32:30] Started run 25 on task 45, dataset 'splice'.
[2018-04-11 20:32:31] Error in run 17: Run already exists in server. Run id(s): {8923428}
[2018-04-11 20:32:31] Started run 26 on task 45, dataset 'splice'.
[2018-04-11 20:32:31] Error in run 21: Run already exists in server. Run id(s): {8923449}
[2018-04-11 20:32:31] Error in run 19: Run already exists in server. Run id(s): {8923439}
[2018-04-11 20:32:31] Error in run 20: Run already exists in server. Run id(s): {8923433}
[2018-04-11 20:32:31] Started run 27 on task 45, dataset 'splice'.
[2018-04-11 20:32:31] Started run 28 on task 45, dataset 'splice'.
[2018-04-11 20:32:31] Started run 29 on task 45, dataset 'splice'.
[2018-04-11 20:32:31] Error in run 23: Run already exists in server. Run id(s): {8923445}
[2018-04-11 20:32:31] Started run 30 on task 45, dataset 'splice'.
[2018-04-11 20:32:31] Error in run 22: Run already exists in server. Run id(s): {8923450}
[2018-04-11 20:32:31] Started run 31 on task 45, dataset 'splice'.
[2018-04-11 20:32:31] Error in run 24: Run already exists in server. Run id(s): {8923457}
[2018-04-11 20:32:31] Started run 32 on task 45, dataset 'splice'.
[2018-04-11 20:32:35] Error in run 25: Run already exists in server. Run id(s): {8923455}
[2018-04-11 20:32:35] Started run 33 on task 45, dataset 'splice'.
[2018-04-11 20:32:35] Error in run 26: Run already exists in server. Run id(s): {8923458}
[2018-04-11 20:32:35] Started run 34 on task 45, dataset 'splice'.
[2018-04-11 20:32:35] Error in run 28: Run already exists in server. Run id(s): {8923473}
[2018-04-11 20:32:35] Started run 35 on task 45, dataset 'splice'.
[2018-04-11 20:32:35] Error in run 29: Run already exists in server. Run id(s): {8923477}
[2018-04-11 20:32:35] Started run 36 on task 45, dataset 'splice'.
[2018-04-11 20:32:35] Error in run 30: Run already exists in server. Run id(s): {8923468}
[2018-04-11 20:32:35] Started run 37 on task 45, dataset 'splice'.
[2018-04-11 20:32:35] Error in run 27: Run already exists in server. Run id(s): {8923469}
[2018-04-11 20:32:35] Started run 38 on task 45, dataset 'splice'.
[2018-04-11 20:32:36] Error in run 31: Run already exists in server. Run id(s): {8923491}
[2018-04-11 20:32:36] Started run 39 on task 45, dataset 'splice'.
[2018-04-11 20:32:36] Error in run 32: Run already exists in server. Run id(s): {8923486}
[2018-04-11 20:32:36] Started run 40 on task 45, dataset 'splice'.
[2018-04-11 20:32:40] Error in run 33: Run already exists in server. Run id(s): {8923494}
[2018-04-11 20:32:40] Started run 41 on task 45, dataset 'splice'.
[2018-04-11 20:32:40] Error in run 34: Run already exists in server. Run id(s): {8923489}
[2018-04-11 20:32:40] Error in run 35: Run already exists in server. Run id(s): {8923505}
[2018-04-11 20:32:40] Started run 42 on task 45, dataset 'splice'.
[2018-04-11 20:32:40] Started run 43 on task 45, dataset 'splice'.
[2018-04-11 20:32:40] Error in run 36: Run already exists in server. Run id(s): {8923500}
[2018-04-11 20:32:40] Started run 44 on task 45, dataset 'splice'.
[2018-04-11 20:32:40] Error in run 38: Run already exists in server. Run id(s): {8923514}
[2018-04-11 20:32:40] Started run 45 on task 45, dataset 'splice'.
[2018-04-11 20:32:40] Error in run 39: Run already exists in server. Run id(s): {8923510}
[2018-04-11 20:32:40] Started run 46 on task 45, dataset 'splice'.
[2018-04-11 20:32:40] Error in run 37: Run already exists in server. Run id(s): {8923512}
[2018-04-11 20:32:40] Started run 47 on task 45, dataset 'splice'.
[2018-04-11 20:32:41] Error in run 40: Run already exists in server. Run id(s): {8923523}
[2018-04-11 20:32:41] Started run 48 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Error in run 41: Run already exists in server. Run id(s): {8923530}
[2018-04-11 20:32:45] Started run 49 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Error in run 43: Run already exists in server. Run id(s): {8923534}
[2018-04-11 20:32:45] Started run 50 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Error in run 42: Run already exists in server. Run id(s): {8923519}
[2018-04-11 20:32:45] Started run 51 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Error in run 45: Run already exists in server. Run id(s): {8923540}
[2018-04-11 20:32:45] Started run 52 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Error in run 44: Run already exists in server. Run id(s): {8923535}
[2018-04-11 20:32:45] Error in run 46: Run already exists in server. Run id(s): {8923549}
[2018-04-11 20:32:45] Started run 53 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Started run 54 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Error in run 47: Run already exists in server. Run id(s): {8923553}
[2018-04-11 20:32:45] Started run 55 on task 45, dataset 'splice'.
[2018-04-11 20:32:45] Error in run 48: Run already exists in server. Run id(s): {8923550}
[2018-04-11 20:32:45] Started run 56 on task 45, dataset 'splice'.
[2018-04-11 20:32:49] Error in run 49: Run already exists in server. Run id(s): {8923561}
[2018-04-11 20:32:49] Started run 57 on task 45, dataset 'splice'.
[2018-04-11 20:32:49] Error in run 50: Run already exists in server. Run id(s): {8923567}
[2018-04-11 20:32:49] Started run 58 on task 45, dataset 'splice'.
[2018-04-11 20:32:49] Error in run 54: Run already exists in server. Run id(s): {8923588}
[2018-04-11 20:32:49] Started run 59 on task 45, dataset 'splice'.
[2018-04-11 20:32:49] Error in run 53: Run already exists in server. Run id(s): {8923580}
[2018-04-11 20:32:49] Started run 60 on task 45, dataset 'splice'.
[2018-04-11 20:32:49] Error in run 51: Run already exists in server. Run id(s): {8923566}
[2018-04-11 20:32:49] Error in run 52: Run already exists in server. Run id(s): {8923568}
[2018-04-11 20:32:49] Started run 61 on task 45, dataset 'splice'.
[2018-04-11 20:32:49] Started run 62 on task 45, dataset 'splice'.
[2018-04-11 20:32:50] Error in run 55: Run already exists in server. Run id(s): {8923577}
[2018-04-11 20:32:50] Started run 63 on task 45, dataset 'splice'.
[2018-04-11 20:32:50] Error in run 56: Run already exists in server. Run id(s): {8923578}
[2018-04-11 20:32:50] Started run 64 on task 45, dataset 'splice'.
[2018-04-11 20:32:54] Error in run 57: Run already exists in server. Run id(s): {8923596}
[2018-04-11 20:32:54] Error in run 58: Run already exists in server. Run id(s): {8923600}
[2018-04-11 20:32:54] Started run 65 on task 45, dataset 'splice'.
[2018-04-11 20:32:54] Started run 66 on task 45, dataset 'splice'.
[2018-04-11 20:32:54] Error in run 59: Run already exists in server. Run id(s): {8923590}
[2018-04-11 20:32:54] Error in run 61: Run already exists in server. Run id(s): {8923606}
[2018-04-11 20:32:54] Started run 67 on task 45, dataset 'splice'.
[2018-04-11 20:32:54] Started run 68 on task 45, dataset 'splice'.
[2018-04-11 20:32:54] Error in run 60: Run already exists in server. Run id(s): {8923602}
[2018-04-11 20:32:54] Started run 69 on task 45, dataset 'splice'.
[2018-04-11 20:32:54] Error in run 62: Run already exists in server. Run id(s): {8923609}
[2018-04-11 20:32:54] Started run 70 on task 45, dataset 'splice'.
[2018-04-11 20:32:54] Error in run 63: Run already exists in server. Run id(s): {8923608}
[2018-04-11 20:32:54] Started run 71 on task 45, dataset 'splice'.
[2018-04-11 20:32:55] Error in run 64: Run already exists in server. Run id(s): {8923623}
[2018-04-11 20:32:55] Started run 72 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Error in run 65: Run already exists in server. Run id(s): {8923625}
[2018-04-11 20:32:59] Started run 73 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Error in run 66: Run already exists in server. Run id(s): {8923627}
[2018-04-11 20:32:59] Error in run 68: Run already exists in server. Run id(s): {8923631}
[2018-04-11 20:32:59] Started run 74 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Error in run 67: Run already exists in server. Run id(s): {8923622}
[2018-04-11 20:32:59] Started run 76 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Started run 75 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Error in run 70: Run already exists in server. Run id(s): {8923643}
[2018-04-11 20:32:59] Started run 77 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Error in run 69: Run already exists in server. Run id(s): {8923642}
[2018-04-11 20:32:59] Started run 78 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Error in run 71: Run already exists in server. Run id(s): {8923648}
[2018-04-11 20:32:59] Started run 79 on task 45, dataset 'splice'.
[2018-04-11 20:32:59] Error in run 72: Run already exists in server. Run id(s): {8923653}
[2018-04-11 20:32:59] Started run 80 on task 45, dataset 'splice'.
[2018-04-11 20:33:03] Error in run 74: Run already exists in server. Run id(s): {8923659}
[2018-04-11 20:33:03] Started run 81 on task 45, dataset 'splice'.
[2018-04-11 20:33:03] Error in run 73: Run already exists in server. Run id(s): {8923660}
[2018-04-11 20:33:03] Started run 82 on task 45, dataset 'splice'.
[2018-04-11 20:33:03] Error in run 76: Run already exists in server. Run id(s): {8923673}
[2018-04-11 20:33:03] Started run 83 on task 45, dataset 'splice'.
[2018-04-11 20:33:03] Error in run 75: Run already exists in server. Run id(s): {8923656}
[2018-04-11 20:33:03] Started run 84 on task 45, dataset 'splice'.
[2018-04-11 20:33:04] Error in run 77: Run already exists in server. Run id(s): {8923674}
[2018-04-11 20:33:04] Error in run 78: Run already exists in server. Run id(s): {8923680}
[2018-04-11 20:33:04] Started run 85 on task 45, dataset 'splice'.
[2018-04-11 20:33:04] Started run 86 on task 45, dataset 'splice'.
[2018-04-11 20:33:04] Error in run 79: Run already exists in server. Run id(s): {8923677}
[2018-04-11 20:33:04] Started run 87 on task 45, dataset 'splice'.
[2018-04-11 20:33:04] Error in run 80: Run already exists in server. Run id(s): {8923687}
[2018-04-11 20:33:04] Started run 88 on task 45, dataset 'splice'.
[2018-04-11 20:33:08] Error in run 82: Run already exists in server. Run id(s): {8923695}
[2018-04-11 20:33:08] Started run 89 on task 45, dataset 'splice'.
[2018-04-11 20:33:08] Error in run 81: Run already exists in server. Run id(s): {8923691}
[2018-04-11 20:33:08] Started run 90 on task 45, dataset 'splice'.
[2018-04-11 20:33:08] Error in run 83: Run already exists in server. Run id(s): {8923697}
[2018-04-11 20:33:08] Started run 91 on task 45, dataset 'splice'.
[2018-04-11 20:33:08] Error in run 85: Run already exists in server. Run id(s): {8923708}
[2018-04-11 20:33:08] Error in run 84: Run already exists in server. Run id(s): {8923707}
[2018-04-11 20:33:08] Started run 92 on task 45, dataset 'splice'.
[2018-04-11 20:33:08] Started run 93 on task 45, dataset 'splice'.
[2018-04-11 20:33:08] Error in run 86: Run already exists in server. Run id(s): {8923709}
[2018-04-11 20:33:08] Started run 94 on task 45, dataset 'splice'.
[2018-04-11 20:33:08] Error in run 87: Run already exists in server. Run id(s): {8923710}
[2018-04-11 20:33:08] Started run 95 on task 45, dataset 'splice'.
[2018-04-11 20:33:09] Error in run 88: Run already exists in server. Run id(s): {8923712}
[2018-04-11 20:33:09] Started run 96 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 90: Run already exists in server. Run id(s): {8923714}
[2018-04-11 20:33:13] Started run 97 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 89: Run already exists in server. Run id(s): {8923711}
[2018-04-11 20:33:13] Started run 98 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 91: Run already exists in server. Run id(s): {8923716}
[2018-04-11 20:33:13] Started run 99 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 94: Run already exists in server. Run id(s): {8923721}
[2018-04-11 20:33:13] Started run 100 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 92: Run already exists in server. Run id(s): {8923715}
[2018-04-11 20:33:13] Started run 101 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 93: Run already exists in server. Run id(s): {8923717}
[2018-04-11 20:33:13] Started run 102 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 95: Run already exists in server. Run id(s): {8923718}
[2018-04-11 20:33:13] Started run 103 on task 45, dataset 'splice'.
[2018-04-11 20:33:13] Error in run 96: Run already exists in server. Run id(s): {8923722}
[2018-04-11 20:33:13] Started run 104 on task 45, dataset 'splice'.
[2018-04-11 20:33:17] Error in run 97: Run already exists in server. Run id(s): {8923724}
[2018-04-11 20:33:17] Started run 105 on task 45, dataset 'splice'.
[2018-04-11 20:33:17] Error in run 98: Run already exists in server. Run id(s): {8923723}
[2018-04-11 20:33:17] Started run 106 on task 45, dataset 'splice'.
[2018-04-11 20:33:17] Error in run 101: Run already exists in server. Run id(s): {8923731}
[2018-04-11 20:33:17] Started run 107 on task 45, dataset 'splice'.
[2018-04-11 20:33:17] Error in run 99: Run already exists in server. Run id(s): {8923726}
[2018-04-11 20:33:17] Started run 108 on task 45, dataset 'splice'.
[2018-04-11 20:33:17] Error in run 100: Run already exists in server. Run id(s): {8923727}
[2018-04-11 20:33:17] Started run 109 on task 45, dataset 'splice'.
[2018-04-11 20:33:17] Error in run 102: Run already exists in server. Run id(s): {8923725}
[2018-04-11 20:33:17] Started run 110 on task 45, dataset 'splice'.
[2018-04-11 20:33:18] Error in run 103: Run already exists in server. Run id(s): {8923733}
[2018-04-11 20:33:18] Started run 111 on task 45, dataset 'splice'.
[2018-04-11 20:33:18] Error in run 104: Run already exists in server. Run id(s): {8923734}
[2018-04-11 20:33:18] Started run 112 on task 45, dataset 'splice'.
[2018-04-11 20:33:22] Error in run 107: Run already exists in server. Run id(s): {8923738}
[2018-04-11 20:33:22] Error in run 106: Run already exists in server. Run id(s): {8923735}
[2018-04-11 20:33:22] Started run 113 on task 45, dataset 'splice'.
[2018-04-11 20:33:22] Error in run 109: Run already exists in server. Run id(s): {8923739}
[2018-04-11 20:33:22] Error in run 105: Run already exists in server. Run id(s): {8923732}
[2018-04-11 20:33:22] Started run 115 on task 45, dataset 'splice'.
[2018-04-11 20:33:22] Error in run 108: Run already exists in server. Run id(s): {8923736}
[2018-04-11 20:33:22] Started run 116 on task 45, dataset 'splice'.
[2018-04-11 20:33:22] Started run 117 on task 45, dataset 'splice'.
[2018-04-11 20:33:22] Started run 114 on task 45, dataset 'splice'.
[2018-04-11 20:33:22] Error in run 110: Run already exists in server. Run id(s): {8923740}
[2018-04-11 20:33:22] Started run 118 on task 45, dataset 'splice'.
[2018-04-11 20:33:22] Error in run 111: Run already exists in server. Run id(s): {8923741}
[2018-04-11 20:33:22] Started run 119 on task 45, dataset 'splice'.
[2018-04-11 20:33:23] Error in run 112: Run already exists in server. Run id(s): {8923742}
[2018-04-11 20:33:23] Started run 120 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Error in run 115: Run already exists in server. Run id(s): {8923747}
[2018-04-11 20:33:27] Error in run 113: Run already exists in server. Run id(s): {8923743}
[2018-04-11 20:33:27] Error in run 114: Run already exists in server. Run id(s): {8923744}
[2018-04-11 20:33:27] Error in run 118: Run already exists in server. Run id(s): {8923750}
[2018-04-11 20:33:27] Started run 121 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Error in run 117: Run already exists in server. Run id(s): {8923749}
[2018-04-11 20:33:27] Error in run 116: Run already exists in server. Run id(s): {8923745}
[2018-04-11 20:33:27] Started run 124 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Started run 122 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Started run 125 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Started run 123 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Started run 126 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Error in run 119: Run already exists in server. Run id(s): {8923748}
[2018-04-11 20:33:27] Started run 127 on task 45, dataset 'splice'.
[2018-04-11 20:33:27] Error in run 120: Run already exists in server. Run id(s): {8923751}
[2018-04-11 20:33:27] Started run 128 on task 45, dataset 'splice'.
[2018-04-11 20:33:31] Error in run 122: Run already exists in server. Run id(s): {8923752}
[2018-04-11 20:33:31] Error in run 124: Run already exists in server. Run id(s): {8923756}
[2018-04-11 20:33:31] Error in run 121: Run already exists in server. Run id(s): {8923755}
[2018-04-11 20:33:31] Started run 129 on task 45, dataset 'splice'.
[2018-04-11 20:33:31] Error in run 127: Run already exists in server. Run id(s): {8923760}
[2018-04-11 20:33:31] Error in run 123: Run already exists in server. Run id(s): {8923757}
[2018-04-11 20:33:31] Started run 131 on task 45, dataset 'splice'.
[2018-04-11 20:33:31] Error in run 125: Run already exists in server. Run id(s): {8923758}
[2018-04-11 20:33:31] Error in run 126: Run already exists in server. Run id(s): {8923761}
[2018-04-11 20:33:31] Started run 132 on task 45, dataset 'splice'.
[2018-04-11 20:33:31] Started run 135 on task 45, dataset 'splice'.
[2018-04-11 20:33:31] Started run 134 on task 45, dataset 'splice'.
[2018-04-11 20:33:31] Started run 133 on task 45, dataset 'splice'.
[2018-04-11 20:33:31] Started run 130 on task 45, dataset 'splice'.
[2018-04-11 20:33:32] Error in run 128: Run already exists in server. Run id(s): {8923759}
[2018-04-11 20:33:32] Started run 136 on task 45, dataset 'splice'.
[2018-04-11 20:33:36] Error in run 129: Run already exists in server. Run id(s): {8923763}
[2018-04-11 20:33:36] Started run 137 on task 45, dataset 'splice'.
[2018-04-11 20:33:36] Error in run 131: Run already exists in server. Run id(s): {8923764}
[2018-04-11 20:33:36] Error in run 132: Run already exists in server. Run id(s): {8923765}
[2018-04-11 20:33:36] Started run 138 on task 45, dataset 'splice'.
[2018-04-11 20:33:36] Error in run 133: Run already exists in server. Run id(s): {8923767}
[2018-04-11 20:33:36] Error in run 130: Run already exists in server. Run id(s): {8923762}
[2018-04-11 20:33:36] Error in run 135: Run already exists in server. Run id(s): {8923770}
[2018-04-11 20:33:36] Started run 139 on task 45, dataset 'splice'.
[2018-04-11 20:33:36] Error in run 134: Run already exists in server. Run id(s): {8923768}
[2018-04-11 20:33:36] Started run 140 on task 45, dataset 'splice'.
[2018-04-11 20:33:36] Started run 143 on task 45, dataset 'splice'.
[2018-04-11 20:33:36] Started run 141 on task 45, dataset 'splice'.
[2018-04-11 20:33:36] Started run 142 on task 45, dataset 'splice'.
[2018-04-11 20:33:37] Error in run 136: Run already exists in server. Run id(s): {8923766}
[2018-04-11 20:33:37] Started run 144 on task 45, dataset 'splice'.
[2018-04-11 20:33:41] Error in run 137: Run already exists in server. Run id(s): {8923769}
[2018-04-11 20:33:41] Started run 145 on task 45, dataset 'splice'.
[2018-04-11 20:33:41] Error in run 138: Run already exists in server. Run id(s): {8923772}
[2018-04-11 20:33:41] Error in run 139: Run already exists in server. Run id(s): {8923771}
[2018-04-11 20:33:41] Error in run 140: Run already exists in server. Run id(s): {8923775}
[2018-04-11 20:33:41] Started run 146 on task 45, dataset 'splice'.
[2018-04-11 20:33:41] Started run 148 on task 45, dataset 'splice'.
[2018-04-11 20:33:41] Started run 147 on task 45, dataset 'splice'.
[2018-04-11 20:33:41] Error in run 141: Run already exists in server. Run id(s): {8923773}
[2018-04-11 20:33:41] Error in run 142: Run already exists in server. Run id(s): {8923776}
[2018-04-11 20:33:41] Error in run 143: Run already exists in server. Run id(s): {8923778}
[2018-04-11 20:33:41] Started run 149 on task 45, dataset 'splice'.
[2018-04-11 20:33:41] Started run 151 on task 45, dataset 'splice'.
[2018-04-11 20:33:41] Started run 150 on task 45, dataset 'splice'.
[2018-04-11 20:33:42] Error in run 144: Run already exists in server. Run id(s): {8923779}
[2018-04-11 20:33:42] Started run 152 on task 45, dataset 'splice'.
[2018-04-11 20:33:45] Error in run 147: Run already exists in server. Run id(s): {8923782}
[2018-04-11 20:33:45] Error in run 145: Run already exists in server. Run id(s): {8923781}
[2018-04-11 20:33:45] Error in run 146: Run already exists in server. Run id(s): {8923783}
[2018-04-11 20:33:45] Started run 153 on task 45, dataset 'splice'.
[2018-04-11 20:33:45] Error in run 148: Run already exists in server. Run id(s): {8923784}
[2018-04-11 20:33:45] Started run 156 on task 45, dataset 'splice'.
[2018-04-11 20:33:45] Error in run 149: Run already exists in server. Run id(s): {8923785}
[2018-04-11 20:33:45] Error in run 151: Run already exists in server. Run id(s): {8923786}
[2018-04-11 20:33:45] Started run 157 on task 45, dataset 'splice'.
[2018-04-11 20:33:45] Error in run 150: Run already exists in server. Run id(s): {8923788}
[2018-04-11 20:33:45] Started run 158 on task 45, dataset 'splice'.
[2018-04-11 20:33:45] Started run 154 on task 45, dataset 'splice'.
[2018-04-11 20:33:45] Started run 159 on task 45, dataset 'splice'.
[2018-04-11 20:33:45] Started run 155 on task 45, dataset 'splice'.
[2018-04-11 20:33:46] Error in run 152: Run already exists in server. Run id(s): {8923787}
[2018-04-11 20:33:46] Started run 160 on task 45, dataset 'splice'.
[2018-04-11 20:33:50] Error in run 154: Run already exists in server. Run id(s): {8923792}
[2018-04-11 20:33:50] Error in run 153: Run already exists in server. Run id(s): {8923789}
[2018-04-11 20:33:50] Error in run 155: Run already exists in server. Run id(s): {8923790}
[2018-04-11 20:33:50] Error in run 157: Run already exists in server. Run id(s): {8923791}
[2018-04-11 20:33:50] Started run 161 on task 45, dataset 'splice'.
[2018-04-11 20:33:50] Error in run 158: Run already exists in server. Run id(s): {8923794}
[2018-04-11 20:33:50] Error in run 156: Run already exists in server. Run id(s): {8923793}
[2018-04-11 20:33:50] Error in run 159: Run already exists in server. Run id(s): {8923795}
[2018-04-11 20:33:50] Started run 165 on task 45, dataset 'splice'.
[2018-04-11 20:33:50] Started run 166 on task 45, dataset 'splice'.
[2018-04-11 20:33:50] Started run 167 on task 45, dataset 'splice'.
[2018-04-11 20:33:50] Started run 162 on task 45, dataset 'splice'.
[2018-04-11 20:33:50] Started run 163 on task 45, dataset 'splice'.
[2018-04-11 20:33:50] Started run 164 on task 45, dataset 'splice'.
[2018-04-11 20:33:51] Error in run 160: Run already exists in server. Run id(s): {8923796}
[2018-04-11 20:33:51] Started run 168 on task 45, dataset 'splice'.
[2018-04-11 20:33:55] Error in run 167: Run already exists in server. Run id(s): {8923804}
[2018-04-11 20:33:55] Error in run 162: Run already exists in server. Run id(s): {8923797}
[2018-04-11 20:33:55] Error in run 164: Run already exists in server. Run id(s): {8923800}
[2018-04-11 20:33:55] Error in run 163: Run already exists in server. Run id(s): {8923799}
[2018-04-11 20:33:55] Started run 169 on task 45, dataset 'splice'.
[2018-04-11 20:33:55] Error in run 166: Run already exists in server. Run id(s): {8923805}
[2018-04-11 20:33:55] Error in run 165: Run already exists in server. Run id(s): {8923803}
[2018-04-11 20:33:55] Error in run 161: Run already exists in server. Run id(s): {8923798}
[2018-04-11 20:33:55] Started run 173 on task 45, dataset 'splice'.
[2018-04-11 20:33:55] Started run 174 on task 45, dataset 'splice'.
[2018-04-11 20:33:55] Started run 175 on task 45, dataset 'splice'.
[2018-04-11 20:33:55] Started run 172 on task 45, dataset 'splice'.
[2018-04-11 20:33:55] Started run 170 on task 45, dataset 'splice'.
[2018-04-11 20:33:55] Started run 171 on task 45, dataset 'splice'.
[2018-04-11 20:33:56] Error in run 168: Run already exists in server. Run id(s): {8923806}
[2018-04-11 20:33:56] Started run 176 on task 45, dataset 'splice'.
[2018-04-11 20:33:59] Error in run 174: Run already exists in server. Run id(s): {8923813}
[2018-04-11 20:33:59] Error in run 175: Run already exists in server. Run id(s): {8923815}
[2018-04-11 20:33:59] Started run 177 on task 45, dataset 'splice'.
[2018-04-11 20:33:59] Error in run 169: Run already exists in server. Run id(s): {8923809}
[2018-04-11 20:33:59] Error in run 173: Run already exists in server. Run id(s): {8923812}
[2018-04-11 20:33:59] Started run 178 on task 45, dataset 'splice'.
[2018-04-11 20:33:59] Error in run 171: Run already exists in server. Run id(s): {8923810}
[2018-04-11 20:33:59] Error in run 172: Run already exists in server. Run id(s): {8923811}
[2018-04-11 20:33:59] Error in run 170: Run already exists in server. Run id(s): {8923807}
[2018-04-11 20:33:59] Started run 179 on task 45, dataset 'splice'.
[2018-04-11 20:33:59] Started run 181 on task 45, dataset 'splice'.
[2018-04-11 20:33:59] Started run 182 on task 45, dataset 'splice'.
[2018-04-11 20:33:59] Started run 180 on task 45, dataset 'splice'.
[2018-04-11 20:33:59] Started run 183 on task 45, dataset 'splice'.
[2018-04-11 20:34:00] Error in run 176: Run already exists in server. Run id(s): {8923814}
[2018-04-11 20:34:00] Started run 184 on task 45, dataset 'splice'.
[2018-04-11 20:34:04] Error in run 180: Run already exists in server. Run id(s): {8923822}
[2018-04-11 20:34:04] Error in run 178: Run already exists in server. Run id(s): {8923821}
[2018-04-11 20:34:04] Error in run 177: Run already exists in server. Run id(s): {8923817}
[2018-04-11 20:34:04] Started run 185 on task 45, dataset 'splice'.
[2018-04-11 20:34:04] Started run 187 on task 45, dataset 'splice'.
[2018-04-11 20:34:04] Error in run 181: Run already exists in server. Run id(s): {8923823}
[2018-04-11 20:34:04] Error in run 183: Run already exists in server. Run id(s): {8923824}
[2018-04-11 20:34:04] Started run 188 on task 45, dataset 'splice'.
[2018-04-11 20:34:04] Error in run 182: Run already exists in server. Run id(s): {8923826}
[2018-04-11 20:34:04] Started run 189 on task 45, dataset 'splice'.
[2018-04-11 20:34:04] Error in run 179: Run already exists in server. Run id(s): {8923820}
[2018-04-11 20:34:04] Started run 191 on task 45, dataset 'splice'.
[2018-04-11 20:34:04] Started run 186 on task 45, dataset 'splice'.
[2018-04-11 20:34:04] Started run 190 on task 45, dataset 'splice'.
[2018-04-11 20:34:05] Error in run 184: Run already exists in server. Run id(s): {8923827}
[2018-04-11 20:34:05] Started run 192 on task 45, dataset 'splice'.
[2018-04-11 20:34:09] Error in run 191: Run already exists in server. Run id(s): {8923834}
[2018-04-11 20:34:09] Started run 193 on task 45, dataset 'splice'.
[2018-04-11 20:34:09] Error in run 185: Run already exists in server. Run id(s): {8923828}
[2018-04-11 20:34:09] Error in run 187: Run already exists in server. Run id(s): {8923830}
[2018-04-11 20:34:09] Started run 194 on task 45, dataset 'splice'.
[2018-04-11 20:34:09] Error in run 189: Run already exists in server. Run id(s): {8923831}
[2018-04-11 20:34:09] Error in run 188: Run already exists in server. Run id(s): {8923832}
[2018-04-11 20:34:09] Started run 195 on task 45, dataset 'splice'.
[2018-04-11 20:34:09] Started run 196 on task 45, dataset 'splice'.
[2018-04-11 20:34:09] Error in run 190: Run already exists in server. Run id(s): {8923833}
[2018-04-11 20:34:09] Started run 197 on task 45, dataset 'splice'.
[2018-04-11 20:34:09] Started run 198 on task 45, dataset 'splice'.
[2018-04-11 20:34:09] Error in run 186: Run already exists in server. Run id(s): {8923829}
[2018-04-11 20:34:09] Started run 199 on task 45, dataset 'splice'.
[2018-04-11 20:34:10] Error in run 192: Run already exists in server. Run id(s): {8923835}
[2018-04-11 20:34:10] Started run 200 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Error in run 199: Run already exists in server. Run id(s): {8923843}
[2018-04-11 20:34:14] Started run 201 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Error in run 195: Run already exists in server. Run id(s): {8923841}
[2018-04-11 20:34:14] Started run 202 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Error in run 196: Run already exists in server. Run id(s): {8923839}
[2018-04-11 20:34:14] Error in run 194: Run already exists in server. Run id(s): {8923840}
[2018-04-11 20:34:14] Error in run 198: Run already exists in server. Run id(s): {8923844}
[2018-04-11 20:34:14] Error in run 197: Run already exists in server. Run id(s): {8923842}
[2018-04-11 20:34:14] Started run 203 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Error in run 193: Run already exists in server. Run id(s): {8923836}
[2018-04-11 20:34:14] Started run 207 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Started run 204 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Started run 205 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Started run 206 on task 45, dataset 'splice'.
[2018-04-11 20:34:14] Error in run 200: Run already exists in server. Run id(s): {8923845}
[2018-04-11 20:34:14] Started run 208 on task 45, dataset 'splice'.
[2018-04-11 20:34:18] Error in run 203: Run already exists in server. Run id(s): {8923848}
[2018-04-11 20:34:18] Error in run 207: Run already exists in server. Run id(s): {8923852}
[2018-04-11 20:34:18] Error in run 202: Run already exists in server. Run id(s): {8923847}
[2018-04-11 20:34:18] Started run 209 on task 45, dataset 'splice'.
[2018-04-11 20:34:18] Error in run 201: Run already exists in server. Run id(s): {8923846}
[2018-04-11 20:34:18] Error in run 204: Run already exists in server. Run id(s): {8923849}
[2018-04-11 20:34:18] Error in run 205: Run already exists in server. Run id(s): {8923850}
[2018-04-11 20:34:18] Error in run 206: Run already exists in server. Run id(s): {8923851}
[2018-04-11 20:34:18] Started run 210 on task 45, dataset 'splice'.
[2018-04-11 20:34:18] Started run 213 on task 45, dataset 'splice'.
[2018-04-11 20:34:18] Started run 214 on task 45, dataset 'splice'.
[2018-04-11 20:34:18] Started run 211 on task 45, dataset 'splice'.
[2018-04-11 20:34:18] Started run 215 on task 45, dataset 'splice'.
[2018-04-11 20:34:18] Started run 212 on task 45, dataset 'splice'.
[2018-04-11 20:34:19] Error in run 208: Run already exists in server. Run id(s): {8923853}
[2018-04-11 20:34:19] Started run 216 on task 45, dataset 'splice'.
[2018-04-11 20:34:23] Error in run 213: Run already exists in server. Run id(s): {8923858}
[2018-04-11 20:34:23] Error in run 214: Run already exists in server. Run id(s): {8923861}
[2018-04-11 20:34:23] Error in run 212: Run already exists in server. Run id(s): {8923856}
[2018-04-11 20:34:23] Error in run 210: Run already exists in server. Run id(s): {8923857}
[2018-04-11 20:34:23] Started run 217 on task 45, dataset 'splice'.
[2018-04-11 20:34:23] Error in run 209: Run already exists in server. Run id(s): {8923855}
[2018-04-11 20:34:23] Error in run 215: Run already exists in server. Run id(s): {8923860}
[2018-04-11 20:34:23] Started run 220 on task 45, dataset 'splice'.
[2018-04-11 20:34:23] Error in run 211: Run already exists in server. Run id(s): {8923859}
[2018-04-11 20:34:23] Started run 221 on task 45, dataset 'splice'.
[2018-04-11 20:34:23] Started run 222 on task 45, dataset 'splice'.
[2018-04-11 20:34:23] Started run 219 on task 45, dataset 'splice'.
[2018-04-11 20:34:23] Started run 223 on task 45, dataset 'splice'.
[2018-04-11 20:34:23] Started run 218 on task 45, dataset 'splice'.
[2018-04-11 20:34:24] Error in run 216: Run already exists in server. Run id(s): {8923863}
[2018-04-11 20:34:24] Started run 224 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Error in run 219: Run already exists in server. Run id(s): {8923867}
[2018-04-11 20:34:28] Error in run 218: Run already exists in server. Run id(s): {8923866}
[2018-04-11 20:34:28] Started run 225 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Error in run 217: Run already exists in server. Run id(s): {8923865}
[2018-04-11 20:34:28] Started run 226 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Error in run 222: Run already exists in server. Run id(s): {8923871}
[2018-04-11 20:34:28] Error in run 223: Run already exists in server. Run id(s): {8923872}
[2018-04-11 20:34:28] Error in run 221: Run already exists in server. Run id(s): {8923869}
[2018-04-11 20:34:28] Started run 227 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Error in run 220: Run already exists in server. Run id(s): {8923868}
[2018-04-11 20:34:28] Started run 231 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Started run 228 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Started run 229 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Started run 230 on task 45, dataset 'splice'.
[2018-04-11 20:34:28] Error in run 224: Run already exists in server. Run id(s): {8923873}
[2018-04-11 20:34:28] Started run 232 on task 45, dataset 'splice'.
[2018-04-11 20:34:32] Error in run 230: Run already exists in server. Run id(s): {8923878}
[2018-04-11 20:34:32] Started run 233 on task 45, dataset 'splice'.
[2018-04-11 20:34:32] Error in run 229: Run already exists in server. Run id(s): {8923876}
[2018-04-11 20:34:32] Started run 234 on task 45, dataset 'splice'.
[2018-04-11 20:34:32] Error in run 226: Run already exists in server. Run id(s): {8923875}
[2018-04-11 20:34:32] Started run 235 on task 45, dataset 'splice'.
[2018-04-11 20:34:32] Error in run 227: Run already exists in server. Run id(s): {8923877}
[2018-04-11 20:34:32] Error in run 231: Run already exists in server. Run id(s): {8923880}
[2018-04-11 20:34:32] Started run 236 on task 45, dataset 'splice'.
[2018-04-11 20:34:32] Started run 237 on task 45, dataset 'splice'.
[2018-04-11 20:34:33] Error in run 225: Run already exists in server. Run id(s): {8923870}
[2018-04-11 20:34:33] Started run 238 on task 45, dataset 'splice'.
[2018-04-11 20:34:33] Error in run 228: Run already exists in server. Run id(s): {8923874}
[2018-04-11 20:34:33] Started run 239 on task 45, dataset 'splice'.
[2018-04-11 20:34:33] Error in run 232: Run already exists in server. Run id(s): {8923882}
[2018-04-11 20:34:33] Started run 240 on task 45, dataset 'splice'.
[2018-04-11 20:34:37] Error in run 233: Run already exists in server. Run id(s): {8923881}
[2018-04-11 20:34:37] Started run 241 on task 45, dataset 'splice'.
[2018-04-11 20:34:37] Error in run 234: Run already exists in server. Run id(s): {8923879}
[2018-04-11 20:34:37] Started run 242 on task 45, dataset 'splice'.
[2018-04-11 20:34:37] Error in run 236: Run already exists in server. Run id(s): {8923884}
[2018-04-11 20:34:37] Error in run 235: Run already exists in server. Run id(s): {8923883}
[2018-04-11 20:34:37] Error in run 237: Run already exists in server. Run id(s): {8923886}
[2018-04-11 20:34:37] Started run 243 on task 45, dataset 'splice'.
[2018-04-11 20:34:37] Started run 244 on task 45, dataset 'splice'.
[2018-04-11 20:34:37] Error in run 238: Run already exists in server. Run id(s): {8923885}
[2018-04-11 20:34:37] Started run 246 on task 45, dataset 'splice'.
[2018-04-11 20:34:37] Started run 245 on task 45, dataset 'splice'.
[2018-04-11 20:34:37] Error in run 239: Run already exists in server. Run id(s): {8923889}
[2018-04-11 20:34:37] Started run 247 on task 45, dataset 'splice'.
[2018-04-11 20:34:38] Error in run 240: Run already exists in server. Run id(s): {8923887}
[2018-04-11 20:34:38] Started run 248 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Error in run 241: Run already exists in server. Run id(s): {8923890}
[2018-04-11 20:34:42] Started run 249 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Error in run 243: Run already exists in server. Run id(s): {8923891}
[2018-04-11 20:34:42] Started run 250 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Error in run 242: Run already exists in server. Run id(s): {8923888}
[2018-04-11 20:34:42] Error in run 244: Run already exists in server. Run id(s): {8923892}
[2018-04-11 20:34:42] Error in run 246: Run already exists in server. Run id(s): {8923896}
[2018-04-11 20:34:42] Started run 251 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Started run 252 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Error in run 247: Run already exists in server. Run id(s): {8923895}
[2018-04-11 20:34:42] Error in run 245: Run already exists in server. Run id(s): {8923894}
[2018-04-11 20:34:42] Started run 254 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Started run 255 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Started run 253 on task 45, dataset 'splice'.
[2018-04-11 20:34:42] Error in run 248: Run already exists in server. Run id(s): {8923897}
[2018-04-11 20:34:42] Started run 256 on task 45, dataset 'splice'.
[2018-04-11 20:34:46] Error in run 249: Run already exists in server. Run id(s): {8923901}
[2018-04-11 20:34:46] Started run 257 on task 45, dataset 'splice'.
[2018-04-11 20:34:46] Error in run 250: Run already exists in server. Run id(s): {8923902}
[2018-04-11 20:34:46] Started run 258 on task 45, dataset 'splice'.
[2018-04-11 20:34:46] Error in run 252: Run already exists in server. Run id(s): {8923903}
[2018-04-11 20:34:46] Started run 259 on task 45, dataset 'splice'.
[2018-04-11 20:34:46] Error in run 251: Run already exists in server. Run id(s): {8923898}
[2018-04-11 20:34:46] Error in run 253: Run already exists in server. Run id(s): {8923905}
[2018-04-11 20:34:46] Started run 260 on task 45, dataset 'splice'.
[2018-04-11 20:34:46] Started run 261 on task 45, dataset 'splice'.
[2018-04-11 20:34:46] Error in run 254: Run already exists in server. Run id(s): {8923907}
[2018-04-11 20:34:46] Error in run 255: Run already exists in server. Run id(s): {8923906}
[2018-04-11 20:34:46] Started run 262 on task 45, dataset 'splice'.
[2018-04-11 20:34:46] Started run 263 on task 45, dataset 'splice'.
[2018-04-11 20:34:47] Error in run 256: Run already exists in server. Run id(s): {8923904}
[2018-04-11 20:34:47] Started run 264 on task 45, dataset 'splice'.
[2018-04-11 20:34:51] Error in run 257: Run already exists in server. Run id(s): {8923910}
[2018-04-11 20:34:51] Started run 265 on task 45, dataset 'splice'.
[2018-04-11 20:34:51] Error in run 258: Run already exists in server. Run id(s): {8923911}
[2018-04-11 20:34:51] Started run 266 on task 45, dataset 'splice'.
[2018-04-11 20:34:51] Error in run 263: Run already exists in server. Run id(s): {8923917}
[2018-04-11 20:34:51] Error in run 260: Run already exists in server. Run id(s): {8923913}
[2018-04-11 20:34:51] Error in run 261: Run already exists in server. Run id(s): {8923912}
[2018-04-11 20:34:51] Error in run 262: Run already exists in server. Run id(s): {8923914}
[2018-04-11 20:34:51] Error in run 259: Run already exists in server. Run id(s): {8923909}
[2018-04-11 20:34:51] Started run 267 on task 45, dataset 'splice'.
[2018-04-11 20:34:51] Started run 269 on task 45, dataset 'splice'.
[2018-04-11 20:34:51] Started run 268 on task 45, dataset 'splice'.
[2018-04-11 20:34:51] Started run 270 on task 45, dataset 'splice'.
[2018-04-11 20:34:51] Started run 271 on task 45, dataset 'splice'.
[2018-04-11 20:34:52] Error in run 264: Run already exists in server. Run id(s): {8923918}
[2018-04-11 20:34:52] Started run 272 on task 45, dataset 'splice'.
[2018-04-11 20:34:55] Error in run 265: Run already exists in server. Run id(s): {8923916}
[2018-04-11 20:34:55] Started run 273 on task 45, dataset 'splice'.
[2018-04-11 20:34:55] Error in run 266: Run already exists in server. Run id(s): {8923920}
[2018-04-11 20:34:55] Started run 274 on task 45, dataset 'splice'.
[2018-04-11 20:34:56] Error in run 267: Run already exists in server. Run id(s): {8923921}
[2018-04-11 20:34:56] Started run 275 on task 45, dataset 'splice'.
[2018-04-11 20:34:56] Error in run 271: Run already exists in server. Run id(s): {8923925}
[2018-04-11 20:34:56] Error in run 269: Run already exists in server. Run id(s): {8923922}
[2018-04-11 20:34:56] Error in run 270: Run already exists in server. Run id(s): {8923924}
[2018-04-11 20:34:56] Error in run 268: Run already exists in server. Run id(s): {8923919}
[2018-04-11 20:34:56] Started run 276 on task 45, dataset 'splice'.
[2018-04-11 20:34:56] Started run 278 on task 45, dataset 'splice'.
[2018-04-11 20:34:56] Started run 277 on task 45, dataset 'splice'.
[2018-04-11 20:34:56] Started run 279 on task 45, dataset 'splice'.
[2018-04-11 20:34:56] Error in run 272: Run already exists in server. Run id(s): {8923923}
[2018-04-11 20:34:56] Started run 280 on task 45, dataset 'splice'.
[2018-04-11 20:35:00] Error in run 273: Run already exists in server. Run id(s): {8923927}
[2018-04-11 20:35:00] Error in run 274: Run already exists in server. Run id(s): {8923930}
[2018-04-11 20:35:00] Started run 281 on task 45, dataset 'splice'.
[2018-04-11 20:35:00] Started run 282 on task 45, dataset 'splice'.
[2018-04-11 20:35:00] Error in run 275: Run already exists in server. Run id(s): {8923931}
[2018-04-11 20:35:00] Started run 283 on task 45, dataset 'splice'.
[2018-04-11 20:35:00] Error in run 278: Run already exists in server. Run id(s): {8923937}
[2018-04-11 20:35:00] Error in run 276: Run already exists in server. Run id(s): {8923933}
[2018-04-11 20:35:00] Error in run 279: Run already exists in server. Run id(s): {8923936}
[2018-04-11 20:35:00] Error in run 277: Run already exists in server. Run id(s): {8923929}
[2018-04-11 20:35:00] Started run 284 on task 45, dataset 'splice'.
[2018-04-11 20:35:00] Started run 287 on task 45, dataset 'splice'.
[2018-04-11 20:35:00] Started run 286 on task 45, dataset 'splice'.
[2018-04-11 20:35:00] Started run 285 on task 45, dataset 'splice'.
[2018-04-11 20:35:01] Error in run 280: Run already exists in server. Run id(s): {8923938}
[2018-04-11 20:35:01] Started run 288 on task 45, dataset 'splice'.
[2018-04-11 20:35:04] Error in run 282: Run already exists in server. Run id(s): {8923939}
[2018-04-11 20:35:04] Error in run 281: Run already exists in server. Run id(s): {8923934}
[2018-04-11 20:35:04] Started run 289 on task 45, dataset 'splice'.
[2018-04-11 20:35:04] Started run 290 on task 45, dataset 'splice'.
[2018-04-11 20:35:05] Error in run 283: Run already exists in server. Run id(s): {8923941}
[2018-04-11 20:35:05] Started run 291 on task 45, dataset 'splice'.
[2018-04-11 20:35:05] Error in run 284: Run already exists in server. Run id(s): {8923940}
[2018-04-11 20:35:05] Error in run 286: Run already exists in server. Run id(s): {8923944, 9014711}
[2018-04-11 20:35:05] Error in run 285: Run already exists in server. Run id(s): {8923942}
[2018-04-11 20:35:05] Started run 292 on task 45, dataset 'splice'.
[2018-04-11 20:35:05] Error in run 288: Run already exists in server. Run id(s): {8923947}
[2018-04-11 20:35:05] Started run 294 on task 45, dataset 'splice'.
[2018-04-11 20:35:05] Error in run 287: Run already exists in server. Run id(s): {8923946}
[2018-04-11 20:35:05] Started run 296 on task 45, dataset 'splice'.
[2018-04-11 20:35:05] Started run 295 on task 45, dataset 'splice'.
[2018-04-11 20:35:05] Started run 293 on task 45, dataset 'splice'.
[2018-04-11 20:35:09] Error in run 289: Run already exists in server. Run id(s): {8923945}
[2018-04-11 20:35:09] Error in run 290: Run already exists in server. Run id(s): {8923950}
[2018-04-11 20:35:09] Started run 297 on task 45, dataset 'splice'.
[2018-04-11 20:35:09] Started run 298 on task 45, dataset 'splice'.
[2018-04-11 20:35:09] Error in run 291: Run already exists in server. Run id(s): {8923951}
[2018-04-11 20:35:09] Started run 299 on task 45, dataset 'splice'.
[2018-04-11 20:35:10] Error in run 295: Run already exists in server. Run id(s): {8923954}
[2018-04-11 20:35:10] Error in run 294: Run already exists in server. Run id(s): {8923953}
[2018-04-11 20:35:10] Error in run 292: Run already exists in server. Run id(s): {8923952}
[2018-04-11 20:35:10] Started run 300 on task 45, dataset 'splice'.
[2018-04-11 20:35:10] Error in run 293: Run already exists in server. Run id(s): {8923949}
[2018-04-11 20:35:10] Error in run 296: Run already exists in server. Run id(s): {8923956}
[2018-04-11 20:35:10] Started run 301 on task 45, dataset 'splice'.
[2018-04-11 20:35:10] Started run 303 on task 45, dataset 'splice'.
[2018-04-11 20:35:10] Started run 304 on task 45, dataset 'splice'.
[2018-04-11 20:35:10] Started run 302 on task 45, dataset 'splice'.
[2018-04-11 20:35:14] Error in run 299: Run already exists in server. Run id(s): {8923961}
[2018-04-11 20:35:14] Error in run 297: Run already exists in server. Run id(s): {8923957}
[2018-04-11 20:35:14] Started run 305 on task 45, dataset 'splice'.
[2018-04-11 20:35:14] Error in run 298: Run already exists in server. Run id(s): {8923958}
[2018-04-11 20:35:14] Started run 306 on task 45, dataset 'splice'.
[2018-04-11 20:35:14] Started run 307 on task 45, dataset 'splice'.
[2018-04-11 20:35:14] Error in run 302: Run already exists in server. Run id(s): {8923965}
[2018-04-11 20:35:14] Started run 308 on task 45, dataset 'splice'.
[2018-04-11 20:35:14] Error in run 304: Run already exists in server. Run id(s): {8923967}
[2018-04-11 20:35:14] Error in run 301: Run already exists in server. Run id(s): {8923959}
[2018-04-11 20:35:14] Error in run 300: Run already exists in server. Run id(s): {8923964}
[2018-04-11 20:35:14] Started run 309 on task 45, dataset 'splice'.
[2018-04-11 20:35:14] Started run 310 on task 45, dataset 'splice'.
[2018-04-11 20:35:14] Started run 311 on task 45, dataset 'splice'.
[2018-04-11 20:35:15] Error in run 303: Run already exists in server. Run id(s): {8923966}
[2018-04-11 20:35:15] Started run 312 on task 45, dataset 'splice'.
[2018-04-11 20:35:18] Error in run 305: Run already exists in server. Run id(s): {8923968}
[2018-04-11 20:35:18] Started run 313 on task 45, dataset 'splice'.
[2018-04-11 20:35:18] Error in run 307: Run already exists in server. Run id(s): {8923971}
[2018-04-11 20:35:18] Error in run 306: Run already exists in server. Run id(s): {8923972}
[2018-04-11 20:35:18] Started run 314 on task 45, dataset 'splice'.
[2018-04-11 20:35:18] Started run 315 on task 45, dataset 'splice'.
[2018-04-11 20:35:19] Error in run 308: Run already exists in server. Run id(s): {8923970}
[2018-04-11 20:35:19] Started run 316 on task 45, dataset 'splice'.
[2018-04-11 20:35:19] Error in run 312: Run already exists in server. Run id(s): {8923978}
[2018-04-11 20:35:19] Started run 317 on task 45, dataset 'splice'.
[2018-04-11 20:35:19] Error in run 311: Run already exists in server. Run id(s): {8923975}
[2018-04-11 20:35:19] Error in run 309: Run already exists in server. Run id(s): {8923973}
[2018-04-11 20:35:19] Error in run 310: Run already exists in server. Run id(s): {8923977}
[2018-04-11 20:35:19] Started run 318 on task 45, dataset 'splice'.
[2018-04-11 20:35:19] Started run 320 on task 45, dataset 'splice'.
[2018-04-11 20:35:19] Started run 319 on task 45, dataset 'splice'.
[2018-04-11 20:35:23] Error in run 313: Run already exists in server. Run id(s): {8923976}
[2018-04-11 20:35:23] Started run 321 on task 45, dataset 'splice'.
[2018-04-11 20:35:23] Error in run 315: Run already exists in server. Run id(s): {8923983}
[2018-04-11 20:35:23] Error in run 314: Run already exists in server. Run id(s): {8923979}
[2018-04-11 20:35:23] Started run 322 on task 45, dataset 'splice'.
[2018-04-11 20:35:23] Started run 323 on task 45, dataset 'splice'.
[2018-04-11 20:35:23] Error in run 316: Run already exists in server. Run id(s): {8923985}
[2018-04-11 20:35:23] Started run 324 on task 45, dataset 'splice'.
[2018-04-11 20:35:24] Error in run 317: Run already exists in server. Run id(s): {8923986}
[2018-04-11 20:35:24] Started run 325 on task 45, dataset 'splice'.
[2018-04-11 20:35:24] Error in run 320: Run already exists in server. Run id(s): {8923987}
[2018-04-11 20:35:24] Error in run 318: Run already exists in server. Run id(s): {8923982}
[2018-04-11 20:35:24] Started run 326 on task 45, dataset 'splice'.
[2018-04-11 20:35:24] Error in run 319: Run already exists in server. Run id(s): {8923989}
[2018-04-11 20:35:24] Started run 327 on task 45, dataset 'splice'.
[2018-04-11 20:35:24] Started run 328 on task 45, dataset 'splice'.
[2018-04-11 20:35:27] Error in run 321: Run already exists in server. Run id(s): {8923991}
[2018-04-11 20:35:27] Started run 329 on task 45, dataset 'splice'.
[2018-04-11 20:35:28] Error in run 322: Run already exists in server. Run id(s): {8923990}
[2018-04-11 20:35:28] Started run 330 on task 45, dataset 'splice'.
[2018-04-11 20:35:28] Error in run 323: Run already exists in server. Run id(s): {8923992}
[2018-04-11 20:35:28] Started run 331 on task 45, dataset 'splice'.
[2018-04-11 20:35:28] Error in run 324: Run already exists in server. Run id(s): {8923994}
[2018-04-11 20:35:28] Started run 332 on task 45, dataset 'splice'.
[2018-04-11 20:35:28] Error in run 325: Run already exists in server. Run id(s): {8923993}
[2018-04-11 20:35:28] Started run 333 on task 45, dataset 'splice'.
[2018-04-11 20:35:29] Error in run 328: Run already exists in server. Run id(s): {8923998}
[2018-04-11 20:35:29] Started run 334 on task 45, dataset 'splice'.
[2018-04-11 20:35:29] Error in run 327: Run already exists in server. Run id(s): {8923997}
[2018-04-11 20:35:29] Error in run 326: Run already exists in server. Run id(s): {8923996}
[2018-04-11 20:35:29] Started run 335 on task 45, dataset 'splice'.
[2018-04-11 20:35:29] Started run 336 on task 45, dataset 'splice'.
[2018-04-11 20:35:32] Error in run 329: Run already exists in server. Run id(s): {8923995}
[2018-04-11 20:35:32] Started run 337 on task 45, dataset 'splice'.
[2018-04-11 20:35:32] Error in run 330: Run already exists in server. Run id(s): {8923999}
[2018-04-11 20:35:32] Started run 338 on task 45, dataset 'splice'.
[2018-04-11 20:35:33] Error in run 332: Run already exists in server. Run id(s): {8924002}
[2018-04-11 20:35:33] Error in run 331: Run already exists in server. Run id(s): {8924001}
[2018-04-11 20:35:33] Started run 339 on task 45, dataset 'splice'.
[2018-04-11 20:35:33] Started run 340 on task 45, dataset 'splice'.
[2018-04-11 20:35:33] Error in run 333: Run already exists in server. Run id(s): {8924003}
[2018-04-11 20:35:33] Started run 341 on task 45, dataset 'splice'.
[2018-04-11 20:35:33] Error in run 334: Run already exists in server. Run id(s): {8924005}
[2018-04-11 20:35:33] Started run 342 on task 45, dataset 'splice'.
[2018-04-11 20:35:33] Error in run 336: Run already exists in server. Run id(s): {8924010}
[2018-04-11 20:35:33] Started run 343 on task 45, dataset 'splice'.
[2018-04-11 20:35:33] Error in run 335: Run already exists in server. Run id(s): {8924007}
[2018-04-11 20:35:33] Started run 344 on task 45, dataset 'splice'.
[2018-04-11 20:35:36] Error in run 337: Run already exists in server. Run id(s): {8924006}
[2018-04-11 20:35:36] Started run 345 on task 45, dataset 'splice'.
[2018-04-11 20:35:37] Error in run 338: Run already exists in server. Run id(s): {8924008}
[2018-04-11 20:35:37] Started run 346 on task 45, dataset 'splice'.
[2018-04-11 20:35:37] Error in run 339: Run already exists in server. Run id(s): {8924011}
[2018-04-11 20:35:37] Started run 347 on task 45, dataset 'splice'.
[2018-04-11 20:35:37] Error in run 340: Run already exists in server. Run id(s): {8924012}
[2018-04-11 20:35:37] Error in run 341: Run already exists in server. Run id(s): {8924014}
[2018-04-11 20:35:37] Started run 348 on task 45, dataset 'splice'.
[2018-04-11 20:35:37] Started run 349 on task 45, dataset 'splice'.
[2018-04-11 20:35:38] Error in run 342: Run already exists in server. Run id(s): {8924013}
[2018-04-11 20:35:38] Started run 350 on task 45, dataset 'splice'.
[2018-04-11 20:35:38] Error in run 343: Run already exists in server. Run id(s): {8924016}
[2018-04-11 20:35:38] Started run 351 on task 45, dataset 'splice'.
[2018-04-11 20:35:38] Error in run 344: Run already exists in server. Run id(s): {8924017}
[2018-04-11 20:35:38] Started run 352 on task 45, dataset 'splice'.
[2018-04-11 20:35:41] Error in run 345: Run already exists in server. Run id(s): {8924015}
[2018-04-11 20:35:41] Started run 353 on task 45, dataset 'splice'.
[2018-04-11 20:35:41] Error in run 346: Run already exists in server. Run id(s): {8924020}
[2018-04-11 20:35:41] Started run 354 on task 45, dataset 'splice'.
[2018-04-11 20:35:42] Error in run 348: Run already exists in server. Run id(s): {8924022}
[2018-04-11 20:35:42] Started run 355 on task 45, dataset 'splice'.
[2018-04-11 20:35:42] Error in run 347: Run already exists in server. Run id(s): {8924019}
[2018-04-11 20:35:42] Error in run 349: Run already exists in server. Run id(s): {8924021}
[2018-04-11 20:35:42] Started run 356 on task 45, dataset 'splice'.
[2018-04-11 20:35:42] Started run 357 on task 45, dataset 'splice'.
[2018-04-11 20:35:42] Error in run 350: Run already exists in server. Run id(s): {8924023}
[2018-04-11 20:35:42] Started run 358 on task 45, dataset 'splice'.
[2018-04-11 20:35:42] Error in run 351: Run already exists in server. Run id(s): {8924024}
[2018-04-11 20:35:42] Started run 359 on task 45, dataset 'splice'.
[2018-04-11 20:35:42] Error in run 352: Run already exists in server. Run id(s): {8924025}
[2018-04-11 20:35:42] Started run 360 on task 45, dataset 'splice'.
[2018-04-11 20:35:46] Error in run 353: Run already exists in server. Run id(s): {8924028}
[2018-04-11 20:35:46] Started run 361 on task 45, dataset 'splice'.
[2018-04-11 20:35:46] Error in run 354: Run already exists in server. Run id(s): {8924026}
[2018-04-11 20:35:46] Started run 362 on task 45, dataset 'splice'.
[2018-04-11 20:35:47] Error in run 356: Run already exists in server. Run id(s): {8963942}
[2018-04-11 20:35:47] Error in run 358: Run already exists in server. Run id(s): {8924030}
[2018-04-11 20:35:47] Error in run 359: Run already exists in server. Run id(s): {8924034}
[2018-04-11 20:35:47] Error in run 357: Run already exists in server. Run id(s): {8924032}
[2018-04-11 20:35:47] Error in run 355: Run already exists in server. Run id(s): {8924027}
[2018-04-11 20:35:47] Started run 363 on task 45, dataset 'splice'.
[2018-04-11 20:35:47] Started run 367 on task 45, dataset 'splice'.
[2018-04-11 20:35:47] Error in run 360: Run already exists in server. Run id(s): {8924035}
[2018-04-11 20:35:47] Started run 368 on task 45, dataset 'splice'.
[2018-04-11 20:35:47] Started run 366 on task 45, dataset 'splice'.
[2018-04-11 20:35:47] Started run 364 on task 45, dataset 'splice'.
[2018-04-11 20:35:47] Started run 365 on task 45, dataset 'splice'.
[2018-04-11 20:35:50] Error in run 361: Run already exists in server. Run id(s): {8924037}
[2018-04-11 20:35:50] Started run 369 on task 45, dataset 'splice'.
[2018-04-11 20:35:51] Error in run 362: Run already exists in server. Run id(s): {8924038}
[2018-04-11 20:35:51] Started run 370 on task 45, dataset 'splice'.
[2018-04-11 20:35:51] Error in run 363: Run already exists in server. Run id(s): {8924036}
[2018-04-11 20:35:51] Error in run 366: Run already exists in server. Run id(s): {8924042}
[2018-04-11 20:35:51] Error in run 367: Run already exists in server. Run id(s): {8924043}
[2018-04-11 20:35:51] Started run 371 on task 45, dataset 'splice'.
[2018-04-11 20:35:51] Error in run 364: Run already exists in server. Run id(s): {8924040}
[2018-04-11 20:35:51] Error in run 368: Run already exists in server. Run id(s): {8924045}
[2018-04-11 20:35:51] Error in run 365: Run already exists in server. Run id(s): {8924041}
[2018-04-11 20:35:51] Started run 372 on task 45, dataset 'splice'.
[2018-04-11 20:35:51] Started run 374 on task 45, dataset 'splice'.
[2018-04-11 20:35:51] Started run 375 on task 45, dataset 'splice'.
[2018-04-11 20:35:51] Started run 376 on task 45, dataset 'splice'.
[2018-04-11 20:35:51] Started run 373 on task 45, dataset 'splice'.
[2018-04-11 20:35:55] Error in run 369: Run already exists in server. Run id(s): {8924046}
[2018-04-11 20:35:55] Started run 377 on task 45, dataset 'splice'.
[2018-04-11 20:35:55] Error in run 370: Run already exists in server. Run id(s): {8924047}
[2018-04-11 20:35:55] Started run 378 on task 45, dataset 'splice'.
[2018-04-11 20:35:56] Error in run 371: Run already exists in server. Run id(s): {8924048}
[2018-04-11 20:35:56] Started run 379 on task 45, dataset 'splice'.
[2018-04-11 20:35:56] Error in run 376: Run already exists in server. Run id(s): {8924054}
[2018-04-11 20:35:56] Error in run 374: Run already exists in server. Run id(s): {8924053}
[2018-04-11 20:35:56] Error in run 372: Run already exists in server. Run id(s): {8924050}
[2018-04-11 20:35:56] Error in run 373: Run already exists in server. Run id(s): {8924051}
[2018-04-11 20:35:56] Error in run 375: Run already exists in server. Run id(s): {8924052}
[2018-04-11 20:35:56] Started run 380 on task 45, dataset 'splice'.
[2018-04-11 20:35:56] Started run 384 on task 45, dataset 'splice'.
[2018-04-11 20:35:56] Started run 381 on task 45, dataset 'splice'.
[2018-04-11 20:35:56] Started run 382 on task 45, dataset 'splice'.
[2018-04-11 20:35:56] Started run 383 on task 45, dataset 'splice'.
[2018-04-11 20:35:59] Error in run 377: Run already exists in server. Run id(s): {8924056}
[2018-04-11 20:35:59] Started run 385 on task 45, dataset 'splice'.
[2018-04-11 20:36:00] Error in run 378: Run already exists in server. Run id(s): {8924058}
[2018-04-11 20:36:00] Started run 386 on task 45, dataset 'splice'.
[2018-04-11 20:36:00] Error in run 379: Run already exists in server. Run id(s): {8924057}
[2018-04-11 20:36:00] Started run 387 on task 45, dataset 'splice'.
[2018-04-11 20:36:01] Error in run 382: Run already exists in server. Run id(s): {8924063}
[2018-04-11 20:36:01] Error in run 380: Run already exists in server. Run id(s): {8924060}
[2018-04-11 20:36:01] Started run 388 on task 45, dataset 'splice'.
[2018-04-11 20:36:01] Started run 389 on task 45, dataset 'splice'.
[2018-04-11 20:36:01] Error in run 384: Run already exists in server. Run id(s): {8924064}
[2018-04-11 20:36:01] Error in run 381: Run already exists in server. Run id(s): {8924062}
[2018-04-11 20:36:01] Error in run 383: Run already exists in server. Run id(s): {8924061}
[2018-04-11 20:36:01] Started run 390 on task 45, dataset 'splice'.
[2018-04-11 20:36:01] Started run 391 on task 45, dataset 'splice'.
[2018-04-11 20:36:01] Started run 392 on task 45, dataset 'splice'.
[2018-04-11 20:36:04] Error in run 385: Run already exists in server. Run id(s): {8924065}
[2018-04-11 20:36:04] Started run 393 on task 45, dataset 'splice'.
[2018-04-11 20:36:04] Error in run 386: Run already exists in server. Run id(s): {8924067}
[2018-04-11 20:36:04] Started run 394 on task 45, dataset 'splice'.
[2018-04-11 20:36:05] Error in run 387: Run already exists in server. Run id(s): {8924066}
[2018-04-11 20:36:05] Started run 395 on task 45, dataset 'splice'.
[2018-04-11 20:36:05] Error in run 391: Run already exists in server. Run id(s): {8924070}
[2018-04-11 20:36:05] Error in run 389: Run already exists in server. Run id(s): {8924071}
[2018-04-11 20:36:05] Error in run 392: Run already exists in server. Run id(s): {8924074}
[2018-04-11 20:36:05] Started run 396 on task 45, dataset 'splice'.
[2018-04-11 20:36:05] Started run 398 on task 45, dataset 'splice'.
[2018-04-11 20:36:05] Error in run 388: Run already exists in server. Run id(s): {8924068}
[2018-04-11 20:36:05] Error in run 390: Run already exists in server. Run id(s): {8924072}
[2018-04-11 20:36:05] Started run 397 on task 45, dataset 'splice'.
[2018-04-11 20:36:05] Started run 399 on task 45, dataset 'splice'.
[2018-04-11 20:36:05] Started run 400 on task 45, dataset 'splice'.
[2018-04-11 20:36:09] Error in run 393: Run already exists in server. Run id(s): {8924075}
[2018-04-11 20:36:09] Started run 401 on task 45, dataset 'splice'.
[2018-04-11 20:36:09] Error in run 394: Run already exists in server. Run id(s): {8924073}
[2018-04-11 20:36:09] Started run 402 on task 45, dataset 'splice'.
[2018-04-11 20:36:09] Error in run 395: Run already exists in server. Run id(s): {8924076}
[2018-04-11 20:36:09] Started run 403 on task 45, dataset 'splice'.
[2018-04-11 20:36:10] Error in run 397: Run already exists in server. Run id(s): {8924080}
[2018-04-11 20:36:10] Error in run 400: Run already exists in server. Run id(s): {8924085}
[2018-04-11 20:36:10] Started run 404 on task 45, dataset 'splice'.
[2018-04-11 20:36:10] Error in run 398: Run already exists in server. Run id(s): {8924081}
[2018-04-11 20:36:10] Error in run 396: Run already exists in server. Run id(s): {8924079}
[2018-04-11 20:36:10] Error in run 399: Run already exists in server. Run id(s): {8924082}
[2018-04-11 20:36:10] Started run 405 on task 45, dataset 'splice'.
[2018-04-11 20:36:10] Started run 407 on task 45, dataset 'splice'.
[2018-04-11 20:36:10] Started run 408 on task 45, dataset 'splice'.
[2018-04-11 20:36:10] Started run 406 on task 45, dataset 'splice'.
[2018-04-11 20:36:13] Error in run 401: Run already exists in server. Run id(s): {8924086}
[2018-04-11 20:36:13] Started run 409 on task 45, dataset 'splice'.
[2018-04-11 20:36:13] Error in run 402: Run already exists in server. Run id(s): {8924084}
[2018-04-11 20:36:13] Started run 410 on task 45, dataset 'splice'.
[2018-04-11 20:36:14] Error in run 403: Run already exists in server. Run id(s): {8924088}
[2018-04-11 20:36:14] Started run 411 on task 45, dataset 'splice'.
[2018-04-11 20:36:15] Error in run 408: Run already exists in server. Run id(s): {8924093}
[2018-04-11 20:36:15] Error in run 406: Run already exists in server. Run id(s): {8924089}
[2018-04-11 20:36:15] Error in run 405: Run already exists in server. Run id(s): {8924087}
[2018-04-11 20:36:15] Error in run 404: Run already exists in server. Run id(s): {8924090}
[2018-04-11 20:36:15] Started run 412 on task 45, dataset 'splice'.
[2018-04-11 20:36:15] Error in run 407: Run already exists in server. Run id(s): {8924091}
[2018-04-11 20:36:15] Started run 414 on task 45, dataset 'splice'.
[2018-04-11 20:36:15] Started run 413 on task 45, dataset 'splice'.
[2018-04-11 20:36:15] Started run 416 on task 45, dataset 'splice'.
[2018-04-11 20:36:15] Started run 415 on task 45, dataset 'splice'.
[2018-04-11 20:36:18] Error in run 409: Run already exists in server. Run id(s): {8924095}
[2018-04-11 20:36:18] Error in run 410: Run already exists in server. Run id(s): {8924094}
[2018-04-11 20:36:18] Started run 417 on task 45, dataset 'splice'.
[2018-04-11 20:36:18] Started run 418 on task 45, dataset 'splice'.
[2018-04-11 20:36:19] Error in run 411: Run already exists in server. Run id(s): {8924096}
[2018-04-11 20:36:19] Started run 419 on task 45, dataset 'splice'.
[2018-04-11 20:36:19] Error in run 413: Run already exists in server. Run id(s): {8924097}
[2018-04-11 20:36:19] Started run 420 on task 45, dataset 'splice'.
[2018-04-11 20:36:19] Error in run 412: Run already exists in server. Run id(s): {8924098}
[2018-04-11 20:36:19] Started run 421 on task 45, dataset 'splice'.
[2018-04-11 20:36:19] Error in run 414: Run already exists in server. Run id(s): {8924099}
[2018-04-11 20:36:19] Started run 422 on task 45, dataset 'splice'.
[2018-04-11 20:36:19] Error in run 415: Run already exists in server. Run id(s): {8924100}
[2018-04-11 20:36:19] Error in run 416: Run already exists in server. Run id(s): {8924102}
[2018-04-11 20:36:19] Started run 423 on task 45, dataset 'splice'.
[2018-04-11 20:36:19] Started run 424 on task 45, dataset 'splice'.
[2018-04-11 20:36:22] Error in run 417: Run already exists in server. Run id(s): {8924101}
[2018-04-11 20:36:22] Started run 425 on task 45, dataset 'splice'.
[2018-04-11 20:36:23] Error in run 418: Run already exists in server. Run id(s): {8924106}
[2018-04-11 20:36:23] Started run 426 on task 45, dataset 'splice'.
[2018-04-11 20:36:23] Error in run 419: Run already exists in server. Run id(s): {8924105}
[2018-04-11 20:36:23] Started run 427 on task 45, dataset 'splice'.
[2018-04-11 20:36:24] Error in run 420: Run already exists in server. Run id(s): {8924104}
[2018-04-11 20:36:24] Started run 428 on task 45, dataset 'splice'.
[2018-04-11 20:36:24] Error in run 421: Run already exists in server. Run id(s): {8924107}
[2018-04-11 20:36:24] Started run 429 on task 45, dataset 'splice'.
[2018-04-11 20:36:24] Error in run 422: Run already exists in server. Run id(s): {8924109}
[2018-04-11 20:36:24] Error in run 424: Run already exists in server. Run id(s): {8924110}
[2018-04-11 20:36:24] Error in run 423: Run already exists in server. Run id(s): {8924108}
[2018-04-11 20:36:24] Started run 430 on task 45, dataset 'splice'.
[2018-04-11 20:36:24] Started run 432 on task 45, dataset 'splice'.
[2018-04-11 20:36:24] Started run 431 on task 45, dataset 'splice'.
[2018-04-11 20:36:27] Error in run 425: Run already exists in server. Run id(s): {8924111}
[2018-04-11 20:36:27] Started run 433 on task 45, dataset 'splice'.
[2018-04-11 20:36:27] Error in run 426: Run already exists in server. Run id(s): {8924113}
[2018-04-11 20:36:27] Started run 434 on task 45, dataset 'splice'.
[2018-04-11 20:36:28] Error in run 427: Run already exists in server. Run id(s): {8924112}
[2018-04-11 20:36:28] Started run 435 on task 45, dataset 'splice'.
[2018-04-11 20:36:28] Error in run 428: Run already exists in server. Run id(s): {8924114}
[2018-04-11 20:36:28] Error in run 429: Run already exists in server. Run id(s): {8924115}
[2018-04-11 20:36:28] Started run 436 on task 45, dataset 'splice'.
[2018-04-11 20:36:28] Started run 437 on task 45, dataset 'splice'.
[2018-04-11 20:36:29] Error in run 430: Run already exists in server. Run id(s): {8924117}
[2018-04-11 20:36:29] Started run 438 on task 45, dataset 'splice'.
[2018-04-11 20:36:29] Error in run 431: Run already exists in server. Run id(s): {8924116}
[2018-04-11 20:36:29] Started run 439 on task 45, dataset 'splice'.
[2018-04-11 20:36:29] Error in run 432: Run already exists in server. Run id(s): {8924118}
[2018-04-11 20:36:29] Started run 440 on task 45, dataset 'splice'.
[2018-04-11 20:36:31] Error in run 433: Run already exists in server. Run id(s): {8924119}
[2018-04-11 20:36:31] Started run 441 on task 45, dataset 'splice'.
[2018-04-11 20:36:32] Error in run 434: Run already exists in server. Run id(s): {8924120}
[2018-04-11 20:36:32] Started run 442 on task 45, dataset 'splice'.
[2018-04-11 20:36:33] Error in run 435: Run already exists in server. Run id(s): {8924121}
[2018-04-11 20:36:33] Started run 443 on task 45, dataset 'splice'.
[2018-04-11 20:36:33] Error in run 436: Run already exists in server. Run id(s): {8924123}
[2018-04-11 20:36:33] Error in run 437: Run already exists in server. Run id(s): {8924126}
[2018-04-11 20:36:33] Started run 444 on task 45, dataset 'splice'.
[2018-04-11 20:36:33] Started run 445 on task 45, dataset 'splice'.
[2018-04-11 20:36:33] Error in run 438: Run already exists in server. Run id(s): {8924122}
[2018-04-11 20:36:33] Started run 446 on task 45, dataset 'splice'.
[2018-04-11 20:36:34] Error in run 439: Run already exists in server. Run id(s): {8924125}
[2018-04-11 20:36:34] Error in run 440: Run already exists in server. Run id(s): {8924124}
[2018-04-11 20:36:34] Started run 447 on task 45, dataset 'splice'.
[2018-04-11 20:36:34] Started run 448 on task 45, dataset 'splice'.
[2018-04-11 20:36:36] Error in run 441: Run already exists in server. Run id(s): {8924127}
[2018-04-11 20:36:36] Started run 449 on task 45, dataset 'splice'.
[2018-04-11 20:36:36] Error in run 442: Run already exists in server. Run id(s): {8924130}
[2018-04-11 20:36:36] Started run 450 on task 45, dataset 'splice'.
[2018-04-11 20:36:37] Error in run 443: Run already exists in server. Run id(s): {8924132}
[2018-04-11 20:36:37] Error in run 444: Run already exists in server. Run id(s): {8924133}
[2018-04-11 20:36:37] Error in run 445: Run already exists in server. Run id(s): {8924129}
[2018-04-11 20:36:37] Started run 451 on task 45, dataset 'splice'.
[2018-04-11 20:36:37] Started run 453 on task 45, dataset 'splice'.
[2018-04-11 20:36:37] Started run 452 on task 45, dataset 'splice'.
[2018-04-11 20:36:38] Error in run 446: Run already exists in server. Run id(s): {8924134}
[2018-04-11 20:36:38] Started run 454 on task 45, dataset 'splice'.
[2018-04-11 20:36:38] Error in run 447: Run already exists in server. Run id(s): {8924135}
[2018-04-11 20:36:38] Started run 455 on task 45, dataset 'splice'.
[2018-04-11 20:36:38] Error in run 448: Run already exists in server. Run id(s): {8924136}
[2018-04-11 20:36:38] Started run 456 on task 45, dataset 'splice'.
[2018-04-11 20:36:41] Error in run 449: Run already exists in server. Run id(s): {8924137}
[2018-04-11 20:36:41] Started run 457 on task 45, dataset 'splice'.
[2018-04-11 20:36:41] Error in run 450: Run already exists in server. Run id(s): {8924139}
[2018-04-11 20:36:41] Started run 458 on task 45, dataset 'splice'.
[2018-04-11 20:36:42] Error in run 453: Run already exists in server. Run id(s): {8924142}
[2018-04-11 20:36:42] Error in run 451: Run already exists in server. Run id(s): {8924140}
[2018-04-11 20:36:42] Error in run 452: Run already exists in server. Run id(s): {8924141}
[2018-04-11 20:36:42] Started run 459 on task 45, dataset 'splice'.
[2018-04-11 20:36:42] Started run 460 on task 45, dataset 'splice'.
[2018-04-11 20:36:42] Started run 461 on task 45, dataset 'splice'.
[2018-04-11 20:36:42] Error in run 454: Run already exists in server. Run id(s): {8924143}
[2018-04-11 20:36:42] Started run 462 on task 45, dataset 'splice'.
[2018-04-11 20:36:43] Error in run 455: Run already exists in server. Run id(s): {8924144}
[2018-04-11 20:36:43] Error in run 456: Run already exists in server. Run id(s): {8924145}
[2018-04-11 20:36:43] Started run 463 on task 45, dataset 'splice'.
[2018-04-11 20:36:43] Started run 464 on task 45, dataset 'splice'.
[2018-04-11 20:36:45] Error in run 457: Run already exists in server. Run id(s): {8924149}
[2018-04-11 20:36:45] Started run 465 on task 45, dataset 'splice'.
[2018-04-11 20:36:46] Error in run 458: Run already exists in server. Run id(s): {8924147}
[2018-04-11 20:36:46] Started run 466 on task 45, dataset 'splice'.
[2018-04-11 20:36:47] Error in run 459: Run already exists in server. Run id(s): {8924148}
[2018-04-11 20:36:47] Started run 467 on task 45, dataset 'splice'.
[2018-04-11 20:36:47] Error in run 460: Run already exists in server. Run id(s): {8924150}
[2018-04-11 20:36:47] Error in run 462: Run already exists in server. Run id(s): {8924153}
[2018-04-11 20:36:47] Error in run 461: Run already exists in server. Run id(s): {8924151}
[2018-04-11 20:36:47] Started run 468 on task 45, dataset 'splice'.
[2018-04-11 20:36:47] Started run 469 on task 45, dataset 'splice'.
[2018-04-11 20:36:47] Started run 470 on task 45, dataset 'splice'.
[2018-04-11 20:36:48] Error in run 463: Run already exists in server. Run id(s): {8924152}
[2018-04-11 20:36:48] Error in run 464: Run already exists in server. Run id(s): {8924155}
[2018-04-11 20:36:48] Started run 471 on task 45, dataset 'splice'.
[2018-04-11 20:36:48] Started run 472 on task 45, dataset 'splice'.
[2018-04-11 20:36:50] Error in run 465: Run already exists in server. Run id(s): {8924157}
[2018-04-11 20:36:50] Started run 473 on task 45, dataset 'splice'.
[2018-04-11 20:36:50] Error in run 466: Run already exists in server. Run id(s): {8924156}
[2018-04-11 20:36:50] Started run 474 on task 45, dataset 'splice'.
[2018-04-11 20:36:51] Error in run 467: Run already exists in server. Run id(s): {8924158}
[2018-04-11 20:36:51] Error in run 468: Run already exists in server. Run id(s): {8924160}
[2018-04-11 20:36:51] Started run 475 on task 45, dataset 'splice'.
[2018-04-11 20:36:51] Started run 476 on task 45, dataset 'splice'.
[2018-04-11 20:36:51] Error in run 469: Run already exists in server. Run id(s): {8924161}
[2018-04-11 20:36:51] Started run 477 on task 45, dataset 'splice'.
[2018-04-11 20:36:51] Error in run 470: Run already exists in server. Run id(s): {8924162}
[2018-04-11 20:36:51] Started run 478 on task 45, dataset 'splice'.
[2018-04-11 20:36:52] Error in run 471: Run already exists in server. Run id(s): {8924163}
[2018-04-11 20:36:52] Started run 479 on task 45, dataset 'splice'.
[2018-04-11 20:36:52] Error in run 472: Run already exists in server. Run id(s): {8924166}
[2018-04-11 20:36:52] Started run 480 on task 45, dataset 'splice'.
[2018-04-11 20:36:54] Error in run 473: Run already exists in server. Run id(s): {8924167}
[2018-04-11 20:36:54] Started run 481 on task 45, dataset 'splice'.
[2018-04-11 20:36:55] Error in run 474: Run already exists in server. Run id(s): {8924168}
[2018-04-11 20:36:55] Started run 482 on task 45, dataset 'splice'.
[2018-04-11 20:36:56] Error in run 475: Run already exists in server. Run id(s): {8924165}
[2018-04-11 20:36:56] Started run 483 on task 45, dataset 'splice'.
[2018-04-11 20:36:56] Error in run 476: Run already exists in server. Run id(s): {8924171}
[2018-04-11 20:36:56] Started run 484 on task 45, dataset 'splice'.
[2018-04-11 20:36:56] Error in run 477: Run already exists in server. Run id(s): {8924169}
[2018-04-11 20:36:56] Started run 485 on task 45, dataset 'splice'.
[2018-04-11 20:36:56] Error in run 478: Run already exists in server. Run id(s): {8924170}
[2018-04-11 20:36:56] Started run 486 on task 45, dataset 'splice'.
[2018-04-11 20:36:57] Error in run 479: Run already exists in server. Run id(s): {8924172}
[2018-04-11 20:36:57] Started run 487 on task 45, dataset 'splice'.
[2018-04-11 20:36:57] Error in run 480: Run already exists in server. Run id(s): {8924173}
[2018-04-11 20:36:57] Started run 488 on task 45, dataset 'splice'.
[2018-04-11 20:36:59] Error in run 481: Run already exists in server. Run id(s): {8924174}
[2018-04-11 20:36:59] Started run 489 on task 45, dataset 'splice'.
[2018-04-11 20:36:59] Error in run 482: Run already exists in server. Run id(s): {8924177}
[2018-04-11 20:36:59] Started run 490 on task 45, dataset 'splice'.
[2018-04-11 20:37:00] Error in run 483: Run already exists in server. Run id(s): {8924178}
[2018-04-11 20:37:00] Started run 491 on task 45, dataset 'splice'.
[2018-04-11 20:37:00] Error in run 484: Run already exists in server. Run id(s): {8924175}
[2018-04-11 20:37:00] Started run 492 on task 45, dataset 'splice'.
[2018-04-11 20:37:01] Error in run 485: Run already exists in server. Run id(s): {8924176}
[2018-04-11 20:37:01] Started run 493 on task 45, dataset 'splice'.
[2018-04-11 20:37:01] Error in run 486: Run already exists in server. Run id(s): {8924181}
[2018-04-11 20:37:01] Started run 494 on task 45, dataset 'splice'.
[2018-04-11 20:37:01] Error in run 487: Run already exists in server. Run id(s): {8924182}
[2018-04-11 20:37:01] Started run 495 on task 45, dataset 'splice'.
[2018-04-11 20:37:01] Error in run 488: Run already exists in server. Run id(s): {8924180}
[2018-04-11 20:37:01] Started run 496 on task 45, dataset 'splice'.
[2018-04-11 20:37:04] Error in run 489: Run already exists in server. Run id(s): {8924183}
[2018-04-11 20:37:04] Started run 497 on task 45, dataset 'splice'.
[2018-04-11 20:37:04] Error in run 490: Run already exists in server. Run id(s): {8924185}
[2018-04-11 20:37:04] Started run 498 on task 45, dataset 'splice'.
[2018-04-11 20:37:05] Error in run 491: Run already exists in server. Run id(s): {8924186}
[2018-04-11 20:37:05] Started run 499 on task 45, dataset 'splice'.
[2018-04-11 20:37:05] Error in run 492: Run already exists in server. Run id(s): {8924188}
[2018-04-11 20:37:05] Started run 500 on task 45, dataset 'splice'.
[2018-04-11 20:37:05] Error in run 493: Run already exists in server. Run id(s): {8924187}
[2018-04-11 20:37:05] Started run 501 on task 45, dataset 'splice'.
[2018-04-11 20:37:05] Error in run 494: Run already exists in server. Run id(s): {8924189}
[2018-04-11 20:37:05] Started run 502 on task 45, dataset 'splice'.
[2018-04-11 20:37:06] Error in run 495: Run already exists in server. Run id(s): {8924192}
[2018-04-11 20:37:06] Started run 503 on task 45, dataset 'splice'.
[2018-04-11 20:37:06] Error in run 496: Run already exists in server. Run id(s): {8924195}
[2018-04-11 20:37:06] Started run 504 on task 45, dataset 'splice'.
[2018-04-11 20:37:08] Error in run 497: Run already exists in server. Run id(s): {8924193}
[2018-04-11 20:37:08] Started run 505 on task 45, dataset 'splice'.
[2018-04-11 20:37:09] Error in run 498: Run already exists in server. Run id(s): {8924194}
[2018-04-11 20:37:09] Started run 506 on task 45, dataset 'splice'.
[2018-04-11 20:37:09] Error in run 499: Run already exists in server. Run id(s): {8924196}
[2018-04-11 20:37:09] Started run 507 on task 45, dataset 'splice'.
[2018-04-11 20:37:10] Error in run 500: Run already exists in server. Run id(s): {8924197}
[2018-04-11 20:37:10] Started run 508 on task 45, dataset 'splice'.
[2018-04-11 20:37:10] Error in run 501: Run already exists in server. Run id(s): {8924198}
[2018-04-11 20:37:10] Error in run 502: Run already exists in server. Run id(s): {8924200}
[2018-04-11 20:37:10] Started run 509 on task 45, dataset 'splice'.
[2018-04-11 20:37:10] Started run 510 on task 45, dataset 'splice'.
[2018-04-11 20:37:10] Error in run 503: Run already exists in server. Run id(s): {8924201}
[2018-04-11 20:37:10] Started run 511 on task 45, dataset 'splice'.
[2018-04-11 20:37:11] Error in run 504: Run already exists in server. Run id(s): {8924203}
[2018-04-11 20:37:11] Started run 512 on task 45, dataset 'splice'.
[2018-04-11 20:37:13] Error in run 505: Run already exists in server. Run id(s): {8924204}
[2018-04-11 20:37:13] Started run 513 on task 45, dataset 'splice'.
[2018-04-11 20:37:13] Error in run 506: Run already exists in server. Run id(s): {8924206}
[2018-04-11 20:37:13] Started run 514 on task 45, dataset 'splice'.
[2018-04-11 20:37:14] Error in run 507: Run already exists in server. Run id(s): {8924205}
[2018-04-11 20:37:14] Started run 515 on task 45, dataset 'splice'.
[2018-04-11 20:37:14] Error in run 508: Run already exists in server. Run id(s): {8924207}
[2018-04-11 20:37:14] Error in run 510: Run already exists in server. Run id(s): {8924209}
[2018-04-11 20:37:14] Started run 516 on task 45, dataset 'splice'.
[2018-04-11 20:37:14] Error in run 509: Run already exists in server. Run id(s): {8924208}
[2018-04-11 20:37:14] Started run 518 on task 45, dataset 'splice'.
[2018-04-11 20:37:14] Started run 517 on task 45, dataset 'splice'.
[2018-04-11 20:37:15] Error in run 511: Run already exists in server. Run id(s): {8924210}
[2018-04-11 20:37:15] Started run 519 on task 45, dataset 'splice'.
[2018-04-11 20:37:15] Error in run 512: Run already exists in server. Run id(s): {8924211}
[2018-04-11 20:37:15] Started run 520 on task 45, dataset 'splice'.
[2018-04-11 20:37:17] Error in run 513: Run already exists in server. Run id(s): {8924214}
[2018-04-11 20:37:17] Started run 521 on task 45, dataset 'splice'.
[2018-04-11 20:37:18] Error in run 514: Run already exists in server. Run id(s): {8924212}
[2018-04-11 20:37:18] Started run 522 on task 45, dataset 'splice'.
[2018-04-11 20:37:19] Error in run 515: Run already exists in server. Run id(s): {8924215}
[2018-04-11 20:37:19] Started run 523 on task 45, dataset 'splice'.
[2018-04-11 20:37:19] Error in run 517: Run already exists in server. Run id(s): {8924218}
[2018-04-11 20:37:19] Error in run 518: Run already exists in server. Run id(s): {8924217}
[2018-04-11 20:37:19] Error in run 516: Run already exists in server. Run id(s): {8924216}
[2018-04-11 20:37:19] Started run 524 on task 45, dataset 'splice'.
[2018-04-11 20:37:19] Started run 525 on task 45, dataset 'splice'.
[2018-04-11 20:37:19] Started run 526 on task 45, dataset 'splice'.
[2018-04-11 20:37:20] Error in run 519: Run already exists in server. Run id(s): {8924219}
[2018-04-11 20:37:20] Started run 527 on task 45, dataset 'splice'.
[2018-04-11 20:37:20] Error in run 520: Run already exists in server. Run id(s): {8924220}
[2018-04-11 20:37:20] Started run 528 on task 45, dataset 'splice'.
[2018-04-11 20:37:22] Error in run 521: Run already exists in server. Run id(s): {8924222}
[2018-04-11 20:37:22] Started run 529 on task 45, dataset 'splice'.
[2018-04-11 20:37:23] Error in run 522: Run already exists in server. Run id(s): {8924221}
[2018-04-11 20:37:23] Started run 530 on task 45, dataset 'splice'.
[2018-04-11 20:37:23] Error in run 523: Run already exists in server. Run id(s): {8924223}
[2018-04-11 20:37:23] Started run 531 on task 45, dataset 'splice'.
[2018-04-11 20:37:24] Error in run 524: Run already exists in server. Run id(s): {8924224}
[2018-04-11 20:37:24] Error in run 526: Run already exists in server. Run id(s): {8924230}
[2018-04-11 20:37:24] Error in run 525: Run already exists in server. Run id(s): {8924229}
[2018-04-11 20:37:24] Started run 532 on task 45, dataset 'splice'.
[2018-04-11 20:37:24] Started run 534 on task 45, dataset 'splice'.
[2018-04-11 20:37:24] Started run 533 on task 45, dataset 'splice'.
[2018-04-11 20:37:24] Error in run 527: Run already exists in server. Run id(s): {8924231}
[2018-04-11 20:37:24] Error in run 528: Run already exists in server. Run id(s): {8924233}
[2018-04-11 20:37:24] Started run 535 on task 45, dataset 'splice'.
[2018-04-11 20:37:24] Started run 536 on task 45, dataset 'splice'.
[2018-04-11 20:37:27] Error in run 529: Run already exists in server. Run id(s): {8924232}
[2018-04-11 20:37:27] Started run 537 on task 45, dataset 'splice'.
[2018-04-11 20:37:27] Error in run 530: Run already exists in server. Run id(s): {8924234}
[2018-04-11 20:37:27] Started run 538 on task 45, dataset 'splice'.
[2018-04-11 20:37:28] Error in run 531: Run already exists in server. Run id(s): {8924236}
[2018-04-11 20:37:28] Started run 539 on task 45, dataset 'splice'.
[2018-04-11 20:37:28] Error in run 534: Run already exists in server. Run id(s): {8924235}
[2018-04-11 20:37:28] Error in run 532: Run already exists in server. Run id(s): {8924237}
[2018-04-11 20:37:28] Error in run 533: Run already exists in server. Run id(s): {8924238}
[2018-04-11 20:37:28] Started run 540 on task 45, dataset 'splice'.
[2018-04-11 20:37:28] Started run 541 on task 45, dataset 'splice'.
[2018-04-11 20:37:28] Started run 542 on task 45, dataset 'splice'.
[2018-04-11 20:37:29] Error in run 536: Run already exists in server. Run id(s): {8924243}
[2018-04-11 20:37:29] Error in run 535: Run already exists in server. Run id(s): {8924244}
[2018-04-11 20:37:29] Started run 543 on task 45, dataset 'splice'.
[2018-04-11 20:37:29] Started run 544 on task 45, dataset 'splice'.
[2018-04-11 20:37:31] Error in run 537: Run already exists in server. Run id(s): {8924241}
[2018-04-11 20:37:31] Started run 545 on task 45, dataset 'splice'.
[2018-04-11 20:37:32] Error in run 538: Run already exists in server. Run id(s): {8924246}
[2018-04-11 20:37:32] Started run 546 on task 45, dataset 'splice'.
[2018-04-11 20:37:32] Error in run 539: Run already exists in server. Run id(s): {8924245}
[2018-04-11 20:37:32] Started run 547 on task 45, dataset 'splice'.
[2018-04-11 20:37:33] Error in run 540: Run already exists in server. Run id(s): {8924247}
[2018-04-11 20:37:33] Error in run 542: Run already exists in server. Run id(s): {8924249}
[2018-04-11 20:37:33] Error in run 541: Run already exists in server. Run id(s): {8924248}
[2018-04-11 20:37:33] Started run 548 on task 45, dataset 'splice'.
[2018-04-11 20:37:33] Started run 549 on task 45, dataset 'splice'.
[2018-04-11 20:37:33] Started run 550 on task 45, dataset 'splice'.
[2018-04-11 20:37:34] Error in run 544: Run already exists in server. Run id(s): {8924253}
[2018-04-11 20:37:34] Error in run 543: Run already exists in server. Run id(s): {8924250}
[2018-04-11 20:37:34] Started run 551 on task 45, dataset 'splice'.
[2018-04-11 20:37:34] Started run 552 on task 45, dataset 'splice'.
[2018-04-11 20:37:36] Error in run 545: Run already exists in server. Run id(s): {8924254}
[2018-04-11 20:37:36] Started run 553 on task 45, dataset 'splice'.
[2018-04-11 20:37:36] Error in run 546: Run already exists in server. Run id(s): {8924251}
[2018-04-11 20:37:36] Started run 554 on task 45, dataset 'splice'.
[2018-04-11 20:37:37] Error in run 547: Run already exists in server. Run id(s): {8924252}
[2018-04-11 20:37:37] Started run 555 on task 45, dataset 'splice'.
[2018-04-11 20:37:38] Error in run 549: Run already exists in server. Run id(s): {8924258}
[2018-04-11 20:37:38] Error in run 548: Run already exists in server. Run id(s): {8924256}
[2018-04-11 20:37:38] Started run 556 on task 45, dataset 'splice'.
[2018-04-11 20:37:38] Error in run 550: Run already exists in server. Run id(s): {8924257}
[2018-04-11 20:37:38] Started run 558 on task 45, dataset 'splice'.
[2018-04-11 20:37:38] Started run 557 on task 45, dataset 'splice'.
[2018-04-11 20:37:38] Error in run 552: Run already exists in server. Run id(s): {8924261}
[2018-04-11 20:37:38] Started run 559 on task 45, dataset 'splice'.
[2018-04-11 20:37:38] Error in run 551: Run already exists in server. Run id(s): {8924259}
[2018-04-11 20:37:38] Started run 560 on task 45, dataset 'splice'.
[2018-04-11 20:37:40] Error in run 553: Run already exists in server. Run id(s): {8924264}
[2018-04-11 20:37:40] Started run 561 on task 45, dataset 'splice'.
[2018-04-11 20:37:41] Error in run 554: Run already exists in server. Run id(s): {8924263}
[2018-04-11 20:37:41] Started run 562 on task 45, dataset 'splice'.
[2018-04-11 20:37:42] Error in run 555: Run already exists in server. Run id(s): {8924262}
[2018-04-11 20:37:42] Started run 563 on task 45, dataset 'splice'.
[2018-04-11 20:37:42] Error in run 557: Run already exists in server. Run id(s): {8924268}
[2018-04-11 20:37:42] Started run 564 on task 45, dataset 'splice'.
[2018-04-11 20:37:42] Error in run 556: Run already exists in server. Run id(s): {8924269}
[2018-04-11 20:37:42] Error in run 558: Run already exists in server. Run id(s): {8924270}
[2018-04-11 20:37:42] Started run 565 on task 45, dataset 'splice'.
[2018-04-11 20:37:42] Started run 566 on task 45, dataset 'splice'.
[2018-04-11 20:37:43] Error in run 559: Run already exists in server. Run id(s): {8924267}
[2018-04-11 20:37:43] Error in run 560: Run already exists in server. Run id(s): {8924271}
[2018-04-11 20:37:43] Started run 567 on task 45, dataset 'splice'.
[2018-04-11 20:37:43] Started run 568 on task 45, dataset 'splice'.
[2018-04-11 20:37:45] Error in run 561: Run already exists in server. Run id(s): {8924272}
[2018-04-11 20:37:45] Started run 569 on task 45, dataset 'splice'.
[2018-04-11 20:37:45] Error in run 562: Run already exists in server. Run id(s): {8924274}
[2018-04-11 20:37:45] Started run 570 on task 45, dataset 'splice'.
[2018-04-11 20:37:46] Error in run 563: Run already exists in server. Run id(s): {8924275}
[2018-04-11 20:37:46] Started run 571 on task 45, dataset 'splice'.
[2018-04-11 20:37:47] Error in run 564: Run already exists in server. Run id(s): {8924273}
[2018-04-11 20:37:47] Started run 572 on task 45, dataset 'splice'.
[2018-04-11 20:37:47] Error in run 566: Run already exists in server. Run id(s): {8924278}
[2018-04-11 20:37:47] Error in run 565: Run already exists in server. Run id(s): {8924277}
[2018-04-11 20:37:47] Started run 573 on task 45, dataset 'splice'.
[2018-04-11 20:37:47] Started run 574 on task 45, dataset 'splice'.
[2018-04-11 20:37:48] Error in run 567: Run already exists in server. Run id(s): {8924279}
[2018-04-11 20:37:48] Started run 575 on task 45, dataset 'splice'.
[2018-04-11 20:37:48] Error in run 568: Run already exists in server. Run id(s): {8924276}
[2018-04-11 20:37:48] Started run 576 on task 45, dataset 'splice'.
[2018-04-11 20:37:49] Error in run 569: Run already exists in server. Run id(s): {8924280}
[2018-04-11 20:37:49] Started run 577 on task 45, dataset 'splice'.
[2018-04-11 20:37:50] Error in run 570: Run already exists in server. Run id(s): {8924284}
[2018-04-11 20:37:50] Started run 578 on task 45, dataset 'splice'.
[2018-04-11 20:37:51] Error in run 571: Run already exists in server. Run id(s): {8924283}
[2018-04-11 20:37:51] Started run 579 on task 45, dataset 'splice'.
[2018-04-11 20:37:51] Error in run 572: Run already exists in server. Run id(s): {8924282}
[2018-04-11 20:37:51] Started run 580 on task 45, dataset 'splice'.
[2018-04-11 20:37:52] Error in run 573: Run already exists in server. Run id(s): {8924286}
[2018-04-11 20:37:52] Started run 581 on task 45, dataset 'splice'.
[2018-04-11 20:37:52] Error in run 574: Run already exists in server. Run id(s): {8924285}
[2018-04-11 20:37:52] Started run 582 on task 45, dataset 'splice'.
[2018-04-11 20:37:52] Error in run 575: Run already exists in server. Run id(s): {8924287}
[2018-04-11 20:37:52] Started run 583 on task 45, dataset 'splice'.
[2018-04-11 20:37:52] Error in run 576: Run already exists in server. Run id(s): {8924290}
[2018-04-11 20:37:52] Started run 584 on task 45, dataset 'splice'.
[2018-04-11 20:37:54] Error in run 577: Run already exists in server. Run id(s): {8924288}
[2018-04-11 20:37:54] Started run 585 on task 45, dataset 'splice'.
[2018-04-11 20:37:54] Error in run 578: Run already exists in server. Run id(s): {8924291}
[2018-04-11 20:37:54] Started run 586 on task 45, dataset 'splice'.
[2018-04-11 20:37:56] Error in run 579: Run already exists in server. Run id(s): {8924289}
[2018-04-11 20:37:56] Started run 587 on task 45, dataset 'splice'.
[2018-04-11 20:37:56] Error in run 580: Run already exists in server. Run id(s): {8924292}
[2018-04-11 20:37:56] Started run 588 on task 45, dataset 'splice'.
[2018-04-11 20:37:56] Error in run 581: Run already exists in server. Run id(s): {8924293}
[2018-04-11 20:37:56] Started run 589 on task 45, dataset 'splice'.
[2018-04-11 20:37:56] Error in run 582: Run already exists in server. Run id(s): {8924295}
[2018-04-11 20:37:56] Started run 590 on task 45, dataset 'splice'.
[2018-04-11 20:37:57] Error in run 584: Run already exists in server. Run id(s): {8924296}
[2018-04-11 20:37:57] Started run 591 on task 45, dataset 'splice'.
[2018-04-11 20:37:57] Error in run 583: Run already exists in server. Run id(s): {8924294}
[2018-04-11 20:37:57] Started run 592 on task 45, dataset 'splice'.
[2018-04-11 20:37:59] Error in run 585: Run already exists in server. Run id(s): {8924299}
[2018-04-11 20:37:59] Started run 593 on task 45, dataset 'splice'.
[2018-04-11 20:37:59] Error in run 586: Run already exists in server. Run id(s): {8924298}
[2018-04-11 20:37:59] Started run 594 on task 45, dataset 'splice'.
[2018-04-11 20:38:00] Error in run 588: Run already exists in server. Run id(s): {8924302}
[2018-04-11 20:38:00] Error in run 587: Run already exists in server. Run id(s): {8924301}
[2018-04-11 20:38:00] Started run 595 on task 45, dataset 'splice'.
[2018-04-11 20:38:00] Started run 596 on task 45, dataset 'splice'.
[2018-04-11 20:38:01] Error in run 589: Run already exists in server. Run id(s): {8924304}
[2018-04-11 20:38:01] Started run 597 on task 45, dataset 'splice'.
[2018-04-11 20:38:01] Error in run 590: Run already exists in server. Run id(s): {8924305}
[2018-04-11 20:38:01] Error in run 592: Run already exists in server. Run id(s): {8924307}
[2018-04-11 20:38:01] Error in run 591: Run already exists in server. Run id(s): {8924306}
[2018-04-11 20:38:01] Started run 598 on task 45, dataset 'splice'.
[2018-04-11 20:38:01] Started run 600 on task 45, dataset 'splice'.
[2018-04-11 20:38:01] Started run 599 on task 45, dataset 'splice'.
[2018-04-11 20:38:03] Error in run 594: Run already exists in server. Run id(s): {8924309}
[2018-04-11 20:38:03] Error in run 593: Run already exists in server. Run id(s): {8924308}
[2018-04-11 20:38:03] Started run 601 on task 45, dataset 'splice'.
[2018-04-11 20:38:03] Started run 602 on task 45, dataset 'splice'.
[2018-04-11 20:38:05] Error in run 595: Run already exists in server. Run id(s): {8924311}
[2018-04-11 20:38:05] Error in run 596: Run already exists in server. Run id(s): {8924310}
[2018-04-11 20:38:05] Started run 603 on task 45, dataset 'splice'.
[2018-04-11 20:38:05] Started run 604 on task 45, dataset 'splice'.
[2018-04-11 20:38:05] Error in run 597: Run already exists in server. Run id(s): {8924313}
[2018-04-11 20:38:05] Started run 605 on task 45, dataset 'splice'.
[2018-04-11 20:38:06] Error in run 598: Run already exists in server. Run id(s): {8924314}
[2018-04-11 20:38:06] Error in run 599: Run already exists in server. Run id(s): {8924315}
[2018-04-11 20:38:06] Error in run 600: Run already exists in server. Run id(s): {8924316}
[2018-04-11 20:38:06] Started run 606 on task 45, dataset 'splice'.
[2018-04-11 20:38:06] Started run 608 on task 45, dataset 'splice'.
[2018-04-11 20:38:06] Started run 607 on task 45, dataset 'splice'.
[2018-04-11 20:38:08] Error in run 601: Run already exists in server. Run id(s): {8924318}
[2018-04-11 20:38:08] Error in run 602: Run already exists in server. Run id(s): {8924320}
[2018-04-11 20:38:08] Started run 609 on task 45, dataset 'splice'.
[2018-04-11 20:38:08] Started run 610 on task 45, dataset 'splice'.
[2018-04-11 20:38:10] Error in run 603: Run already exists in server. Run id(s): {8924322}
[2018-04-11 20:38:10] Error in run 604: Run already exists in server. Run id(s): {8924319}
[2018-04-11 20:38:10] Started run 611 on task 45, dataset 'splice'.
[2018-04-11 20:38:10] Error in run 605: Run already exists in server. Run id(s): {8924323}
[2018-04-11 20:38:10] Started run 612 on task 45, dataset 'splice'.
[2018-04-11 20:38:10] Started run 613 on task 45, dataset 'splice'.
[2018-04-11 20:38:11] Error in run 608: Run already exists in server. Run id(s): {8924327}
[2018-04-11 20:38:11] Error in run 606: Run already exists in server. Run id(s): {9015868, 8924326}
[2018-04-11 20:38:11] Error in run 607: Run already exists in server. Run id(s): {8924324}
[2018-04-11 20:38:11] Started run 614 on task 45, dataset 'splice'.
[2018-04-11 20:38:11] Started run 615 on task 45, dataset 'splice'.
[2018-04-11 20:38:11] Started run 616 on task 45, dataset 'splice'.
[2018-04-11 20:38:13] Error in run 609: Run already exists in server. Run id(s): {8924329}
[2018-04-11 20:38:13] Started run 617 on task 45, dataset 'splice'.
[2018-04-11 20:38:13] Error in run 610: Run already exists in server. Run id(s): {8924328}
[2018-04-11 20:38:13] Started run 618 on task 45, dataset 'splice'.
[2018-04-11 20:38:14] Error in run 613: Run already exists in server. Run id(s): {8924332}
[2018-04-11 20:38:14] Error in run 612: Run already exists in server. Run id(s): {8924334}
[2018-04-11 20:38:14] Started run 619 on task 45, dataset 'splice'.
[2018-04-11 20:38:14] Error in run 611: Run already exists in server. Run id(s): {8924331}
[2018-04-11 20:38:14] Started run 621 on task 45, dataset 'splice'.
[2018-04-11 20:38:14] Started run 620 on task 45, dataset 'splice'.
[2018-04-11 20:38:15] Error in run 616: Run already exists in server. Run id(s): {8924337}
[2018-04-11 20:38:15] Error in run 614: Run already exists in server. Run id(s): {8924336}
[2018-04-11 20:38:15] Error in run 615: Run already exists in server. Run id(s): {8924335}
[2018-04-11 20:38:15] Started run 622 on task 45, dataset 'splice'.
[2018-04-11 20:38:15] Started run 623 on task 45, dataset 'splice'.
[2018-04-11 20:38:15] Started run 624 on task 45, dataset 'splice'.
[2018-04-11 20:38:17] Error in run 617: Run already exists in server. Run id(s): {8924338}
[2018-04-11 20:38:17] Started run 625 on task 45, dataset 'splice'.
[2018-04-11 20:38:18] Error in run 618: Run already exists in server. Run id(s): {8924339}
[2018-04-11 20:38:18] Started run 626 on task 45, dataset 'splice'.
[2018-04-11 20:38:19] Error in run 620: Run already exists in server. Run id(s): {8924340}
[2018-04-11 20:38:19] Error in run 621: Run already exists in server. Run id(s): {8924343}
[2018-04-11 20:38:19] Started run 627 on task 45, dataset 'splice'.
[2018-04-11 20:38:19] Error in run 619: Run already exists in server. Run id(s): {8924341}
[2018-04-11 20:38:19] Started run 629 on task 45, dataset 'splice'.
[2018-04-11 20:38:19] Started run 628 on task 45, dataset 'splice'.
[2018-04-11 20:38:20] Error in run 622: Run already exists in server. Run id(s): {8924342}
[2018-04-11 20:38:20] Error in run 624: Run already exists in server. Run id(s): {8924345}
[2018-04-11 20:38:20] Error in run 623: Run already exists in server. Run id(s): {8924344}
[2018-04-11 20:38:20] Started run 630 on task 45, dataset 'splice'.
[2018-04-11 20:38:20] Started run 632 on task 45, dataset 'splice'.
[2018-04-11 20:38:20] Started run 631 on task 45, dataset 'splice'.
[2018-04-11 20:38:22] Error in run 625: Run already exists in server. Run id(s): {8924348}
[2018-04-11 20:38:22] Started run 633 on task 45, dataset 'splice'.
[2018-04-11 20:38:22] Error in run 626: Run already exists in server. Run id(s): {8924347}
[2018-04-11 20:38:22] Started run 634 on task 45, dataset 'splice'.
[2018-04-11 20:38:24] Error in run 629: Run already exists in server. Run id(s): {8924349}
[2018-04-11 20:38:24] Error in run 628: Run already exists in server. Run id(s): {8924350}
[2018-04-11 20:38:24] Started run 635 on task 45, dataset 'splice'.
[2018-04-11 20:38:24] Error in run 627: Run already exists in server. Run id(s): {8924346}
[2018-04-11 20:38:24] Started run 637 on task 45, dataset 'splice'.
[2018-04-11 20:38:24] Started run 636 on task 45, dataset 'splice'.
[2018-04-11 20:38:25] Error in run 630: Run already exists in server. Run id(s): {8924353}
[2018-04-11 20:38:25] Error in run 631: Run already exists in server. Run id(s): {8924351}
[2018-04-11 20:38:25] Error in run 632: Run already exists in server. Run id(s): {8924354}
[2018-04-11 20:38:25] Started run 638 on task 45, dataset 'splice'.
[2018-04-11 20:38:25] Started run 639 on task 45, dataset 'splice'.
[2018-04-11 20:38:25] Started run 640 on task 45, dataset 'splice'.
[2018-04-11 20:38:26] Error in run 633: Run already exists in server. Run id(s): {8924352}
[2018-04-11 20:38:26] Started run 641 on task 45, dataset 'splice'.
[2018-04-11 20:38:27] Error in run 634: Run already exists in server. Run id(s): {8924359}
[2018-04-11 20:38:27] Started run 642 on task 45, dataset 'splice'.
[2018-04-11 20:38:28] Error in run 637: Run already exists in server. Run id(s): {8924357}
[2018-04-11 20:38:28] Error in run 635: Run already exists in server. Run id(s): {8924356}
[2018-04-11 20:38:28] Started run 643 on task 45, dataset 'splice'.
[2018-04-11 20:38:28] Started run 644 on task 45, dataset 'splice'.
[2018-04-11 20:38:29] Error in run 636: Run already exists in server. Run id(s): {8924358}
[2018-04-11 20:38:29] Started run 645 on task 45, dataset 'splice'.
[2018-04-11 20:38:29] Error in run 640: Run already exists in server. Run id(s): {8924363}
[2018-04-11 20:38:29] Error in run 639: Run already exists in server. Run id(s): {8924364}
[2018-04-11 20:38:29] Error in run 638: Run already exists in server. Run id(s): {8924362}
[2018-04-11 20:38:29] Started run 646 on task 45, dataset 'splice'.
[2018-04-11 20:38:29] Started run 648 on task 45, dataset 'splice'.
[2018-04-11 20:38:29] Started run 647 on task 45, dataset 'splice'.
[2018-04-11 20:38:31] Error in run 641: Run already exists in server. Run id(s): {8924361}
[2018-04-11 20:38:31] Started run 649 on task 45, dataset 'splice'.
[2018-04-11 20:38:32] Error in run 642: Run already exists in server. Run id(s): {8924367}
[2018-04-11 20:38:32] Started run 650 on task 45, dataset 'splice'.
[2018-04-11 20:38:33] Error in run 643: Run already exists in server. Run id(s): {8924368}
[2018-04-11 20:38:33] Error in run 645: Run already exists in server. Run id(s): {8924370}
[2018-04-11 20:38:33] Started run 651 on task 45, dataset 'splice'.
[2018-04-11 20:38:33] Started run 652 on task 45, dataset 'splice'.
[2018-04-11 20:38:33] Error in run 644: Run already exists in server. Run id(s): {8924366}
[2018-04-11 20:38:33] Started run 653 on task 45, dataset 'splice'.
[2018-04-11 20:38:34] Error in run 648: Run already exists in server. Run id(s): {8924373}
[2018-04-11 20:38:34] Started run 654 on task 45, dataset 'splice'.
[2018-04-11 20:38:34] Error in run 646: Run already exists in server. Run id(s): {8924371}
[2018-04-11 20:38:34] Error in run 647: Run already exists in server. Run id(s): {8964021}
[2018-04-11 20:38:34] Started run 655 on task 45, dataset 'splice'.
[2018-04-11 20:38:34] Started run 656 on task 45, dataset 'splice'.
[2018-04-11 20:38:36] Error in run 649: Run already exists in server. Run id(s): {8924374}
[2018-04-11 20:38:36] Started run 657 on task 45, dataset 'splice'.
[2018-04-11 20:38:36] Error in run 650: Run already exists in server. Run id(s): {8924376}
[2018-04-11 20:38:36] Started run 658 on task 45, dataset 'splice'.
[2018-04-11 20:38:38] Error in run 652: Run already exists in server. Run id(s): {8924378}
[2018-04-11 20:38:38] Started run 659 on task 45, dataset 'splice'.
[2018-04-11 20:38:38] Error in run 651: Run already exists in server. Run id(s): {8924377}
[2018-04-11 20:38:38] Started run 660 on task 45, dataset 'splice'.
[2018-04-11 20:38:38] Error in run 653: Run already exists in server. Run id(s): {8924379}
[2018-04-11 20:38:38] Started run 661 on task 45, dataset 'splice'.
[2018-04-11 20:38:38] Error in run 654: Run already exists in server. Run id(s): {8924380}
[2018-04-11 20:38:38] Started run 662 on task 45, dataset 'splice'.
[2018-04-11 20:38:39] Error in run 655: Run already exists in server. Run id(s): {8924381}
[2018-04-11 20:38:39] Error in run 656: Run already exists in server. Run id(s): {8924383}
[2018-04-11 20:38:39] Started run 663 on task 45, dataset 'splice'.
[2018-04-11 20:38:39] Started run 664 on task 45, dataset 'splice'.
[2018-04-11 20:38:40] Error in run 657: Run already exists in server. Run id(s): {8924384}
[2018-04-11 20:38:40] Started run 665 on task 45, dataset 'splice'.
[2018-04-11 20:38:41] Error in run 658: Run already exists in server. Run id(s): {8924382}
[2018-04-11 20:38:41] Started run 666 on task 45, dataset 'splice'.
[2018-04-11 20:38:42] Error in run 659: Run already exists in server. Run id(s): {8924386}
[2018-04-11 20:38:42] Started run 667 on task 45, dataset 'splice'.
[2018-04-11 20:38:42] Error in run 660: Run already exists in server. Run id(s): {8924385}
[2018-04-11 20:38:42] Started run 668 on task 45, dataset 'splice'.
[2018-04-11 20:38:43] Error in run 661: Run already exists in server. Run id(s): {8924388}
[2018-04-11 20:38:43] Started run 669 on task 45, dataset 'splice'.
[2018-04-11 20:38:43] Error in run 662: Run already exists in server. Run id(s): {8924387}
[2018-04-11 20:38:43] Started run 670 on task 45, dataset 'splice'.
[2018-04-11 20:38:43] Error in run 663: Run already exists in server. Run id(s): {8924389}
[2018-04-11 20:38:43] Error in run 664: Run already exists in server. Run id(s): {8924390}
[2018-04-11 20:38:43] Started run 671 on task 45, dataset 'splice'.
[2018-04-11 20:38:43] Started run 672 on task 45, dataset 'splice'.
[2018-04-11 20:38:45] Error in run 665: Run already exists in server. Run id(s): {8924391}
[2018-04-11 20:38:45] Started run 673 on task 45, dataset 'splice'.
[2018-04-11 20:38:46] Error in run 666: Run already exists in server. Run id(s): {8924392}
[2018-04-11 20:38:46] Started run 674 on task 45, dataset 'splice'.
[2018-04-11 20:38:47] Error in run 668: Run already exists in server. Run id(s): {8924395}
[2018-04-11 20:38:47] Error in run 667: Run already exists in server. Run id(s): {8924393}
[2018-04-11 20:38:47] Started run 676 on task 45, dataset 'splice'.
[2018-04-11 20:38:47] Started run 675 on task 45, dataset 'splice'.
[2018-04-11 20:38:47] Error in run 669: Run already exists in server. Run id(s): {8924394}
[2018-04-11 20:38:47] Started run 677 on task 45, dataset 'splice'.
[2018-04-11 20:38:48] Error in run 670: Run already exists in server. Run id(s): {8924397}
[2018-04-11 20:38:48] Started run 678 on task 45, dataset 'splice'.
[2018-04-11 20:38:48] Error in run 671: Run already exists in server. Run id(s): {8924399}
[2018-04-11 20:38:48] Started run 679 on task 45, dataset 'splice'.
[2018-04-11 20:38:48] Error in run 672: Run already exists in server. Run id(s): {8924398}
[2018-04-11 20:38:48] Started run 680 on task 45, dataset 'splice'.
[2018-04-11 20:38:50] Error in run 673: Run already exists in server. Run id(s): {8924402}
[2018-04-11 20:38:50] Started run 681 on task 45, dataset 'splice'.
[2018-04-11 20:38:50] Error in run 674: Run already exists in server. Run id(s): {8924403}
[2018-04-11 20:38:50] Started run 682 on task 45, dataset 'splice'.
[2018-04-11 20:38:51] Error in run 675: Run already exists in server. Run id(s): {8924404}
[2018-04-11 20:38:51] Error in run 676: Run already exists in server. Run id(s): {8924405}
[2018-04-11 20:38:51] Started run 683 on task 45, dataset 'splice'.
[2018-04-11 20:38:51] Started run 684 on task 45, dataset 'splice'.
[2018-04-11 20:38:52] Error in run 677: Run already exists in server. Run id(s): {8924406}
[2018-04-11 20:38:52] Started run 685 on task 45, dataset 'splice'.
[2018-04-11 20:38:52] Error in run 678: Run already exists in server. Run id(s): {8924408}
[2018-04-11 20:38:52] Started run 686 on task 45, dataset 'splice'.
[2018-04-11 20:38:53] Error in run 680: Run already exists in server. Run id(s): {8924414}
[2018-04-11 20:38:53] Error in run 679: Run already exists in server. Run id(s): {8924407}
[2018-04-11 20:38:53] Started run 687 on task 45, dataset 'splice'.
[2018-04-11 20:38:53] Started run 688 on task 45, dataset 'splice'.
[2018-04-11 20:38:54] Error in run 681: Run already exists in server. Run id(s): {8924410}
[2018-04-11 20:38:54] Started run 689 on task 45, dataset 'splice'.
[2018-04-11 20:38:55] Error in run 682: Run already exists in server. Run id(s): {8924416}
[2018-04-11 20:38:55] Started run 690 on task 45, dataset 'splice'.
[2018-04-11 20:38:56] Error in run 684: Run already exists in server. Run id(s): {8924415}
[2018-04-11 20:38:56] Started run 691 on task 45, dataset 'splice'.
[2018-04-11 20:38:56] Error in run 683: Run already exists in server. Run id(s): {8924417}
[2018-04-11 20:38:56] Started run 692 on task 45, dataset 'splice'.
[2018-04-11 20:38:56] Error in run 685: Run already exists in server. Run id(s): {8924419}
[2018-04-11 20:38:56] Started run 693 on task 45, dataset 'splice'.
[2018-04-11 20:38:57] Error in run 686: Run already exists in server. Run id(s): {8924421}
[2018-04-11 20:38:57] Started run 694 on task 45, dataset 'splice'.
[2018-04-11 20:38:57] Error in run 688: Run already exists in server. Run id(s): {8924420}
[2018-04-11 20:38:57] Error in run 687: Run already exists in server. Run id(s): {8924422}
[2018-04-11 20:38:57] Started run 695 on task 45, dataset 'splice'.
[2018-04-11 20:38:57] Started run 696 on task 45, dataset 'splice'.
[2018-04-11 20:38:59] Error in run 689: Run already exists in server. Run id(s): {8924423}
[2018-04-11 20:38:59] Started run 697 on task 45, dataset 'splice'.
[2018-04-11 20:39:00] Error in run 690: Run already exists in server. Run id(s): {8924424}
[2018-04-11 20:39:00] Started run 698 on task 45, dataset 'splice'.
[2018-04-11 20:39:01] Error in run 691: Run already exists in server. Run id(s): {8924426}
[2018-04-11 20:39:01] Error in run 692: Run already exists in server. Run id(s): {8924425}
[2018-04-11 20:39:01] Started run 699 on task 45, dataset 'splice'.
[2018-04-11 20:39:01] Started run 700 on task 45, dataset 'splice'.
[2018-04-11 20:39:01] Error in run 693: Run already exists in server. Run id(s): {8924427}
[2018-04-11 20:39:01] Started run 701 on task 45, dataset 'splice'.
[2018-04-11 20:39:01] Error in run 694: Run already exists in server. Run id(s): {8924428}
[2018-04-11 20:39:01] Started run 702 on task 45, dataset 'splice'.
[2018-04-11 20:39:02] Error in run 696: Run already exists in server. Run id(s): {8924430}
[2018-04-11 20:39:02] Error in run 695: Run already exists in server. Run id(s): {8924431}
[2018-04-11 20:39:02] Started run 703 on task 45, dataset 'splice'.
[2018-04-11 20:39:02] Started run 704 on task 45, dataset 'splice'.
[2018-04-11 20:39:04] Error in run 697: Run already exists in server. Run id(s): {8924432}
[2018-04-11 20:39:04] Started run 705 on task 45, dataset 'splice'.
[2018-04-11 20:39:04] Error in run 698: Run already exists in server. Run id(s): {8924434}
[2018-04-11 20:39:04] Started run 706 on task 45, dataset 'splice'.
[2018-04-11 20:39:05] Error in run 700: Run already exists in server. Run id(s): {8924437}
[2018-04-11 20:39:05] Error in run 699: Run already exists in server. Run id(s): {8924436}
[2018-04-11 20:39:05] Started run 707 on task 45, dataset 'splice'.
[2018-04-11 20:39:05] Started run 708 on task 45, dataset 'splice'.
[2018-04-11 20:39:05] Error in run 701: Run already exists in server. Run id(s): {8924435}
[2018-04-11 20:39:05] Started run 709 on task 45, dataset 'splice'.
[2018-04-11 20:39:06] Error in run 702: Run already exists in server. Run id(s): {8924441}
[2018-04-11 20:39:06] Started run 710 on task 45, dataset 'splice'.
[2018-04-11 20:39:07] Error in run 703: Run already exists in server. Run id(s): {8924439}
[2018-04-11 20:39:07] Started run 711 on task 45, dataset 'splice'.
[2018-04-11 20:39:07] Error in run 704: Run already exists in server. Run id(s): {8924442}
[2018-04-11 20:39:07] Started run 712 on task 45, dataset 'splice'.
[2018-04-11 20:39:08] Error in run 705: Run already exists in server. Run id(s): {8924444}
[2018-04-11 20:39:08] Started run 713 on task 45, dataset 'splice'.
[2018-04-11 20:39:09] Error in run 706: Run already exists in server. Run id(s): {8924443}
[2018-04-11 20:39:09] Started run 714 on task 45, dataset 'splice'.
[2018-04-11 20:39:10] Error in run 708: Run already exists in server. Run id(s): {8924445}
[2018-04-11 20:39:10] Error in run 707: Run already exists in server. Run id(s): {8924446}
[2018-04-11 20:39:10] Started run 715 on task 45, dataset 'splice'.
[2018-04-11 20:39:10] Started run 716 on task 45, dataset 'splice'.
[2018-04-11 20:39:10] Error in run 709: Run already exists in server. Run id(s): {8924449}
[2018-04-11 20:39:10] Started run 717 on task 45, dataset 'splice'.
[2018-04-11 20:39:11] Error in run 710: Run already exists in server. Run id(s): {8924450}
[2018-04-11 20:39:11] Started run 718 on task 45, dataset 'splice'.
[2018-04-11 20:39:11] Error in run 711: Run already exists in server. Run id(s): {8924447}
[2018-04-11 20:39:11] Error in run 712: Run already exists in server. Run id(s): {8924451}
[2018-04-11 20:39:11] Started run 719 on task 45, dataset 'splice'.
[2018-04-11 20:39:11] Started run 720 on task 45, dataset 'splice'.
[2018-04-11 20:39:13] Error in run 713: Run already exists in server. Run id(s): {8924452}
[2018-04-11 20:39:13] Started run 721 on task 45, dataset 'splice'.
[2018-04-11 20:39:14] Error in run 714: Run already exists in server. Run id(s): {8924453}
[2018-04-11 20:39:14] Started run 722 on task 45, dataset 'splice'.
[2018-04-11 20:39:15] Error in run 715: Run already exists in server. Run id(s): {8924454}
[2018-04-11 20:39:15] Error in run 717: Run already exists in server. Run id(s): {8924456}
[2018-04-11 20:39:15] Started run 723 on task 45, dataset 'splice'.
[2018-04-11 20:39:15] Error in run 716: Run already exists in server. Run id(s): {8924455}
[2018-04-11 20:39:15] Started run 725 on task 45, dataset 'splice'.
[2018-04-11 20:39:15] Started run 724 on task 45, dataset 'splice'.
[2018-04-11 20:39:15] Error in run 718: Run already exists in server. Run id(s): {8924457}
[2018-04-11 20:39:15] Started run 726 on task 45, dataset 'splice'.
[2018-04-11 20:39:16] Error in run 719: Run already exists in server. Run id(s): {8924459}
[2018-04-11 20:39:16] Error in run 720: Run already exists in server. Run id(s): {8924458}
[2018-04-11 20:39:16] Started run 727 on task 45, dataset 'splice'.
[2018-04-11 20:39:16] Started run 728 on task 45, dataset 'splice'.
[2018-04-11 20:39:18] Error in run 721: Run already exists in server. Run id(s): {8924460}
[2018-04-11 20:39:18] Started run 729 on task 45, dataset 'splice'.
[2018-04-11 20:39:18] Error in run 722: Run already exists in server. Run id(s): {8924462}
[2018-04-11 20:39:18] Started run 730 on task 45, dataset 'splice'.
[2018-04-11 20:39:19] Error in run 724: Run already exists in server. Run id(s): {8924461}
[2018-04-11 20:39:19] Started run 731 on task 45, dataset 'splice'.
[2018-04-11 20:39:19] Error in run 723: Run already exists in server. Run id(s): {8924463}
[2018-04-11 20:39:19] Started run 732 on task 45, dataset 'splice'.
[2018-04-11 20:39:19] Error in run 725: Run already exists in server. Run id(s): {8924464}
[2018-04-11 20:39:19] Started run 733 on task 45, dataset 'splice'.
[2018-04-11 20:39:20] Error in run 726: Run already exists in server. Run id(s): {8924465}
[2018-04-11 20:39:20] Started run 734 on task 45, dataset 'splice'.
[2018-04-11 20:39:21] Error in run 728: Run already exists in server. Run id(s): {8924467}
[2018-04-11 20:39:21] Error in run 727: Run already exists in server. Run id(s): {8924466}
[2018-04-11 20:39:21] Started run 735 on task 45, dataset 'splice'.
[2018-04-11 20:39:21] Started run 736 on task 45, dataset 'splice'.
[2018-04-11 20:39:22] Error in run 729: Run already exists in server. Run id(s): {8924469}
[2018-04-11 20:39:22] Started run 737 on task 45, dataset 'splice'.
[2018-04-11 20:39:23] Error in run 730: Run already exists in server. Run id(s): {9016387, 8924468}
[2018-04-11 20:39:23] Started run 738 on task 45, dataset 'splice'.
[2018-04-11 20:39:24] Error in run 731: Run already exists in server. Run id(s): {8924470}
[2018-04-11 20:39:24] Started run 739 on task 45, dataset 'splice'.
[2018-04-11 20:39:24] Error in run 733: Run already exists in server. Run id(s): {8924473}
[2018-04-11 20:39:24] Error in run 732: Run already exists in server. Run id(s): {8924471}
[2018-04-11 20:39:24] Started run 740 on task 45, dataset 'splice'.
[2018-04-11 20:39:24] Started run 741 on task 45, dataset 'splice'.
[2018-04-11 20:39:25] Error in run 734: Run already exists in server. Run id(s): {8924472}
[2018-04-11 20:39:25] Started run 742 on task 45, dataset 'splice'.
[2018-04-11 20:39:26] Error in run 735: Run already exists in server. Run id(s): {8924474}
[2018-04-11 20:39:26] Error in run 736: Run already exists in server. Run id(s): {8924476}
[2018-04-11 20:39:26] Started run 743 on task 45, dataset 'splice'.
[2018-04-11 20:39:26] Started run 744 on task 45, dataset 'splice'.
[2018-04-11 20:39:27] Error in run 737: Run already exists in server. Run id(s): {8924478}
[2018-04-11 20:39:27] Started run 745 on task 45, dataset 'splice'.
[2018-04-11 20:39:28] Error in run 738: Run already exists in server. Run id(s): {8924479}
[2018-04-11 20:39:28] Started run 746 on task 45, dataset 'splice'.
[2018-04-11 20:39:28] Error in run 739: Run already exists in server. Run id(s): {8924477}
[2018-04-11 20:39:28] Started run 747 on task 45, dataset 'splice'.
[2018-04-11 20:39:29] Error in run 741: Run already exists in server. Run id(s): {8924482}
[2018-04-11 20:39:29] Error in run 740: Run already exists in server. Run id(s): {8924480}
[2018-04-11 20:39:29] Started run 748 on task 45, dataset 'splice'.
[2018-04-11 20:39:29] Started run 749 on task 45, dataset 'splice'.
[2018-04-11 20:39:29] Error in run 742: Run already exists in server. Run id(s): {8924481}
[2018-04-11 20:39:29] Started run 750 on task 45, dataset 'splice'.
[2018-04-11 20:39:30] Error in run 743: Run already exists in server. Run id(s): {8924483}
[2018-04-11 20:39:30] Started run 751 on task 45, dataset 'splice'.
[2018-04-11 20:39:30] Error in run 744: Run already exists in server. Run id(s): {8924484}
[2018-04-11 20:39:30] Started run 752 on task 45, dataset 'splice'.
[2018-04-11 20:39:31] Error in run 745: Run already exists in server. Run id(s): {8924485}
[2018-04-11 20:39:31] Started run 753 on task 45, dataset 'splice'.
[2018-04-11 20:39:32] Error in run 746: Run already exists in server. Run id(s): {8924489}
[2018-04-11 20:39:32] Started run 754 on task 45, dataset 'splice'.
[2018-04-11 20:39:33] Error in run 747: Run already exists in server. Run id(s): {8924491}
[2018-04-11 20:39:33] Started run 755 on task 45, dataset 'splice'.
[2018-04-11 20:39:33] Error in run 749: Run already exists in server. Run id(s): {8924488}
[2018-04-11 20:39:33] Error in run 748: Run already exists in server. Run id(s): {8924490}
[2018-04-11 20:39:33] Started run 756 on task 45, dataset 'splice'.
[2018-04-11 20:39:33] Started run 757 on task 45, dataset 'splice'.
[2018-04-11 20:39:34] Error in run 750: Run already exists in server. Run id(s): {8924493}
[2018-04-11 20:39:34] Started run 758 on task 45, dataset 'splice'.
[2018-04-11 20:39:35] Error in run 751: Run already exists in server. Run id(s): {8924495}
[2018-04-11 20:39:35] Started run 759 on task 45, dataset 'splice'.
[2018-04-11 20:39:35] Error in run 752: Run already exists in server. Run id(s): {8924496}
[2018-04-11 20:39:35] Started run 760 on task 45, dataset 'splice'.
[2018-04-11 20:39:36] Error in run 753: Run already exists in server. Run id(s): {8924494}
[2018-04-11 20:39:36] Started run 761 on task 45, dataset 'splice'.
[2018-04-11 20:39:37] Error in run 754: Run already exists in server. Run id(s): {8924497}
[2018-04-11 20:39:37] Started run 762 on task 45, dataset 'splice'.
[2018-04-11 20:39:37] Error in run 755: Run already exists in server. Run id(s): {8924498}
[2018-04-11 20:39:37] Started run 763 on task 45, dataset 'splice'.
[2018-04-11 20:39:38] Error in run 757: Run already exists in server. Run id(s): {8924500}
[2018-04-11 20:39:38] Error in run 756: Run already exists in server. Run id(s): {8924501}
[2018-04-11 20:39:38] Started run 764 on task 45, dataset 'splice'.
[2018-04-11 20:39:38] Started run 765 on task 45, dataset 'splice'.
[2018-04-11 20:39:39] Error in run 758: Run already exists in server. Run id(s): {8924502}
[2018-04-11 20:39:39] Started run 766 on task 45, dataset 'splice'.
[2018-04-11 20:39:40] Error in run 760: Run already exists in server. Run id(s): {8924503}
[2018-04-11 20:39:40] Error in run 759: Run already exists in server. Run id(s): {8924506}
[2018-04-11 20:39:40] Started run 767 on task 45, dataset 'splice'.
[2018-04-11 20:39:40] Started run 768 on task 45, dataset 'splice'.
[2018-04-11 20:39:40] Error in run 761: Run already exists in server. Run id(s): {8924504}
[2018-04-11 20:39:40] Started run 769 on task 45, dataset 'splice'.
[2018-04-11 20:39:42] Error in run 762: Run already exists in server. Run id(s): {8924507}
[2018-04-11 20:39:42] Started run 770 on task 45, dataset 'splice'.
[2018-04-11 20:39:42] Error in run 763: Run already exists in server. Run id(s): {8924505}
[2018-04-11 20:39:42] Started run 771 on task 45, dataset 'splice'.
[2018-04-11 20:39:43] Error in run 765: Run already exists in server. Run id(s): {8924510}
[2018-04-11 20:39:43] Error in run 764: Run already exists in server. Run id(s): {8924509}
[2018-04-11 20:39:43] Started run 772 on task 45, dataset 'splice'.
[2018-04-11 20:39:43] Started run 773 on task 45, dataset 'splice'.
[2018-04-11 20:39:43] Error in run 766: Run already exists in server. Run id(s): {8924511}
[2018-04-11 20:39:43] Started run 774 on task 45, dataset 'splice'.
[2018-04-11 20:39:44] Error in run 767: Run already exists in server. Run id(s): {8924512}
[2018-04-11 20:39:44] Error in run 768: Run already exists in server. Run id(s): {8924513}
[2018-04-11 20:39:44] Started run 775 on task 45, dataset 'splice'.
[2018-04-11 20:39:44] Started run 776 on task 45, dataset 'splice'.
[2018-04-11 20:39:45] Error in run 769: Run already exists in server. Run id(s): {8924514}
[2018-04-11 20:39:45] Started run 777 on task 45, dataset 'splice'.
[2018-04-11 20:39:46] Error in run 770: Run already exists in server. Run id(s): {8924516}
[2018-04-11 20:39:46] Started run 778 on task 45, dataset 'splice'.
[2018-04-11 20:39:47] Error in run 771: Run already exists in server. Run id(s): {8924518}
[2018-04-11 20:39:47] Started run 779 on task 45, dataset 'splice'.
[2018-04-11 20:39:47] Error in run 772: Run already exists in server. Run id(s): {8924517}
[2018-04-11 20:39:47] Error in run 773: Run already exists in server. Run id(s): {8924515}
[2018-04-11 20:39:47] Started run 780 on task 45, dataset 'splice'.
[2018-04-11 20:39:47] Started run 781 on task 45, dataset 'splice'.
[2018-04-11 20:39:48] Error in run 774: Run already exists in server. Run id(s): {8924519}
[2018-04-11 20:39:48] Started run 782 on task 45, dataset 'splice'.
[2018-04-11 20:39:49] Error in run 776: Run already exists in server. Run id(s): {8924524}
[2018-04-11 20:39:49] Error in run 775: Run already exists in server. Run id(s): {8924521}
[2018-04-11 20:39:49] Started run 783 on task 45, dataset 'splice'.
[2018-04-11 20:39:49] Started run 784 on task 45, dataset 'splice'.
[2018-04-11 20:39:50] Error in run 777: Run already exists in server. Run id(s): {8924522}
[2018-04-11 20:39:50] Started run 785 on task 45, dataset 'splice'.
[2018-04-11 20:39:51] Error in run 778: Run already exists in server. Run id(s): {8924523}
[2018-04-11 20:39:51] Started run 786 on task 45, dataset 'splice'.
[2018-04-11 20:39:51] Error in run 779: Run already exists in server. Run id(s): {8924527}
[2018-04-11 20:39:51] Started run 787 on task 45, dataset 'splice'.
[2018-04-11 20:39:52] Error in run 780: Run already exists in server. Run id(s): {8924528}
[2018-04-11 20:39:52] Error in run 781: Run already exists in server. Run id(s): {8924526}
[2018-04-11 20:39:52] Started run 788 on task 45, dataset 'splice'.
[2018-04-11 20:39:52] Started run 789 on task 45, dataset 'splice'.
[2018-04-11 20:39:53] Error in run 782: Run already exists in server. Run id(s): {8924525}
[2018-04-11 20:39:53] Started run 790 on task 45, dataset 'splice'.
[2018-04-11 20:39:54] Error in run 783: Run already exists in server. Run id(s): {8924529}
[2018-04-11 20:39:54] Error in run 784: Run already exists in server. Run id(s): {8924530}
[2018-04-11 20:39:54] Started run 791 on task 45, dataset 'splice'.
[2018-04-11 20:39:54] Started run 792 on task 45, dataset 'splice'.
[2018-04-11 20:39:54] Error in run 785: Run already exists in server. Run id(s): {8924531}
[2018-04-11 20:39:54] Started run 793 on task 45, dataset 'splice'.
[2018-04-11 20:39:55] Error in run 786: Run already exists in server. Run id(s): {8924532}
[2018-04-11 20:39:55] Started run 794 on task 45, dataset 'splice'.
[2018-04-11 20:39:56] Error in run 787: Run already exists in server. Run id(s): {8924537}
[2018-04-11 20:39:56] Started run 795 on task 45, dataset 'splice'.
[2018-04-11 20:39:57] Error in run 788: Run already exists in server. Run id(s): {8924536}
[2018-04-11 20:39:57] Error in run 789: Run already exists in server. Run id(s): {8924534}
[2018-04-11 20:39:57] Started run 796 on task 45, dataset 'splice'.
[2018-04-11 20:39:57] Started run 797 on task 45, dataset 'splice'.
[2018-04-11 20:39:58] Error in run 790: Run already exists in server. Run id(s): {8924540}
[2018-04-11 20:39:58] Started run 798 on task 45, dataset 'splice'.
[2018-04-11 20:39:58] Error in run 792: Run already exists in server. Run id(s): {8924539}
[2018-04-11 20:39:58] Error in run 791: Run already exists in server. Run id(s): {8924543}
[2018-04-11 20:39:58] Started run 799 on task 45, dataset 'splice'.
[2018-04-11 20:39:58] Started run 800 on task 45, dataset 'splice'.
[2018-04-11 20:39:59] Error in run 793: Run already exists in server. Run id(s): {8924541}
[2018-04-11 20:39:59] Started run 801 on task 45, dataset 'splice'.
[2018-04-11 20:40:00] Error in run 794: Run already exists in server. Run id(s): {8924547}
[2018-04-11 20:40:00] Started run 802 on task 45, dataset 'splice'.
[2018-04-11 20:40:01] Error in run 795: Run already exists in server. Run id(s): {8924545}
[2018-04-11 20:40:01] Started run 803 on task 45, dataset 'splice'.
[2018-04-11 20:40:01] Error in run 797: Run already exists in server. Run id(s): {8924548}
[2018-04-11 20:40:01] Error in run 796: Run already exists in server. Run id(s): {8924550}
[2018-04-11 20:40:01] Started run 804 on task 45, dataset 'splice'.
[2018-04-11 20:40:01] Started run 805 on task 45, dataset 'splice'.
[2018-04-11 20:40:02] Error in run 798: Run already exists in server. Run id(s): {8924553}
[2018-04-11 20:40:02] Started run 806 on task 45, dataset 'splice'.
[2018-04-11 20:40:03] Error in run 799: Run already exists in server. Run id(s): {8924555}
[2018-04-11 20:40:03] Error in run 800: Run already exists in server. Run id(s): {8924552}
[2018-04-11 20:40:03] Started run 807 on task 45, dataset 'splice'.
[2018-04-11 20:40:03] Started run 808 on task 45, dataset 'splice'.
[2018-04-11 20:40:04] Error in run 801: Run already exists in server. Run id(s): {8924554}
[2018-04-11 20:40:04] Started run 809 on task 45, dataset 'splice'.
[2018-04-11 20:40:05] Error in run 802: Run already exists in server. Run id(s): {8924557}
[2018-04-11 20:40:05] Started run 810 on task 45, dataset 'splice'.
[2018-04-11 20:40:05] Error in run 803: Run already exists in server. Run id(s): {8924560}
[2018-04-11 20:40:05] Started run 811 on task 45, dataset 'splice'.
[2018-04-11 20:40:06] Error in run 804: Run already exists in server. Run id(s): {8924561}
[2018-04-11 20:40:06] Error in run 805: Run already exists in server. Run id(s): {8924558}
[2018-04-11 20:40:06] Started run 812 on task 45, dataset 'splice'.
[2018-04-11 20:40:06] Started run 813 on task 45, dataset 'splice'.
[2018-04-11 20:40:07] Error in run 806: Run already exists in server. Run id(s): {8924563}
[2018-04-11 20:40:07] Started run 814 on task 45, dataset 'splice'.
[2018-04-11 20:40:08] Error in run 808: Run already exists in server. Run id(s): {8924564}
[2018-04-11 20:40:08] Error in run 807: Run already exists in server. Run id(s): {8924562}
[2018-04-11 20:40:08] Started run 815 on task 45, dataset 'splice'.
[2018-04-11 20:40:08] Started run 816 on task 45, dataset 'splice'.
[2018-04-11 20:40:08] Error in run 809: Run already exists in server. Run id(s): {8924567}
[2018-04-11 20:40:08] Started run 817 on task 45, dataset 'splice'.
[2018-04-11 20:40:09] Error in run 810: Run already exists in server. Run id(s): {8924566}
[2018-04-11 20:40:09] Started run 818 on task 45, dataset 'splice'.
[2018-04-11 20:40:10] Error in run 811: Run already exists in server. Run id(s): {8924565}
[2018-04-11 20:40:10] Started run 819 on task 45, dataset 'splice'.
[2018-04-11 20:40:11] Error in run 813: Run already exists in server. Run id(s): {8924570}
[2018-04-11 20:40:11] Error in run 812: Run already exists in server. Run id(s): {8924569}
[2018-04-11 20:40:11] Started run 820 on task 45, dataset 'splice'.
[2018-04-11 20:40:11] Started run 821 on task 45, dataset 'splice'.
[2018-04-11 20:40:12] Error in run 814: Run already exists in server. Run id(s): {8924571}
[2018-04-11 20:40:12] Started run 822 on task 45, dataset 'splice'.
[2018-04-11 20:40:12] Error in run 815: Run already exists in server. Run id(s): {8924568}
[2018-04-11 20:40:12] Error in run 816: Run already exists in server. Run id(s): {8924575}
[2018-04-11 20:40:12] Started run 823 on task 45, dataset 'splice'.
[2018-04-11 20:40:12] Started run 824 on task 45, dataset 'splice'.
[2018-04-11 20:40:13] Error in run 817: Run already exists in server. Run id(s): {8924574}
[2018-04-11 20:40:13] Started run 825 on task 45, dataset 'splice'.
[2018-04-11 20:40:14] Error in run 818: Run already exists in server. Run id(s): {8924573}
[2018-04-11 20:40:14] Started run 826 on task 45, dataset 'splice'.
[2018-04-11 20:40:15] Error in run 819: Run already exists in server. Run id(s): {8924577}
[2018-04-11 20:40:15] Started run 827 on task 45, dataset 'splice'.
[2018-04-11 20:40:16] Error in run 820: Run already exists in server. Run id(s): {8924579}
[2018-04-11 20:40:16] Error in run 821: Run already exists in server. Run id(s): {8924578}
[2018-04-11 20:40:16] Started run 828 on task 45, dataset 'splice'.
[2018-04-11 20:40:16] Started run 829 on task 45, dataset 'splice'.
[2018-04-11 20:40:16] Error in run 822: Run already exists in server. Run id(s): {8924580}
[2018-04-11 20:40:16] Started run 830 on task 45, dataset 'splice'.
[2018-04-11 20:40:17] Error in run 823: Run already exists in server. Run id(s): {8924581}
[2018-04-11 20:40:17] Started run 831 on task 45, dataset 'splice'.
[2018-04-11 20:40:17] Error in run 824: Run already exists in server. Run id(s): {8924582}
[2018-04-11 20:40:17] Started run 832 on task 45, dataset 'splice'.
[2018-04-11 20:40:18] Error in run 825: Run already exists in server. Run id(s): {8924584}
[2018-04-11 20:40:18] Started run 833 on task 45, dataset 'splice'.
[2018-04-11 20:40:19] Error in run 826: Run already exists in server. Run id(s): {8924586}
[2018-04-11 20:40:19] Started run 834 on task 45, dataset 'splice'.
[2018-04-11 20:40:19] Error in run 827: Run already exists in server. Run id(s): {8924588}
[2018-04-11 20:40:19] Started run 835 on task 45, dataset 'splice'.
[2018-04-11 20:40:20] Error in run 829: Run already exists in server. Run id(s): {8924590}
[2018-04-11 20:40:20] Error in run 828: Run already exists in server. Run id(s): {8924585}
[2018-04-11 20:40:20] Started run 836 on task 45, dataset 'splice'.
[2018-04-11 20:40:20] Started run 837 on task 45, dataset 'splice'.
[2018-04-11 20:40:21] Error in run 830: Run already exists in server. Run id(s): {8924591}
[2018-04-11 20:40:21] Started run 838 on task 45, dataset 'splice'.
[2018-04-11 20:40:22] Error in run 831: Run already exists in server. Run id(s): {8924592}
[2018-04-11 20:40:22] Started run 839 on task 45, dataset 'splice'.
[2018-04-11 20:40:22] Error in run 832: Run already exists in server. Run id(s): {8924593}
[2018-04-11 20:40:22] Started run 840 on task 45, dataset 'splice'.
[2018-04-11 20:40:23] Error in run 833: Run already exists in server. Run id(s): {8924594}
[2018-04-11 20:40:23] Started run 841 on task 45, dataset 'splice'.
[2018-04-11 20:40:23] Error in run 834: Run already exists in server. Run id(s): {8924598}
[2018-04-11 20:40:23] Started run 842 on task 45, dataset 'splice'.
[2018-04-11 20:40:24] Error in run 835: Run already exists in server. Run id(s): {8924596}
[2018-04-11 20:40:24] Started run 843 on task 45, dataset 'splice'.
[2018-04-11 20:40:25] Error in run 836: Run already exists in server. Run id(s): {8924597}
[2018-04-11 20:40:25] Error in run 837: Run already exists in server. Run id(s): {8924599}
[2018-04-11 20:40:25] Started run 844 on task 45, dataset 'splice'.
[2018-04-11 20:40:25] Started run 845 on task 45, dataset 'splice'.
[2018-04-11 20:40:26] Error in run 838: Run already exists in server. Run id(s): {8924602}
[2018-04-11 20:40:26] Started run 846 on task 45, dataset 'splice'.
[2018-04-11 20:40:26] Error in run 839: Run already exists in server. Run id(s): {8924604}
[2018-04-11 20:40:26] Started run 847 on task 45, dataset 'splice'.
[2018-04-11 20:40:26] Error in run 840: Run already exists in server. Run id(s): {8924606}
[2018-04-11 20:40:26] Started run 848 on task 45, dataset 'splice'.
[2018-04-11 20:40:27] Error in run 841: Run already exists in server. Run id(s): {8924603}
[2018-04-11 20:40:27] Started run 849 on task 45, dataset 'splice'.
[2018-04-11 20:40:28] Error in run 842: Run already exists in server. Run id(s): {8924610}
[2018-04-11 20:40:28] Started run 850 on task 45, dataset 'splice'.
[2018-04-11 20:40:29] Error in run 843: Run already exists in server. Run id(s): {8924608}
[2018-04-11 20:40:29] Started run 851 on task 45, dataset 'splice'.
[2018-04-11 20:40:30] Error in run 844: Run already exists in server. Run id(s): {8924609}
[2018-04-11 20:40:30] Started run 852 on task 45, dataset 'splice'.
[2018-04-11 20:40:30] Error in run 845: Run already exists in server. Run id(s): {8924612}
[2018-04-11 20:40:30] Started run 853 on task 45, dataset 'splice'.
[2018-04-11 20:40:30] Error in run 846: Run already exists in server. Run id(s): {8924616}
[2018-04-11 20:40:30] Started run 854 on task 45, dataset 'splice'.
[2018-04-11 20:40:31] Error in run 847: Run already exists in server. Run id(s): {8924613}
[2018-04-11 20:40:31] Started run 855 on task 45, dataset 'splice'.
[2018-04-11 20:40:31] Error in run 848: Run already exists in server. Run id(s): {8924617}
[2018-04-11 20:40:31] Started run 856 on task 45, dataset 'splice'.
[2018-04-11 20:40:32] Error in run 849: Run already exists in server. Run id(s): {8924615}
[2018-04-11 20:40:32] Started run 857 on task 45, dataset 'splice'.
[2018-04-11 20:40:33] Error in run 850: Run already exists in server. Run id(s): {8924619}
[2018-04-11 20:40:33] Started run 858 on task 45, dataset 'splice'.
[2018-04-11 20:40:34] Error in run 851: Run already exists in server. Run id(s): {8924621}
[2018-04-11 20:40:34] Started run 859 on task 45, dataset 'splice'.
[2018-04-11 20:40:34] Error in run 852: Run already exists in server. Run id(s): {8924622}
[2018-04-11 20:40:34] Error in run 853: Run already exists in server. Run id(s): {8924625}
[2018-04-11 20:40:34] Started run 860 on task 45, dataset 'splice'.
[2018-04-11 20:40:34] Started run 861 on task 45, dataset 'splice'.
[2018-04-11 20:40:35] Error in run 854: Run already exists in server. Run id(s): {8924624}
[2018-04-11 20:40:35] Started run 862 on task 45, dataset 'splice'.
[2018-04-11 20:40:35] Error in run 855: Run already exists in server. Run id(s): {8924626}
[2018-04-11 20:40:35] Started run 863 on task 45, dataset 'splice'.
[2018-04-11 20:40:36] Error in run 856: Run already exists in server. Run id(s): {8924627}
[2018-04-11 20:40:36] Started run 864 on task 45, dataset 'splice'.
[2018-04-11 20:40:37] Error in run 857: Run already exists in server. Run id(s): {8924628}
[2018-04-11 20:40:37] Started run 865 on task 45, dataset 'splice'.
[2018-04-11 20:40:37] Error in run 858: Run already exists in server. Run id(s): {8924632}
[2018-04-11 20:40:37] Started run 866 on task 45, dataset 'splice'.
[2018-04-11 20:40:38] Error in run 859: Run already exists in server. Run id(s): {8924631}
[2018-04-11 20:40:38] Started run 867 on task 45, dataset 'splice'.
[2018-04-11 20:40:39] Error in run 861: Run already exists in server. Run id(s): {8924635}
[2018-04-11 20:40:39] Error in run 860: Run already exists in server. Run id(s): {8924633}
[2018-04-11 20:40:39] Started run 868 on task 45, dataset 'splice'.
[2018-04-11 20:40:39] Started run 869 on task 45, dataset 'splice'.
[2018-04-11 20:40:39] Error in run 862: Run already exists in server. Run id(s): {8964071}
[2018-04-11 20:40:39] Started run 870 on task 45, dataset 'splice'.
[2018-04-11 20:40:40] Error in run 863: Run already exists in server. Run id(s): {8924637}
[2018-04-11 20:40:40] Started run 871 on task 45, dataset 'splice'.
[2018-04-11 20:40:41] Error in run 864: Run already exists in server. Run id(s): {8924641}
[2018-04-11 20:40:41] Started run 872 on task 45, dataset 'splice'.
[2018-04-11 20:40:41] Error in run 865: Run already exists in server. Run id(s): {8924639}
[2018-04-11 20:40:41] Started run 873 on task 45, dataset 'splice'.
[2018-04-11 20:40:42] Error in run 866: Run already exists in server. Run id(s): {8924645}
[2018-04-11 20:40:42] Started run 874 on task 45, dataset 'splice'.
[2018-04-11 20:40:43] Error in run 867: Run already exists in server. Run id(s): {8924644}
[2018-04-11 20:40:43] Started run 875 on task 45, dataset 'splice'.
[2018-04-11 20:40:44] Error in run 868: Run already exists in server. Run id(s): {8924646}
[2018-04-11 20:40:44] Started run 876 on task 45, dataset 'splice'.
[2018-04-11 20:40:44] Error in run 869: Run already exists in server. Run id(s): {8924643}
[2018-04-11 20:40:44] Started run 877 on task 45, dataset 'splice'.
[2018-04-11 20:40:44] Error in run 870: Run already exists in server. Run id(s): {8964075}
[2018-04-11 20:40:44] Started run 878 on task 45, dataset 'splice'.
[2018-04-11 20:40:44] Error in run 871: Run already exists in server. Run id(s): {8924650}
[2018-04-11 20:40:44] Started run 879 on task 45, dataset 'splice'.
[2018-04-11 20:40:45] Error in run 872: Run already exists in server. Run id(s): {8924651}
[2018-04-11 20:40:45] Started run 880 on task 45, dataset 'splice'.
[2018-04-11 20:40:46] Error in run 873: Run already exists in server. Run id(s): {8924649}
[2018-04-11 20:40:46] Started run 881 on task 45, dataset 'splice'.
[2018-04-11 20:40:47] Error in run 874: Run already exists in server. Run id(s): {8924652}
[2018-04-11 20:40:47] Started run 882 on task 45, dataset 'splice'.
[2018-04-11 20:40:48] Error in run 875: Run already exists in server. Run id(s): {8924653}
[2018-04-11 20:40:48] Started run 883 on task 45, dataset 'splice'.
[2018-04-11 20:40:48] Error in run 878: Run already exists in server. Run id(s): {8924656}
[2018-04-11 20:40:48] Error in run 876: Run already exists in server. Run id(s): {8924654}
[2018-04-11 20:40:48] Error in run 877: Run already exists in server. Run id(s): {8924655}
[2018-04-11 20:40:48] Started run 884 on task 45, dataset 'splice'.
[2018-04-11 20:40:48] Started run 886 on task 45, dataset 'splice'.
[2018-04-11 20:40:48] Started run 885 on task 45, dataset 'splice'.
[2018-04-11 20:40:49] Error in run 879: Run already exists in server. Run id(s): {8924657}
[2018-04-11 20:40:49] Started run 887 on task 45, dataset 'splice'.
[2018-04-11 20:40:50] Error in run 880: Run already exists in server. Run id(s): {8924658}
[2018-04-11 20:40:50] Started run 888 on task 45, dataset 'splice'.
[2018-04-11 20:40:51] Error in run 881: Run already exists in server. Run id(s): {8924659}
[2018-04-11 20:40:51] Started run 889 on task 45, dataset 'splice'.
[2018-04-11 20:40:51] Error in run 882: Run already exists in server. Run id(s): {8924660}
[2018-04-11 20:40:51] Started run 890 on task 45, dataset 'splice'.
[2018-04-11 20:40:52] Error in run 883: Run already exists in server. Run id(s): {8924663}
[2018-04-11 20:40:52] Started run 891 on task 45, dataset 'splice'.
[2018-04-11 20:40:53] Error in run 884: Run already exists in server. Run id(s): {8924664}
[2018-04-11 20:40:53] Error in run 886: Run already exists in server. Run id(s): {8924666}
[2018-04-11 20:40:53] Error in run 885: Run already exists in server. Run id(s): {8924665}
[2018-04-11 20:40:53] Started run 892 on task 45, dataset 'splice'.
[2018-04-11 20:40:53] Started run 893 on task 45, dataset 'splice'.
[2018-04-11 20:40:53] Started run 894 on task 45, dataset 'splice'.
[2018-04-11 20:40:53] Error in run 887: Run already exists in server. Run id(s): {8924667}
[2018-04-11 20:40:53] Started run 895 on task 45, dataset 'splice'.
[2018-04-11 20:40:55] Error in run 888: Run already exists in server. Run id(s): {8924670}
[2018-04-11 20:40:55] Started run 896 on task 45, dataset 'splice'.
[2018-04-11 20:40:55] Error in run 889: Run already exists in server. Run id(s): {8924669}
[2018-04-11 20:40:55] Started run 897 on task 45, dataset 'splice'.
[2018-04-11 20:40:56] Error in run 890: Run already exists in server. Run id(s): {8924668}
[2018-04-11 20:40:56] Started run 898 on task 45, dataset 'splice'.
[2018-04-11 20:40:57] Error in run 891: Run already exists in server. Run id(s): {8924671}
[2018-04-11 20:40:57] Started run 899 on task 45, dataset 'splice'.
[2018-04-11 20:40:58] Error in run 894: Run already exists in server. Run id(s): {8924676}
[2018-04-11 20:40:58] Error in run 893: Run already exists in server. Run id(s): {8924674}
[2018-04-11 20:40:58] Started run 900 on task 45, dataset 'splice'.
[2018-04-11 20:40:58] Error in run 892: Run already exists in server. Run id(s): {8924673}
[2018-04-11 20:40:58] Started run 902 on task 45, dataset 'splice'.
[2018-04-11 20:40:58] Started run 901 on task 45, dataset 'splice'.
[2018-04-11 20:40:58] Error in run 895: Run already exists in server. Run id(s): {8924675}
[2018-04-11 20:40:58] Started run 903 on task 45, dataset 'splice'.
[2018-04-11 20:40:59] Error in run 896: Run already exists in server. Run id(s): {8924679}
[2018-04-11 20:40:59] Started run 904 on task 45, dataset 'splice'.
[2018-04-11 20:41:00] Error in run 897: Run already exists in server. Run id(s): {8924677}
[2018-04-11 20:41:00] Started run 905 on task 45, dataset 'splice'.
[2018-04-11 20:41:01] Error in run 898: Run already exists in server. Run id(s): {8924678}
[2018-04-11 20:41:01] Started run 906 on task 45, dataset 'splice'.
[2018-04-11 20:41:02] Error in run 899: Run already exists in server. Run id(s): {8924680}
[2018-04-11 20:41:02] Started run 907 on task 45, dataset 'splice'.
[2018-04-11 20:41:02] Error in run 901: Run already exists in server. Run id(s): {8924684}
[2018-04-11 20:41:02] Started run 908 on task 45, dataset 'splice'.
[2018-04-11 20:41:03] Error in run 902: Run already exists in server. Run id(s): {8924682}
[2018-04-11 20:41:03] Error in run 900: Run already exists in server. Run id(s): {8924681}
[2018-04-11 20:41:03] Started run 909 on task 45, dataset 'splice'.
[2018-04-11 20:41:03] Started run 910 on task 45, dataset 'splice'.
[2018-04-11 20:41:03] Error in run 903: Run already exists in server. Run id(s): {8924685}
[2018-04-11 20:41:03] Started run 911 on task 45, dataset 'splice'.
[2018-04-11 20:41:04] Error in run 904: Run already exists in server. Run id(s): {8924688}
[2018-04-11 20:41:04] Started run 912 on task 45, dataset 'splice'.
[2018-04-11 20:41:05] Error in run 905: Run already exists in server. Run id(s): {8924690}
[2018-04-11 20:41:05] Started run 913 on task 45, dataset 'splice'.
[2018-04-11 20:41:05] Error in run 906: Run already exists in server. Run id(s): {8924693}
[2018-04-11 20:41:05] Started run 914 on task 45, dataset 'splice'.
[2018-04-11 20:41:06] Error in run 907: Run already exists in server. Run id(s): {8924692}
[2018-04-11 20:41:06] Started run 915 on task 45, dataset 'splice'.
[2018-04-11 20:41:07] Error in run 908: Run already exists in server. Run id(s): {8924691}
[2018-04-11 20:41:07] Started run 916 on task 45, dataset 'splice'.
[2018-04-11 20:41:07] Error in run 910: Run already exists in server. Run id(s): {8924694}
[2018-04-11 20:41:07] Error in run 909: Run already exists in server. Run id(s): {8924696}
[2018-04-11 20:41:07] Started run 917 on task 45, dataset 'splice'.
[2018-04-11 20:41:07] Started run 918 on task 45, dataset 'splice'.
[2018-04-11 20:41:08] Error in run 911: Run already exists in server. Run id(s): {8924699}
[2018-04-11 20:41:08] Started run 919 on task 45, dataset 'splice'.
[2018-04-11 20:41:09] Error in run 912: Run already exists in server. Run id(s): {8924698}
[2018-04-11 20:41:09] Started run 920 on task 45, dataset 'splice'.
[2018-04-11 20:41:09] Error in run 913: Run already exists in server. Run id(s): {8924701}
[2018-04-11 20:41:09] Started run 921 on task 45, dataset 'splice'.
[2018-04-11 20:41:10] Error in run 914: Run already exists in server. Run id(s): {8924706}
[2018-04-11 20:41:10] Started run 922 on task 45, dataset 'splice'.
[2018-04-11 20:41:11] Error in run 915: Run already exists in server. Run id(s): {8924705}
[2018-04-11 20:41:11] Started run 923 on task 45, dataset 'splice'.
[2018-04-11 20:41:12] Error in run 916: Run already exists in server. Run id(s): {8924704}
[2018-04-11 20:41:12] Started run 924 on task 45, dataset 'splice'.
[2018-04-11 20:41:12] Error in run 917: Run already exists in server. Run id(s): {8924707}
[2018-04-11 20:41:12] Started run 925 on task 45, dataset 'splice'.
[2018-04-11 20:41:12] Error in run 918: Run already exists in server. Run id(s): {8924710}
[2018-04-11 20:41:12] Started run 926 on task 45, dataset 'splice'.
[2018-04-11 20:41:12] Error in run 919: Run already exists in server. Run id(s): {8924714}
[2018-04-11 20:41:12] Started run 927 on task 45, dataset 'splice'.
[2018-04-11 20:41:13] Error in run 920: Run already exists in server. Run id(s): {8924713}
[2018-04-11 20:41:13] Started run 928 on task 45, dataset 'splice'.
[2018-04-11 20:41:14] Error in run 921: Run already exists in server. Run id(s): {8924717}
[2018-04-11 20:41:14] Started run 929 on task 45, dataset 'splice'.
[2018-04-11 20:41:15] Error in run 922: Run already exists in server. Run id(s): {8924722}
[2018-04-11 20:41:15] Started run 930 on task 45, dataset 'splice'.
[2018-04-11 20:41:15] Error in run 923: Run already exists in server. Run id(s): {8924721}
[2018-04-11 20:41:15] Started run 931 on task 45, dataset 'splice'.
[2018-04-11 20:41:16] Error in run 924: Run already exists in server. Run id(s): {8924719}
[2018-04-11 20:41:16] Started run 932 on task 45, dataset 'splice'.
[2018-04-11 20:41:16] Error in run 925: Run already exists in server. Run id(s): {8924724}
[2018-04-11 20:41:16] Started run 933 on task 45, dataset 'splice'.
[2018-04-11 20:41:17] Error in run 926: Run already exists in server. Run id(s): {8924723}
[2018-04-11 20:41:17] Started run 934 on task 45, dataset 'splice'.
[2018-04-11 20:41:17] Error in run 927: Run already exists in server. Run id(s): {8924727}
[2018-04-11 20:41:17] Started run 935 on task 45, dataset 'splice'.
[2018-04-11 20:41:18] Error in run 928: Run already exists in server. Run id(s): {8924725}
[2018-04-11 20:41:18] Started run 936 on task 45, dataset 'splice'.
[2018-04-11 20:41:19] Error in run 929: Run already exists in server. Run id(s): {8924728}
[2018-04-11 20:41:19] Started run 937 on task 45, dataset 'splice'.
[2018-04-11 20:41:19] Error in run 930: Run already exists in server. Run id(s): {8924730}
[2018-04-11 20:41:19] Started run 938 on task 45, dataset 'splice'.
[2018-04-11 20:41:20] Error in run 931: Run already exists in server. Run id(s): {8924732}
[2018-04-11 20:41:20] Started run 939 on task 45, dataset 'splice'.
[2018-04-11 20:41:21] Error in run 932: Run already exists in server. Run id(s): {8924731}
[2018-04-11 20:41:21] Error in run 933: Run already exists in server. Run id(s): {8924734}
[2018-04-11 20:41:21] Started run 940 on task 45, dataset 'splice'.
[2018-04-11 20:41:21] Started run 941 on task 45, dataset 'splice'.
[2018-04-11 20:41:21] Error in run 934: Run already exists in server. Run id(s): {8924733}
[2018-04-11 20:41:21] Started run 942 on task 45, dataset 'splice'.
[2018-04-11 20:41:21] Error in run 935: Run already exists in server. Run id(s): {8924738}
[2018-04-11 20:41:21] Started run 943 on task 45, dataset 'splice'.
[2018-04-11 20:41:22] Error in run 936: Run already exists in server. Run id(s): {8924740}
[2018-04-11 20:41:22] Started run 944 on task 45, dataset 'splice'.
[2018-04-11 20:41:23] Error in run 937: Run already exists in server. Run id(s): {8924742}
[2018-04-11 20:41:23] Started run 945 on task 45, dataset 'splice'.
[2018-04-11 20:41:24] Error in run 938: Run already exists in server. Run id(s): {8924739}
[2018-04-11 20:41:24] Started run 946 on task 45, dataset 'splice'.
[2018-04-11 20:41:25] Error in run 939: Run already exists in server. Run id(s): {8924745}
[2018-04-11 20:41:25] Started run 947 on task 45, dataset 'splice'.
[2018-04-11 20:41:25] Error in run 940: Run already exists in server. Run id(s): {8924746}
[2018-04-11 20:41:25] Error in run 941: Run already exists in server. Run id(s): {8924743}
[2018-04-11 20:41:25] Started run 948 on task 45, dataset 'splice'.
[2018-04-11 20:41:25] Started run 949 on task 45, dataset 'splice'.
[2018-04-11 20:41:26] Error in run 942: Run already exists in server. Run id(s): {8924748}
[2018-04-11 20:41:26] Started run 950 on task 45, dataset 'splice'.
[2018-04-11 20:41:26] Error in run 943: Run already exists in server. Run id(s): {8924749}
[2018-04-11 20:41:26] Started run 951 on task 45, dataset 'splice'.
[2018-04-11 20:41:27] Error in run 944: Run already exists in server. Run id(s): {8924752}
[2018-04-11 20:41:27] Started run 952 on task 45, dataset 'splice'.
[2018-04-11 20:41:28] Error in run 945: Run already exists in server. Run id(s): {8924751}
[2018-04-11 20:41:28] Started run 953 on task 45, dataset 'splice'.
[2018-04-11 20:41:28] Error in run 946: Run already exists in server. Run id(s): {8924750}
[2018-04-11 20:41:28] Started run 954 on task 45, dataset 'splice'.
[2018-04-11 20:41:29] Error in run 947: Run already exists in server. Run id(s): {8924756}
[2018-04-11 20:41:29] Started run 955 on task 45, dataset 'splice'.
[2018-04-11 20:41:30] Error in run 948: Run already exists in server. Run id(s): {8924758}
[2018-04-11 20:41:30] Started run 956 on task 45, dataset 'splice'.
[2018-04-11 20:41:30] Error in run 949: Run already exists in server. Run id(s): {8924757}
[2018-04-11 20:41:30] Started run 957 on task 45, dataset 'splice'.
[2018-04-11 20:41:30] Error in run 950: Run already exists in server. Run id(s): {8924759}
[2018-04-11 20:41:30] Started run 958 on task 45, dataset 'splice'.
[2018-04-11 20:41:31] Error in run 951: Run already exists in server. Run id(s): {8924760}
[2018-04-11 20:41:31] Started run 959 on task 45, dataset 'splice'.
[2018-04-11 20:41:31] Error in run 952: Run already exists in server. Run id(s): {8924762}
[2018-04-11 20:41:31] Started run 960 on task 45, dataset 'splice'.
[2018-04-11 20:41:32] Error in run 953: Run already exists in server. Run id(s): {8924766}
[2018-04-11 20:41:32] Started run 961 on task 45, dataset 'splice'.
[2018-04-11 20:41:33] Error in run 954: Run already exists in server. Run id(s): {8924761}
[2018-04-11 20:41:33] Started run 962 on task 45, dataset 'splice'.
[2018-04-11 20:41:34] Error in run 955: Run already exists in server. Run id(s): {8924770}
[2018-04-11 20:41:34] Started run 963 on task 45, dataset 'splice'.
[2018-04-11 20:41:35] Error in run 958: Run already exists in server. Run id(s): {8924771}
[2018-04-11 20:41:35] Error in run 957: Run already exists in server. Run id(s): {8924768}
[2018-04-11 20:41:35] Error in run 956: Run already exists in server. Run id(s): {8924769}
[2018-04-11 20:41:35] Started run 964 on task 45, dataset 'splice'.
[2018-04-11 20:41:35] Started run 966 on task 45, dataset 'splice'.
[2018-04-11 20:41:35] Started run 965 on task 45, dataset 'splice'.
[2018-04-11 20:41:35] Error in run 959: Run already exists in server. Run id(s): {8924773}
[2018-04-11 20:41:35] Started run 967 on task 45, dataset 'splice'.
[2018-04-11 20:41:36] Error in run 960: Run already exists in server. Run id(s): {8924774}
[2018-04-11 20:41:36] Started run 968 on task 45, dataset 'splice'.
[2018-04-11 20:41:37] Error in run 961: Run already exists in server. Run id(s): {8924775}
[2018-04-11 20:41:37] Started run 969 on task 45, dataset 'splice'.
[2018-04-11 20:41:38] Error in run 962: Run already exists in server. Run id(s): {8924778}
[2018-04-11 20:41:38] Started run 970 on task 45, dataset 'splice'.
[2018-04-11 20:41:38] Error in run 963: Run already exists in server. Run id(s): {8924780}
[2018-04-11 20:41:38] Started run 971 on task 45, dataset 'splice'.
[2018-04-11 20:41:39] Error in run 966: Run already exists in server. Run id(s): {8924783}
[2018-04-11 20:41:39] Error in run 964: Run already exists in server. Run id(s): {8924781}
[2018-04-11 20:41:39] Error in run 965: Run already exists in server. Run id(s): {8924782}
[2018-04-11 20:41:39] Started run 972 on task 45, dataset 'splice'.
[2018-04-11 20:41:39] Started run 973 on task 45, dataset 'splice'.
[2018-04-11 20:41:39] Started run 974 on task 45, dataset 'splice'.
[2018-04-11 20:41:40] Error in run 967: Run already exists in server. Run id(s): {8924785}
[2018-04-11 20:41:40] Started run 975 on task 45, dataset 'splice'.
[2018-04-11 20:41:41] Error in run 968: Run already exists in server. Run id(s): {8924787}
[2018-04-11 20:41:41] Started run 976 on task 45, dataset 'splice'.
[2018-04-11 20:41:42] Error in run 969: Run already exists in server. Run id(s): {8924788}
[2018-04-11 20:41:42] Started run 977 on task 45, dataset 'splice'.
[2018-04-11 20:41:42] Error in run 970: Run already exists in server. Run id(s): {8924789}
[2018-04-11 20:41:42] Started run 978 on task 45, dataset 'splice'.
[2018-04-11 20:41:43] Error in run 971: Run already exists in server. Run id(s): {8924791}
[2018-04-11 20:41:43] Started run 979 on task 45, dataset 'splice'.
[2018-04-11 20:41:44] Error in run 974: Run already exists in server. Run id(s): {8924794}
[2018-04-11 20:41:44] Error in run 973: Run already exists in server. Run id(s): {8924793}
[2018-04-11 20:41:44] Started run 980 on task 45, dataset 'splice'.
[2018-04-11 20:41:44] Error in run 972: Run already exists in server. Run id(s): {8924790}
[2018-04-11 20:41:44] Started run 981 on task 45, dataset 'splice'.
[2018-04-11 20:41:44] Started run 982 on task 45, dataset 'splice'.
[2018-04-11 20:41:44] Error in run 975: Run already exists in server. Run id(s): {8924796}
[2018-04-11 20:41:44] Started run 983 on task 45, dataset 'splice'.
[2018-04-11 20:41:45] Error in run 976: Run already exists in server. Run id(s): {8924797}
[2018-04-11 20:41:45] Started run 984 on task 45, dataset 'splice'.
[2018-04-11 20:41:46] Error in run 977: Run already exists in server. Run id(s): {8924795}
[2018-04-11 20:41:46] Started run 985 on task 45, dataset 'splice'.
[2018-04-11 20:41:47] Error in run 978: Run already exists in server. Run id(s): {8924803}
[2018-04-11 20:41:47] Started run 986 on task 45, dataset 'splice'.
[2018-04-11 20:41:48] Error in run 979: Run already exists in server. Run id(s): {8924804}
[2018-04-11 20:41:48] Started run 987 on task 45, dataset 'splice'.
[2018-04-11 20:41:49] Error in run 981: Run already exists in server. Run id(s): {8924802}
[2018-04-11 20:41:49] Error in run 980: Run already exists in server. Run id(s): {8924805}
[2018-04-11 20:41:49] Error in run 983: Run already exists in server. Run id(s): {8924813}
[2018-04-11 20:41:49] Started run 988 on task 45, dataset 'splice'.
[2018-04-11 20:41:49] Error in run 982: Run already exists in server. Run id(s): {8924809}
[2018-04-11 20:41:49] Started run 989 on task 45, dataset 'splice'.
[2018-04-11 20:41:49] Started run 991 on task 45, dataset 'splice'.
[2018-04-11 20:41:49] Started run 990 on task 45, dataset 'splice'.
[2018-04-11 20:41:50] Error in run 984: Run already exists in server. Run id(s): {8924811}
[2018-04-11 20:41:50] Started run 992 on task 45, dataset 'splice'.
[2018-04-11 20:41:51] Error in run 985: Run already exists in server. Run id(s): {8924812}
[2018-04-11 20:41:51] Started run 993 on task 45, dataset 'splice'.
[2018-04-11 20:41:52] Error in run 986: Run already exists in server. Run id(s): {8924816}
[2018-04-11 20:41:52] Started run 994 on task 45, dataset 'splice'.
[2018-04-11 20:41:53] Error in run 987: Run already exists in server. Run id(s): {8924818}
[2018-04-11 20:41:53] Started run 995 on task 45, dataset 'splice'.
[2018-04-11 20:41:53] Error in run 988: Run already exists in server. Run id(s): {8924817}
[2018-04-11 20:41:53] Error in run 991: Run already exists in server. Run id(s): {8924826}
[2018-04-11 20:41:53] Error in run 990: Run already exists in server. Run id(s): {8924822}
[2018-04-11 20:41:53] Error in run 989: Run already exists in server. Run id(s): {8924819}
[2018-04-11 20:41:53] Started run 996 on task 45, dataset 'splice'.
[2018-04-11 20:41:53] Started run 998 on task 45, dataset 'splice'.
[2018-04-11 20:41:53] Started run 997 on task 45, dataset 'splice'.
[2018-04-11 20:41:53] Started run 999 on task 45, dataset 'splice'.
[2018-04-11 20:41:55] Error in run 992: Run already exists in server. Run id(s): {8924825}
[2018-04-11 20:41:55] Started run 1000 on task 45, dataset 'splice'.
[2018-04-11 20:41:56] Error in run 993: Run already exists in server. Run id(s): {8924828}
[2018-04-11 20:41:56] Error in run 994: Run already exists in server. Run id(s): {8924829}
[2018-04-11 20:41:57] Error in run 995: Run already exists in server. Run id(s): {8924834}
[2018-04-11 20:41:58] Error in run 998: Run already exists in server. Run id(s): {8924832}
[2018-04-11 20:41:58] Error in run 996: Run already exists in server. Run id(s): {8964120}
[2018-04-11 20:41:58] Error in run 997: Run already exists in server. Run id(s): {8924830}
[2018-04-11 20:41:58] Error in run 999: Run already exists in server. Run id(s): {8924836}
[2018-04-11 20:42:00] Error in run 1000: Run already exists in server. Run id(s): {8924835}
