declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/svm2/job-1/task-00001/certs"
declare -x AZ_BATCH_JOB_ID="svm2"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/svm2/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/svm2/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_7-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/svm2/job-1/task-00001"
declare -x AZ_BATCH_TASK_ID="task-00001"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/svm2/job-1/task-00001/wd"
declare -x HOME="/mnt/batch/tasks/workitems/svm2/job-1/task-00001/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/svm2/job-1/task-00001/wd"
declare -x PWD="/mnt/batch/tasks/workitems/svm2/job-1/task-00001/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 22:10:31] Results will not be logged locally.
[2018-04-11 22:10:31] Retrieving tasks...
[2018-04-11 22:10:31] Tasks will be retrieved based on provided task ids.
[2018-04-11 22:10:31] The following tasks were retrieved: [146227].
[2018-04-11 22:10:38] Downloaded task 146227.
[2018-04-11 22:10:38] Prepared pipelines.
[2018-04-11 22:10:38] Started run 1 on task 146227, dataset 'churn'.
[2018-04-11 22:10:38] Started run 6 on task 146227, dataset 'churn'.
[2018-04-11 22:10:38] Started run 2 on task 146227, dataset 'churn'.
[2018-04-11 22:10:38] Started run 8 on task 146227, dataset 'churn'.
[2018-04-11 22:10:38] Started run 3 on task 146227, dataset 'churn'.
[2018-04-11 22:10:38] Started run 4 on task 146227, dataset 'churn'.
[2018-04-11 22:10:38] Started run 5 on task 146227, dataset 'churn'.
[2018-04-11 22:10:38] Started run 7 on task 146227, dataset 'churn'.
[2018-04-11 22:10:42] Error in run 8: Run already exists in server. Run id(s): {8984157}
[2018-04-11 22:10:42] Error in run 6: Run already exists in server. Run id(s): {8984155}
[2018-04-11 22:10:42] Started run 9 on task 146227, dataset 'churn'.
[2018-04-11 22:10:42] Started run 10 on task 146227, dataset 'churn'.
[2018-04-11 22:10:43] Error in run 2: Run already exists in server. Run id(s): {8984151}
[2018-04-11 22:10:43] Started run 11 on task 146227, dataset 'churn'.
[2018-04-11 22:10:43] Error in run 4: Run already exists in server. Run id(s): {8984149}
[2018-04-11 22:10:43] Started run 12 on task 146227, dataset 'churn'.
[2018-04-11 22:10:43] Error in run 5: Run already exists in server. Run id(s): {8984152}
[2018-04-11 22:10:43] Error in run 7: Run already exists in server. Run id(s): {8984154}
[2018-04-11 22:10:43] Started run 13 on task 146227, dataset 'churn'.
[2018-04-11 22:10:43] Started run 14 on task 146227, dataset 'churn'.
[2018-04-11 22:10:43] Error in run 1: Run already exists in server. Run id(s): {8941384}
[2018-04-11 22:10:43] Error in run 3: Run already exists in server. Run id(s): {8984150}
[2018-04-11 22:10:43] Started run 15 on task 146227, dataset 'churn'.
[2018-04-11 22:10:43] Started run 16 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Error in run 10: Run already exists in server. Run id(s): {8984158}
[2018-04-11 22:10:47] Started run 17 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Error in run 9: Run already exists in server. Run id(s): {8984159}
[2018-04-11 22:10:47] Started run 18 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Error in run 11: Run already exists in server. Run id(s): {8984160}
[2018-04-11 22:10:47] Started run 19 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Error in run 13: Run already exists in server. Run id(s): {8984167}
[2018-04-11 22:10:47] Started run 20 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Error in run 14: Run already exists in server. Run id(s): {8984168}
[2018-04-11 22:10:47] Error in run 12: Run already exists in server. Run id(s): {8984166}
[2018-04-11 22:10:47] Error in run 15: Run already exists in server. Run id(s): {8984171}
[2018-04-11 22:10:47] Started run 21 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Error in run 16: Run already exists in server. Run id(s): {8984175}
[2018-04-11 22:10:47] Started run 23 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Started run 22 on task 146227, dataset 'churn'.
[2018-04-11 22:10:47] Started run 24 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Error in run 17: Run already exists in server. Run id(s): {8984178}
[2018-04-11 22:10:52] Started run 25 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Error in run 18: Run already exists in server. Run id(s): {8984177}
[2018-04-11 22:10:52] Started run 26 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Error in run 19: Run already exists in server. Run id(s): {8984176}
[2018-04-11 22:10:52] Started run 27 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Error in run 20: Run already exists in server. Run id(s): {8984184}
[2018-04-11 22:10:52] Started run 28 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Error in run 24: Run already exists in server. Run id(s): {8984189}
[2018-04-11 22:10:52] Error in run 23: Run already exists in server. Run id(s): {8984183}
[2018-04-11 22:10:52] Started run 29 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Started run 30 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Error in run 22: Run already exists in server. Run id(s): {8984182}
[2018-04-11 22:10:52] Error in run 21: Run already exists in server. Run id(s): {8984185}
[2018-04-11 22:10:52] Started run 31 on task 146227, dataset 'churn'.
[2018-04-11 22:10:52] Started run 32 on task 146227, dataset 'churn'.
[2018-04-11 22:10:56] Error in run 25: Run already exists in server. Run id(s): {8984190}
[2018-04-11 22:10:56] Error in run 26: Run already exists in server. Run id(s): {8984191}
[2018-04-11 22:10:56] Started run 33 on task 146227, dataset 'churn'.
[2018-04-11 22:10:56] Started run 34 on task 146227, dataset 'churn'.
[2018-04-11 22:10:56] Error in run 27: Run already exists in server. Run id(s): {8984193}
[2018-04-11 22:10:56] Started run 35 on task 146227, dataset 'churn'.
[2018-04-11 22:10:56] Error in run 28: Run already exists in server. Run id(s): {8984194}
[2018-04-11 22:10:56] Started run 36 on task 146227, dataset 'churn'.
[2018-04-11 22:10:57] Error in run 30: Run already exists in server. Run id(s): {8984199}
[2018-04-11 22:10:57] Error in run 29: Run already exists in server. Run id(s): {8984196}
[2018-04-11 22:10:57] Started run 37 on task 146227, dataset 'churn'.
[2018-04-11 22:10:57] Started run 38 on task 146227, dataset 'churn'.
[2018-04-11 22:10:57] Error in run 32: Run already exists in server. Run id(s): {8984201}
[2018-04-11 22:10:57] Error in run 31: Run already exists in server. Run id(s): {8984198}
[2018-04-11 22:10:57] Started run 39 on task 146227, dataset 'churn'.
[2018-04-11 22:10:57] Started run 40 on task 146227, dataset 'churn'.
[2018-04-11 22:11:01] Error in run 35: Run already exists in server. Run id(s): {8984206}
[2018-04-11 22:11:01] Started run 41 on task 146227, dataset 'churn'.
[2018-04-11 22:11:01] Error in run 34: Run already exists in server. Run id(s): {8984204}
[2018-04-11 22:11:01] Started run 42 on task 146227, dataset 'churn'.
[2018-04-11 22:11:01] Error in run 36: Run already exists in server. Run id(s): {8984205}
[2018-04-11 22:11:01] Error in run 33: Run already exists in server. Run id(s): {8984200}
[2018-04-11 22:11:01] Started run 43 on task 146227, dataset 'churn'.
[2018-04-11 22:11:01] Started run 44 on task 146227, dataset 'churn'.
[2018-04-11 22:11:01] Error in run 38: Run already exists in server. Run id(s): {8984209}
[2018-04-11 22:11:01] Started run 45 on task 146227, dataset 'churn'.
[2018-04-11 22:11:01] Error in run 37: Run already exists in server. Run id(s): {8984207}
[2018-04-11 22:11:01] Started run 46 on task 146227, dataset 'churn'.
[2018-04-11 22:11:02] Error in run 40: Run already exists in server. Run id(s): {8984212}
[2018-04-11 22:11:02] Started run 47 on task 146227, dataset 'churn'.
[2018-04-11 22:11:02] Error in run 39: Run already exists in server. Run id(s): {8984214}
[2018-04-11 22:11:02] Started run 48 on task 146227, dataset 'churn'.
[2018-04-11 22:11:05] Error in run 41: Run already exists in server. Run id(s): {8984210}
[2018-04-11 22:11:05] Started run 49 on task 146227, dataset 'churn'.
[2018-04-11 22:11:05] Error in run 42: Run already exists in server. Run id(s): {8984216}
[2018-04-11 22:11:05] Started run 50 on task 146227, dataset 'churn'.
[2018-04-11 22:11:06] Error in run 43: Run already exists in server. Run id(s): {8984218}
[2018-04-11 22:11:06] Error in run 44: Run already exists in server. Run id(s): {8984219}
[2018-04-11 22:11:06] Started run 51 on task 146227, dataset 'churn'.
[2018-04-11 22:11:06] Started run 52 on task 146227, dataset 'churn'.
[2018-04-11 22:11:06] Error in run 45: Run already exists in server. Run id(s): {8984220}
[2018-04-11 22:11:06] Started run 53 on task 146227, dataset 'churn'.
[2018-04-11 22:11:06] Error in run 46: Run already exists in server. Run id(s): {8984225}
[2018-04-11 22:11:06] Started run 54 on task 146227, dataset 'churn'.
[2018-04-11 22:11:06] Error in run 47: Run already exists in server. Run id(s): {8984222}
[2018-04-11 22:11:06] Started run 55 on task 146227, dataset 'churn'.
[2018-04-11 22:11:06] Error in run 48: Run already exists in server. Run id(s): {8984223}
[2018-04-11 22:11:06] Started run 56 on task 146227, dataset 'churn'.
[2018-04-11 22:11:10] Error in run 50: Run already exists in server. Run id(s): {8984229}
[2018-04-11 22:11:10] Started run 57 on task 146227, dataset 'churn'.
[2018-04-11 22:11:10] Error in run 49: Run already exists in server. Run id(s): {8984228}
[2018-04-11 22:11:10] Started run 58 on task 146227, dataset 'churn'.
[2018-04-11 22:11:10] Error in run 51: Run already exists in server. Run id(s): {8984230}
[2018-04-11 22:11:10] Started run 59 on task 146227, dataset 'churn'.
[2018-04-11 22:11:10] Error in run 52: Run already exists in server. Run id(s): {8984231}
[2018-04-11 22:11:10] Started run 60 on task 146227, dataset 'churn'.
[2018-04-11 22:11:10] Error in run 53: Run already exists in server. Run id(s): {8984232}
[2018-04-11 22:11:10] Started run 61 on task 146227, dataset 'churn'.
[2018-04-11 22:11:10] Error in run 54: Run already exists in server. Run id(s): {8984233}
[2018-04-11 22:11:10] Started run 62 on task 146227, dataset 'churn'.
[2018-04-11 22:11:11] Error in run 55: Run already exists in server. Run id(s): {8984241}
[2018-04-11 22:11:11] Started run 63 on task 146227, dataset 'churn'.
[2018-04-11 22:11:11] Error in run 56: Run already exists in server. Run id(s): {8984237}
[2018-04-11 22:11:11] Started run 64 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Error in run 57: Run already exists in server. Run id(s): {8984239}
[2018-04-11 22:11:15] Error in run 58: Run already exists in server. Run id(s): {8984243}
[2018-04-11 22:11:15] Started run 65 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Started run 66 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Error in run 59: Run already exists in server. Run id(s): {8984245}
[2018-04-11 22:11:15] Started run 67 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Error in run 60: Run already exists in server. Run id(s): {8984247}
[2018-04-11 22:11:15] Started run 68 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Error in run 61: Run already exists in server. Run id(s): {8984249}
[2018-04-11 22:11:15] Started run 69 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Error in run 62: Run already exists in server. Run id(s): {8984251}
[2018-04-11 22:11:15] Started run 70 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Error in run 63: Run already exists in server. Run id(s): {8984252}
[2018-04-11 22:11:15] Started run 71 on task 146227, dataset 'churn'.
[2018-04-11 22:11:15] Error in run 64: Run already exists in server. Run id(s): {8984250}
[2018-04-11 22:11:15] Started run 72 on task 146227, dataset 'churn'.
[2018-04-11 22:11:19] Error in run 66: Run already exists in server. Run id(s): {8984256}
[2018-04-11 22:11:19] Error in run 65: Run already exists in server. Run id(s): {8984253}
[2018-04-11 22:11:19] Started run 73 on task 146227, dataset 'churn'.
[2018-04-11 22:11:19] Started run 74 on task 146227, dataset 'churn'.
[2018-04-11 22:11:19] Error in run 68: Run already exists in server. Run id(s): {8984257}
[2018-04-11 22:11:19] Started run 75 on task 146227, dataset 'churn'.
[2018-04-11 22:11:19] Error in run 67: Run already exists in server. Run id(s): {8984258}
[2018-04-11 22:11:19] Started run 76 on task 146227, dataset 'churn'.
[2018-04-11 22:11:19] Error in run 69: Run already exists in server. Run id(s): {8984259}
[2018-04-11 22:11:19] Started run 77 on task 146227, dataset 'churn'.
[2018-04-11 22:11:19] Error in run 70: Run already exists in server. Run id(s): {8984262}
[2018-04-11 22:11:19] Started run 78 on task 146227, dataset 'churn'.
[2018-04-11 22:11:20] Error in run 71: Run already exists in server. Run id(s): {8984264}
[2018-04-11 22:11:20] Started run 79 on task 146227, dataset 'churn'.
[2018-04-11 22:11:20] Error in run 72: Run already exists in server. Run id(s): {8984265}
[2018-04-11 22:11:20] Started run 80 on task 146227, dataset 'churn'.
[2018-04-11 22:11:23] Error in run 74: Run already exists in server. Run id(s): {8984270}
[2018-04-11 22:11:23] Started run 81 on task 146227, dataset 'churn'.
[2018-04-11 22:11:24] Error in run 73: Run already exists in server. Run id(s): {8984266}
[2018-04-11 22:11:24] Started run 82 on task 146227, dataset 'churn'.
[2018-04-11 22:11:24] Error in run 75: Run already exists in server. Run id(s): {8984271}
[2018-04-11 22:11:24] Started run 83 on task 146227, dataset 'churn'.
[2018-04-11 22:11:24] Error in run 77: Run already exists in server. Run id(s): {8984272}
[2018-04-11 22:11:24] Started run 84 on task 146227, dataset 'churn'.
[2018-04-11 22:11:24] Error in run 76: Run already exists in server. Run id(s): {8984269}
[2018-04-11 22:11:24] Started run 85 on task 146227, dataset 'churn'.
[2018-04-11 22:11:24] Error in run 78: Run already exists in server. Run id(s): {8984273}
[2018-04-11 22:11:24] Started run 86 on task 146227, dataset 'churn'.
[2018-04-11 22:11:24] Error in run 79: Run already exists in server. Run id(s): {8984276}
[2018-04-11 22:11:24] Started run 87 on task 146227, dataset 'churn'.
[2018-04-11 22:11:25] Error in run 80: Run already exists in server. Run id(s): {8984277}
[2018-04-11 22:11:25] Started run 88 on task 146227, dataset 'churn'.
[2018-04-11 22:11:28] Error in run 82: Run already exists in server. Run id(s): {8984279}
[2018-04-11 22:11:28] Started run 89 on task 146227, dataset 'churn'.
[2018-04-11 22:11:28] Error in run 81: Run already exists in server. Run id(s): {8984278}
[2018-04-11 22:11:28] Started run 90 on task 146227, dataset 'churn'.
[2018-04-11 22:11:28] Error in run 83: Run already exists in server. Run id(s): {8984281}
[2018-04-11 22:11:28] Started run 91 on task 146227, dataset 'churn'.
[2018-04-11 22:11:28] Error in run 85: Run already exists in server. Run id(s): {8984284}
[2018-04-11 22:11:28] Started run 92 on task 146227, dataset 'churn'.
[2018-04-11 22:11:28] Error in run 84: Run already exists in server. Run id(s): {8984290}
[2018-04-11 22:11:28] Started run 93 on task 146227, dataset 'churn'.
[2018-04-11 22:11:29] Error in run 86: Run already exists in server. Run id(s): {8984286}
[2018-04-11 22:11:29] Started run 94 on task 146227, dataset 'churn'.
[2018-04-11 22:11:29] Error in run 87: Run already exists in server. Run id(s): {8984291}
[2018-04-11 22:11:29] Started run 95 on task 146227, dataset 'churn'.
[2018-04-11 22:11:29] Error in run 88: Run already exists in server. Run id(s): {8984295}
[2018-04-11 22:11:29] Started run 96 on task 146227, dataset 'churn'.
[2018-04-11 22:11:33] Error in run 89: Run already exists in server. Run id(s): {8984294}
[2018-04-11 22:11:33] Error in run 90: Run already exists in server. Run id(s): {8984292}
[2018-04-11 22:11:33] Started run 97 on task 146227, dataset 'churn'.
[2018-04-11 22:11:33] Started run 98 on task 146227, dataset 'churn'.
[2018-04-11 22:11:33] Error in run 91: Run already exists in server. Run id(s): {8984297}
[2018-04-11 22:11:33] Started run 99 on task 146227, dataset 'churn'.
[2018-04-11 22:11:33] Error in run 92: Run already exists in server. Run id(s): {8984298}
[2018-04-11 22:11:33] Started run 100 on task 146227, dataset 'churn'.
[2018-04-11 22:11:33] Error in run 93: Run already exists in server. Run id(s): {8984302}
[2018-04-11 22:11:33] Started run 101 on task 146227, dataset 'churn'.
[2018-04-11 22:11:33] Error in run 94: Run already exists in server. Run id(s): {8984300}
[2018-04-11 22:11:33] Started run 102 on task 146227, dataset 'churn'.
[2018-04-11 22:11:33] Error in run 95: Run already exists in server. Run id(s): {8984303}
[2018-04-11 22:11:33] Started run 103 on task 146227, dataset 'churn'.
[2018-04-11 22:11:34] Error in run 96: Run already exists in server. Run id(s): {8984304}
[2018-04-11 22:11:34] Started run 104 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Error in run 97: Run already exists in server. Run id(s): {8984307}
[2018-04-11 22:11:38] Started run 105 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Error in run 99: Run already exists in server. Run id(s): {8984306}
[2018-04-11 22:11:38] Error in run 98: Run already exists in server. Run id(s): {8984305}
[2018-04-11 22:11:38] Started run 106 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Started run 107 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Error in run 102: Run already exists in server. Run id(s): {8984317}
[2018-04-11 22:11:38] Error in run 100: Run already exists in server. Run id(s): {8984309}
[2018-04-11 22:11:38] Error in run 101: Run already exists in server. Run id(s): {8984310}
[2018-04-11 22:11:38] Started run 108 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Started run 109 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Started run 110 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Error in run 103: Run already exists in server. Run id(s): {8984313}
[2018-04-11 22:11:38] Started run 111 on task 146227, dataset 'churn'.
[2018-04-11 22:11:38] Error in run 104: Run already exists in server. Run id(s): {8984314}
[2018-04-11 22:11:38] Started run 112 on task 146227, dataset 'churn'.
[2018-04-11 22:11:42] Error in run 108: Run already exists in server. Run id(s): {8984325}
[2018-04-11 22:11:42] Started run 113 on task 146227, dataset 'churn'.
[2018-04-11 22:11:42] Error in run 110: Run already exists in server. Run id(s): {8984327}
[2018-04-11 22:11:42] Error in run 109: Run already exists in server. Run id(s): {8984331}
[2018-04-11 22:11:42] Error in run 106: Run already exists in server. Run id(s): {8984320}
[2018-04-11 22:11:42] Error in run 105: Run already exists in server. Run id(s): {8984323}
[2018-04-11 22:11:42] Started run 114 on task 146227, dataset 'churn'.
[2018-04-11 22:11:42] Error in run 107: Run already exists in server. Run id(s): {8984321}
[2018-04-11 22:11:42] Started run 116 on task 146227, dataset 'churn'.
[2018-04-11 22:11:42] Error in run 111: Run already exists in server. Run id(s): {8984328}
[2018-04-11 22:11:42] Started run 119 on task 146227, dataset 'churn'.
[2018-04-11 22:11:42] Started run 117 on task 146227, dataset 'churn'.
[2018-04-11 22:11:42] Started run 115 on task 146227, dataset 'churn'.
[2018-04-11 22:11:42] Started run 118 on task 146227, dataset 'churn'.
[2018-04-11 22:11:43] Error in run 112: Run already exists in server. Run id(s): {8984333}
[2018-04-11 22:11:43] Started run 120 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Error in run 113: Run already exists in server. Run id(s): {8984332}
[2018-04-11 22:11:47] Started run 121 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Error in run 118: Run already exists in server. Run id(s): {8984337}
[2018-04-11 22:11:47] Error in run 115: Run already exists in server. Run id(s): {8984338}
[2018-04-11 22:11:47] Started run 122 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Error in run 119: Run already exists in server. Run id(s): {8984339}
[2018-04-11 22:11:47] Error in run 114: Run already exists in server. Run id(s): {8984334}
[2018-04-11 22:11:47] Started run 123 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Error in run 116: Run already exists in server. Run id(s): {8984336}
[2018-04-11 22:11:47] Error in run 117: Run already exists in server. Run id(s): {8984340}
[2018-04-11 22:11:47] Started run 126 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Started run 127 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Started run 124 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Started run 125 on task 146227, dataset 'churn'.
[2018-04-11 22:11:47] Error in run 120: Run already exists in server. Run id(s): {8984341}
[2018-04-11 22:11:47] Started run 128 on task 146227, dataset 'churn'.
[2018-04-11 22:11:51] Error in run 121: Run already exists in server. Run id(s): {8984344}
[2018-04-11 22:11:51] Started run 129 on task 146227, dataset 'churn'.
[2018-04-11 22:11:52] Error in run 122: Run already exists in server. Run id(s): {8984347}
[2018-04-11 22:11:52] Started run 130 on task 146227, dataset 'churn'.
[2018-04-11 22:11:52] Error in run 124: Run already exists in server. Run id(s): {8984351}
[2018-04-11 22:11:52] Error in run 123: Run already exists in server. Run id(s): {8984348}
[2018-04-11 22:11:52] Error in run 125: Run already exists in server. Run id(s): {8984355}
[2018-04-11 22:11:52] Started run 131 on task 146227, dataset 'churn'.
[2018-04-11 22:11:52] Error in run 126: Run already exists in server. Run id(s): {8984352}
[2018-04-11 22:11:52] Started run 134 on task 146227, dataset 'churn'.
[2018-04-11 22:11:52] Started run 132 on task 146227, dataset 'churn'.
[2018-04-11 22:11:52] Error in run 127: Run already exists in server. Run id(s): {8984358}
[2018-04-11 22:11:52] Started run 135 on task 146227, dataset 'churn'.
[2018-04-11 22:11:52] Started run 133 on task 146227, dataset 'churn'.
[2018-04-11 22:11:52] Error in run 128: Run already exists in server. Run id(s): {8984361}
[2018-04-11 22:11:52] Started run 136 on task 146227, dataset 'churn'.
[2018-04-11 22:11:56] Error in run 129: Run already exists in server. Run id(s): {8984359}
[2018-04-11 22:11:56] Started run 137 on task 146227, dataset 'churn'.
[2018-04-11 22:11:56] Error in run 130: Run already exists in server. Run id(s): {8984363}
[2018-04-11 22:11:56] Started run 138 on task 146227, dataset 'churn'.
[2018-04-11 22:11:57] Error in run 133: Run already exists in server. Run id(s): {8984367}
[2018-04-11 22:11:57] Error in run 131: Run already exists in server. Run id(s): {8984362}
[2018-04-11 22:11:57] Error in run 132: Run already exists in server. Run id(s): {8984364}
[2018-04-11 22:11:57] Started run 139 on task 146227, dataset 'churn'.
[2018-04-11 22:11:57] Error in run 134: Run already exists in server. Run id(s): {8984365}
[2018-04-11 22:11:57] Error in run 136: Run already exists in server. Run id(s): {8984371}
[2018-04-11 22:11:57] Error in run 135: Run already exists in server. Run id(s): {8984366}
[2018-04-11 22:11:57] Started run 142 on task 146227, dataset 'churn'.
[2018-04-11 22:11:57] Started run 143 on task 146227, dataset 'churn'.
[2018-04-11 22:11:57] Started run 140 on task 146227, dataset 'churn'.
[2018-04-11 22:11:57] Started run 144 on task 146227, dataset 'churn'.
[2018-04-11 22:11:57] Started run 141 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Error in run 137: Run already exists in server. Run id(s): {8984369}
[2018-04-11 22:12:01] Started run 145 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Error in run 138: Run already exists in server. Run id(s): {8984370}
[2018-04-11 22:12:01] Started run 146 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Error in run 139: Run already exists in server. Run id(s): {8984372}
[2018-04-11 22:12:01] Started run 147 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Error in run 142: Run already exists in server. Run id(s): {8984377}
[2018-04-11 22:12:01] Started run 148 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Error in run 143: Run already exists in server. Run id(s): {8984374}
[2018-04-11 22:12:01] Error in run 144: Run already exists in server. Run id(s): {8984376}
[2018-04-11 22:12:01] Started run 149 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Error in run 141: Run already exists in server. Run id(s): {8984375}
[2018-04-11 22:12:01] Started run 150 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Started run 151 on task 146227, dataset 'churn'.
[2018-04-11 22:12:01] Error in run 140: Run already exists in server. Run id(s): {8984373}
[2018-04-11 22:12:01] Started run 152 on task 146227, dataset 'churn'.
[2018-04-11 22:12:05] Error in run 145: Run already exists in server. Run id(s): {8984380}
[2018-04-11 22:12:05] Error in run 146: Run already exists in server. Run id(s): {8984378}
[2018-04-11 22:12:05] Started run 153 on task 146227, dataset 'churn'.
[2018-04-11 22:12:05] Started run 154 on task 146227, dataset 'churn'.
[2018-04-11 22:12:06] Error in run 147: Run already exists in server. Run id(s): {8984379}
[2018-04-11 22:12:06] Started run 155 on task 146227, dataset 'churn'.
[2018-04-11 22:12:06] Error in run 148: Run already exists in server. Run id(s): {8984381}
[2018-04-11 22:12:06] Started run 156 on task 146227, dataset 'churn'.
[2018-04-11 22:12:06] Error in run 152: Run already exists in server. Run id(s): {8984388}
[2018-04-11 22:12:06] Started run 157 on task 146227, dataset 'churn'.
[2018-04-11 22:12:06] Error in run 151: Run already exists in server. Run id(s): {8984384}
[2018-04-11 22:12:06] Error in run 150: Run already exists in server. Run id(s): {8984385}
[2018-04-11 22:12:06] Error in run 149: Run already exists in server. Run id(s): {8984382}
[2018-04-11 22:12:06] Started run 158 on task 146227, dataset 'churn'.
[2018-04-11 22:12:06] Started run 159 on task 146227, dataset 'churn'.
[2018-04-11 22:12:06] Started run 160 on task 146227, dataset 'churn'.
[2018-04-11 22:12:10] Error in run 154: Run already exists in server. Run id(s): {8984390}
[2018-04-11 22:12:10] Started run 161 on task 146227, dataset 'churn'.
[2018-04-11 22:12:10] Error in run 153: Run already exists in server. Run id(s): {8984391}
[2018-04-11 22:12:10] Started run 162 on task 146227, dataset 'churn'.
[2018-04-11 22:12:10] Error in run 155: Run already exists in server. Run id(s): {8984389}
[2018-04-11 22:12:10] Started run 163 on task 146227, dataset 'churn'.
[2018-04-11 22:12:10] Error in run 156: Run already exists in server. Run id(s): {8984392}
[2018-04-11 22:12:10] Started run 164 on task 146227, dataset 'churn'.
[2018-04-11 22:12:11] Error in run 157: Run already exists in server. Run id(s): {8984394}
[2018-04-11 22:12:11] Started run 165 on task 146227, dataset 'churn'.
[2018-04-11 22:12:11] Error in run 158: Run already exists in server. Run id(s): {8984396}
[2018-04-11 22:12:11] Error in run 159: Run already exists in server. Run id(s): {8984395}
[2018-04-11 22:12:11] Error in run 160: Run already exists in server. Run id(s): {8984397}
[2018-04-11 22:12:11] Started run 167 on task 146227, dataset 'churn'.
[2018-04-11 22:12:11] Started run 168 on task 146227, dataset 'churn'.
[2018-04-11 22:12:11] Started run 166 on task 146227, dataset 'churn'.
[2018-04-11 22:12:14] Error in run 162: Run already exists in server. Run id(s): {8984401}
[2018-04-11 22:12:14] Error in run 161: Run already exists in server. Run id(s): {8984399}
[2018-04-11 22:12:14] Started run 169 on task 146227, dataset 'churn'.
[2018-04-11 22:12:14] Started run 170 on task 146227, dataset 'churn'.
[2018-04-11 22:12:15] Error in run 163: Run already exists in server. Run id(s): {8984403}
[2018-04-11 22:12:15] Error in run 164: Run already exists in server. Run id(s): {8984402}
[2018-04-11 22:12:15] Started run 171 on task 146227, dataset 'churn'.
[2018-04-11 22:12:15] Started run 172 on task 146227, dataset 'churn'.
[2018-04-11 22:12:15] Error in run 165: Run already exists in server. Run id(s): {8984410}
[2018-04-11 22:12:15] Started run 173 on task 146227, dataset 'churn'.
[2018-04-11 22:12:16] Error in run 168: Run already exists in server. Run id(s): {8984406}
[2018-04-11 22:12:16] Started run 174 on task 146227, dataset 'churn'.
[2018-04-11 22:12:16] Error in run 167: Run already exists in server. Run id(s): {8984405}
[2018-04-11 22:12:16] Error in run 166: Run already exists in server. Run id(s): {8984411}
[2018-04-11 22:12:16] Started run 175 on task 146227, dataset 'churn'.
[2018-04-11 22:12:16] Started run 176 on task 146227, dataset 'churn'.
[2018-04-11 22:12:19] Error in run 170: Run already exists in server. Run id(s): {8984416}
[2018-04-11 22:12:19] Started run 177 on task 146227, dataset 'churn'.
[2018-04-11 22:12:19] Error in run 169: Run already exists in server. Run id(s): {8984419}
[2018-04-11 22:12:19] Started run 178 on task 146227, dataset 'churn'.
[2018-04-11 22:12:20] Error in run 171: Run already exists in server. Run id(s): {8984420}
[2018-04-11 22:12:20] Started run 179 on task 146227, dataset 'churn'.
[2018-04-11 22:12:20] Error in run 172: Run already exists in server. Run id(s): {8984431}
[2018-04-11 22:12:20] Started run 180 on task 146227, dataset 'churn'.
[2018-04-11 22:12:20] Error in run 173: Run already exists in server. Run id(s): {8984429}
[2018-04-11 22:12:20] Started run 181 on task 146227, dataset 'churn'.
[2018-04-11 22:12:20] Error in run 174: Run already exists in server. Run id(s): {8984435}
[2018-04-11 22:12:20] Started run 182 on task 146227, dataset 'churn'.
[2018-04-11 22:12:20] Error in run 176: Run already exists in server. Run id(s): {8984442}
[2018-04-11 22:12:20] Started run 183 on task 146227, dataset 'churn'.
[2018-04-11 22:12:20] Error in run 175: Run already exists in server. Run id(s): {8984438}
[2018-04-11 22:12:20] Started run 184 on task 146227, dataset 'churn'.
[2018-04-11 22:12:23] Error in run 177: Run already exists in server. Run id(s): {8984444}
[2018-04-11 22:12:23] Started run 185 on task 146227, dataset 'churn'.
[2018-04-11 22:12:24] Error in run 178: Run already exists in server. Run id(s): {8984453}
[2018-04-11 22:12:24] Started run 186 on task 146227, dataset 'churn'.
[2018-04-11 22:12:24] Error in run 179: Run already exists in server. Run id(s): {8984449}
[2018-04-11 22:12:24] Started run 187 on task 146227, dataset 'churn'.
[2018-04-11 22:12:24] Error in run 180: Run already exists in server. Run id(s): {8984461}
[2018-04-11 22:12:24] Started run 188 on task 146227, dataset 'churn'.
[2018-04-11 22:12:24] Error in run 181: Run already exists in server. Run id(s): {8984455}
[2018-04-11 22:12:24] Started run 189 on task 146227, dataset 'churn'.
[2018-04-11 22:12:25] Error in run 182: Run already exists in server. Run id(s): {8984469}
[2018-04-11 22:12:25] Started run 190 on task 146227, dataset 'churn'.
[2018-04-11 22:12:25] Error in run 184: Run already exists in server. Run id(s): {8984472}
[2018-04-11 22:12:25] Started run 191 on task 146227, dataset 'churn'.
[2018-04-11 22:12:25] Error in run 183: Run already exists in server. Run id(s): {8984473}
[2018-04-11 22:12:25] Started run 192 on task 146227, dataset 'churn'.
[2018-04-11 22:12:28] Error in run 185: Run already exists in server. Run id(s): {8984471}
[2018-04-11 22:12:28] Started run 193 on task 146227, dataset 'churn'.
[2018-04-11 22:12:28] Error in run 186: Run already exists in server. Run id(s): {8984484}
[2018-04-11 22:12:28] Started run 194 on task 146227, dataset 'churn'.
[2018-04-11 22:12:29] Error in run 187: Run already exists in server. Run id(s): {8984485}
[2018-04-11 22:12:29] Started run 195 on task 146227, dataset 'churn'.
[2018-04-11 22:12:29] Error in run 188: Run already exists in server. Run id(s): {8984486}
[2018-04-11 22:12:29] Started run 196 on task 146227, dataset 'churn'.
[2018-04-11 22:12:29] Error in run 189: Run already exists in server. Run id(s): {8984487}
[2018-04-11 22:12:29] Started run 197 on task 146227, dataset 'churn'.
[2018-04-11 22:12:29] Error in run 190: Run already exists in server. Run id(s): {8984502}
[2018-04-11 22:12:29] Started run 198 on task 146227, dataset 'churn'.
[2018-04-11 22:12:30] Error in run 192: Run already exists in server. Run id(s): {8984510}
[2018-04-11 22:12:30] Started run 199 on task 146227, dataset 'churn'.
[2018-04-11 22:12:30] Error in run 191: Run already exists in server. Run id(s): {8984500}
[2018-04-11 22:12:30] Started run 200 on task 146227, dataset 'churn'.
[2018-04-11 22:12:33] Error in run 193: Run already exists in server. Run id(s): {8984507}
[2018-04-11 22:12:33] Started run 201 on task 146227, dataset 'churn'.
[2018-04-11 22:12:33] Error in run 194: Run already exists in server. Run id(s): {8984513}
[2018-04-11 22:12:33] Started run 202 on task 146227, dataset 'churn'.
[2018-04-11 22:12:33] Error in run 195: Run already exists in server. Run id(s): {8984514}
[2018-04-11 22:12:33] Started run 203 on task 146227, dataset 'churn'.
[2018-04-11 22:12:34] Error in run 196: Run already exists in server. Run id(s): {8984523}
[2018-04-11 22:12:34] Started run 204 on task 146227, dataset 'churn'.
[2018-04-11 22:12:34] Error in run 197: Run already exists in server. Run id(s): {8984530}
[2018-04-11 22:12:34] Started run 205 on task 146227, dataset 'churn'.
[2018-04-11 22:12:34] Error in run 198: Run already exists in server. Run id(s): {8984524}
[2018-04-11 22:12:34] Started run 206 on task 146227, dataset 'churn'.
[2018-04-11 22:12:34] Error in run 199: Run already exists in server. Run id(s): {8984525}
[2018-04-11 22:12:34] Started run 207 on task 146227, dataset 'churn'.
[2018-04-11 22:12:35] Error in run 200: Run already exists in server. Run id(s): {8984543}
[2018-04-11 22:12:35] Started run 208 on task 146227, dataset 'churn'.
[2018-04-11 22:12:37] Error in run 201: Run already exists in server. Run id(s): {8984536}
[2018-04-11 22:12:37] Started run 209 on task 146227, dataset 'churn'.
[2018-04-11 22:12:37] Error in run 202: Run already exists in server. Run id(s): {8984551}
[2018-04-11 22:12:37] Started run 210 on task 146227, dataset 'churn'.
[2018-04-11 22:12:38] Error in run 203: Run already exists in server. Run id(s): {8984544}
[2018-04-11 22:12:38] Started run 211 on task 146227, dataset 'churn'.
[2018-04-11 22:12:38] Error in run 204: Run already exists in server. Run id(s): {8984545}
[2018-04-11 22:12:38] Started run 212 on task 146227, dataset 'churn'.
[2018-04-11 22:12:38] Error in run 205: Run already exists in server. Run id(s): {8984556}
[2018-04-11 22:12:38] Started run 213 on task 146227, dataset 'churn'.
[2018-04-11 22:12:39] Error in run 206: Run already exists in server. Run id(s): {8984562}
[2018-04-11 22:12:39] Started run 214 on task 146227, dataset 'churn'.
[2018-04-11 22:12:39] Error in run 207: Run already exists in server. Run id(s): {8984564}
[2018-04-11 22:12:39] Started run 215 on task 146227, dataset 'churn'.
[2018-04-11 22:12:39] Error in run 208: Run already exists in server. Run id(s): {8984561}
[2018-04-11 22:12:39] Started run 216 on task 146227, dataset 'churn'.
[2018-04-11 22:12:42] Error in run 209: Run already exists in server. Run id(s): {8984570}
[2018-04-11 22:12:42] Error in run 210: Run already exists in server. Run id(s): {8984578}
[2018-04-11 22:12:42] Started run 217 on task 146227, dataset 'churn'.
[2018-04-11 22:12:42] Started run 218 on task 146227, dataset 'churn'.
[2018-04-11 22:12:43] Error in run 213: Run already exists in server. Run id(s): {8984585}
[2018-04-11 22:12:43] Error in run 212: Run already exists in server. Run id(s): {8984580}
[2018-04-11 22:12:43] Error in run 211: Run already exists in server. Run id(s): {8984579}
[2018-04-11 22:12:43] Started run 219 on task 146227, dataset 'churn'.
[2018-04-11 22:12:43] Started run 220 on task 146227, dataset 'churn'.
[2018-04-11 22:12:43] Started run 221 on task 146227, dataset 'churn'.
[2018-04-11 22:12:44] Error in run 215: Run already exists in server. Run id(s): {8984591}
[2018-04-11 22:12:44] Started run 222 on task 146227, dataset 'churn'.
[2018-04-11 22:12:44] Error in run 216: Run already exists in server. Run id(s): {8984600}
[2018-04-11 22:12:44] Error in run 214: Run already exists in server. Run id(s): {8984590}
[2018-04-11 22:12:44] Started run 223 on task 146227, dataset 'churn'.
[2018-04-11 22:12:44] Started run 224 on task 146227, dataset 'churn'.
[2018-04-11 22:12:47] Error in run 217: Run already exists in server. Run id(s): {8984596}
[2018-04-11 22:12:47] Started run 225 on task 146227, dataset 'churn'.
[2018-04-11 22:12:47] Error in run 218: Run already exists in server. Run id(s): {8984601}
[2018-04-11 22:12:47] Started run 226 on task 146227, dataset 'churn'.
[2018-04-11 22:12:48] Error in run 219: Run already exists in server. Run id(s): {8984608}
[2018-04-11 22:12:48] Started run 227 on task 146227, dataset 'churn'.
[2018-04-11 22:12:48] Error in run 220: Run already exists in server. Run id(s): {8984606}
[2018-04-11 22:12:48] Started run 228 on task 146227, dataset 'churn'.
[2018-04-11 22:12:48] Error in run 221: Run already exists in server. Run id(s): {8984609}
[2018-04-11 22:12:48] Started run 229 on task 146227, dataset 'churn'.
[2018-04-11 22:12:48] Error in run 222: Run already exists in server. Run id(s): {8984620}
[2018-04-11 22:12:48] Started run 230 on task 146227, dataset 'churn'.
[2018-04-11 22:12:48] Error in run 224: Run already exists in server. Run id(s): {8984622}
[2018-04-11 22:12:48] Started run 231 on task 146227, dataset 'churn'.
[2018-04-11 22:12:48] Error in run 223: Run already exists in server. Run id(s): {8984619}
[2018-04-11 22:12:48] Started run 232 on task 146227, dataset 'churn'.
[2018-04-11 22:12:51] Error in run 225: Run already exists in server. Run id(s): {8984633}
[2018-04-11 22:12:51] Started run 233 on task 146227, dataset 'churn'.
[2018-04-11 22:12:51] Error in run 226: Run already exists in server. Run id(s): {8984629}
[2018-04-11 22:12:51] Started run 234 on task 146227, dataset 'churn'.
[2018-04-11 22:12:52] Error in run 227: Run already exists in server. Run id(s): {8984643}
[2018-04-11 22:12:52] Started run 235 on task 146227, dataset 'churn'.
[2018-04-11 22:12:52] Error in run 229: Run already exists in server. Run id(s): {8984648}
[2018-04-11 22:12:52] Started run 236 on task 146227, dataset 'churn'.
[2018-04-11 22:12:52] Error in run 228: Run already exists in server. Run id(s): {8984636}
[2018-04-11 22:12:52] Started run 237 on task 146227, dataset 'churn'.
[2018-04-11 22:12:53] Error in run 230: Run already exists in server. Run id(s): {8984657}
[2018-04-11 22:12:53] Started run 238 on task 146227, dataset 'churn'.
[2018-04-11 22:12:53] Error in run 232: Run already exists in server. Run id(s): {8984664}
[2018-04-11 22:12:53] Error in run 231: Run already exists in server. Run id(s): {8984653}
[2018-04-11 22:12:53] Started run 239 on task 146227, dataset 'churn'.
[2018-04-11 22:12:53] Started run 240 on task 146227, dataset 'churn'.
[2018-04-11 22:12:56] Error in run 234: Run already exists in server. Run id(s): {8984666}
[2018-04-11 22:12:56] Started run 241 on task 146227, dataset 'churn'.
[2018-04-11 22:12:56] Error in run 233: Run already exists in server. Run id(s): {8984660}
[2018-04-11 22:12:56] Started run 242 on task 146227, dataset 'churn'.
[2018-04-11 22:12:57] Error in run 237: Run already exists in server. Run id(s): {8984682}
[2018-04-11 22:12:57] Error in run 235: Run already exists in server. Run id(s): {8984676}
[2018-04-11 22:12:57] Error in run 236: Run already exists in server. Run id(s): {8984674}
[2018-04-11 22:12:57] Started run 243 on task 146227, dataset 'churn'.
[2018-04-11 22:12:57] Started run 244 on task 146227, dataset 'churn'.
[2018-04-11 22:12:57] Started run 245 on task 146227, dataset 'churn'.
[2018-04-11 22:12:57] Error in run 238: Run already exists in server. Run id(s): {8984689}
[2018-04-11 22:12:57] Started run 246 on task 146227, dataset 'churn'.
[2018-04-11 22:12:58] Error in run 240: Run already exists in server. Run id(s): {8984700}
[2018-04-11 22:12:58] Started run 247 on task 146227, dataset 'churn'.
[2018-04-11 22:12:58] Error in run 239: Run already exists in server. Run id(s): {8984688}
[2018-04-11 22:12:58] Started run 248 on task 146227, dataset 'churn'.
[2018-04-11 22:13:00] Error in run 241: Run already exists in server. Run id(s): {8984691}
[2018-04-11 22:13:00] Started run 249 on task 146227, dataset 'churn'.
[2018-04-11 22:13:00] Error in run 242: Run already exists in server. Run id(s): {8984708}
[2018-04-11 22:13:00] Started run 250 on task 146227, dataset 'churn'.
[2018-04-11 22:13:02] Error in run 244: Run already exists in server. Run id(s): {8984703}
[2018-04-11 22:13:02] Error in run 243: Run already exists in server. Run id(s): {8984699}
[2018-04-11 22:13:02] Started run 251 on task 146227, dataset 'churn'.
[2018-04-11 22:13:02] Started run 252 on task 146227, dataset 'churn'.
[2018-04-11 22:13:02] Error in run 245: Run already exists in server. Run id(s): {8984712}
[2018-04-11 22:13:02] Started run 253 on task 146227, dataset 'churn'.
[2018-04-11 22:13:02] Error in run 246: Run already exists in server. Run id(s): {8984722}
[2018-04-11 22:13:02] Started run 254 on task 146227, dataset 'churn'.
[2018-04-11 22:13:02] Error in run 248: Run already exists in server. Run id(s): {8984723}
[2018-04-11 22:13:02] Error in run 247: Run already exists in server. Run id(s): {8984716}
[2018-04-11 22:13:02] Started run 255 on task 146227, dataset 'churn'.
[2018-04-11 22:13:02] Started run 256 on task 146227, dataset 'churn'.
[2018-04-11 22:13:05] Error in run 250: Run already exists in server. Run id(s): {8984737}
[2018-04-11 22:13:05] Started run 257 on task 146227, dataset 'churn'.
[2018-04-11 22:13:05] Error in run 249: Run already exists in server. Run id(s): {8984728}
[2018-04-11 22:13:05] Started run 258 on task 146227, dataset 'churn'.
[2018-04-11 22:13:06] Error in run 251: Run already exists in server. Run id(s): {8984734}
[2018-04-11 22:13:06] Started run 259 on task 146227, dataset 'churn'.
[2018-04-11 22:13:06] Error in run 252: Run already exists in server. Run id(s): {8984742}
[2018-04-11 22:13:06] Started run 260 on task 146227, dataset 'churn'.
[2018-04-11 22:13:06] Error in run 253: Run already exists in server. Run id(s): {8984743}
[2018-04-11 22:13:06] Started run 261 on task 146227, dataset 'churn'.
[2018-04-11 22:13:07] Error in run 254: Run already exists in server. Run id(s): {9014457, 8984749}
[2018-04-11 22:13:07] Started run 262 on task 146227, dataset 'churn'.
[2018-04-11 22:13:07] Error in run 256: Run already exists in server. Run id(s): {8984754}
[2018-04-11 22:13:07] Started run 263 on task 146227, dataset 'churn'.
[2018-04-11 22:13:07] Error in run 255: Run already exists in server. Run id(s): {8984748}
[2018-04-11 22:13:07] Started run 264 on task 146227, dataset 'churn'.
[2018-04-11 22:13:10] Error in run 257: Run already exists in server. Run id(s): {8984759}
[2018-04-11 22:13:10] Error in run 258: Run already exists in server. Run id(s): {8984768}
[2018-04-11 22:13:10] Started run 265 on task 146227, dataset 'churn'.
[2018-04-11 22:13:10] Started run 266 on task 146227, dataset 'churn'.
[2018-04-11 22:13:11] Error in run 259: Run already exists in server. Run id(s): {8984765}
[2018-04-11 22:13:11] Started run 267 on task 146227, dataset 'churn'.
[2018-04-11 22:13:11] Error in run 260: Run already exists in server. Run id(s): {8984770}
[2018-04-11 22:13:11] Started run 268 on task 146227, dataset 'churn'.
[2018-04-11 22:13:11] Error in run 261: Run already exists in server. Run id(s): {8984785}
[2018-04-11 22:13:11] Started run 269 on task 146227, dataset 'churn'.
[2018-04-11 22:13:11] Error in run 262: Run already exists in server. Run id(s): {8984782}
[2018-04-11 22:13:11] Started run 270 on task 146227, dataset 'churn'.
[2018-04-11 22:13:11] Error in run 263: Run already exists in server. Run id(s): {8984786}
[2018-04-11 22:13:11] Started run 271 on task 146227, dataset 'churn'.
[2018-04-11 22:13:11] Error in run 264: Run already exists in server. Run id(s): {8984788}
[2018-04-11 22:13:11] Started run 272 on task 146227, dataset 'churn'.
[2018-04-11 22:13:14] Error in run 265: Run already exists in server. Run id(s): {8984806}
[2018-04-11 22:13:14] Started run 273 on task 146227, dataset 'churn'.
[2018-04-11 22:13:14] Error in run 266: Run already exists in server. Run id(s): {8984801}
[2018-04-11 22:13:14] Started run 274 on task 146227, dataset 'churn'.
[2018-04-11 22:13:15] Error in run 267: Run already exists in server. Run id(s): {8984800}
[2018-04-11 22:13:15] Started run 275 on task 146227, dataset 'churn'.
[2018-04-11 22:13:15] Error in run 269: Run already exists in server. Run id(s): {8984813}
[2018-04-11 22:13:15] Started run 276 on task 146227, dataset 'churn'.
[2018-04-11 22:13:15] Error in run 268: Run already exists in server. Run id(s): {8984812}
[2018-04-11 22:13:15] Started run 277 on task 146227, dataset 'churn'.
[2018-04-11 22:13:16] Error in run 270: Run already exists in server. Run id(s): {8984820}
[2018-04-11 22:13:16] Started run 278 on task 146227, dataset 'churn'.
[2018-04-11 22:13:16] Error in run 271: Run already exists in server. Run id(s): {8984828}
[2018-04-11 22:13:16] Started run 279 on task 146227, dataset 'churn'.
[2018-04-11 22:13:16] Error in run 272: Run already exists in server. Run id(s): {8984827}
[2018-04-11 22:13:16] Started run 280 on task 146227, dataset 'churn'.
[2018-04-11 22:13:19] Error in run 273: Run already exists in server. Run id(s): {8984829}
[2018-04-11 22:13:19] Started run 281 on task 146227, dataset 'churn'.
[2018-04-11 22:13:19] Error in run 274: Run already exists in server. Run id(s): {8984834}
[2018-04-11 22:13:19] Started run 282 on task 146227, dataset 'churn'.
[2018-04-11 22:13:20] Error in run 275: Run already exists in server. Run id(s): {8984845}
[2018-04-11 22:13:20] Started run 283 on task 146227, dataset 'churn'.
[2018-04-11 22:13:20] Error in run 276: Run already exists in server. Run id(s): {8984840}
[2018-04-11 22:13:20] Started run 284 on task 146227, dataset 'churn'.
[2018-04-11 22:13:20] Error in run 277: Run already exists in server. Run id(s): {8984841}
[2018-04-11 22:13:20] Started run 285 on task 146227, dataset 'churn'.
[2018-04-11 22:13:20] Error in run 278: Run already exists in server. Run id(s): {8984848}
[2018-04-11 22:13:20] Started run 286 on task 146227, dataset 'churn'.
[2018-04-11 22:13:21] Error in run 279: Run already exists in server. Run id(s): {8984854}
[2018-04-11 22:13:21] Started run 287 on task 146227, dataset 'churn'.
[2018-04-11 22:13:21] Error in run 280: Run already exists in server. Run id(s): {8984856}
[2018-04-11 22:13:21] Started run 288 on task 146227, dataset 'churn'.
[2018-04-11 22:13:23] Error in run 282: Run already exists in server. Run id(s): {8984861}
[2018-04-11 22:13:23] Started run 289 on task 146227, dataset 'churn'.
[2018-04-11 22:13:23] Error in run 281: Run already exists in server. Run id(s): {8984859}
[2018-04-11 22:13:23] Started run 290 on task 146227, dataset 'churn'.
[2018-04-11 22:13:24] Error in run 283: Run already exists in server. Run id(s): {8984867}
[2018-04-11 22:13:24] Started run 291 on task 146227, dataset 'churn'.
[2018-04-11 22:13:24] Error in run 284: Run already exists in server. Run id(s): {8984870}
[2018-04-11 22:13:24] Error in run 285: Run already exists in server. Run id(s): {8984879}
[2018-04-11 22:13:24] Started run 292 on task 146227, dataset 'churn'.
[2018-04-11 22:13:24] Started run 293 on task 146227, dataset 'churn'.
[2018-04-11 22:13:25] Error in run 286: Run already exists in server. Run id(s): {8984874}
[2018-04-11 22:13:25] Started run 294 on task 146227, dataset 'churn'.
[2018-04-11 22:13:25] Error in run 287: Run already exists in server. Run id(s): {8984878}
[2018-04-11 22:13:25] Started run 295 on task 146227, dataset 'churn'.
[2018-04-11 22:13:25] Error in run 288: Run already exists in server. Run id(s): {8984883}
[2018-04-11 22:13:25] Started run 296 on task 146227, dataset 'churn'.
[2018-04-11 22:13:28] Error in run 289: Run already exists in server. Run id(s): {8984895}
[2018-04-11 22:13:28] Started run 297 on task 146227, dataset 'churn'.
[2018-04-11 22:13:28] Error in run 290: Run already exists in server. Run id(s): {8984898}
[2018-04-11 22:13:28] Started run 298 on task 146227, dataset 'churn'.
[2018-04-11 22:13:29] Error in run 291: Run already exists in server. Run id(s): {8984890}
[2018-04-11 22:13:29] Started run 299 on task 146227, dataset 'churn'.
[2018-04-11 22:13:29] Error in run 293: Run already exists in server. Run id(s): {8984908}
[2018-04-11 22:13:29] Started run 300 on task 146227, dataset 'churn'.
[2018-04-11 22:13:29] Error in run 292: Run already exists in server. Run id(s): {8984894}
[2018-04-11 22:13:29] Started run 301 on task 146227, dataset 'churn'.
[2018-04-11 22:13:29] Error in run 294: Run already exists in server. Run id(s): {8984912}
[2018-04-11 22:13:29] Started run 302 on task 146227, dataset 'churn'.
[2018-04-11 22:13:30] Error in run 295: Run already exists in server. Run id(s): {8984911}
[2018-04-11 22:13:30] Started run 303 on task 146227, dataset 'churn'.
[2018-04-11 22:13:30] Error in run 296: Run already exists in server. Run id(s): {8984915}
[2018-04-11 22:13:30] Started run 304 on task 146227, dataset 'churn'.
[2018-04-11 22:13:32] Error in run 297: Run already exists in server. Run id(s): {8984922}
[2018-04-11 22:13:32] Started run 305 on task 146227, dataset 'churn'.
[2018-04-11 22:13:32] Error in run 298: Run already exists in server. Run id(s): {8984934}
[2018-04-11 22:13:32] Started run 306 on task 146227, dataset 'churn'.
[2018-04-11 22:13:33] Error in run 299: Run already exists in server. Run id(s): {8984927}
[2018-04-11 22:13:33] Started run 307 on task 146227, dataset 'churn'.
[2018-04-11 22:13:33] Error in run 301: Run already exists in server. Run id(s): {8984945}
[2018-04-11 22:13:33] Started run 308 on task 146227, dataset 'churn'.
[2018-04-11 22:13:33] Error in run 300: Run already exists in server. Run id(s): {8984929}
[2018-04-11 22:13:33] Started run 309 on task 146227, dataset 'churn'.
[2018-04-11 22:13:34] Error in run 302: Run already exists in server. Run id(s): {8984937}
[2018-04-11 22:13:34] Started run 310 on task 146227, dataset 'churn'.
[2018-04-11 22:13:34] Error in run 304: Run already exists in server. Run id(s): {8984952}
[2018-04-11 22:13:34] Started run 311 on task 146227, dataset 'churn'.
[2018-04-11 22:13:34] Error in run 303: Run already exists in server. Run id(s): {8984953}
[2018-04-11 22:13:34] Started run 312 on task 146227, dataset 'churn'.
[2018-04-11 22:13:37] Error in run 306: Run already exists in server. Run id(s): {8984967}
[2018-04-11 22:13:37] Error in run 305: Run already exists in server. Run id(s): {8984951}
[2018-04-11 22:13:37] Started run 313 on task 146227, dataset 'churn'.
[2018-04-11 22:13:37] Started run 314 on task 146227, dataset 'churn'.
[2018-04-11 22:13:38] Error in run 308: Run already exists in server. Run id(s): {8984963}
[2018-04-11 22:13:38] Started run 315 on task 146227, dataset 'churn'.
[2018-04-11 22:13:38] Error in run 307: Run already exists in server. Run id(s): {8984966}
[2018-04-11 22:13:38] Started run 316 on task 146227, dataset 'churn'.
[2018-04-11 22:13:38] Error in run 309: Run already exists in server. Run id(s): {8984969}
[2018-04-11 22:13:38] Started run 317 on task 146227, dataset 'churn'.
[2018-04-11 22:13:39] Error in run 312: Run already exists in server. Run id(s): {8984982}
[2018-04-11 22:13:39] Started run 318 on task 146227, dataset 'churn'.
[2018-04-11 22:13:39] Error in run 311: Run already exists in server. Run id(s): {8984979}
[2018-04-11 22:13:39] Error in run 310: Run already exists in server. Run id(s): {8984983}
[2018-04-11 22:13:39] Started run 319 on task 146227, dataset 'churn'.
[2018-04-11 22:13:39] Started run 320 on task 146227, dataset 'churn'.
[2018-04-11 22:13:41] Error in run 313: Run already exists in server. Run id(s): {8984987}
[2018-04-11 22:13:41] Started run 321 on task 146227, dataset 'churn'.
[2018-04-11 22:13:42] Error in run 314: Run already exists in server. Run id(s): {8984997}
[2018-04-11 22:13:42] Started run 322 on task 146227, dataset 'churn'.
[2018-04-11 22:13:42] Error in run 316: Run already exists in server. Run id(s): {8985006}
[2018-04-11 22:13:42] Started run 323 on task 146227, dataset 'churn'.
[2018-04-11 22:13:42] Error in run 317: Run already exists in server. Run id(s): {8985002}
[2018-04-11 22:13:42] Started run 324 on task 146227, dataset 'churn'.
[2018-04-11 22:13:42] Error in run 315: Run already exists in server. Run id(s): {8984995}
[2018-04-11 22:13:42] Started run 325 on task 146227, dataset 'churn'.
[2018-04-11 22:13:43] Error in run 320: Run already exists in server. Run id(s): {8985025}
[2018-04-11 22:13:43] Error in run 318: Run already exists in server. Run id(s): {8985015}
[2018-04-11 22:13:43] Started run 326 on task 146227, dataset 'churn'.
[2018-04-11 22:13:43] Error in run 319: Run already exists in server. Run id(s): {8985012}
[2018-04-11 22:13:43] Started run 327 on task 146227, dataset 'churn'.
[2018-04-11 22:13:43] Started run 328 on task 146227, dataset 'churn'.
[2018-04-11 22:13:46] Error in run 321: Run already exists in server. Run id(s): {8985021}
[2018-04-11 22:13:46] Started run 329 on task 146227, dataset 'churn'.
[2018-04-11 22:13:46] Error in run 322: Run already exists in server. Run id(s): {8985026}
[2018-04-11 22:13:46] Started run 330 on task 146227, dataset 'churn'.
[2018-04-11 22:13:47] Error in run 323: Run already exists in server. Run id(s): {8985029}
[2018-04-11 22:13:47] Started run 331 on task 146227, dataset 'churn'.
[2018-04-11 22:13:47] Error in run 325: Run already exists in server. Run id(s): {8985039}
[2018-04-11 22:13:47] Started run 332 on task 146227, dataset 'churn'.
[2018-04-11 22:13:47] Error in run 324: Run already exists in server. Run id(s): {8985036}
[2018-04-11 22:13:47] Started run 333 on task 146227, dataset 'churn'.
[2018-04-11 22:13:48] Error in run 328: Run already exists in server. Run id(s): {8985054}
[2018-04-11 22:13:48] Error in run 326: Run already exists in server. Run id(s): {8985050}
[2018-04-11 22:13:48] Started run 334 on task 146227, dataset 'churn'.
[2018-04-11 22:13:48] Error in run 327: Run already exists in server. Run id(s): {8985040}
[2018-04-11 22:13:48] Started run 335 on task 146227, dataset 'churn'.
[2018-04-11 22:13:48] Started run 336 on task 146227, dataset 'churn'.
[2018-04-11 22:13:50] Error in run 329: Run already exists in server. Run id(s): {8985066}
[2018-04-11 22:13:50] Started run 337 on task 146227, dataset 'churn'.
[2018-04-11 22:13:51] Error in run 330: Run already exists in server. Run id(s): {8985055}
[2018-04-11 22:13:51] Started run 338 on task 146227, dataset 'churn'.
[2018-04-11 22:13:51] Error in run 331: Run already exists in server. Run id(s): {8985072}
[2018-04-11 22:13:51] Started run 339 on task 146227, dataset 'churn'.
[2018-04-11 22:13:52] Error in run 332: Run already exists in server. Run id(s): {8985073}
[2018-04-11 22:13:52] Started run 340 on task 146227, dataset 'churn'.
[2018-04-11 22:13:52] Error in run 333: Run already exists in server. Run id(s): {8985076}
[2018-04-11 22:13:52] Started run 341 on task 146227, dataset 'churn'.
[2018-04-11 22:13:52] Error in run 334: Run already exists in server. Run id(s): {8985081}
[2018-04-11 22:13:52] Started run 342 on task 146227, dataset 'churn'.
[2018-04-11 22:13:52] Error in run 335: Run already exists in server. Run id(s): {8985084}
[2018-04-11 22:13:52] Started run 343 on task 146227, dataset 'churn'.
[2018-04-11 22:13:53] Error in run 336: Run already exists in server. Run id(s): {8985092}
[2018-04-11 22:13:53] Started run 344 on task 146227, dataset 'churn'.
[2018-04-11 22:13:55] Error in run 337: Run already exists in server. Run id(s): {8985087}
[2018-04-11 22:13:55] Started run 345 on task 146227, dataset 'churn'.
[2018-04-11 22:13:55] Error in run 338: Run already exists in server. Run id(s): {8985101}
[2018-04-11 22:13:55] Started run 346 on task 146227, dataset 'churn'.
[2018-04-11 22:13:56] Error in run 339: Run already exists in server. Run id(s): {8985096}
[2018-04-11 22:13:56] Started run 347 on task 146227, dataset 'churn'.
[2018-04-11 22:13:56] Error in run 340: Run already exists in server. Run id(s): {8985107}
[2018-04-11 22:13:56] Started run 348 on task 146227, dataset 'churn'.
[2018-04-11 22:13:57] Error in run 341: Run already exists in server. Run id(s): {8985104}
[2018-04-11 22:13:57] Started run 349 on task 146227, dataset 'churn'.
[2018-04-11 22:13:57] Error in run 343: Run already exists in server. Run id(s): {8985113}
[2018-04-11 22:13:57] Error in run 342: Run already exists in server. Run id(s): {8985117}
[2018-04-11 22:13:57] Started run 350 on task 146227, dataset 'churn'.
[2018-04-11 22:13:57] Started run 351 on task 146227, dataset 'churn'.
[2018-04-11 22:13:58] Error in run 344: Run already exists in server. Run id(s): {8985116}
[2018-04-11 22:13:58] Started run 352 on task 146227, dataset 'churn'.
[2018-04-11 22:13:59] Error in run 345: Run already exists in server. Run id(s): {8985132}
[2018-04-11 22:13:59] Started run 353 on task 146227, dataset 'churn'.
[2018-04-11 22:14:00] Error in run 346: Run already exists in server. Run id(s): {8985127}
[2018-04-11 22:14:00] Started run 354 on task 146227, dataset 'churn'.
[2018-04-11 22:14:00] Error in run 347: Run already exists in server. Run id(s): {8985134}
[2018-04-11 22:14:00] Started run 355 on task 146227, dataset 'churn'.
[2018-04-11 22:14:01] Error in run 348: Run already exists in server. Run id(s): {8985130}
[2018-04-11 22:14:01] Started run 356 on task 146227, dataset 'churn'.
[2018-04-11 22:14:01] Error in run 349: Run already exists in server. Run id(s): {8985156}
[2018-04-11 22:14:01] Started run 357 on task 146227, dataset 'churn'.
[2018-04-11 22:14:01] Error in run 351: Run already exists in server. Run id(s): {8985145}
[2018-04-11 22:14:01] Error in run 350: Run already exists in server. Run id(s): {8985143}
[2018-04-11 22:14:01] Started run 358 on task 146227, dataset 'churn'.
[2018-04-11 22:14:01] Started run 359 on task 146227, dataset 'churn'.
[2018-04-11 22:14:02] Error in run 352: Run already exists in server. Run id(s): {8985148}
[2018-04-11 22:14:02] Started run 360 on task 146227, dataset 'churn'.
[2018-04-11 22:14:04] Error in run 353: Run already exists in server. Run id(s): {8985159}
[2018-04-11 22:14:04] Started run 361 on task 146227, dataset 'churn'.
[2018-04-11 22:14:04] Error in run 354: Run already exists in server. Run id(s): {8985161}
[2018-04-11 22:14:04] Started run 362 on task 146227, dataset 'churn'.
[2018-04-11 22:14:05] Error in run 355: Run already exists in server. Run id(s): {8985166}
[2018-04-11 22:14:05] Started run 363 on task 146227, dataset 'churn'.
[2018-04-11 22:14:05] Error in run 356: Run already exists in server. Run id(s): {8985170}
[2018-04-11 22:14:05] Started run 364 on task 146227, dataset 'churn'.
[2018-04-11 22:14:06] Error in run 357: Run already exists in server. Run id(s): {8985185}
[2018-04-11 22:14:06] Started run 365 on task 146227, dataset 'churn'.
[2018-04-11 22:14:06] Error in run 358: Run already exists in server. Run id(s): {8985177}
[2018-04-11 22:14:06] Started run 366 on task 146227, dataset 'churn'.
[2018-04-11 22:14:06] Error in run 359: Run already exists in server. Run id(s): {8985178}
[2018-04-11 22:14:06] Started run 367 on task 146227, dataset 'churn'.
[2018-04-11 22:14:07] Error in run 360: Run already exists in server. Run id(s): {8985180}
[2018-04-11 22:14:07] Started run 368 on task 146227, dataset 'churn'.
[2018-04-11 22:14:09] Error in run 361: Run already exists in server. Run id(s): {8985186}
[2018-04-11 22:14:09] Started run 369 on task 146227, dataset 'churn'.
[2018-04-11 22:14:09] Error in run 362: Run already exists in server. Run id(s): {8985191}
[2018-04-11 22:14:09] Started run 370 on task 146227, dataset 'churn'.
[2018-04-11 22:14:10] Error in run 363: Run already exists in server. Run id(s): {8985192}
[2018-04-11 22:14:10] Started run 371 on task 146227, dataset 'churn'.
[2018-04-11 22:14:10] Error in run 364: Run already exists in server. Run id(s): {8985197}
[2018-04-11 22:14:10] Started run 372 on task 146227, dataset 'churn'.
[2018-04-11 22:14:10] Error in run 365: Run already exists in server. Run id(s): {8985213}
[2018-04-11 22:14:10] Started run 373 on task 146227, dataset 'churn'.
[2018-04-11 22:14:11] Error in run 366: Run already exists in server. Run id(s): {8985215}
[2018-04-11 22:14:11] Started run 374 on task 146227, dataset 'churn'.
[2018-04-11 22:14:11] Error in run 367: Run already exists in server. Run id(s): {8985206}
[2018-04-11 22:14:11] Started run 375 on task 146227, dataset 'churn'.
[2018-04-11 22:14:11] Error in run 368: Run already exists in server. Run id(s): {8985217}
[2018-04-11 22:14:11] Started run 376 on task 146227, dataset 'churn'.
[2018-04-11 22:14:13] Error in run 369: Run already exists in server. Run id(s): {8985223}
[2018-04-11 22:14:13] Started run 377 on task 146227, dataset 'churn'.
[2018-04-11 22:14:13] Error in run 370: Run already exists in server. Run id(s): {8985236}
[2018-04-11 22:14:13] Started run 378 on task 146227, dataset 'churn'.
[2018-04-11 22:14:14] Error in run 371: Run already exists in server. Run id(s): {8985229}
[2018-04-11 22:14:14] Started run 379 on task 146227, dataset 'churn'.
[2018-04-11 22:14:15] Error in run 372: Run already exists in server. Run id(s): {8985230}
[2018-04-11 22:14:15] Started run 380 on task 146227, dataset 'churn'.
[2018-04-11 22:14:15] Error in run 373: Run already exists in server. Run id(s): {8985237}
[2018-04-11 22:14:15] Started run 381 on task 146227, dataset 'churn'.
[2018-04-11 22:14:15] Error in run 374: Run already exists in server. Run id(s): {8985243}
[2018-04-11 22:14:15] Started run 382 on task 146227, dataset 'churn'.
[2018-04-11 22:14:16] Error in run 375: Run already exists in server. Run id(s): {8985242}
[2018-04-11 22:14:16] Started run 383 on task 146227, dataset 'churn'.
[2018-04-11 22:14:16] Error in run 376: Run already exists in server. Run id(s): {8985256}
[2018-04-11 22:14:16] Started run 384 on task 146227, dataset 'churn'.
[2018-04-11 22:14:18] Error in run 377: Run already exists in server. Run id(s): {8985250}
[2018-04-11 22:14:18] Started run 385 on task 146227, dataset 'churn'.
[2018-04-11 22:14:18] Error in run 378: Run already exists in server. Run id(s): {8985264}
[2018-04-11 22:14:18] Started run 386 on task 146227, dataset 'churn'.
[2018-04-11 22:14:19] Error in run 379: Run already exists in server. Run id(s): {8985258, 9014924}
[2018-04-11 22:14:19] Started run 387 on task 146227, dataset 'churn'.
[2018-04-11 22:14:19] Error in run 380: Run already exists in server. Run id(s): {8985265, 9014871}
[2018-04-11 22:14:19] Started run 388 on task 146227, dataset 'churn'.
[2018-04-11 22:14:19] Error in run 381: Run already exists in server. Run id(s): {8985272}
[2018-04-11 22:14:19] Started run 389 on task 146227, dataset 'churn'.
[2018-04-11 22:14:20] Error in run 382: Run already exists in server. Run id(s): {8985271}
[2018-04-11 22:14:20] Started run 390 on task 146227, dataset 'churn'.
[2018-04-11 22:14:20] Error in run 383: Run already exists in server. Run id(s): {8985278}
[2018-04-11 22:14:20] Started run 391 on task 146227, dataset 'churn'.
[2018-04-11 22:14:21] Error in run 384: Run already exists in server. Run id(s): {8985280}
[2018-04-11 22:14:21] Started run 392 on task 146227, dataset 'churn'.
[2018-04-11 22:14:22] Error in run 385: Run already exists in server. Run id(s): {8985295}
[2018-04-11 22:14:22] Started run 393 on task 146227, dataset 'churn'.
[2018-04-11 22:14:22] Error in run 386: Run already exists in server. Run id(s): {8985287}
[2018-04-11 22:14:22] Started run 394 on task 146227, dataset 'churn'.
[2018-04-11 22:14:23] Error in run 387: Run already exists in server. Run id(s): {8985293}
[2018-04-11 22:14:23] Started run 395 on task 146227, dataset 'churn'.
[2018-04-11 22:14:24] Error in run 389: Run already exists in server. Run id(s): {8985301}
[2018-04-11 22:14:24] Started run 396 on task 146227, dataset 'churn'.
[2018-04-11 22:14:24] Error in run 388: Run already exists in server. Run id(s): {8985296}
[2018-04-11 22:14:24] Started run 397 on task 146227, dataset 'churn'.
[2018-04-11 22:14:24] Error in run 390: Run already exists in server. Run id(s): {8985314}
[2018-04-11 22:14:24] Started run 398 on task 146227, dataset 'churn'.
[2018-04-11 22:14:25] Error in run 391: Run already exists in server. Run id(s): {8985307}
[2018-04-11 22:14:25] Started run 399 on task 146227, dataset 'churn'.
[2018-04-11 22:14:25] Error in run 392: Run already exists in server. Run id(s): {8985315}
[2018-04-11 22:14:25] Started run 400 on task 146227, dataset 'churn'.
[2018-04-11 22:14:27] Error in run 393: Run already exists in server. Run id(s): {8985327}
[2018-04-11 22:14:27] Started run 401 on task 146227, dataset 'churn'.
[2018-04-11 22:14:27] Error in run 394: Run already exists in server. Run id(s): {8985329}
[2018-04-11 22:14:27] Started run 402 on task 146227, dataset 'churn'.
[2018-04-11 22:14:27] Error in run 395: Run already exists in server. Run id(s): {8985330}
[2018-04-11 22:14:27] Started run 403 on task 146227, dataset 'churn'.
[2018-04-11 22:14:28] Error in run 396: Run already exists in server. Run id(s): {8985340}
[2018-04-11 22:14:28] Started run 404 on task 146227, dataset 'churn'.
[2018-04-11 22:14:28] Error in run 397: Run already exists in server. Run id(s): {8985350}
[2018-04-11 22:14:28] Started run 405 on task 146227, dataset 'churn'.
[2018-04-11 22:14:29] Error in run 398: Run already exists in server. Run id(s): {8985344}
[2018-04-11 22:14:29] Started run 406 on task 146227, dataset 'churn'.
[2018-04-11 22:14:29] Error in run 399: Run already exists in server. Run id(s): {8985352}
[2018-04-11 22:14:29] Started run 407 on task 146227, dataset 'churn'.
[2018-04-11 22:14:30] Error in run 400: Run already exists in server. Run id(s): {8985349}
[2018-04-11 22:14:30] Started run 408 on task 146227, dataset 'churn'.
[2018-04-11 22:14:31] Error in run 401: Run already exists in server. Run id(s): {8985357}
[2018-04-11 22:14:31] Started run 409 on task 146227, dataset 'churn'.
[2018-04-11 22:14:31] Error in run 402: Run already exists in server. Run id(s): {8985371}
[2018-04-11 22:14:31] Started run 410 on task 146227, dataset 'churn'.
[2018-04-11 22:14:32] Error in run 403: Run already exists in server. Run id(s): {8985368}
[2018-04-11 22:14:32] Started run 411 on task 146227, dataset 'churn'.
[2018-04-11 22:14:33] Error in run 404: Run already exists in server. Run id(s): {8985362}
[2018-04-11 22:14:33] Started run 412 on task 146227, dataset 'churn'.
[2018-04-11 22:14:33] Error in run 405: Run already exists in server. Run id(s): {8985374}
[2018-04-11 22:14:33] Started run 413 on task 146227, dataset 'churn'.
[2018-04-11 22:14:33] Error in run 406: Run already exists in server. Run id(s): {8985375}
[2018-04-11 22:14:33] Started run 414 on task 146227, dataset 'churn'.
[2018-04-11 22:14:33] Error in run 407: Run already exists in server. Run id(s): {8985393}
[2018-04-11 22:14:33] Started run 415 on task 146227, dataset 'churn'.
[2018-04-11 22:14:34] Error in run 408: Run already exists in server. Run id(s): {8985392}
[2018-04-11 22:14:34] Started run 416 on task 146227, dataset 'churn'.
[2018-04-11 22:14:36] Error in run 409: Run already exists in server. Run id(s): {8985386, 9014990}
[2018-04-11 22:14:36] Started run 417 on task 146227, dataset 'churn'.
[2018-04-11 22:14:36] Error in run 410: Run already exists in server. Run id(s): {8985387}
[2018-04-11 22:14:36] Started run 418 on task 146227, dataset 'churn'.
[2018-04-11 22:14:37] Error in run 411: Run already exists in server. Run id(s): {8985409}
[2018-04-11 22:14:37] Started run 419 on task 146227, dataset 'churn'.
[2018-04-11 22:14:37] Error in run 412: Run already exists in server. Run id(s): {8985399}
[2018-04-11 22:14:37] Started run 420 on task 146227, dataset 'churn'.
[2018-04-11 22:14:37] Error in run 413: Run already exists in server. Run id(s): {8985407}
[2018-04-11 22:14:37] Started run 421 on task 146227, dataset 'churn'.
[2018-04-11 22:14:38] Error in run 415: Run already exists in server. Run id(s): {8985424}
[2018-04-11 22:14:38] Started run 422 on task 146227, dataset 'churn'.
[2018-04-11 22:14:38] Error in run 414: Run already exists in server. Run id(s): {8985415}
[2018-04-11 22:14:38] Started run 423 on task 146227, dataset 'churn'.
[2018-04-11 22:14:39] Error in run 416: Run already exists in server. Run id(s): {8985418}
[2018-04-11 22:14:39] Started run 424 on task 146227, dataset 'churn'.
[2018-04-11 22:14:40] Error in run 417: Run already exists in server. Run id(s): {8985426}
[2018-04-11 22:14:40] Started run 425 on task 146227, dataset 'churn'.
[2018-04-11 22:14:40] Error in run 418: Run already exists in server. Run id(s): {8985433}
[2018-04-11 22:14:40] Started run 426 on task 146227, dataset 'churn'.
[2018-04-11 22:14:41] Error in run 419: Run already exists in server. Run id(s): {8985431}
[2018-04-11 22:14:41] Started run 427 on task 146227, dataset 'churn'.
[2018-04-11 22:14:42] Error in run 420: Run already exists in server. Run id(s): {8985436}
[2018-04-11 22:14:42] Started run 428 on task 146227, dataset 'churn'.
[2018-04-11 22:14:42] Error in run 421: Run already exists in server. Run id(s): {8985442}
[2018-04-11 22:14:42] Started run 429 on task 146227, dataset 'churn'.
[2018-04-11 22:14:42] Error in run 422: Run already exists in server. Run id(s): {8985445}
[2018-04-11 22:14:42] Started run 430 on task 146227, dataset 'churn'.
[2018-04-11 22:14:43] Error in run 423: Run already exists in server. Run id(s): {8985447}
[2018-04-11 22:14:43] Started run 431 on task 146227, dataset 'churn'.
[2018-04-11 22:14:44] Error in run 424: Run already exists in server. Run id(s): {8985448}
[2018-04-11 22:14:44] Started run 432 on task 146227, dataset 'churn'.
[2018-04-11 22:14:45] Error in run 425: Run already exists in server. Run id(s): {8985465}
[2018-04-11 22:14:45] Started run 433 on task 146227, dataset 'churn'.
[2018-04-11 22:14:45] Error in run 426: Run already exists in server. Run id(s): {8985466}
[2018-04-11 22:14:45] Started run 434 on task 146227, dataset 'churn'.
[2018-04-11 22:14:46] Error in run 427: Run already exists in server. Run id(s): {8985470}
[2018-04-11 22:14:46] Started run 435 on task 146227, dataset 'churn'.
[2018-04-11 22:14:46] Error in run 428: Run already exists in server. Run id(s): {8985460}
[2018-04-11 22:14:46] Started run 436 on task 146227, dataset 'churn'.
[2018-04-11 22:14:46] Error in run 429: Run already exists in server. Run id(s): {8985477}
[2018-04-11 22:14:46] Started run 437 on task 146227, dataset 'churn'.
[2018-04-11 22:14:47] Error in run 430: Run already exists in server. Run id(s): {8985476}
[2018-04-11 22:14:47] Started run 438 on task 146227, dataset 'churn'.
[2018-04-11 22:14:48] Error in run 431: Run already exists in server. Run id(s): {8985478}
[2018-04-11 22:14:48] Started run 439 on task 146227, dataset 'churn'.
[2018-04-11 22:14:48] Error in run 432: Run already exists in server. Run id(s): {8985481}
[2018-04-11 22:14:48] Started run 440 on task 146227, dataset 'churn'.
[2018-04-11 22:14:49] Error in run 433: Run already exists in server. Run id(s): {8985490}
[2018-04-11 22:14:49] Started run 441 on task 146227, dataset 'churn'.
[2018-04-11 22:14:49] Error in run 434: Run already exists in server. Run id(s): {8985492}
[2018-04-11 22:14:49] Started run 442 on task 146227, dataset 'churn'.
[2018-04-11 22:14:51] Error in run 435: Run already exists in server. Run id(s): {8985494}
[2018-04-11 22:14:51] Started run 443 on task 146227, dataset 'churn'.
[2018-04-11 22:14:51] Error in run 437: Run already exists in server. Run id(s): {8985505}
[2018-04-11 22:14:51] Error in run 436: Run already exists in server. Run id(s): {8985497}
[2018-04-11 22:14:51] Started run 444 on task 146227, dataset 'churn'.
[2018-04-11 22:14:51] Started run 445 on task 146227, dataset 'churn'.
[2018-04-11 22:14:51] Error in run 438: Run already exists in server. Run id(s): {8985507}
[2018-04-11 22:14:51] Started run 446 on task 146227, dataset 'churn'.
[2018-04-11 22:14:52] Error in run 439: Run already exists in server. Run id(s): {8985517}
[2018-04-11 22:14:52] Started run 447 on task 146227, dataset 'churn'.
[2018-04-11 22:14:53] Error in run 440: Run already exists in server. Run id(s): {8985510}
[2018-04-11 22:14:53] Started run 448 on task 146227, dataset 'churn'.
[2018-04-11 22:14:54] Error in run 441: Run already exists in server. Run id(s): {8985523}
[2018-04-11 22:14:54] Started run 449 on task 146227, dataset 'churn'.
[2018-04-11 22:14:54] Error in run 442: Run already exists in server. Run id(s): {8985519}
[2018-04-11 22:14:54] Started run 450 on task 146227, dataset 'churn'.
[2018-04-11 22:14:55] Error in run 443: Run already exists in server. Run id(s): {8985528}
[2018-04-11 22:14:55] Started run 451 on task 146227, dataset 'churn'.
[2018-04-11 22:14:55] Error in run 444: Run already exists in server. Run id(s): {8985530}
[2018-04-11 22:14:55] Started run 452 on task 146227, dataset 'churn'.
[2018-04-11 22:14:56] Error in run 445: Run already exists in server. Run id(s): {8985537}
[2018-04-11 22:14:56] Started run 453 on task 146227, dataset 'churn'.
[2018-04-11 22:14:56] Error in run 446: Run already exists in server. Run id(s): {8985538}
[2018-04-11 22:14:56] Started run 454 on task 146227, dataset 'churn'.
[2018-04-11 22:14:57] Error in run 447: Run already exists in server. Run id(s): {8985539}
[2018-04-11 22:14:57] Started run 455 on task 146227, dataset 'churn'.
[2018-04-11 22:14:57] Error in run 448: Run already exists in server. Run id(s): {8985543}
[2018-04-11 22:14:57] Started run 456 on task 146227, dataset 'churn'.
[2018-04-11 22:14:58] Error in run 449: Run already exists in server. Run id(s): {8985554}
[2018-04-11 22:14:58] Started run 457 on task 146227, dataset 'churn'.
[2018-04-11 22:14:59] Error in run 450: Run already exists in server. Run id(s): {8985555}
[2018-04-11 22:14:59] Started run 458 on task 146227, dataset 'churn'.
[2018-04-11 22:15:00] Error in run 451: Run already exists in server. Run id(s): {8985550}
[2018-04-11 22:15:00] Started run 459 on task 146227, dataset 'churn'.
[2018-04-11 22:15:00] Error in run 452: Run already exists in server. Run id(s): {8985556}
[2018-04-11 22:15:00] Started run 460 on task 146227, dataset 'churn'.
[2018-04-11 22:15:00] Error in run 453: Run already exists in server. Run id(s): {8985565}
[2018-04-11 22:15:00] Started run 461 on task 146227, dataset 'churn'.
[2018-04-11 22:15:00] Error in run 454: Run already exists in server. Run id(s): {8985571}
[2018-04-11 22:15:00] Started run 462 on task 146227, dataset 'churn'.
[2018-04-11 22:15:01] Error in run 455: Run already exists in server. Run id(s): {8985568}
[2018-04-11 22:15:01] Started run 463 on task 146227, dataset 'churn'.
[2018-04-11 22:15:02] Error in run 456: Run already exists in server. Run id(s): {8985570}
[2018-04-11 22:15:02] Started run 464 on task 146227, dataset 'churn'.
[2018-04-11 22:15:03] Error in run 457: Run already exists in server. Run id(s): {8985583}
[2018-04-11 22:15:03] Started run 465 on task 146227, dataset 'churn'.
[2018-04-11 22:15:03] Error in run 458: Run already exists in server. Run id(s): {8985578}
[2018-04-11 22:15:03] Started run 466 on task 146227, dataset 'churn'.
[2018-04-11 22:15:04] Error in run 459: Run already exists in server. Run id(s): {8985584}
[2018-04-11 22:15:04] Started run 467 on task 146227, dataset 'churn'.
[2018-04-11 22:15:04] Error in run 460: Run already exists in server. Run id(s): {8985585}
[2018-04-11 22:15:04] Started run 468 on task 146227, dataset 'churn'.
[2018-04-11 22:15:05] Error in run 461: Run already exists in server. Run id(s): {8985598}
[2018-04-11 22:15:05] Started run 469 on task 146227, dataset 'churn'.
[2018-04-11 22:15:05] Error in run 462: Run already exists in server. Run id(s): {8985594}
[2018-04-11 22:15:05] Started run 470 on task 146227, dataset 'churn'.
[2018-04-11 22:15:06] Error in run 463: Run already exists in server. Run id(s): {8985632}
[2018-04-11 22:15:06] Started run 471 on task 146227, dataset 'churn'.
[2018-04-11 22:15:06] Error in run 464: Run already exists in server. Run id(s): {8985596}
[2018-04-11 22:15:06] Started run 472 on task 146227, dataset 'churn'.
[2018-04-11 22:15:08] Error in run 465: Run already exists in server. Run id(s): {8985601, 9015231}
[2018-04-11 22:15:08] Started run 473 on task 146227, dataset 'churn'.
[2018-04-11 22:15:08] Error in run 466: Run already exists in server. Run id(s): {8985624}
[2018-04-11 22:15:08] Started run 474 on task 146227, dataset 'churn'.
[2018-04-11 22:15:09] Error in run 467: Run already exists in server. Run id(s): {8985603}
[2018-04-11 22:15:09] Started run 475 on task 146227, dataset 'churn'.
[2018-04-11 22:15:09] Error in run 468: Run already exists in server. Run id(s): {8985615}
[2018-04-11 22:15:09] Started run 476 on task 146227, dataset 'churn'.
[2018-04-11 22:15:09] Error in run 469: Run already exists in server. Run id(s): {8985619}
[2018-04-11 22:15:09] Started run 477 on task 146227, dataset 'churn'.
[2018-04-11 22:15:10] Error in run 470: Run already exists in server. Run id(s): {8985637}
[2018-04-11 22:15:10] Started run 478 on task 146227, dataset 'churn'.
[2018-04-11 22:15:10] Error in run 471: Run already exists in server. Run id(s): {8985647}
[2018-04-11 22:15:10] Started run 479 on task 146227, dataset 'churn'.
[2018-04-11 22:15:11] Error in run 472: Run already exists in server. Run id(s): {8985643}
[2018-04-11 22:15:11] Started run 480 on task 146227, dataset 'churn'.
[2018-04-11 22:15:12] Error in run 473: Run already exists in server. Run id(s): {8985648}
[2018-04-11 22:15:12] Started run 481 on task 146227, dataset 'churn'.
[2018-04-11 22:15:12] Error in run 474: Run already exists in server. Run id(s): {8985654}
[2018-04-11 22:15:12] Started run 482 on task 146227, dataset 'churn'.
[2018-04-11 22:15:13] Error in run 475: Run already exists in server. Run id(s): {8985660}
[2018-04-11 22:15:13] Started run 483 on task 146227, dataset 'churn'.
[2018-04-11 22:15:14] Error in run 476: Run already exists in server. Run id(s): {8985664}
[2018-04-11 22:15:14] Started run 484 on task 146227, dataset 'churn'.
[2018-04-11 22:15:14] Error in run 477: Run already exists in server. Run id(s): {8985662}
[2018-04-11 22:15:14] Started run 485 on task 146227, dataset 'churn'.
[2018-04-11 22:15:14] Error in run 478: Run already exists in server. Run id(s): {8985678}
[2018-04-11 22:15:14] Started run 486 on task 146227, dataset 'churn'.
[2018-04-11 22:15:15] Error in run 479: Run already exists in server. Run id(s): {8985676}
[2018-04-11 22:15:15] Started run 487 on task 146227, dataset 'churn'.
[2018-04-11 22:15:15] Error in run 480: Run already exists in server. Run id(s): {8985680}
[2018-04-11 22:15:15] Started run 488 on task 146227, dataset 'churn'.
[2018-04-11 22:15:17] Error in run 481: Run already exists in server. Run id(s): {8985679}
[2018-04-11 22:15:17] Started run 489 on task 146227, dataset 'churn'.
[2018-04-11 22:15:17] Error in run 482: Run already exists in server. Run id(s): {8985704}
[2018-04-11 22:15:17] Started run 490 on task 146227, dataset 'churn'.
[2018-04-11 22:15:18] Error in run 483: Run already exists in server. Run id(s): {8985694}
[2018-04-11 22:15:18] Started run 491 on task 146227, dataset 'churn'.
[2018-04-11 22:15:18] Error in run 484: Run already exists in server. Run id(s): {8985693}
[2018-04-11 22:15:18] Started run 492 on task 146227, dataset 'churn'.
[2018-04-11 22:15:18] Error in run 485: Run already exists in server. Run id(s): {9015396, 8985695}
[2018-04-11 22:15:18] Started run 493 on task 146227, dataset 'churn'.
[2018-04-11 22:15:19] Error in run 486: Run already exists in server. Run id(s): {8985710}
[2018-04-11 22:15:19] Started run 494 on task 146227, dataset 'churn'.
[2018-04-11 22:15:19] Error in run 487: Run already exists in server. Run id(s): {8985719}
[2018-04-11 22:15:19] Started run 495 on task 146227, dataset 'churn'.
[2018-04-11 22:15:20] Error in run 488: Run already exists in server. Run id(s): {8985712}
[2018-04-11 22:15:20] Started run 496 on task 146227, dataset 'churn'.
[2018-04-11 22:15:21] Error in run 489: Run already exists in server. Run id(s): {8985718}
[2018-04-11 22:15:21] Started run 497 on task 146227, dataset 'churn'.
[2018-04-11 22:15:22] Error in run 490: Run already exists in server. Run id(s): {8985730}
[2018-04-11 22:15:22] Started run 498 on task 146227, dataset 'churn'.
[2018-04-11 22:15:23] Error in run 491: Run already exists in server. Run id(s): {8985726}
[2018-04-11 22:15:23] Started run 499 on task 146227, dataset 'churn'.
[2018-04-11 22:15:23] Error in run 493: Run already exists in server. Run id(s): {8985745}
[2018-04-11 22:15:23] Started run 500 on task 146227, dataset 'churn'.
[2018-04-11 22:15:23] Error in run 492: Run already exists in server. Run id(s): {8985731}
[2018-04-11 22:15:23] Started run 501 on task 146227, dataset 'churn'.
[2018-04-11 22:15:23] Error in run 494: Run already exists in server. Run id(s): {8985753}
[2018-04-11 22:15:23] Started run 502 on task 146227, dataset 'churn'.
[2018-04-11 22:15:24] Error in run 495: Run already exists in server. Run id(s): {8985754}
[2018-04-11 22:15:24] Started run 503 on task 146227, dataset 'churn'.
[2018-04-11 22:15:25] Error in run 496: Run already exists in server. Run id(s): {8985746}
[2018-04-11 22:15:25] Started run 504 on task 146227, dataset 'churn'.
[2018-04-11 22:15:26] Error in run 497: Run already exists in server. Run id(s): {8985758}
[2018-04-11 22:15:26] Started run 505 on task 146227, dataset 'churn'.
[2018-04-11 22:15:26] Error in run 498: Run already exists in server. Run id(s): {8985760}
[2018-04-11 22:15:26] Started run 506 on task 146227, dataset 'churn'.
[2018-04-11 22:15:27] Error in run 499: Run already exists in server. Run id(s): {8985764}
[2018-04-11 22:15:27] Started run 507 on task 146227, dataset 'churn'.
[2018-04-11 22:15:27] Error in run 500: Run already exists in server. Run id(s): {8985767}
[2018-04-11 22:15:27] Started run 508 on task 146227, dataset 'churn'.
[2018-04-11 22:15:27] Error in run 501: Run already exists in server. Run id(s): {8985776}
[2018-04-11 22:15:27] Started run 509 on task 146227, dataset 'churn'.
[2018-04-11 22:15:28] Error in run 502: Run already exists in server. Run id(s): {8985780}
[2018-04-11 22:15:28] Started run 510 on task 146227, dataset 'churn'.
[2018-04-11 22:15:28] Error in run 503: Run already exists in server. Run id(s): {8985787}
[2018-04-11 22:15:28] Started run 511 on task 146227, dataset 'churn'.
[2018-04-11 22:15:30] Error in run 504: Run already exists in server. Run id(s): {8985781}
[2018-04-11 22:15:30] Started run 512 on task 146227, dataset 'churn'.
[2018-04-11 22:15:31] Error in run 505: Run already exists in server. Run id(s): {8985791}
[2018-04-11 22:15:31] Started run 513 on task 146227, dataset 'churn'.
[2018-04-11 22:15:31] Error in run 506: Run already exists in server. Run id(s): {8985794}
[2018-04-11 22:15:31] Started run 514 on task 146227, dataset 'churn'.
[2018-04-11 22:15:32] Error in run 507: Run already exists in server. Run id(s): {8985808}
[2018-04-11 22:15:32] Started run 515 on task 146227, dataset 'churn'.
[2018-04-11 22:15:32] Error in run 508: Run already exists in server. Run id(s): {8985799}
[2018-04-11 22:15:32] Started run 516 on task 146227, dataset 'churn'.
[2018-04-11 22:15:32] Error in run 509: Run already exists in server. Run id(s): {8985805}
[2018-04-11 22:15:32] Started run 517 on task 146227, dataset 'churn'.
[2018-04-11 22:15:32] Error in run 510: Run already exists in server. Run id(s): {8985810}
[2018-04-11 22:15:32] Started run 518 on task 146227, dataset 'churn'.
[2018-04-11 22:15:33] Error in run 511: Run already exists in server. Run id(s): {8985828}
[2018-04-11 22:15:33] Started run 519 on task 146227, dataset 'churn'.
[2018-04-11 22:15:34] Error in run 512: Run already exists in server. Run id(s): {8985830}
[2018-04-11 22:15:34] Started run 520 on task 146227, dataset 'churn'.
[2018-04-11 22:15:35] Error in run 513: Run already exists in server. Run id(s): {8985826}
[2018-04-11 22:15:35] Started run 521 on task 146227, dataset 'churn'.
[2018-04-11 22:15:35] Error in run 514: Run already exists in server. Run id(s): {8985829}
[2018-04-11 22:15:35] Started run 522 on task 146227, dataset 'churn'.
[2018-04-11 22:15:36] Error in run 515: Run already exists in server. Run id(s): {8985841}
[2018-04-11 22:15:36] Started run 523 on task 146227, dataset 'churn'.
[2018-04-11 22:15:37] Error in run 516: Run already exists in server. Run id(s): {8985848}
[2018-04-11 22:15:37] Started run 524 on task 146227, dataset 'churn'.
[2018-04-11 22:15:37] Error in run 517: Run already exists in server. Run id(s): {8985843}
[2018-04-11 22:15:37] Started run 525 on task 146227, dataset 'churn'.
[2018-04-11 22:15:37] Error in run 518: Run already exists in server. Run id(s): {8985849}
[2018-04-11 22:15:37] Started run 526 on task 146227, dataset 'churn'.
[2018-04-11 22:15:38] Error in run 519: Run already exists in server. Run id(s): {8985850}
[2018-04-11 22:15:38] Started run 527 on task 146227, dataset 'churn'.
[2018-04-11 22:15:39] Error in run 520: Run already exists in server. Run id(s): {8985860}
[2018-04-11 22:15:39] Started run 528 on task 146227, dataset 'churn'.
[2018-04-11 22:15:40] Error in run 521: Run already exists in server. Run id(s): {8985859}
[2018-04-11 22:15:40] Started run 529 on task 146227, dataset 'churn'.
[2018-04-11 22:15:40] Error in run 522: Run already exists in server. Run id(s): {8985867}
[2018-04-11 22:15:40] Started run 530 on task 146227, dataset 'churn'.
[2018-04-11 22:15:41] Error in run 523: Run already exists in server. Run id(s): {8985861}
[2018-04-11 22:15:41] Started run 531 on task 146227, dataset 'churn'.
[2018-04-11 22:15:41] Error in run 524: Run already exists in server. Run id(s): {8985873}
[2018-04-11 22:15:41] Started run 532 on task 146227, dataset 'churn'.
[2018-04-11 22:15:41] Error in run 525: Run already exists in server. Run id(s): {8985874}
[2018-04-11 22:15:41] Started run 533 on task 146227, dataset 'churn'.
[2018-04-11 22:15:42] Error in run 526: Run already exists in server. Run id(s): {8985878}
[2018-04-11 22:15:42] Started run 534 on task 146227, dataset 'churn'.
[2018-04-11 22:15:43] Error in run 527: Run already exists in server. Run id(s): {8985880}
[2018-04-11 22:15:43] Started run 535 on task 146227, dataset 'churn'.
[2018-04-11 22:15:43] Error in run 528: Run already exists in server. Run id(s): {8985899}
[2018-04-11 22:15:43] Started run 536 on task 146227, dataset 'churn'.
[2018-04-11 22:15:44] Error in run 529: Run already exists in server. Run id(s): {8985885}
[2018-04-11 22:15:44] Started run 537 on task 146227, dataset 'churn'.
[2018-04-11 22:15:44] Error in run 530: Run already exists in server. Run id(s): {8985894}
[2018-04-11 22:15:44] Started run 538 on task 146227, dataset 'churn'.
[2018-04-11 22:15:45] Error in run 531: Run already exists in server. Run id(s): {8985898}
[2018-04-11 22:15:45] Started run 539 on task 146227, dataset 'churn'.
[2018-04-11 22:15:46] Error in run 532: Run already exists in server. Run id(s): {8985907}
[2018-04-11 22:15:46] Started run 540 on task 146227, dataset 'churn'.
[2018-04-11 22:15:46] Error in run 533: Run already exists in server. Run id(s): {8985908}
[2018-04-11 22:15:46] Started run 541 on task 146227, dataset 'churn'.
[2018-04-11 22:15:46] Error in run 534: Run already exists in server. Run id(s): {8985917}
[2018-04-11 22:15:46] Started run 542 on task 146227, dataset 'churn'.
[2018-04-11 22:15:47] Error in run 535: Run already exists in server. Run id(s): {8985916}
[2018-04-11 22:15:47] Started run 543 on task 146227, dataset 'churn'.
[2018-04-11 22:15:48] Error in run 536: Run already exists in server. Run id(s): {8985923}
[2018-04-11 22:15:48] Started run 544 on task 146227, dataset 'churn'.
[2018-04-11 22:15:48] Error in run 538: Run already exists in server. Run id(s): {8985940}
[2018-04-11 22:15:48] Started run 545 on task 146227, dataset 'churn'.
[2018-04-11 22:15:49] Error in run 537: Run already exists in server. Run id(s): {8985930}
[2018-04-11 22:15:49] Started run 546 on task 146227, dataset 'churn'.
[2018-04-11 22:15:50] Error in run 539: Run already exists in server. Run id(s): {8985934}
[2018-04-11 22:15:50] Started run 547 on task 146227, dataset 'churn'.
[2018-04-11 22:15:50] Error in run 540: Run already exists in server. Run id(s): {8985942}
[2018-04-11 22:15:50] Started run 548 on task 146227, dataset 'churn'.
[2018-04-11 22:15:50] Error in run 541: Run already exists in server. Run id(s): {8985951}
[2018-04-11 22:15:50] Started run 549 on task 146227, dataset 'churn'.
[2018-04-11 22:15:51] Error in run 542: Run already exists in server. Run id(s): {8985955}
[2018-04-11 22:15:51] Started run 550 on task 146227, dataset 'churn'.
[2018-04-11 22:15:52] Error in run 543: Run already exists in server. Run id(s): {8985952}
[2018-04-11 22:15:52] Started run 551 on task 146227, dataset 'churn'.
[2018-04-11 22:15:52] Error in run 544: Run already exists in server. Run id(s): {8985954}
[2018-04-11 22:15:52] Started run 552 on task 146227, dataset 'churn'.
[2018-04-11 22:15:53] Error in run 546: Run already exists in server. Run id(s): {8985963}
[2018-04-11 22:15:53] Started run 553 on task 146227, dataset 'churn'.
[2018-04-11 22:15:53] Error in run 545: Run already exists in server. Run id(s): {8985964}
[2018-04-11 22:15:53] Started run 554 on task 146227, dataset 'churn'.
[2018-04-11 22:15:55] Error in run 547: Run already exists in server. Run id(s): {8985966}
[2018-04-11 22:15:55] Started run 555 on task 146227, dataset 'churn'.
[2018-04-11 22:15:55] Error in run 548: Run already exists in server. Run id(s): {8985971}
[2018-04-11 22:15:55] Started run 556 on task 146227, dataset 'churn'.
[2018-04-11 22:15:55] Error in run 549: Run already exists in server. Run id(s): {8985974}
[2018-04-11 22:15:55] Started run 557 on task 146227, dataset 'churn'.
[2018-04-11 22:15:55] Error in run 550: Run already exists in server. Run id(s): {8985986}
[2018-04-11 22:15:55] Started run 558 on task 146227, dataset 'churn'.
[2018-04-11 22:15:56] Error in run 551: Run already exists in server. Run id(s): {8985985}
[2018-04-11 22:15:56] Started run 559 on task 146227, dataset 'churn'.
[2018-04-11 22:15:57] Error in run 552: Run already exists in server. Run id(s): {8985992}
[2018-04-11 22:15:57] Started run 560 on task 146227, dataset 'churn'.
[2018-04-11 22:15:57] Error in run 553: Run already exists in server. Run id(s): {8985987}
[2018-04-11 22:15:57] Started run 561 on task 146227, dataset 'churn'.
[2018-04-11 22:15:58] Error in run 554: Run already exists in server. Run id(s): {8985999}
[2018-04-11 22:15:58] Started run 562 on task 146227, dataset 'churn'.
[2018-04-11 22:15:59] Error in run 555: Run already exists in server. Run id(s): {8986000}
[2018-04-11 22:15:59] Started run 563 on task 146227, dataset 'churn'.
[2018-04-11 22:15:59] Error in run 556: Run already exists in server. Run id(s): {8986002}
[2018-04-11 22:15:59] Started run 564 on task 146227, dataset 'churn'.
[2018-04-11 22:15:59] Error in run 557: Run already exists in server. Run id(s): {8986007}
[2018-04-11 22:15:59] Started run 565 on task 146227, dataset 'churn'.
[2018-04-11 22:16:00] Error in run 558: Run already exists in server. Run id(s): {8986014}
[2018-04-11 22:16:00] Started run 566 on task 146227, dataset 'churn'.
[2018-04-11 22:16:00] Error in run 559: Run already exists in server. Run id(s): {8986015}
[2018-04-11 22:16:00] Started run 567 on task 146227, dataset 'churn'.
[2018-04-11 22:16:01] Error in run 560: Run already exists in server. Run id(s): {8986019}
[2018-04-11 22:16:01] Started run 568 on task 146227, dataset 'churn'.
[2018-04-11 22:16:02] Error in run 561: Run already exists in server. Run id(s): {8986021}
[2018-04-11 22:16:02] Started run 569 on task 146227, dataset 'churn'.
[2018-04-11 22:16:02] Error in run 562: Run already exists in server. Run id(s): {8986026}
[2018-04-11 22:16:02] Started run 570 on task 146227, dataset 'churn'.
[2018-04-11 22:16:03] Error in run 563: Run already exists in server. Run id(s): {8986027}
[2018-04-11 22:16:03] Started run 571 on task 146227, dataset 'churn'.
[2018-04-11 22:16:04] Error in run 564: Run already exists in server. Run id(s): {8986040}
[2018-04-11 22:16:04] Started run 572 on task 146227, dataset 'churn'.
[2018-04-11 22:16:04] Error in run 565: Run already exists in server. Run id(s): {8986033}
[2018-04-11 22:16:04] Started run 573 on task 146227, dataset 'churn'.
[2018-04-11 22:16:04] Error in run 566: Run already exists in server. Run id(s): {8986039}
[2018-04-11 22:16:04] Started run 574 on task 146227, dataset 'churn'.
[2018-04-11 22:16:05] Error in run 567: Run already exists in server. Run id(s): {8986045}
[2018-04-11 22:16:05] Started run 575 on task 146227, dataset 'churn'.
[2018-04-11 22:16:06] Error in run 568: Run already exists in server. Run id(s): {8986046}
[2018-04-11 22:16:06] Started run 576 on task 146227, dataset 'churn'.
[2018-04-11 22:16:07] Error in run 569: Run already exists in server. Run id(s): {8986066}
[2018-04-11 22:16:07] Started run 577 on task 146227, dataset 'churn'.
[2018-04-11 22:16:07] Error in run 570: Run already exists in server. Run id(s): {8986051}
[2018-04-11 22:16:07] Started run 578 on task 146227, dataset 'churn'.
[2018-04-11 22:16:08] Error in run 571: Run already exists in server. Run id(s): {8986058}
[2018-04-11 22:16:08] Started run 579 on task 146227, dataset 'churn'.
[2018-04-11 22:16:08] Error in run 572: Run already exists in server. Run id(s): {8986059}
[2018-04-11 22:16:08] Started run 580 on task 146227, dataset 'churn'.
[2018-04-11 22:16:09] Error in run 573: Run already exists in server. Run id(s): {8986067}
[2018-04-11 22:16:09] Started run 581 on task 146227, dataset 'churn'.
[2018-04-11 22:16:09] Error in run 574: Run already exists in server. Run id(s): {8986072}
[2018-04-11 22:16:09] Started run 582 on task 146227, dataset 'churn'.
[2018-04-11 22:16:10] Error in run 575: Run already exists in server. Run id(s): {8986075}
[2018-04-11 22:16:10] Started run 583 on task 146227, dataset 'churn'.
[2018-04-11 22:16:10] Error in run 576: Run already exists in server. Run id(s): {8986081}
[2018-04-11 22:16:10] Started run 584 on task 146227, dataset 'churn'.
[2018-04-11 22:16:11] Error in run 578: Run already exists in server. Run id(s): {8986087}
[2018-04-11 22:16:11] Started run 585 on task 146227, dataset 'churn'.
[2018-04-11 22:16:11] Error in run 577: Run already exists in server. Run id(s): {8986080}
[2018-04-11 22:16:11] Started run 586 on task 146227, dataset 'churn'.
[2018-04-11 22:16:12] Error in run 579: Run already exists in server. Run id(s): {8986090}
[2018-04-11 22:16:12] Started run 587 on task 146227, dataset 'churn'.
[2018-04-11 22:16:13] Error in run 580: Run already exists in server. Run id(s): {8986094}
[2018-04-11 22:16:13] Started run 588 on task 146227, dataset 'churn'.
[2018-04-11 22:16:13] Error in run 581: Run already exists in server. Run id(s): {8986093}
[2018-04-11 22:16:13] Started run 589 on task 146227, dataset 'churn'.
[2018-04-11 22:16:13] Error in run 582: Run already exists in server. Run id(s): {8986099}
[2018-04-11 22:16:13] Started run 590 on task 146227, dataset 'churn'.
[2018-04-11 22:16:14] Error in run 583: Run already exists in server. Run id(s): {8986111}
[2018-04-11 22:16:14] Started run 591 on task 146227, dataset 'churn'.
[2018-04-11 22:16:15] Error in run 584: Run already exists in server. Run id(s): {8986104}
[2018-04-11 22:16:15] Started run 592 on task 146227, dataset 'churn'.
[2018-04-11 22:16:16] Error in run 585: Run already exists in server. Run id(s): {8986106}
[2018-04-11 22:16:16] Started run 593 on task 146227, dataset 'churn'.
[2018-04-11 22:16:16] Error in run 586: Run already exists in server. Run id(s): {8986118}
[2018-04-11 22:16:16] Started run 594 on task 146227, dataset 'churn'.
[2018-04-11 22:16:17] Error in run 587: Run already exists in server. Run id(s): {8986115}
[2018-04-11 22:16:17] Started run 595 on task 146227, dataset 'churn'.
[2018-04-11 22:16:17] Error in run 588: Run already exists in server. Run id(s): {8986116}
[2018-04-11 22:16:17] Started run 596 on task 146227, dataset 'churn'.
[2018-04-11 22:16:18] Error in run 589: Run already exists in server. Run id(s): {8986124}
[2018-04-11 22:16:18] Started run 597 on task 146227, dataset 'churn'.
[2018-04-11 22:16:18] Error in run 590: Run already exists in server. Run id(s): {8986129}
[2018-04-11 22:16:18] Started run 598 on task 146227, dataset 'churn'.
[2018-04-11 22:16:19] Error in run 591: Run already exists in server. Run id(s): {8986130}
[2018-04-11 22:16:19] Started run 599 on task 146227, dataset 'churn'.
[2018-04-11 22:16:20] Error in run 592: Run already exists in server. Run id(s): {8986132}
[2018-04-11 22:16:20] Started run 600 on task 146227, dataset 'churn'.
[2018-04-11 22:16:20] Error in run 593: Run already exists in server. Run id(s): {8986150}
[2018-04-11 22:16:20] Started run 601 on task 146227, dataset 'churn'.
[2018-04-11 22:16:20] Error in run 594: Run already exists in server. Run id(s): {8986138}
[2018-04-11 22:16:20] Started run 602 on task 146227, dataset 'churn'.
[2018-04-11 22:16:22] Error in run 595: Run already exists in server. Run id(s): {8986143}
[2018-04-11 22:16:22] Started run 603 on task 146227, dataset 'churn'.
[2018-04-11 22:16:22] Error in run 596: Run already exists in server. Run id(s): {8986145}
[2018-04-11 22:16:22] Started run 604 on task 146227, dataset 'churn'.
[2018-04-11 22:16:22] Error in run 597: Run already exists in server. Run id(s): {8986162}
[2018-04-11 22:16:22] Started run 605 on task 146227, dataset 'churn'.
[2018-04-11 22:16:22] Error in run 598: Run already exists in server. Run id(s): {9015708, 8986158}
[2018-04-11 22:16:22] Started run 606 on task 146227, dataset 'churn'.
[2018-04-11 22:16:23] Error in run 599: Run already exists in server. Run id(s): {8986169}
[2018-04-11 22:16:23] Started run 607 on task 146227, dataset 'churn'.
[2018-04-11 22:16:24] Error in run 600: Run already exists in server. Run id(s): {8986164}
[2018-04-11 22:16:24] Started run 608 on task 146227, dataset 'churn'.
[2018-04-11 22:16:25] Error in run 601: Run already exists in server. Run id(s): {8986180}
[2018-04-11 22:16:25] Started run 609 on task 146227, dataset 'churn'.
[2018-04-11 22:16:25] Error in run 602: Run already exists in server. Run id(s): {8986176}
[2018-04-11 22:16:25] Started run 610 on task 146227, dataset 'churn'.
[2018-04-11 22:16:26] Error in run 603: Run already exists in server. Run id(s): {8986177}
[2018-04-11 22:16:26] Started run 611 on task 146227, dataset 'churn'.
[2018-04-11 22:16:26] Error in run 604: Run already exists in server. Run id(s): {8986190}
[2018-04-11 22:16:26] Started run 612 on task 146227, dataset 'churn'.
[2018-04-11 22:16:27] Error in run 605: Run already exists in server. Run id(s): {8986188}
[2018-04-11 22:16:27] Error in run 606: Run already exists in server. Run id(s): {8986189}
[2018-04-11 22:16:27] Started run 613 on task 146227, dataset 'churn'.
[2018-04-11 22:16:27] Started run 614 on task 146227, dataset 'churn'.
[2018-04-11 22:16:28] Error in run 607: Run already exists in server. Run id(s): {8986191}
[2018-04-11 22:16:28] Started run 615 on task 146227, dataset 'churn'.
[2018-04-11 22:16:29] Error in run 608: Run already exists in server. Run id(s): {8986197}
[2018-04-11 22:16:29] Started run 616 on task 146227, dataset 'churn'.
[2018-04-11 22:16:29] Error in run 609: Run already exists in server. Run id(s): {8986202}
[2018-04-11 22:16:29] Started run 617 on task 146227, dataset 'churn'.
[2018-04-11 22:16:30] Error in run 610: Run already exists in server. Run id(s): {8986205}
[2018-04-11 22:16:30] Started run 618 on task 146227, dataset 'churn'.
[2018-04-11 22:16:31] Error in run 611: Run already exists in server. Run id(s): {8986203}
[2018-04-11 22:16:31] Started run 619 on task 146227, dataset 'churn'.
[2018-04-11 22:16:31] Error in run 612: Run already exists in server. Run id(s): {8986210}
[2018-04-11 22:16:31] Started run 620 on task 146227, dataset 'churn'.
[2018-04-11 22:16:31] Error in run 614: Run already exists in server. Run id(s): {8986217}
[2018-04-11 22:16:31] Error in run 613: Run already exists in server. Run id(s): {8986216}
[2018-04-11 22:16:31] Started run 621 on task 146227, dataset 'churn'.
[2018-04-11 22:16:31] Started run 622 on task 146227, dataset 'churn'.
[2018-04-11 22:16:32] Error in run 615: Run already exists in server. Run id(s): {8986218}
[2018-04-11 22:16:32] Started run 623 on task 146227, dataset 'churn'.
[2018-04-11 22:16:33] Error in run 616: Run already exists in server. Run id(s): {8986231}
[2018-04-11 22:16:33] Started run 624 on task 146227, dataset 'churn'.
[2018-04-11 22:16:34] Error in run 617: Run already exists in server. Run id(s): {8986227}
[2018-04-11 22:16:34] Started run 625 on task 146227, dataset 'churn'.
[2018-04-11 22:16:34] Error in run 618: Run already exists in server. Run id(s): {8986225}
[2018-04-11 22:16:34] Started run 626 on task 146227, dataset 'churn'.
[2018-04-11 22:16:35] Error in run 619: Run already exists in server. Run id(s): {8986230}
[2018-04-11 22:16:35] Started run 627 on task 146227, dataset 'churn'.
[2018-04-11 22:16:36] Error in run 620: Run already exists in server. Run id(s): {8986246}
[2018-04-11 22:16:36] Started run 628 on task 146227, dataset 'churn'.
[2018-04-11 22:16:36] Error in run 621: Run already exists in server. Run id(s): {8986238}
[2018-04-11 22:16:36] Started run 629 on task 146227, dataset 'churn'.
[2018-04-11 22:16:36] Error in run 622: Run already exists in server. Run id(s): {8986244}
[2018-04-11 22:16:36] Started run 630 on task 146227, dataset 'churn'.
[2018-04-11 22:16:37] Error in run 623: Run already exists in server. Run id(s): {8986247}
[2018-04-11 22:16:37] Started run 631 on task 146227, dataset 'churn'.
[2018-04-11 22:16:38] Error in run 624: Run already exists in server. Run id(s): {8986252}
[2018-04-11 22:16:38] Started run 632 on task 146227, dataset 'churn'.
[2018-04-11 22:16:38] Error in run 625: Run already exists in server. Run id(s): {8986253}
[2018-04-11 22:16:38] Started run 633 on task 146227, dataset 'churn'.
[2018-04-11 22:16:39] Error in run 626: Run already exists in server. Run id(s): {8986267}
[2018-04-11 22:16:39] Started run 634 on task 146227, dataset 'churn'.
[2018-04-11 22:16:40] Error in run 627: Run already exists in server. Run id(s): {8986269}
[2018-04-11 22:16:40] Started run 635 on task 146227, dataset 'churn'.
[2018-04-11 22:16:40] Error in run 628: Run already exists in server. Run id(s): {8986274}
[2018-04-11 22:16:40] Started run 636 on task 146227, dataset 'churn'.
[2018-04-11 22:16:40] Error in run 630: Run already exists in server. Run id(s): {8986287}
[2018-04-11 22:16:40] Started run 637 on task 146227, dataset 'churn'.
[2018-04-11 22:16:41] Error in run 629: Run already exists in server. Run id(s): {8986275}
[2018-04-11 22:16:41] Started run 638 on task 146227, dataset 'churn'.
[2018-04-11 22:16:41] Error in run 631: Run already exists in server. Run id(s): {8986288}
[2018-04-11 22:16:41] Started run 639 on task 146227, dataset 'churn'.
[2018-04-11 22:16:42] Error in run 632: Run already exists in server. Run id(s): {8986294}
[2018-04-11 22:16:42] Started run 640 on task 146227, dataset 'churn'.
[2018-04-11 22:16:43] Error in run 633: Run already exists in server. Run id(s): {8986286}
[2018-04-11 22:16:43] Started run 641 on task 146227, dataset 'churn'.
[2018-04-11 22:16:43] Error in run 634: Run already exists in server. Run id(s): {8986302}
[2018-04-11 22:16:43] Started run 642 on task 146227, dataset 'churn'.
[2018-04-11 22:16:44] Error in run 635: Run already exists in server. Run id(s): {8986303}
[2018-04-11 22:16:44] Started run 643 on task 146227, dataset 'churn'.
[2018-04-11 22:16:45] Error in run 636: Run already exists in server. Run id(s): {8986304}
[2018-04-11 22:16:45] Started run 644 on task 146227, dataset 'churn'.
[2018-04-11 22:16:45] Error in run 637: Run already exists in server. Run id(s): {8986308}
[2018-04-11 22:16:45] Started run 645 on task 146227, dataset 'churn'.
[2018-04-11 22:16:45] Error in run 638: Run already exists in server. Run id(s): {8986320}
[2018-04-11 22:16:45] Started run 646 on task 146227, dataset 'churn'.
[2018-04-11 22:16:46] Error in run 639: Run already exists in server. Run id(s): {8986321}
[2018-04-11 22:16:46] Started run 647 on task 146227, dataset 'churn'.
[2018-04-11 22:16:47] Error in run 640: Run already exists in server. Run id(s): {8986327}
[2018-04-11 22:16:47] Started run 648 on task 146227, dataset 'churn'.
[2018-04-11 22:16:47] Error in run 641: Run already exists in server. Run id(s): {8986322}
[2018-04-11 22:16:47] Started run 649 on task 146227, dataset 'churn'.
[2018-04-11 22:16:48] Error in run 642: Run already exists in server. Run id(s): {8986328}
[2018-04-11 22:16:48] Started run 650 on task 146227, dataset 'churn'.
[2018-04-11 22:16:49] Error in run 643: Run already exists in server. Run id(s): {8986329}
[2018-04-11 22:16:49] Started run 651 on task 146227, dataset 'churn'.
[2018-04-11 22:16:49] Error in run 644: Run already exists in server. Run id(s): {8986338}
[2018-04-11 22:16:49] Started run 652 on task 146227, dataset 'churn'.
[2018-04-11 22:16:49] Error in run 645: Run already exists in server. Run id(s): {8986339}
[2018-04-11 22:16:49] Started run 653 on task 146227, dataset 'churn'.
[2018-04-11 22:16:50] Error in run 646: Run already exists in server. Run id(s): {8986345}
[2018-04-11 22:16:50] Started run 654 on task 146227, dataset 'churn'.
[2018-04-11 22:16:50] Error in run 647: Run already exists in server. Run id(s): {8986344}
[2018-04-11 22:16:50] Started run 655 on task 146227, dataset 'churn'.
[2018-04-11 22:16:51] Error in run 648: Run already exists in server. Run id(s): {8986346}
[2018-04-11 22:16:51] Started run 656 on task 146227, dataset 'churn'.
[2018-04-11 22:16:52] Error in run 649: Run already exists in server. Run id(s): {8986357}
[2018-04-11 22:16:52] Started run 657 on task 146227, dataset 'churn'.
[2018-04-11 22:16:52] Error in run 650: Run already exists in server. Run id(s): {8986355}
[2018-04-11 22:16:52] Started run 658 on task 146227, dataset 'churn'.
[2018-04-11 22:16:53] Error in run 651: Run already exists in server. Run id(s): {8986356}
[2018-04-11 22:16:53] Started run 659 on task 146227, dataset 'churn'.
[2018-04-11 22:16:54] Error in run 652: Run already exists in server. Run id(s): {8986358}
[2018-04-11 22:16:54] Started run 660 on task 146227, dataset 'churn'.
[2018-04-11 22:16:54] Error in run 653: Run already exists in server. Run id(s): {8986364}
[2018-04-11 22:16:54] Started run 661 on task 146227, dataset 'churn'.
[2018-04-11 22:16:54] Error in run 654: Run already exists in server. Run id(s): {8986369}
[2018-04-11 22:16:54] Started run 662 on task 146227, dataset 'churn'.
[2018-04-11 22:16:55] Error in run 655: Run already exists in server. Run id(s): {8986370}
[2018-04-11 22:16:55] Started run 663 on task 146227, dataset 'churn'.
[2018-04-11 22:16:56] Error in run 656: Run already exists in server. Run id(s): {8986376}
[2018-04-11 22:16:56] Started run 664 on task 146227, dataset 'churn'.
[2018-04-11 22:16:56] Error in run 657: Run already exists in server. Run id(s): {8986383}
[2018-04-11 22:16:56] Started run 665 on task 146227, dataset 'churn'.
[2018-04-11 22:16:57] Error in run 658: Run already exists in server. Run id(s): {8986377}
[2018-04-11 22:16:57] Started run 666 on task 146227, dataset 'churn'.
[2018-04-11 22:16:58] Error in run 659: Run already exists in server. Run id(s): {8986385}
[2018-04-11 22:16:58] Started run 667 on task 146227, dataset 'churn'.
[2018-04-11 22:16:58] Error in run 660: Run already exists in server. Run id(s): {8986392}
[2018-04-11 22:16:58] Started run 668 on task 146227, dataset 'churn'.
[2018-04-11 22:16:58] Error in run 661: Run already exists in server. Run id(s): {8986391}
[2018-04-11 22:16:58] Started run 669 on task 146227, dataset 'churn'.
[2018-04-11 22:16:59] Error in run 662: Run already exists in server. Run id(s): {8986399}
[2018-04-11 22:16:59] Started run 670 on task 146227, dataset 'churn'.
[2018-04-11 22:16:59] Error in run 663: Run already exists in server. Run id(s): {8986398}
[2018-04-11 22:16:59] Started run 671 on task 146227, dataset 'churn'.
[2018-04-11 22:17:00] Error in run 664: Run already exists in server. Run id(s): {8986404}
[2018-04-11 22:17:00] Started run 672 on task 146227, dataset 'churn'.
[2018-04-11 22:17:01] Error in run 665: Run already exists in server. Run id(s): {8986417}
[2018-04-11 22:17:01] Started run 673 on task 146227, dataset 'churn'.
[2018-04-11 22:17:01] Error in run 666: Run already exists in server. Run id(s): {8986416}
[2018-04-11 22:17:01] Started run 674 on task 146227, dataset 'churn'.
[2018-04-11 22:17:03] Error in run 667: Run already exists in server. Run id(s): {8986426}
[2018-04-11 22:17:03] Started run 675 on task 146227, dataset 'churn'.
[2018-04-11 22:17:03] Error in run 669: Run already exists in server. Run id(s): {8986427}
[2018-04-11 22:17:03] Started run 676 on task 146227, dataset 'churn'.
[2018-04-11 22:17:03] Error in run 668: Run already exists in server. Run id(s): {8986419}
[2018-04-11 22:17:03] Started run 677 on task 146227, dataset 'churn'.
[2018-04-11 22:17:03] Error in run 670: Run already exists in server. Run id(s): {8986428}
[2018-04-11 22:17:03] Started run 678 on task 146227, dataset 'churn'.
[2018-04-11 22:17:04] Error in run 671: Run already exists in server. Run id(s): {8986438}
[2018-04-11 22:17:04] Started run 679 on task 146227, dataset 'churn'.
[2018-04-11 22:17:05] Error in run 672: Run already exists in server. Run id(s): {8986442}
[2018-04-11 22:17:05] Started run 680 on task 146227, dataset 'churn'.
[2018-04-11 22:17:05] Error in run 673: Run already exists in server. Run id(s): {8986447}
[2018-04-11 22:17:05] Started run 681 on task 146227, dataset 'churn'.
[2018-04-11 22:17:06] Error in run 674: Run already exists in server. Run id(s): {8986440}
[2018-04-11 22:17:06] Started run 682 on task 146227, dataset 'churn'.
[2018-04-11 22:17:07] Error in run 675: Run already exists in server. Run id(s): {8986450}
[2018-04-11 22:17:07] Started run 683 on task 146227, dataset 'churn'.
[2018-04-11 22:17:08] Error in run 676: Run already exists in server. Run id(s): {8986460}
[2018-04-11 22:17:08] Started run 684 on task 146227, dataset 'churn'.
[2018-04-11 22:17:08] Error in run 677: Run already exists in server. Run id(s): {8986461}
[2018-04-11 22:17:08] Started run 685 on task 146227, dataset 'churn'.
[2018-04-11 22:17:08] Error in run 678: Run already exists in server. Run id(s): {8986463}
[2018-04-11 22:17:08] Started run 686 on task 146227, dataset 'churn'.
[2018-04-11 22:17:08] Error in run 679: Run already exists in server. Run id(s): {8986462}
[2018-04-11 22:17:08] Started run 687 on task 146227, dataset 'churn'.
[2018-04-11 22:17:10] Error in run 681: Run already exists in server. Run id(s): {8986479}
[2018-04-11 22:17:10] Started run 688 on task 146227, dataset 'churn'.
[2018-04-11 22:17:10] Error in run 680: Run already exists in server. Run id(s): {8986478}
[2018-04-11 22:17:10] Started run 689 on task 146227, dataset 'churn'.
[2018-04-11 22:17:10] Error in run 682: Run already exists in server. Run id(s): {8986487}
[2018-04-11 22:17:10] Started run 690 on task 146227, dataset 'churn'.
[2018-04-11 22:17:12] Error in run 683: Run already exists in server. Run id(s): {8986480}
[2018-04-11 22:17:12] Started run 691 on task 146227, dataset 'churn'.
[2018-04-11 22:17:12] Error in run 684: Run already exists in server. Run id(s): {8986488}
[2018-04-11 22:17:12] Started run 692 on task 146227, dataset 'churn'.
[2018-04-11 22:17:12] Error in run 685: Run already exists in server. Run id(s): {8986489}
[2018-04-11 22:17:12] Started run 693 on task 146227, dataset 'churn'.
[2018-04-11 22:17:12] Error in run 686: Run already exists in server. Run id(s): {8986494}
[2018-04-11 22:17:12] Started run 694 on task 146227, dataset 'churn'.
[2018-04-11 22:17:13] Error in run 687: Run already exists in server. Run id(s): {8986496}
[2018-04-11 22:17:13] Started run 695 on task 146227, dataset 'churn'.
[2018-04-11 22:17:14] Error in run 688: Run already exists in server. Run id(s): {8986501}
[2018-04-11 22:17:14] Started run 696 on task 146227, dataset 'churn'.
[2018-04-11 22:17:14] Error in run 689: Run already exists in server. Run id(s): {8986507}
[2018-04-11 22:17:14] Started run 697 on task 146227, dataset 'churn'.
[2018-04-11 22:17:15] Error in run 690: Run already exists in server. Run id(s): {8986506}
[2018-04-11 22:17:15] Started run 698 on task 146227, dataset 'churn'.
[2018-04-11 22:17:16] Error in run 691: Run already exists in server. Run id(s): {8986508}
[2018-04-11 22:17:16] Started run 699 on task 146227, dataset 'churn'.
[2018-04-11 22:17:16] Error in run 692: Run already exists in server. Run id(s): {8986513}
[2018-04-11 22:17:16] Started run 700 on task 146227, dataset 'churn'.
[2018-04-11 22:17:17] Error in run 693: Run already exists in server. Run id(s): {8986523}
[2018-04-11 22:17:17] Started run 701 on task 146227, dataset 'churn'.
[2018-04-11 22:17:17] Error in run 694: Run already exists in server. Run id(s): {8986529}
[2018-04-11 22:17:17] Error in run 695: Run already exists in server. Run id(s): {8986521}
[2018-04-11 22:17:17] Started run 702 on task 146227, dataset 'churn'.
[2018-04-11 22:17:17] Started run 703 on task 146227, dataset 'churn'.
[2018-04-11 22:17:19] Error in run 696: Run already exists in server. Run id(s): {8986522}
[2018-04-11 22:17:19] Started run 704 on task 146227, dataset 'churn'.
[2018-04-11 22:17:19] Error in run 697: Run already exists in server. Run id(s): {8986532}
[2018-04-11 22:17:19] Started run 705 on task 146227, dataset 'churn'.
[2018-04-11 22:17:20] Error in run 698: Run already exists in server. Run id(s): {8986545}
[2018-04-11 22:17:20] Started run 706 on task 146227, dataset 'churn'.
[2018-04-11 22:17:21] Error in run 699: Run already exists in server. Run id(s): {8986540}
[2018-04-11 22:17:21] Started run 707 on task 146227, dataset 'churn'.
[2018-04-11 22:17:21] Error in run 701: Run already exists in server. Run id(s): {8986546}
[2018-04-11 22:17:21] Error in run 700: Run already exists in server. Run id(s): {8986551}
[2018-04-11 22:17:21] Started run 708 on task 146227, dataset 'churn'.
[2018-04-11 22:17:21] Started run 709 on task 146227, dataset 'churn'.
[2018-04-11 22:17:22] Error in run 703: Run already exists in server. Run id(s): {8986557}
[2018-04-11 22:17:22] Started run 710 on task 146227, dataset 'churn'.
[2018-04-11 22:17:22] Error in run 702: Run already exists in server. Run id(s): {8986552}
[2018-04-11 22:17:22] Started run 711 on task 146227, dataset 'churn'.
[2018-04-11 22:17:24] Error in run 705: Run already exists in server. Run id(s): {8986568}
[2018-04-11 22:17:24] Started run 712 on task 146227, dataset 'churn'.
[2018-04-11 22:17:24] Error in run 704: Run already exists in server. Run id(s): {8986564}
[2018-04-11 22:17:24] Started run 713 on task 146227, dataset 'churn'.
[2018-04-11 22:17:24] Error in run 706: Run already exists in server. Run id(s): {8986558}
[2018-04-11 22:17:24] Started run 714 on task 146227, dataset 'churn'.
[2018-04-11 22:17:26] Error in run 707: Run already exists in server. Run id(s): {8986578}
[2018-04-11 22:17:26] Started run 715 on task 146227, dataset 'churn'.
[2018-04-11 22:17:26] Error in run 708: Run already exists in server. Run id(s): {8986572}
[2018-04-11 22:17:26] Error in run 709: Run already exists in server. Run id(s): {8986577}
[2018-04-11 22:17:26] Started run 716 on task 146227, dataset 'churn'.
[2018-04-11 22:17:26] Started run 717 on task 146227, dataset 'churn'.
[2018-04-11 22:17:26] Error in run 710: Run already exists in server. Run id(s): {8986579}
[2018-04-11 22:17:26] Started run 718 on task 146227, dataset 'churn'.
[2018-04-11 22:17:27] Error in run 711: Run already exists in server. Run id(s): {8986587}
[2018-04-11 22:17:27] Started run 719 on task 146227, dataset 'churn'.
[2018-04-11 22:17:28] Error in run 712: Run already exists in server. Run id(s): {8986589}
[2018-04-11 22:17:28] Started run 720 on task 146227, dataset 'churn'.
[2018-04-11 22:17:28] Error in run 713: Run already exists in server. Run id(s): {8986595}
[2018-04-11 22:17:28] Started run 721 on task 146227, dataset 'churn'.
[2018-04-11 22:17:29] Error in run 714: Run already exists in server. Run id(s): {8986602}
[2018-04-11 22:17:29] Started run 722 on task 146227, dataset 'churn'.
[2018-04-11 22:17:30] Error in run 715: Run already exists in server. Run id(s): {8986601}
[2018-04-11 22:17:30] Started run 723 on task 146227, dataset 'churn'.
[2018-04-11 22:17:30] Error in run 716: Run already exists in server. Run id(s): {8986612}
[2018-04-11 22:17:30] Started run 724 on task 146227, dataset 'churn'.
[2018-04-11 22:17:30] Error in run 717: Run already exists in server. Run id(s): {8986615}
[2018-04-11 22:17:30] Started run 725 on task 146227, dataset 'churn'.
[2018-04-11 22:17:31] Error in run 718: Run already exists in server. Run id(s): {8986613}
[2018-04-11 22:17:31] Started run 726 on task 146227, dataset 'churn'.
[2018-04-11 22:17:31] Error in run 719: Run already exists in server. Run id(s): {8986621}
[2018-04-11 22:17:31] Started run 727 on task 146227, dataset 'churn'.
[2018-04-11 22:17:33] Error in run 720: Run already exists in server. Run id(s): {8986627}
[2018-04-11 22:17:33] Started run 728 on task 146227, dataset 'churn'.
[2018-04-11 22:17:33] Error in run 721: Run already exists in server. Run id(s): {8986639}
[2018-04-11 22:17:33] Started run 729 on task 146227, dataset 'churn'.
[2018-04-11 22:17:33] Error in run 722: Run already exists in server. Run id(s): {8986628}
[2018-04-11 22:17:33] Started run 730 on task 146227, dataset 'churn'.
[2018-04-11 22:17:35] Error in run 723: Run already exists in server. Run id(s): {8986629}
[2018-04-11 22:17:35] Started run 731 on task 146227, dataset 'churn'.
[2018-04-11 22:17:35] Error in run 724: Run already exists in server. Run id(s): {8986641}
[2018-04-11 22:17:35] Started run 732 on task 146227, dataset 'churn'.
[2018-04-11 22:17:35] Error in run 725: Run already exists in server. Run id(s): {8986650}
[2018-04-11 22:17:35] Started run 733 on task 146227, dataset 'churn'.
[2018-04-11 22:17:35] Error in run 726: Run already exists in server. Run id(s): {8986646}
[2018-04-11 22:17:35] Started run 734 on task 146227, dataset 'churn'.
[2018-04-11 22:17:36] Error in run 727: Run already exists in server. Run id(s): {8986655}
[2018-04-11 22:17:36] Started run 735 on task 146227, dataset 'churn'.
[2018-04-11 22:17:37] Error in run 728: Run already exists in server. Run id(s): {8986661}
[2018-04-11 22:17:37] Started run 736 on task 146227, dataset 'churn'.
[2018-04-11 22:17:37] Error in run 729: Run already exists in server. Run id(s): {8986658}
[2018-04-11 22:17:37] Started run 737 on task 146227, dataset 'churn'.
[2018-04-11 22:17:38] Error in run 730: Run already exists in server. Run id(s): {8986667}
[2018-04-11 22:17:38] Started run 738 on task 146227, dataset 'churn'.
[2018-04-11 22:17:39] Error in run 731: Run already exists in server. Run id(s): {8986671}
[2018-04-11 22:17:39] Started run 739 on task 146227, dataset 'churn'.
[2018-04-11 22:17:39] Error in run 733: Run already exists in server. Run id(s): {8986669}
[2018-04-11 22:17:39] Started run 740 on task 146227, dataset 'churn'.
[2018-04-11 22:17:39] Error in run 732: Run already exists in server. Run id(s): {8986668}
[2018-04-11 22:17:39] Started run 741 on task 146227, dataset 'churn'.
[2018-04-11 22:17:40] Error in run 735: Run already exists in server. Run id(s): {8986682}
[2018-04-11 22:17:40] Started run 742 on task 146227, dataset 'churn'.
[2018-04-11 22:17:40] Error in run 734: Run already exists in server. Run id(s): {8986681}
[2018-04-11 22:17:40] Started run 743 on task 146227, dataset 'churn'.
[2018-04-11 22:17:42] Error in run 736: Run already exists in server. Run id(s): {8986683}
[2018-04-11 22:17:42] Started run 744 on task 146227, dataset 'churn'.
[2018-04-11 22:17:42] Error in run 737: Run already exists in server. Run id(s): {8986688}
[2018-04-11 22:17:42] Started run 745 on task 146227, dataset 'churn'.
[2018-04-11 22:17:42] Error in run 738: Run already exists in server. Run id(s): {8986690}
[2018-04-11 22:17:42] Started run 746 on task 146227, dataset 'churn'.
[2018-04-11 22:17:44] Error in run 739: Run already exists in server. Run id(s): {8986701}
[2018-04-11 22:17:44] Started run 747 on task 146227, dataset 'churn'.
[2018-04-11 22:17:44] Error in run 740: Run already exists in server. Run id(s): {8986707}
[2018-04-11 22:17:44] Started run 748 on task 146227, dataset 'churn'.
[2018-04-11 22:17:44] Error in run 741: Run already exists in server. Run id(s): {8986704}
[2018-04-11 22:17:44] Started run 749 on task 146227, dataset 'churn'.
[2018-04-11 22:17:45] Error in run 742: Run already exists in server. Run id(s): {8986713}
[2018-04-11 22:17:45] Started run 750 on task 146227, dataset 'churn'.
[2018-04-11 22:17:45] Error in run 743: Run already exists in server. Run id(s): {8986715}
[2018-04-11 22:17:45] Started run 751 on task 146227, dataset 'churn'.
[2018-04-11 22:17:46] Error in run 744: Run already exists in server. Run id(s): {8986722}
[2018-04-11 22:17:46] Started run 752 on task 146227, dataset 'churn'.
[2018-04-11 22:17:46] Error in run 745: Run already exists in server. Run id(s): {8986719}
[2018-04-11 22:17:46] Started run 753 on task 146227, dataset 'churn'.
[2018-04-11 22:17:47] Error in run 746: Run already exists in server. Run id(s): {8986721}
[2018-04-11 22:17:47] Started run 754 on task 146227, dataset 'churn'.
[2018-04-11 22:17:49] Error in run 747: Run already exists in server. Run id(s): {8986736}
[2018-04-11 22:17:49] Started run 755 on task 146227, dataset 'churn'.
[2018-04-11 22:17:49] Error in run 748: Run already exists in server. Run id(s): {8986726}
[2018-04-11 22:17:49] Started run 756 on task 146227, dataset 'churn'.
[2018-04-11 22:17:49] Error in run 749: Run already exists in server. Run id(s): {8986738}
[2018-04-11 22:17:49] Started run 757 on task 146227, dataset 'churn'.
[2018-04-11 22:17:49] Error in run 750: Run already exists in server. Run id(s): {8986739}
[2018-04-11 22:17:49] Started run 758 on task 146227, dataset 'churn'.
[2018-04-11 22:17:50] Error in run 751: Run already exists in server. Run id(s): {8986737}
[2018-04-11 22:17:50] Started run 759 on task 146227, dataset 'churn'.
[2018-04-11 22:17:51] Error in run 752: Run already exists in server. Run id(s): {8986748}
[2018-04-11 22:17:51] Started run 760 on task 146227, dataset 'churn'.
[2018-04-11 22:17:51] Error in run 753: Run already exists in server. Run id(s): {8986758}
[2018-04-11 22:17:51] Started run 761 on task 146227, dataset 'churn'.
[2018-04-11 22:17:52] Error in run 754: Run already exists in server. Run id(s): {8986752}
[2018-04-11 22:17:52] Started run 762 on task 146227, dataset 'churn'.
[2018-04-11 22:17:53] Error in run 756: Run already exists in server. Run id(s): {8986767}
[2018-04-11 22:17:53] Error in run 755: Run already exists in server. Run id(s): {8986759}
[2018-04-11 22:17:53] Started run 763 on task 146227, dataset 'churn'.
[2018-04-11 22:17:53] Started run 764 on task 146227, dataset 'churn'.
[2018-04-11 22:17:53] Error in run 757: Run already exists in server. Run id(s): {8986772}
[2018-04-11 22:17:53] Started run 765 on task 146227, dataset 'churn'.
[2018-04-11 22:17:54] Error in run 758: Run already exists in server. Run id(s): {8986778}
[2018-04-11 22:17:54] Started run 766 on task 146227, dataset 'churn'.
[2018-04-11 22:17:54] Error in run 759: Run already exists in server. Run id(s): {8986771}
[2018-04-11 22:17:54] Started run 767 on task 146227, dataset 'churn'.
[2018-04-11 22:17:56] Error in run 760: Run already exists in server. Run id(s): {8986779}
[2018-04-11 22:17:56] Started run 768 on task 146227, dataset 'churn'.
[2018-04-11 22:17:56] Error in run 761: Run already exists in server. Run id(s): {8986788}
[2018-04-11 22:17:56] Started run 769 on task 146227, dataset 'churn'.
[2018-04-11 22:17:56] Error in run 762: Run already exists in server. Run id(s): {8986781}
[2018-04-11 22:17:56] Started run 770 on task 146227, dataset 'churn'.
[2018-04-11 22:17:58] Error in run 764: Run already exists in server. Run id(s): {8986796}
[2018-04-11 22:17:58] Error in run 763: Run already exists in server. Run id(s): {8986792}
[2018-04-11 22:17:58] Started run 771 on task 146227, dataset 'churn'.
[2018-04-11 22:17:58] Started run 772 on task 146227, dataset 'churn'.
[2018-04-11 22:17:58] Error in run 765: Run already exists in server. Run id(s): {8986795}
[2018-04-11 22:17:58] Started run 773 on task 146227, dataset 'churn'.
[2018-04-11 22:17:58] Error in run 766: Run already exists in server. Run id(s): {8986804}
[2018-04-11 22:17:58] Started run 774 on task 146227, dataset 'churn'.
[2018-04-11 22:17:59] Error in run 767: Run already exists in server. Run id(s): {8986806}
[2018-04-11 22:17:59] Started run 775 on task 146227, dataset 'churn'.
[2018-04-11 22:18:00] Error in run 768: Run already exists in server. Run id(s): {8986810}
[2018-04-11 22:18:00] Started run 776 on task 146227, dataset 'churn'.
[2018-04-11 22:18:00] Error in run 769: Run already exists in server. Run id(s): {8986813}
[2018-04-11 22:18:00] Started run 777 on task 146227, dataset 'churn'.
[2018-04-11 22:18:01] Error in run 770: Run already exists in server. Run id(s): {8986823}
[2018-04-11 22:18:01] Started run 778 on task 146227, dataset 'churn'.
[2018-04-11 22:18:02] Error in run 771: Run already exists in server. Run id(s): {8986826}
[2018-04-11 22:18:02] Started run 779 on task 146227, dataset 'churn'.
[2018-04-11 22:18:02] Error in run 772: Run already exists in server. Run id(s): {8986828}
[2018-04-11 22:18:02] Started run 780 on task 146227, dataset 'churn'.
[2018-04-11 22:18:03] Error in run 773: Run already exists in server. Run id(s): {8986836}
[2018-04-11 22:18:03] Started run 781 on task 146227, dataset 'churn'.
[2018-04-11 22:18:03] Error in run 774: Run already exists in server. Run id(s): {8986835}
[2018-04-11 22:18:03] Started run 782 on task 146227, dataset 'churn'.
[2018-04-11 22:18:03] Error in run 775: Run already exists in server. Run id(s): {8986838}
[2018-04-11 22:18:03] Started run 783 on task 146227, dataset 'churn'.
[2018-04-11 22:18:05] Error in run 776: Run already exists in server. Run id(s): {8986839}
[2018-04-11 22:18:05] Started run 784 on task 146227, dataset 'churn'.
[2018-04-11 22:18:05] Error in run 777: Run already exists in server. Run id(s): {8986850}
[2018-04-11 22:18:05] Started run 785 on task 146227, dataset 'churn'.
[2018-04-11 22:18:06] Error in run 778: Run already exists in server. Run id(s): {8986844}
[2018-04-11 22:18:06] Started run 786 on task 146227, dataset 'churn'.
[2018-04-11 22:18:07] Error in run 779: Run already exists in server. Run id(s): {8986854}
[2018-04-11 22:18:07] Started run 787 on task 146227, dataset 'churn'.
[2018-04-11 22:18:07] Error in run 780: Run already exists in server. Run id(s): {8986848}
[2018-04-11 22:18:07] Started run 788 on task 146227, dataset 'churn'.
[2018-04-11 22:18:07] Error in run 781: Run already exists in server. Run id(s): {8986864}
[2018-04-11 22:18:07] Started run 789 on task 146227, dataset 'churn'.
[2018-04-11 22:18:07] Error in run 782: Run already exists in server. Run id(s): {8986859}
[2018-04-11 22:18:07] Started run 790 on task 146227, dataset 'churn'.
[2018-04-11 22:18:08] Error in run 783: Run already exists in server. Run id(s): {8986863}
[2018-04-11 22:18:08] Started run 791 on task 146227, dataset 'churn'.
[2018-04-11 22:18:09] Error in run 784: Run already exists in server. Run id(s): {8986872}
[2018-04-11 22:18:09] Started run 792 on task 146227, dataset 'churn'.
[2018-04-11 22:18:09] Error in run 785: Run already exists in server. Run id(s): {8986873}
[2018-04-11 22:18:09] Started run 793 on task 146227, dataset 'churn'.
[2018-04-11 22:18:10] Error in run 786: Run already exists in server. Run id(s): {8986879}
[2018-04-11 22:18:10] Started run 794 on task 146227, dataset 'churn'.
[2018-04-11 22:18:11] Error in run 787: Run already exists in server. Run id(s): {8986884}
[2018-04-11 22:18:11] Started run 795 on task 146227, dataset 'churn'.
[2018-04-11 22:18:11] Error in run 788: Run already exists in server. Run id(s): {8986885}
[2018-04-11 22:18:11] Started run 796 on task 146227, dataset 'churn'.
[2018-04-11 22:18:12] Error in run 789: Run already exists in server. Run id(s): {8986886}
[2018-04-11 22:18:12] Started run 797 on task 146227, dataset 'churn'.
[2018-04-11 22:18:12] Error in run 790: Run already exists in server. Run id(s): {8986893}
[2018-04-11 22:18:12] Started run 798 on task 146227, dataset 'churn'.
[2018-04-11 22:18:12] Error in run 791: Run already exists in server. Run id(s): {8986900}
[2018-04-11 22:18:12] Started run 799 on task 146227, dataset 'churn'.
[2018-04-11 22:18:14] Error in run 792: Run already exists in server. Run id(s): {8986892}
[2018-04-11 22:18:14] Started run 800 on task 146227, dataset 'churn'.
[2018-04-11 22:18:14] Error in run 793: Run already exists in server. Run id(s): {8986899}
[2018-04-11 22:18:14] Started run 801 on task 146227, dataset 'churn'.
[2018-04-11 22:18:15] Error in run 794: Run already exists in server. Run id(s): {8986906}
[2018-04-11 22:18:15] Started run 802 on task 146227, dataset 'churn'.
[2018-04-11 22:18:16] Error in run 795: Run already exists in server. Run id(s): {8986907}
[2018-04-11 22:18:16] Started run 803 on task 146227, dataset 'churn'.
[2018-04-11 22:18:16] Error in run 796: Run already exists in server. Run id(s): {8986909}
[2018-04-11 22:18:16] Started run 804 on task 146227, dataset 'churn'.
[2018-04-11 22:18:16] Error in run 797: Run already exists in server. Run id(s): {8986916}
[2018-04-11 22:18:16] Started run 805 on task 146227, dataset 'churn'.
[2018-04-11 22:18:17] Error in run 798: Run already exists in server. Run id(s): {8986923}
[2018-04-11 22:18:17] Started run 806 on task 146227, dataset 'churn'.
[2018-04-11 22:18:17] Error in run 799: Run already exists in server. Run id(s): {8986922}
[2018-04-11 22:18:17] Started run 807 on task 146227, dataset 'churn'.
[2018-04-11 22:18:18] Error in run 800: Run already exists in server. Run id(s): {8986929}
[2018-04-11 22:18:18] Started run 808 on task 146227, dataset 'churn'.
[2018-04-11 22:18:18] Error in run 801: Run already exists in server. Run id(s): {8986928}
[2018-04-11 22:18:18] Started run 809 on task 146227, dataset 'churn'.
[2018-04-11 22:18:19] Error in run 802: Run already exists in server. Run id(s): {8986935}
[2018-04-11 22:18:19] Started run 810 on task 146227, dataset 'churn'.
[2018-04-11 22:18:20] Error in run 803: Run already exists in server. Run id(s): {8986930}
[2018-04-11 22:18:20] Started run 811 on task 146227, dataset 'churn'.
[2018-04-11 22:18:21] Error in run 804: Run already exists in server. Run id(s): {8986948}
[2018-04-11 22:18:21] Error in run 805: Run already exists in server. Run id(s): {8986942}
[2018-04-11 22:18:21] Started run 812 on task 146227, dataset 'churn'.
[2018-04-11 22:18:21] Started run 813 on task 146227, dataset 'churn'.
[2018-04-11 22:18:21] Error in run 806: Run already exists in server. Run id(s): {8986949}
[2018-04-11 22:18:21] Started run 814 on task 146227, dataset 'churn'.
[2018-04-11 22:18:21] Error in run 807: Run already exists in server. Run id(s): {8986950}
[2018-04-11 22:18:21] Started run 815 on task 146227, dataset 'churn'.
[2018-04-11 22:18:23] Error in run 808: Run already exists in server. Run id(s): {8986956}
[2018-04-11 22:18:23] Started run 816 on task 146227, dataset 'churn'.
[2018-04-11 22:18:23] Error in run 809: Run already exists in server. Run id(s): {8986957}
[2018-04-11 22:18:23] Started run 817 on task 146227, dataset 'churn'.
[2018-04-11 22:18:24] Error in run 810: Run already exists in server. Run id(s): {8986970}
[2018-04-11 22:18:24] Started run 818 on task 146227, dataset 'churn'.
[2018-04-11 22:18:25] Error in run 811: Run already exists in server. Run id(s): {8986962}
[2018-04-11 22:18:25] Started run 819 on task 146227, dataset 'churn'.
[2018-04-11 22:18:26] Error in run 814: Run already exists in server. Run id(s): {8986979}
[2018-04-11 22:18:26] Error in run 812: Run already exists in server. Run id(s): {8986968}
[2018-04-11 22:18:26] Started run 820 on task 146227, dataset 'churn'.
[2018-04-11 22:18:26] Error in run 813: Run already exists in server. Run id(s): {8986975}
[2018-04-11 22:18:26] Started run 822 on task 146227, dataset 'churn'.
[2018-04-11 22:18:26] Started run 821 on task 146227, dataset 'churn'.
[2018-04-11 22:18:26] Error in run 815: Run already exists in server. Run id(s): {8986976}
[2018-04-11 22:18:26] Started run 823 on task 146227, dataset 'churn'.
[2018-04-11 22:18:27] Error in run 816: Run already exists in server. Run id(s): {8986978}
[2018-04-11 22:18:27] Started run 824 on task 146227, dataset 'churn'.
[2018-04-11 22:18:28] Error in run 817: Run already exists in server. Run id(s): {8986989}
[2018-04-11 22:18:28] Started run 825 on task 146227, dataset 'churn'.
[2018-04-11 22:18:28] Error in run 818: Run already exists in server. Run id(s): {8986990}
[2018-04-11 22:18:28] Started run 826 on task 146227, dataset 'churn'.
[2018-04-11 22:18:30] Error in run 819: Run already exists in server. Run id(s): {8986991}
[2018-04-11 22:18:30] Started run 827 on task 146227, dataset 'churn'.
[2018-04-11 22:18:30] Error in run 820: Run already exists in server. Run id(s): {8986999}
[2018-04-11 22:18:30] Started run 828 on task 146227, dataset 'churn'.
[2018-04-11 22:18:30] Error in run 822: Run already exists in server. Run id(s): {8986998}
[2018-04-11 22:18:30] Started run 829 on task 146227, dataset 'churn'.
[2018-04-11 22:18:30] Error in run 821: Run already exists in server. Run id(s): {8987009}
[2018-04-11 22:18:30] Started run 830 on task 146227, dataset 'churn'.
[2018-04-11 22:18:30] Error in run 823: Run already exists in server. Run id(s): {9016641, 8987004}
[2018-04-11 22:18:30] Started run 831 on task 146227, dataset 'churn'.
[2018-04-11 22:18:32] Error in run 824: Run already exists in server. Run id(s): {8987020}
[2018-04-11 22:18:32] Started run 832 on task 146227, dataset 'churn'.
[2018-04-11 22:18:33] Error in run 825: Run already exists in server. Run id(s): {8987010}
[2018-04-11 22:18:33] Started run 833 on task 146227, dataset 'churn'.
[2018-04-11 22:18:33] Error in run 826: Run already exists in server. Run id(s): {8987024}
[2018-04-11 22:18:33] Started run 834 on task 146227, dataset 'churn'.
[2018-04-11 22:18:34] Error in run 827: Run already exists in server. Run id(s): {8987019}
[2018-04-11 22:18:34] Started run 835 on task 146227, dataset 'churn'.
[2018-04-11 22:18:35] Error in run 828: Run already exists in server. Run id(s): {8987025}
[2018-04-11 22:18:35] Started run 836 on task 146227, dataset 'churn'.
[2018-04-11 22:18:35] Error in run 829: Run already exists in server. Run id(s): {8987036}
[2018-04-11 22:18:35] Started run 837 on task 146227, dataset 'churn'.
[2018-04-11 22:18:35] Error in run 830: Run already exists in server. Run id(s): {8987042}
[2018-04-11 22:18:35] Started run 838 on task 146227, dataset 'churn'.
[2018-04-11 22:18:35] Error in run 831: Run already exists in server. Run id(s): {8987046}
[2018-04-11 22:18:35] Started run 839 on task 146227, dataset 'churn'.
[2018-04-11 22:18:36] Error in run 832: Run already exists in server. Run id(s): {8987041}
[2018-04-11 22:18:36] Started run 840 on task 146227, dataset 'churn'.
[2018-04-11 22:18:37] Error in run 833: Run already exists in server. Run id(s): {8987053}
[2018-04-11 22:18:37] Started run 841 on task 146227, dataset 'churn'.
[2018-04-11 22:18:37] Error in run 834: Run already exists in server. Run id(s): {8987058}
[2018-04-11 22:18:37] Started run 842 on task 146227, dataset 'churn'.
[2018-04-11 22:18:39] Error in run 835: Run already exists in server. Run id(s): {8987063}
[2018-04-11 22:18:39] Started run 843 on task 146227, dataset 'churn'.
[2018-04-11 22:18:39] Error in run 837: Run already exists in server. Run id(s): {8987065}
[2018-04-11 22:18:39] Error in run 836: Run already exists in server. Run id(s): {8987057}
[2018-04-11 22:18:39] Started run 844 on task 146227, dataset 'churn'.
[2018-04-11 22:18:39] Started run 845 on task 146227, dataset 'churn'.
[2018-04-11 22:18:39] Error in run 838: Run already exists in server. Run id(s): {8987069}
[2018-04-11 22:18:39] Started run 846 on task 146227, dataset 'churn'.
[2018-04-11 22:18:40] Error in run 839: Run already exists in server. Run id(s): {8987071}
[2018-04-11 22:18:40] Started run 847 on task 146227, dataset 'churn'.
[2018-04-11 22:18:41] Error in run 840: Run already exists in server. Run id(s): {8987075}
[2018-04-11 22:18:41] Started run 848 on task 146227, dataset 'churn'.
[2018-04-11 22:18:42] Error in run 841: Run already exists in server. Run id(s): {8987084}
[2018-04-11 22:18:42] Started run 849 on task 146227, dataset 'churn'.
[2018-04-11 22:18:42] Error in run 842: Run already exists in server. Run id(s): {8987081}
[2018-04-11 22:18:42] Started run 850 on task 146227, dataset 'churn'.
[2018-04-11 22:18:43] Error in run 843: Run already exists in server. Run id(s): {8987091}
[2018-04-11 22:18:43] Started run 851 on task 146227, dataset 'churn'.
[2018-04-11 22:18:44] Error in run 844: Run already exists in server. Run id(s): {8987089}
[2018-04-11 22:18:44] Started run 852 on task 146227, dataset 'churn'.
[2018-04-11 22:18:44] Error in run 845: Run already exists in server. Run id(s): {8987099}
[2018-04-11 22:18:44] Started run 853 on task 146227, dataset 'churn'.
[2018-04-11 22:18:44] Error in run 846: Run already exists in server. Run id(s): {8987100}
[2018-04-11 22:18:44] Started run 854 on task 146227, dataset 'churn'.
[2018-04-11 22:18:44] Error in run 847: Run already exists in server. Run id(s): {8987105}
[2018-04-11 22:18:44] Started run 855 on task 146227, dataset 'churn'.
[2018-04-11 22:18:45] Error in run 848: Run already exists in server. Run id(s): {8987110}
[2018-04-11 22:18:45] Started run 856 on task 146227, dataset 'churn'.
[2018-04-11 22:18:46] Error in run 849: Run already exists in server. Run id(s): {8987115}
[2018-04-11 22:18:46] Started run 857 on task 146227, dataset 'churn'.
[2018-04-11 22:18:46] Error in run 850: Run already exists in server. Run id(s): {8987118}
[2018-04-11 22:18:46] Started run 858 on task 146227, dataset 'churn'.
[2018-04-11 22:18:48] Error in run 851: Run already exists in server. Run id(s): {8987117}
[2018-04-11 22:18:48] Started run 859 on task 146227, dataset 'churn'.
[2018-04-11 22:18:48] Error in run 852: Run already exists in server. Run id(s): {8987130}
[2018-04-11 22:18:48] Started run 860 on task 146227, dataset 'churn'.
[2018-04-11 22:18:49] Error in run 853: Run already exists in server. Run id(s): {8987127}
[2018-04-11 22:18:49] Error in run 854: Run already exists in server. Run id(s): {8987131}
[2018-04-11 22:18:49] Started run 861 on task 146227, dataset 'churn'.
[2018-04-11 22:18:49] Started run 862 on task 146227, dataset 'churn'.
[2018-04-11 22:18:49] Error in run 855: Run already exists in server. Run id(s): {8987132}
[2018-04-11 22:18:49] Started run 863 on task 146227, dataset 'churn'.
[2018-04-11 22:18:50] Error in run 856: Run already exists in server. Run id(s): {8987139}
[2018-04-11 22:18:50] Started run 864 on task 146227, dataset 'churn'.
[2018-04-11 22:18:51] Error in run 857: Run already exists in server. Run id(s): {8987144}
[2018-04-11 22:18:51] Started run 865 on task 146227, dataset 'churn'.
[2018-04-11 22:18:51] Error in run 858: Run already exists in server. Run id(s): {8987141}
[2018-04-11 22:18:51] Started run 866 on task 146227, dataset 'churn'.
[2018-04-11 22:18:52] Error in run 859: Run already exists in server. Run id(s): {8987145}
[2018-04-11 22:18:52] Started run 867 on task 146227, dataset 'churn'.
[2018-04-11 22:18:53] Error in run 860: Run already exists in server. Run id(s): {8987159}
[2018-04-11 22:18:53] Started run 868 on task 146227, dataset 'churn'.
[2018-04-11 22:18:53] Error in run 861: Run already exists in server. Run id(s): {8987155}
[2018-04-11 22:18:53] Error in run 862: Run already exists in server. Run id(s): {8987158}
[2018-04-11 22:18:53] Started run 869 on task 146227, dataset 'churn'.
[2018-04-11 22:18:53] Started run 870 on task 146227, dataset 'churn'.
[2018-04-11 22:18:53] Error in run 863: Run already exists in server. Run id(s): {8987163}
[2018-04-11 22:18:53] Started run 871 on task 146227, dataset 'churn'.
[2018-04-11 22:18:55] Error in run 864: Run already exists in server. Run id(s): {8987165}
[2018-04-11 22:18:55] Started run 872 on task 146227, dataset 'churn'.
[2018-04-11 22:18:55] Error in run 865: Run already exists in server. Run id(s): {8987175}
[2018-04-11 22:18:55] Started run 873 on task 146227, dataset 'churn'.
[2018-04-11 22:18:56] Error in run 866: Run already exists in server. Run id(s): {8987172}
[2018-04-11 22:18:56] Started run 874 on task 146227, dataset 'churn'.
[2018-04-11 22:18:57] Error in run 867: Run already exists in server. Run id(s): {8987180}
[2018-04-11 22:18:57] Started run 875 on task 146227, dataset 'churn'.
[2018-04-11 22:18:57] Error in run 868: Run already exists in server. Run id(s): {8987186}
[2018-04-11 22:18:57] Started run 876 on task 146227, dataset 'churn'.
[2018-04-11 22:18:58] Error in run 869: Run already exists in server. Run id(s): {8987184}
[2018-04-11 22:18:58] Started run 877 on task 146227, dataset 'churn'.
[2018-04-11 22:18:58] Error in run 870: Run already exists in server. Run id(s): {8987199}
[2018-04-11 22:18:58] Started run 878 on task 146227, dataset 'churn'.
[2018-04-11 22:18:58] Error in run 871: Run already exists in server. Run id(s): {8987194}
[2018-04-11 22:18:58] Started run 879 on task 146227, dataset 'churn'.
[2018-04-11 22:18:59] Error in run 872: Run already exists in server. Run id(s): {8987196}
[2018-04-11 22:18:59] Started run 880 on task 146227, dataset 'churn'.
[2018-04-11 22:19:00] Error in run 873: Run already exists in server. Run id(s): {8987205}
[2018-04-11 22:19:00] Started run 881 on task 146227, dataset 'churn'.
[2018-04-11 22:19:00] Error in run 874: Run already exists in server. Run id(s): {8987215}
[2018-04-11 22:19:00] Started run 882 on task 146227, dataset 'churn'.
[2018-04-11 22:19:01] Error in run 875: Run already exists in server. Run id(s): {8987209}
[2018-04-11 22:19:01] Started run 883 on task 146227, dataset 'churn'.
[2018-04-11 22:19:02] Error in run 876: Run already exists in server. Run id(s): {8987214}
[2018-04-11 22:19:02] Started run 884 on task 146227, dataset 'churn'.
[2018-04-11 22:19:02] Error in run 878: Run already exists in server. Run id(s): {8987220}
[2018-04-11 22:19:02] Started run 885 on task 146227, dataset 'churn'.
[2018-04-11 22:19:02] Error in run 877: Run already exists in server. Run id(s): {8987222}
[2018-04-11 22:19:02] Started run 886 on task 146227, dataset 'churn'.
[2018-04-11 22:19:02] Error in run 879: Run already exists in server. Run id(s): {8987233}
[2018-04-11 22:19:02] Started run 887 on task 146227, dataset 'churn'.
[2018-04-11 22:19:04] Error in run 880: Run already exists in server. Run id(s): {8987228}
[2018-04-11 22:19:04] Started run 888 on task 146227, dataset 'churn'.
[2018-04-11 22:19:04] Error in run 881: Run already exists in server. Run id(s): {8987232}
[2018-04-11 22:19:04] Started run 889 on task 146227, dataset 'churn'.
[2018-04-11 22:19:05] Error in run 882: Run already exists in server. Run id(s): {8987249}
[2018-04-11 22:19:05] Started run 890 on task 146227, dataset 'churn'.
[2018-04-11 22:19:06] Error in run 883: Run already exists in server. Run id(s): {8987248}
[2018-04-11 22:19:06] Started run 891 on task 146227, dataset 'churn'.
[2018-04-11 22:19:06] Error in run 884: Run already exists in server. Run id(s): {8987250}
[2018-04-11 22:19:06] Started run 892 on task 146227, dataset 'churn'.
[2018-04-11 22:19:07] Error in run 885: Run already exists in server. Run id(s): {8987253}
[2018-04-11 22:19:07] Started run 893 on task 146227, dataset 'churn'.
[2018-04-11 22:19:07] Error in run 886: Run already exists in server. Run id(s): {8987275}
[2018-04-11 22:19:07] Started run 894 on task 146227, dataset 'churn'.
[2018-04-11 22:19:07] Error in run 887: Run already exists in server. Run id(s): {8987269}
[2018-04-11 22:19:07] Started run 895 on task 146227, dataset 'churn'.
[2018-04-11 22:19:08] Error in run 888: Run already exists in server. Run id(s): {8987264}
[2018-04-11 22:19:08] Started run 896 on task 146227, dataset 'churn'.
[2018-04-11 22:19:09] Error in run 889: Run already exists in server. Run id(s): {8987267}
[2018-04-11 22:19:09] Started run 897 on task 146227, dataset 'churn'.
[2018-04-11 22:19:09] Error in run 890: Run already exists in server. Run id(s): {8987284}
[2018-04-11 22:19:09] Started run 898 on task 146227, dataset 'churn'.
[2018-04-11 22:19:10] Error in run 891: Run already exists in server. Run id(s): {8987288}
[2018-04-11 22:19:10] Started run 899 on task 146227, dataset 'churn'.
[2018-04-11 22:19:11] Error in run 892: Run already exists in server. Run id(s): {8987286}
[2018-04-11 22:19:11] Started run 900 on task 146227, dataset 'churn'.
[2018-04-11 22:19:11] Error in run 893: Run already exists in server. Run id(s): {8987285}
[2018-04-11 22:19:11] Started run 901 on task 146227, dataset 'churn'.
[2018-04-11 22:19:11] Error in run 894: Run already exists in server. Run id(s): {8987295}
[2018-04-11 22:19:11] Started run 902 on task 146227, dataset 'churn'.
[2018-04-11 22:19:12] Error in run 895: Run already exists in server. Run id(s): {8987298}
[2018-04-11 22:19:12] Started run 903 on task 146227, dataset 'churn'.
[2018-04-11 22:19:13] Error in run 896: Run already exists in server. Run id(s): {8987300}
[2018-04-11 22:19:13] Started run 904 on task 146227, dataset 'churn'.
[2018-04-11 22:19:13] Error in run 897: Run already exists in server. Run id(s): {8987297}
[2018-04-11 22:19:13] Started run 905 on task 146227, dataset 'churn'.
[2018-04-11 22:19:13] Error in run 898: Run already exists in server. Run id(s): {8987307}
[2018-04-11 22:19:13] Started run 906 on task 146227, dataset 'churn'.
[2018-04-11 22:19:15] Error in run 899: Run already exists in server. Run id(s): {8987316}
[2018-04-11 22:19:15] Started run 907 on task 146227, dataset 'churn'.
[2018-04-11 22:19:16] Error in run 900: Run already exists in server. Run id(s): {8987323}
[2018-04-11 22:19:16] Started run 908 on task 146227, dataset 'churn'.
[2018-04-11 22:19:16] Error in run 901: Run already exists in server. Run id(s): {8987317}
[2018-04-11 22:19:16] Error in run 902: Run already exists in server. Run id(s): {8987324}
[2018-04-11 22:19:16] Started run 909 on task 146227, dataset 'churn'.
[2018-04-11 22:19:16] Started run 910 on task 146227, dataset 'churn'.
[2018-04-11 22:19:16] Error in run 903: Run already exists in server. Run id(s): {8987340}
[2018-04-11 22:19:16] Started run 911 on task 146227, dataset 'churn'.
[2018-04-11 22:19:17] Error in run 904: Run already exists in server. Run id(s): {8987329}
[2018-04-11 22:19:17] Started run 912 on task 146227, dataset 'churn'.
[2018-04-11 22:19:18] Error in run 905: Run already exists in server. Run id(s): {8987337}
[2018-04-11 22:19:18] Started run 913 on task 146227, dataset 'churn'.
[2018-04-11 22:19:18] Error in run 906: Run already exists in server. Run id(s): {8987346}
[2018-04-11 22:19:18] Started run 914 on task 146227, dataset 'churn'.
[2018-04-11 22:19:20] Error in run 907: Run already exists in server. Run id(s): {8987341}
[2018-04-11 22:19:20] Started run 915 on task 146227, dataset 'churn'.
[2018-04-11 22:19:20] Error in run 908: Run already exists in server. Run id(s): {8987348}
[2018-04-11 22:19:20] Started run 916 on task 146227, dataset 'churn'.
[2018-04-11 22:19:20] Error in run 909: Run already exists in server. Run id(s): {8987363}
[2018-04-11 22:19:20] Error in run 910: Run already exists in server. Run id(s): {8987367}
[2018-04-11 22:19:20] Started run 917 on task 146227, dataset 'churn'.
[2018-04-11 22:19:20] Started run 918 on task 146227, dataset 'churn'.
[2018-04-11 22:19:21] Error in run 911: Run already exists in server. Run id(s): {8987365}
[2018-04-11 22:19:21] Started run 919 on task 146227, dataset 'churn'.
[2018-04-11 22:19:22] Error in run 912: Run already exists in server. Run id(s): {8987373}
[2018-04-11 22:19:22] Started run 920 on task 146227, dataset 'churn'.
[2018-04-11 22:19:22] Error in run 913: Run already exists in server. Run id(s): {8987381}
[2018-04-11 22:19:22] Started run 921 on task 146227, dataset 'churn'.
[2018-04-11 22:19:23] Error in run 914: Run already exists in server. Run id(s): {8987375}
[2018-04-11 22:19:23] Started run 922 on task 146227, dataset 'churn'.
[2018-04-11 22:19:24] Error in run 915: Run already exists in server. Run id(s): {8987380}
[2018-04-11 22:19:24] Started run 923 on task 146227, dataset 'churn'.
[2018-04-11 22:19:25] Error in run 916: Run already exists in server. Run id(s): {8987393}
[2018-04-11 22:19:25] Started run 924 on task 146227, dataset 'churn'.
[2018-04-11 22:19:25] Error in run 917: Run already exists in server. Run id(s): {8987387}
[2018-04-11 22:19:25] Started run 925 on task 146227, dataset 'churn'.
[2018-04-11 22:19:25] Error in run 918: Run already exists in server. Run id(s): {8987395}
[2018-04-11 22:19:25] Started run 926 on task 146227, dataset 'churn'.
[2018-04-11 22:19:25] Error in run 919: Run already exists in server. Run id(s): {8987392}
[2018-04-11 22:19:25] Started run 927 on task 146227, dataset 'churn'.
[2018-04-11 22:19:27] Error in run 920: Run already exists in server. Run id(s): {8987410}
[2018-04-11 22:19:27] Started run 928 on task 146227, dataset 'churn'.
[2018-04-11 22:19:27] Error in run 921: Run already exists in server. Run id(s): {8987405}
[2018-04-11 22:19:27] Started run 929 on task 146227, dataset 'churn'.
[2018-04-11 22:19:27] Error in run 922: Run already exists in server. Run id(s): {8987415}
[2018-04-11 22:19:27] Started run 930 on task 146227, dataset 'churn'.
[2018-04-11 22:19:29] Error in run 923: Run already exists in server. Run id(s): {8987420}
[2018-04-11 22:19:29] Started run 931 on task 146227, dataset 'churn'.
[2018-04-11 22:19:29] Error in run 924: Run already exists in server. Run id(s): {8987422}
[2018-04-11 22:19:29] Started run 932 on task 146227, dataset 'churn'.
[2018-04-11 22:19:29] Error in run 926: Run already exists in server. Run id(s): {8987430}
[2018-04-11 22:19:29] Error in run 925: Run already exists in server. Run id(s): {8987425}
[2018-04-11 22:19:29] Started run 933 on task 146227, dataset 'churn'.
[2018-04-11 22:19:29] Started run 934 on task 146227, dataset 'churn'.
[2018-04-11 22:19:30] Error in run 927: Run already exists in server. Run id(s): {8987440}
[2018-04-11 22:19:30] Started run 935 on task 146227, dataset 'churn'.
[2018-04-11 22:19:31] Error in run 928: Run already exists in server. Run id(s): {9016875, 8987435}
[2018-04-11 22:19:31] Started run 936 on task 146227, dataset 'churn'.
[2018-04-11 22:19:31] Error in run 929: Run already exists in server. Run id(s): {8987436}
[2018-04-11 22:19:31] Started run 937 on task 146227, dataset 'churn'.
[2018-04-11 22:19:32] Error in run 930: Run already exists in server. Run id(s): {8987441}
[2018-04-11 22:19:32] Started run 938 on task 146227, dataset 'churn'.
[2018-04-11 22:19:33] Error in run 931: Run already exists in server. Run id(s): {8987454}
[2018-04-11 22:19:33] Started run 939 on task 146227, dataset 'churn'.
[2018-04-11 22:19:34] Error in run 932: Run already exists in server. Run id(s): {8987451}
[2018-04-11 22:19:34] Started run 940 on task 146227, dataset 'churn'.
[2018-04-11 22:19:34] Error in run 934: Run already exists in server. Run id(s): {8987459}
[2018-04-11 22:19:34] Started run 941 on task 146227, dataset 'churn'.
[2018-04-11 22:19:34] Error in run 933: Run already exists in server. Run id(s): {8987452}
[2018-04-11 22:19:34] Started run 942 on task 146227, dataset 'churn'.
[2018-04-11 22:19:34] Error in run 935: Run already exists in server. Run id(s): {8987463}
[2018-04-11 22:19:34] Started run 943 on task 146227, dataset 'churn'.
[2018-04-11 22:19:36] Error in run 936: Run already exists in server. Run id(s): {8987470}
[2018-04-11 22:19:36] Started run 944 on task 146227, dataset 'churn'.
[2018-04-11 22:19:36] Error in run 937: Run already exists in server. Run id(s): {8987472}
[2018-04-11 22:19:36] Started run 945 on task 146227, dataset 'churn'.
[2018-04-11 22:19:36] Error in run 938: Run already exists in server. Run id(s): {8987471}
[2018-04-11 22:19:36] Started run 946 on task 146227, dataset 'churn'.
[2018-04-11 22:19:37] Error in run 939: Run already exists in server. Run id(s): {8987474}
[2018-04-11 22:19:37] Started run 947 on task 146227, dataset 'churn'.
[2018-04-11 22:19:38] Error in run 940: Run already exists in server. Run id(s): {8987492}
[2018-04-11 22:19:38] Started run 948 on task 146227, dataset 'churn'.
[2018-04-11 22:19:38] Error in run 941: Run already exists in server. Run id(s): {8987496}
[2018-04-11 22:19:38] Started run 949 on task 146227, dataset 'churn'.
[2018-04-11 22:19:39] Error in run 942: Run already exists in server. Run id(s): {8987488}
[2018-04-11 22:19:39] Started run 950 on task 146227, dataset 'churn'.
[2018-04-11 22:19:39] Error in run 943: Run already exists in server. Run id(s): {8987489}
[2018-04-11 22:19:39] Started run 951 on task 146227, dataset 'churn'.
[2018-04-11 22:19:40] Error in run 944: Run already exists in server. Run id(s): {8987504}
[2018-04-11 22:19:40] Started run 952 on task 146227, dataset 'churn'.
[2018-04-11 22:19:40] Error in run 945: Run already exists in server. Run id(s): {8987501}
[2018-04-11 22:19:40] Started run 953 on task 146227, dataset 'churn'.
[2018-04-11 22:19:41] Error in run 946: Run already exists in server. Run id(s): {8987505}
[2018-04-11 22:19:41] Started run 954 on task 146227, dataset 'churn'.
[2018-04-11 22:19:42] Error in run 947: Run already exists in server. Run id(s): {8987515}
[2018-04-11 22:19:42] Started run 955 on task 146227, dataset 'churn'.
[2018-04-11 22:19:43] Error in run 948: Run already exists in server. Run id(s): {8987510}
[2018-04-11 22:19:43] Started run 956 on task 146227, dataset 'churn'.
[2018-04-11 22:19:43] Error in run 949: Run already exists in server. Run id(s): {8987522}
[2018-04-11 22:19:43] Started run 957 on task 146227, dataset 'churn'.
[2018-04-11 22:19:43] Error in run 950: Run already exists in server. Run id(s): {8987517}
[2018-04-11 22:19:43] Started run 958 on task 146227, dataset 'churn'.
[2018-04-11 22:19:43] Error in run 951: Run already exists in server. Run id(s): {8987529}
[2018-04-11 22:19:43] Started run 959 on task 146227, dataset 'churn'.
[2018-04-11 22:19:45] Error in run 952: Run already exists in server. Run id(s): {8987531}
[2018-04-11 22:19:45] Started run 960 on task 146227, dataset 'churn'.
[2018-04-11 22:19:45] Error in run 953: Run already exists in server. Run id(s): {8987526}
[2018-04-11 22:19:45] Started run 961 on task 146227, dataset 'churn'.
[2018-04-11 22:19:45] Error in run 954: Run already exists in server. Run id(s): {8987538}
[2018-04-11 22:19:45] Started run 962 on task 146227, dataset 'churn'.
[2018-04-11 22:19:47] Error in run 955: Run already exists in server. Run id(s): {8987536}
[2018-04-11 22:19:47] Started run 963 on task 146227, dataset 'churn'.
[2018-04-11 22:19:48] Error in run 958: Run already exists in server. Run id(s): {8987563}
[2018-04-11 22:19:48] Error in run 957: Run already exists in server. Run id(s): {8987549}
[2018-04-11 22:19:48] Started run 964 on task 146227, dataset 'churn'.
[2018-04-11 22:19:48] Error in run 956: Run already exists in server. Run id(s): {8987539}
[2018-04-11 22:19:48] Started run 965 on task 146227, dataset 'churn'.
[2018-04-11 22:19:48] Started run 966 on task 146227, dataset 'churn'.
[2018-04-11 22:19:48] Error in run 959: Run already exists in server. Run id(s): {8987564}
[2018-04-11 22:19:48] Started run 967 on task 146227, dataset 'churn'.
[2018-04-11 22:19:49] Error in run 960: Run already exists in server. Run id(s): {8987556}
[2018-04-11 22:19:49] Started run 968 on task 146227, dataset 'churn'.
[2018-04-11 22:19:49] Error in run 961: Run already exists in server. Run id(s): {8987573}
[2018-04-11 22:19:49] Started run 969 on task 146227, dataset 'churn'.
[2018-04-11 22:19:50] Error in run 962: Run already exists in server. Run id(s): {8987571}
[2018-04-11 22:19:50] Started run 970 on task 146227, dataset 'churn'.
[2018-04-11 22:19:51] Error in run 963: Run already exists in server. Run id(s): {8987583}
[2018-04-11 22:19:51] Started run 971 on task 146227, dataset 'churn'.
[2018-04-11 22:19:52] Error in run 964: Run already exists in server. Run id(s): {8987588}
[2018-04-11 22:19:52] Error in run 965: Run already exists in server. Run id(s): {8987581}
[2018-04-11 22:19:52] Started run 972 on task 146227, dataset 'churn'.
[2018-04-11 22:19:52] Started run 973 on task 146227, dataset 'churn'.
[2018-04-11 22:19:52] Error in run 966: Run already exists in server. Run id(s): {8987591}
[2018-04-11 22:19:52] Started run 974 on task 146227, dataset 'churn'.
[2018-04-11 22:19:52] Error in run 967: Run already exists in server. Run id(s): {8987605}
[2018-04-11 22:19:52] Started run 975 on task 146227, dataset 'churn'.
[2018-04-11 22:19:54] Error in run 968: Run already exists in server. Run id(s): {8987604}
[2018-04-11 22:19:54] Started run 976 on task 146227, dataset 'churn'.
[2018-04-11 22:19:54] Error in run 969: Run already exists in server. Run id(s): {8987612}
[2018-04-11 22:19:54] Started run 977 on task 146227, dataset 'churn'.
[2018-04-11 22:19:54] Error in run 970: Run already exists in server. Run id(s): {8987601}
[2018-04-11 22:19:54] Started run 978 on task 146227, dataset 'churn'.
[2018-04-11 22:19:56] Error in run 971: Run already exists in server. Run id(s): {8987624}
[2018-04-11 22:19:56] Started run 979 on task 146227, dataset 'churn'.
[2018-04-11 22:19:57] Error in run 972: Run already exists in server. Run id(s): {8987628}
[2018-04-11 22:19:57] Started run 980 on task 146227, dataset 'churn'.
[2018-04-11 22:19:57] Error in run 973: Run already exists in server. Run id(s): {8987621}
[2018-04-11 22:19:57] Started run 981 on task 146227, dataset 'churn'.
[2018-04-11 22:19:57] Error in run 974: Run already exists in server. Run id(s): {8987630}
[2018-04-11 22:19:57] Started run 982 on task 146227, dataset 'churn'.
[2018-04-11 22:19:57] Error in run 975: Run already exists in server. Run id(s): {8987638}
[2018-04-11 22:19:57] Started run 983 on task 146227, dataset 'churn'.
[2018-04-11 22:19:58] Error in run 976: Run already exists in server. Run id(s): {8987649}
[2018-04-11 22:19:58] Started run 984 on task 146227, dataset 'churn'.
[2018-04-11 22:19:58] Error in run 977: Run already exists in server. Run id(s): {8987639}
[2018-04-11 22:19:58] Started run 985 on task 146227, dataset 'churn'.
[2018-04-11 22:19:59] Error in run 978: Run already exists in server. Run id(s): {8987654}
[2018-04-11 22:19:59] Started run 986 on task 146227, dataset 'churn'.
[2018-04-11 22:20:00] Error in run 979: Run already exists in server. Run id(s): {8987653}
[2018-04-11 22:20:00] Started run 987 on task 146227, dataset 'churn'.
[2018-04-11 22:20:01] Error in run 980: Run already exists in server. Run id(s): {8987652}
[2018-04-11 22:20:01] Started run 988 on task 146227, dataset 'churn'.
[2018-04-11 22:20:01] Error in run 982: Run already exists in server. Run id(s): {8987668}
[2018-04-11 22:20:01] Started run 989 on task 146227, dataset 'churn'.
[2018-04-11 22:20:01] Error in run 981: Run already exists in server. Run id(s): {8987661}
[2018-04-11 22:20:01] Started run 990 on task 146227, dataset 'churn'.
[2018-04-11 22:20:01] Error in run 983: Run already exists in server. Run id(s): {8987674}
[2018-04-11 22:20:01] Started run 991 on task 146227, dataset 'churn'.
[2018-04-11 22:20:03] Error in run 984: Run already exists in server. Run id(s): {8987669}
[2018-04-11 22:20:03] Started run 992 on task 146227, dataset 'churn'.
[2018-04-11 22:20:03] Error in run 985: Run already exists in server. Run id(s): {8987675}
[2018-04-11 22:20:03] Started run 993 on task 146227, dataset 'churn'.
[2018-04-11 22:20:04] Error in run 986: Run already exists in server. Run id(s): {8987690}
[2018-04-11 22:20:04] Started run 994 on task 146227, dataset 'churn'.
[2018-04-11 22:20:05] Error in run 987: Run already exists in server. Run id(s): {8987681}
[2018-04-11 22:20:05] Started run 995 on task 146227, dataset 'churn'.
[2018-04-11 22:20:06] Error in run 988: Run already exists in server. Run id(s): {8987692}
[2018-04-11 22:20:06] Started run 996 on task 146227, dataset 'churn'.
[2018-04-11 22:20:06] Error in run 989: Run already exists in server. Run id(s): {8987689}
[2018-04-11 22:20:06] Started run 997 on task 146227, dataset 'churn'.
[2018-04-11 22:20:06] Error in run 991: Run already exists in server. Run id(s): {8987698}
[2018-04-11 22:20:06] Started run 998 on task 146227, dataset 'churn'.
[2018-04-11 22:20:06] Error in run 990: Run already exists in server. Run id(s): {8987702}
[2018-04-11 22:20:06] Started run 999 on task 146227, dataset 'churn'.
[2018-04-11 22:20:07] Error in run 992: Run already exists in server. Run id(s): {8987699}
[2018-04-11 22:20:07] Started run 1000 on task 146227, dataset 'churn'.
[2018-04-11 22:20:08] Error in run 993: Run already exists in server. Run id(s): {8987708}
[2018-04-11 22:20:08] Error in run 994: Run already exists in server. Run id(s): {8987719}
[2018-04-11 22:20:09] Error in run 995: Run already exists in server. Run id(s): {8987716}
[2018-04-11 22:20:10] Error in run 996: Run already exists in server. Run id(s): {8987723}
[2018-04-11 22:20:10] Error in run 997: Run already exists in server. Run id(s): {8987720}
[2018-04-11 22:20:11] Error in run 998: Run already exists in server. Run id(s): {8987738}
[2018-04-11 22:20:11] Error in run 999: Run already exists in server. Run id(s): {8987730}
[2018-04-11 22:20:12] Error in run 1000: Run already exists in server. Run id(s): {8987735}
