declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00007/certs"
declare -x AZ_BATCH_JOB_ID="svm"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/svm/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/svm/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_5-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00007"
declare -x AZ_BATCH_TASK_ID="task-00007"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00007/wd"
declare -x HOME="/mnt/batch/tasks/workitems/svm/job-1/task-00007/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/svm/job-1/task-00007/wd"
declare -x PWD="/mnt/batch/tasks/workitems/svm/job-1/task-00007/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 21:03:06] Results will not be logged locally.
[2018-04-11 21:03:06] Retrieving tasks...
[2018-04-11 21:03:06] Tasks will be retrieved based on provided task ids.
[2018-04-11 21:03:06] The following tasks were retrieved: [3021].
[2018-04-11 21:03:12] Downloaded task 3021.
[2018-04-11 21:03:13] Prepared pipelines.
[2018-04-11 21:03:13] Started run 1 on task 3021, dataset 'sick'.
[2018-04-11 21:03:13] Started run 2 on task 3021, dataset 'sick'.
[2018-04-11 21:03:13] Started run 3 on task 3021, dataset 'sick'.
[2018-04-11 21:03:13] Started run 4 on task 3021, dataset 'sick'.
[2018-04-11 21:03:13] Started run 5 on task 3021, dataset 'sick'.
[2018-04-11 21:03:13] Started run 6 on task 3021, dataset 'sick'.
[2018-04-11 21:03:13] Started run 7 on task 3021, dataset 'sick'.
[2018-04-11 21:03:13] Started run 8 on task 3021, dataset 'sick'.
[2018-04-11 21:03:17] Error in run 3: Run already exists in server. Run id(s): {8943706}
[2018-04-11 21:03:17] Error in run 1: Run already exists in server. Run id(s): {8943707}
[2018-04-11 21:03:17] Started run 9 on task 3021, dataset 'sick'.
[2018-04-11 21:03:17] Started run 10 on task 3021, dataset 'sick'.
[2018-04-11 21:03:17] Error in run 4: Run already exists in server. Run id(s): {8943708}
[2018-04-11 21:03:17] Error in run 5: Run already exists in server. Run id(s): {8943712}
[2018-04-11 21:03:17] Error in run 2: Run already exists in server. Run id(s): {8943705}
[2018-04-11 21:03:17] Started run 11 on task 3021, dataset 'sick'.
[2018-04-11 21:03:17] Started run 13 on task 3021, dataset 'sick'.
[2018-04-11 21:03:17] Started run 12 on task 3021, dataset 'sick'.
[2018-04-11 21:03:17] Error in run 6: Run already exists in server. Run id(s): {8943709}
[2018-04-11 21:03:17] Started run 14 on task 3021, dataset 'sick'.
[2018-04-11 21:03:18] Error in run 7: Run already exists in server. Run id(s): {8943710}
[2018-04-11 21:03:18] Started run 15 on task 3021, dataset 'sick'.
[2018-04-11 21:03:18] Error in run 8: Run already exists in server. Run id(s): {8943711}
[2018-04-11 21:03:18] Started run 16 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Error in run 9: Run already exists in server. Run id(s): {8943713}
[2018-04-11 21:03:22] Error in run 12: Run already exists in server. Run id(s): {8943716}
[2018-04-11 21:03:22] Error in run 11: Run already exists in server. Run id(s): {8943715}
[2018-04-11 21:03:22] Started run 17 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Error in run 15: Run already exists in server. Run id(s): {8943719}
[2018-04-11 21:03:22] Error in run 14: Run already exists in server. Run id(s): {8943718}
[2018-04-11 21:03:22] Started run 19 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Error in run 13: Run already exists in server. Run id(s): {8943717}
[2018-04-11 21:03:22] Error in run 10: Run already exists in server. Run id(s): {8943714}
[2018-04-11 21:03:22] Error in run 16: Run already exists in server. Run id(s): {8943720}
[2018-04-11 21:03:22] Started run 20 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Started run 23 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Started run 22 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Started run 24 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Started run 21 on task 3021, dataset 'sick'.
[2018-04-11 21:03:22] Started run 18 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Error in run 20: Run already exists in server. Run id(s): {8943724}
[2018-04-11 21:03:27] Error in run 23: Run already exists in server. Run id(s): {8943727}
[2018-04-11 21:03:27] Error in run 21: Run already exists in server. Run id(s): {8943725}
[2018-04-11 21:03:27] Started run 25 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Error in run 17: Run already exists in server. Run id(s): {8943722}
[2018-04-11 21:03:27] Error in run 18: Run already exists in server. Run id(s): {8943721}
[2018-04-11 21:03:27] Started run 28 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Started run 29 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Error in run 24: Run already exists in server. Run id(s): {8943729}
[2018-04-11 21:03:27] Error in run 19: Run already exists in server. Run id(s): {8943723}
[2018-04-11 21:03:27] Error in run 22: Run already exists in server. Run id(s): {8943726}
[2018-04-11 21:03:27] Started run 30 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Started run 32 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Started run 31 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Started run 27 on task 3021, dataset 'sick'.
[2018-04-11 21:03:27] Started run 26 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Error in run 32: Run already exists in server. Run id(s): {8943736}
[2018-04-11 21:03:32] Error in run 27: Run already exists in server. Run id(s): {8943731}
[2018-04-11 21:03:32] Error in run 30: Run already exists in server. Run id(s): {8943734}
[2018-04-11 21:03:32] Started run 33 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Error in run 25: Run already exists in server. Run id(s): {8943728}
[2018-04-11 21:03:32] Error in run 29: Run already exists in server. Run id(s): {8943732}
[2018-04-11 21:03:32] Error in run 26: Run already exists in server. Run id(s): {8943730}
[2018-04-11 21:03:32] Error in run 28: Run already exists in server. Run id(s): {8943733}
[2018-04-11 21:03:32] Error in run 31: Run already exists in server. Run id(s): {8943735}
[2018-04-11 21:03:32] Started run 36 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Started run 37 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Started run 34 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Started run 38 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Started run 35 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Started run 39 on task 3021, dataset 'sick'.
[2018-04-11 21:03:32] Started run 40 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Error in run 40: Run already exists in server. Run id(s): {8943744}
[2018-04-11 21:03:36] Error in run 37: Run already exists in server. Run id(s): {8943743}
[2018-04-11 21:03:36] Started run 41 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Error in run 36: Run already exists in server. Run id(s): {8943740}
[2018-04-11 21:03:36] Error in run 38: Run already exists in server. Run id(s): {8943742}
[2018-04-11 21:03:36] Started run 42 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Error in run 35: Run already exists in server. Run id(s): {8943739}
[2018-04-11 21:03:36] Error in run 33: Run already exists in server. Run id(s): {8943737}
[2018-04-11 21:03:36] Error in run 39: Run already exists in server. Run id(s): {8943741}
[2018-04-11 21:03:36] Started run 43 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Error in run 34: Run already exists in server. Run id(s): {8943738}
[2018-04-11 21:03:36] Started run 45 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Started run 44 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Started run 46 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Started run 48 on task 3021, dataset 'sick'.
[2018-04-11 21:03:36] Started run 47 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Error in run 41: Run already exists in server. Run id(s): {8943745}
[2018-04-11 21:03:41] Started run 49 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Error in run 44: Run already exists in server. Run id(s): {8943750}
[2018-04-11 21:03:41] Error in run 45: Run already exists in server. Run id(s): {8943748}
[2018-04-11 21:03:41] Started run 50 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Error in run 46: Run already exists in server. Run id(s): {8943751}
[2018-04-11 21:03:41] Error in run 47: Run already exists in server. Run id(s): {8943749}
[2018-04-11 21:03:41] Error in run 48: Run already exists in server. Run id(s): {8943752}
[2018-04-11 21:03:41] Started run 52 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Error in run 42: Run already exists in server. Run id(s): {8943747}
[2018-04-11 21:03:41] Error in run 43: Run already exists in server. Run id(s): {8943746}
[2018-04-11 21:03:41] Started run 55 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Started run 51 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Started run 54 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Started run 56 on task 3021, dataset 'sick'.
[2018-04-11 21:03:41] Started run 53 on task 3021, dataset 'sick'.
[2018-04-11 21:03:45] Error in run 49: Run already exists in server. Run id(s): {8943753}
[2018-04-11 21:03:45] Started run 57 on task 3021, dataset 'sick'.
[2018-04-11 21:03:46] Error in run 55: Run already exists in server. Run id(s): {8943757}
[2018-04-11 21:03:46] Error in run 50: Run already exists in server. Run id(s): {8943755}
[2018-04-11 21:03:46] Error in run 51: Run already exists in server. Run id(s): {8943754}
[2018-04-11 21:03:46] Error in run 53: Run already exists in server. Run id(s): {8943756}
[2018-04-11 21:03:46] Error in run 56: Run already exists in server. Run id(s): {8943760}
[2018-04-11 21:03:46] Started run 58 on task 3021, dataset 'sick'.
[2018-04-11 21:03:46] Started run 59 on task 3021, dataset 'sick'.
[2018-04-11 21:03:46] Error in run 54: Run already exists in server. Run id(s): {8943759}
[2018-04-11 21:03:46] Started run 63 on task 3021, dataset 'sick'.
[2018-04-11 21:03:46] Error in run 52: Run already exists in server. Run id(s): {8943758}
[2018-04-11 21:03:46] Started run 62 on task 3021, dataset 'sick'.
[2018-04-11 21:03:46] Started run 64 on task 3021, dataset 'sick'.
[2018-04-11 21:03:46] Started run 60 on task 3021, dataset 'sick'.
[2018-04-11 21:03:46] Started run 61 on task 3021, dataset 'sick'.
[2018-04-11 21:03:50] Error in run 57: Run already exists in server. Run id(s): {8943761}
[2018-04-11 21:03:50] Started run 65 on task 3021, dataset 'sick'.
[2018-04-11 21:03:50] Error in run 59: Run already exists in server. Run id(s): {8943763}
[2018-04-11 21:03:50] Started run 66 on task 3021, dataset 'sick'.
[2018-04-11 21:03:51] Error in run 61: Run already exists in server. Run id(s): {8943764}
[2018-04-11 21:03:51] Error in run 63: Run already exists in server. Run id(s): {8943766}
[2018-04-11 21:03:51] Error in run 64: Run already exists in server. Run id(s): {8943769}
[2018-04-11 21:03:51] Started run 67 on task 3021, dataset 'sick'.
[2018-04-11 21:03:51] Error in run 58: Run already exists in server. Run id(s): {8943762}
[2018-04-11 21:03:51] Error in run 60: Run already exists in server. Run id(s): {8943765}
[2018-04-11 21:03:51] Error in run 62: Run already exists in server. Run id(s): {8943767}
[2018-04-11 21:03:51] Started run 70 on task 3021, dataset 'sick'.
[2018-04-11 21:03:51] Started run 69 on task 3021, dataset 'sick'.
[2018-04-11 21:03:51] Started run 68 on task 3021, dataset 'sick'.
[2018-04-11 21:03:51] Started run 71 on task 3021, dataset 'sick'.
[2018-04-11 21:03:51] Started run 72 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Error in run 65: Run already exists in server. Run id(s): {8943768}
[2018-04-11 21:03:55] Started run 73 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Error in run 66: Run already exists in server. Run id(s): {8943770}
[2018-04-11 21:03:55] Started run 74 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Error in run 69: Run already exists in server. Run id(s): {8943774}
[2018-04-11 21:03:55] Error in run 71: Run already exists in server. Run id(s): {8943775}
[2018-04-11 21:03:55] Error in run 68: Run already exists in server. Run id(s): {8943772}
[2018-04-11 21:03:55] Error in run 72: Run already exists in server. Run id(s): {8943778}
[2018-04-11 21:03:55] Started run 75 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Error in run 67: Run already exists in server. Run id(s): {8943771}
[2018-04-11 21:03:55] Error in run 70: Run already exists in server. Run id(s): {8943773}
[2018-04-11 21:03:55] Started run 76 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Started run 79 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Started run 78 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Started run 80 on task 3021, dataset 'sick'.
[2018-04-11 21:03:55] Started run 77 on task 3021, dataset 'sick'.
[2018-04-11 21:03:59] Error in run 73: Run already exists in server. Run id(s): {8943776}
[2018-04-11 21:03:59] Started run 81 on task 3021, dataset 'sick'.
[2018-04-11 21:03:59] Error in run 74: Run already exists in server. Run id(s): {8943777}
[2018-04-11 21:03:59] Started run 82 on task 3021, dataset 'sick'.
[2018-04-11 21:04:00] Error in run 78: Run already exists in server. Run id(s): {8943781}
[2018-04-11 21:04:00] Error in run 76: Run already exists in server. Run id(s): {8943780}
[2018-04-11 21:04:00] Error in run 77: Run already exists in server. Run id(s): {8943782}
[2018-04-11 21:04:00] Started run 83 on task 3021, dataset 'sick'.
[2018-04-11 21:04:00] Error in run 80: Run already exists in server. Run id(s): {8943784}
[2018-04-11 21:04:00] Error in run 75: Run already exists in server. Run id(s): {8943779}
[2018-04-11 21:04:00] Error in run 79: Run already exists in server. Run id(s): {8943783}
[2018-04-11 21:04:00] Started run 86 on task 3021, dataset 'sick'.
[2018-04-11 21:04:00] Started run 87 on task 3021, dataset 'sick'.
[2018-04-11 21:04:00] Started run 88 on task 3021, dataset 'sick'.
[2018-04-11 21:04:00] Started run 84 on task 3021, dataset 'sick'.
[2018-04-11 21:04:00] Started run 85 on task 3021, dataset 'sick'.
[2018-04-11 21:04:04] Error in run 82: Run already exists in server. Run id(s): {9014011}
[2018-04-11 21:04:04] Started run 89 on task 3021, dataset 'sick'.
[2018-04-11 21:04:04] Error in run 81: Run already exists in server. Run id(s): {8943785}
[2018-04-11 21:04:04] Started run 90 on task 3021, dataset 'sick'.
[2018-04-11 21:04:05] Error in run 84: Run already exists in server. Run id(s): {8943788}
[2018-04-11 21:04:05] Error in run 86: Run already exists in server. Run id(s): {8943789}
[2018-04-11 21:04:05] Started run 91 on task 3021, dataset 'sick'.
[2018-04-11 21:04:05] Started run 92 on task 3021, dataset 'sick'.
[2018-04-11 21:04:05] Error in run 83: Run already exists in server. Run id(s): {9014019}
[2018-04-11 21:04:05] Started run 93 on task 3021, dataset 'sick'.
[2018-04-11 21:04:05] Error in run 88: Run already exists in server. Run id(s): {8943792}
[2018-04-11 21:04:05] Started run 94 on task 3021, dataset 'sick'.
[2018-04-11 21:04:05] Error in run 85: Run already exists in server. Run id(s): {8943790}
[2018-04-11 21:04:05] Started run 95 on task 3021, dataset 'sick'.
[2018-04-11 21:04:05] Error in run 87: Run already exists in server. Run id(s): {8943791}
[2018-04-11 21:04:05] Started run 96 on task 3021, dataset 'sick'.
[2018-04-11 21:04:09] Error in run 89: Run already exists in server. Run id(s): {8943793}
[2018-04-11 21:04:09] Error in run 90: Run already exists in server. Run id(s): {8943794}
[2018-04-11 21:04:09] Started run 97 on task 3021, dataset 'sick'.
[2018-04-11 21:04:09] Started run 98 on task 3021, dataset 'sick'.
[2018-04-11 21:04:10] Error in run 95: Run already exists in server. Run id(s): {8943800}
[2018-04-11 21:04:10] Error in run 91: Run already exists in server. Run id(s): {8943795}
[2018-04-11 21:04:10] Error in run 94: Run already exists in server. Run id(s): {8943797}
[2018-04-11 21:04:10] Started run 99 on task 3021, dataset 'sick'.
[2018-04-11 21:04:10] Error in run 93: Run already exists in server. Run id(s): {8943798}
[2018-04-11 21:04:10] Error in run 92: Run already exists in server. Run id(s): {8943796}
[2018-04-11 21:04:10] Error in run 96: Run already exists in server. Run id(s): {8943799}
[2018-04-11 21:04:10] Started run 102 on task 3021, dataset 'sick'.
[2018-04-11 21:04:10] Started run 103 on task 3021, dataset 'sick'.
[2018-04-11 21:04:10] Started run 104 on task 3021, dataset 'sick'.
[2018-04-11 21:04:10] Started run 100 on task 3021, dataset 'sick'.
[2018-04-11 21:04:10] Started run 101 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Error in run 98: Run already exists in server. Run id(s): {8943803}
[2018-04-11 21:04:14] Started run 105 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Error in run 97: Run already exists in server. Run id(s): {8943801}
[2018-04-11 21:04:14] Started run 106 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Error in run 102: Run already exists in server. Run id(s): {8943806}
[2018-04-11 21:04:14] Error in run 99: Run already exists in server. Run id(s): {8943802}
[2018-04-11 21:04:14] Started run 107 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Error in run 100: Run already exists in server. Run id(s): {8943804}
[2018-04-11 21:04:14] Error in run 104: Run already exists in server. Run id(s): {8943808}
[2018-04-11 21:04:14] Started run 108 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Error in run 103: Run already exists in server. Run id(s): {8943807}
[2018-04-11 21:04:14] Error in run 101: Run already exists in server. Run id(s): {8943805}
[2018-04-11 21:04:14] Started run 111 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Started run 112 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Started run 110 on task 3021, dataset 'sick'.
[2018-04-11 21:04:14] Started run 109 on task 3021, dataset 'sick'.
[2018-04-11 21:04:19] Error in run 106: Run already exists in server. Run id(s): {8943812}
[2018-04-11 21:04:19] Started run 113 on task 3021, dataset 'sick'.
[2018-04-11 21:04:19] Error in run 105: Run already exists in server. Run id(s): {8943809}
[2018-04-11 21:04:19] Started run 114 on task 3021, dataset 'sick'.
[2018-04-11 21:04:20] Error in run 108: Run already exists in server. Run id(s): {8943811}
[2018-04-11 21:04:20] Error in run 107: Run already exists in server. Run id(s): {8943810}
[2018-04-11 21:04:20] Started run 115 on task 3021, dataset 'sick'.
[2018-04-11 21:04:20] Started run 116 on task 3021, dataset 'sick'.
[2018-04-11 21:04:20] Error in run 112: Run already exists in server. Run id(s): {8943816}
[2018-04-11 21:04:20] Started run 117 on task 3021, dataset 'sick'.
[2018-04-11 21:04:20] Error in run 110: Run already exists in server. Run id(s): {8943814}
[2018-04-11 21:04:20] Started run 118 on task 3021, dataset 'sick'.
[2018-04-11 21:04:20] Error in run 109: Run already exists in server. Run id(s): {8943813}
[2018-04-11 21:04:20] Started run 119 on task 3021, dataset 'sick'.
[2018-04-11 21:04:20] Error in run 111: Run already exists in server. Run id(s): {8943815}
[2018-04-11 21:04:20] Started run 120 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Error in run 113: Run already exists in server. Run id(s): {8943817}
[2018-04-11 21:04:24] Started run 121 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Error in run 114: Run already exists in server. Run id(s): {8943820}
[2018-04-11 21:04:24] Started run 122 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Error in run 115: Run already exists in server. Run id(s): {8943818}
[2018-04-11 21:04:24] Error in run 116: Run already exists in server. Run id(s): {8943819}
[2018-04-11 21:04:24] Started run 123 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Started run 124 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Error in run 118: Run already exists in server. Run id(s): {8943823}
[2018-04-11 21:04:24] Error in run 117: Run already exists in server. Run id(s): {8943821}
[2018-04-11 21:04:24] Started run 125 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Error in run 119: Run already exists in server. Run id(s): {8943824}
[2018-04-11 21:04:24] Error in run 120: Run already exists in server. Run id(s): {8943822}
[2018-04-11 21:04:24] Started run 126 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Started run 128 on task 3021, dataset 'sick'.
[2018-04-11 21:04:24] Started run 127 on task 3021, dataset 'sick'.
[2018-04-11 21:04:28] Error in run 122: Run already exists in server. Run id(s): {8943827}
[2018-04-11 21:04:28] Error in run 121: Run already exists in server. Run id(s): {8943825}
[2018-04-11 21:04:28] Started run 129 on task 3021, dataset 'sick'.
[2018-04-11 21:04:28] Started run 130 on task 3021, dataset 'sick'.
[2018-04-11 21:04:29] Error in run 123: Run already exists in server. Run id(s): {8943826}
[2018-04-11 21:04:29] Error in run 124: Run already exists in server. Run id(s): {8943828}
[2018-04-11 21:04:29] Started run 131 on task 3021, dataset 'sick'.
[2018-04-11 21:04:29] Error in run 125: Run already exists in server. Run id(s): {8943830}
[2018-04-11 21:04:29] Started run 132 on task 3021, dataset 'sick'.
[2018-04-11 21:04:29] Started run 133 on task 3021, dataset 'sick'.
[2018-04-11 21:04:29] Error in run 128: Run already exists in server. Run id(s): {8943832}
[2018-04-11 21:04:29] Started run 134 on task 3021, dataset 'sick'.
[2018-04-11 21:04:29] Error in run 126: Run already exists in server. Run id(s): {8943829}
[2018-04-11 21:04:29] Started run 135 on task 3021, dataset 'sick'.
[2018-04-11 21:04:29] Error in run 127: Run already exists in server. Run id(s): {8943831}
[2018-04-11 21:04:29] Started run 136 on task 3021, dataset 'sick'.
[2018-04-11 21:04:33] Error in run 129: Run already exists in server. Run id(s): {8943833}
[2018-04-11 21:04:33] Started run 137 on task 3021, dataset 'sick'.
[2018-04-11 21:04:33] Error in run 130: Run already exists in server. Run id(s): {8943834}
[2018-04-11 21:04:33] Started run 138 on task 3021, dataset 'sick'.
[2018-04-11 21:04:34] Error in run 135: Run already exists in server. Run id(s): {8943839}
[2018-04-11 21:04:34] Started run 139 on task 3021, dataset 'sick'.
[2018-04-11 21:04:34] Error in run 131: Run already exists in server. Run id(s): {8943835}
[2018-04-11 21:04:34] Error in run 133: Run already exists in server. Run id(s): {8943838}
[2018-04-11 21:04:34] Started run 140 on task 3021, dataset 'sick'.
[2018-04-11 21:04:34] Error in run 132: Run already exists in server. Run id(s): {8943836}
[2018-04-11 21:04:34] Error in run 134: Run already exists in server. Run id(s): {8943837}
[2018-04-11 21:04:34] Error in run 136: Run already exists in server. Run id(s): {8943840}
[2018-04-11 21:04:34] Started run 142 on task 3021, dataset 'sick'.
[2018-04-11 21:04:34] Started run 143 on task 3021, dataset 'sick'.
[2018-04-11 21:04:34] Started run 141 on task 3021, dataset 'sick'.
[2018-04-11 21:04:34] Started run 144 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Error in run 137: Run already exists in server. Run id(s): {8943843}
[2018-04-11 21:04:38] Started run 145 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Error in run 138: Run already exists in server. Run id(s): {8943841}
[2018-04-11 21:04:38] Started run 146 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Error in run 139: Run already exists in server. Run id(s): {8943842}
[2018-04-11 21:04:38] Started run 147 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Error in run 141: Run already exists in server. Run id(s): {8943845}
[2018-04-11 21:04:38] Started run 148 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Error in run 142: Run already exists in server. Run id(s): {8943847}
[2018-04-11 21:04:38] Error in run 140: Run already exists in server. Run id(s): {8943844}
[2018-04-11 21:04:38] Error in run 144: Run already exists in server. Run id(s): {8943850}
[2018-04-11 21:04:38] Error in run 143: Run already exists in server. Run id(s): {8943846}
[2018-04-11 21:04:38] Started run 149 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Started run 150 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Started run 151 on task 3021, dataset 'sick'.
[2018-04-11 21:04:38] Started run 152 on task 3021, dataset 'sick'.
[2018-04-11 21:04:42] Error in run 146: Run already exists in server. Run id(s): {8943848}
[2018-04-11 21:04:42] Error in run 145: Run already exists in server. Run id(s): {8943851}
[2018-04-11 21:04:42] Started run 153 on task 3021, dataset 'sick'.
[2018-04-11 21:04:42] Started run 154 on task 3021, dataset 'sick'.
[2018-04-11 21:04:43] Error in run 147: Run already exists in server. Run id(s): {8943849}
[2018-04-11 21:04:43] Started run 155 on task 3021, dataset 'sick'.
[2018-04-11 21:04:43] Error in run 148: Run already exists in server. Run id(s): {8943852}
[2018-04-11 21:04:43] Started run 156 on task 3021, dataset 'sick'.
[2018-04-11 21:04:43] Error in run 150: Run already exists in server. Run id(s): {8943855}
[2018-04-11 21:04:43] Error in run 149: Run already exists in server. Run id(s): {8943853}
[2018-04-11 21:04:43] Started run 157 on task 3021, dataset 'sick'.
[2018-04-11 21:04:43] Error in run 151: Run already exists in server. Run id(s): {8943854}
[2018-04-11 21:04:43] Error in run 152: Run already exists in server. Run id(s): {8943856}
[2018-04-11 21:04:43] Started run 159 on task 3021, dataset 'sick'.
[2018-04-11 21:04:43] Started run 158 on task 3021, dataset 'sick'.
[2018-04-11 21:04:43] Started run 160 on task 3021, dataset 'sick'.
[2018-04-11 21:04:47] Error in run 153: Run already exists in server. Run id(s): {8943859}
[2018-04-11 21:04:47] Started run 161 on task 3021, dataset 'sick'.
[2018-04-11 21:04:47] Error in run 155: Run already exists in server. Run id(s): {8943858}
[2018-04-11 21:04:47] Error in run 154: Run already exists in server. Run id(s): {8943857}
[2018-04-11 21:04:47] Started run 162 on task 3021, dataset 'sick'.
[2018-04-11 21:04:47] Started run 163 on task 3021, dataset 'sick'.
[2018-04-11 21:04:48] Error in run 156: Run already exists in server. Run id(s): {8943860}
[2018-04-11 21:04:48] Started run 164 on task 3021, dataset 'sick'.
[2018-04-11 21:04:48] Error in run 160: Run already exists in server. Run id(s): {8943863}
[2018-04-11 21:04:48] Error in run 158: Run already exists in server. Run id(s): {8943861}
[2018-04-11 21:04:48] Error in run 157: Run already exists in server. Run id(s): {8943864}
[2018-04-11 21:04:48] Error in run 159: Run already exists in server. Run id(s): {8943862}
[2018-04-11 21:04:48] Started run 165 on task 3021, dataset 'sick'.
[2018-04-11 21:04:48] Started run 166 on task 3021, dataset 'sick'.
[2018-04-11 21:04:48] Started run 167 on task 3021, dataset 'sick'.
[2018-04-11 21:04:48] Started run 168 on task 3021, dataset 'sick'.
[2018-04-11 21:04:51] Error in run 161: Run already exists in server. Run id(s): {8943865}
[2018-04-11 21:04:51] Started run 169 on task 3021, dataset 'sick'.
[2018-04-11 21:04:52] Error in run 163: Run already exists in server. Run id(s): {8943867}
[2018-04-11 21:04:52] Error in run 162: Run already exists in server. Run id(s): {8943866}
[2018-04-11 21:04:52] Started run 170 on task 3021, dataset 'sick'.
[2018-04-11 21:04:52] Started run 171 on task 3021, dataset 'sick'.
[2018-04-11 21:04:52] Error in run 164: Run already exists in server. Run id(s): {8943868}
[2018-04-11 21:04:52] Started run 172 on task 3021, dataset 'sick'.
[2018-04-11 21:04:53] Error in run 168: Run already exists in server. Run id(s): {8943872}
[2018-04-11 21:04:53] Error in run 167: Run already exists in server. Run id(s): {8943870}
[2018-04-11 21:04:53] Error in run 165: Run already exists in server. Run id(s): {8943869}
[2018-04-11 21:04:53] Started run 173 on task 3021, dataset 'sick'.
[2018-04-11 21:04:53] Error in run 166: Run already exists in server. Run id(s): {8943871}
[2018-04-11 21:04:53] Started run 176 on task 3021, dataset 'sick'.
[2018-04-11 21:04:53] Started run 174 on task 3021, dataset 'sick'.
[2018-04-11 21:04:53] Started run 175 on task 3021, dataset 'sick'.
[2018-04-11 21:04:56] Error in run 169: Run already exists in server. Run id(s): {8943875}
[2018-04-11 21:04:56] Started run 177 on task 3021, dataset 'sick'.
[2018-04-11 21:04:56] Error in run 170: Run already exists in server. Run id(s): {8943873}
[2018-04-11 21:04:56] Started run 178 on task 3021, dataset 'sick'.
[2018-04-11 21:04:57] Error in run 172: Run already exists in server. Run id(s): {8943876}
[2018-04-11 21:04:57] Error in run 171: Run already exists in server. Run id(s): {8943874}
[2018-04-11 21:04:57] Started run 179 on task 3021, dataset 'sick'.
[2018-04-11 21:04:57] Started run 180 on task 3021, dataset 'sick'.
[2018-04-11 21:04:57] Error in run 176: Run already exists in server. Run id(s): {8943880}
[2018-04-11 21:04:58] Error in run 173: Run already exists in server. Run id(s): {8943877}
[2018-04-11 21:04:58] Error in run 174: Run already exists in server. Run id(s): {8943878}
[2018-04-11 21:04:57] Started run 181 on task 3021, dataset 'sick'.
[2018-04-11 21:04:58] Started run 183 on task 3021, dataset 'sick'.
[2018-04-11 21:04:58] Error in run 175: Run already exists in server. Run id(s): {8943879}
[2018-04-11 21:04:58] Started run 184 on task 3021, dataset 'sick'.
[2018-04-11 21:04:58] Started run 182 on task 3021, dataset 'sick'.
[2018-04-11 21:05:01] Error in run 177: Run already exists in server. Run id(s): {8943881}
[2018-04-11 21:05:01] Started run 185 on task 3021, dataset 'sick'.
[2018-04-11 21:05:01] Error in run 178: Run already exists in server. Run id(s): {8943883}
[2018-04-11 21:05:01] Started run 186 on task 3021, dataset 'sick'.
[2018-04-11 21:05:01] Error in run 180: Run already exists in server. Run id(s): {8943884}
[2018-04-11 21:05:01] Started run 187 on task 3021, dataset 'sick'.
[2018-04-11 21:05:01] Error in run 179: Run already exists in server. Run id(s): {8943882}
[2018-04-11 21:05:01] Started run 188 on task 3021, dataset 'sick'.
[2018-04-11 21:05:02] Error in run 181: Run already exists in server. Run id(s): {8943886}
[2018-04-11 21:05:02] Error in run 184: Run already exists in server. Run id(s): {8943887}
[2018-04-11 21:05:02] Error in run 182: Run already exists in server. Run id(s): {8943885}
[2018-04-11 21:05:02] Started run 189 on task 3021, dataset 'sick'.
[2018-04-11 21:05:02] Error in run 183: Run already exists in server. Run id(s): {8943888}
[2018-04-11 21:05:02] Started run 192 on task 3021, dataset 'sick'.
[2018-04-11 21:05:02] Started run 190 on task 3021, dataset 'sick'.
[2018-04-11 21:05:02] Started run 191 on task 3021, dataset 'sick'.
[2018-04-11 21:05:05] Error in run 185: Run already exists in server. Run id(s): {8943889}
[2018-04-11 21:05:05] Started run 193 on task 3021, dataset 'sick'.
[2018-04-11 21:05:05] Error in run 186: Run already exists in server. Run id(s): {8943893}
[2018-04-11 21:05:05] Started run 194 on task 3021, dataset 'sick'.
[2018-04-11 21:05:06] Error in run 188: Run already exists in server. Run id(s): {8943891}
[2018-04-11 21:05:06] Error in run 187: Run already exists in server. Run id(s): {8943890}
[2018-04-11 21:05:06] Started run 195 on task 3021, dataset 'sick'.
[2018-04-11 21:05:06] Started run 196 on task 3021, dataset 'sick'.
[2018-04-11 21:05:07] Error in run 190: Run already exists in server. Run id(s): {8943894}
[2018-04-11 21:05:07] Error in run 192: Run already exists in server. Run id(s): {8943896}
[2018-04-11 21:05:07] Error in run 189: Run already exists in server. Run id(s): {8943892}
[2018-04-11 21:05:07] Error in run 191: Run already exists in server. Run id(s): {8943895}
[2018-04-11 21:05:07] Started run 197 on task 3021, dataset 'sick'.
[2018-04-11 21:05:07] Started run 200 on task 3021, dataset 'sick'.
[2018-04-11 21:05:07] Started run 199 on task 3021, dataset 'sick'.
[2018-04-11 21:05:07] Started run 198 on task 3021, dataset 'sick'.
[2018-04-11 21:05:10] Error in run 194: Run already exists in server. Run id(s): {8943898}
[2018-04-11 21:05:10] Error in run 193: Run already exists in server. Run id(s): {8943897}
[2018-04-11 21:05:10] Started run 201 on task 3021, dataset 'sick'.
[2018-04-11 21:05:10] Started run 202 on task 3021, dataset 'sick'.
[2018-04-11 21:05:11] Error in run 196: Run already exists in server. Run id(s): {8943902}
[2018-04-11 21:05:11] Error in run 195: Run already exists in server. Run id(s): {8943900}
[2018-04-11 21:05:11] Started run 203 on task 3021, dataset 'sick'.
[2018-04-11 21:05:11] Started run 204 on task 3021, dataset 'sick'.
[2018-04-11 21:05:12] Error in run 197: Run already exists in server. Run id(s): {8943899}
[2018-04-11 21:05:12] Started run 205 on task 3021, dataset 'sick'.
[2018-04-11 21:05:12] Error in run 198: Run already exists in server. Run id(s): {8943901}
[2018-04-11 21:05:12] Error in run 199: Run already exists in server. Run id(s): {8943903}
[2018-04-11 21:05:12] Error in run 200: Run already exists in server. Run id(s): {8943904}
[2018-04-11 21:05:12] Started run 206 on task 3021, dataset 'sick'.
[2018-04-11 21:05:12] Started run 207 on task 3021, dataset 'sick'.
[2018-04-11 21:05:12] Started run 208 on task 3021, dataset 'sick'.
[2018-04-11 21:05:15] Error in run 201: Run already exists in server. Run id(s): {8943906}
[2018-04-11 21:05:15] Error in run 202: Run already exists in server. Run id(s): {8943905}
[2018-04-11 21:05:15] Started run 209 on task 3021, dataset 'sick'.
[2018-04-11 21:05:15] Started run 210 on task 3021, dataset 'sick'.
[2018-04-11 21:05:16] Error in run 203: Run already exists in server. Run id(s): {8943907}
[2018-04-11 21:05:16] Started run 211 on task 3021, dataset 'sick'.
[2018-04-11 21:05:16] Error in run 204: Run already exists in server. Run id(s): {8943908}
[2018-04-11 21:05:16] Started run 212 on task 3021, dataset 'sick'.
[2018-04-11 21:05:16] Error in run 205: Run already exists in server. Run id(s): {8943909}
[2018-04-11 21:05:16] Started run 213 on task 3021, dataset 'sick'.
[2018-04-11 21:05:17] Error in run 208: Run already exists in server. Run id(s): {8943913}
[2018-04-11 21:05:17] Error in run 206: Run already exists in server. Run id(s): {8943912}
[2018-04-11 21:05:17] Error in run 207: Run already exists in server. Run id(s): {8943910}
[2018-04-11 21:05:17] Started run 214 on task 3021, dataset 'sick'.
[2018-04-11 21:05:17] Started run 215 on task 3021, dataset 'sick'.
[2018-04-11 21:05:17] Started run 216 on task 3021, dataset 'sick'.
[2018-04-11 21:05:20] Error in run 209: Run already exists in server. Run id(s): {8943911}
[2018-04-11 21:05:20] Error in run 210: Run already exists in server. Run id(s): {8943914}
[2018-04-11 21:05:20] Started run 217 on task 3021, dataset 'sick'.
[2018-04-11 21:05:20] Started run 218 on task 3021, dataset 'sick'.
[2018-04-11 21:05:20] Error in run 211: Run already exists in server. Run id(s): {8943917}
[2018-04-11 21:05:20] Started run 219 on task 3021, dataset 'sick'.
[2018-04-11 21:05:20] Error in run 212: Run already exists in server. Run id(s): {8943915}
[2018-04-11 21:05:20] Started run 220 on task 3021, dataset 'sick'.
[2018-04-11 21:05:21] Error in run 213: Run already exists in server. Run id(s): {8943916}
[2018-04-11 21:05:21] Started run 221 on task 3021, dataset 'sick'.
[2018-04-11 21:05:21] Error in run 216: Run already exists in server. Run id(s): {8943920}
[2018-04-11 21:05:21] Error in run 215: Run already exists in server. Run id(s): {8943919}
[2018-04-11 21:05:21] Started run 222 on task 3021, dataset 'sick'.
[2018-04-11 21:05:21] Error in run 214: Run already exists in server. Run id(s): {8943918}
[2018-04-11 21:05:21] Started run 224 on task 3021, dataset 'sick'.
[2018-04-11 21:05:21] Started run 223 on task 3021, dataset 'sick'.
[2018-04-11 21:05:24] Error in run 218: Run already exists in server. Run id(s): {8943922}
[2018-04-11 21:05:24] Started run 225 on task 3021, dataset 'sick'.
[2018-04-11 21:05:24] Error in run 217: Run already exists in server. Run id(s): {8943921}
[2018-04-11 21:05:24] Started run 226 on task 3021, dataset 'sick'.
[2018-04-11 21:05:25] Error in run 219: Run already exists in server. Run id(s): {8943923}
[2018-04-11 21:05:25] Error in run 221: Run already exists in server. Run id(s): {8943925}
[2018-04-11 21:05:25] Error in run 220: Run already exists in server. Run id(s): {8943924}
[2018-04-11 21:05:25] Started run 227 on task 3021, dataset 'sick'.
[2018-04-11 21:05:25] Started run 228 on task 3021, dataset 'sick'.
[2018-04-11 21:05:25] Started run 229 on task 3021, dataset 'sick'.
[2018-04-11 21:05:26] Error in run 223: Run already exists in server. Run id(s): {8943927}
[2018-04-11 21:05:26] Error in run 224: Run already exists in server. Run id(s): {8943928}
[2018-04-11 21:05:26] Started run 230 on task 3021, dataset 'sick'.
[2018-04-11 21:05:26] Error in run 222: Run already exists in server. Run id(s): {8943926}
[2018-04-11 21:05:26] Started run 231 on task 3021, dataset 'sick'.
[2018-04-11 21:05:26] Started run 232 on task 3021, dataset 'sick'.
[2018-04-11 21:05:29] Error in run 226: Run already exists in server. Run id(s): {8943930}
[2018-04-11 21:05:29] Error in run 225: Run already exists in server. Run id(s): {8943929}
[2018-04-11 21:05:29] Started run 233 on task 3021, dataset 'sick'.
[2018-04-11 21:05:29] Started run 234 on task 3021, dataset 'sick'.
[2018-04-11 21:05:30] Error in run 229: Run already exists in server. Run id(s): {8943932}
[2018-04-11 21:05:30] Error in run 228: Run already exists in server. Run id(s): {8943934}
[2018-04-11 21:05:30] Started run 235 on task 3021, dataset 'sick'.
[2018-04-11 21:05:30] Error in run 227: Run already exists in server. Run id(s): {8943931}
[2018-04-11 21:05:30] Started run 236 on task 3021, dataset 'sick'.
[2018-04-11 21:05:30] Started run 237 on task 3021, dataset 'sick'.
[2018-04-11 21:05:31] Error in run 230: Run already exists in server. Run id(s): {8943933}
[2018-04-11 21:05:31] Started run 238 on task 3021, dataset 'sick'.
[2018-04-11 21:05:31] Error in run 232: Run already exists in server. Run id(s): {8943936}
[2018-04-11 21:05:31] Error in run 231: Run already exists in server. Run id(s): {8943935}
[2018-04-11 21:05:31] Started run 239 on task 3021, dataset 'sick'.
[2018-04-11 21:05:31] Started run 240 on task 3021, dataset 'sick'.
[2018-04-11 21:05:34] Error in run 233: Run already exists in server. Run id(s): {8943937}
[2018-04-11 21:05:34] Started run 241 on task 3021, dataset 'sick'.
[2018-04-11 21:05:34] Error in run 234: Run already exists in server. Run id(s): {8943939}
[2018-04-11 21:05:34] Started run 242 on task 3021, dataset 'sick'.
[2018-04-11 21:05:35] Error in run 236: Run already exists in server. Run id(s): {8943940}
[2018-04-11 21:05:35] Started run 243 on task 3021, dataset 'sick'.
[2018-04-11 21:05:35] Error in run 235: Run already exists in server. Run id(s): {8943938}
[2018-04-11 21:05:35] Started run 244 on task 3021, dataset 'sick'.
[2018-04-11 21:05:35] Error in run 237: Run already exists in server. Run id(s): {8943941}
[2018-04-11 21:05:35] Started run 245 on task 3021, dataset 'sick'.
[2018-04-11 21:05:36] Error in run 238: Run already exists in server. Run id(s): {8943942}
[2018-04-11 21:05:36] Error in run 239: Run already exists in server. Run id(s): {8943943}
[2018-04-11 21:05:36] Error in run 240: Run already exists in server. Run id(s): {8943944}
[2018-04-11 21:05:36] Started run 246 on task 3021, dataset 'sick'.
[2018-04-11 21:05:36] Started run 248 on task 3021, dataset 'sick'.
[2018-04-11 21:05:36] Started run 247 on task 3021, dataset 'sick'.
[2018-04-11 21:05:39] Error in run 242: Run already exists in server. Run id(s): {8943948}
[2018-04-11 21:05:39] Error in run 241: Run already exists in server. Run id(s): {8943945}
[2018-04-11 21:05:39] Started run 249 on task 3021, dataset 'sick'.
[2018-04-11 21:05:39] Started run 250 on task 3021, dataset 'sick'.
[2018-04-11 21:05:39] Error in run 243: Run already exists in server. Run id(s): {8943946}
[2018-04-11 21:05:39] Started run 251 on task 3021, dataset 'sick'.
[2018-04-11 21:05:40] Error in run 245: Run already exists in server. Run id(s): {8943949}
[2018-04-11 21:05:40] Error in run 244: Run already exists in server. Run id(s): {8943947}
[2018-04-11 21:05:40] Started run 252 on task 3021, dataset 'sick'.
[2018-04-11 21:05:40] Started run 253 on task 3021, dataset 'sick'.
[2018-04-11 21:05:40] Error in run 247: Run already exists in server. Run id(s): {8943952}
[2018-04-11 21:05:40] Error in run 246: Run already exists in server. Run id(s): {8943950}
[2018-04-11 21:05:40] Started run 254 on task 3021, dataset 'sick'.
[2018-04-11 21:05:40] Error in run 248: Run already exists in server. Run id(s): {8943951}
[2018-04-11 21:05:40] Started run 255 on task 3021, dataset 'sick'.
[2018-04-11 21:05:40] Started run 256 on task 3021, dataset 'sick'.
[2018-04-11 21:05:43] Error in run 249: Run already exists in server. Run id(s): {8943953}
[2018-04-11 21:05:43] Error in run 250: Run already exists in server. Run id(s): {8943954}
[2018-04-11 21:05:43] Started run 257 on task 3021, dataset 'sick'.
[2018-04-11 21:05:43] Started run 258 on task 3021, dataset 'sick'.
[2018-04-11 21:05:44] Error in run 252: Run already exists in server. Run id(s): {8943956}
[2018-04-11 21:05:44] Error in run 253: Run already exists in server. Run id(s): {8943957}
[2018-04-11 21:05:44] Started run 259 on task 3021, dataset 'sick'.
[2018-04-11 21:05:44] Error in run 251: Run already exists in server. Run id(s): {8943955}
[2018-04-11 21:05:44] Started run 260 on task 3021, dataset 'sick'.
[2018-04-11 21:05:44] Started run 261 on task 3021, dataset 'sick'.
[2018-04-11 21:05:45] Error in run 256: Run already exists in server. Run id(s): {8943960}
[2018-04-11 21:05:45] Error in run 255: Run already exists in server. Run id(s): {8943959}
[2018-04-11 21:05:45] Started run 262 on task 3021, dataset 'sick'.
[2018-04-11 21:05:45] Error in run 254: Run already exists in server. Run id(s): {8943958}
[2018-04-11 21:05:45] Started run 264 on task 3021, dataset 'sick'.
[2018-04-11 21:05:45] Started run 263 on task 3021, dataset 'sick'.
[2018-04-11 21:05:48] Error in run 257: Run already exists in server. Run id(s): {8943961}
[2018-04-11 21:05:48] Error in run 258: Run already exists in server. Run id(s): {8943962}
[2018-04-11 21:05:48] Started run 265 on task 3021, dataset 'sick'.
[2018-04-11 21:05:48] Started run 266 on task 3021, dataset 'sick'.
[2018-04-11 21:05:49] Error in run 261: Run already exists in server. Run id(s): {8943966}
[2018-04-11 21:05:49] Error in run 259: Run already exists in server. Run id(s): {8943963}
[2018-04-11 21:05:49] Started run 267 on task 3021, dataset 'sick'.
[2018-04-11 21:05:49] Error in run 260: Run already exists in server. Run id(s): {8943964}
[2018-04-11 21:05:49] Started run 269 on task 3021, dataset 'sick'.
[2018-04-11 21:05:49] Started run 268 on task 3021, dataset 'sick'.
[2018-04-11 21:05:50] Error in run 264: Run already exists in server. Run id(s): {8943968}
[2018-04-11 21:05:50] Started run 270 on task 3021, dataset 'sick'.
[2018-04-11 21:05:50] Error in run 263: Run already exists in server. Run id(s): {8943967}
[2018-04-11 21:05:50] Error in run 262: Run already exists in server. Run id(s): {8943965}
[2018-04-11 21:05:50] Started run 271 on task 3021, dataset 'sick'.
[2018-04-11 21:05:50] Started run 272 on task 3021, dataset 'sick'.
[2018-04-11 21:05:53] Error in run 266: Run already exists in server. Run id(s): {8943969}
[2018-04-11 21:05:53] Started run 273 on task 3021, dataset 'sick'.
[2018-04-11 21:05:53] Error in run 265: Run already exists in server. Run id(s): {8943970}
[2018-04-11 21:05:53] Started run 274 on task 3021, dataset 'sick'.
[2018-04-11 21:05:54] Error in run 269: Run already exists in server. Run id(s): {8943973}
[2018-04-11 21:05:54] Error in run 268: Run already exists in server. Run id(s): {8943972}
[2018-04-11 21:05:54] Started run 275 on task 3021, dataset 'sick'.
[2018-04-11 21:05:54] Error in run 267: Run already exists in server. Run id(s): {8943971}
[2018-04-11 21:05:54] Started run 276 on task 3021, dataset 'sick'.
[2018-04-11 21:05:54] Started run 277 on task 3021, dataset 'sick'.
[2018-04-11 21:05:55] Error in run 272: Run already exists in server. Run id(s): {8943976}
[2018-04-11 21:05:55] Error in run 270: Run already exists in server. Run id(s): {8943974}
[2018-04-11 21:05:55] Error in run 271: Run already exists in server. Run id(s): {8943975}
[2018-04-11 21:05:55] Started run 278 on task 3021, dataset 'sick'.
[2018-04-11 21:05:55] Started run 280 on task 3021, dataset 'sick'.
[2018-04-11 21:05:55] Started run 279 on task 3021, dataset 'sick'.
[2018-04-11 21:05:58] Error in run 274: Run already exists in server. Run id(s): {8943978}
[2018-04-11 21:05:58] Started run 281 on task 3021, dataset 'sick'.
[2018-04-11 21:05:58] Error in run 273: Run already exists in server. Run id(s): {8943977}
[2018-04-11 21:05:58] Started run 282 on task 3021, dataset 'sick'.
[2018-04-11 21:05:59] Error in run 275: Run already exists in server. Run id(s): {8943979}
[2018-04-11 21:05:59] Error in run 277: Run already exists in server. Run id(s): {8943981}
[2018-04-11 21:05:59] Started run 283 on task 3021, dataset 'sick'.
[2018-04-11 21:05:59] Started run 284 on task 3021, dataset 'sick'.
[2018-04-11 21:05:59] Error in run 276: Run already exists in server. Run id(s): {8943980}
[2018-04-11 21:05:59] Started run 285 on task 3021, dataset 'sick'.
[2018-04-11 21:05:59] Error in run 278: Run already exists in server. Run id(s): {8943982}
[2018-04-11 21:05:59] Started run 286 on task 3021, dataset 'sick'.
[2018-04-11 21:05:59] Error in run 280: Run already exists in server. Run id(s): {8943984}
[2018-04-11 21:05:59] Error in run 279: Run already exists in server. Run id(s): {8943983}
[2018-04-11 21:05:59] Started run 287 on task 3021, dataset 'sick'.
[2018-04-11 21:05:59] Started run 288 on task 3021, dataset 'sick'.
[2018-04-11 21:06:03] Error in run 282: Run already exists in server. Run id(s): {8943986}
[2018-04-11 21:06:03] Started run 289 on task 3021, dataset 'sick'.
[2018-04-11 21:06:03] Error in run 281: Run already exists in server. Run id(s): {8943985}
[2018-04-11 21:06:03] Started run 290 on task 3021, dataset 'sick'.
[2018-04-11 21:06:04] Error in run 284: Run already exists in server. Run id(s): {8943987}
[2018-04-11 21:06:04] Error in run 283: Run already exists in server. Run id(s): {8943989}
[2018-04-11 21:06:04] Error in run 285: Run already exists in server. Run id(s): {8943988}
[2018-04-11 21:06:04] Started run 291 on task 3021, dataset 'sick'.
[2018-04-11 21:06:04] Started run 292 on task 3021, dataset 'sick'.
[2018-04-11 21:06:04] Started run 293 on task 3021, dataset 'sick'.
[2018-04-11 21:06:04] Error in run 288: Run already exists in server. Run id(s): {8943992}
[2018-04-11 21:06:04] Started run 294 on task 3021, dataset 'sick'.
[2018-04-11 21:06:04] Error in run 286: Run already exists in server. Run id(s): {8943991}
[2018-04-11 21:06:04] Error in run 287: Run already exists in server. Run id(s): {8943990}
[2018-04-11 21:06:04] Started run 295 on task 3021, dataset 'sick'.
[2018-04-11 21:06:04] Started run 296 on task 3021, dataset 'sick'.
[2018-04-11 21:06:07] Error in run 289: Run already exists in server. Run id(s): {9014544, 8943993}
[2018-04-11 21:06:07] Error in run 290: Run already exists in server. Run id(s): {8943995}
[2018-04-11 21:06:07] Started run 297 on task 3021, dataset 'sick'.
[2018-04-11 21:06:07] Started run 298 on task 3021, dataset 'sick'.
[2018-04-11 21:06:08] Error in run 291: Run already exists in server. Run id(s): {8943994}
[2018-04-11 21:06:08] Error in run 292: Run already exists in server. Run id(s): {8943996}
[2018-04-11 21:06:08] Started run 299 on task 3021, dataset 'sick'.
[2018-04-11 21:06:08] Error in run 293: Run already exists in server. Run id(s): {8943997}
[2018-04-11 21:06:08] Started run 300 on task 3021, dataset 'sick'.
[2018-04-11 21:06:08] Started run 301 on task 3021, dataset 'sick'.
[2018-04-11 21:06:09] Error in run 294: Run already exists in server. Run id(s): {8943998}
[2018-04-11 21:06:09] Started run 302 on task 3021, dataset 'sick'.
[2018-04-11 21:06:09] Error in run 295: Run already exists in server. Run id(s): {8944000}
[2018-04-11 21:06:09] Started run 303 on task 3021, dataset 'sick'.
[2018-04-11 21:06:09] Error in run 296: Run already exists in server. Run id(s): {8943999}
[2018-04-11 21:06:09] Started run 304 on task 3021, dataset 'sick'.
[2018-04-11 21:06:12] Error in run 297: Run already exists in server. Run id(s): {8944002}
[2018-04-11 21:06:12] Started run 305 on task 3021, dataset 'sick'.
[2018-04-11 21:06:12] Error in run 298: Run already exists in server. Run id(s): {8944001}
[2018-04-11 21:06:12] Started run 306 on task 3021, dataset 'sick'.
[2018-04-11 21:06:13] Error in run 301: Run already exists in server. Run id(s): {8944006}
[2018-04-11 21:06:13] Error in run 299: Run already exists in server. Run id(s): {8944003}
[2018-04-11 21:06:13] Error in run 300: Run already exists in server. Run id(s): {8944004}
[2018-04-11 21:06:13] Started run 307 on task 3021, dataset 'sick'.
[2018-04-11 21:06:13] Started run 308 on task 3021, dataset 'sick'.
[2018-04-11 21:06:13] Started run 309 on task 3021, dataset 'sick'.
[2018-04-11 21:06:14] Error in run 303: Run already exists in server. Run id(s): {8944007}
[2018-04-11 21:06:14] Error in run 304: Run already exists in server. Run id(s): {8944008}
[2018-04-11 21:06:14] Error in run 302: Run already exists in server. Run id(s): {8944005}
[2018-04-11 21:06:14] Started run 310 on task 3021, dataset 'sick'.
[2018-04-11 21:06:14] Started run 311 on task 3021, dataset 'sick'.
[2018-04-11 21:06:14] Started run 312 on task 3021, dataset 'sick'.
[2018-04-11 21:06:17] Error in run 306: Run already exists in server. Run id(s): {8944010}
[2018-04-11 21:06:17] Error in run 305: Run already exists in server. Run id(s): {8944009}
[2018-04-11 21:06:17] Started run 313 on task 3021, dataset 'sick'.
[2018-04-11 21:06:17] Started run 314 on task 3021, dataset 'sick'.
[2018-04-11 21:06:18] Error in run 307: Run already exists in server. Run id(s): {8944011}
[2018-04-11 21:06:18] Started run 315 on task 3021, dataset 'sick'.
[2018-04-11 21:06:18] Error in run 308: Run already exists in server. Run id(s): {8944012}
[2018-04-11 21:06:18] Error in run 309: Run already exists in server. Run id(s): {8944013}
[2018-04-11 21:06:18] Started run 316 on task 3021, dataset 'sick'.
[2018-04-11 21:06:18] Started run 317 on task 3021, dataset 'sick'.
[2018-04-11 21:06:18] Error in run 311: Run already exists in server. Run id(s): {8944015}
[2018-04-11 21:06:18] Error in run 312: Run already exists in server. Run id(s): {8944016}
[2018-04-11 21:06:18] Error in run 310: Run already exists in server. Run id(s): {8944014}
[2018-04-11 21:06:18] Started run 318 on task 3021, dataset 'sick'.
[2018-04-11 21:06:18] Started run 319 on task 3021, dataset 'sick'.
[2018-04-11 21:06:18] Started run 320 on task 3021, dataset 'sick'.
[2018-04-11 21:06:22] Error in run 313: Run already exists in server. Run id(s): {8944017}
[2018-04-11 21:06:22] Error in run 314: Run already exists in server. Run id(s): {8944018}
[2018-04-11 21:06:22] Started run 321 on task 3021, dataset 'sick'.
[2018-04-11 21:06:22] Started run 322 on task 3021, dataset 'sick'.
[2018-04-11 21:06:22] Error in run 315: Run already exists in server. Run id(s): {8944019}
[2018-04-11 21:06:22] Error in run 316: Run already exists in server. Run id(s): {8944020}
[2018-04-11 21:06:22] Error in run 317: Run already exists in server. Run id(s): {8944021}
[2018-04-11 21:06:22] Started run 323 on task 3021, dataset 'sick'.
[2018-04-11 21:06:22] Started run 324 on task 3021, dataset 'sick'.
[2018-04-11 21:06:22] Started run 325 on task 3021, dataset 'sick'.
[2018-04-11 21:06:23] Error in run 320: Run already exists in server. Run id(s): {8944024}
[2018-04-11 21:06:23] Error in run 318: Run already exists in server. Run id(s): {8944022}
[2018-04-11 21:06:23] Started run 326 on task 3021, dataset 'sick'.
[2018-04-11 21:06:23] Error in run 319: Run already exists in server. Run id(s): {8944023}
[2018-04-11 21:06:23] Started run 327 on task 3021, dataset 'sick'.
[2018-04-11 21:06:23] Started run 328 on task 3021, dataset 'sick'.
[2018-04-11 21:06:26] Error in run 321: Run already exists in server. Run id(s): {8944025}
[2018-04-11 21:06:26] Started run 329 on task 3021, dataset 'sick'.
[2018-04-11 21:06:26] Error in run 322: Run already exists in server. Run id(s): {8944026}
[2018-04-11 21:06:26] Started run 330 on task 3021, dataset 'sick'.
[2018-04-11 21:06:27] Error in run 325: Run already exists in server. Run id(s): {8944029}
[2018-04-11 21:06:27] Error in run 324: Run already exists in server. Run id(s): {8944028}
[2018-04-11 21:06:27] Started run 331 on task 3021, dataset 'sick'.
[2018-04-11 21:06:27] Error in run 323: Run already exists in server. Run id(s): {8944027}
[2018-04-11 21:06:27] Started run 332 on task 3021, dataset 'sick'.
[2018-04-11 21:06:27] Started run 333 on task 3021, dataset 'sick'.
[2018-04-11 21:06:28] Error in run 327: Run already exists in server. Run id(s): {8944030}
[2018-04-11 21:06:28] Error in run 326: Run already exists in server. Run id(s): {8944031}
[2018-04-11 21:06:28] Started run 334 on task 3021, dataset 'sick'.
[2018-04-11 21:06:28] Error in run 328: Run already exists in server. Run id(s): {8944032}
[2018-04-11 21:06:28] Started run 335 on task 3021, dataset 'sick'.
[2018-04-11 21:06:28] Started run 336 on task 3021, dataset 'sick'.
[2018-04-11 21:06:31] Error in run 330: Run already exists in server. Run id(s): {8944035}
[2018-04-11 21:06:31] Error in run 329: Run already exists in server. Run id(s): {8944033}
[2018-04-11 21:06:31] Started run 337 on task 3021, dataset 'sick'.
[2018-04-11 21:06:31] Started run 338 on task 3021, dataset 'sick'.
[2018-04-11 21:06:32] Error in run 333: Run already exists in server. Run id(s): {8944039}
[2018-04-11 21:06:32] Error in run 332: Run already exists in server. Run id(s): {8944036}
[2018-04-11 21:06:32] Started run 339 on task 3021, dataset 'sick'.
[2018-04-11 21:06:32] Error in run 331: Run already exists in server. Run id(s): {8944034}
[2018-04-11 21:06:32] Started run 340 on task 3021, dataset 'sick'.
[2018-04-11 21:06:32] Started run 341 on task 3021, dataset 'sick'.
[2018-04-11 21:06:33] Error in run 335: Run already exists in server. Run id(s): {8944038}
[2018-04-11 21:06:33] Error in run 334: Run already exists in server. Run id(s): {8944037}
[2018-04-11 21:06:33] Error in run 336: Run already exists in server. Run id(s): {8944040}
[2018-04-11 21:06:33] Started run 342 on task 3021, dataset 'sick'.
[2018-04-11 21:06:33] Started run 343 on task 3021, dataset 'sick'.
[2018-04-11 21:06:33] Started run 344 on task 3021, dataset 'sick'.
[2018-04-11 21:06:36] Error in run 337: Run already exists in server. Run id(s): {8944042}
[2018-04-11 21:06:36] Error in run 338: Run already exists in server. Run id(s): {8944041}
[2018-04-11 21:06:36] Started run 345 on task 3021, dataset 'sick'.
[2018-04-11 21:06:36] Started run 346 on task 3021, dataset 'sick'.
[2018-04-11 21:06:37] Error in run 340: Run already exists in server. Run id(s): {8944044}
[2018-04-11 21:06:37] Error in run 339: Run already exists in server. Run id(s): {8944043}
[2018-04-11 21:06:37] Error in run 341: Run already exists in server. Run id(s): {8944047}
[2018-04-11 21:06:37] Started run 347 on task 3021, dataset 'sick'.
[2018-04-11 21:06:37] Started run 348 on task 3021, dataset 'sick'.
[2018-04-11 21:06:37] Started run 349 on task 3021, dataset 'sick'.
[2018-04-11 21:06:37] Error in run 344: Run already exists in server. Run id(s): {8944049}
[2018-04-11 21:06:37] Started run 350 on task 3021, dataset 'sick'.
[2018-04-11 21:06:37] Error in run 342: Run already exists in server. Run id(s): {8944045}
[2018-04-11 21:06:37] Started run 351 on task 3021, dataset 'sick'.
[2018-04-11 21:06:37] Error in run 343: Run already exists in server. Run id(s): {8944046}
[2018-04-11 21:06:37] Started run 352 on task 3021, dataset 'sick'.
[2018-04-11 21:06:41] Error in run 345: Run already exists in server. Run id(s): {8944048}
[2018-04-11 21:06:41] Error in run 346: Run already exists in server. Run id(s): {8944051}
[2018-04-11 21:06:41] Started run 353 on task 3021, dataset 'sick'.
[2018-04-11 21:06:41] Started run 354 on task 3021, dataset 'sick'.
[2018-04-11 21:06:41] Error in run 347: Run already exists in server. Run id(s): {8944050}
[2018-04-11 21:06:41] Started run 355 on task 3021, dataset 'sick'.
[2018-04-11 21:06:41] Error in run 348: Run already exists in server. Run id(s): {8944052}
[2018-04-11 21:06:41] Started run 356 on task 3021, dataset 'sick'.
[2018-04-11 21:06:41] Error in run 349: Run already exists in server. Run id(s): {9014866, 8944053}
[2018-04-11 21:06:41] Started run 357 on task 3021, dataset 'sick'.
[2018-04-11 21:06:42] Error in run 351: Run already exists in server. Run id(s): {8944055}
[2018-04-11 21:06:42] Error in run 350: Run already exists in server. Run id(s): {8944054}
[2018-04-11 21:06:42] Error in run 352: Run already exists in server. Run id(s): {8944056}
[2018-04-11 21:06:42] Started run 358 on task 3021, dataset 'sick'.
[2018-04-11 21:06:42] Started run 359 on task 3021, dataset 'sick'.
[2018-04-11 21:06:42] Started run 360 on task 3021, dataset 'sick'.
[2018-04-11 21:06:45] Error in run 353: Run already exists in server. Run id(s): {8944057}
[2018-04-11 21:06:45] Started run 361 on task 3021, dataset 'sick'.
[2018-04-11 21:06:45] Error in run 354: Run already exists in server. Run id(s): {8944058}
[2018-04-11 21:06:45] Started run 362 on task 3021, dataset 'sick'.
[2018-04-11 21:06:46] Error in run 355: Run already exists in server. Run id(s): {8944060}
[2018-04-11 21:06:46] Started run 363 on task 3021, dataset 'sick'.
[2018-04-11 21:06:46] Error in run 357: Run already exists in server. Run id(s): {8944061}
[2018-04-11 21:06:46] Started run 364 on task 3021, dataset 'sick'.
[2018-04-11 21:06:46] Error in run 356: Run already exists in server. Run id(s): {8944059}
[2018-04-11 21:06:46] Started run 365 on task 3021, dataset 'sick'.
[2018-04-11 21:06:47] Error in run 358: Run already exists in server. Run id(s): {8944062}
[2018-04-11 21:06:47] Started run 366 on task 3021, dataset 'sick'.
[2018-04-11 21:06:47] Error in run 359: Run already exists in server. Run id(s): {8944064}
[2018-04-11 21:06:47] Error in run 360: Run already exists in server. Run id(s): {8944063}
[2018-04-11 21:06:47] Started run 367 on task 3021, dataset 'sick'.
[2018-04-11 21:06:47] Started run 368 on task 3021, dataset 'sick'.
[2018-04-11 21:06:50] Error in run 361: Run already exists in server. Run id(s): {8944065}
[2018-04-11 21:06:50] Started run 369 on task 3021, dataset 'sick'.
[2018-04-11 21:06:50] Error in run 362: Run already exists in server. Run id(s): {8944066}
[2018-04-11 21:06:50] Started run 370 on task 3021, dataset 'sick'.
[2018-04-11 21:06:50] Error in run 363: Run already exists in server. Run id(s): {8944070}
[2018-04-11 21:06:50] Started run 371 on task 3021, dataset 'sick'.
[2018-04-11 21:06:51] Error in run 364: Run already exists in server. Run id(s): {8944067}
[2018-04-11 21:06:51] Started run 372 on task 3021, dataset 'sick'.
[2018-04-11 21:06:51] Error in run 365: Run already exists in server. Run id(s): {8944068}
[2018-04-11 21:06:51] Started run 373 on task 3021, dataset 'sick'.
[2018-04-11 21:06:52] Error in run 367: Run already exists in server. Run id(s): {8944071}
[2018-04-11 21:06:52] Error in run 366: Run already exists in server. Run id(s): {8944069}
[2018-04-11 21:06:52] Started run 374 on task 3021, dataset 'sick'.
[2018-04-11 21:06:52] Error in run 368: Run already exists in server. Run id(s): {8944072}
[2018-04-11 21:06:52] Started run 376 on task 3021, dataset 'sick'.
[2018-04-11 21:06:52] Started run 375 on task 3021, dataset 'sick'.
[2018-04-11 21:06:55] Error in run 371: Run already exists in server. Run id(s): {8944075}
[2018-04-11 21:06:55] Started run 377 on task 3021, dataset 'sick'.
[2018-04-11 21:06:55] Error in run 370: Run already exists in server. Run id(s): {8944074}
[2018-04-11 21:06:55] Started run 378 on task 3021, dataset 'sick'.
[2018-04-11 21:06:55] Error in run 369: Run already exists in server. Run id(s): {8944073}
[2018-04-11 21:06:55] Started run 379 on task 3021, dataset 'sick'.
[2018-04-11 21:06:55] Error in run 372: Run already exists in server. Run id(s): {8944076}
[2018-04-11 21:06:55] Started run 380 on task 3021, dataset 'sick'.
[2018-04-11 21:06:56] Error in run 373: Run already exists in server. Run id(s): {8944077}
[2018-04-11 21:06:56] Started run 381 on task 3021, dataset 'sick'.
[2018-04-11 21:06:56] Error in run 375: Run already exists in server. Run id(s): {8944079}
[2018-04-11 21:06:56] Started run 382 on task 3021, dataset 'sick'.
[2018-04-11 21:06:56] Error in run 374: Run already exists in server. Run id(s): {8944078}
[2018-04-11 21:06:56] Error in run 376: Run already exists in server. Run id(s): {8944080}
[2018-04-11 21:06:56] Started run 383 on task 3021, dataset 'sick'.
[2018-04-11 21:06:56] Started run 384 on task 3021, dataset 'sick'.
[2018-04-11 21:07:00] Error in run 377: Run already exists in server. Run id(s): {8944081}
[2018-04-11 21:07:00] Error in run 378: Run already exists in server. Run id(s): {8944082}
[2018-04-11 21:07:00] Error in run 380: Run already exists in server. Run id(s): {8944084}
[2018-04-11 21:07:00] Error in run 379: Run already exists in server. Run id(s): {8944083}
[2018-04-11 21:07:00] Started run 385 on task 3021, dataset 'sick'.
[2018-04-11 21:07:00] Started run 386 on task 3021, dataset 'sick'.
[2018-04-11 21:07:00] Started run 387 on task 3021, dataset 'sick'.
[2018-04-11 21:07:00] Started run 388 on task 3021, dataset 'sick'.
[2018-04-11 21:07:00] Error in run 381: Run already exists in server. Run id(s): {8944087}
[2018-04-11 21:07:00] Started run 389 on task 3021, dataset 'sick'.
[2018-04-11 21:07:01] Error in run 383: Run already exists in server. Run id(s): {8944086}
[2018-04-11 21:07:01] Error in run 382: Run already exists in server. Run id(s): {8944085}
[2018-04-11 21:07:01] Error in run 384: Run already exists in server. Run id(s): {8944088}
[2018-04-11 21:07:01] Started run 390 on task 3021, dataset 'sick'.
[2018-04-11 21:07:01] Started run 392 on task 3021, dataset 'sick'.
[2018-04-11 21:07:01] Started run 391 on task 3021, dataset 'sick'.
[2018-04-11 21:07:04] Error in run 387: Run already exists in server. Run id(s): {8944090}
[2018-04-11 21:07:04] Error in run 385: Run already exists in server. Run id(s): {8944091}
[2018-04-11 21:07:04] Error in run 386: Run already exists in server. Run id(s): {8944089}
[2018-04-11 21:07:04] Error in run 388: Run already exists in server. Run id(s): {8944092}
[2018-04-11 21:07:04] Started run 393 on task 3021, dataset 'sick'.
[2018-04-11 21:07:04] Started run 394 on task 3021, dataset 'sick'.
[2018-04-11 21:07:04] Started run 395 on task 3021, dataset 'sick'.
[2018-04-11 21:07:04] Started run 396 on task 3021, dataset 'sick'.
[2018-04-11 21:07:05] Error in run 389: Run already exists in server. Run id(s): {8944094}
[2018-04-11 21:07:05] Started run 397 on task 3021, dataset 'sick'.
[2018-04-11 21:07:06] Error in run 391: Run already exists in server. Run id(s): {8944095}
[2018-04-11 21:07:06] Error in run 390: Run already exists in server. Run id(s): {8944093}
[2018-04-11 21:07:06] Error in run 392: Run already exists in server. Run id(s): {8944096}
[2018-04-11 21:07:06] Started run 398 on task 3021, dataset 'sick'.
[2018-04-11 21:07:06] Started run 399 on task 3021, dataset 'sick'.
[2018-04-11 21:07:06] Started run 400 on task 3021, dataset 'sick'.
[2018-04-11 21:07:09] Error in run 394: Run already exists in server. Run id(s): {8944098}
[2018-04-11 21:07:09] Error in run 395: Run already exists in server. Run id(s): {8944099, 9015035}
[2018-04-11 21:07:09] Error in run 393: Run already exists in server. Run id(s): {8944097}
[2018-04-11 21:07:09] Started run 401 on task 3021, dataset 'sick'.
[2018-04-11 21:07:09] Started run 402 on task 3021, dataset 'sick'.
[2018-04-11 21:07:09] Error in run 396: Run already exists in server. Run id(s): {8944102}
[2018-04-11 21:07:09] Started run 404 on task 3021, dataset 'sick'.
[2018-04-11 21:07:09] Error in run 397: Run already exists in server. Run id(s): {8944100}
[2018-04-11 21:07:09] Started run 405 on task 3021, dataset 'sick'.
[2018-04-11 21:07:09] Started run 403 on task 3021, dataset 'sick'.
[2018-04-11 21:07:11] Error in run 400: Run already exists in server. Run id(s): {8944104}
[2018-04-11 21:07:11] Error in run 398: Run already exists in server. Run id(s): {8944101}
[2018-04-11 21:07:11] Started run 406 on task 3021, dataset 'sick'.
[2018-04-11 21:07:11] Error in run 399: Run already exists in server. Run id(s): {8944103}
[2018-04-11 21:07:11] Started run 407 on task 3021, dataset 'sick'.
[2018-04-11 21:07:11] Started run 408 on task 3021, dataset 'sick'.
[2018-04-11 21:07:14] Error in run 402: Run already exists in server. Run id(s): {8944107}
[2018-04-11 21:07:14] Started run 409 on task 3021, dataset 'sick'.
[2018-04-11 21:07:14] Error in run 405: Run already exists in server. Run id(s): {8944110}
[2018-04-11 21:07:14] Error in run 404: Run already exists in server. Run id(s): {8944108}
[2018-04-11 21:07:14] Error in run 403: Run already exists in server. Run id(s): {8944105}
[2018-04-11 21:07:14] Started run 410 on task 3021, dataset 'sick'.
[2018-04-11 21:07:14] Error in run 401: Run already exists in server. Run id(s): {8944106}
[2018-04-11 21:07:14] Started run 413 on task 3021, dataset 'sick'.
[2018-04-11 21:07:14] Started run 411 on task 3021, dataset 'sick'.
[2018-04-11 21:07:14] Started run 412 on task 3021, dataset 'sick'.
[2018-04-11 21:07:15] Error in run 408: Run already exists in server. Run id(s): {8944112}
[2018-04-11 21:07:15] Started run 414 on task 3021, dataset 'sick'.
[2018-04-11 21:07:15] Error in run 406: Run already exists in server. Run id(s): {8944109}
[2018-04-11 21:07:15] Started run 415 on task 3021, dataset 'sick'.
[2018-04-11 21:07:15] Error in run 407: Run already exists in server. Run id(s): {8944111}
[2018-04-11 21:07:15] Started run 416 on task 3021, dataset 'sick'.
[2018-04-11 21:07:19] Error in run 413: Run already exists in server. Run id(s): {8944117}
[2018-04-11 21:07:19] Error in run 410: Run already exists in server. Run id(s): {8944113}
[2018-04-11 21:07:19] Started run 417 on task 3021, dataset 'sick'.
[2018-04-11 21:07:19] Error in run 409: Run already exists in server. Run id(s): {9014912}
[2018-04-11 21:07:19] Error in run 411: Run already exists in server. Run id(s): {8944116}
[2018-04-11 21:07:19] Error in run 412: Run already exists in server. Run id(s): {8944115}
[2018-04-11 21:07:19] Started run 419 on task 3021, dataset 'sick'.
[2018-04-11 21:07:19] Started run 420 on task 3021, dataset 'sick'.
[2018-04-11 21:07:19] Started run 421 on task 3021, dataset 'sick'.
[2018-04-11 21:07:19] Started run 418 on task 3021, dataset 'sick'.
[2018-04-11 21:07:20] Error in run 414: Run already exists in server. Run id(s): {8944118}
[2018-04-11 21:07:20] Error in run 416: Run already exists in server. Run id(s): {8944119}
[2018-04-11 21:07:20] Error in run 415: Run already exists in server. Run id(s): {8944122}
[2018-04-11 21:07:20] Started run 422 on task 3021, dataset 'sick'.
[2018-04-11 21:07:20] Started run 423 on task 3021, dataset 'sick'.
[2018-04-11 21:07:20] Started run 424 on task 3021, dataset 'sick'.
[2018-04-11 21:07:23] Error in run 419: Run already exists in server. Run id(s): {8944123}
[2018-04-11 21:07:23] Error in run 417: Run already exists in server. Run id(s): {8944120}
[2018-04-11 21:07:23] Error in run 420: Run already exists in server. Run id(s): {8944124}
[2018-04-11 21:07:23] Started run 425 on task 3021, dataset 'sick'.
[2018-04-11 21:07:23] Error in run 421: Run already exists in server. Run id(s): {8944126}
[2018-04-11 21:07:23] Error in run 418: Run already exists in server. Run id(s): {8944121}
[2018-04-11 21:07:23] Started run 427 on task 3021, dataset 'sick'.
[2018-04-11 21:07:23] Started run 428 on task 3021, dataset 'sick'.
[2018-04-11 21:07:23] Started run 426 on task 3021, dataset 'sick'.
[2018-04-11 21:07:23] Started run 429 on task 3021, dataset 'sick'.
[2018-04-11 21:07:25] Error in run 422: Run already exists in server. Run id(s): {8944125}
[2018-04-11 21:07:25] Error in run 423: Run already exists in server. Run id(s): {8944127}
[2018-04-11 21:07:25] Started run 430 on task 3021, dataset 'sick'.
[2018-04-11 21:07:25] Error in run 424: Run already exists in server. Run id(s): {8944128}
[2018-04-11 21:07:25] Started run 431 on task 3021, dataset 'sick'.
[2018-04-11 21:07:25] Started run 432 on task 3021, dataset 'sick'.
[2018-04-11 21:07:28] Error in run 426: Run already exists in server. Run id(s): {8944129}
[2018-04-11 21:07:28] Error in run 428: Run already exists in server. Run id(s): {8944132}
[2018-04-11 21:07:28] Error in run 425: Run already exists in server. Run id(s): {8944131}
[2018-04-11 21:07:28] Started run 433 on task 3021, dataset 'sick'.
[2018-04-11 21:07:28] Error in run 427: Run already exists in server. Run id(s): {8944130}
[2018-04-11 21:07:28] Error in run 429: Run already exists in server. Run id(s): {8944133}
[2018-04-11 21:07:28] Started run 434 on task 3021, dataset 'sick'.
[2018-04-11 21:07:28] Started run 435 on task 3021, dataset 'sick'.
[2018-04-11 21:07:28] Started run 436 on task 3021, dataset 'sick'.
[2018-04-11 21:07:28] Started run 437 on task 3021, dataset 'sick'.
[2018-04-11 21:07:30] Error in run 431: Run already exists in server. Run id(s): {8944136}
[2018-04-11 21:07:30] Error in run 432: Run already exists in server. Run id(s): {8944135}
[2018-04-11 21:07:30] Error in run 430: Run already exists in server. Run id(s): {8944134}
[2018-04-11 21:07:30] Started run 438 on task 3021, dataset 'sick'.
[2018-04-11 21:07:30] Started run 439 on task 3021, dataset 'sick'.
[2018-04-11 21:07:30] Started run 440 on task 3021, dataset 'sick'.
[2018-04-11 21:07:33] Error in run 433: Run already exists in server. Run id(s): {8944137}
[2018-04-11 21:07:33] Error in run 435: Run already exists in server. Run id(s): {8944139}
[2018-04-11 21:07:33] Error in run 437: Run already exists in server. Run id(s): {8944141}
[2018-04-11 21:07:33] Error in run 434: Run already exists in server. Run id(s): {8944138}
[2018-04-11 21:07:33] Started run 441 on task 3021, dataset 'sick'.
[2018-04-11 21:07:33] Error in run 436: Run already exists in server. Run id(s): {8944140}
[2018-04-11 21:07:33] Started run 442 on task 3021, dataset 'sick'.
[2018-04-11 21:07:33] Started run 445 on task 3021, dataset 'sick'.
[2018-04-11 21:07:33] Started run 443 on task 3021, dataset 'sick'.
[2018-04-11 21:07:33] Started run 444 on task 3021, dataset 'sick'.
[2018-04-11 21:07:34] Error in run 439: Run already exists in server. Run id(s): {8944146}
[2018-04-11 21:07:34] Error in run 440: Run already exists in server. Run id(s): {8944143}
[2018-04-11 21:07:34] Error in run 438: Run already exists in server. Run id(s): {8944142}
[2018-04-11 21:07:34] Started run 446 on task 3021, dataset 'sick'.
[2018-04-11 21:07:34] Started run 447 on task 3021, dataset 'sick'.
[2018-04-11 21:07:34] Started run 448 on task 3021, dataset 'sick'.
[2018-04-11 21:07:37] Error in run 441: Run already exists in server. Run id(s): {8944144}
[2018-04-11 21:07:37] Started run 449 on task 3021, dataset 'sick'.
[2018-04-11 21:07:37] Error in run 442: Run already exists in server. Run id(s): {8944145}
[2018-04-11 21:07:37] Started run 450 on task 3021, dataset 'sick'.
[2018-04-11 21:07:38] Error in run 445: Run already exists in server. Run id(s): {8944148}
[2018-04-11 21:07:38] Error in run 443: Run already exists in server. Run id(s): {8944147}
[2018-04-11 21:07:38] Error in run 444: Run already exists in server. Run id(s): {8944149}
[2018-04-11 21:07:38] Started run 451 on task 3021, dataset 'sick'.
[2018-04-11 21:07:38] Started run 452 on task 3021, dataset 'sick'.
[2018-04-11 21:07:38] Started run 453 on task 3021, dataset 'sick'.
[2018-04-11 21:07:39] Error in run 447: Run already exists in server. Run id(s): {8944151}
[2018-04-11 21:07:39] Started run 454 on task 3021, dataset 'sick'.
[2018-04-11 21:07:39] Error in run 446: Run already exists in server. Run id(s): {8944150}
[2018-04-11 21:07:39] Error in run 448: Run already exists in server. Run id(s): {8944152}
[2018-04-11 21:07:39] Started run 455 on task 3021, dataset 'sick'.
[2018-04-11 21:07:39] Started run 456 on task 3021, dataset 'sick'.
[2018-04-11 21:07:42] Error in run 449: Run already exists in server. Run id(s): {8944154}
[2018-04-11 21:07:42] Started run 457 on task 3021, dataset 'sick'.
[2018-04-11 21:07:42] Error in run 450: Run already exists in server. Run id(s): {8944153}
[2018-04-11 21:07:42] Error in run 451: Run already exists in server. Run id(s): {8944155}
[2018-04-11 21:07:42] Started run 458 on task 3021, dataset 'sick'.
[2018-04-11 21:07:42] Started run 459 on task 3021, dataset 'sick'.
[2018-04-11 21:07:42] Error in run 452: Run already exists in server. Run id(s): {8944156}
[2018-04-11 21:07:42] Started run 460 on task 3021, dataset 'sick'.
[2018-04-11 21:07:42] Error in run 453: Run already exists in server. Run id(s): {8944157}
[2018-04-11 21:07:42] Started run 461 on task 3021, dataset 'sick'.
[2018-04-11 21:07:43] Error in run 454: Run already exists in server. Run id(s): {8944158}
[2018-04-11 21:07:43] Started run 462 on task 3021, dataset 'sick'.
[2018-04-11 21:07:43] Error in run 456: Run already exists in server. Run id(s): {8944160}
[2018-04-11 21:07:43] Error in run 455: Run already exists in server. Run id(s): {8944159}
[2018-04-11 21:07:43] Started run 463 on task 3021, dataset 'sick'.
[2018-04-11 21:07:43] Started run 464 on task 3021, dataset 'sick'.
[2018-04-11 21:07:46] Error in run 457: Run already exists in server. Run id(s): {8944162}
[2018-04-11 21:07:47] Error in run 459: Run already exists in server. Run id(s): {8944163}
[2018-04-11 21:07:46] Started run 465 on task 3021, dataset 'sick'.
[2018-04-11 21:07:47] Error in run 458: Run already exists in server. Run id(s): {8944161}
[2018-04-11 21:07:47] Error in run 461: Run already exists in server. Run id(s): {8944165}
[2018-04-11 21:07:47] Started run 466 on task 3021, dataset 'sick'.
[2018-04-11 21:07:47] Started run 467 on task 3021, dataset 'sick'.
[2018-04-11 21:07:47] Error in run 460: Run already exists in server. Run id(s): {8944164}
[2018-04-11 21:07:47] Started run 469 on task 3021, dataset 'sick'.
[2018-04-11 21:07:47] Started run 468 on task 3021, dataset 'sick'.
[2018-04-11 21:07:48] Error in run 464: Run already exists in server. Run id(s): {8944169}
[2018-04-11 21:07:48] Error in run 462: Run already exists in server. Run id(s): {8944166}
[2018-04-11 21:07:48] Started run 470 on task 3021, dataset 'sick'.
[2018-04-11 21:07:48] Error in run 463: Run already exists in server. Run id(s): {8944167}
[2018-04-11 21:07:48] Started run 472 on task 3021, dataset 'sick'.
[2018-04-11 21:07:48] Started run 471 on task 3021, dataset 'sick'.
[2018-04-11 21:07:51] Error in run 465: Run already exists in server. Run id(s): {8944168}
[2018-04-11 21:07:51] Error in run 466: Run already exists in server. Run id(s): {8944171}
[2018-04-11 21:07:51] Started run 473 on task 3021, dataset 'sick'.
[2018-04-11 21:07:51] Error in run 467: Run already exists in server. Run id(s): {8944170}
[2018-04-11 21:07:51] Error in run 468: Run already exists in server. Run id(s): {8944172}
[2018-04-11 21:07:51] Started run 474 on task 3021, dataset 'sick'.
[2018-04-11 21:07:51] Error in run 469: Run already exists in server. Run id(s): {8944173}
[2018-04-11 21:07:51] Started run 477 on task 3021, dataset 'sick'.
[2018-04-11 21:07:51] Started run 475 on task 3021, dataset 'sick'.
[2018-04-11 21:07:51] Started run 476 on task 3021, dataset 'sick'.
[2018-04-11 21:07:53] Error in run 471: Run already exists in server. Run id(s): {8944175}
[2018-04-11 21:07:53] Started run 478 on task 3021, dataset 'sick'.
[2018-04-11 21:07:53] Error in run 472: Run already exists in server. Run id(s): {8944176}
[2018-04-11 21:07:53] Error in run 470: Run already exists in server. Run id(s): {8944174}
[2018-04-11 21:07:53] Started run 479 on task 3021, dataset 'sick'.
[2018-04-11 21:07:53] Started run 480 on task 3021, dataset 'sick'.
[2018-04-11 21:07:56] Error in run 475: Run already exists in server. Run id(s): {8944179}
[2018-04-11 21:07:56] Error in run 477: Run already exists in server. Run id(s): {9015194, 8944181}
[2018-04-11 21:07:56] Started run 481 on task 3021, dataset 'sick'.
[2018-04-11 21:07:56] Error in run 474: Run already exists in server. Run id(s): {8944177}
[2018-04-11 21:07:56] Error in run 473: Run already exists in server. Run id(s): {8944180}
[2018-04-11 21:07:56] Started run 483 on task 3021, dataset 'sick'.
[2018-04-11 21:07:56] Error in run 476: Run already exists in server. Run id(s): {8944178}
[2018-04-11 21:07:56] Started run 485 on task 3021, dataset 'sick'.
[2018-04-11 21:07:56] Started run 482 on task 3021, dataset 'sick'.
[2018-04-11 21:07:56] Started run 484 on task 3021, dataset 'sick'.
[2018-04-11 21:07:58] Error in run 480: Run already exists in server. Run id(s): {8944183}
[2018-04-11 21:07:58] Started run 486 on task 3021, dataset 'sick'.
[2018-04-11 21:07:58] Error in run 479: Run already exists in server. Run id(s): {8944182}
[2018-04-11 21:07:58] Error in run 478: Run already exists in server. Run id(s): {8944184}
[2018-04-11 21:07:58] Started run 487 on task 3021, dataset 'sick'.
[2018-04-11 21:07:58] Started run 488 on task 3021, dataset 'sick'.
[2018-04-11 21:08:01] Error in run 483: Run already exists in server. Run id(s): {8944186}
[2018-04-11 21:08:01] Error in run 484: Run already exists in server. Run id(s): {8944187}
[2018-04-11 21:08:01] Started run 489 on task 3021, dataset 'sick'.
[2018-04-11 21:08:01] Error in run 485: Run already exists in server. Run id(s): {8944189}
[2018-04-11 21:08:01] Error in run 482: Run already exists in server. Run id(s): {8944188}
[2018-04-11 21:08:01] Error in run 481: Run already exists in server. Run id(s): {8944185}
[2018-04-11 21:08:01] Started run 491 on task 3021, dataset 'sick'.
[2018-04-11 21:08:01] Started run 492 on task 3021, dataset 'sick'.
[2018-04-11 21:08:01] Started run 490 on task 3021, dataset 'sick'.
[2018-04-11 21:08:01] Started run 493 on task 3021, dataset 'sick'.
[2018-04-11 21:08:02] Error in run 488: Run already exists in server. Run id(s): {8944192}
[2018-04-11 21:08:02] Started run 494 on task 3021, dataset 'sick'.
[2018-04-11 21:08:02] Error in run 487: Run already exists in server. Run id(s): {8944191}
[2018-04-11 21:08:02] Error in run 486: Run already exists in server. Run id(s): {8944190}
[2018-04-11 21:08:02] Started run 495 on task 3021, dataset 'sick'.
[2018-04-11 21:08:02] Started run 496 on task 3021, dataset 'sick'.
[2018-04-11 21:08:06] Error in run 492: Run already exists in server. Run id(s): {8944195}
[2018-04-11 21:08:06] Error in run 489: Run already exists in server. Run id(s): {8944193}
[2018-04-11 21:08:06] Error in run 490: Run already exists in server. Run id(s): {8944194}
[2018-04-11 21:08:06] Started run 497 on task 3021, dataset 'sick'.
[2018-04-11 21:08:06] Started run 499 on task 3021, dataset 'sick'.
[2018-04-11 21:08:06] Error in run 491: Run already exists in server. Run id(s): {8944196}
[2018-04-11 21:08:06] Started run 498 on task 3021, dataset 'sick'.
[2018-04-11 21:08:06] Started run 500 on task 3021, dataset 'sick'.
[2018-04-11 21:08:06] Error in run 493: Run already exists in server. Run id(s): {9015300}
[2018-04-11 21:08:06] Started run 501 on task 3021, dataset 'sick'.
[2018-04-11 21:08:07] Error in run 495: Run already exists in server. Run id(s): {8944199}
[2018-04-11 21:08:07] Error in run 496: Run already exists in server. Run id(s): {8944200}
[2018-04-11 21:08:07] Started run 502 on task 3021, dataset 'sick'.
[2018-04-11 21:08:07] Error in run 494: Run already exists in server. Run id(s): {8944198}
[2018-04-11 21:08:07] Started run 503 on task 3021, dataset 'sick'.
[2018-04-11 21:08:07] Started run 504 on task 3021, dataset 'sick'.
[2018-04-11 21:08:10] Error in run 497: Run already exists in server. Run id(s): {8944201}
[2018-04-11 21:08:10] Started run 505 on task 3021, dataset 'sick'.
[2018-04-11 21:08:10] Error in run 499: Run already exists in server. Run id(s): {8944203}
[2018-04-11 21:08:10] Error in run 501: Run already exists in server. Run id(s): {8944205}
[2018-04-11 21:08:10] Error in run 498: Run already exists in server. Run id(s): {8944202}
[2018-04-11 21:08:10] Started run 506 on task 3021, dataset 'sick'.
[2018-04-11 21:08:10] Error in run 500: Run already exists in server. Run id(s): {8944204}
[2018-04-11 21:08:10] Started run 509 on task 3021, dataset 'sick'.
[2018-04-11 21:08:10] Started run 507 on task 3021, dataset 'sick'.
[2018-04-11 21:08:10] Started run 508 on task 3021, dataset 'sick'.
[2018-04-11 21:08:12] Error in run 502: Run already exists in server. Run id(s): {8944208}
[2018-04-11 21:08:12] Error in run 504: Run already exists in server. Run id(s): {8944206}
[2018-04-11 21:08:12] Error in run 503: Run already exists in server. Run id(s): {8944207}
[2018-04-11 21:08:12] Started run 510 on task 3021, dataset 'sick'.
[2018-04-11 21:08:12] Started run 511 on task 3021, dataset 'sick'.
[2018-04-11 21:08:12] Started run 512 on task 3021, dataset 'sick'.
[2018-04-11 21:08:15] Error in run 505: Run already exists in server. Run id(s): {8944209}
[2018-04-11 21:08:15] Started run 513 on task 3021, dataset 'sick'.
[2018-04-11 21:08:15] Error in run 506: Run already exists in server. Run id(s): {8944210}
[2018-04-11 21:08:15] Error in run 507: Run already exists in server. Run id(s): {8944211}
[2018-04-11 21:08:15] Error in run 509: Run already exists in server. Run id(s): {8944213}
[2018-04-11 21:08:15] Started run 514 on task 3021, dataset 'sick'.
[2018-04-11 21:08:15] Started run 515 on task 3021, dataset 'sick'.
[2018-04-11 21:08:15] Started run 516 on task 3021, dataset 'sick'.
[2018-04-11 21:08:15] Error in run 508: Run already exists in server. Run id(s): {8944212}
[2018-04-11 21:08:15] Started run 517 on task 3021, dataset 'sick'.
[2018-04-11 21:08:17] Error in run 510: Run already exists in server. Run id(s): {8944216}
[2018-04-11 21:08:17] Error in run 512: Run already exists in server. Run id(s): {8944214}
[2018-04-11 21:08:17] Error in run 511: Run already exists in server. Run id(s): {8944217}
[2018-04-11 21:08:17] Started run 518 on task 3021, dataset 'sick'.
[2018-04-11 21:08:17] Started run 519 on task 3021, dataset 'sick'.
[2018-04-11 21:08:17] Started run 520 on task 3021, dataset 'sick'.
[2018-04-11 21:08:19] Error in run 513: Run already exists in server. Run id(s): {8944215}
[2018-04-11 21:08:19] Started run 521 on task 3021, dataset 'sick'.
[2018-04-11 21:08:20] Error in run 517: Run already exists in server. Run id(s): {8944221}
[2018-04-11 21:08:20] Error in run 516: Run already exists in server. Run id(s): {8944220}
[2018-04-11 21:08:20] Started run 522 on task 3021, dataset 'sick'.
[2018-04-11 21:08:20] Error in run 514: Run already exists in server. Run id(s): {8944218}
[2018-04-11 21:08:20] Error in run 515: Run already exists in server. Run id(s): {8944219}
[2018-04-11 21:08:20] Started run 523 on task 3021, dataset 'sick'.
[2018-04-11 21:08:20] Started run 525 on task 3021, dataset 'sick'.
[2018-04-11 21:08:20] Started run 524 on task 3021, dataset 'sick'.
[2018-04-11 21:08:21] Error in run 518: Run already exists in server. Run id(s): {8944222}
[2018-04-11 21:08:21] Started run 526 on task 3021, dataset 'sick'.
[2018-04-11 21:08:21] Error in run 519: Run already exists in server. Run id(s): {8944223}
[2018-04-11 21:08:21] Error in run 520: Run already exists in server. Run id(s): {8944226}
[2018-04-11 21:08:21] Started run 527 on task 3021, dataset 'sick'.
[2018-04-11 21:08:21] Started run 528 on task 3021, dataset 'sick'.
[2018-04-11 21:08:24] Error in run 521: Run already exists in server. Run id(s): {8944225}
[2018-04-11 21:08:24] Started run 529 on task 3021, dataset 'sick'.
[2018-04-11 21:08:25] Error in run 524: Run already exists in server. Run id(s): {8944229}
[2018-04-11 21:08:25] Started run 530 on task 3021, dataset 'sick'.
[2018-04-11 21:08:25] Error in run 525: Run already exists in server. Run id(s): {8944230}
[2018-04-11 21:08:25] Error in run 523: Run already exists in server. Run id(s): {8944227}
[2018-04-11 21:08:25] Error in run 522: Run already exists in server. Run id(s): {8944228}
[2018-04-11 21:08:25] Started run 531 on task 3021, dataset 'sick'.
[2018-04-11 21:08:25] Started run 532 on task 3021, dataset 'sick'.
[2018-04-11 21:08:25] Started run 533 on task 3021, dataset 'sick'.
[2018-04-11 21:08:26] Error in run 527: Run already exists in server. Run id(s): {8944231}
[2018-04-11 21:08:26] Error in run 528: Run already exists in server. Run id(s): {8944232}
[2018-04-11 21:08:26] Started run 534 on task 3021, dataset 'sick'.
[2018-04-11 21:08:26] Error in run 526: Run already exists in server. Run id(s): {8944233}
[2018-04-11 21:08:26] Started run 535 on task 3021, dataset 'sick'.
[2018-04-11 21:08:26] Started run 536 on task 3021, dataset 'sick'.
[2018-04-11 21:08:29] Error in run 529: Run already exists in server. Run id(s): {8944234}
[2018-04-11 21:08:29] Started run 537 on task 3021, dataset 'sick'.
[2018-04-11 21:08:29] Error in run 531: Run already exists in server. Run id(s): {8944236}
[2018-04-11 21:08:29] Started run 538 on task 3021, dataset 'sick'.
[2018-04-11 21:08:29] Error in run 530: Run already exists in server. Run id(s): {9015415}
[2018-04-11 21:08:29] Started run 539 on task 3021, dataset 'sick'.
[2018-04-11 21:08:30] Error in run 533: Run already exists in server. Run id(s): {8944238}
[2018-04-11 21:08:30] Error in run 532: Run already exists in server. Run id(s): {8944237}
[2018-04-11 21:08:30] Started run 540 on task 3021, dataset 'sick'.
[2018-04-11 21:08:30] Started run 541 on task 3021, dataset 'sick'.
[2018-04-11 21:08:31] Error in run 534: Run already exists in server. Run id(s): {9015432}
[2018-04-11 21:08:31] Started run 542 on task 3021, dataset 'sick'.
[2018-04-11 21:08:31] Error in run 535: Run already exists in server. Run id(s): {8944241}
[2018-04-11 21:08:31] Started run 543 on task 3021, dataset 'sick'.
[2018-04-11 21:08:31] Error in run 536: Run already exists in server. Run id(s): {8944240}
[2018-04-11 21:08:31] Started run 544 on task 3021, dataset 'sick'.
[2018-04-11 21:08:33] Error in run 537: Run already exists in server. Run id(s): {8944243}
[2018-04-11 21:08:33] Started run 545 on task 3021, dataset 'sick'.
[2018-04-11 21:08:34] Error in run 541: Run already exists in server. Run id(s): {8944245}
[2018-04-11 21:08:34] Error in run 538: Run already exists in server. Run id(s): {8944242}
[2018-04-11 21:08:34] Started run 546 on task 3021, dataset 'sick'.
[2018-04-11 21:08:34] Error in run 539: Run already exists in server. Run id(s): {8944246}
[2018-04-11 21:08:34] Error in run 540: Run already exists in server. Run id(s): {8944244}
[2018-04-11 21:08:34] Started run 547 on task 3021, dataset 'sick'.
[2018-04-11 21:08:34] Started run 548 on task 3021, dataset 'sick'.
[2018-04-11 21:08:34] Started run 549 on task 3021, dataset 'sick'.
[2018-04-11 21:08:35] Error in run 542: Run already exists in server. Run id(s): {8944247}
[2018-04-11 21:08:35] Started run 550 on task 3021, dataset 'sick'.
[2018-04-11 21:08:36] Error in run 544: Run already exists in server. Run id(s): {8944249}
[2018-04-11 21:08:36] Error in run 543: Run already exists in server. Run id(s): {8944248}
[2018-04-11 21:08:36] Started run 551 on task 3021, dataset 'sick'.
[2018-04-11 21:08:36] Started run 552 on task 3021, dataset 'sick'.
[2018-04-11 21:08:38] Error in run 545: Run already exists in server. Run id(s): {8944251}
[2018-04-11 21:08:38] Started run 553 on task 3021, dataset 'sick'.
[2018-04-11 21:08:39] Error in run 549: Run already exists in server. Run id(s): {8944254}
[2018-04-11 21:08:39] Error in run 547: Run already exists in server. Run id(s): {8944252}
[2018-04-11 21:08:39] Error in run 546: Run already exists in server. Run id(s): {8944250}
[2018-04-11 21:08:39] Started run 554 on task 3021, dataset 'sick'.
[2018-04-11 21:08:39] Error in run 548: Run already exists in server. Run id(s): {8944253}
[2018-04-11 21:08:39] Started run 555 on task 3021, dataset 'sick'.
[2018-04-11 21:08:39] Started run 557 on task 3021, dataset 'sick'.
[2018-04-11 21:08:39] Started run 556 on task 3021, dataset 'sick'.
[2018-04-11 21:08:40] Error in run 550: Run already exists in server. Run id(s): {8944255}
[2018-04-11 21:08:40] Started run 558 on task 3021, dataset 'sick'.
[2018-04-11 21:08:40] Error in run 552: Run already exists in server. Run id(s): {8944258}
[2018-04-11 21:08:40] Error in run 551: Run already exists in server. Run id(s): {8944257}
[2018-04-11 21:08:40] Started run 559 on task 3021, dataset 'sick'.
[2018-04-11 21:08:40] Started run 560 on task 3021, dataset 'sick'.
[2018-04-11 21:08:43] Error in run 553: Run already exists in server. Run id(s): {8944256}
[2018-04-11 21:08:43] Started run 561 on task 3021, dataset 'sick'.
[2018-04-11 21:08:44] Error in run 555: Run already exists in server. Run id(s): {8944260}
[2018-04-11 21:08:44] Error in run 554: Run already exists in server. Run id(s): {8944259}
[2018-04-11 21:08:44] Error in run 557: Run already exists in server. Run id(s): {8944264}
[2018-04-11 21:08:44] Started run 562 on task 3021, dataset 'sick'.
[2018-04-11 21:08:44] Error in run 556: Run already exists in server. Run id(s): {8944262}
[2018-04-11 21:08:44] Started run 563 on task 3021, dataset 'sick'.
[2018-04-11 21:08:44] Started run 565 on task 3021, dataset 'sick'.
[2018-04-11 21:08:44] Started run 564 on task 3021, dataset 'sick'.
[2018-04-11 21:08:44] Error in run 558: Run already exists in server. Run id(s): {8944261}
[2018-04-11 21:08:44] Started run 566 on task 3021, dataset 'sick'.
[2018-04-11 21:08:45] Error in run 560: Run already exists in server. Run id(s): {8944268}
[2018-04-11 21:08:45] Error in run 559: Run already exists in server. Run id(s): {8944263}
[2018-04-11 21:08:45] Started run 567 on task 3021, dataset 'sick'.
[2018-04-11 21:08:45] Started run 568 on task 3021, dataset 'sick'.
[2018-04-11 21:08:48] Error in run 561: Run already exists in server. Run id(s): {8944265}
[2018-04-11 21:08:48] Started run 569 on task 3021, dataset 'sick'.
[2018-04-11 21:08:48] Error in run 565: Run already exists in server. Run id(s): {8944270}
[2018-04-11 21:08:48] Error in run 564: Run already exists in server. Run id(s): {8944269}
[2018-04-11 21:08:48] Error in run 562: Run already exists in server. Run id(s): {8944266}
[2018-04-11 21:08:48] Error in run 563: Run already exists in server. Run id(s): {8944267}
[2018-04-11 21:08:48] Started run 570 on task 3021, dataset 'sick'.
[2018-04-11 21:08:48] Started run 571 on task 3021, dataset 'sick'.
[2018-04-11 21:08:48] Started run 572 on task 3021, dataset 'sick'.
[2018-04-11 21:08:48] Started run 573 on task 3021, dataset 'sick'.
[2018-04-11 21:08:49] Error in run 566: Run already exists in server. Run id(s): {8944271}
[2018-04-11 21:08:49] Started run 574 on task 3021, dataset 'sick'.
[2018-04-11 21:08:50] Error in run 567: Run already exists in server. Run id(s): {8944272}
[2018-04-11 21:08:50] Error in run 568: Run already exists in server. Run id(s): {8944273}
[2018-04-11 21:08:50] Started run 575 on task 3021, dataset 'sick'.
[2018-04-11 21:08:50] Started run 576 on task 3021, dataset 'sick'.
[2018-04-11 21:08:52] Error in run 569: Run already exists in server. Run id(s): {8944276}
[2018-04-11 21:08:52] Started run 577 on task 3021, dataset 'sick'.
[2018-04-11 21:08:53] Error in run 571: Run already exists in server. Run id(s): {8944274}
[2018-04-11 21:08:53] Error in run 573: Run already exists in server. Run id(s): {8944278}
[2018-04-11 21:08:53] Error in run 570: Run already exists in server. Run id(s): {8944275}
[2018-04-11 21:08:53] Started run 579 on task 3021, dataset 'sick'.
[2018-04-11 21:08:53] Error in run 572: Run already exists in server. Run id(s): {8944277}
[2018-04-11 21:08:53] Started run 580 on task 3021, dataset 'sick'.
[2018-04-11 21:08:53] Started run 581 on task 3021, dataset 'sick'.
[2018-04-11 21:08:53] Started run 578 on task 3021, dataset 'sick'.
[2018-04-11 21:08:54] Error in run 574: Run already exists in server. Run id(s): {8944279}
[2018-04-11 21:08:54] Started run 582 on task 3021, dataset 'sick'.
[2018-04-11 21:08:55] Error in run 575: Run already exists in server. Run id(s): {8944280}
[2018-04-11 21:08:55] Error in run 576: Run already exists in server. Run id(s): {8944281}
[2018-04-11 21:08:55] Started run 583 on task 3021, dataset 'sick'.
[2018-04-11 21:08:55] Started run 584 on task 3021, dataset 'sick'.
[2018-04-11 21:08:57] Error in run 577: Run already exists in server. Run id(s): {8944282}
[2018-04-11 21:08:57] Started run 585 on task 3021, dataset 'sick'.
[2018-04-11 21:08:58] Error in run 579: Run already exists in server. Run id(s): {8944283}
[2018-04-11 21:08:58] Error in run 580: Run already exists in server. Run id(s): {8944285}
[2018-04-11 21:08:58] Error in run 578: Run already exists in server. Run id(s): {8944284}
[2018-04-11 21:08:58] Started run 586 on task 3021, dataset 'sick'.
[2018-04-11 21:08:58] Started run 587 on task 3021, dataset 'sick'.
[2018-04-11 21:08:58] Started run 588 on task 3021, dataset 'sick'.
[2018-04-11 21:08:58] Error in run 581: Run already exists in server. Run id(s): {8944286}
[2018-04-11 21:08:58] Started run 589 on task 3021, dataset 'sick'.
[2018-04-11 21:08:59] Error in run 582: Run already exists in server. Run id(s): {8944288}
[2018-04-11 21:08:59] Started run 590 on task 3021, dataset 'sick'.
[2018-04-11 21:09:00] Error in run 583: Run already exists in server. Run id(s): {8944289}
[2018-04-11 21:09:00] Error in run 584: Run already exists in server. Run id(s): {8944287}
[2018-04-11 21:09:00] Started run 591 on task 3021, dataset 'sick'.
[2018-04-11 21:09:00] Started run 592 on task 3021, dataset 'sick'.
[2018-04-11 21:09:02] Error in run 585: Run already exists in server. Run id(s): {8944290}
[2018-04-11 21:09:02] Started run 593 on task 3021, dataset 'sick'.
[2018-04-11 21:09:03] Error in run 588: Run already exists in server. Run id(s): {8944295}
[2018-04-11 21:09:03] Started run 594 on task 3021, dataset 'sick'.
[2018-04-11 21:09:03] Error in run 586: Run already exists in server. Run id(s): {8944291}
[2018-04-11 21:09:03] Error in run 589: Run already exists in server. Run id(s): {8944292}
[2018-04-11 21:09:03] Started run 595 on task 3021, dataset 'sick'.
[2018-04-11 21:09:03] Error in run 587: Run already exists in server. Run id(s): {8944293}
[2018-04-11 21:09:03] Started run 596 on task 3021, dataset 'sick'.
[2018-04-11 21:09:03] Started run 597 on task 3021, dataset 'sick'.
[2018-04-11 21:09:03] Error in run 590: Run already exists in server. Run id(s): {8944294}
[2018-04-11 21:09:03] Started run 598 on task 3021, dataset 'sick'.
[2018-04-11 21:09:04] Error in run 591: Run already exists in server. Run id(s): {8944299}
[2018-04-11 21:09:04] Error in run 592: Run already exists in server. Run id(s): {8944296}
[2018-04-11 21:09:04] Started run 599 on task 3021, dataset 'sick'.
[2018-04-11 21:09:04] Started run 600 on task 3021, dataset 'sick'.
[2018-04-11 21:09:06] Error in run 593: Run already exists in server. Run id(s): {8944298}
[2018-04-11 21:09:06] Started run 601 on task 3021, dataset 'sick'.
[2018-04-11 21:09:07] Error in run 594: Run already exists in server. Run id(s): {8944297}
[2018-04-11 21:09:07] Started run 602 on task 3021, dataset 'sick'.
[2018-04-11 21:09:08] Error in run 595: Run already exists in server. Run id(s): {8944300}
[2018-04-11 21:09:08] Error in run 596: Run already exists in server. Run id(s): {8944301}
[2018-04-11 21:09:08] Error in run 597: Run already exists in server. Run id(s): {8944303}
[2018-04-11 21:09:08] Started run 603 on task 3021, dataset 'sick'.
[2018-04-11 21:09:08] Started run 605 on task 3021, dataset 'sick'.
[2018-04-11 21:09:08] Started run 604 on task 3021, dataset 'sick'.
[2018-04-11 21:09:08] Error in run 598: Run already exists in server. Run id(s): {8944302}
[2018-04-11 21:09:08] Started run 606 on task 3021, dataset 'sick'.
[2018-04-11 21:09:09] Error in run 599: Run already exists in server. Run id(s): {8944304}
[2018-04-11 21:09:09] Started run 607 on task 3021, dataset 'sick'.
[2018-04-11 21:09:09] Error in run 600: Run already exists in server. Run id(s): {8944305}
[2018-04-11 21:09:09] Started run 608 on task 3021, dataset 'sick'.
[2018-04-11 21:09:11] Error in run 601: Run already exists in server. Run id(s): {8944307}
[2018-04-11 21:09:11] Started run 609 on task 3021, dataset 'sick'.
[2018-04-11 21:09:12] Error in run 602: Run already exists in server. Run id(s): {8944306}
[2018-04-11 21:09:12] Started run 610 on task 3021, dataset 'sick'.
[2018-04-11 21:09:12] Error in run 605: Run already exists in server. Run id(s): {8944310}
[2018-04-11 21:09:12] Error in run 603: Run already exists in server. Run id(s): {8944308}
[2018-04-11 21:09:12] Started run 611 on task 3021, dataset 'sick'.
[2018-04-11 21:09:12] Error in run 604: Run already exists in server. Run id(s): {8944309}
[2018-04-11 21:09:12] Started run 612 on task 3021, dataset 'sick'.
[2018-04-11 21:09:12] Started run 613 on task 3021, dataset 'sick'.
[2018-04-11 21:09:13] Error in run 606: Run already exists in server. Run id(s): {8944311}
[2018-04-11 21:09:13] Started run 614 on task 3021, dataset 'sick'.
[2018-04-11 21:09:14] Error in run 607: Run already exists in server. Run id(s): {8944312}
[2018-04-11 21:09:14] Started run 615 on task 3021, dataset 'sick'.
[2018-04-11 21:09:14] Error in run 608: Run already exists in server. Run id(s): {8944314}
[2018-04-11 21:09:14] Started run 616 on task 3021, dataset 'sick'.
[2018-04-11 21:09:15] Error in run 609: Run already exists in server. Run id(s): {8944313}
[2018-04-11 21:09:15] Started run 617 on task 3021, dataset 'sick'.
[2018-04-11 21:09:16] Error in run 610: Run already exists in server. Run id(s): {8944315}
[2018-04-11 21:09:16] Started run 618 on task 3021, dataset 'sick'.
[2018-04-11 21:09:17] Error in run 611: Run already exists in server. Run id(s): {8944318}
[2018-04-11 21:09:17] Error in run 613: Run already exists in server. Run id(s): {8944317}
[2018-04-11 21:09:17] Error in run 612: Run already exists in server. Run id(s): {8944316}
[2018-04-11 21:09:17] Started run 619 on task 3021, dataset 'sick'.
[2018-04-11 21:09:17] Started run 620 on task 3021, dataset 'sick'.
[2018-04-11 21:09:17] Started run 621 on task 3021, dataset 'sick'.
[2018-04-11 21:09:17] Error in run 614: Run already exists in server. Run id(s): {8944319}
[2018-04-11 21:09:17] Started run 622 on task 3021, dataset 'sick'.
[2018-04-11 21:09:18] Error in run 615: Run already exists in server. Run id(s): {8944322}
[2018-04-11 21:09:18] Started run 623 on task 3021, dataset 'sick'.
[2018-04-11 21:09:19] Error in run 616: Run already exists in server. Run id(s): {8944321}
[2018-04-11 21:09:19] Started run 624 on task 3021, dataset 'sick'.
[2018-04-11 21:09:20] Error in run 617: Run already exists in server. Run id(s): {8944320}
[2018-04-11 21:09:20] Started run 625 on task 3021, dataset 'sick'.
[2018-04-11 21:09:21] Error in run 618: Run already exists in server. Run id(s): {8944323}
[2018-04-11 21:09:21] Started run 626 on task 3021, dataset 'sick'.
[2018-04-11 21:09:22] Error in run 619: Run already exists in server. Run id(s): {8944325}
[2018-04-11 21:09:22] Started run 627 on task 3021, dataset 'sick'.
[2018-04-11 21:09:22] Error in run 620: Run already exists in server. Run id(s): {8944324}
[2018-04-11 21:09:22] Error in run 621: Run already exists in server. Run id(s): {8944327}
[2018-04-11 21:09:22] Started run 628 on task 3021, dataset 'sick'.
[2018-04-11 21:09:22] Started run 629 on task 3021, dataset 'sick'.
[2018-04-11 21:09:22] Error in run 622: Run already exists in server. Run id(s): {8944326}
[2018-04-11 21:09:22] Started run 630 on task 3021, dataset 'sick'.
[2018-04-11 21:09:23] Error in run 623: Run already exists in server. Run id(s): {8944328}
[2018-04-11 21:09:23] Started run 631 on task 3021, dataset 'sick'.
[2018-04-11 21:09:23] Error in run 624: Run already exists in server. Run id(s): {8944330}
[2018-04-11 21:09:23] Started run 632 on task 3021, dataset 'sick'.
[2018-04-11 21:09:25] Error in run 625: Run already exists in server. Run id(s): {8944331}
[2018-04-11 21:09:25] Started run 633 on task 3021, dataset 'sick'.
[2018-04-11 21:09:26] Error in run 626: Run already exists in server. Run id(s): {8944329}
[2018-04-11 21:09:26] Started run 634 on task 3021, dataset 'sick'.
[2018-04-11 21:09:27] Error in run 630: Run already exists in server. Run id(s): {8944335}
[2018-04-11 21:09:27] Error in run 628: Run already exists in server. Run id(s): {8944333}
[2018-04-11 21:09:27] Error in run 629: Run already exists in server. Run id(s): {8944334}
[2018-04-11 21:09:27] Error in run 627: Run already exists in server. Run id(s): {8944332}
[2018-04-11 21:09:27] Started run 635 on task 3021, dataset 'sick'.
[2018-04-11 21:09:27] Started run 638 on task 3021, dataset 'sick'.
[2018-04-11 21:09:27] Started run 636 on task 3021, dataset 'sick'.
[2018-04-11 21:09:27] Started run 637 on task 3021, dataset 'sick'.
[2018-04-11 21:09:27] Error in run 631: Run already exists in server. Run id(s): {8944336}
[2018-04-11 21:09:27] Started run 639 on task 3021, dataset 'sick'.
[2018-04-11 21:09:28] Error in run 632: Run already exists in server. Run id(s): {8944338}
[2018-04-11 21:09:28] Started run 640 on task 3021, dataset 'sick'.
[2018-04-11 21:09:30] Error in run 633: Run already exists in server. Run id(s): {8944337}
[2018-04-11 21:09:30] Started run 641 on task 3021, dataset 'sick'.
[2018-04-11 21:09:30] Error in run 634: Run already exists in server. Run id(s): {9015809, 8944339}
[2018-04-11 21:09:30] Started run 642 on task 3021, dataset 'sick'.
[2018-04-11 21:09:31] Error in run 637: Run already exists in server. Run id(s): {8944344}
[2018-04-11 21:09:31] Error in run 635: Run already exists in server. Run id(s): {8944340}
[2018-04-11 21:09:31] Error in run 636: Run already exists in server. Run id(s): {8944341}
[2018-04-11 21:09:31] Started run 643 on task 3021, dataset 'sick'.
[2018-04-11 21:09:31] Error in run 638: Run already exists in server. Run id(s): {8944342}
[2018-04-11 21:09:31] Started run 646 on task 3021, dataset 'sick'.
[2018-04-11 21:09:31] Started run 644 on task 3021, dataset 'sick'.
[2018-04-11 21:09:31] Started run 645 on task 3021, dataset 'sick'.
[2018-04-11 21:09:32] Error in run 639: Run already exists in server. Run id(s): {8944343}
[2018-04-11 21:09:32] Started run 647 on task 3021, dataset 'sick'.
[2018-04-11 21:09:33] Error in run 640: Run already exists in server. Run id(s): {8944345}
[2018-04-11 21:09:33] Started run 648 on task 3021, dataset 'sick'.
[2018-04-11 21:09:34] Error in run 641: Run already exists in server. Run id(s): {8944346}
[2018-04-11 21:09:34] Started run 649 on task 3021, dataset 'sick'.
[2018-04-11 21:09:35] Error in run 642: Run already exists in server. Run id(s): {8944348}
[2018-04-11 21:09:35] Started run 650 on task 3021, dataset 'sick'.
[2018-04-11 21:09:36] Error in run 646: Run already exists in server. Run id(s): {8944353}
[2018-04-11 21:09:36] Error in run 643: Run already exists in server. Run id(s): {8944347}
[2018-04-11 21:09:36] Error in run 644: Run already exists in server. Run id(s): {8944349}
[2018-04-11 21:09:36] Error in run 645: Run already exists in server. Run id(s): {8944350}
[2018-04-11 21:09:36] Started run 651 on task 3021, dataset 'sick'.
[2018-04-11 21:09:36] Started run 652 on task 3021, dataset 'sick'.
[2018-04-11 21:09:36] Started run 653 on task 3021, dataset 'sick'.
[2018-04-11 21:09:36] Started run 654 on task 3021, dataset 'sick'.
[2018-04-11 21:09:37] Error in run 647: Run already exists in server. Run id(s): {8944351}
[2018-04-11 21:09:37] Started run 655 on task 3021, dataset 'sick'.
[2018-04-11 21:09:38] Error in run 648: Run already exists in server. Run id(s): {8944352}
[2018-04-11 21:09:38] Started run 656 on task 3021, dataset 'sick'.
[2018-04-11 21:09:39] Error in run 649: Run already exists in server. Run id(s): {8944354}
[2018-04-11 21:09:39] Started run 657 on task 3021, dataset 'sick'.
[2018-04-11 21:09:39] Error in run 650: Run already exists in server. Run id(s): {8944355}
[2018-04-11 21:09:39] Started run 658 on task 3021, dataset 'sick'.
[2018-04-11 21:09:41] Error in run 652: Run already exists in server. Run id(s): {8944356}
[2018-04-11 21:09:41] Error in run 651: Run already exists in server. Run id(s): {8944357}
[2018-04-11 21:09:41] Started run 659 on task 3021, dataset 'sick'.
[2018-04-11 21:09:41] Error in run 654: Run already exists in server. Run id(s): {8944359}
[2018-04-11 21:09:41] Started run 660 on task 3021, dataset 'sick'.
[2018-04-11 21:09:41] Started run 661 on task 3021, dataset 'sick'.
[2018-04-11 21:09:41] Error in run 653: Run already exists in server. Run id(s): {8944358}
[2018-04-11 21:09:41] Started run 662 on task 3021, dataset 'sick'.
[2018-04-11 21:09:41] Error in run 655: Run already exists in server. Run id(s): {8944360}
[2018-04-11 21:09:41] Started run 663 on task 3021, dataset 'sick'.
[2018-04-11 21:09:42] Error in run 656: Run already exists in server. Run id(s): {8944361}
[2018-04-11 21:09:42] Started run 664 on task 3021, dataset 'sick'.
[2018-04-11 21:09:44] Error in run 657: Run already exists in server. Run id(s): {8944362}
[2018-04-11 21:09:44] Started run 665 on task 3021, dataset 'sick'.
[2018-04-11 21:09:44] Error in run 658: Run already exists in server. Run id(s): {8944363}
[2018-04-11 21:09:44] Started run 666 on task 3021, dataset 'sick'.
[2018-04-11 21:09:45] Error in run 659: Run already exists in server. Run id(s): {8944364}
[2018-04-11 21:09:45] Error in run 660: Run already exists in server. Run id(s): {8944367}
[2018-04-11 21:09:45] Started run 667 on task 3021, dataset 'sick'.
[2018-04-11 21:09:45] Started run 668 on task 3021, dataset 'sick'.
[2018-04-11 21:09:46] Error in run 662: Run already exists in server. Run id(s): {8944366}
[2018-04-11 21:09:46] Error in run 661: Run already exists in server. Run id(s): {8944365}
[2018-04-11 21:09:46] Started run 669 on task 3021, dataset 'sick'.
[2018-04-11 21:09:46] Started run 670 on task 3021, dataset 'sick'.
[2018-04-11 21:09:46] Error in run 663: Run already exists in server. Run id(s): {8944368}
[2018-04-11 21:09:46] Started run 671 on task 3021, dataset 'sick'.
[2018-04-11 21:09:47] Error in run 664: Run already exists in server. Run id(s): {8944369}
[2018-04-11 21:09:47] Started run 672 on task 3021, dataset 'sick'.
[2018-04-11 21:09:49] Error in run 665: Run already exists in server. Run id(s): {8944370}
[2018-04-11 21:09:49] Error in run 666: Run already exists in server. Run id(s): {8944371}
[2018-04-11 21:09:49] Started run 673 on task 3021, dataset 'sick'.
[2018-04-11 21:09:49] Started run 674 on task 3021, dataset 'sick'.
[2018-04-11 21:09:50] Error in run 668: Run already exists in server. Run id(s): {8944373}
[2018-04-11 21:09:50] Error in run 667: Run already exists in server. Run id(s): {8944372}
[2018-04-11 21:09:50] Started run 675 on task 3021, dataset 'sick'.
[2018-04-11 21:09:50] Started run 676 on task 3021, dataset 'sick'.
[2018-04-11 21:09:50] Error in run 670: Run already exists in server. Run id(s): {8944375}
[2018-04-11 21:09:50] Error in run 669: Run already exists in server. Run id(s): {8944374}
[2018-04-11 21:09:50] Started run 677 on task 3021, dataset 'sick'.
[2018-04-11 21:09:50] Started run 678 on task 3021, dataset 'sick'.
[2018-04-11 21:09:50] Error in run 671: Run already exists in server. Run id(s): {8944376}
[2018-04-11 21:09:50] Started run 679 on task 3021, dataset 'sick'.
[2018-04-11 21:09:51] Error in run 672: Run already exists in server. Run id(s): {8944377}
[2018-04-11 21:09:51] Started run 680 on task 3021, dataset 'sick'.
[2018-04-11 21:09:53] Error in run 674: Run already exists in server. Run id(s): {8944379}
[2018-04-11 21:09:53] Started run 681 on task 3021, dataset 'sick'.
[2018-04-11 21:09:53] Error in run 673: Run already exists in server. Run id(s): {8944378}
[2018-04-11 21:09:53] Started run 682 on task 3021, dataset 'sick'.
[2018-04-11 21:09:54] Error in run 675: Run already exists in server. Run id(s): {8944380}
[2018-04-11 21:09:54] Error in run 676: Run already exists in server. Run id(s): {8944381}
[2018-04-11 21:09:54] Started run 683 on task 3021, dataset 'sick'.
[2018-04-11 21:09:54] Started run 684 on task 3021, dataset 'sick'.
[2018-04-11 21:09:55] Error in run 678: Run already exists in server. Run id(s): {8944383}
[2018-04-11 21:09:55] Error in run 677: Run already exists in server. Run id(s): {8944382}
[2018-04-11 21:09:55] Started run 685 on task 3021, dataset 'sick'.
[2018-04-11 21:09:55] Started run 686 on task 3021, dataset 'sick'.
[2018-04-11 21:09:55] Error in run 679: Run already exists in server. Run id(s): {8944384}
[2018-04-11 21:09:55] Started run 687 on task 3021, dataset 'sick'.
[2018-04-11 21:09:56] Error in run 680: Run already exists in server. Run id(s): {8944385}
[2018-04-11 21:09:56] Started run 688 on task 3021, dataset 'sick'.
[2018-04-11 21:09:58] Error in run 681: Run already exists in server. Run id(s): {8944386}
[2018-04-11 21:09:58] Started run 689 on task 3021, dataset 'sick'.
[2018-04-11 21:09:58] Error in run 682: Run already exists in server. Run id(s): {8944387}
[2018-04-11 21:09:58] Started run 690 on task 3021, dataset 'sick'.
[2018-04-11 21:09:59] Error in run 684: Run already exists in server. Run id(s): {8944389}
[2018-04-11 21:09:59] Error in run 683: Run already exists in server. Run id(s): {9016018, 8944388}
[2018-04-11 21:09:59] Started run 691 on task 3021, dataset 'sick'.
[2018-04-11 21:09:59] Started run 692 on task 3021, dataset 'sick'.
[2018-04-11 21:09:59] Error in run 685: Run already exists in server. Run id(s): {8944390}
[2018-04-11 21:09:59] Error in run 686: Run already exists in server. Run id(s): {8944392}
[2018-04-11 21:09:59] Started run 693 on task 3021, dataset 'sick'.
[2018-04-11 21:09:59] Started run 694 on task 3021, dataset 'sick'.
[2018-04-11 21:09:59] Error in run 687: Run already exists in server. Run id(s): {8944391}
[2018-04-11 21:09:59] Started run 695 on task 3021, dataset 'sick'.
[2018-04-11 21:10:00] Error in run 688: Run already exists in server. Run id(s): {8944393}
[2018-04-11 21:10:00] Started run 696 on task 3021, dataset 'sick'.
[2018-04-11 21:10:02] Error in run 689: Run already exists in server. Run id(s): {8944394}
[2018-04-11 21:10:02] Started run 697 on task 3021, dataset 'sick'.
[2018-04-11 21:10:02] Error in run 690: Run already exists in server. Run id(s): {8944395}
[2018-04-11 21:10:02] Started run 698 on task 3021, dataset 'sick'.
[2018-04-11 21:10:04] Error in run 691: Run already exists in server. Run id(s): {8944396}
[2018-04-11 21:10:04] Started run 699 on task 3021, dataset 'sick'.
[2018-04-11 21:10:04] Error in run 692: Run already exists in server. Run id(s): {8944397}
[2018-04-11 21:10:04] Error in run 693: Run already exists in server. Run id(s): {8944398}
[2018-04-11 21:10:04] Started run 700 on task 3021, dataset 'sick'.
[2018-04-11 21:10:04] Error in run 694: Run already exists in server. Run id(s): {8944399}
[2018-04-11 21:10:04] Started run 702 on task 3021, dataset 'sick'.
[2018-04-11 21:10:04] Started run 701 on task 3021, dataset 'sick'.
[2018-04-11 21:10:04] Error in run 695: Run already exists in server. Run id(s): {8944401}
[2018-04-11 21:10:04] Started run 703 on task 3021, dataset 'sick'.
[2018-04-11 21:10:05] Error in run 696: Run already exists in server. Run id(s): {8944400}
[2018-04-11 21:10:05] Started run 704 on task 3021, dataset 'sick'.
[2018-04-11 21:10:07] Error in run 697: Run already exists in server. Run id(s): {8944402}
[2018-04-11 21:10:07] Started run 705 on task 3021, dataset 'sick'.
[2018-04-11 21:10:07] Error in run 698: Run already exists in server. Run id(s): {8944403}
[2018-04-11 21:10:07] Started run 706 on task 3021, dataset 'sick'.
[2018-04-11 21:10:08] Error in run 699: Run already exists in server. Run id(s): {8944406}
[2018-04-11 21:10:08] Started run 707 on task 3021, dataset 'sick'.
[2018-04-11 21:10:08] Error in run 700: Run already exists in server. Run id(s): {8944404}
[2018-04-11 21:10:08] Started run 708 on task 3021, dataset 'sick'.
[2018-04-11 21:10:09] Error in run 703: Run already exists in server. Run id(s): {8944408}
[2018-04-11 21:10:09] Error in run 701: Run already exists in server. Run id(s): {8944405}
[2018-04-11 21:10:09] Started run 709 on task 3021, dataset 'sick'.
[2018-04-11 21:10:09] Error in run 702: Run already exists in server. Run id(s): {8944407}
[2018-04-11 21:10:09] Started run 710 on task 3021, dataset 'sick'.
[2018-04-11 21:10:09] Started run 711 on task 3021, dataset 'sick'.
[2018-04-11 21:10:09] Error in run 704: Run already exists in server. Run id(s): {8944409}
[2018-04-11 21:10:09] Started run 712 on task 3021, dataset 'sick'.
[2018-04-11 21:10:12] Error in run 705: Run already exists in server. Run id(s): {8944410}
[2018-04-11 21:10:12] Error in run 706: Run already exists in server. Run id(s): {8944411}
[2018-04-11 21:10:12] Started run 713 on task 3021, dataset 'sick'.
[2018-04-11 21:10:12] Started run 714 on task 3021, dataset 'sick'.
[2018-04-11 21:10:13] Error in run 707: Run already exists in server. Run id(s): {8944414}
[2018-04-11 21:10:13] Started run 715 on task 3021, dataset 'sick'.
[2018-04-11 21:10:13] Error in run 708: Run already exists in server. Run id(s): {8944412}
[2018-04-11 21:10:13] Started run 716 on task 3021, dataset 'sick'.
[2018-04-11 21:10:13] Error in run 710: Run already exists in server. Run id(s): {8944415}
[2018-04-11 21:10:13] Error in run 709: Run already exists in server. Run id(s): {8944413}
[2018-04-11 21:10:13] Started run 717 on task 3021, dataset 'sick'.
[2018-04-11 21:10:13] Started run 718 on task 3021, dataset 'sick'.
[2018-04-11 21:10:13] Error in run 711: Run already exists in server. Run id(s): {8944416}
[2018-04-11 21:10:13] Started run 719 on task 3021, dataset 'sick'.
[2018-04-11 21:10:14] Error in run 712: Run already exists in server. Run id(s): {8944417}
[2018-04-11 21:10:14] Started run 720 on task 3021, dataset 'sick'.
[2018-04-11 21:10:16] Error in run 713: Run already exists in server. Run id(s): {8944418}
[2018-04-11 21:10:16] Error in run 714: Run already exists in server. Run id(s): {8944419}
[2018-04-11 21:10:16] Started run 721 on task 3021, dataset 'sick'.
[2018-04-11 21:10:16] Started run 722 on task 3021, dataset 'sick'.
[2018-04-11 21:10:17] Error in run 716: Run already exists in server. Run id(s): {8944421}
[2018-04-11 21:10:17] Error in run 715: Run already exists in server. Run id(s): {8944420}
[2018-04-11 21:10:17] Started run 723 on task 3021, dataset 'sick'.
[2018-04-11 21:10:17] Started run 724 on task 3021, dataset 'sick'.
[2018-04-11 21:10:18] Error in run 718: Run already exists in server. Run id(s): {8944423}
[2018-04-11 21:10:18] Error in run 717: Run already exists in server. Run id(s): {8944422}
[2018-04-11 21:10:18] Started run 725 on task 3021, dataset 'sick'.
[2018-04-11 21:10:18] Started run 726 on task 3021, dataset 'sick'.
[2018-04-11 21:10:18] Error in run 719: Run already exists in server. Run id(s): {8944425}
[2018-04-11 21:10:18] Started run 727 on task 3021, dataset 'sick'.
[2018-04-11 21:10:19] Error in run 720: Run already exists in server. Run id(s): {8944424}
[2018-04-11 21:10:19] Started run 728 on task 3021, dataset 'sick'.
[2018-04-11 21:10:21] Error in run 721: Run already exists in server. Run id(s): {8944426}
[2018-04-11 21:10:21] Started run 729 on task 3021, dataset 'sick'.
[2018-04-11 21:10:21] Error in run 722: Run already exists in server. Run id(s): {8944427}
[2018-04-11 21:10:21] Started run 730 on task 3021, dataset 'sick'.
[2018-04-11 21:10:22] Error in run 723: Run already exists in server. Run id(s): {8944429}
[2018-04-11 21:10:22] Error in run 724: Run already exists in server. Run id(s): {8944428}
[2018-04-11 21:10:22] Started run 731 on task 3021, dataset 'sick'.
[2018-04-11 21:10:22] Started run 732 on task 3021, dataset 'sick'.
[2018-04-11 21:10:22] Error in run 726: Run already exists in server. Run id(s): {8944430}
[2018-04-11 21:10:22] Started run 733 on task 3021, dataset 'sick'.
[2018-04-11 21:10:22] Error in run 725: Run already exists in server. Run id(s): {8944432}
[2018-04-11 21:10:22] Started run 734 on task 3021, dataset 'sick'.
[2018-04-11 21:10:23] Error in run 727: Run already exists in server. Run id(s): {8944431}
[2018-04-11 21:10:23] Started run 735 on task 3021, dataset 'sick'.
[2018-04-11 21:10:24] Error in run 728: Run already exists in server. Run id(s): {8944433}
[2018-04-11 21:10:24] Started run 736 on task 3021, dataset 'sick'.
[2018-04-11 21:10:26] Error in run 729: Run already exists in server. Run id(s): {8944434}
[2018-04-11 21:10:26] Started run 737 on task 3021, dataset 'sick'.
[2018-04-11 21:10:26] Error in run 730: Run already exists in server. Run id(s): {8944435}
[2018-04-11 21:10:26] Started run 738 on task 3021, dataset 'sick'.
[2018-04-11 21:10:27] Error in run 731: Run already exists in server. Run id(s): {8944436}
[2018-04-11 21:10:27] Started run 739 on task 3021, dataset 'sick'.
[2018-04-11 21:10:27] Error in run 734: Run already exists in server. Run id(s): {8944438}
[2018-04-11 21:10:27] Error in run 732: Run already exists in server. Run id(s): {8944437}
[2018-04-11 21:10:27] Error in run 733: Run already exists in server. Run id(s): {8944440}
[2018-04-11 21:10:27] Started run 740 on task 3021, dataset 'sick'.
[2018-04-11 21:10:27] Started run 741 on task 3021, dataset 'sick'.
[2018-04-11 21:10:27] Started run 742 on task 3021, dataset 'sick'.
[2018-04-11 21:10:27] Error in run 735: Run already exists in server. Run id(s): {8944439}
[2018-04-11 21:10:27] Started run 743 on task 3021, dataset 'sick'.
[2018-04-11 21:10:28] Error in run 736: Run already exists in server. Run id(s): {8944441}
[2018-04-11 21:10:28] Started run 744 on task 3021, dataset 'sick'.
[2018-04-11 21:10:30] Error in run 737: Run already exists in server. Run id(s): {8944442}
[2018-04-11 21:10:30] Started run 745 on task 3021, dataset 'sick'.
[2018-04-11 21:10:30] Error in run 738: Run already exists in server. Run id(s): {8944445}
[2018-04-11 21:10:30] Started run 746 on task 3021, dataset 'sick'.
[2018-04-11 21:10:32] Error in run 739: Run already exists in server. Run id(s): {8944443}
[2018-04-11 21:10:32] Error in run 741: Run already exists in server. Run id(s): {8944446}
[2018-04-11 21:10:32] Error in run 740: Run already exists in server. Run id(s): {8944444}
[2018-04-11 21:10:32] Started run 747 on task 3021, dataset 'sick'.
[2018-04-11 21:10:32] Error in run 742: Run already exists in server. Run id(s): {8944448}
[2018-04-11 21:10:32] Started run 748 on task 3021, dataset 'sick'.
[2018-04-11 21:10:32] Started run 750 on task 3021, dataset 'sick'.
[2018-04-11 21:10:32] Error in run 743: Run already exists in server. Run id(s): {8944447}
[2018-04-11 21:10:32] Started run 749 on task 3021, dataset 'sick'.
[2018-04-11 21:10:32] Started run 751 on task 3021, dataset 'sick'.
[2018-04-11 21:10:33] Error in run 744: Run already exists in server. Run id(s): {8944449}
[2018-04-11 21:10:33] Started run 752 on task 3021, dataset 'sick'.
[2018-04-11 21:10:35] Error in run 745: Run already exists in server. Run id(s): {8944453}
[2018-04-11 21:10:35] Started run 753 on task 3021, dataset 'sick'.
[2018-04-11 21:10:35] Error in run 746: Run already exists in server. Run id(s): {8944450}
[2018-04-11 21:10:35] Started run 754 on task 3021, dataset 'sick'.
[2018-04-11 21:10:36] Error in run 747: Run already exists in server. Run id(s): {8944451}
[2018-04-11 21:10:36] Started run 755 on task 3021, dataset 'sick'.
[2018-04-11 21:10:36] Error in run 750: Run already exists in server. Run id(s): {8944454}
[2018-04-11 21:10:36] Error in run 748: Run already exists in server. Run id(s): {8944452}
[2018-04-11 21:10:36] Started run 756 on task 3021, dataset 'sick'.
[2018-04-11 21:10:36] Started run 757 on task 3021, dataset 'sick'.
[2018-04-11 21:10:36] Error in run 749: Run already exists in server. Run id(s): {8944456}
[2018-04-11 21:10:36] Error in run 751: Run already exists in server. Run id(s): {8944455}
[2018-04-11 21:10:36] Started run 758 on task 3021, dataset 'sick'.
[2018-04-11 21:10:36] Started run 759 on task 3021, dataset 'sick'.
[2018-04-11 21:10:38] Error in run 752: Run already exists in server. Run id(s): {8944457}
[2018-04-11 21:10:38] Started run 760 on task 3021, dataset 'sick'.
[2018-04-11 21:10:40] Error in run 753: Run already exists in server. Run id(s): {8944460}
[2018-04-11 21:10:40] Error in run 754: Run already exists in server. Run id(s): {8944458}
[2018-04-11 21:10:40] Started run 761 on task 3021, dataset 'sick'.
[2018-04-11 21:10:40] Started run 762 on task 3021, dataset 'sick'.
[2018-04-11 21:10:41] Error in run 755: Run already exists in server. Run id(s): {8944459}
[2018-04-11 21:10:41] Started run 763 on task 3021, dataset 'sick'.
[2018-04-11 21:10:41] Error in run 756: Run already exists in server. Run id(s): {8944461}
[2018-04-11 21:10:41] Started run 764 on task 3021, dataset 'sick'.
[2018-04-11 21:10:41] Error in run 757: Run already exists in server. Run id(s): {8944464}
[2018-04-11 21:10:41] Started run 765 on task 3021, dataset 'sick'.
[2018-04-11 21:10:41] Error in run 759: Run already exists in server. Run id(s): {8944463}
[2018-04-11 21:10:41] Started run 766 on task 3021, dataset 'sick'.
[2018-04-11 21:10:41] Error in run 758: Run already exists in server. Run id(s): {8944462}
[2018-04-11 21:10:41] Started run 767 on task 3021, dataset 'sick'.
[2018-04-11 21:10:42] Error in run 760: Run already exists in server. Run id(s): {8944465}
[2018-04-11 21:10:42] Started run 768 on task 3021, dataset 'sick'.
[2018-04-11 21:10:44] Error in run 761: Run already exists in server. Run id(s): {8944467}
[2018-04-11 21:10:44] Error in run 762: Run already exists in server. Run id(s): {8944466}
[2018-04-11 21:10:44] Started run 769 on task 3021, dataset 'sick'.
[2018-04-11 21:10:44] Started run 770 on task 3021, dataset 'sick'.
[2018-04-11 21:10:45] Error in run 763: Run already exists in server. Run id(s): {8944468, 9016367}
[2018-04-11 21:10:45] Started run 771 on task 3021, dataset 'sick'.
[2018-04-11 21:10:45] Error in run 764: Run already exists in server. Run id(s): {8944469}
[2018-04-11 21:10:45] Error in run 765: Run already exists in server. Run id(s): {8944470}
[2018-04-11 21:10:45] Started run 772 on task 3021, dataset 'sick'.
[2018-04-11 21:10:45] Started run 773 on task 3021, dataset 'sick'.
[2018-04-11 21:10:46] Error in run 766: Run already exists in server. Run id(s): {8944471}
[2018-04-11 21:10:46] Started run 774 on task 3021, dataset 'sick'.
[2018-04-11 21:10:46] Error in run 767: Run already exists in server. Run id(s): {8944472}
[2018-04-11 21:10:46] Started run 775 on task 3021, dataset 'sick'.
[2018-04-11 21:10:47] Error in run 768: Run already exists in server. Run id(s): {8944474}
[2018-04-11 21:10:47] Started run 776 on task 3021, dataset 'sick'.
[2018-04-11 21:10:49] Error in run 769: Run already exists in server. Run id(s): {8944476}
[2018-04-11 21:10:49] Error in run 770: Run already exists in server. Run id(s): {8944473}
[2018-04-11 21:10:49] Started run 777 on task 3021, dataset 'sick'.
[2018-04-11 21:10:49] Started run 778 on task 3021, dataset 'sick'.
[2018-04-11 21:10:50] Error in run 772: Run already exists in server. Run id(s): {8944479}
[2018-04-11 21:10:50] Error in run 771: Run already exists in server. Run id(s): {8944475}
[2018-04-11 21:10:50] Started run 779 on task 3021, dataset 'sick'.
[2018-04-11 21:10:50] Error in run 773: Run already exists in server. Run id(s): {8944477}
[2018-04-11 21:10:50] Started run 780 on task 3021, dataset 'sick'.
[2018-04-11 21:10:50] Started run 781 on task 3021, dataset 'sick'.
[2018-04-11 21:10:50] Error in run 774: Run already exists in server. Run id(s): {8944478}
[2018-04-11 21:10:50] Started run 782 on task 3021, dataset 'sick'.
[2018-04-11 21:10:51] Error in run 775: Run already exists in server. Run id(s): {8944480}
[2018-04-11 21:10:51] Started run 783 on task 3021, dataset 'sick'.
[2018-04-11 21:10:51] Error in run 776: Run already exists in server. Run id(s): {8944481}
[2018-04-11 21:10:51] Started run 784 on task 3021, dataset 'sick'.
[2018-04-11 21:10:54] Error in run 778: Run already exists in server. Run id(s): {8944482}
[2018-04-11 21:10:54] Error in run 777: Run already exists in server. Run id(s): {8944484}
[2018-04-11 21:10:54] Started run 785 on task 3021, dataset 'sick'.
[2018-04-11 21:10:54] Started run 786 on task 3021, dataset 'sick'.
[2018-04-11 21:10:54] Error in run 779: Run already exists in server. Run id(s): {8944483}
[2018-04-11 21:10:54] Started run 787 on task 3021, dataset 'sick'.
[2018-04-11 21:10:55] Error in run 780: Run already exists in server. Run id(s): {8944485}
[2018-04-11 21:10:55] Started run 788 on task 3021, dataset 'sick'.
[2018-04-11 21:10:55] Error in run 781: Run already exists in server. Run id(s): {8944486}
[2018-04-11 21:10:55] Error in run 782: Run already exists in server. Run id(s): {8944487}
[2018-04-11 21:10:55] Started run 790 on task 3021, dataset 'sick'.
[2018-04-11 21:10:55] Started run 789 on task 3021, dataset 'sick'.
[2018-04-11 21:10:55] Error in run 783: Run already exists in server. Run id(s): {8944488}
[2018-04-11 21:10:55] Started run 791 on task 3021, dataset 'sick'.
[2018-04-11 21:10:56] Error in run 784: Run already exists in server. Run id(s): {8944489}
[2018-04-11 21:10:56] Started run 792 on task 3021, dataset 'sick'.
[2018-04-11 21:10:58] Error in run 785: Run already exists in server. Run id(s): {8944490}
[2018-04-11 21:10:58] Started run 793 on task 3021, dataset 'sick'.
[2018-04-11 21:10:59] Error in run 786: Run already exists in server. Run id(s): {8944491}
[2018-04-11 21:10:59] Started run 794 on task 3021, dataset 'sick'.
[2018-04-11 21:10:59] Error in run 787: Run already exists in server. Run id(s): {8944492}
[2018-04-11 21:10:59] Started run 795 on task 3021, dataset 'sick'.
[2018-04-11 21:10:59] Error in run 788: Run already exists in server. Run id(s): {8944493}
[2018-04-11 21:10:59] Started run 796 on task 3021, dataset 'sick'.
[2018-04-11 21:10:59] Error in run 789: Run already exists in server. Run id(s): {8944496}
[2018-04-11 21:10:59] Started run 797 on task 3021, dataset 'sick'.
[2018-04-11 21:10:59] Error in run 790: Run already exists in server. Run id(s): {8944495}
[2018-04-11 21:10:59] Started run 798 on task 3021, dataset 'sick'.
[2018-04-11 21:11:00] Error in run 791: Run already exists in server. Run id(s): {8944494}
[2018-04-11 21:11:00] Started run 799 on task 3021, dataset 'sick'.
[2018-04-11 21:11:01] Error in run 792: Run already exists in server. Run id(s): {8944497}
[2018-04-11 21:11:01] Started run 800 on task 3021, dataset 'sick'.
[2018-04-11 21:11:03] Error in run 793: Run already exists in server. Run id(s): {8944498}
[2018-04-11 21:11:03] Started run 801 on task 3021, dataset 'sick'.
[2018-04-11 21:11:03] Error in run 794: Run already exists in server. Run id(s): {8944500}
[2018-04-11 21:11:03] Started run 802 on task 3021, dataset 'sick'.
[2018-04-11 21:11:03] Error in run 795: Run already exists in server. Run id(s): {8944501}
[2018-04-11 21:11:03] Started run 803 on task 3021, dataset 'sick'.
[2018-04-11 21:11:03] Error in run 796: Run already exists in server. Run id(s): {8944499}
[2018-04-11 21:11:03] Started run 804 on task 3021, dataset 'sick'.
[2018-04-11 21:11:04] Error in run 797: Run already exists in server. Run id(s): {8944502}
[2018-04-11 21:11:04] Started run 805 on task 3021, dataset 'sick'.
[2018-04-11 21:11:04] Error in run 798: Run already exists in server. Run id(s): {8944503}
[2018-04-11 21:11:04] Started run 806 on task 3021, dataset 'sick'.
[2018-04-11 21:11:04] Error in run 799: Run already exists in server. Run id(s): {8944504}
[2018-04-11 21:11:04] Started run 807 on task 3021, dataset 'sick'.
[2018-04-11 21:11:05] Error in run 800: Run already exists in server. Run id(s): {8944506}
[2018-04-11 21:11:05] Started run 808 on task 3021, dataset 'sick'.
[2018-04-11 21:11:07] Error in run 801: Run already exists in server. Run id(s): {8944505}
[2018-04-11 21:11:07] Started run 809 on task 3021, dataset 'sick'.
[2018-04-11 21:11:08] Error in run 802: Run already exists in server. Run id(s): {8944508}
[2018-04-11 21:11:08] Started run 810 on task 3021, dataset 'sick'.
[2018-04-11 21:11:08] Error in run 803: Run already exists in server. Run id(s): {8944507}
[2018-04-11 21:11:08] Started run 811 on task 3021, dataset 'sick'.
[2018-04-11 21:11:08] Error in run 804: Run already exists in server. Run id(s): {8944510}
[2018-04-11 21:11:08] Error in run 805: Run already exists in server. Run id(s): {8944509}
[2018-04-11 21:11:08] Started run 812 on task 3021, dataset 'sick'.
[2018-04-11 21:11:08] Started run 813 on task 3021, dataset 'sick'.
[2018-04-11 21:11:08] Error in run 806: Run already exists in server. Run id(s): {8944511}
[2018-04-11 21:11:08] Started run 814 on task 3021, dataset 'sick'.
[2018-04-11 21:11:09] Error in run 807: Run already exists in server. Run id(s): {9016548}
[2018-04-11 21:11:09] Started run 815 on task 3021, dataset 'sick'.
[2018-04-11 21:11:10] Error in run 808: Run already exists in server. Run id(s): {8944514}
[2018-04-11 21:11:10] Started run 816 on task 3021, dataset 'sick'.
[2018-04-11 21:11:12] Error in run 809: Run already exists in server. Run id(s): {8944513}
[2018-04-11 21:11:12] Started run 817 on task 3021, dataset 'sick'.
[2018-04-11 21:11:12] Error in run 810: Run already exists in server. Run id(s): {8944515}
[2018-04-11 21:11:12] Started run 818 on task 3021, dataset 'sick'.
[2018-04-11 21:11:12] Error in run 811: Run already exists in server. Run id(s): {8944516}
[2018-04-11 21:11:12] Started run 819 on task 3021, dataset 'sick'.
[2018-04-11 21:11:13] Error in run 812: Run already exists in server. Run id(s): {8944517}
[2018-04-11 21:11:13] Started run 820 on task 3021, dataset 'sick'.
[2018-04-11 21:11:13] Error in run 813: Run already exists in server. Run id(s): {8944518}
[2018-04-11 21:11:13] Error in run 814: Run already exists in server. Run id(s): {8944519}
[2018-04-11 21:11:13] Started run 821 on task 3021, dataset 'sick'.
[2018-04-11 21:11:13] Started run 822 on task 3021, dataset 'sick'.
[2018-04-11 21:11:14] Error in run 815: Run already exists in server. Run id(s): {8944522}
[2018-04-11 21:11:14] Started run 823 on task 3021, dataset 'sick'.
[2018-04-11 21:11:15] Error in run 816: Run already exists in server. Run id(s): {8944520}
[2018-04-11 21:11:15] Started run 824 on task 3021, dataset 'sick'.
[2018-04-11 21:11:16] Error in run 817: Run already exists in server. Run id(s): {8944521}
[2018-04-11 21:11:16] Started run 825 on task 3021, dataset 'sick'.
[2018-04-11 21:11:17] Error in run 818: Run already exists in server. Run id(s): {8944523}
[2018-04-11 21:11:17] Started run 826 on task 3021, dataset 'sick'.
[2018-04-11 21:11:17] Error in run 819: Run already exists in server. Run id(s): {8944524}
[2018-04-11 21:11:17] Started run 827 on task 3021, dataset 'sick'.
[2018-04-11 21:11:17] Error in run 820: Run already exists in server. Run id(s): {8944525}
[2018-04-11 21:11:17] Started run 828 on task 3021, dataset 'sick'.
[2018-04-11 21:11:18] Error in run 822: Run already exists in server. Run id(s): {8944526}
[2018-04-11 21:11:18] Error in run 821: Run already exists in server. Run id(s): {8944527}
[2018-04-11 21:11:18] Started run 829 on task 3021, dataset 'sick'.
[2018-04-11 21:11:18] Started run 830 on task 3021, dataset 'sick'.
[2018-04-11 21:11:18] Error in run 823: Run already exists in server. Run id(s): {8944529}
[2018-04-11 21:11:18] Started run 831 on task 3021, dataset 'sick'.
[2018-04-11 21:11:19] Error in run 824: Run already exists in server. Run id(s): {8944528}
[2018-04-11 21:11:19] Started run 832 on task 3021, dataset 'sick'.
[2018-04-11 21:11:21] Error in run 825: Run already exists in server. Run id(s): {8944530}
[2018-04-11 21:11:21] Started run 833 on task 3021, dataset 'sick'.
[2018-04-11 21:11:21] Error in run 826: Run already exists in server. Run id(s): {8944531}
[2018-04-11 21:11:21] Started run 834 on task 3021, dataset 'sick'.
[2018-04-11 21:11:22] Error in run 827: Run already exists in server. Run id(s): {8944534}
[2018-04-11 21:11:22] Started run 835 on task 3021, dataset 'sick'.
[2018-04-11 21:11:22] Error in run 828: Run already exists in server. Run id(s): {8944533}
[2018-04-11 21:11:22] Started run 836 on task 3021, dataset 'sick'.
[2018-04-11 21:11:23] Error in run 829: Run already exists in server. Run id(s): {8944532}
[2018-04-11 21:11:23] Error in run 830: Run already exists in server. Run id(s): {8944535}
[2018-04-11 21:11:23] Started run 837 on task 3021, dataset 'sick'.
[2018-04-11 21:11:23] Started run 838 on task 3021, dataset 'sick'.
[2018-04-11 21:11:23] Error in run 831: Run already exists in server. Run id(s): {8944537}
[2018-04-11 21:11:23] Started run 839 on task 3021, dataset 'sick'.
[2018-04-11 21:11:24] Error in run 832: Run already exists in server. Run id(s): {8944536}
[2018-04-11 21:11:24] Started run 840 on task 3021, dataset 'sick'.
[2018-04-11 21:11:26] Error in run 833: Run already exists in server. Run id(s): {8944538}
[2018-04-11 21:11:26] Started run 841 on task 3021, dataset 'sick'.
[2018-04-11 21:11:26] Error in run 834: Run already exists in server. Run id(s): {8944539}
[2018-04-11 21:11:26] Started run 842 on task 3021, dataset 'sick'.
[2018-04-11 21:11:26] Error in run 835: Run already exists in server. Run id(s): {8944540}
[2018-04-11 21:11:26] Started run 843 on task 3021, dataset 'sick'.
[2018-04-11 21:11:27] Error in run 836: Run already exists in server. Run id(s): {8944541}
[2018-04-11 21:11:27] Started run 844 on task 3021, dataset 'sick'.
[2018-04-11 21:11:27] Error in run 838: Run already exists in server. Run id(s): {8944543}
[2018-04-11 21:11:27] Started run 845 on task 3021, dataset 'sick'.
[2018-04-11 21:11:27] Error in run 837: Run already exists in server. Run id(s): {8944542}
[2018-04-11 21:11:27] Started run 846 on task 3021, dataset 'sick'.
[2018-04-11 21:11:27] Error in run 839: Run already exists in server. Run id(s): {8944544}
[2018-04-11 21:11:27] Started run 847 on task 3021, dataset 'sick'.
[2018-04-11 21:11:28] Error in run 840: Run already exists in server. Run id(s): {8944545}
[2018-04-11 21:11:28] Started run 848 on task 3021, dataset 'sick'.
[2018-04-11 21:11:30] Error in run 841: Run already exists in server. Run id(s): {8944548}
[2018-04-11 21:11:30] Started run 849 on task 3021, dataset 'sick'.
[2018-04-11 21:11:30] Error in run 842: Run already exists in server. Run id(s): {8944546}
[2018-04-11 21:11:30] Started run 850 on task 3021, dataset 'sick'.
[2018-04-11 21:11:31] Error in run 844: Run already exists in server. Run id(s): {8944549}
[2018-04-11 21:11:31] Error in run 843: Run already exists in server. Run id(s): {8944547}
[2018-04-11 21:11:31] Started run 851 on task 3021, dataset 'sick'.
[2018-04-11 21:11:31] Started run 852 on task 3021, dataset 'sick'.
[2018-04-11 21:11:32] Error in run 846: Run already exists in server. Run id(s): {8944551}
[2018-04-11 21:11:32] Started run 853 on task 3021, dataset 'sick'.
[2018-04-11 21:11:32] Error in run 847: Run already exists in server. Run id(s): {8944553}
[2018-04-11 21:11:32] Error in run 845: Run already exists in server. Run id(s): {8944550}
[2018-04-11 21:11:32] Started run 854 on task 3021, dataset 'sick'.
[2018-04-11 21:11:32] Started run 855 on task 3021, dataset 'sick'.
[2018-04-11 21:11:33] Error in run 848: Run already exists in server. Run id(s): {8944552}
[2018-04-11 21:11:33] Started run 856 on task 3021, dataset 'sick'.
[2018-04-11 21:11:35] Error in run 850: Run already exists in server. Run id(s): {8944555}
[2018-04-11 21:11:35] Error in run 849: Run already exists in server. Run id(s): {8944554}
[2018-04-11 21:11:35] Started run 857 on task 3021, dataset 'sick'.
[2018-04-11 21:11:35] Started run 858 on task 3021, dataset 'sick'.
[2018-04-11 21:11:36] Error in run 851: Run already exists in server. Run id(s): {8944556}
[2018-04-11 21:11:36] Started run 859 on task 3021, dataset 'sick'.
[2018-04-11 21:11:36] Error in run 852: Run already exists in server. Run id(s): {8944557}
[2018-04-11 21:11:36] Started run 860 on task 3021, dataset 'sick'.
[2018-04-11 21:11:36] Error in run 853: Run already exists in server. Run id(s): {8944559}
[2018-04-11 21:11:36] Started run 861 on task 3021, dataset 'sick'.
[2018-04-11 21:11:37] Error in run 855: Run already exists in server. Run id(s): {8944560}
[2018-04-11 21:11:37] Started run 862 on task 3021, dataset 'sick'.
[2018-04-11 21:11:37] Error in run 854: Run already exists in server. Run id(s): {8944558}
[2018-04-11 21:11:37] Started run 863 on task 3021, dataset 'sick'.
[2018-04-11 21:11:38] Error in run 856: Run already exists in server. Run id(s): {8944561}
[2018-04-11 21:11:38] Started run 864 on task 3021, dataset 'sick'.
[2018-04-11 21:11:40] Error in run 857: Run already exists in server. Run id(s): {8944562}
[2018-04-11 21:11:40] Started run 865 on task 3021, dataset 'sick'.
[2018-04-11 21:11:40] Error in run 858: Run already exists in server. Run id(s): {8944563}
[2018-04-11 21:11:40] Started run 866 on task 3021, dataset 'sick'.
[2018-04-11 21:11:40] Error in run 859: Run already exists in server. Run id(s): {8944564}
[2018-04-11 21:11:40] Started run 867 on task 3021, dataset 'sick'.
[2018-04-11 21:11:41] Error in run 860: Run already exists in server. Run id(s): {8944565}
[2018-04-11 21:11:41] Started run 868 on task 3021, dataset 'sick'.
[2018-04-11 21:11:41] Error in run 861: Run already exists in server. Run id(s): {8944566}
[2018-04-11 21:11:41] Started run 869 on task 3021, dataset 'sick'.
[2018-04-11 21:11:41] Error in run 863: Run already exists in server. Run id(s): {8944568}
[2018-04-11 21:11:41] Error in run 862: Run already exists in server. Run id(s): {8944567}
[2018-04-11 21:11:41] Started run 870 on task 3021, dataset 'sick'.
[2018-04-11 21:11:41] Started run 871 on task 3021, dataset 'sick'.
[2018-04-11 21:11:42] Error in run 864: Run already exists in server. Run id(s): {8944569}
[2018-04-11 21:11:42] Started run 872 on task 3021, dataset 'sick'.
[2018-04-11 21:11:44] Error in run 865: Run already exists in server. Run id(s): {8944570}
[2018-04-11 21:11:44] Started run 873 on task 3021, dataset 'sick'.
[2018-04-11 21:11:45] Error in run 866: Run already exists in server. Run id(s): {8944571}
[2018-04-11 21:11:45] Error in run 867: Run already exists in server. Run id(s): {8944572}
[2018-04-11 21:11:45] Started run 874 on task 3021, dataset 'sick'.
[2018-04-11 21:11:45] Started run 875 on task 3021, dataset 'sick'.
[2018-04-11 21:11:45] Error in run 868: Run already exists in server. Run id(s): {8944573}
[2018-04-11 21:11:45] Started run 876 on task 3021, dataset 'sick'.
[2018-04-11 21:11:46] Error in run 869: Run already exists in server. Run id(s): {8944574}
[2018-04-11 21:11:46] Started run 877 on task 3021, dataset 'sick'.
[2018-04-11 21:11:46] Error in run 870: Run already exists in server. Run id(s): {8944575}
[2018-04-11 21:11:46] Error in run 871: Run already exists in server. Run id(s): {8944576}
[2018-04-11 21:11:46] Started run 878 on task 3021, dataset 'sick'.
[2018-04-11 21:11:46] Started run 879 on task 3021, dataset 'sick'.
[2018-04-11 21:11:47] Error in run 872: Run already exists in server. Run id(s): {8944577}
[2018-04-11 21:11:47] Started run 880 on task 3021, dataset 'sick'.
[2018-04-11 21:11:49] Error in run 873: Run already exists in server. Run id(s): {8944578}
[2018-04-11 21:11:49] Started run 881 on task 3021, dataset 'sick'.
[2018-04-11 21:11:50] Error in run 875: Run already exists in server. Run id(s): {8944580}
[2018-04-11 21:11:50] Error in run 874: Run already exists in server. Run id(s): {8944579}
[2018-04-11 21:11:50] Started run 882 on task 3021, dataset 'sick'.
[2018-04-11 21:11:50] Started run 883 on task 3021, dataset 'sick'.
[2018-04-11 21:11:50] Error in run 876: Run already exists in server. Run id(s): {8944582}
[2018-04-11 21:11:50] Error in run 877: Run already exists in server. Run id(s): {8944581}
[2018-04-11 21:11:50] Started run 884 on task 3021, dataset 'sick'.
[2018-04-11 21:11:50] Started run 885 on task 3021, dataset 'sick'.
[2018-04-11 21:11:51] Error in run 878: Run already exists in server. Run id(s): {8944583}
[2018-04-11 21:11:51] Error in run 879: Run already exists in server. Run id(s): {8944584}
[2018-04-11 21:11:51] Started run 886 on task 3021, dataset 'sick'.
[2018-04-11 21:11:51] Started run 887 on task 3021, dataset 'sick'.
[2018-04-11 21:11:52] Error in run 880: Run already exists in server. Run id(s): {8944585}
[2018-04-11 21:11:52] Started run 888 on task 3021, dataset 'sick'.
[2018-04-11 21:11:53] Error in run 881: Run already exists in server. Run id(s): {8944586}
[2018-04-11 21:11:53] Started run 889 on task 3021, dataset 'sick'.
[2018-04-11 21:11:54] Error in run 883: Run already exists in server. Run id(s): {8944588}
[2018-04-11 21:11:54] Started run 890 on task 3021, dataset 'sick'.
[2018-04-11 21:11:54] Error in run 882: Run already exists in server. Run id(s): {8944587}
[2018-04-11 21:11:54] Started run 891 on task 3021, dataset 'sick'.
[2018-04-11 21:11:55] Error in run 884: Run already exists in server. Run id(s): {8944590}
[2018-04-11 21:11:55] Started run 892 on task 3021, dataset 'sick'.
[2018-04-11 21:11:55] Error in run 885: Run already exists in server. Run id(s): {8944589}
[2018-04-11 21:11:55] Started run 893 on task 3021, dataset 'sick'.
[2018-04-11 21:11:56] Error in run 886: Run already exists in server. Run id(s): {8944591}
[2018-04-11 21:11:56] Started run 894 on task 3021, dataset 'sick'.
[2018-04-11 21:11:56] Error in run 887: Run already exists in server. Run id(s): {8944592}
[2018-04-11 21:11:56] Started run 895 on task 3021, dataset 'sick'.
[2018-04-11 21:11:57] Error in run 888: Run already exists in server. Run id(s): {8944593}
[2018-04-11 21:11:57] Started run 896 on task 3021, dataset 'sick'.
[2018-04-11 21:11:58] Error in run 889: Run already exists in server. Run id(s): {8944594}
[2018-04-11 21:11:58] Started run 897 on task 3021, dataset 'sick'.
[2018-04-11 21:11:59] Error in run 890: Run already exists in server. Run id(s): {8944595}
[2018-04-11 21:11:59] Started run 898 on task 3021, dataset 'sick'.
[2018-04-11 21:11:59] Error in run 891: Run already exists in server. Run id(s): {8944596}
[2018-04-11 21:11:59] Started run 899 on task 3021, dataset 'sick'.
[2018-04-11 21:11:59] Error in run 892: Run already exists in server. Run id(s): {8944597}
[2018-04-11 21:11:59] Started run 900 on task 3021, dataset 'sick'.
[2018-04-11 21:11:59] Error in run 893: Run already exists in server. Run id(s): {8944598}
[2018-04-11 21:11:59] Started run 901 on task 3021, dataset 'sick'.
[2018-04-11 21:12:00] Error in run 894: Run already exists in server. Run id(s): {8944599}
[2018-04-11 21:12:00] Started run 902 on task 3021, dataset 'sick'.
[2018-04-11 21:12:01] Error in run 895: Run already exists in server. Run id(s): {8944603}
[2018-04-11 21:12:01] Started run 903 on task 3021, dataset 'sick'.
[2018-04-11 21:12:01] Error in run 896: Run already exists in server. Run id(s): {8944600}
[2018-04-11 21:12:01] Started run 904 on task 3021, dataset 'sick'.
[2018-04-11 21:12:02] Error in run 897: Run already exists in server. Run id(s): {8944602}
[2018-04-11 21:12:02] Started run 905 on task 3021, dataset 'sick'.
[2018-04-11 21:12:03] Error in run 898: Run already exists in server. Run id(s): {8944601}
[2018-04-11 21:12:03] Started run 906 on task 3021, dataset 'sick'.
[2018-04-11 21:12:04] Error in run 899: Run already exists in server. Run id(s): {8944604}
[2018-04-11 21:12:04] Started run 907 on task 3021, dataset 'sick'.
[2018-04-11 21:12:04] Error in run 900: Run already exists in server. Run id(s): {8944605}
[2018-04-11 21:12:04] Started run 908 on task 3021, dataset 'sick'.
[2018-04-11 21:12:04] Error in run 901: Run already exists in server. Run id(s): {8944607}
[2018-04-11 21:12:04] Started run 909 on task 3021, dataset 'sick'.
[2018-04-11 21:12:05] Error in run 902: Run already exists in server. Run id(s): {8944606}
[2018-04-11 21:12:05] Started run 910 on task 3021, dataset 'sick'.
[2018-04-11 21:12:05] Error in run 903: Run already exists in server. Run id(s): {8944609}
[2018-04-11 21:12:05] Started run 911 on task 3021, dataset 'sick'.
[2018-04-11 21:12:06] Error in run 904: Run already exists in server. Run id(s): {8944608}
[2018-04-11 21:12:06] Started run 912 on task 3021, dataset 'sick'.
[2018-04-11 21:12:07] Error in run 905: Run already exists in server. Run id(s): {8944610}
[2018-04-11 21:12:07] Started run 913 on task 3021, dataset 'sick'.
[2018-04-11 21:12:08] Error in run 906: Run already exists in server. Run id(s): {8944611}
[2018-04-11 21:12:08] Started run 914 on task 3021, dataset 'sick'.
[2018-04-11 21:12:08] Error in run 907: Run already exists in server. Run id(s): {8944613}
[2018-04-11 21:12:08] Started run 915 on task 3021, dataset 'sick'.
[2018-04-11 21:12:09] Error in run 908: Run already exists in server. Run id(s): {8944612}
[2018-04-11 21:12:09] Error in run 909: Run already exists in server. Run id(s): {8944614}
[2018-04-11 21:12:09] Started run 916 on task 3021, dataset 'sick'.
[2018-04-11 21:12:09] Started run 917 on task 3021, dataset 'sick'.
[2018-04-11 21:12:09] Error in run 910: Run already exists in server. Run id(s): {8944615}
[2018-04-11 21:12:09] Started run 918 on task 3021, dataset 'sick'.
[2018-04-11 21:12:09] Error in run 911: Run already exists in server. Run id(s): {8944616}
[2018-04-11 21:12:09] Started run 919 on task 3021, dataset 'sick'.
[2018-04-11 21:12:11] Error in run 912: Run already exists in server. Run id(s): {8944617}
[2018-04-11 21:12:11] Started run 920 on task 3021, dataset 'sick'.
[2018-04-11 21:12:12] Error in run 913: Run already exists in server. Run id(s): {8944618}
[2018-04-11 21:12:12] Started run 921 on task 3021, dataset 'sick'.
[2018-04-11 21:12:12] Error in run 914: Run already exists in server. Run id(s): {8944620}
[2018-04-11 21:12:12] Started run 922 on task 3021, dataset 'sick'.
[2018-04-11 21:12:13] Error in run 915: Run already exists in server. Run id(s): {8944619}
[2018-04-11 21:12:13] Started run 923 on task 3021, dataset 'sick'.
[2018-04-11 21:12:13] Error in run 916: Run already exists in server. Run id(s): {8944622}
[2018-04-11 21:12:13] Started run 924 on task 3021, dataset 'sick'.
[2018-04-11 21:12:13] Error in run 917: Run already exists in server. Run id(s): {8944621}
[2018-04-11 21:12:13] Started run 925 on task 3021, dataset 'sick'.
[2018-04-11 21:12:14] Error in run 918: Run already exists in server. Run id(s): {8944623}
[2018-04-11 21:12:14] Started run 926 on task 3021, dataset 'sick'.
[2018-04-11 21:12:14] Error in run 919: Run already exists in server. Run id(s): {8944624}
[2018-04-11 21:12:14] Started run 927 on task 3021, dataset 'sick'.
[2018-04-11 21:12:15] Error in run 920: Run already exists in server. Run id(s): {8944626}
[2018-04-11 21:12:15] Started run 928 on task 3021, dataset 'sick'.
[2018-04-11 21:12:16] Error in run 921: Run already exists in server. Run id(s): {8944625}
[2018-04-11 21:12:16] Started run 929 on task 3021, dataset 'sick'.
[2018-04-11 21:12:17] Error in run 923: Run already exists in server. Run id(s): {8944629}
[2018-04-11 21:12:17] Started run 930 on task 3021, dataset 'sick'.
[2018-04-11 21:12:17] Error in run 922: Run already exists in server. Run id(s): {8944627}
[2018-04-11 21:12:17] Started run 931 on task 3021, dataset 'sick'.
[2018-04-11 21:12:18] Error in run 925: Run already exists in server. Run id(s): {8944631}
[2018-04-11 21:12:18] Error in run 924: Run already exists in server. Run id(s): {8944628}
[2018-04-11 21:12:18] Started run 932 on task 3021, dataset 'sick'.
[2018-04-11 21:12:18] Started run 933 on task 3021, dataset 'sick'.
[2018-04-11 21:12:19] Error in run 926: Run already exists in server. Run id(s): {8944630}
[2018-04-11 21:12:19] Started run 934 on task 3021, dataset 'sick'.
[2018-04-11 21:12:19] Error in run 927: Run already exists in server. Run id(s): {8944632}
[2018-04-11 21:12:19] Started run 935 on task 3021, dataset 'sick'.
[2018-04-11 21:12:20] Error in run 928: Run already exists in server. Run id(s): {8944633}
[2018-04-11 21:12:20] Started run 936 on task 3021, dataset 'sick'.
[2018-04-11 21:12:21] Error in run 929: Run already exists in server. Run id(s): {8944636, 9016900}
[2018-04-11 21:12:21] Started run 937 on task 3021, dataset 'sick'.
[2018-04-11 21:12:22] Error in run 930: Run already exists in server. Run id(s): {8944634}
[2018-04-11 21:12:22] Started run 938 on task 3021, dataset 'sick'.
[2018-04-11 21:12:22] Error in run 931: Run already exists in server. Run id(s): {8944635}
[2018-04-11 21:12:22] Started run 939 on task 3021, dataset 'sick'.
[2018-04-11 21:12:23] Error in run 933: Run already exists in server. Run id(s): {8944637}
[2018-04-11 21:12:23] Error in run 932: Run already exists in server. Run id(s): {8944639}
[2018-04-11 21:12:23] Started run 940 on task 3021, dataset 'sick'.
[2018-04-11 21:12:23] Started run 941 on task 3021, dataset 'sick'.
[2018-04-11 21:12:23] Error in run 935: Run already exists in server. Run id(s): {8944640}
[2018-04-11 21:12:23] Started run 942 on task 3021, dataset 'sick'.
[2018-04-11 21:12:23] Error in run 934: Run already exists in server. Run id(s): {8944638}
[2018-04-11 21:12:23] Started run 943 on task 3021, dataset 'sick'.
[2018-04-11 21:12:24] Error in run 936: Run already exists in server. Run id(s): {8944641}
[2018-04-11 21:12:24] Started run 944 on task 3021, dataset 'sick'.
[2018-04-11 21:12:26] Error in run 937: Run already exists in server. Run id(s): {8944643}
[2018-04-11 21:12:26] Started run 945 on task 3021, dataset 'sick'.
[2018-04-11 21:12:26] Error in run 938: Run already exists in server. Run id(s): {8944642}
[2018-04-11 21:12:26] Started run 946 on task 3021, dataset 'sick'.
[2018-04-11 21:12:27] Error in run 939: Run already exists in server. Run id(s): {8944646}
[2018-04-11 21:12:27] Started run 947 on task 3021, dataset 'sick'.
[2018-04-11 21:12:27] Error in run 940: Run already exists in server. Run id(s): {8944644}
[2018-04-11 21:12:27] Started run 948 on task 3021, dataset 'sick'.
[2018-04-11 21:12:27] Error in run 941: Run already exists in server. Run id(s): {8944645}
[2018-04-11 21:12:27] Started run 949 on task 3021, dataset 'sick'.
[2018-04-11 21:12:28] Error in run 942: Run already exists in server. Run id(s): {8944647}
[2018-04-11 21:12:28] Started run 950 on task 3021, dataset 'sick'.
[2018-04-11 21:12:28] Error in run 943: Run already exists in server. Run id(s): {8944648}
[2018-04-11 21:12:28] Started run 951 on task 3021, dataset 'sick'.
[2018-04-11 21:12:29] Error in run 944: Run already exists in server. Run id(s): {8944649}
[2018-04-11 21:12:29] Started run 952 on task 3021, dataset 'sick'.
[2018-04-11 21:12:30] Error in run 945: Run already exists in server. Run id(s): {8944650}
[2018-04-11 21:12:30] Started run 953 on task 3021, dataset 'sick'.
[2018-04-11 21:12:31] Error in run 946: Run already exists in server. Run id(s): {8944651}
[2018-04-11 21:12:31] Started run 954 on task 3021, dataset 'sick'.
[2018-04-11 21:12:31] Error in run 947: Run already exists in server. Run id(s): {8944652}
[2018-04-11 21:12:31] Started run 955 on task 3021, dataset 'sick'.
[2018-04-11 21:12:32] Error in run 948: Run already exists in server. Run id(s): {8944653}
[2018-04-11 21:12:32] Started run 956 on task 3021, dataset 'sick'.
[2018-04-11 21:12:32] Error in run 949: Run already exists in server. Run id(s): {8944654}
[2018-04-11 21:12:32] Started run 957 on task 3021, dataset 'sick'.
[2018-04-11 21:12:32] Error in run 950: Run already exists in server. Run id(s): {8944655}
[2018-04-11 21:12:32] Started run 958 on task 3021, dataset 'sick'.
[2018-04-11 21:12:33] Error in run 951: Run already exists in server. Run id(s): {8944656}
[2018-04-11 21:12:33] Started run 959 on task 3021, dataset 'sick'.
[2018-04-11 21:12:33] Error in run 952: Run already exists in server. Run id(s): {8944658}
[2018-04-11 21:12:33] Started run 960 on task 3021, dataset 'sick'.
[2018-04-11 21:12:35] Error in run 953: Run already exists in server. Run id(s): {8944657}
[2018-04-11 21:12:35] Started run 961 on task 3021, dataset 'sick'.
[2018-04-11 21:12:35] Error in run 954: Run already exists in server. Run id(s): {8944659}
[2018-04-11 21:12:35] Started run 962 on task 3021, dataset 'sick'.
[2018-04-11 21:12:36] Error in run 955: Run already exists in server. Run id(s): {8944660}
[2018-04-11 21:12:36] Started run 963 on task 3021, dataset 'sick'.
[2018-04-11 21:12:36] Error in run 956: Run already exists in server. Run id(s): {8944661}
[2018-04-11 21:12:36] Started run 964 on task 3021, dataset 'sick'.
[2018-04-11 21:12:36] Error in run 957: Run already exists in server. Run id(s): {8944662}
[2018-04-11 21:12:36] Started run 965 on task 3021, dataset 'sick'.
[2018-04-11 21:12:37] Error in run 958: Run already exists in server. Run id(s): {8944663}
[2018-04-11 21:12:37] Started run 966 on task 3021, dataset 'sick'.
[2018-04-11 21:12:38] Error in run 959: Run already exists in server. Run id(s): {8944664}
[2018-04-11 21:12:38] Started run 967 on task 3021, dataset 'sick'.
[2018-04-11 21:12:38] Error in run 960: Run already exists in server. Run id(s): {8944665}
[2018-04-11 21:12:38] Started run 968 on task 3021, dataset 'sick'.
[2018-04-11 21:12:39] Error in run 961: Run already exists in server. Run id(s): {8944666}
[2018-04-11 21:12:39] Started run 969 on task 3021, dataset 'sick'.
[2018-04-11 21:12:40] Error in run 962: Run already exists in server. Run id(s): {8944667}
[2018-04-11 21:12:40] Error in run 963: Run already exists in server. Run id(s): {8944670}
[2018-04-11 21:12:40] Started run 970 on task 3021, dataset 'sick'.
[2018-04-11 21:12:40] Started run 971 on task 3021, dataset 'sick'.
[2018-04-11 21:12:41] Error in run 964: Run already exists in server. Run id(s): {8944668}
[2018-04-11 21:12:41] Started run 972 on task 3021, dataset 'sick'.
[2018-04-11 21:12:41] Error in run 965: Run already exists in server. Run id(s): {8944669}
[2018-04-11 21:12:41] Started run 973 on task 3021, dataset 'sick'.
[2018-04-11 21:12:41] Error in run 966: Run already exists in server. Run id(s): {8944671}
[2018-04-11 21:12:41] Started run 974 on task 3021, dataset 'sick'.
[2018-04-11 21:12:42] Error in run 967: Run already exists in server. Run id(s): {8944672}
[2018-04-11 21:12:42] Started run 975 on task 3021, dataset 'sick'.
[2018-04-11 21:12:42] Error in run 968: Run already exists in server. Run id(s): {8944673}
[2018-04-11 21:12:42] Started run 976 on task 3021, dataset 'sick'.
[2018-04-11 21:12:44] Error in run 969: Run already exists in server. Run id(s): {8944675}
[2018-04-11 21:12:44] Started run 977 on task 3021, dataset 'sick'.
[2018-04-11 21:12:45] Error in run 970: Run already exists in server. Run id(s): {8944674, 9017014}
[2018-04-11 21:12:45] Error in run 971: Run already exists in server. Run id(s): {8944676}
[2018-04-11 21:12:45] Started run 978 on task 3021, dataset 'sick'.
[2018-04-11 21:12:45] Started run 979 on task 3021, dataset 'sick'.
[2018-04-11 21:12:45] Error in run 972: Run already exists in server. Run id(s): {8944677}
[2018-04-11 21:12:45] Started run 980 on task 3021, dataset 'sick'.
[2018-04-11 21:12:46] Error in run 973: Run already exists in server. Run id(s): {8944678}
[2018-04-11 21:12:46] Started run 981 on task 3021, dataset 'sick'.
[2018-04-11 21:12:46] Error in run 974: Run already exists in server. Run id(s): {8944681}
[2018-04-11 21:12:46] Started run 982 on task 3021, dataset 'sick'.
[2018-04-11 21:12:47] Error in run 975: Run already exists in server. Run id(s): {8944679}
[2018-04-11 21:12:47] Started run 983 on task 3021, dataset 'sick'.
[2018-04-11 21:12:47] Error in run 976: Run already exists in server. Run id(s): {8944680}
[2018-04-11 21:12:47] Started run 984 on task 3021, dataset 'sick'.
[2018-04-11 21:12:48] Error in run 977: Run already exists in server. Run id(s): {8944682}
[2018-04-11 21:12:48] Started run 985 on task 3021, dataset 'sick'.
[2018-04-11 21:12:49] Error in run 978: Run already exists in server. Run id(s): {8944683}
[2018-04-11 21:12:49] Started run 986 on task 3021, dataset 'sick'.
[2018-04-11 21:12:50] Error in run 979: Run already exists in server. Run id(s): {8944684}
[2018-04-11 21:12:50] Error in run 980: Run already exists in server. Run id(s): {8944685}
[2018-04-11 21:12:50] Started run 987 on task 3021, dataset 'sick'.
[2018-04-11 21:12:50] Started run 988 on task 3021, dataset 'sick'.
[2018-04-11 21:12:50] Error in run 981: Run already exists in server. Run id(s): {8944686}
[2018-04-11 21:12:50] Started run 989 on task 3021, dataset 'sick'.
[2018-04-11 21:12:50] Error in run 982: Run already exists in server. Run id(s): {8944687}
[2018-04-11 21:12:50] Started run 990 on task 3021, dataset 'sick'.
[2018-04-11 21:12:51] Error in run 983: Run already exists in server. Run id(s): {8944688}
[2018-04-11 21:12:51] Started run 991 on task 3021, dataset 'sick'.
[2018-04-11 21:12:52] Error in run 984: Run already exists in server. Run id(s): {8944692}
[2018-04-11 21:12:52] Started run 992 on task 3021, dataset 'sick'.
[2018-04-11 21:12:53] Error in run 985: Run already exists in server. Run id(s): {8944689}
[2018-04-11 21:12:53] Started run 993 on task 3021, dataset 'sick'.
[2018-04-11 21:12:54] Error in run 986: Run already exists in server. Run id(s): {8944690}
[2018-04-11 21:12:54] Started run 994 on task 3021, dataset 'sick'.
[2018-04-11 21:12:54] Error in run 987: Run already exists in server. Run id(s): {8944691}
[2018-04-11 21:12:54] Started run 995 on task 3021, dataset 'sick'.
[2018-04-11 21:12:54] Error in run 988: Run already exists in server. Run id(s): {8944693}
[2018-04-11 21:12:54] Started run 996 on task 3021, dataset 'sick'.
[2018-04-11 21:12:55] Error in run 990: Run already exists in server. Run id(s): {8944695}
[2018-04-11 21:12:55] Started run 997 on task 3021, dataset 'sick'.
[2018-04-11 21:12:55] Error in run 989: Run already exists in server. Run id(s): {8944694}
[2018-04-11 21:12:55] Started run 998 on task 3021, dataset 'sick'.
[2018-04-11 21:12:56] Error in run 991: Run already exists in server. Run id(s): {8944696}
[2018-04-11 21:12:56] Started run 999 on task 3021, dataset 'sick'.
[2018-04-11 21:12:56] Error in run 992: Run already exists in server. Run id(s): {9017117}
[2018-04-11 21:12:56] Started run 1000 on task 3021, dataset 'sick'.
[2018-04-11 21:12:57] Error in run 993: Run already exists in server. Run id(s): {8944698}
[2018-04-11 21:12:58] Error in run 994: Run already exists in server. Run id(s): {8944700}
[2018-04-11 21:12:59] Error in run 995: Run already exists in server. Run id(s): {8944699}
[2018-04-11 21:12:59] Error in run 996: Run already exists in server. Run id(s): {8944701}
[2018-04-11 21:13:00] Error in run 997: Run already exists in server. Run id(s): {8944702}
[2018-04-11 21:13:00] Error in run 998: Run already exists in server. Run id(s): {8944703}
[2018-04-11 21:13:01] Error in run 999: Run already exists in server. Run id(s): {8944704}
[2018-04-11 21:13:01] Error in run 1000: Run already exists in server. Run id(s): {8944705}
