declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00028/certs"
declare -x AZ_BATCH_JOB_ID="svm"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/svm/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/svm/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_9-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00028"
declare -x AZ_BATCH_TASK_ID="task-00028"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/svm/job-1/task-00028/wd"
declare -x HOME="/mnt/batch/tasks/workitems/svm/job-1/task-00028/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/svm/job-1/task-00028/wd"
declare -x PWD="/mnt/batch/tasks/workitems/svm/job-1/task-00028/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 20:12:20] Results will not be logged locally.
[2018-04-11 20:12:20] Retrieving tasks...
[2018-04-11 20:12:20] Tasks will be retrieved based on provided task ids.
[2018-04-11 20:12:20] The following tasks were retrieved: [9985].
[2018-04-11 20:12:28] Downloaded task 9985.
[2018-04-11 20:12:29] Prepared pipelines.
[2018-04-11 20:12:29] Started run 1 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:29] Started run 6 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:29] Started run 2 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:29] Started run 3 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:29] Started run 4 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:29] Started run 5 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:29] Started run 7 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:29] Started run 8 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Error in run 6: Run already exists in server. Run id(s): {8969202}
[2018-04-11 20:12:34] Started run 9 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Error in run 2: Run already exists in server. Run id(s): {8969176}
[2018-04-11 20:12:34] Started run 10 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Error in run 1: Run already exists in server. Run id(s): {8969178}
[2018-04-11 20:12:34] Error in run 3: Run already exists in server. Run id(s): {8969174}
[2018-04-11 20:12:34] Started run 11 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Started run 12 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Error in run 4: Run already exists in server. Run id(s): {8969191}
[2018-04-11 20:12:34] Started run 13 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Error in run 5: Run already exists in server. Run id(s): {8969204}
[2018-04-11 20:12:34] Started run 14 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Error in run 7: Run already exists in server. Run id(s): {8969211}
[2018-04-11 20:12:34] Started run 15 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:34] Error in run 8: Run already exists in server. Run id(s): {8969215}
[2018-04-11 20:12:34] Started run 16 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:38] Error in run 11: Run already exists in server. Run id(s): {8969235}
[2018-04-11 20:12:38] Error in run 9: Run already exists in server. Run id(s): {8969225}
[2018-04-11 20:12:38] Error in run 12: Run already exists in server. Run id(s): {8969241}
[2018-04-11 20:12:38] Error in run 10: Run already exists in server. Run id(s): {8969232}
[2018-04-11 20:12:38] Started run 17 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:38] Started run 18 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:38] Started run 19 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:38] Started run 20 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:38] Error in run 13: Run already exists in server. Run id(s): {8969270}
[2018-04-11 20:12:38] Error in run 14: Run already exists in server. Run id(s): {8969257}
[2018-04-11 20:12:38] Started run 21 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:38] Started run 22 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:39] Error in run 15: Run already exists in server. Run id(s): {8969258}
[2018-04-11 20:12:39] Started run 23 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:39] Error in run 16: Run already exists in server. Run id(s): {8969269}
[2018-04-11 20:12:39] Started run 24 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Error in run 19: Run already exists in server. Run id(s): {8969310}
[2018-04-11 20:12:43] Started run 25 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Error in run 17: Run already exists in server. Run id(s): {8969295}
[2018-04-11 20:12:43] Error in run 18: Run already exists in server. Run id(s): {8969291}
[2018-04-11 20:12:43] Started run 26 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Error in run 22: Run already exists in server. Run id(s): {8969337}
[2018-04-11 20:12:43] Error in run 20: Run already exists in server. Run id(s): {8969305}
[2018-04-11 20:12:43] Error in run 21: Run already exists in server. Run id(s): {8969328}
[2018-04-11 20:12:43] Started run 28 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Started run 29 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Started run 30 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Started run 27 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Error in run 23: Run already exists in server. Run id(s): {8969343}
[2018-04-11 20:12:43] Error in run 24: Run already exists in server. Run id(s): {8969349}
[2018-04-11 20:12:43] Started run 31 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:43] Started run 32 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:47] Error in run 25: Run already exists in server. Run id(s): {8969397}
[2018-04-11 20:12:47] Started run 33 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:48] Error in run 26: Run already exists in server. Run id(s): {8969394}
[2018-04-11 20:12:48] Error in run 30: Run already exists in server. Run id(s): {8969445}
[2018-04-11 20:12:48] Started run 34 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:48] Started run 35 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:48] Error in run 27: Run already exists in server. Run id(s): {8969407}
[2018-04-11 20:12:48] Error in run 31: Run already exists in server. Run id(s): {8969449}
[2018-04-11 20:12:48] Started run 36 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:48] Error in run 32: Run already exists in server. Run id(s): {8969456}
[2018-04-11 20:12:48] Started run 37 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:48] Started run 38 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:48] Error in run 29: Run already exists in server. Run id(s): {8969444}
[2018-04-11 20:12:48] Error in run 28: Run already exists in server. Run id(s): {8969396}
[2018-04-11 20:12:48] Started run 39 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:48] Started run 40 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Error in run 33: Run already exists in server. Run id(s): {8969489}
[2018-04-11 20:12:52] Started run 41 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Error in run 35: Run already exists in server. Run id(s): {8969504}
[2018-04-11 20:12:52] Error in run 34: Run already exists in server. Run id(s): {8969493}
[2018-04-11 20:12:52] Started run 42 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Started run 43 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Error in run 37: Run already exists in server. Run id(s): {8969545}
[2018-04-11 20:12:52] Error in run 40: Run already exists in server. Run id(s): {8969558}
[2018-04-11 20:12:52] Error in run 38: Run already exists in server. Run id(s): {8969571}
[2018-04-11 20:12:52] Error in run 39: Run already exists in server. Run id(s): {8969557}
[2018-04-11 20:12:52] Started run 44 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Error in run 36: Run already exists in server. Run id(s): {8969501}
[2018-04-11 20:12:52] Started run 45 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Started run 46 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Started run 47 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:52] Started run 48 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Error in run 41: Run already exists in server. Run id(s): {8969590}
[2018-04-11 20:12:57] Started run 49 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Error in run 42: Run already exists in server. Run id(s): {8969598}
[2018-04-11 20:12:57] Started run 50 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Error in run 43: Run already exists in server. Run id(s): {8969599}
[2018-04-11 20:12:57] Started run 51 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Error in run 44: Run already exists in server. Run id(s): {8969625}
[2018-04-11 20:12:57] Started run 52 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Error in run 46: Run already exists in server. Run id(s): {8969642}
[2018-04-11 20:12:57] Started run 53 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Error in run 48: Run already exists in server. Run id(s): {8969675}
[2018-04-11 20:12:57] Error in run 45: Run already exists in server. Run id(s): {8969627}
[2018-04-11 20:12:57] Started run 54 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Error in run 47: Run already exists in server. Run id(s): {8969653}
[2018-04-11 20:12:57] Started run 55 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:12:57] Started run 56 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:01] Error in run 49: Run already exists in server. Run id(s): {8969669}
[2018-04-11 20:13:01] Started run 57 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:01] Error in run 50: Run already exists in server. Run id(s): {8969684}
[2018-04-11 20:13:01] Started run 58 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:01] Error in run 51: Run already exists in server. Run id(s): {8969689}
[2018-04-11 20:13:01] Started run 59 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:01] Error in run 52: Run already exists in server. Run id(s): {8969712}
[2018-04-11 20:13:01] Started run 60 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:01] Error in run 53: Run already exists in server. Run id(s): {8969702}
[2018-04-11 20:13:01] Started run 61 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:01] Error in run 54: Run already exists in server. Run id(s): {8969715}
[2018-04-11 20:13:01] Started run 62 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:02] Error in run 56: Run already exists in server. Run id(s): {8969738}
[2018-04-11 20:13:02] Error in run 55: Run already exists in server. Run id(s): {8969720}
[2018-04-11 20:13:02] Started run 63 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:02] Started run 64 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Error in run 57: Run already exists in server. Run id(s): {8969744}
[2018-04-11 20:13:06] Started run 65 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Error in run 58: Run already exists in server. Run id(s): {8969749}
[2018-04-11 20:13:06] Started run 66 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Error in run 59: Run already exists in server. Run id(s): {8969754}
[2018-04-11 20:13:06] Started run 67 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Error in run 60: Run already exists in server. Run id(s): {8969843}
[2018-04-11 20:13:06] Started run 68 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Error in run 61: Run already exists in server. Run id(s): {8969892}
[2018-04-11 20:13:06] Error in run 62: Run already exists in server. Run id(s): {8969915}
[2018-04-11 20:13:06] Started run 69 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Started run 70 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Error in run 63: Run already exists in server. Run id(s): {8969903}
[2018-04-11 20:13:06] Started run 71 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:06] Error in run 64: Run already exists in server. Run id(s): {8969944}
[2018-04-11 20:13:06] Started run 72 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:10] Error in run 65: Run already exists in server. Run id(s): {9014085}
[2018-04-11 20:13:10] Started run 73 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:10] Error in run 68: Run already exists in server. Run id(s): {9014103}
[2018-04-11 20:13:10] Error in run 67: Run already exists in server. Run id(s): {9014102}
[2018-04-11 20:13:10] Started run 74 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:10] Started run 75 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:10] Error in run 66: Run already exists in server. Run id(s): {9012444}
[2018-04-11 20:13:10] Started run 76 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:11] Error in run 69: Run already exists in server. Run id(s): {9014136}
[2018-04-11 20:13:11] Error in run 70: Run already exists in server. Run id(s): {9014094}
[2018-04-11 20:13:11] Started run 77 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:11] Started run 78 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:11] Error in run 71: Run already exists in server. Run id(s): {9012565}
[2018-04-11 20:13:11] Started run 79 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:11] Error in run 72: Run already exists in server. Run id(s): {9012802}
[2018-04-11 20:13:11] Started run 80 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 73: Run already exists in server. Run id(s): {9014138}
[2018-04-11 20:13:15] Started run 81 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 74: Run already exists in server. Run id(s): {9013230}
[2018-04-11 20:13:15] Started run 82 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 76: Run already exists in server. Run id(s): {9014170}
[2018-04-11 20:13:15] Started run 83 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 75: Run already exists in server. Run id(s): {9012804}
[2018-04-11 20:13:15] Started run 84 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 78: Run already exists in server. Run id(s): {8970012}
[2018-04-11 20:13:15] Started run 85 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 77: Run already exists in server. Run id(s): {8970009}
[2018-04-11 20:13:15] Started run 86 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 79: Run already exists in server. Run id(s): {8970020}
[2018-04-11 20:13:15] Started run 87 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:15] Error in run 80: Run already exists in server. Run id(s): {8970080}
[2018-04-11 20:13:15] Started run 88 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:19] Error in run 81: Run already exists in server. Run id(s): {8970134}
[2018-04-11 20:13:19] Started run 89 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:19] Error in run 82: Run already exists in server. Run id(s): {8970150}
[2018-04-11 20:13:19] Started run 90 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:19] Error in run 83: Run already exists in server. Run id(s): {8970172}
[2018-04-11 20:13:19] Started run 91 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:20] Error in run 84: Run already exists in server. Run id(s): {8970231}
[2018-04-11 20:13:20] Error in run 86: Run already exists in server. Run id(s): {8970311}
[2018-04-11 20:13:20] Error in run 85: Run already exists in server. Run id(s): {8970305}
[2018-04-11 20:13:20] Started run 92 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:20] Started run 94 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:20] Started run 93 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:20] Error in run 87: Run already exists in server. Run id(s): {8970359}
[2018-04-11 20:13:20] Started run 95 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:20] Error in run 88: Run already exists in server. Run id(s): {8970430}
[2018-04-11 20:13:20] Started run 96 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Error in run 89: Run already exists in server. Run id(s): {8970496}
[2018-04-11 20:13:24] Started run 97 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Error in run 90: Run already exists in server. Run id(s): {8970454}
[2018-04-11 20:13:24] Started run 98 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Error in run 91: Run already exists in server. Run id(s): {8970485}
[2018-04-11 20:13:24] Started run 99 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Error in run 92: Run already exists in server. Run id(s): {9014294}
[2018-04-11 20:13:24] Started run 100 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Error in run 93: Run already exists in server. Run id(s): {9013266}
[2018-04-11 20:13:24] Error in run 94: Run already exists in server. Run id(s): {9013324}
[2018-04-11 20:13:24] Error in run 96: Run already exists in server. Run id(s): {8970602}
[2018-04-11 20:13:24] Error in run 95: Run already exists in server. Run id(s): {8970651}
[2018-04-11 20:13:24] Started run 101 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Started run 103 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Started run 102 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:24] Started run 104 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:28] Error in run 97: Run already exists in server. Run id(s): {8970661}
[2018-04-11 20:13:28] Started run 105 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:28] Error in run 98: Run already exists in server. Run id(s): {8970678}
[2018-04-11 20:13:28] Started run 106 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:28] Error in run 99: Run already exists in server. Run id(s): {8970740}
[2018-04-11 20:13:28] Started run 107 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:29] Error in run 100: Run already exists in server. Run id(s): {8970780}
[2018-04-11 20:13:29] Started run 108 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:29] Error in run 103: Run already exists in server. Run id(s): {9014285}
[2018-04-11 20:13:29] Error in run 102: Run already exists in server. Run id(s): {8970789}
[2018-04-11 20:13:29] Error in run 101: Run already exists in server. Run id(s): {8970786}
[2018-04-11 20:13:29] Started run 109 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:29] Error in run 104: Run already exists in server. Run id(s): {8970912}
[2018-04-11 20:13:29] Started run 111 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:29] Started run 112 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:29] Started run 110 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:33] Error in run 106: Run already exists in server. Run id(s): {8970905}
[2018-04-11 20:13:33] Started run 113 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:33] Error in run 105: Run already exists in server. Run id(s): {8970913}
[2018-04-11 20:13:33] Started run 114 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:33] Error in run 107: Run already exists in server. Run id(s): {9014301}
[2018-04-11 20:13:33] Started run 115 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:33] Error in run 108: Run already exists in server. Run id(s): {9014340}
[2018-04-11 20:13:33] Started run 116 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:33] Error in run 109: Run already exists in server. Run id(s): {8970927}
[2018-04-11 20:13:33] Started run 117 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:34] Error in run 111: Run already exists in server. Run id(s): {8971052}
[2018-04-11 20:13:34] Started run 118 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:34] Error in run 110: Run already exists in server. Run id(s): {8971040}
[2018-04-11 20:13:34] Error in run 112: Run already exists in server. Run id(s): {9014314}
[2018-04-11 20:13:34] Started run 119 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:34] Started run 120 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:37] Error in run 114: Run already exists in server. Run id(s): {9014331}
[2018-04-11 20:13:37] Started run 121 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:38] Error in run 116: Run already exists in server. Run id(s): {9014347}
[2018-04-11 20:13:38] Error in run 113: Run already exists in server. Run id(s): {8971069}
[2018-04-11 20:13:38] Started run 122 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:38] Started run 123 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:38] Error in run 115: Run already exists in server. Run id(s): {9014352}
[2018-04-11 20:13:38] Started run 124 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:38] Error in run 117: Run already exists in server. Run id(s): {9013684}
[2018-04-11 20:13:38] Started run 125 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:38] Error in run 118: Run already exists in server. Run id(s): {9014430}
[2018-04-11 20:13:38] Started run 126 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:38] Error in run 120: Run already exists in server. Run id(s): {8971102}
[2018-04-11 20:13:38] Error in run 119: Run already exists in server. Run id(s): {9014414}
[2018-04-11 20:13:38] Started run 127 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:38] Started run 128 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:42] Error in run 121: Run already exists in server. Run id(s): {8971109}
[2018-04-11 20:13:42] Started run 129 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:42] Error in run 123: Run already exists in server. Run id(s): {8971124}
[2018-04-11 20:13:42] Error in run 124: Run already exists in server. Run id(s): {8971137}
[2018-04-11 20:13:42] Started run 130 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:42] Started run 131 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:42] Error in run 122: Run already exists in server. Run id(s): {8971111}
[2018-04-11 20:13:42] Started run 132 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:42] Error in run 125: Run already exists in server. Run id(s): {8971143}
[2018-04-11 20:13:42] Started run 133 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:43] Error in run 126: Run already exists in server. Run id(s): {8971142}
[2018-04-11 20:13:43] Started run 134 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:43] Error in run 127: Run already exists in server. Run id(s): {8971152}
[2018-04-11 20:13:43] Error in run 128: Run already exists in server. Run id(s): {8971165}
[2018-04-11 20:13:43] Started run 135 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:43] Started run 136 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:46] Error in run 129: Run already exists in server. Run id(s): {8971186}
[2018-04-11 20:13:46] Started run 137 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:47] Error in run 130: Run already exists in server. Run id(s): {8971189}
[2018-04-11 20:13:47] Started run 138 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:47] Error in run 131: Run already exists in server. Run id(s): {8971185}
[2018-04-11 20:13:47] Error in run 132: Run already exists in server. Run id(s): {8971216}
[2018-04-11 20:13:47] Started run 139 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:47] Started run 140 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:47] Error in run 133: Run already exists in server. Run id(s): {8971223}
[2018-04-11 20:13:47] Started run 141 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:47] Error in run 134: Run already exists in server. Run id(s): {8971233}
[2018-04-11 20:13:47] Started run 142 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:48] Error in run 135: Run already exists in server. Run id(s): {8971224}
[2018-04-11 20:13:48] Started run 143 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:48] Error in run 136: Run already exists in server. Run id(s): {8971248}
[2018-04-11 20:13:48] Started run 144 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:51] Error in run 137: Run already exists in server. Run id(s): {8971253}
[2018-04-11 20:13:51] Started run 145 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:51] Error in run 138: Run already exists in server. Run id(s): {8971258}
[2018-04-11 20:13:51] Started run 146 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:51] Error in run 139: Run already exists in server. Run id(s): {8971268}
[2018-04-11 20:13:51] Started run 147 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:51] Error in run 140: Run already exists in server. Run id(s): {8971285}
[2018-04-11 20:13:51] Started run 148 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:52] Error in run 141: Run already exists in server. Run id(s): {8971292}
[2018-04-11 20:13:52] Started run 149 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:52] Error in run 142: Run already exists in server. Run id(s): {8971303}
[2018-04-11 20:13:52] Started run 150 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:52] Error in run 143: Run already exists in server. Run id(s): {8971305}
[2018-04-11 20:13:52] Started run 151 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:52] Error in run 144: Run already exists in server. Run id(s): {8971322}
[2018-04-11 20:13:52] Started run 152 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:56] Error in run 145: Run already exists in server. Run id(s): {8971350}
[2018-04-11 20:13:56] Started run 153 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:56] Error in run 146: Run already exists in server. Run id(s): {8971348}
[2018-04-11 20:13:56] Started run 154 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:56] Error in run 147: Run already exists in server. Run id(s): {8971363}
[2018-04-11 20:13:56] Started run 155 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:56] Error in run 148: Run already exists in server. Run id(s): {8971389}
[2018-04-11 20:13:56] Started run 156 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:56] Error in run 149: Run already exists in server. Run id(s): {8971395}
[2018-04-11 20:13:56] Started run 157 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:56] Error in run 150: Run already exists in server. Run id(s): {8971406}
[2018-04-11 20:13:56] Started run 158 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:57] Error in run 151: Run already exists in server. Run id(s): {8971411}
[2018-04-11 20:13:57] Started run 159 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:13:57] Error in run 152: Run already exists in server. Run id(s): {8971434}
[2018-04-11 20:13:57] Started run 160 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:00] Error in run 153: Run already exists in server. Run id(s): {8971445}
[2018-04-11 20:14:00] Started run 161 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:00] Error in run 154: Run already exists in server. Run id(s): {8971454}
[2018-04-11 20:14:00] Error in run 155: Run already exists in server. Run id(s): {8971461}
[2018-04-11 20:14:00] Started run 162 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:00] Started run 163 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:01] Error in run 156: Run already exists in server. Run id(s): {8971484}
[2018-04-11 20:14:01] Started run 164 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:01] Error in run 157: Run already exists in server. Run id(s): {8971505}
[2018-04-11 20:14:01] Started run 165 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:01] Error in run 158: Run already exists in server. Run id(s): {8971504}
[2018-04-11 20:14:01] Started run 166 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:01] Error in run 159: Run already exists in server. Run id(s): {8971522}
[2018-04-11 20:14:01] Started run 167 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:01] Error in run 160: Run already exists in server. Run id(s): {8971527}
[2018-04-11 20:14:01] Started run 168 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:05] Error in run 161: Run already exists in server. Run id(s): {8971550}
[2018-04-11 20:14:05] Started run 169 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:05] Error in run 163: Run already exists in server. Run id(s): {8971574}
[2018-04-11 20:14:05] Error in run 162: Run already exists in server. Run id(s): {8971543}
[2018-04-11 20:14:05] Started run 170 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:05] Started run 171 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:05] Error in run 164: Run already exists in server. Run id(s): {8971563}
[2018-04-11 20:14:05] Started run 172 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:05] Error in run 165: Run already exists in server. Run id(s): {8971579}
[2018-04-11 20:14:05] Started run 173 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:05] Error in run 166: Run already exists in server. Run id(s): {8971585}
[2018-04-11 20:14:05] Started run 174 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:06] Error in run 167: Run already exists in server. Run id(s): {8971605}
[2018-04-11 20:14:06] Started run 175 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:06] Error in run 168: Run already exists in server. Run id(s): {8971606}
[2018-04-11 20:14:06] Started run 176 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:09] Error in run 169: Run already exists in server. Run id(s): {8971609}
[2018-04-11 20:14:09] Started run 177 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:09] Error in run 170: Run already exists in server. Run id(s): {8971612}
[2018-04-11 20:14:09] Started run 178 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:10] Error in run 171: Run already exists in server. Run id(s): {8971614}
[2018-04-11 20:14:10] Error in run 172: Run already exists in server. Run id(s): {8971616}
[2018-04-11 20:14:10] Started run 179 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:10] Started run 180 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:10] Error in run 173: Run already exists in server. Run id(s): {8971619}
[2018-04-11 20:14:10] Started run 181 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:10] Error in run 174: Run already exists in server. Run id(s): {8971640}
[2018-04-11 20:14:10] Started run 182 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:10] Error in run 176: Run already exists in server. Run id(s): {8971637}
[2018-04-11 20:14:10] Started run 183 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:10] Error in run 175: Run already exists in server. Run id(s): {8971634}
[2018-04-11 20:14:10] Started run 184 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:14] Error in run 177: Run already exists in server. Run id(s): {8971641}
[2018-04-11 20:14:14] Started run 185 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:14] Error in run 178: Run already exists in server. Run id(s): {8971654}
[2018-04-11 20:14:14] Started run 186 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:14] Error in run 180: Run already exists in server. Run id(s): {8971656}
[2018-04-11 20:14:14] Error in run 181: Run already exists in server. Run id(s): {8971658}
[2018-04-11 20:14:14] Error in run 179: Run already exists in server. Run id(s): {8971655}
[2018-04-11 20:14:14] Started run 188 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:14] Started run 189 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:14] Started run 187 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:14] Error in run 182: Run already exists in server. Run id(s): {8971667}
[2018-04-11 20:14:14] Started run 190 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:15] Error in run 184: Run already exists in server. Run id(s): {8971666}
[2018-04-11 20:14:15] Error in run 183: Run already exists in server. Run id(s): {8971664}
[2018-04-11 20:14:15] Started run 191 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:15] Started run 192 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:18] Error in run 185: Run already exists in server. Run id(s): {8971669}
[2018-04-11 20:14:18] Started run 193 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:19] Error in run 186: Run already exists in server. Run id(s): {8971681}
[2018-04-11 20:14:19] Started run 194 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:19] Error in run 187: Run already exists in server. Run id(s): {8971677}
[2018-04-11 20:14:19] Error in run 188: Run already exists in server. Run id(s): {8971680}
[2018-04-11 20:14:19] Started run 195 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:19] Error in run 189: Run already exists in server. Run id(s): {8971682}
[2018-04-11 20:14:19] Started run 196 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:19] Error in run 190: Run already exists in server. Run id(s): {8971688}
[2018-04-11 20:14:19] Started run 198 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:19] Started run 197 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:20] Error in run 191: Run already exists in server. Run id(s): {8971692}
[2018-04-11 20:14:20] Error in run 192: Run already exists in server. Run id(s): {8971689}
[2018-04-11 20:14:20] Started run 199 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:20] Started run 200 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:23] Error in run 193: Run already exists in server. Run id(s): {8971691}
[2018-04-11 20:14:23] Error in run 194: Run already exists in server. Run id(s): {8971707}
[2018-04-11 20:14:23] Started run 201 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:23] Started run 202 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:24] Error in run 197: Run already exists in server. Run id(s): {8971703}
[2018-04-11 20:14:24] Error in run 195: Run already exists in server. Run id(s): {8971702}
[2018-04-11 20:14:24] Error in run 196: Run already exists in server. Run id(s): {8971705}
[2018-04-11 20:14:24] Error in run 198: Run already exists in server. Run id(s): {8971719}
[2018-04-11 20:14:24] Started run 203 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:24] Started run 205 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:24] Started run 204 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:24] Started run 206 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:24] Error in run 199: Run already exists in server. Run id(s): {8971720}
[2018-04-11 20:14:24] Error in run 200: Run already exists in server. Run id(s): {8971724}
[2018-04-11 20:14:24] Started run 207 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:24] Started run 208 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:28] Error in run 201: Run already exists in server. Run id(s): {8971726}
[2018-04-11 20:14:28] Started run 209 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:28] Error in run 202: Run already exists in server. Run id(s): {8971729}
[2018-04-11 20:14:28] Started run 210 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:28] Error in run 205: Run already exists in server. Run id(s): {8971735}
[2018-04-11 20:14:28] Started run 211 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:28] Error in run 204: Run already exists in server. Run id(s): {8971732}
[2018-04-11 20:14:28] Started run 212 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:28] Error in run 206: Run already exists in server. Run id(s): {8971748}
[2018-04-11 20:14:28] Error in run 203: Run already exists in server. Run id(s): {8971728}
[2018-04-11 20:14:28] Started run 213 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:28] Started run 214 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:29] Error in run 207: Run already exists in server. Run id(s): {8971744}
[2018-04-11 20:14:29] Started run 215 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:29] Error in run 208: Run already exists in server. Run id(s): {8971745}
[2018-04-11 20:14:29] Started run 216 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:32] Error in run 209: Run already exists in server. Run id(s): {8971746}
[2018-04-11 20:14:32] Started run 217 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:32] Error in run 210: Run already exists in server. Run id(s): {8971779}
[2018-04-11 20:14:32] Started run 218 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:33] Error in run 211: Run already exists in server. Run id(s): {8971778}
[2018-04-11 20:14:33] Started run 219 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:33] Error in run 214: Run already exists in server. Run id(s): {8971795}
[2018-04-11 20:14:33] Error in run 212: Run already exists in server. Run id(s): {8971773}
[2018-04-11 20:14:33] Error in run 213: Run already exists in server. Run id(s): {8971783}
[2018-04-11 20:14:33] Started run 220 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:33] Started run 222 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:33] Started run 221 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:33] Error in run 215: Run already exists in server. Run id(s): {8971801}
[2018-04-11 20:14:33] Started run 223 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:34] Error in run 216: Run already exists in server. Run id(s): {8971802}
[2018-04-11 20:14:34] Started run 224 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:37] Error in run 217: Run already exists in server. Run id(s): {8971807}
[2018-04-11 20:14:37] Started run 225 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:37] Error in run 218: Run already exists in server. Run id(s): {8971829}
[2018-04-11 20:14:37] Started run 226 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:37] Error in run 219: Run already exists in server. Run id(s): {8971850}
[2018-04-11 20:14:37] Started run 227 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:38] Error in run 221: Run already exists in server. Run id(s): {8971854}
[2018-04-11 20:14:38] Error in run 220: Run already exists in server. Run id(s): {8971843}
[2018-04-11 20:14:38] Error in run 222: Run already exists in server. Run id(s): {8971857}
[2018-04-11 20:14:38] Started run 228 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:38] Started run 229 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:38] Started run 230 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:38] Error in run 223: Run already exists in server. Run id(s): {8971868}
[2018-04-11 20:14:38] Started run 231 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:38] Error in run 224: Run already exists in server. Run id(s): {8971876}
[2018-04-11 20:14:38] Started run 232 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:41] Error in run 225: Run already exists in server. Run id(s): {8971879}
[2018-04-11 20:14:41] Started run 233 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:41] Error in run 226: Run already exists in server. Run id(s): {8971885}
[2018-04-11 20:14:41] Started run 234 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:42] Error in run 227: Run already exists in server. Run id(s): {8971894}
[2018-04-11 20:14:42] Started run 235 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:42] Error in run 230: Run already exists in server. Run id(s): {8971913}
[2018-04-11 20:14:42] Error in run 231: Run already exists in server. Run id(s): {8971923}
[2018-04-11 20:14:42] Error in run 229: Run already exists in server. Run id(s): {8971903}
[2018-04-11 20:14:42] Started run 236 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:42] Error in run 228: Run already exists in server. Run id(s): {8971911}
[2018-04-11 20:14:42] Started run 237 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:42] Started run 239 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:42] Started run 238 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:43] Error in run 232: Run already exists in server. Run id(s): {8971932}
[2018-04-11 20:14:43] Started run 240 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:46] Error in run 233: Run already exists in server. Run id(s): {8971941}
[2018-04-11 20:14:46] Started run 241 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:46] Error in run 234: Run already exists in server. Run id(s): {8971946}
[2018-04-11 20:14:46] Started run 242 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:46] Error in run 235: Run already exists in server. Run id(s): {8971970}
[2018-04-11 20:14:46] Started run 243 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:47] Error in run 237: Run already exists in server. Run id(s): {8971976}
[2018-04-11 20:14:47] Started run 244 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:47] Error in run 238: Run already exists in server. Run id(s): {8971979}
[2018-04-11 20:14:47] Started run 245 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:47] Error in run 239: Run already exists in server. Run id(s): {8972004}
[2018-04-11 20:14:47] Started run 246 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:47] Error in run 236: Run already exists in server. Run id(s): {8971985}
[2018-04-11 20:14:47] Started run 247 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:48] Error in run 240: Run already exists in server. Run id(s): {8972005}
[2018-04-11 20:14:48] Started run 248 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:50] Error in run 241: Run already exists in server. Run id(s): {8972010}
[2018-04-11 20:14:50] Started run 249 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:50] Error in run 242: Run already exists in server. Run id(s): {8972026}
[2018-04-11 20:14:50] Started run 250 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:51] Error in run 243: Run already exists in server. Run id(s): {8972041}
[2018-04-11 20:14:51] Started run 251 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:52] Error in run 245: Run already exists in server. Run id(s): {8972040}
[2018-04-11 20:14:52] Started run 252 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:52] Error in run 246: Run already exists in server. Run id(s): {8972060}
[2018-04-11 20:14:52] Error in run 247: Run already exists in server. Run id(s): {8972064}
[2018-04-11 20:14:52] Error in run 244: Run already exists in server. Run id(s): {8972037}
[2018-04-11 20:14:52] Started run 253 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:52] Started run 254 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:52] Started run 255 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:52] Error in run 248: Run already exists in server. Run id(s): {8972068}
[2018-04-11 20:14:52] Started run 256 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:55] Error in run 249: Run already exists in server. Run id(s): {8972067}
[2018-04-11 20:14:55] Started run 257 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:55] Error in run 250: Run already exists in server. Run id(s): {8972089}
[2018-04-11 20:14:55] Started run 258 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:55] Error in run 251: Run already exists in server. Run id(s): {8972110}
[2018-04-11 20:14:55] Started run 259 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:56] Error in run 252: Run already exists in server. Run id(s): {8972093}
[2018-04-11 20:14:56] Started run 260 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:56] Error in run 254: Run already exists in server. Run id(s): {8972117}
[2018-04-11 20:14:56] Error in run 255: Run already exists in server. Run id(s): {8972120}
[2018-04-11 20:14:56] Error in run 253: Run already exists in server. Run id(s): {8972096}
[2018-04-11 20:14:56] Started run 261 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:56] Started run 263 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:56] Started run 262 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:57] Error in run 256: Run already exists in server. Run id(s): {8972127}
[2018-04-11 20:14:57] Started run 264 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:59] Error in run 257: Run already exists in server. Run id(s): {8972138}
[2018-04-11 20:14:59] Started run 265 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:14:59] Error in run 258: Run already exists in server. Run id(s): {8972145}
[2018-04-11 20:14:59] Started run 266 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:00] Error in run 259: Run already exists in server. Run id(s): {8972149}
[2018-04-11 20:15:00] Started run 267 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:01] Error in run 260: Run already exists in server. Run id(s): {8972157}
[2018-04-11 20:15:01] Started run 268 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:01] Error in run 261: Run already exists in server. Run id(s): {8972178}
[2018-04-11 20:15:01] Started run 269 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:01] Error in run 263: Run already exists in server. Run id(s): {8972182}
[2018-04-11 20:15:01] Started run 270 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:01] Error in run 262: Run already exists in server. Run id(s): {8972184}
[2018-04-11 20:15:01] Started run 271 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:01] Error in run 264: Run already exists in server. Run id(s): {9014806, 8972191}
[2018-04-11 20:15:01] Started run 272 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:04] Error in run 265: Run already exists in server. Run id(s): {8972215}
[2018-04-11 20:15:04] Started run 273 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:04] Error in run 266: Run already exists in server. Run id(s): {8972217}
[2018-04-11 20:15:04] Started run 274 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:04] Error in run 267: Run already exists in server. Run id(s): {8972218}
[2018-04-11 20:15:04] Started run 275 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:05] Error in run 268: Run already exists in server. Run id(s): {8972227}
[2018-04-11 20:15:05] Started run 276 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:05] Error in run 269: Run already exists in server. Run id(s): {8972245}
[2018-04-11 20:15:05] Error in run 270: Run already exists in server. Run id(s): {8972248}
[2018-04-11 20:15:05] Started run 277 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:05] Started run 278 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:05] Error in run 271: Run already exists in server. Run id(s): {8972247}
[2018-04-11 20:15:05] Started run 279 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:06] Error in run 272: Run already exists in server. Run id(s): {8972256}
[2018-04-11 20:15:06] Started run 280 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:08] Error in run 273: Run already exists in server. Run id(s): {8972279}
[2018-04-11 20:15:08] Started run 281 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:08] Error in run 274: Run already exists in server. Run id(s): {8972271}
[2018-04-11 20:15:08] Started run 282 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:09] Error in run 275: Run already exists in server. Run id(s): {8972288}
[2018-04-11 20:15:09] Started run 283 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:10] Error in run 276: Run already exists in server. Run id(s): {8972285}
[2018-04-11 20:15:10] Started run 284 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:10] Error in run 277: Run already exists in server. Run id(s): {8972303}
[2018-04-11 20:15:10] Error in run 278: Run already exists in server. Run id(s): {8972306}
[2018-04-11 20:15:10] Started run 285 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:10] Started run 286 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:10] Error in run 279: Run already exists in server. Run id(s): {8972315}
[2018-04-11 20:15:10] Started run 287 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:10] Error in run 280: Run already exists in server. Run id(s): {8972317}
[2018-04-11 20:15:10] Started run 288 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:13] Error in run 281: Run already exists in server. Run id(s): {8972328}
[2018-04-11 20:15:13] Started run 289 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:13] Error in run 282: Run already exists in server. Run id(s): {8972334}
[2018-04-11 20:15:13] Started run 290 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:13] Error in run 283: Run already exists in server. Run id(s): {8972341}
[2018-04-11 20:15:13] Started run 291 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:14] Error in run 284: Run already exists in server. Run id(s): {8972343}
[2018-04-11 20:15:14] Started run 292 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:14] Error in run 285: Run already exists in server. Run id(s): {8972362}
[2018-04-11 20:15:14] Started run 293 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:14] Error in run 286: Run already exists in server. Run id(s): {8972377}
[2018-04-11 20:15:14] Started run 294 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:14] Error in run 287: Run already exists in server. Run id(s): {8972365}
[2018-04-11 20:15:14] Started run 295 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:15] Error in run 288: Run already exists in server. Run id(s): {8972376}
[2018-04-11 20:15:15] Started run 296 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:17] Error in run 290: Run already exists in server. Run id(s): {8972415}
[2018-04-11 20:15:17] Started run 297 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:17] Error in run 289: Run already exists in server. Run id(s): {8972398}
[2018-04-11 20:15:17] Started run 298 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:18] Error in run 291: Run already exists in server. Run id(s): {8972410}
[2018-04-11 20:15:18] Started run 299 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:19] Error in run 292: Run already exists in server. Run id(s): {8972406}
[2018-04-11 20:15:19] Started run 300 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:19] Error in run 293: Run already exists in server. Run id(s): {8972421}
[2018-04-11 20:15:19] Started run 301 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:19] Error in run 295: Run already exists in server. Run id(s): {8972438}
[2018-04-11 20:15:19] Error in run 294: Run already exists in server. Run id(s): {8972434}
[2018-04-11 20:15:19] Started run 302 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:19] Started run 303 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:19] Error in run 296: Run already exists in server. Run id(s): {8972445}
[2018-04-11 20:15:19] Started run 304 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:22] Error in run 297: Run already exists in server. Run id(s): {8972455}
[2018-04-11 20:15:22] Started run 305 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:22] Error in run 298: Run already exists in server. Run id(s): {8972482}
[2018-04-11 20:15:22] Started run 306 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:22] Error in run 299: Run already exists in server. Run id(s): {8972465}
[2018-04-11 20:15:22] Started run 307 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:23] Error in run 300: Run already exists in server. Run id(s): {8972476}
[2018-04-11 20:15:23] Started run 308 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:23] Error in run 301: Run already exists in server. Run id(s): {8972491}
[2018-04-11 20:15:23] Started run 309 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:24] Error in run 302: Run already exists in server. Run id(s): {8972499}
[2018-04-11 20:15:24] Started run 310 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:24] Error in run 303: Run already exists in server. Run id(s): {8972511}
[2018-04-11 20:15:24] Started run 311 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:24] Error in run 304: Run already exists in server. Run id(s): {8972514}
[2018-04-11 20:15:24] Started run 312 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:26] Error in run 305: Run already exists in server. Run id(s): {8972529}
[2018-04-11 20:15:26] Started run 313 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:27] Error in run 306: Run already exists in server. Run id(s): {8972532}
[2018-04-11 20:15:27] Started run 314 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:27] Error in run 307: Run already exists in server. Run id(s): {8972545}
[2018-04-11 20:15:27] Started run 315 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:28] Error in run 308: Run already exists in server. Run id(s): {8972540}
[2018-04-11 20:15:28] Started run 316 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:28] Error in run 309: Run already exists in server. Run id(s): {8972557}
[2018-04-11 20:15:28] Started run 317 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:28] Error in run 310: Run already exists in server. Run id(s): {8972563}
[2018-04-11 20:15:28] Started run 318 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:28] Error in run 312: Run already exists in server. Run id(s): {8972575}
[2018-04-11 20:15:28] Started run 319 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:28] Error in run 311: Run already exists in server. Run id(s): {8972577}
[2018-04-11 20:15:28] Started run 320 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:31] Error in run 313: Run already exists in server. Run id(s): {8972585}
[2018-04-11 20:15:31] Started run 321 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:32] Error in run 315: Run already exists in server. Run id(s): {8972603}
[2018-04-11 20:15:32] Error in run 314: Run already exists in server. Run id(s): {8972594}
[2018-04-11 20:15:32] Started run 322 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:32] Started run 323 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:32] Error in run 316: Run already exists in server. Run id(s): {8972605}
[2018-04-11 20:15:32] Started run 324 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:32] Error in run 317: Run already exists in server. Run id(s): {8972613}
[2018-04-11 20:15:32] Started run 325 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:33] Error in run 318: Run already exists in server. Run id(s): {8972621}
[2018-04-11 20:15:33] Started run 326 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:33] Error in run 319: Run already exists in server. Run id(s): {8972633}
[2018-04-11 20:15:33] Started run 327 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:33] Error in run 320: Run already exists in server. Run id(s): {8972637}
[2018-04-11 20:15:33] Started run 328 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:36] Error in run 321: Run already exists in server. Run id(s): {8972640}
[2018-04-11 20:15:36] Started run 329 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:36] Error in run 323: Run already exists in server. Run id(s): {8972660}
[2018-04-11 20:15:36] Started run 330 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:36] Error in run 322: Run already exists in server. Run id(s): {8972649}
[2018-04-11 20:15:36] Started run 331 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:37] Error in run 325: Run already exists in server. Run id(s): {8972673}
[2018-04-11 20:15:37] Error in run 326: Run already exists in server. Run id(s): {8972678}
[2018-04-11 20:15:37] Started run 332 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:37] Error in run 324: Run already exists in server. Run id(s): {8972672}
[2018-04-11 20:15:37] Started run 334 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:37] Started run 333 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:37] Error in run 327: Run already exists in server. Run id(s): {8972688}
[2018-04-11 20:15:37] Started run 335 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:38] Error in run 328: Run already exists in server. Run id(s): {8972702}
[2018-04-11 20:15:38] Started run 336 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:40] Error in run 329: Run already exists in server. Run id(s): {8972703}
[2018-04-11 20:15:40] Started run 337 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:41] Error in run 330: Run already exists in server. Run id(s): {8972705}
[2018-04-11 20:15:41] Started run 338 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:41] Error in run 331: Run already exists in server. Run id(s): {8972722}
[2018-04-11 20:15:41] Started run 339 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:42] Error in run 333: Run already exists in server. Run id(s): {8972730}
[2018-04-11 20:15:42] Error in run 334: Run already exists in server. Run id(s): {8972735}
[2018-04-11 20:15:42] Error in run 332: Run already exists in server. Run id(s): {8972727}
[2018-04-11 20:15:42] Started run 340 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:42] Started run 342 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:42] Started run 341 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:42] Error in run 335: Run already exists in server. Run id(s): {8972752}
[2018-04-11 20:15:42] Started run 343 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:43] Error in run 336: Run already exists in server. Run id(s): {8972761}
[2018-04-11 20:15:43] Started run 344 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:45] Error in run 337: Run already exists in server. Run id(s): {8972757}
[2018-04-11 20:15:45] Started run 345 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:46] Error in run 339: Run already exists in server. Run id(s): {8972779}
[2018-04-11 20:15:46] Started run 346 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:46] Error in run 338: Run already exists in server. Run id(s): {8972762}
[2018-04-11 20:15:46] Started run 347 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:46] Error in run 342: Run already exists in server. Run id(s): {8972789}
[2018-04-11 20:15:46] Error in run 341: Run already exists in server. Run id(s): {8972787}
[2018-04-11 20:15:46] Started run 348 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:46] Error in run 340: Run already exists in server. Run id(s): {8972782}
[2018-04-11 20:15:46] Started run 350 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:46] Started run 349 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:46] Error in run 343: Run already exists in server. Run id(s): {8972806}
[2018-04-11 20:15:46] Started run 351 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:47] Error in run 344: Run already exists in server. Run id(s): {8972812}
[2018-04-11 20:15:47] Started run 352 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:49] Error in run 345: Run already exists in server. Run id(s): {8972817}
[2018-04-11 20:15:49] Started run 353 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:50] Error in run 347: Run already exists in server. Run id(s): {8972834}
[2018-04-11 20:15:50] Started run 354 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:50] Error in run 346: Run already exists in server. Run id(s): {8972819}
[2018-04-11 20:15:50] Started run 355 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:51] Error in run 348: Run already exists in server. Run id(s): {8972848}
[2018-04-11 20:15:51] Started run 356 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:51] Error in run 349: Run already exists in server. Run id(s): {8972843}
[2018-04-11 20:15:51] Error in run 351: Run already exists in server. Run id(s): {8972862}
[2018-04-11 20:15:51] Started run 357 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:51] Started run 358 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:51] Error in run 350: Run already exists in server. Run id(s): {8972855}
[2018-04-11 20:15:51] Started run 359 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:52] Error in run 352: Run already exists in server. Run id(s): {8972873}
[2018-04-11 20:15:52] Started run 360 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:54] Error in run 353: Run already exists in server. Run id(s): {8972891}
[2018-04-11 20:15:54] Started run 361 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:55] Error in run 355: Run already exists in server. Run id(s): {8972892}
[2018-04-11 20:15:55] Error in run 354: Run already exists in server. Run id(s): {8972883}
[2018-04-11 20:15:55] Started run 362 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:55] Started run 363 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:55] Error in run 356: Run already exists in server. Run id(s): {8972907}
[2018-04-11 20:15:55] Started run 364 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:56] Error in run 358: Run already exists in server. Run id(s): {8972922}
[2018-04-11 20:15:56] Started run 365 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:56] Error in run 357: Run already exists in server. Run id(s): {8972911}
[2018-04-11 20:15:56] Error in run 359: Run already exists in server. Run id(s): {8972921}
[2018-04-11 20:15:56] Started run 366 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:56] Started run 367 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:56] Error in run 360: Run already exists in server. Run id(s): {8972946}
[2018-04-11 20:15:56] Started run 368 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:15:58] Error in run 361: Run already exists in server. Run id(s): {8972941}
[2018-04-11 20:15:58] Started run 369 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:00] Error in run 363: Run already exists in server. Run id(s): {8972960}
[2018-04-11 20:16:00] Started run 370 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:00] Error in run 362: Run already exists in server. Run id(s): {8972950}
[2018-04-11 20:16:00] Started run 371 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:00] Error in run 364: Run already exists in server. Run id(s): {8972965}
[2018-04-11 20:16:00] Started run 372 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:00] Error in run 365: Run already exists in server. Run id(s): {8972984}
[2018-04-11 20:16:00] Started run 373 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:01] Error in run 366: Run already exists in server. Run id(s): {8972976}
[2018-04-11 20:16:01] Error in run 367: Run already exists in server. Run id(s): {8972988}
[2018-04-11 20:16:01] Started run 374 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:01] Started run 375 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:01] Error in run 368: Run already exists in server. Run id(s): {8973000}
[2018-04-11 20:16:01] Started run 376 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:03] Error in run 369: Run already exists in server. Run id(s): {8973011}
[2018-04-11 20:16:03] Started run 377 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:04] Error in run 370: Run already exists in server. Run id(s): {8973013}
[2018-04-11 20:16:04] Started run 378 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:04] Error in run 371: Run already exists in server. Run id(s): {8973020}
[2018-04-11 20:16:04] Started run 379 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:04] Error in run 372: Run already exists in server. Run id(s): {8973030}
[2018-04-11 20:16:04] Started run 380 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:05] Error in run 373: Run already exists in server. Run id(s): {8973049}
[2018-04-11 20:16:05] Started run 381 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:05] Error in run 375: Run already exists in server. Run id(s): {8973052}
[2018-04-11 20:16:05] Started run 382 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:05] Error in run 374: Run already exists in server. Run id(s): {8973059}
[2018-04-11 20:16:05] Started run 383 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:05] Error in run 376: Run already exists in server. Run id(s): {8973061}
[2018-04-11 20:16:05] Started run 384 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:07] Error in run 377: Run already exists in server. Run id(s): {8973071}
[2018-04-11 20:16:07] Started run 385 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:09] Error in run 378: Run already exists in server. Run id(s): {8973073}
[2018-04-11 20:16:09] Started run 386 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:09] Error in run 379: Run already exists in server. Run id(s): {8973080}
[2018-04-11 20:16:09] Started run 387 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:09] Error in run 380: Run already exists in server. Run id(s): {8973092}
[2018-04-11 20:16:09] Started run 388 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:09] Error in run 381: Run already exists in server. Run id(s): {8973101}
[2018-04-11 20:16:09] Started run 389 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:10] Error in run 383: Run already exists in server. Run id(s): {8973114}
[2018-04-11 20:16:10] Error in run 382: Run already exists in server. Run id(s): {8973107}
[2018-04-11 20:16:10] Started run 390 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:10] Started run 391 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:10] Error in run 384: Run already exists in server. Run id(s): {8973126}
[2018-04-11 20:16:10] Started run 392 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:12] Error in run 385: Run already exists in server. Run id(s): {8973129}
[2018-04-11 20:16:12] Started run 393 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:13] Error in run 386: Run already exists in server. Run id(s): {8973148}
[2018-04-11 20:16:13] Started run 394 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:13] Error in run 387: Run already exists in server. Run id(s): {8973155}
[2018-04-11 20:16:13] Started run 395 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:14] Error in run 388: Run already exists in server. Run id(s): {8973167}
[2018-04-11 20:16:14] Started run 396 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:14] Error in run 389: Run already exists in server. Run id(s): {8973161}
[2018-04-11 20:16:14] Started run 397 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:14] Error in run 390: Run already exists in server. Run id(s): {8973177}
[2018-04-11 20:16:14] Started run 398 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:15] Error in run 391: Run already exists in server. Run id(s): {8973197}
[2018-04-11 20:16:15] Started run 399 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:15] Error in run 392: Run already exists in server. Run id(s): {8973190}
[2018-04-11 20:16:15] Started run 400 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:16] Error in run 393: Run already exists in server. Run id(s): {8973196}
[2018-04-11 20:16:16] Started run 401 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:18] Error in run 394: Run already exists in server. Run id(s): {8973209}
[2018-04-11 20:16:18] Started run 402 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:18] Error in run 395: Run already exists in server. Run id(s): {8973219}
[2018-04-11 20:16:18] Started run 403 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:18] Error in run 396: Run already exists in server. Run id(s): {8973236}
[2018-04-11 20:16:18] Started run 404 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:18] Error in run 397: Run already exists in server. Run id(s): {8973229}
[2018-04-11 20:16:18] Started run 405 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:19] Error in run 398: Run already exists in server. Run id(s): {8973240}
[2018-04-11 20:16:19] Started run 406 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:19] Error in run 399: Run already exists in server. Run id(s): {8973248}
[2018-04-11 20:16:19] Started run 407 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:19] Error in run 400: Run already exists in server. Run id(s): {8973254}
[2018-04-11 20:16:19] Started run 408 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:21] Error in run 401: Run already exists in server. Run id(s): {8973279}
[2018-04-11 20:16:21] Started run 409 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:22] Error in run 403: Run already exists in server. Run id(s): {8973281}
[2018-04-11 20:16:22] Error in run 402: Run already exists in server. Run id(s): {8973268}
[2018-04-11 20:16:22] Started run 410 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:22] Started run 411 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:23] Error in run 404: Run already exists in server. Run id(s): {8973292}
[2018-04-11 20:16:23] Started run 412 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:23] Error in run 405: Run already exists in server. Run id(s): {8973306}
[2018-04-11 20:16:23] Started run 413 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:23] Error in run 406: Run already exists in server. Run id(s): {8973314}
[2018-04-11 20:16:23] Started run 414 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:24] Error in run 407: Run already exists in server. Run id(s): {8973332}
[2018-04-11 20:16:24] Started run 415 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:24] Error in run 408: Run already exists in server. Run id(s): {8973324}
[2018-04-11 20:16:24] Started run 416 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:26] Error in run 409: Run already exists in server. Run id(s): {8973355}
[2018-04-11 20:16:26] Started run 417 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:27] Error in run 410: Run already exists in server. Run id(s): {8973349}
[2018-04-11 20:16:27] Started run 418 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:27] Error in run 411: Run already exists in server. Run id(s): {8973359}
[2018-04-11 20:16:27] Started run 419 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:27] Error in run 412: Run already exists in server. Run id(s): {8973364}
[2018-04-11 20:16:27] Started run 420 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:28] Error in run 413: Run already exists in server. Run id(s): {8973380}
[2018-04-11 20:16:28] Started run 421 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:28] Error in run 414: Run already exists in server. Run id(s): {8973394}
[2018-04-11 20:16:28] Started run 422 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:28] Error in run 415: Run already exists in server. Run id(s): {9015386, 8973388}
[2018-04-11 20:16:28] Started run 423 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:29] Error in run 416: Run already exists in server. Run id(s): {8973418}
[2018-04-11 20:16:29] Started run 424 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:30] Error in run 417: Run already exists in server. Run id(s): {8973417}
[2018-04-11 20:16:30] Started run 425 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:32] Error in run 418: Run already exists in server. Run id(s): {8973422}
[2018-04-11 20:16:32] Started run 426 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:32] Error in run 419: Run already exists in server. Run id(s): {8973434}
[2018-04-11 20:16:32] Error in run 420: Run already exists in server. Run id(s): {8973457}
[2018-04-11 20:16:32] Started run 427 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:32] Started run 428 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:32] Error in run 421: Run already exists in server. Run id(s): {8973450}
[2018-04-11 20:16:32] Started run 429 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:33] Error in run 422: Run already exists in server. Run id(s): {8973451}
[2018-04-11 20:16:33] Started run 430 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:33] Error in run 423: Run already exists in server. Run id(s): {8973459}
[2018-04-11 20:16:33] Started run 431 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:33] Error in run 424: Run already exists in server. Run id(s): {8973474}
[2018-04-11 20:16:33] Started run 432 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:35] Error in run 425: Run already exists in server. Run id(s): {8973482}
[2018-04-11 20:16:35] Started run 433 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:36] Error in run 426: Run already exists in server. Run id(s): {8973483}
[2018-04-11 20:16:36] Started run 434 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:36] Error in run 428: Run already exists in server. Run id(s): {8973517}
[2018-04-11 20:16:36] Started run 435 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:36] Error in run 427: Run already exists in server. Run id(s): {8973493}
[2018-04-11 20:16:36] Started run 436 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:37] Error in run 429: Run already exists in server. Run id(s): {8973513}
[2018-04-11 20:16:37] Started run 437 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:37] Error in run 430: Run already exists in server. Run id(s): {8973516}
[2018-04-11 20:16:37] Error in run 431: Run already exists in server. Run id(s): {8973532}
[2018-04-11 20:16:37] Started run 438 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:37] Started run 439 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:38] Error in run 432: Run already exists in server. Run id(s): {8973541}
[2018-04-11 20:16:38] Started run 440 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:39] Error in run 433: Run already exists in server. Run id(s): {8973542}
[2018-04-11 20:16:39] Started run 441 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:41] Error in run 434: Run already exists in server. Run id(s): {8973543}
[2018-04-11 20:16:41] Started run 442 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:41] Error in run 435: Run already exists in server. Run id(s): {8973570}
[2018-04-11 20:16:41] Started run 443 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:41] Error in run 436: Run already exists in server. Run id(s): {8973563}
[2018-04-11 20:16:41] Started run 444 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:41] Error in run 437: Run already exists in server. Run id(s): {8973565}
[2018-04-11 20:16:41] Started run 445 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:42] Error in run 438: Run already exists in server. Run id(s): {8973571}
[2018-04-11 20:16:42] Error in run 439: Run already exists in server. Run id(s): {8973600}
[2018-04-11 20:16:42] Started run 446 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:42] Started run 447 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:43] Error in run 440: Run already exists in server. Run id(s): {8973603}
[2018-04-11 20:16:43] Started run 448 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:44] Error in run 441: Run already exists in server. Run id(s): {8973614}
[2018-04-11 20:16:44] Started run 449 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:45] Error in run 442: Run already exists in server. Run id(s): {8973606}
[2018-04-11 20:16:45] Started run 450 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:45] Error in run 443: Run already exists in server. Run id(s): {8973630}
[2018-04-11 20:16:45] Started run 451 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:46] Error in run 444: Run already exists in server. Run id(s): {8973629}
[2018-04-11 20:16:46] Started run 452 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:46] Error in run 445: Run already exists in server. Run id(s): {8973632}
[2018-04-11 20:16:46] Started run 453 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:46] Error in run 446: Run already exists in server. Run id(s): {8973644}
[2018-04-11 20:16:46] Started run 454 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:47] Error in run 447: Run already exists in server. Run id(s): {8973652}
[2018-04-11 20:16:47] Started run 455 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:47] Error in run 448: Run already exists in server. Run id(s): {8973653}
[2018-04-11 20:16:47] Started run 456 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:48] Error in run 449: Run already exists in server. Run id(s): {8973658}
[2018-04-11 20:16:48] Started run 457 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:50] Error in run 450: Run already exists in server. Run id(s): {8973661}
[2018-04-11 20:16:50] Started run 458 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:50] Error in run 451: Run already exists in server. Run id(s): {8973678}
[2018-04-11 20:16:50] Started run 459 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:50] Error in run 452: Run already exists in server. Run id(s): {8973679}
[2018-04-11 20:16:50] Started run 460 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:50] Error in run 453: Run already exists in server. Run id(s): {8973680}
[2018-04-11 20:16:50] Started run 461 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:51] Error in run 454: Run already exists in server. Run id(s): {8973698}
[2018-04-11 20:16:51] Started run 462 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:51] Error in run 455: Run already exists in server. Run id(s): {8973718}
[2018-04-11 20:16:51] Started run 463 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:52] Error in run 456: Run already exists in server. Run id(s): {8973706}
[2018-04-11 20:16:52] Started run 464 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:53] Error in run 457: Run already exists in server. Run id(s): {8973708}
[2018-04-11 20:16:53] Started run 465 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:54] Error in run 458: Run already exists in server. Run id(s): {8973724}
[2018-04-11 20:16:54] Started run 466 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:54] Error in run 459: Run already exists in server. Run id(s): {8973739}
[2018-04-11 20:16:54] Started run 467 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:55] Error in run 460: Run already exists in server. Run id(s): {8973731}
[2018-04-11 20:16:55] Started run 468 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:55] Error in run 461: Run already exists in server. Run id(s): {8973740}
[2018-04-11 20:16:55] Started run 469 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:55] Error in run 462: Run already exists in server. Run id(s): {8973748}
[2018-04-11 20:16:55] Started run 470 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:55] Error in run 463: Run already exists in server. Run id(s): {8973761}
[2018-04-11 20:16:55] Started run 471 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:56] Error in run 464: Run already exists in server. Run id(s): {8973769}
[2018-04-11 20:16:56] Started run 472 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:58] Error in run 465: Run already exists in server. Run id(s): {8973759}
[2018-04-11 20:16:58] Started run 473 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:59] Error in run 466: Run already exists in server. Run id(s): {8973766}
[2018-04-11 20:16:59] Started run 474 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:59] Error in run 467: Run already exists in server. Run id(s): {8973787}
[2018-04-11 20:16:59] Started run 475 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:16:59] Error in run 468: Run already exists in server. Run id(s): {8973785}
[2018-04-11 20:16:59] Started run 476 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:00] Error in run 469: Run already exists in server. Run id(s): {8973789}
[2018-04-11 20:17:00] Started run 477 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:00] Error in run 470: Run already exists in server. Run id(s): {8973793}
[2018-04-11 20:17:00] Started run 478 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:00] Error in run 471: Run already exists in server. Run id(s): {8973808}
[2018-04-11 20:17:00] Started run 479 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:01] Error in run 472: Run already exists in server. Run id(s): {8973810}
[2018-04-11 20:17:01] Started run 480 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:02] Error in run 473: Run already exists in server. Run id(s): {8973809}
[2018-04-11 20:17:02] Started run 481 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:04] Error in run 474: Run already exists in server. Run id(s): {8973812}
[2018-04-11 20:17:04] Started run 482 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:04] Error in run 475: Run already exists in server. Run id(s): {8973835}
[2018-04-11 20:17:04] Started run 483 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:04] Error in run 476: Run already exists in server. Run id(s): {8973841}
[2018-04-11 20:17:04] Started run 484 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:04] Error in run 477: Run already exists in server. Run id(s): {8973842}
[2018-04-11 20:17:04] Started run 485 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:05] Error in run 478: Run already exists in server. Run id(s): {8973845}
[2018-04-11 20:17:05] Started run 486 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:05] Error in run 479: Run already exists in server. Run id(s): {8973862}
[2018-04-11 20:17:05] Started run 487 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:05] Error in run 480: Run already exists in server. Run id(s): {8973870}
[2018-04-11 20:17:05] Started run 488 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:07] Error in run 481: Run already exists in server. Run id(s): {8973872}
[2018-04-11 20:17:07] Started run 489 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:08] Error in run 482: Run already exists in server. Run id(s): {8973875}
[2018-04-11 20:17:08] Started run 490 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:09] Error in run 483: Run already exists in server. Run id(s): {8973891}
[2018-04-11 20:17:09] Started run 491 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:09] Error in run 485: Run already exists in server. Run id(s): {8973896}
[2018-04-11 20:17:09] Started run 492 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:09] Error in run 484: Run already exists in server. Run id(s): {8973893}
[2018-04-11 20:17:09] Started run 493 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:09] Error in run 486: Run already exists in server. Run id(s): {8973908}
[2018-04-11 20:17:09] Started run 494 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:09] Error in run 487: Run already exists in server. Run id(s): {8973914}
[2018-04-11 20:17:09] Started run 495 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:10] Error in run 488: Run already exists in server. Run id(s): {8973917}
[2018-04-11 20:17:10] Started run 496 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:12] Error in run 489: Run already exists in server. Run id(s): {8973923}
[2018-04-11 20:17:12] Started run 497 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:13] Error in run 490: Run already exists in server. Run id(s): {8973927}
[2018-04-11 20:17:13] Started run 498 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:13] Error in run 491: Run already exists in server. Run id(s): {8973947}
[2018-04-11 20:17:13] Started run 499 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:13] Error in run 493: Run already exists in server. Run id(s): {8973951}
[2018-04-11 20:17:13] Error in run 492: Run already exists in server. Run id(s): {8973937}
[2018-04-11 20:17:13] Started run 500 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:13] Started run 501 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:14] Error in run 494: Run already exists in server. Run id(s): {8973948}
[2018-04-11 20:17:14] Started run 502 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:14] Error in run 495: Run already exists in server. Run id(s): {8973957}
[2018-04-11 20:17:14] Started run 503 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:15] Error in run 496: Run already exists in server. Run id(s): {8973965}
[2018-04-11 20:17:15] Started run 504 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:17] Error in run 497: Run already exists in server. Run id(s): {8973975}
[2018-04-11 20:17:17] Started run 505 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:17] Error in run 498: Run already exists in server. Run id(s): {8973974}
[2018-04-11 20:17:17] Started run 506 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:18] Error in run 501: Run already exists in server. Run id(s): {8974005}
[2018-04-11 20:17:18] Started run 507 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:18] Error in run 499: Run already exists in server. Run id(s): {8973978}
[2018-04-11 20:17:18] Error in run 502: Run already exists in server. Run id(s): {8974000}
[2018-04-11 20:17:18] Started run 508 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:18] Error in run 500: Run already exists in server. Run id(s): {8973995}
[2018-04-11 20:17:18] Started run 510 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:18] Started run 509 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:19] Error in run 503: Run already exists in server. Run id(s): {8974003}
[2018-04-11 20:17:19] Started run 511 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:20] Error in run 504: Run already exists in server. Run id(s): {8974014}
[2018-04-11 20:17:20] Started run 512 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:21] Error in run 505: Run already exists in server. Run id(s): {8974021}
[2018-04-11 20:17:21] Started run 513 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:22] Error in run 506: Run already exists in server. Run id(s): {8974025}
[2018-04-11 20:17:22] Started run 514 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:23] Error in run 508: Run already exists in server. Run id(s): {8974040}
[2018-04-11 20:17:23] Started run 515 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:23] Error in run 509: Run already exists in server. Run id(s): {8974047}
[2018-04-11 20:17:23] Started run 516 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:23] Error in run 510: Run already exists in server. Run id(s): {8974060}
[2018-04-11 20:17:23] Error in run 507: Run already exists in server. Run id(s): {8974024}
[2018-04-11 20:17:23] Started run 517 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:23] Started run 518 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:24] Error in run 511: Run already exists in server. Run id(s): {8974050}
[2018-04-11 20:17:24] Started run 519 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:24] Error in run 512: Run already exists in server. Run id(s): {8974067}
[2018-04-11 20:17:24] Started run 520 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:26] Error in run 513: Run already exists in server. Run id(s): {8974068}
[2018-04-11 20:17:26] Started run 521 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:27] Error in run 514: Run already exists in server. Run id(s): {8974071}
[2018-04-11 20:17:27] Started run 522 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:27] Error in run 515: Run already exists in server. Run id(s): {8974086}
[2018-04-11 20:17:27] Started run 523 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:27] Error in run 516: Run already exists in server. Run id(s): {8974108}
[2018-04-11 20:17:27] Started run 524 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:28] Error in run 517: Run already exists in server. Run id(s): {8974091}
[2018-04-11 20:17:28] Started run 525 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:28] Error in run 518: Run already exists in server. Run id(s): {8974098}
[2018-04-11 20:17:28] Started run 526 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:28] Error in run 519: Run already exists in server. Run id(s): {8974119}
[2018-04-11 20:17:28] Started run 527 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:29] Error in run 520: Run already exists in server. Run id(s): {8974120}
[2018-04-11 20:17:29] Started run 528 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:31] Error in run 521: Run already exists in server. Run id(s): {8974126}
[2018-04-11 20:17:31] Started run 529 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:31] Error in run 522: Run already exists in server. Run id(s): {8974132}
[2018-04-11 20:17:31] Started run 530 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:32] Error in run 524: Run already exists in server. Run id(s): {8974147}
[2018-04-11 20:17:32] Started run 531 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:32] Error in run 523: Run already exists in server. Run id(s): {8974145}
[2018-04-11 20:17:32] Started run 532 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:32] Error in run 526: Run already exists in server. Run id(s): {8974164}
[2018-04-11 20:17:32] Started run 533 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:32] Error in run 525: Run already exists in server. Run id(s): {8974156}
[2018-04-11 20:17:32] Started run 534 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:33] Error in run 527: Run already exists in server. Run id(s): {8974177}
[2018-04-11 20:17:33] Started run 535 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:34] Error in run 528: Run already exists in server. Run id(s): {8974178}
[2018-04-11 20:17:34] Started run 536 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:35] Error in run 529: Run already exists in server. Run id(s): {8974189}
[2018-04-11 20:17:35] Started run 537 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:36] Error in run 530: Run already exists in server. Run id(s): {8974197}
[2018-04-11 20:17:36] Started run 538 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:37] Error in run 531: Run already exists in server. Run id(s): {8974207}
[2018-04-11 20:17:37] Started run 539 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:37] Error in run 532: Run already exists in server. Run id(s): {8974204}
[2018-04-11 20:17:37] Started run 540 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:37] Error in run 533: Run already exists in server. Run id(s): {8974217}
[2018-04-11 20:17:37] Error in run 534: Run already exists in server. Run id(s): {8974223}
[2018-04-11 20:17:37] Started run 541 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:37] Started run 542 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:38] Error in run 535: Run already exists in server. Run id(s): {8974230}
[2018-04-11 20:17:38] Started run 543 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:38] Error in run 536: Run already exists in server. Run id(s): {8974231}
[2018-04-11 20:17:38] Started run 544 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:40] Error in run 537: Run already exists in server. Run id(s): {8974239}
[2018-04-11 20:17:40] Started run 545 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:41] Error in run 538: Run already exists in server. Run id(s): {8974243}
[2018-04-11 20:17:41] Started run 546 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:41] Error in run 539: Run already exists in server. Run id(s): {8974264}
[2018-04-11 20:17:41] Started run 547 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:42] Error in run 540: Run already exists in server. Run id(s): {8974253}
[2018-04-11 20:17:42] Started run 548 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:42] Error in run 542: Run already exists in server. Run id(s): {8974269}
[2018-04-11 20:17:42] Started run 549 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:42] Error in run 541: Run already exists in server. Run id(s): {8974262}
[2018-04-11 20:17:42] Started run 550 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:42] Error in run 543: Run already exists in server. Run id(s): {8974276}
[2018-04-11 20:17:42] Started run 551 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:43] Error in run 544: Run already exists in server. Run id(s): {8974287}
[2018-04-11 20:17:43] Started run 552 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:45] Error in run 545: Run already exists in server. Run id(s): {8974295}
[2018-04-11 20:17:45] Started run 553 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:45] Error in run 546: Run already exists in server. Run id(s): {8974296}
[2018-04-11 20:17:45] Started run 554 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:46] Error in run 547: Run already exists in server. Run id(s): {8974300}
[2018-04-11 20:17:46] Started run 555 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:46] Error in run 550: Run already exists in server. Run id(s): {8974322}
[2018-04-11 20:17:46] Started run 556 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:46] Error in run 548: Run already exists in server. Run id(s): {8974313}
[2018-04-11 20:17:46] Started run 557 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:46] Error in run 549: Run already exists in server. Run id(s): {8974317}
[2018-04-11 20:17:46] Started run 558 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:47] Error in run 551: Run already exists in server. Run id(s): {8974327}
[2018-04-11 20:17:47] Started run 559 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:48] Error in run 552: Run already exists in server. Run id(s): {8974339}
[2018-04-11 20:17:48] Started run 560 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:50] Error in run 553: Run already exists in server. Run id(s): {8974340}
[2018-04-11 20:17:50] Started run 561 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:50] Error in run 554: Run already exists in server. Run id(s): {8974343}
[2018-04-11 20:17:50] Started run 562 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:51] Error in run 555: Run already exists in server. Run id(s): {8974348}
[2018-04-11 20:17:51] Started run 563 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:51] Error in run 556: Run already exists in server. Run id(s): {8974367}
[2018-04-11 20:17:51] Error in run 558: Run already exists in server. Run id(s): {8974369}
[2018-04-11 20:17:51] Started run 565 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:51] Started run 564 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:51] Error in run 557: Run already exists in server. Run id(s): {8974364}
[2018-04-11 20:17:51] Started run 566 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:52] Error in run 559: Run already exists in server. Run id(s): {8974378}
[2018-04-11 20:17:52] Started run 567 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:52] Error in run 560: Run already exists in server. Run id(s): {8974388}
[2018-04-11 20:17:52] Started run 568 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:54] Error in run 561: Run already exists in server. Run id(s): {8974389}
[2018-04-11 20:17:54] Started run 569 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:55] Error in run 562: Run already exists in server. Run id(s): {8974392}
[2018-04-11 20:17:55] Started run 570 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:55] Error in run 563: Run already exists in server. Run id(s): {8974404}
[2018-04-11 20:17:55] Started run 571 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:56] Error in run 564: Run already exists in server. Run id(s): {8974419}
[2018-04-11 20:17:56] Started run 572 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:56] Error in run 566: Run already exists in server. Run id(s): {8974423}
[2018-04-11 20:17:56] Started run 573 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:56] Error in run 565: Run already exists in server. Run id(s): {8974425}
[2018-04-11 20:17:56] Started run 574 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:57] Error in run 567: Run already exists in server. Run id(s): {8974431}
[2018-04-11 20:17:57] Started run 575 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:57] Error in run 568: Run already exists in server. Run id(s): {8974437}
[2018-04-11 20:17:57] Started run 576 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:17:59] Error in run 569: Run already exists in server. Run id(s): {8974443}
[2018-04-11 20:17:59] Started run 577 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:00] Error in run 570: Run already exists in server. Run id(s): {8974445}
[2018-04-11 20:18:00] Started run 578 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:00] Error in run 571: Run already exists in server. Run id(s): {8974457}
[2018-04-11 20:18:00] Started run 579 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:00] Error in run 572: Run already exists in server. Run id(s): {8974470}
[2018-04-11 20:18:00] Started run 580 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:00] Error in run 574: Run already exists in server. Run id(s): {8974488}
[2018-04-11 20:18:00] Started run 581 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:00] Error in run 573: Run already exists in server. Run id(s): {8974485}
[2018-04-11 20:18:00] Started run 582 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:01] Error in run 575: Run already exists in server. Run id(s): {8974489}
[2018-04-11 20:18:01] Started run 583 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:02] Error in run 576: Run already exists in server. Run id(s): {8974495}
[2018-04-11 20:18:02] Started run 584 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:04] Error in run 577: Run already exists in server. Run id(s): {8974503}
[2018-04-11 20:18:04] Started run 585 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:04] Error in run 578: Run already exists in server. Run id(s): {8974506}
[2018-04-11 20:18:04] Started run 586 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:05] Error in run 579: Run already exists in server. Run id(s): {8974510}
[2018-04-11 20:18:05] Started run 587 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:05] Error in run 580: Run already exists in server. Run id(s): {8974516}
[2018-04-11 20:18:05] Started run 588 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:05] Error in run 581: Run already exists in server. Run id(s): {8974530}
[2018-04-11 20:18:05] Started run 589 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:05] Error in run 582: Run already exists in server. Run id(s): {8974539}
[2018-04-11 20:18:05] Started run 590 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:06] Error in run 583: Run already exists in server. Run id(s): {8974532}
[2018-04-11 20:18:06] Started run 591 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:07] Error in run 584: Run already exists in server. Run id(s): {8974543}
[2018-04-11 20:18:07] Started run 592 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:08] Error in run 585: Run already exists in server. Run id(s): {8974552}
[2018-04-11 20:18:08] Started run 593 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:09] Error in run 586: Run already exists in server. Run id(s): {8974557}
[2018-04-11 20:18:09] Started run 594 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:10] Error in run 589: Run already exists in server. Run id(s): {8974587}
[2018-04-11 20:18:10] Error in run 587: Run already exists in server. Run id(s): {8974559}
[2018-04-11 20:18:10] Started run 595 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:10] Started run 596 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:10] Error in run 588: Run already exists in server. Run id(s): {8974564}
[2018-04-11 20:18:10] Started run 597 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:10] Error in run 590: Run already exists in server. Run id(s): {8974579}
[2018-04-11 20:18:10] Started run 598 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:11] Error in run 591: Run already exists in server. Run id(s): {8974588}
[2018-04-11 20:18:11] Started run 599 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:11] Error in run 592: Run already exists in server. Run id(s): {8974590}
[2018-04-11 20:18:11] Started run 600 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:13] Error in run 593: Run already exists in server. Run id(s): {8974607}
[2018-04-11 20:18:13] Started run 601 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:14] Error in run 594: Run already exists in server. Run id(s): {8974608}
[2018-04-11 20:18:14] Started run 602 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:14] Error in run 596: Run already exists in server. Run id(s): {8974614}
[2018-04-11 20:18:14] Started run 603 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:14] Error in run 595: Run already exists in server. Run id(s): {8974611}
[2018-04-11 20:18:14] Started run 604 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:14] Error in run 598: Run already exists in server. Run id(s): {8974634}
[2018-04-11 20:18:14] Started run 605 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:14] Error in run 597: Run already exists in server. Run id(s): {8974628}
[2018-04-11 20:18:14] Started run 606 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:15] Error in run 599: Run already exists in server. Run id(s): {8974633}
[2018-04-11 20:18:15] Started run 607 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:16] Error in run 600: Run already exists in server. Run id(s): {8974635}
[2018-04-11 20:18:16] Started run 608 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:18] Error in run 601: Run already exists in server. Run id(s): {8974653}
[2018-04-11 20:18:18] Started run 609 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:18] Error in run 602: Run already exists in server. Run id(s): {8974656}
[2018-04-11 20:18:18] Started run 610 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:19] Error in run 605: Run already exists in server. Run id(s): {8974674}
[2018-04-11 20:18:19] Started run 611 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:19] Error in run 604: Run already exists in server. Run id(s): {8974667}
[2018-04-11 20:18:19] Error in run 603: Run already exists in server. Run id(s): {8974657}
[2018-04-11 20:18:19] Started run 612 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:19] Started run 613 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:19] Error in run 606: Run already exists in server. Run id(s): {8974681}
[2018-04-11 20:18:19] Started run 614 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:20] Error in run 607: Run already exists in server. Run id(s): {8974685}
[2018-04-11 20:18:20] Started run 615 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:21] Error in run 608: Run already exists in server. Run id(s): {8974694}
[2018-04-11 20:18:21] Started run 616 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:23] Error in run 609: Run already exists in server. Run id(s): {8974696}
[2018-04-11 20:18:23] Started run 617 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:23] Error in run 610: Run already exists in server. Run id(s): {8974707}
[2018-04-11 20:18:23] Started run 618 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:23] Error in run 613: Run already exists in server. Run id(s): {8974720}
[2018-04-11 20:18:23] Started run 619 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:24] Error in run 612: Run already exists in server. Run id(s): {8974718}
[2018-04-11 20:18:24] Error in run 611: Run already exists in server. Run id(s): {8974713}
[2018-04-11 20:18:24] Started run 620 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:24] Started run 621 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:24] Error in run 614: Run already exists in server. Run id(s): {8974731}
[2018-04-11 20:18:24] Started run 622 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:25] Error in run 615: Run already exists in server. Run id(s): {8974738}
[2018-04-11 20:18:25] Started run 623 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:25] Error in run 616: Run already exists in server. Run id(s): {8974741}
[2018-04-11 20:18:25] Started run 624 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:27] Error in run 617: Run already exists in server. Run id(s): {8974743}
[2018-04-11 20:18:27] Started run 625 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:28] Error in run 618: Run already exists in server. Run id(s): {8974757}
[2018-04-11 20:18:28] Started run 626 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:28] Error in run 621: Run already exists in server. Run id(s): {8974766}
[2018-04-11 20:18:28] Error in run 619: Run already exists in server. Run id(s): {8974758}
[2018-04-11 20:18:28] Started run 627 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:28] Started run 628 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:28] Error in run 622: Run already exists in server. Run id(s): {8974802}
[2018-04-11 20:18:28] Started run 629 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:28] Error in run 620: Run already exists in server. Run id(s): {8974765}
[2018-04-11 20:18:28] Started run 630 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:30] Error in run 623: Run already exists in server. Run id(s): {8974795}
[2018-04-11 20:18:30] Started run 631 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:30] Error in run 624: Run already exists in server. Run id(s): {8974788}
[2018-04-11 20:18:30] Started run 632 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:32] Error in run 625: Run already exists in server. Run id(s): {8974790}
[2018-04-11 20:18:32] Started run 633 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:33] Error in run 626: Run already exists in server. Run id(s): {8974818}
[2018-04-11 20:18:33] Started run 634 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:33] Error in run 627: Run already exists in server. Run id(s): {8974825}
[2018-04-11 20:18:33] Started run 635 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:33] Error in run 628: Run already exists in server. Run id(s): {8974824}
[2018-04-11 20:18:33] Started run 636 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:33] Error in run 629: Run already exists in server. Run id(s): {8974826}
[2018-04-11 20:18:33] Started run 637 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:33] Error in run 630: Run already exists in server. Run id(s): {8974841}
[2018-04-11 20:18:33] Started run 638 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:34] Error in run 631: Run already exists in server. Run id(s): {8974843}
[2018-04-11 20:18:34] Started run 639 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:35] Error in run 632: Run already exists in server. Run id(s): {8974849}
[2018-04-11 20:18:35] Started run 640 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:37] Error in run 633: Run already exists in server. Run id(s): {8974852}
[2018-04-11 20:18:37] Started run 641 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:37] Error in run 634: Run already exists in server. Run id(s): {8974865}
[2018-04-11 20:18:37] Started run 642 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:38] Error in run 635: Run already exists in server. Run id(s): {8974871}
[2018-04-11 20:18:38] Started run 643 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:38] Error in run 636: Run already exists in server. Run id(s): {8974876}
[2018-04-11 20:18:38] Started run 644 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:38] Error in run 638: Run already exists in server. Run id(s): {8974895}
[2018-04-11 20:18:38] Started run 645 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:38] Error in run 637: Run already exists in server. Run id(s): {9016121, 8974878}
[2018-04-11 20:18:38] Started run 646 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:39] Error in run 639: Run already exists in server. Run id(s): {8974893}
[2018-04-11 20:18:39] Started run 647 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:39] Error in run 640: Run already exists in server. Run id(s): {8974908}
[2018-04-11 20:18:39] Started run 648 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:41] Error in run 641: Run already exists in server. Run id(s): {8974899}
[2018-04-11 20:18:41] Started run 649 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:42] Error in run 642: Run already exists in server. Run id(s): {8974916}
[2018-04-11 20:18:42] Started run 650 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:42] Error in run 644: Run already exists in server. Run id(s): {8974921}
[2018-04-11 20:18:42] Started run 651 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:42] Error in run 643: Run already exists in server. Run id(s): {8974917}
[2018-04-11 20:18:42] Started run 652 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:43] Error in run 645: Run already exists in server. Run id(s): {8974930}
[2018-04-11 20:18:43] Started run 653 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:43] Error in run 646: Run already exists in server. Run id(s): {8974940}
[2018-04-11 20:18:43] Started run 654 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:44] Error in run 647: Run already exists in server. Run id(s): {8974941}
[2018-04-11 20:18:44] Started run 655 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:44] Error in run 648: Run already exists in server. Run id(s): {8974949}
[2018-04-11 20:18:44] Started run 656 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:46] Error in run 649: Run already exists in server. Run id(s): {8974953}
[2018-04-11 20:18:46] Started run 657 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:47] Error in run 650: Run already exists in server. Run id(s): {8974969}
[2018-04-11 20:18:47] Started run 658 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:47] Error in run 651: Run already exists in server. Run id(s): {8974971}
[2018-04-11 20:18:47] Started run 659 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:47] Error in run 652: Run already exists in server. Run id(s): {8974974}
[2018-04-11 20:18:47] Started run 660 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:47] Error in run 653: Run already exists in server. Run id(s): {8974981}
[2018-04-11 20:18:47] Started run 661 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:47] Error in run 654: Run already exists in server. Run id(s): {8974996}
[2018-04-11 20:18:47] Started run 662 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:49] Error in run 655: Run already exists in server. Run id(s): {8974989}
[2018-04-11 20:18:49] Started run 663 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:49] Error in run 656: Run already exists in server. Run id(s): {8974998}
[2018-04-11 20:18:49] Started run 664 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:51] Error in run 657: Run already exists in server. Run id(s): {8975002}
[2018-04-11 20:18:51] Started run 665 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:51] Error in run 658: Run already exists in server. Run id(s): {8975010}
[2018-04-11 20:18:51] Started run 666 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:52] Error in run 659: Run already exists in server. Run id(s): {8975014}
[2018-04-11 20:18:52] Error in run 660: Run already exists in server. Run id(s): {8975023}
[2018-04-11 20:18:52] Started run 667 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:52] Started run 668 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:52] Error in run 661: Run already exists in server. Run id(s): {8975020}
[2018-04-11 20:18:52] Error in run 662: Run already exists in server. Run id(s): {8975028}
[2018-04-11 20:18:52] Started run 669 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:52] Started run 670 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:53] Error in run 663: Run already exists in server. Run id(s): {8975030}
[2018-04-11 20:18:53] Started run 671 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:54] Error in run 664: Run already exists in server. Run id(s): {8975037}
[2018-04-11 20:18:54] Started run 672 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:55] Error in run 665: Run already exists in server. Run id(s): {8975039}
[2018-04-11 20:18:55] Started run 673 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:56] Error in run 666: Run already exists in server. Run id(s): {8975049}
[2018-04-11 20:18:56] Started run 674 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:56] Error in run 667: Run already exists in server. Run id(s): {8975059}
[2018-04-11 20:18:56] Started run 675 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:57] Error in run 668: Run already exists in server. Run id(s): {8975062}
[2018-04-11 20:18:57] Started run 676 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:57] Error in run 670: Run already exists in server. Run id(s): {8975087}
[2018-04-11 20:18:57] Started run 677 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:57] Error in run 669: Run already exists in server. Run id(s): {8975073}
[2018-04-11 20:18:57] Started run 678 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:58] Error in run 671: Run already exists in server. Run id(s): {8975080}
[2018-04-11 20:18:58] Started run 679 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:18:58] Error in run 672: Run already exists in server. Run id(s): {8975086}
[2018-04-11 20:18:58] Started run 680 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:00] Error in run 673: Run already exists in server. Run id(s): {8975096}
[2018-04-11 20:19:00] Started run 681 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:01] Error in run 674: Run already exists in server. Run id(s): {8975113}
[2018-04-11 20:19:01] Started run 682 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:01] Error in run 675: Run already exists in server. Run id(s): {8975115}
[2018-04-11 20:19:01] Started run 683 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:01] Error in run 676: Run already exists in server. Run id(s): {8975104}
[2018-04-11 20:19:01] Started run 684 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:01] Error in run 678: Run already exists in server. Run id(s): {8975125}
[2018-04-11 20:19:01] Started run 685 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:01] Error in run 677: Run already exists in server. Run id(s): {8975114}
[2018-04-11 20:19:01] Started run 686 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:03] Error in run 679: Run already exists in server. Run id(s): {8975127}
[2018-04-11 20:19:03] Started run 687 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:03] Error in run 680: Run already exists in server. Run id(s): {8975131}
[2018-04-11 20:19:03] Started run 688 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:04] Error in run 681: Run already exists in server. Run id(s): {8975133}
[2018-04-11 20:19:04] Started run 689 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:05] Error in run 682: Run already exists in server. Run id(s): {8975138}
[2018-04-11 20:19:05] Started run 690 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:06] Error in run 684: Run already exists in server. Run id(s): {8975146}
[2018-04-11 20:19:06] Started run 691 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:06] Error in run 683: Run already exists in server. Run id(s): {8975143}
[2018-04-11 20:19:06] Started run 692 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:06] Error in run 685: Run already exists in server. Run id(s): {8975150}
[2018-04-11 20:19:06] Started run 693 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:06] Error in run 686: Run already exists in server. Run id(s): {8975154}
[2018-04-11 20:19:06] Started run 694 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:07] Error in run 687: Run already exists in server. Run id(s): {8975163}
[2018-04-11 20:19:07] Started run 695 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:08] Error in run 688: Run already exists in server. Run id(s): {8975162}
[2018-04-11 20:19:08] Started run 696 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:09] Error in run 689: Run already exists in server. Run id(s): {8975166}
[2018-04-11 20:19:09] Started run 697 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:10] Error in run 690: Run already exists in server. Run id(s): {8975169}
[2018-04-11 20:19:10] Started run 698 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:11] Error in run 691: Run already exists in server. Run id(s): {8975180}
[2018-04-11 20:19:11] Started run 699 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:11] Error in run 692: Run already exists in server. Run id(s): {8975186}
[2018-04-11 20:19:11] Error in run 693: Run already exists in server. Run id(s): {8975184}
[2018-04-11 20:19:11] Started run 700 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:11] Started run 701 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:11] Error in run 694: Run already exists in server. Run id(s): {8975191}
[2018-04-11 20:19:11] Started run 702 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:12] Error in run 695: Run already exists in server. Run id(s): {8975197}
[2018-04-11 20:19:12] Started run 703 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:12] Error in run 696: Run already exists in server. Run id(s): {8975199}
[2018-04-11 20:19:12] Started run 704 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:14] Error in run 697: Run already exists in server. Run id(s): {8975201}
[2018-04-11 20:19:14] Started run 705 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:15] Error in run 698: Run already exists in server. Run id(s): {8975205}
[2018-04-11 20:19:15] Started run 706 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:15] Error in run 699: Run already exists in server. Run id(s): {8975213}
[2018-04-11 20:19:15] Started run 707 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:15] Error in run 701: Run already exists in server. Run id(s): {8975229}
[2018-04-11 20:19:15] Error in run 700: Run already exists in server. Run id(s): {8975215}
[2018-04-11 20:19:15] Started run 708 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:15] Started run 709 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:16] Error in run 702: Run already exists in server. Run id(s): {8975228}
[2018-04-11 20:19:16] Started run 710 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:17] Error in run 703: Run already exists in server. Run id(s): {8975247}
[2018-04-11 20:19:17] Started run 711 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:17] Error in run 704: Run already exists in server. Run id(s): {8975241}
[2018-04-11 20:19:17] Started run 712 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:19] Error in run 705: Run already exists in server. Run id(s): {8975249}
[2018-04-11 20:19:19] Started run 713 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:19] Error in run 706: Run already exists in server. Run id(s): {8975259}
[2018-04-11 20:19:19] Started run 714 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:20] Error in run 707: Run already exists in server. Run id(s): {8975264}
[2018-04-11 20:19:20] Started run 715 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:20] Error in run 708: Run already exists in server. Run id(s): {9016481, 8975267}
[2018-04-11 20:19:20] Started run 716 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:20] Error in run 709: Run already exists in server. Run id(s): {8975268}
[2018-04-11 20:19:20] Started run 717 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:20] Error in run 710: Run already exists in server. Run id(s): {8975286}
[2018-04-11 20:19:20] Started run 718 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:21] Error in run 711: Run already exists in server. Run id(s): {8975279}
[2018-04-11 20:19:21] Started run 719 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:22] Error in run 712: Run already exists in server. Run id(s): {8975280}
[2018-04-11 20:19:22] Started run 720 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:23] Error in run 713: Run already exists in server. Run id(s): {8975288}
[2018-04-11 20:19:23] Started run 721 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:24] Error in run 714: Run already exists in server. Run id(s): {8975315}
[2018-04-11 20:19:24] Started run 722 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:25] Error in run 715: Run already exists in server. Run id(s): {8975321}
[2018-04-11 20:19:25] Started run 723 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:25] Error in run 716: Run already exists in server. Run id(s): {8975334}
[2018-04-11 20:19:25] Started run 724 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:25] Error in run 717: Run already exists in server. Run id(s): {8975336}
[2018-04-11 20:19:25] Started run 725 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:25] Error in run 718: Run already exists in server. Run id(s): {8975344}
[2018-04-11 20:19:25] Started run 726 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:26] Error in run 719: Run already exists in server. Run id(s): {8975346}
[2018-04-11 20:19:26] Started run 727 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:26] Error in run 720: Run already exists in server. Run id(s): {8975354}
[2018-04-11 20:19:26] Started run 728 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:28] Error in run 721: Run already exists in server. Run id(s): {8975357}
[2018-04-11 20:19:28] Started run 729 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:29] Error in run 722: Run already exists in server. Run id(s): {8975363}
[2018-04-11 20:19:29] Started run 730 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:29] Error in run 723: Run already exists in server. Run id(s): {8975367}
[2018-04-11 20:19:29] Started run 731 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:29] Error in run 724: Run already exists in server. Run id(s): {8975387}
[2018-04-11 20:19:29] Started run 732 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:30] Error in run 725: Run already exists in server. Run id(s): {8975395}
[2018-04-11 20:19:30] Started run 733 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:30] Error in run 726: Run already exists in server. Run id(s): {8975399}
[2018-04-11 20:19:30] Started run 734 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:31] Error in run 727: Run already exists in server. Run id(s): {8975418}
[2018-04-11 20:19:31] Started run 735 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:31] Error in run 728: Run already exists in server. Run id(s): {8975477}
[2018-04-11 20:19:31] Started run 736 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:33] Error in run 729: Run already exists in server. Run id(s): {8975462}
[2018-04-11 20:19:33] Started run 737 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:34] Error in run 730: Run already exists in server. Run id(s): {8975479}
[2018-04-11 20:19:34] Started run 738 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:34] Error in run 731: Run already exists in server. Run id(s): {8975504}
[2018-04-11 20:19:34] Started run 739 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:34] Error in run 732: Run already exists in server. Run id(s): {8975525}
[2018-04-11 20:19:34] Started run 740 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:34] Error in run 733: Run already exists in server. Run id(s): {8975539}
[2018-04-11 20:19:34] Started run 741 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:34] Error in run 734: Run already exists in server. Run id(s): {8975542}
[2018-04-11 20:19:34] Started run 742 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:36] Error in run 735: Run already exists in server. Run id(s): {8975560}
[2018-04-11 20:19:36] Started run 743 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:36] Error in run 736: Run already exists in server. Run id(s): {8975566}
[2018-04-11 20:19:36] Started run 744 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:37] Error in run 737: Run already exists in server. Run id(s): {8975582}
[2018-04-11 20:19:37] Started run 745 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:38] Error in run 738: Run already exists in server. Run id(s): {8975584}
[2018-04-11 20:19:38] Started run 746 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:39] Error in run 739: Run already exists in server. Run id(s): {8975610}
[2018-04-11 20:19:39] Started run 747 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:39] Error in run 740: Run already exists in server. Run id(s): {8975615}
[2018-04-11 20:19:39] Started run 748 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:39] Error in run 741: Run already exists in server. Run id(s): {8975630}
[2018-04-11 20:19:39] Started run 749 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:39] Error in run 742: Run already exists in server. Run id(s): {8975647}
[2018-04-11 20:19:39] Started run 750 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:40] Error in run 743: Run already exists in server. Run id(s): {8975656}
[2018-04-11 20:19:40] Started run 751 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:40] Error in run 744: Run already exists in server. Run id(s): {8975669}
[2018-04-11 20:19:40] Started run 752 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:42] Error in run 745: Run already exists in server. Run id(s): {8975679}
[2018-04-11 20:19:42] Started run 753 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:43] Error in run 746: Run already exists in server. Run id(s): {8975692}
[2018-04-11 20:19:43] Started run 754 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:43] Error in run 747: Run already exists in server. Run id(s): {8975712}
[2018-04-11 20:19:43] Started run 755 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:43] Error in run 748: Run already exists in server. Run id(s): {8975704}
[2018-04-11 20:19:43] Started run 756 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:44] Error in run 749: Run already exists in server. Run id(s): {8975749}
[2018-04-11 20:19:44] Started run 757 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:44] Error in run 750: Run already exists in server. Run id(s): {8975740}
[2018-04-11 20:19:44] Started run 758 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:45] Error in run 751: Run already exists in server. Run id(s): {8975762}
[2018-04-11 20:19:45] Started run 759 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:45] Error in run 752: Run already exists in server. Run id(s): {8975768}
[2018-04-11 20:19:45] Started run 760 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:47] Error in run 753: Run already exists in server. Run id(s): {8975817}
[2018-04-11 20:19:47] Started run 761 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:48] Error in run 754: Run already exists in server. Run id(s): {8975804}
[2018-04-11 20:19:48] Started run 762 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:48] Error in run 755: Run already exists in server. Run id(s): {8975835}
[2018-04-11 20:19:48] Started run 763 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:48] Error in run 756: Run already exists in server. Run id(s): {8975855}
[2018-04-11 20:19:48] Started run 764 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:48] Error in run 757: Run already exists in server. Run id(s): {8975861}
[2018-04-11 20:19:48] Started run 765 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:49] Error in run 758: Run already exists in server. Run id(s): {8975871}
[2018-04-11 20:19:49] Started run 766 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:50] Error in run 759: Run already exists in server. Run id(s): {8975886}
[2018-04-11 20:19:50] Started run 767 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:50] Error in run 760: Run already exists in server. Run id(s): {8975914}
[2018-04-11 20:19:50] Started run 768 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:51] Error in run 761: Run already exists in server. Run id(s): {8975902}
[2018-04-11 20:19:51] Started run 769 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:52] Error in run 762: Run already exists in server. Run id(s): {8975909}
[2018-04-11 20:19:52] Started run 770 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:53] Error in run 764: Run already exists in server. Run id(s): {8975958}
[2018-04-11 20:19:53] Error in run 763: Run already exists in server. Run id(s): {8975960}
[2018-04-11 20:19:53] Started run 771 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:53] Started run 772 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:53] Error in run 765: Run already exists in server. Run id(s): {8975966}
[2018-04-11 20:19:53] Started run 773 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:53] Error in run 766: Run already exists in server. Run id(s): {8975988}
[2018-04-11 20:19:53] Started run 774 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:54] Error in run 767: Run already exists in server. Run id(s): {8976002}
[2018-04-11 20:19:54] Started run 775 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:55] Error in run 768: Run already exists in server. Run id(s): {8976000}
[2018-04-11 20:19:55] Started run 776 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:56] Error in run 769: Run already exists in server. Run id(s): {8976010}
[2018-04-11 20:19:56] Started run 777 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:57] Error in run 770: Run already exists in server. Run id(s): {8976040}
[2018-04-11 20:19:57] Started run 778 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:57] Error in run 771: Run already exists in server. Run id(s): {8976051}
[2018-04-11 20:19:57] Started run 779 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:57] Error in run 772: Run already exists in server. Run id(s): {8976053}
[2018-04-11 20:19:57] Started run 780 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:58] Error in run 773: Run already exists in server. Run id(s): {8976057}
[2018-04-11 20:19:58] Started run 781 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:58] Error in run 774: Run already exists in server. Run id(s): {8976087}
[2018-04-11 20:19:58] Started run 782 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:59] Error in run 775: Run already exists in server. Run id(s): {8976079}
[2018-04-11 20:19:59] Started run 783 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:19:59] Error in run 776: Run already exists in server. Run id(s): {8976077}
[2018-04-11 20:19:59] Started run 784 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:01] Error in run 777: Run already exists in server. Run id(s): {8976134}
[2018-04-11 20:20:01] Started run 785 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:02] Error in run 778: Run already exists in server. Run id(s): {8976186}
[2018-04-11 20:20:02] Started run 786 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:02] Error in run 780: Run already exists in server. Run id(s): {8976159}
[2018-04-11 20:20:02] Started run 787 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:02] Error in run 779: Run already exists in server. Run id(s): {8976152}
[2018-04-11 20:20:02] Started run 788 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:02] Error in run 781: Run already exists in server. Run id(s): {8976241}
[2018-04-11 20:20:02] Started run 789 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:03] Error in run 782: Run already exists in server. Run id(s): {8976244}
[2018-04-11 20:20:03] Started run 790 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:04] Error in run 783: Run already exists in server. Run id(s): {8976236}
[2018-04-11 20:20:04] Started run 791 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:04] Error in run 784: Run already exists in server. Run id(s): {8976249}
[2018-04-11 20:20:04] Started run 792 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:05] Error in run 785: Run already exists in server. Run id(s): {8976306}
[2018-04-11 20:20:05] Started run 793 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:06] Error in run 786: Run already exists in server. Run id(s): {8976311}
[2018-04-11 20:20:06] Started run 794 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:07] Error in run 787: Run already exists in server. Run id(s): {8976364}
[2018-04-11 20:20:07] Started run 795 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:07] Error in run 788: Run already exists in server. Run id(s): {8976360}
[2018-04-11 20:20:07] Started run 796 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:07] Error in run 789: Run already exists in server. Run id(s): {8976387}
[2018-04-11 20:20:07] Started run 797 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:08] Error in run 790: Run already exists in server. Run id(s): {8976389}
[2018-04-11 20:20:08] Started run 798 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:09] Error in run 791: Run already exists in server. Run id(s): {8976414}
[2018-04-11 20:20:09] Started run 799 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:09] Error in run 792: Run already exists in server. Run id(s): {8976438}
[2018-04-11 20:20:09] Started run 800 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:10] Error in run 793: Run already exists in server. Run id(s): {8976430}
[2018-04-11 20:20:10] Started run 801 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:11] Error in run 794: Run already exists in server. Run id(s): {8976432}
[2018-04-11 20:20:11] Started run 802 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:11] Error in run 795: Run already exists in server. Run id(s): {8976495}
[2018-04-11 20:20:11] Started run 803 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:12] Error in run 797: Run already exists in server. Run id(s): {8976568}
[2018-04-11 20:20:12] Started run 804 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:12] Error in run 796: Run already exists in server. Run id(s): {8976590}
[2018-04-11 20:20:12] Started run 805 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:12] Error in run 798: Run already exists in server. Run id(s): {8976592}
[2018-04-11 20:20:12] Started run 806 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:13] Error in run 799: Run already exists in server. Run id(s): {8976613}
[2018-04-11 20:20:13] Started run 807 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:13] Error in run 800: Run already exists in server. Run id(s): {8976650}
[2018-04-11 20:20:13] Started run 808 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:15] Error in run 801: Run already exists in server. Run id(s): {8976666}
[2018-04-11 20:20:15] Started run 809 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:16] Error in run 802: Run already exists in server. Run id(s): {8976668}
[2018-04-11 20:20:16] Started run 810 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:16] Error in run 803: Run already exists in server. Run id(s): {8976684}
[2018-04-11 20:20:16] Started run 811 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:16] Error in run 804: Run already exists in server. Run id(s): {8976729}
[2018-04-11 20:20:16] Started run 812 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:16] Error in run 805: Run already exists in server. Run id(s): {8976771}
[2018-04-11 20:20:16] Started run 813 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:17] Error in run 806: Run already exists in server. Run id(s): {8976749}
[2018-04-11 20:20:17] Started run 814 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:18] Error in run 807: Run already exists in server. Run id(s): {8976804}
[2018-04-11 20:20:18] Started run 815 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:18] Error in run 808: Run already exists in server. Run id(s): {8976810}
[2018-04-11 20:20:18] Started run 816 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:20] Error in run 809: Run already exists in server. Run id(s): {8976847}
[2018-04-11 20:20:20] Started run 817 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:20] Error in run 810: Run already exists in server. Run id(s): {8976854}
[2018-04-11 20:20:20] Started run 818 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:21] Error in run 811: Run already exists in server. Run id(s): {8976875}
[2018-04-11 20:20:21] Started run 819 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:21] Error in run 812: Run already exists in server. Run id(s): {8976880}
[2018-04-11 20:20:21] Started run 820 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:21] Error in run 813: Run already exists in server. Run id(s): {8976910}
[2018-04-11 20:20:21] Started run 821 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:22] Error in run 814: Run already exists in server. Run id(s): {8976920}
[2018-04-11 20:20:22] Started run 822 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:23] Error in run 815: Run already exists in server. Run id(s): {8976946}
[2018-04-11 20:20:23] Started run 823 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:23] Error in run 816: Run already exists in server. Run id(s): {8976955}
[2018-04-11 20:20:23] Started run 824 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:24] Error in run 817: Run already exists in server. Run id(s): {8976961}
[2018-04-11 20:20:24] Started run 825 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:25] Error in run 818: Run already exists in server. Run id(s): {8976990}
[2018-04-11 20:20:25] Started run 826 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:26] Error in run 819: Run already exists in server. Run id(s): {8976988}
[2018-04-11 20:20:26] Error in run 820: Run already exists in server. Run id(s): {8977004}
[2018-04-11 20:20:26] Started run 827 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:26] Started run 828 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:26] Error in run 821: Run already exists in server. Run id(s): {8977040}
[2018-04-11 20:20:26] Started run 829 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:26] Error in run 822: Run already exists in server. Run id(s): {8977041}
[2018-04-11 20:20:26] Started run 830 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:27] Error in run 823: Run already exists in server. Run id(s): {8977042}
[2018-04-11 20:20:27] Started run 831 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:28] Error in run 824: Run already exists in server. Run id(s): {8977054}
[2018-04-11 20:20:28] Started run 832 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:29] Error in run 825: Run already exists in server. Run id(s): {8977090}
[2018-04-11 20:20:29] Started run 833 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:30] Error in run 826: Run already exists in server. Run id(s): {8977087}
[2018-04-11 20:20:30] Started run 834 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:30] Error in run 827: Run already exists in server. Run id(s): {8977093}
[2018-04-11 20:20:30] Started run 835 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:30] Error in run 828: Run already exists in server. Run id(s): {8977098}
[2018-04-11 20:20:30] Started run 836 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:31] Error in run 829: Run already exists in server. Run id(s): {8977124}
[2018-04-11 20:20:31] Started run 837 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:31] Error in run 830: Run already exists in server. Run id(s): {8977125}
[2018-04-11 20:20:31] Started run 838 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:32] Error in run 832: Run already exists in server. Run id(s): {8977152}
[2018-04-11 20:20:32] Started run 839 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:32] Error in run 831: Run already exists in server. Run id(s): {8977127}
[2018-04-11 20:20:32] Started run 840 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:34] Error in run 833: Run already exists in server. Run id(s): {8977225}
[2018-04-11 20:20:34] Started run 841 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:35] Error in run 834: Run already exists in server. Run id(s): {8977199}
[2018-04-11 20:20:35] Started run 842 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:35] Error in run 835: Run already exists in server. Run id(s): {8977202}
[2018-04-11 20:20:35] Started run 843 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:35] Error in run 836: Run already exists in server. Run id(s): {8977212}
[2018-04-11 20:20:35] Started run 844 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:35] Error in run 837: Run already exists in server. Run id(s): {8977243}
[2018-04-11 20:20:35] Started run 845 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:36] Error in run 838: Run already exists in server. Run id(s): {8977249}
[2018-04-11 20:20:36] Started run 846 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:37] Error in run 839: Run already exists in server. Run id(s): {8977252}
[2018-04-11 20:20:37] Started run 847 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:37] Error in run 840: Run already exists in server. Run id(s): {8977261}
[2018-04-11 20:20:37] Started run 848 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:38] Error in run 841: Run already exists in server. Run id(s): {8977280}
[2018-04-11 20:20:38] Started run 849 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:39] Error in run 842: Run already exists in server. Run id(s): {8977284}
[2018-04-11 20:20:39] Started run 850 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:40] Error in run 843: Run already exists in server. Run id(s): {8977337}
[2018-04-11 20:20:40] Started run 851 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:40] Error in run 844: Run already exists in server. Run id(s): {8977321}
[2018-04-11 20:20:40] Started run 852 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:40] Error in run 845: Run already exists in server. Run id(s): {8977364}
[2018-04-11 20:20:40] Started run 853 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:40] Error in run 846: Run already exists in server. Run id(s): {8977360}
[2018-04-11 20:20:40] Started run 854 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:41] Error in run 847: Run already exists in server. Run id(s): {8977386}
[2018-04-11 20:20:41] Started run 855 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:41] Error in run 848: Run already exists in server. Run id(s): {8977403}
[2018-04-11 20:20:41] Started run 856 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:43] Error in run 849: Run already exists in server. Run id(s): {8977413}
[2018-04-11 20:20:43] Started run 857 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:44] Error in run 850: Run already exists in server. Run id(s): {8977418}
[2018-04-11 20:20:44] Started run 858 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:44] Error in run 852: Run already exists in server. Run id(s): {8977440}
[2018-04-11 20:20:44] Started run 859 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:44] Error in run 851: Run already exists in server. Run id(s): {8977431}
[2018-04-11 20:20:44] Started run 860 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:45] Error in run 853: Run already exists in server. Run id(s): {8977465}
[2018-04-11 20:20:45] Started run 861 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:45] Error in run 854: Run already exists in server. Run id(s): {8977469}
[2018-04-11 20:20:45] Started run 862 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:46] Error in run 855: Run already exists in server. Run id(s): {8977528}
[2018-04-11 20:20:46] Started run 863 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:46] Error in run 856: Run already exists in server. Run id(s): {8977492}
[2018-04-11 20:20:46] Started run 864 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:48] Error in run 857: Run already exists in server. Run id(s): {8977559}
[2018-04-11 20:20:48] Started run 865 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:49] Error in run 859: Run already exists in server. Run id(s): {8977608}
[2018-04-11 20:20:49] Started run 866 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:49] Error in run 858: Run already exists in server. Run id(s): {8977565}
[2018-04-11 20:20:49] Started run 867 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:49] Error in run 860: Run already exists in server. Run id(s): {8977645}
[2018-04-11 20:20:49] Started run 868 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:49] Error in run 861: Run already exists in server. Run id(s): {8977652}
[2018-04-11 20:20:49] Started run 869 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:50] Error in run 862: Run already exists in server. Run id(s): {8977644}
[2018-04-11 20:20:50] Started run 870 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:51] Error in run 863: Run already exists in server. Run id(s): {8977658}
[2018-04-11 20:20:51] Started run 871 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:51] Error in run 864: Run already exists in server. Run id(s): {8977719}
[2018-04-11 20:20:51] Started run 872 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:53] Error in run 865: Run already exists in server. Run id(s): {8977696}
[2018-04-11 20:20:53] Started run 873 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:54] Error in run 867: Run already exists in server. Run id(s): {8977726}
[2018-04-11 20:20:54] Started run 874 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:54] Error in run 866: Run already exists in server. Run id(s): {8977702}
[2018-04-11 20:20:54] Started run 875 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:54] Error in run 868: Run already exists in server. Run id(s): {8977774}
[2018-04-11 20:20:54] Started run 876 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:54] Error in run 869: Run already exists in server. Run id(s): {8977778}
[2018-04-11 20:20:54] Started run 877 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:54] Error in run 870: Run already exists in server. Run id(s): {8977790}
[2018-04-11 20:20:54] Started run 878 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:55] Error in run 871: Run already exists in server. Run id(s): {8977829}
[2018-04-11 20:20:55] Started run 879 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:56] Error in run 872: Run already exists in server. Run id(s): {8977839}
[2018-04-11 20:20:56] Started run 880 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:57] Error in run 873: Run already exists in server. Run id(s): {8977842}
[2018-04-11 20:20:57] Started run 881 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:58] Error in run 874: Run already exists in server. Run id(s): {8977847}
[2018-04-11 20:20:58] Started run 882 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:58] Error in run 875: Run already exists in server. Run id(s): {8977882}
[2018-04-11 20:20:58] Started run 883 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:59] Error in run 876: Run already exists in server. Run id(s): {8977892}
[2018-04-11 20:20:59] Started run 884 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:59] Error in run 877: Run already exists in server. Run id(s): {8977952}
[2018-04-11 20:20:59] Started run 885 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:20:59] Error in run 878: Run already exists in server. Run id(s): {8977915}
[2018-04-11 20:20:59] Started run 886 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:00] Error in run 879: Run already exists in server. Run id(s): {8977968}
[2018-04-11 20:21:00] Started run 887 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:00] Error in run 880: Run already exists in server. Run id(s): {8977989}
[2018-04-11 20:21:00] Started run 888 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:02] Error in run 881: Run already exists in server. Run id(s): {8978004}
[2018-04-11 20:21:02] Started run 889 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:03] Error in run 882: Run already exists in server. Run id(s): {8978024}
[2018-04-11 20:21:03] Started run 890 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:03] Error in run 883: Run already exists in server. Run id(s): {8978038}
[2018-04-11 20:21:03] Started run 891 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:03] Error in run 885: Run already exists in server. Run id(s): {8978060}
[2018-04-11 20:21:03] Error in run 884: Run already exists in server. Run id(s): {8978053}
[2018-04-11 20:21:03] Started run 892 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:03] Started run 893 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:04] Error in run 886: Run already exists in server. Run id(s): {8978092}
[2018-04-11 20:21:04] Started run 894 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:05] Error in run 887: Run already exists in server. Run id(s): {8978087}
[2018-04-11 20:21:05] Started run 895 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:05] Error in run 888: Run already exists in server. Run id(s): {8978101}
[2018-04-11 20:21:05] Started run 896 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:07] Error in run 889: Run already exists in server. Run id(s): {8978107, 9016916}
[2018-04-11 20:21:07] Started run 897 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:08] Error in run 890: Run already exists in server. Run id(s): {8978138}
[2018-04-11 20:21:08] Started run 898 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:08] Error in run 893: Run already exists in server. Run id(s): {8978185}
[2018-04-11 20:21:08] Started run 899 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:08] Error in run 891: Run already exists in server. Run id(s): {8978162}
[2018-04-11 20:21:08] Started run 900 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:08] Error in run 892: Run already exists in server. Run id(s): {8978155}
[2018-04-11 20:21:08] Started run 901 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:08] Error in run 894: Run already exists in server. Run id(s): {8978196}
[2018-04-11 20:21:08] Started run 902 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:09] Error in run 895: Run already exists in server. Run id(s): {8978207}
[2018-04-11 20:21:09] Started run 903 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:09] Error in run 896: Run already exists in server. Run id(s): {8978216}
[2018-04-11 20:21:09] Started run 904 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:12] Error in run 897: Run already exists in server. Run id(s): {8978254}
[2018-04-11 20:21:12] Started run 905 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:12] Error in run 898: Run already exists in server. Run id(s): {8978260}
[2018-04-11 20:21:12] Started run 906 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:13] Error in run 899: Run already exists in server. Run id(s): {8978283}
[2018-04-11 20:21:13] Started run 907 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:13] Error in run 901: Run already exists in server. Run id(s): {8978370}
[2018-04-11 20:21:13] Started run 908 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:13] Error in run 900: Run already exists in server. Run id(s): {8978282}
[2018-04-11 20:21:13] Started run 909 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:13] Error in run 902: Run already exists in server. Run id(s): {8978362}
[2018-04-11 20:21:13] Started run 910 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:14] Error in run 904: Run already exists in server. Run id(s): {8978368}
[2018-04-11 20:21:14] Started run 911 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:14] Error in run 903: Run already exists in server. Run id(s): {8978367}
[2018-04-11 20:21:14] Started run 912 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:16] Error in run 905: Run already exists in server. Run id(s): {8978429}
[2018-04-11 20:21:16] Started run 913 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:17] Error in run 906: Run already exists in server. Run id(s): {8978452}
[2018-04-11 20:21:17] Started run 914 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:17] Error in run 907: Run already exists in server. Run id(s): {8978445}
[2018-04-11 20:21:17] Started run 915 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:17] Error in run 909: Run already exists in server. Run id(s): {8978500}
[2018-04-11 20:21:17] Started run 916 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:18] Error in run 908: Run already exists in server. Run id(s): {8978444}
[2018-04-11 20:21:18] Started run 917 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:18] Error in run 910: Run already exists in server. Run id(s): {8978506}
[2018-04-11 20:21:18] Started run 918 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:19] Error in run 911: Run already exists in server. Run id(s): {8978504}
[2018-04-11 20:21:19] Started run 919 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:19] Error in run 912: Run already exists in server. Run id(s): {8978513}
[2018-04-11 20:21:19] Started run 920 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:21] Error in run 913: Run already exists in server. Run id(s): {8978568}
[2018-04-11 20:21:21] Started run 921 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:22] Error in run 914: Run already exists in server. Run id(s): {8978566}
[2018-04-11 20:21:22] Started run 922 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:22] Error in run 915: Run already exists in server. Run id(s): {8978624}
[2018-04-11 20:21:22] Started run 923 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:22] Error in run 916: Run already exists in server. Run id(s): {8978580}
[2018-04-11 20:21:22] Started run 924 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:22] Error in run 917: Run already exists in server. Run id(s): {8978643}
[2018-04-11 20:21:22] Started run 925 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:23] Error in run 918: Run already exists in server. Run id(s): {8978671}
[2018-04-11 20:21:23] Started run 926 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:23] Error in run 919: Run already exists in server. Run id(s): {8978665}
[2018-04-11 20:21:23] Started run 927 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:24] Error in run 920: Run already exists in server. Run id(s): {8978675}
[2018-04-11 20:21:24] Started run 928 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:26] Error in run 921: Run already exists in server. Run id(s): {8978707}
[2018-04-11 20:21:26] Started run 929 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:27] Error in run 922: Run already exists in server. Run id(s): {8978715}
[2018-04-11 20:21:27] Started run 930 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:27] Error in run 925: Run already exists in server. Run id(s): {8978758}
[2018-04-11 20:21:27] Started run 931 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:27] Error in run 923: Run already exists in server. Run id(s): {8978711}
[2018-04-11 20:21:27] Started run 932 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:27] Error in run 924: Run already exists in server. Run id(s): {8978725}
[2018-04-11 20:21:27] Started run 933 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:27] Error in run 926: Run already exists in server. Run id(s): {8978763}
[2018-04-11 20:21:27] Started run 934 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:28] Error in run 927: Run already exists in server. Run id(s): {8978767}
[2018-04-11 20:21:28] Started run 935 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:28] Error in run 928: Run already exists in server. Run id(s): {8978776}
[2018-04-11 20:21:28] Started run 936 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:31] Error in run 929: Run already exists in server. Run id(s): {8978830}
[2018-04-11 20:21:31] Started run 937 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:31] Error in run 930: Run already exists in server. Run id(s): {8978831}
[2018-04-11 20:21:31] Started run 938 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:32] Error in run 933: Run already exists in server. Run id(s): {8978898}
[2018-04-11 20:21:32] Started run 939 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:32] Error in run 931: Run already exists in server. Run id(s): {8978862}
[2018-04-11 20:21:32] Started run 940 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:32] Error in run 932: Run already exists in server. Run id(s): {8978873}
[2018-04-11 20:21:32] Started run 941 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:32] Error in run 934: Run already exists in server. Run id(s): {8978900}
[2018-04-11 20:21:32] Started run 942 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:33] Error in run 935: Run already exists in server. Run id(s): {8978911}
[2018-04-11 20:21:33] Started run 943 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:33] Error in run 936: Run already exists in server. Run id(s): {8978922}
[2018-04-11 20:21:33] Started run 944 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:35] Error in run 937: Run already exists in server. Run id(s): {8978942}
[2018-04-11 20:21:35] Started run 945 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:36] Error in run 938: Run already exists in server. Run id(s): {8978964}
[2018-04-11 20:21:36] Started run 946 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:36] Error in run 939: Run already exists in server. Run id(s): {8978992}
[2018-04-11 20:21:36] Started run 947 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:36] Error in run 940: Run already exists in server. Run id(s): {8978981}
[2018-04-11 20:21:36] Error in run 941: Run already exists in server. Run id(s): {8979012}
[2018-04-11 20:21:36] Started run 948 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:36] Started run 949 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:37] Error in run 942: Run already exists in server. Run id(s): {8979029}
[2018-04-11 20:21:37] Started run 950 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:37] Error in run 943: Run already exists in server. Run id(s): {8979080}
[2018-04-11 20:21:37] Started run 951 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:38] Error in run 944: Run already exists in server. Run id(s): {8979081}
[2018-04-11 20:21:38] Started run 952 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:40] Error in run 945: Run already exists in server. Run id(s): {8979088}
[2018-04-11 20:21:40] Started run 953 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:41] Error in run 946: Run already exists in server. Run id(s): {8979120}
[2018-04-11 20:21:41] Started run 954 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:41] Error in run 949: Run already exists in server. Run id(s): {8979156}
[2018-04-11 20:21:41] Started run 955 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:41] Error in run 948: Run already exists in server. Run id(s): {8979142}
[2018-04-11 20:21:41] Started run 956 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:41] Error in run 947: Run already exists in server. Run id(s): {8979141}
[2018-04-11 20:21:41] Started run 957 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:41] Error in run 950: Run already exists in server. Run id(s): {8979178}
[2018-04-11 20:21:41] Started run 958 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:42] Error in run 951: Run already exists in server. Run id(s): {8979195}
[2018-04-11 20:21:42] Started run 959 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:43] Error in run 952: Run already exists in server. Run id(s): {8979209}
[2018-04-11 20:21:43] Started run 960 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:45] Error in run 953: Run already exists in server. Run id(s): {8979214}
[2018-04-11 20:21:45] Started run 961 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:45] Error in run 954: Run already exists in server. Run id(s): {8979250}
[2018-04-11 20:21:45] Started run 962 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:46] Error in run 955: Run already exists in server. Run id(s): {8979258}
[2018-04-11 20:21:46] Started run 963 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:46] Error in run 957: Run already exists in server. Run id(s): {8979285}
[2018-04-11 20:21:46] Started run 964 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:46] Error in run 956: Run already exists in server. Run id(s): {8979272}
[2018-04-11 20:21:46] Started run 965 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:46] Error in run 958: Run already exists in server. Run id(s): {8979309}
[2018-04-11 20:21:46] Started run 966 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:47] Error in run 959: Run already exists in server. Run id(s): {8979329}
[2018-04-11 20:21:47] Started run 967 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:47] Error in run 960: Run already exists in server. Run id(s): {8979344, 9017160}
[2018-04-11 20:21:47] Started run 968 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:49] Error in run 961: Run already exists in server. Run id(s): {8979346}
[2018-04-11 20:21:49] Started run 969 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:50] Error in run 962: Run already exists in server. Run id(s): {8979375}
[2018-04-11 20:21:50] Started run 970 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:50] Error in run 963: Run already exists in server. Run id(s): {8979384}
[2018-04-11 20:21:50] Started run 971 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:50] Error in run 964: Run already exists in server. Run id(s): {8979398}
[2018-04-11 20:21:50] Error in run 965: Run already exists in server. Run id(s): {8979415}
[2018-04-11 20:21:50] Started run 972 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:50] Started run 973 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:51] Error in run 966: Run already exists in server. Run id(s): {8979421}
[2018-04-11 20:21:51] Started run 974 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:52] Error in run 967: Run already exists in server. Run id(s): {8979425}
[2018-04-11 20:21:52] Started run 975 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:52] Error in run 968: Run already exists in server. Run id(s): {8979440}
[2018-04-11 20:21:52] Started run 976 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:54] Error in run 969: Run already exists in server. Run id(s): {8979468}
[2018-04-11 20:21:54] Started run 977 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:55] Error in run 970: Run already exists in server. Run id(s): {8979462}
[2018-04-11 20:21:55] Started run 978 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:55] Error in run 971: Run already exists in server. Run id(s): {8979477}
[2018-04-11 20:21:55] Started run 979 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:55] Error in run 972: Run already exists in server. Run id(s): {8979483}
[2018-04-11 20:21:55] Started run 980 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:55] Error in run 973: Run already exists in server. Run id(s): {8979498}
[2018-04-11 20:21:55] Started run 981 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:55] Error in run 974: Run already exists in server. Run id(s): {8979503}
[2018-04-11 20:21:55] Started run 982 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:56] Error in run 975: Run already exists in server. Run id(s): {8979524}
[2018-04-11 20:21:56] Started run 983 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:57] Error in run 976: Run already exists in server. Run id(s): {8979519}
[2018-04-11 20:21:57] Started run 984 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:21:59] Error in run 977: Run already exists in server. Run id(s): {8979533}
[2018-04-11 20:21:59] Started run 985 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:00] Error in run 978: Run already exists in server. Run id(s): {8979542}
[2018-04-11 20:22:00] Started run 986 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:00] Error in run 979: Run already exists in server. Run id(s): {8979559}
[2018-04-11 20:22:00] Started run 987 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:00] Error in run 980: Run already exists in server. Run id(s): {8979564}
[2018-04-11 20:22:00] Started run 988 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:00] Error in run 981: Run already exists in server. Run id(s): {8979568}
[2018-04-11 20:22:00] Started run 989 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:00] Error in run 982: Run already exists in server. Run id(s): {8979583}
[2018-04-11 20:22:00] Started run 990 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:01] Error in run 983: Run already exists in server. Run id(s): {8979593}
[2018-04-11 20:22:01] Started run 991 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:01] Error in run 984: Run already exists in server. Run id(s): {8979597}
[2018-04-11 20:22:01] Started run 992 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:03] Error in run 985: Run already exists in server. Run id(s): {8979603}
[2018-04-11 20:22:03] Started run 993 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:04] Error in run 987: Run already exists in server. Run id(s): {8979619}
[2018-04-11 20:22:04] Started run 994 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:04] Error in run 986: Run already exists in server. Run id(s): {8979608}
[2018-04-11 20:22:04] Started run 995 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:05] Error in run 989: Run already exists in server. Run id(s): {8979626}
[2018-04-11 20:22:05] Started run 996 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:05] Error in run 990: Run already exists in server. Run id(s): {8979644}
[2018-04-11 20:22:05] Started run 997 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:05] Error in run 988: Run already exists in server. Run id(s): {8979623}
[2018-04-11 20:22:05] Started run 998 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:06] Error in run 991: Run already exists in server. Run id(s): {8979663}
[2018-04-11 20:22:06] Started run 999 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:06] Error in run 992: Run already exists in server. Run id(s): {8979659}
[2018-04-11 20:22:06] Started run 1000 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 20:22:08] Error in run 993: Run already exists in server. Run id(s): {8979660}
[2018-04-11 20:22:09] Error in run 995: Run already exists in server. Run id(s): {8979692}
[2018-04-11 20:22:09] Error in run 994: Run already exists in server. Run id(s): {8979675}
[2018-04-11 20:22:09] Error in run 996: Run already exists in server. Run id(s): {8979708}
[2018-04-11 20:22:09] Error in run 998: Run already exists in server. Run id(s): {8979716}
[2018-04-11 20:22:09] Error in run 997: Run already exists in server. Run id(s): {8979697}
[2018-04-11 20:22:10] Error in run 999: Run already exists in server. Run id(s): {8979727}
[2018-04-11 20:22:11] Error in run 1000: Run already exists in server. Run id(s): {8979728}
