declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/svm2/job-1/task-00000/certs"
declare -x AZ_BATCH_JOB_ID="svm2"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/svm2/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/svm2/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_10-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/svm2/job-1/task-00000"
declare -x AZ_BATCH_TASK_ID="task-00000"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/svm2/job-1/task-00000/wd"
declare -x HOME="/mnt/batch/tasks/workitems/svm2/job-1/task-00000/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/svm2/job-1/task-00000/wd"
declare -x PWD="/mnt/batch/tasks/workitems/svm2/job-1/task-00000/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 21:40:55] Results will not be logged locally.
[2018-04-11 21:40:55] Retrieving tasks...
[2018-04-11 21:40:55] Tasks will be retrieved based on provided task ids.
[2018-04-11 21:40:55] The following tasks were retrieved: [146197].
[2018-04-11 21:41:03] Downloaded task 146197.
[2018-04-11 21:41:03] Prepared pipelines.
[2018-04-11 21:41:03] Started run 1 on task 146197, dataset 'dna'.
[2018-04-11 21:41:03] Started run 8 on task 146197, dataset 'dna'.
[2018-04-11 21:41:03] Started run 2 on task 146197, dataset 'dna'.
[2018-04-11 21:41:03] Started run 3 on task 146197, dataset 'dna'.
[2018-04-11 21:41:03] Started run 4 on task 146197, dataset 'dna'.
[2018-04-11 21:41:03] Started run 5 on task 146197, dataset 'dna'.
[2018-04-11 21:41:03] Started run 6 on task 146197, dataset 'dna'.
[2018-04-11 21:41:03] Started run 7 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Error in run 8: Run already exists in server. Run id(s): {9020157}
[2018-04-11 21:41:08] Error in run 1: Run already exists in server. Run id(s): {8941385}
[2018-04-11 21:41:08] Started run 9 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Error in run 2: Run already exists in server. Run id(s): {9020163}
[2018-04-11 21:41:08] Started run 10 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Error in run 3: Run already exists in server. Run id(s): {9020130}
[2018-04-11 21:41:08] Started run 12 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Started run 11 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Error in run 4: Run already exists in server. Run id(s): {9020166}
[2018-04-11 21:41:08] Started run 13 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Error in run 5: Run already exists in server. Run id(s): {9011234}
[2018-04-11 21:41:08] Started run 14 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Error in run 6: Run already exists in server. Run id(s): {9020159}
[2018-04-11 21:41:08] Started run 15 on task 146197, dataset 'dna'.
[2018-04-11 21:41:08] Error in run 7: Run already exists in server. Run id(s): {9011185}
[2018-04-11 21:41:08] Started run 16 on task 146197, dataset 'dna'.
[2018-04-11 21:41:12] Error in run 9: Run already exists in server. Run id(s): {9020181}
[2018-04-11 21:41:12] Error in run 10: Run already exists in server. Run id(s): {9011445}
[2018-04-11 21:41:12] Error in run 12: Run already exists in server. Run id(s): {9020177}
[2018-04-11 21:41:12] Started run 17 on task 146197, dataset 'dna'.
[2018-04-11 21:41:12] Error in run 11: Run already exists in server. Run id(s): {9020060}
[2018-04-11 21:41:12] Started run 19 on task 146197, dataset 'dna'.
[2018-04-11 21:41:12] Error in run 13: Run already exists in server. Run id(s): {9011481}
[2018-04-11 21:41:12] Started run 18 on task 146197, dataset 'dna'.
[2018-04-11 21:41:12] Started run 20 on task 146197, dataset 'dna'.
[2018-04-11 21:41:12] Error in run 14: Run already exists in server. Run id(s): {9020308}
[2018-04-11 21:41:12] Started run 21 on task 146197, dataset 'dna'.
[2018-04-11 21:41:12] Started run 22 on task 146197, dataset 'dna'.
[2018-04-11 21:41:13] Error in run 16: Run already exists in server. Run id(s): {9011687}
[2018-04-11 21:41:13] Error in run 15: Run already exists in server. Run id(s): {9012143}
[2018-04-11 21:41:13] Started run 23 on task 146197, dataset 'dna'.
[2018-04-11 21:41:13] Started run 24 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Error in run 17: Run already exists in server. Run id(s): {9020350}
[2018-04-11 21:41:17] Error in run 19: Run already exists in server. Run id(s): {9011649}
[2018-04-11 21:41:17] Started run 25 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Started run 26 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Error in run 18: Run already exists in server. Run id(s): {9011828}
[2018-04-11 21:41:17] Error in run 20: Run already exists in server. Run id(s): {9020403}
[2018-04-11 21:41:17] Started run 27 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Error in run 21: Run already exists in server. Run id(s): {9020458}
[2018-04-11 21:41:17] Started run 28 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Error in run 22: Run already exists in server. Run id(s): {9020311}
[2018-04-11 21:41:17] Started run 29 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Started run 30 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Error in run 23: Run already exists in server. Run id(s): {9012012}
[2018-04-11 21:41:17] Started run 31 on task 146197, dataset 'dna'.
[2018-04-11 21:41:17] Error in run 24: Run already exists in server. Run id(s): {9020431}
[2018-04-11 21:41:17] Started run 32 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Error in run 26: Run already exists in server. Run id(s): {9020414}
[2018-04-11 21:41:22] Error in run 25: Run already exists in server. Run id(s): {9020312}
[2018-04-11 21:41:22] Error in run 29: Run already exists in server. Run id(s): {9020557}
[2018-04-11 21:41:22] Error in run 30: Run already exists in server. Run id(s): {9012290}
[2018-04-11 21:41:22] Error in run 27: Run already exists in server. Run id(s): {9020489}
[2018-04-11 21:41:22] Error in run 28: Run already exists in server. Run id(s): {9012324}
[2018-04-11 21:41:22] Started run 33 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Started run 37 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Started run 38 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Started run 35 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Started run 34 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Started run 36 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Error in run 32: Run already exists in server. Run id(s): {9020555}
[2018-04-11 21:41:22] Started run 39 on task 146197, dataset 'dna'.
[2018-04-11 21:41:22] Error in run 31: Run already exists in server. Run id(s): {9020561}
[2018-04-11 21:41:22] Started run 40 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Error in run 35: Run already exists in server. Run id(s): {9020670}
[2018-04-11 21:41:26] Error in run 34: Run already exists in server. Run id(s): {9012393}
[2018-04-11 21:41:26] Error in run 37: Run already exists in server. Run id(s): {9012521}
[2018-04-11 21:41:26] Error in run 38: Run already exists in server. Run id(s): {9020668}
[2018-04-11 21:41:26] Error in run 36: Run already exists in server. Run id(s): {9020693}
[2018-04-11 21:41:26] Error in run 33: Run already exists in server. Run id(s): {9020514}
[2018-04-11 21:41:26] Started run 41 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Started run 42 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Started run 43 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Started run 44 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Started run 45 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Error in run 39: Run already exists in server. Run id(s): {9012476}
[2018-04-11 21:41:26] Started run 47 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Error in run 40: Run already exists in server. Run id(s): {9020727}
[2018-04-11 21:41:26] Started run 46 on task 146197, dataset 'dna'.
[2018-04-11 21:41:26] Started run 48 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Error in run 41: Run already exists in server. Run id(s): {9020770}
[2018-04-11 21:41:31] Started run 49 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Error in run 43: Run already exists in server. Run id(s): {9020674}
[2018-04-11 21:41:31] Error in run 42: Run already exists in server. Run id(s): {9020691}
[2018-04-11 21:41:31] Error in run 44: Run already exists in server. Run id(s): {9012688}
[2018-04-11 21:41:31] Error in run 45: Run already exists in server. Run id(s): {9020764}
[2018-04-11 21:41:31] Error in run 47: Run already exists in server. Run id(s): {9012701}
[2018-04-11 21:41:31] Error in run 48: Run already exists in server. Run id(s): {9020913}
[2018-04-11 21:41:31] Error in run 46: Run already exists in server. Run id(s): {9020924}
[2018-04-11 21:41:31] Started run 50 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Started run 55 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Started run 56 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Started run 51 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Started run 52 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Started run 53 on task 146197, dataset 'dna'.
[2018-04-11 21:41:31] Started run 54 on task 146197, dataset 'dna'.
[2018-04-11 21:41:35] Error in run 49: Run already exists in server. Run id(s): {9020993}
[2018-04-11 21:41:35] Started run 57 on task 146197, dataset 'dna'.
[2018-04-11 21:41:36] Error in run 56: Run already exists in server. Run id(s): {9021003}
[2018-04-11 21:41:36] Error in run 50: Run already exists in server. Run id(s): {9012841}
[2018-04-11 21:41:36] Error in run 55: Run already exists in server. Run id(s): {9020978}
[2018-04-11 21:41:36] Error in run 52: Run already exists in server. Run id(s): {9020826}
[2018-04-11 21:41:36] Error in run 51: Run already exists in server. Run id(s): {9020938}
[2018-04-11 21:41:36] Started run 58 on task 146197, dataset 'dna'.
[2018-04-11 21:41:36] Error in run 53: Run already exists in server. Run id(s): {9013146}
[2018-04-11 21:41:36] Started run 59 on task 146197, dataset 'dna'.
[2018-04-11 21:41:36] Started run 63 on task 146197, dataset 'dna'.
[2018-04-11 21:41:36] Started run 60 on task 146197, dataset 'dna'.
[2018-04-11 21:41:36] Error in run 54: Run already exists in server. Run id(s): {9013054}
[2018-04-11 21:41:36] Started run 61 on task 146197, dataset 'dna'.
[2018-04-11 21:41:36] Started run 64 on task 146197, dataset 'dna'.
[2018-04-11 21:41:36] Started run 62 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Error in run 57: Run already exists in server. Run id(s): {9013133}
[2018-04-11 21:41:40] Started run 65 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Error in run 61: Run already exists in server. Run id(s): {9013187}
[2018-04-11 21:41:40] Error in run 62: Run already exists in server. Run id(s): {9013407}
[2018-04-11 21:41:40] Error in run 58: Run already exists in server. Run id(s): {9013108}
[2018-04-11 21:41:40] Error in run 59: Run already exists in server. Run id(s): {9021061}
[2018-04-11 21:41:40] Error in run 60: Run already exists in server. Run id(s): {9021098}
[2018-04-11 21:41:40] Error in run 63: Run already exists in server. Run id(s): {9021169}
[2018-04-11 21:41:40] Started run 66 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Error in run 64: Run already exists in server. Run id(s): {9021206}
[2018-04-11 21:41:40] Started run 71 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Started run 69 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Started run 68 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Started run 67 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Started run 70 on task 146197, dataset 'dna'.
[2018-04-11 21:41:40] Started run 72 on task 146197, dataset 'dna'.
[2018-04-11 21:41:44] Error in run 65: Run already exists in server. Run id(s): {9021244}
[2018-04-11 21:41:44] Started run 73 on task 146197, dataset 'dna'.
[2018-04-11 21:41:45] Error in run 68: Run already exists in server. Run id(s): {9021227}
[2018-04-11 21:41:45] Error in run 66: Run already exists in server. Run id(s): {9021110}
[2018-04-11 21:41:45] Error in run 70: Run already exists in server. Run id(s): {9021290}
[2018-04-11 21:41:45] Started run 74 on task 146197, dataset 'dna'.
[2018-04-11 21:41:45] Error in run 67: Run already exists in server. Run id(s): {9013284}
[2018-04-11 21:41:45] Error in run 69: Run already exists in server. Run id(s): {9021204}
[2018-04-11 21:41:45] Error in run 71: Run already exists in server. Run id(s): {9021337}
[2018-04-11 21:41:45] Started run 76 on task 146197, dataset 'dna'.
[2018-04-11 21:41:45] Started run 78 on task 146197, dataset 'dna'.
[2018-04-11 21:41:45] Started run 79 on task 146197, dataset 'dna'.
[2018-04-11 21:41:45] Error in run 72: Run already exists in server. Run id(s): {9021300}
[2018-04-11 21:41:45] Started run 80 on task 146197, dataset 'dna'.
[2018-04-11 21:41:45] Started run 75 on task 146197, dataset 'dna'.
[2018-04-11 21:41:45] Started run 77 on task 146197, dataset 'dna'.
[2018-04-11 21:41:49] Error in run 73: Run already exists in server. Run id(s): {9021395}
[2018-04-11 21:41:49] Started run 81 on task 146197, dataset 'dna'.
[2018-04-11 21:41:49] Error in run 74: Run already exists in server. Run id(s): {9013672}
[2018-04-11 21:41:49] Started run 82 on task 146197, dataset 'dna'.
[2018-04-11 21:41:50] Error in run 80: Run already exists in server. Run id(s): {9021515}
[2018-04-11 21:41:50] Error in run 77: Run already exists in server. Run id(s): {9021433}
[2018-04-11 21:41:50] Error in run 75: Run already exists in server. Run id(s): {9021423}
[2018-04-11 21:41:50] Error in run 78: Run already exists in server. Run id(s): {9021465}
[2018-04-11 21:41:50] Error in run 79: Run already exists in server. Run id(s): {9021504}
[2018-04-11 21:41:50] Error in run 76: Run already exists in server. Run id(s): {9021442}
[2018-04-11 21:41:50] Started run 83 on task 146197, dataset 'dna'.
[2018-04-11 21:41:50] Started run 84 on task 146197, dataset 'dna'.
[2018-04-11 21:41:50] Started run 87 on task 146197, dataset 'dna'.
[2018-04-11 21:41:50] Started run 85 on task 146197, dataset 'dna'.
[2018-04-11 21:41:50] Started run 86 on task 146197, dataset 'dna'.
[2018-04-11 21:41:50] Started run 88 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Error in run 81: Run already exists in server. Run id(s): {9021549}
[2018-04-11 21:41:54] Started run 89 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Error in run 82: Run already exists in server. Run id(s): {9021488}
[2018-04-11 21:41:54] Started run 90 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Error in run 87: Run already exists in server. Run id(s): {9021720}
[2018-04-11 21:41:54] Error in run 85: Run already exists in server. Run id(s): {9021665}
[2018-04-11 21:41:54] Error in run 83: Run already exists in server. Run id(s): {9021641}
[2018-04-11 21:41:54] Error in run 84: Run already exists in server. Run id(s): {9021649}
[2018-04-11 21:41:54] Error in run 86: Run already exists in server. Run id(s): {9021681}
[2018-04-11 21:41:54] Started run 91 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Started run 94 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Error in run 88: Run already exists in server. Run id(s): {9021608}
[2018-04-11 21:41:54] Started run 95 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Started run 93 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Started run 92 on task 146197, dataset 'dna'.
[2018-04-11 21:41:54] Started run 96 on task 146197, dataset 'dna'.
[2018-04-11 21:41:58] Error in run 89: Run already exists in server. Run id(s): {9021736}
[2018-04-11 21:41:58] Started run 97 on task 146197, dataset 'dna'.
[2018-04-11 21:41:58] Error in run 90: Run already exists in server. Run id(s): {9021657}
[2018-04-11 21:41:58] Started run 98 on task 146197, dataset 'dna'.
[2018-04-11 21:41:59] Error in run 96: Run already exists in server. Run id(s): {9021960}
[2018-04-11 21:41:59] Error in run 93: Run already exists in server. Run id(s): {9021877}
[2018-04-11 21:41:59] Error in run 94: Run already exists in server. Run id(s): {9021891}
[2018-04-11 21:41:59] Error in run 95: Run already exists in server. Run id(s): {9021895}
[2018-04-11 21:41:59] Started run 99 on task 146197, dataset 'dna'.
[2018-04-11 21:41:59] Error in run 92: Run already exists in server. Run id(s): {9021833}
[2018-04-11 21:41:59] Error in run 91: Run already exists in server. Run id(s): {9021789}
[2018-04-11 21:41:59] Started run 103 on task 146197, dataset 'dna'.
[2018-04-11 21:41:59] Started run 104 on task 146197, dataset 'dna'.
[2018-04-11 21:41:59] Started run 100 on task 146197, dataset 'dna'.
[2018-04-11 21:41:59] Started run 101 on task 146197, dataset 'dna'.
[2018-04-11 21:41:59] Started run 102 on task 146197, dataset 'dna'.
[2018-04-11 21:42:03] Error in run 97: Run already exists in server. Run id(s): {9021914}
[2018-04-11 21:42:03] Error in run 98: Run already exists in server. Run id(s): {9021885}
[2018-04-11 21:42:03] Started run 105 on task 146197, dataset 'dna'.
[2018-04-11 21:42:03] Started run 106 on task 146197, dataset 'dna'.
[2018-04-11 21:42:04] Error in run 100: Run already exists in server. Run id(s): {9022091}
[2018-04-11 21:42:04] Error in run 101: Run already exists in server. Run id(s): {9022072}
[2018-04-11 21:42:04] Error in run 99: Run already exists in server. Run id(s): {9022020}
[2018-04-11 21:42:04] Error in run 103: Run already exists in server. Run id(s): {9022054}
[2018-04-11 21:42:04] Started run 107 on task 146197, dataset 'dna'.
[2018-04-11 21:42:04] Error in run 104: Run already exists in server. Run id(s): {9022048}
[2018-04-11 21:42:04] Started run 108 on task 146197, dataset 'dna'.
[2018-04-11 21:42:04] Started run 109 on task 146197, dataset 'dna'.
[2018-04-11 21:42:04] Error in run 102: Run already exists in server. Run id(s): {9022008}
[2018-04-11 21:42:04] Started run 112 on task 146197, dataset 'dna'.
[2018-04-11 21:42:04] Started run 110 on task 146197, dataset 'dna'.
[2018-04-11 21:42:04] Started run 111 on task 146197, dataset 'dna'.
[2018-04-11 21:42:07] Error in run 105: Run already exists in server. Run id(s): {9022093}
[2018-04-11 21:42:08] Error in run 106: Run already exists in server. Run id(s): {9022209}
[2018-04-11 21:42:07] Started run 113 on task 146197, dataset 'dna'.
[2018-04-11 21:42:08] Started run 114 on task 146197, dataset 'dna'.
[2018-04-11 21:42:08] Error in run 109: Run already exists in server. Run id(s): {9022287}
[2018-04-11 21:42:08] Started run 115 on task 146197, dataset 'dna'.
[2018-04-11 21:42:08] Error in run 110: Run already exists in server. Run id(s): {9022387}
[2018-04-11 21:42:08] Error in run 107: Run already exists in server. Run id(s): {9022118}
[2018-04-11 21:42:08] Error in run 108: Run already exists in server. Run id(s): {9022230}
[2018-04-11 21:42:08] Error in run 111: Run already exists in server. Run id(s): {9022257}
[2018-04-11 21:42:08] Error in run 112: Run already exists in server. Run id(s): {9022298}
[2018-04-11 21:42:08] Started run 116 on task 146197, dataset 'dna'.
[2018-04-11 21:42:08] Started run 117 on task 146197, dataset 'dna'.
[2018-04-11 21:42:08] Started run 118 on task 146197, dataset 'dna'.
[2018-04-11 21:42:08] Started run 119 on task 146197, dataset 'dna'.
[2018-04-11 21:42:08] Started run 120 on task 146197, dataset 'dna'.
[2018-04-11 21:42:12] Error in run 114: Run already exists in server. Run id(s): {9022358}
[2018-04-11 21:42:12] Started run 121 on task 146197, dataset 'dna'.
[2018-04-11 21:42:12] Error in run 113: Run already exists in server. Run id(s): {9022188}
[2018-04-11 21:42:12] Started run 122 on task 146197, dataset 'dna'.
[2018-04-11 21:42:13] Error in run 115: Run already exists in server. Run id(s): {9022427}
[2018-04-11 21:42:13] Started run 123 on task 146197, dataset 'dna'.
[2018-04-11 21:42:13] Error in run 116: Run already exists in server. Run id(s): {9022318}
[2018-04-11 21:42:13] Error in run 119: Run already exists in server. Run id(s): {9022394}
[2018-04-11 21:42:13] Started run 124 on task 146197, dataset 'dna'.
[2018-04-11 21:42:13] Started run 125 on task 146197, dataset 'dna'.
[2018-04-11 21:42:13] Error in run 117: Run already exists in server. Run id(s): {9022381}
[2018-04-11 21:42:13] Started run 126 on task 146197, dataset 'dna'.
[2018-04-11 21:42:13] Error in run 118: Run already exists in server. Run id(s): {9022580}
[2018-04-11 21:42:13] Started run 127 on task 146197, dataset 'dna'.
[2018-04-11 21:42:13] Error in run 120: Run already exists in server. Run id(s): {9022447}
[2018-04-11 21:42:13] Started run 128 on task 146197, dataset 'dna'.
[2018-04-11 21:42:17] Error in run 121: Run already exists in server. Run id(s): {9022576}
[2018-04-11 21:42:17] Started run 129 on task 146197, dataset 'dna'.
[2018-04-11 21:42:17] Error in run 122: Run already exists in server. Run id(s): {9022672}
[2018-04-11 21:42:17] Started run 130 on task 146197, dataset 'dna'.
[2018-04-11 21:42:17] Error in run 123: Run already exists in server. Run id(s): {9022597}
[2018-04-11 21:42:17] Started run 131 on task 146197, dataset 'dna'.
[2018-04-11 21:42:17] Error in run 124: Run already exists in server. Run id(s): {9022632}
[2018-04-11 21:42:17] Started run 132 on task 146197, dataset 'dna'.
[2018-04-11 21:42:18] Error in run 127: Run already exists in server. Run id(s): {9022690}
[2018-04-11 21:42:18] Error in run 125: Run already exists in server. Run id(s): {9022592}
[2018-04-11 21:42:18] Error in run 126: Run already exists in server. Run id(s): {9022660}
[2018-04-11 21:42:18] Error in run 128: Run already exists in server. Run id(s): {9022802}
[2018-04-11 21:42:18] Started run 133 on task 146197, dataset 'dna'.
[2018-04-11 21:42:18] Started run 134 on task 146197, dataset 'dna'.
[2018-04-11 21:42:18] Started run 135 on task 146197, dataset 'dna'.
[2018-04-11 21:42:18] Started run 136 on task 146197, dataset 'dna'.
[2018-04-11 21:42:21] Error in run 129: Run already exists in server. Run id(s): {9022828}
[2018-04-11 21:42:21] Started run 137 on task 146197, dataset 'dna'.
[2018-04-11 21:42:22] Error in run 130: Run already exists in server. Run id(s): {9022905}
[2018-04-11 21:42:22] Started run 138 on task 146197, dataset 'dna'.
[2018-04-11 21:42:22] Error in run 131: Run already exists in server. Run id(s): {9022842}
[2018-04-11 21:42:22] Started run 139 on task 146197, dataset 'dna'.
[2018-04-11 21:42:22] Error in run 132: Run already exists in server. Run id(s): {9022869}
[2018-04-11 21:42:22] Started run 140 on task 146197, dataset 'dna'.
[2018-04-11 21:42:22] Error in run 136: Run already exists in server. Run id(s): {9023040}
[2018-04-11 21:42:22] Error in run 134: Run already exists in server. Run id(s): {9022873}
[2018-04-11 21:42:22] Error in run 135: Run already exists in server. Run id(s): {9022888}
[2018-04-11 21:42:22] Error in run 133: Run already exists in server. Run id(s): {9022788}
[2018-04-11 21:42:22] Started run 141 on task 146197, dataset 'dna'.
[2018-04-11 21:42:22] Started run 142 on task 146197, dataset 'dna'.
[2018-04-11 21:42:22] Started run 143 on task 146197, dataset 'dna'.
[2018-04-11 21:42:22] Started run 144 on task 146197, dataset 'dna'.
[2018-04-11 21:42:26] Error in run 137: Run already exists in server. Run id(s): {9022904}
[2018-04-11 21:42:26] Started run 145 on task 146197, dataset 'dna'.
[2018-04-11 21:42:26] Error in run 138: Run already exists in server. Run id(s): {9023077}
[2018-04-11 21:42:26] Error in run 139: Run already exists in server. Run id(s): {9023044}
[2018-04-11 21:42:26] Started run 146 on task 146197, dataset 'dna'.
[2018-04-11 21:42:26] Started run 147 on task 146197, dataset 'dna'.
[2018-04-11 21:42:27] Error in run 140: Run already exists in server. Run id(s): {9023115}
[2018-04-11 21:42:27] Started run 148 on task 146197, dataset 'dna'.
[2018-04-11 21:42:27] Error in run 141: Run already exists in server. Run id(s): {9023018}
[2018-04-11 21:42:27] Error in run 144: Run already exists in server. Run id(s): {9023188}
[2018-04-11 21:42:27] Error in run 142: Run already exists in server. Run id(s): {9023109}
[2018-04-11 21:42:27] Error in run 143: Run already exists in server. Run id(s): {9023128}
[2018-04-11 21:42:27] Started run 149 on task 146197, dataset 'dna'.
[2018-04-11 21:42:27] Started run 151 on task 146197, dataset 'dna'.
[2018-04-11 21:42:27] Started run 152 on task 146197, dataset 'dna'.
[2018-04-11 21:42:27] Started run 150 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Error in run 145: Run already exists in server. Run id(s): {9023255}
[2018-04-11 21:42:30] Started run 153 on task 146197, dataset 'dna'.
[2018-04-11 21:42:31] Error in run 146: Run already exists in server. Run id(s): {9023300}
[2018-04-11 21:42:31] Started run 154 on task 146197, dataset 'dna'.
[2018-04-11 21:42:31] Error in run 148: Run already exists in server. Run id(s): {9023318}
[2018-04-11 21:42:31] Error in run 147: Run already exists in server. Run id(s): {9023149}
[2018-04-11 21:42:31] Started run 155 on task 146197, dataset 'dna'.
[2018-04-11 21:42:31] Started run 156 on task 146197, dataset 'dna'.
[2018-04-11 21:42:32] Error in run 149: Run already exists in server. Run id(s): {9023224}
[2018-04-11 21:42:32] Started run 157 on task 146197, dataset 'dna'.
[2018-04-11 21:42:32] Error in run 152: Run already exists in server. Run id(s): {9023277}
[2018-04-11 21:42:32] Error in run 150: Run already exists in server. Run id(s): {9023353}
[2018-04-11 21:42:32] Error in run 151: Run already exists in server. Run id(s): {9023302}
[2018-04-11 21:42:32] Started run 158 on task 146197, dataset 'dna'.
[2018-04-11 21:42:32] Started run 160 on task 146197, dataset 'dna'.
[2018-04-11 21:42:32] Started run 159 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Error in run 153: Run already exists in server. Run id(s): {9023423}
[2018-04-11 21:42:35] Started run 161 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Error in run 154: Run already exists in server. Run id(s): {9023459}
[2018-04-11 21:42:35] Started run 162 on task 146197, dataset 'dna'.
[2018-04-11 21:42:36] Error in run 156: Run already exists in server. Run id(s): {9023518}
[2018-04-11 21:42:36] Error in run 155: Run already exists in server. Run id(s): {9023356}
[2018-04-11 21:42:36] Started run 163 on task 146197, dataset 'dna'.
[2018-04-11 21:42:36] Started run 164 on task 146197, dataset 'dna'.
[2018-04-11 21:42:36] Error in run 157: Run already exists in server. Run id(s): {9023543}
[2018-04-11 21:42:36] Started run 165 on task 146197, dataset 'dna'.
[2018-04-11 21:42:36] Error in run 158: Run already exists in server. Run id(s): {9023544}
[2018-04-11 21:42:36] Started run 166 on task 146197, dataset 'dna'.
[2018-04-11 21:42:37] Error in run 159: Run already exists in server. Run id(s): {9023494}
[2018-04-11 21:42:37] Error in run 160: Run already exists in server. Run id(s): {9023585}
[2018-04-11 21:42:37] Started run 167 on task 146197, dataset 'dna'.
[2018-04-11 21:42:37] Started run 168 on task 146197, dataset 'dna'.
[2018-04-11 21:42:40] Error in run 161: Run already exists in server. Run id(s): {9023452}
[2018-04-11 21:42:40] Started run 169 on task 146197, dataset 'dna'.
[2018-04-11 21:42:40] Error in run 162: Run already exists in server. Run id(s): {9023559}
[2018-04-11 21:42:40] Started run 170 on task 146197, dataset 'dna'.
[2018-04-11 21:42:40] Error in run 164: Run already exists in server. Run id(s): {9023721}
[2018-04-11 21:42:40] Error in run 163: Run already exists in server. Run id(s): {9023686}
[2018-04-11 21:42:40] Started run 171 on task 146197, dataset 'dna'.
[2018-04-11 21:42:40] Started run 172 on task 146197, dataset 'dna'.
[2018-04-11 21:42:41] Error in run 165: Run already exists in server. Run id(s): {9023728}
[2018-04-11 21:42:41] Started run 173 on task 146197, dataset 'dna'.
[2018-04-11 21:42:41] Error in run 166: Run already exists in server. Run id(s): {9023756}
[2018-04-11 21:42:41] Started run 174 on task 146197, dataset 'dna'.
[2018-04-11 21:42:41] Error in run 168: Run already exists in server. Run id(s): {9023778}
[2018-04-11 21:42:41] Started run 175 on task 146197, dataset 'dna'.
[2018-04-11 21:42:41] Error in run 167: Run already exists in server. Run id(s): {9023719}
[2018-04-11 21:42:41] Started run 176 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Error in run 169: Run already exists in server. Run id(s): {9023699}
[2018-04-11 21:42:44] Started run 177 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Error in run 170: Run already exists in server. Run id(s): {9023819}
[2018-04-11 21:42:44] Started run 178 on task 146197, dataset 'dna'.
[2018-04-11 21:42:45] Error in run 171: Run already exists in server. Run id(s): {9023929}
[2018-04-11 21:42:45] Started run 179 on task 146197, dataset 'dna'.
[2018-04-11 21:42:45] Error in run 172: Run already exists in server. Run id(s): {9023939}
[2018-04-11 21:42:45] Started run 180 on task 146197, dataset 'dna'.
[2018-04-11 21:42:45] Error in run 173: Run already exists in server. Run id(s): {9023961}
[2018-04-11 21:42:45] Started run 181 on task 146197, dataset 'dna'.
[2018-04-11 21:42:45] Error in run 174: Run already exists in server. Run id(s): {9023958}
[2018-04-11 21:42:45] Started run 182 on task 146197, dataset 'dna'.
[2018-04-11 21:42:46] Error in run 175: Run already exists in server. Run id(s): {9023968, 9024040}
[2018-04-11 21:42:46] Started run 183 on task 146197, dataset 'dna'.
[2018-04-11 21:42:46] Error in run 176: Run already exists in server. Run id(s): {9023949}
[2018-04-11 21:42:46] Started run 184 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Error in run 177: Run already exists in server. Run id(s): {9024021}
[2018-04-11 21:42:49] Error in run 178: Run already exists in server. Run id(s): {9024144}
[2018-04-11 21:42:49] Started run 185 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Started run 186 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Error in run 179: Run already exists in server. Run id(s): {9024181}
[2018-04-11 21:42:49] Started run 187 on task 146197, dataset 'dna'.
[2018-04-11 21:42:50] Error in run 181: Run already exists in server. Run id(s): {9024139}
[2018-04-11 21:42:50] Error in run 180: Run already exists in server. Run id(s): {9024185}
[2018-04-11 21:42:50] Started run 188 on task 146197, dataset 'dna'.
[2018-04-11 21:42:50] Started run 189 on task 146197, dataset 'dna'.
[2018-04-11 21:42:50] Error in run 182: Run already exists in server. Run id(s): {9024202}
[2018-04-11 21:42:50] Started run 190 on task 146197, dataset 'dna'.
[2018-04-11 21:42:50] Error in run 183: Run already exists in server. Run id(s): {9024209}
[2018-04-11 21:42:50] Started run 191 on task 146197, dataset 'dna'.
[2018-04-11 21:42:51] Error in run 184: Run already exists in server. Run id(s): {9024227}
[2018-04-11 21:42:51] Started run 192 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Error in run 186: Run already exists in server. Run id(s): {9024392}
[2018-04-11 21:42:54] Error in run 185: Run already exists in server. Run id(s): {9024297}
[2018-04-11 21:42:54] Started run 193 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Started run 194 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Error in run 187: Run already exists in server. Run id(s): {9024403}
[2018-04-11 21:42:54] Started run 195 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Error in run 190: Run already exists in server. Run id(s): {9024453}
[2018-04-11 21:42:54] Error in run 189: Run already exists in server. Run id(s): {9024385}
[2018-04-11 21:42:54] Started run 196 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Error in run 188: Run already exists in server. Run id(s): {9024436}
[2018-04-11 21:42:54] Started run 198 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Started run 197 on task 146197, dataset 'dna'.
[2018-04-11 21:42:55] Error in run 191: Run already exists in server. Run id(s): {9024455}
[2018-04-11 21:42:55] Started run 199 on task 146197, dataset 'dna'.
[2018-04-11 21:42:55] Error in run 192: Run already exists in server. Run id(s): {9024496}
[2018-04-11 21:42:55] Started run 200 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Error in run 193: Run already exists in server. Run id(s): {9024573}
[2018-04-11 21:42:58] Started run 201 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Error in run 195: Run already exists in server. Run id(s): {9024658}
[2018-04-11 21:42:58] Error in run 194: Run already exists in server. Run id(s): {9024669}
[2018-04-11 21:42:58] Started run 202 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Started run 203 on task 146197, dataset 'dna'.
[2018-04-11 21:42:59] Error in run 197: Run already exists in server. Run id(s): {9024698, 9024686}
[2018-04-11 21:42:59] Error in run 196: Run already exists in server. Run id(s): {9024690}
[2018-04-11 21:42:59] Error in run 199: Run already exists in server. Run id(s): {9024662}
[2018-04-11 21:42:59] Error in run 198: Run already exists in server. Run id(s): {9024680}
[2018-04-11 21:42:59] Started run 204 on task 146197, dataset 'dna'.
[2018-04-11 21:42:59] Started run 205 on task 146197, dataset 'dna'.
[2018-04-11 21:42:59] Started run 207 on task 146197, dataset 'dna'.
[2018-04-11 21:42:59] Started run 206 on task 146197, dataset 'dna'.
[2018-04-11 21:43:00] Error in run 200: Run already exists in server. Run id(s): {9024753}
[2018-04-11 21:43:00] Started run 208 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Error in run 201: Run already exists in server. Run id(s): {9024811}
[2018-04-11 21:43:03] Started run 209 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Error in run 203: Run already exists in server. Run id(s): {9024858}
[2018-04-11 21:43:03] Error in run 202: Run already exists in server. Run id(s): {9024926}
[2018-04-11 21:43:03] Started run 210 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Started run 211 on task 146197, dataset 'dna'.
[2018-04-11 21:43:04] Error in run 207: Run already exists in server. Run id(s): {9024974}
[2018-04-11 21:43:04] Error in run 204: Run already exists in server. Run id(s): {9024875}
[2018-04-11 21:43:04] Error in run 206: Run already exists in server. Run id(s): {9024799}
[2018-04-11 21:43:04] Error in run 205: Run already exists in server. Run id(s): {9024898}
[2018-04-11 21:43:04] Started run 212 on task 146197, dataset 'dna'.
[2018-04-11 21:43:04] Started run 213 on task 146197, dataset 'dna'.
[2018-04-11 21:43:04] Started run 215 on task 146197, dataset 'dna'.
[2018-04-11 21:43:04] Started run 214 on task 146197, dataset 'dna'.
[2018-04-11 21:43:04] Error in run 208: Run already exists in server. Run id(s): {9025233}
[2018-04-11 21:43:04] Started run 216 on task 146197, dataset 'dna'.
[2018-04-11 21:43:07] Error in run 209: Run already exists in server. Run id(s): {9025038}
[2018-04-11 21:43:07] Started run 217 on task 146197, dataset 'dna'.
[2018-04-11 21:43:08] Error in run 211: Run already exists in server. Run id(s): {9025103}
[2018-04-11 21:43:08] Error in run 210: Run already exists in server. Run id(s): {9025068}
[2018-04-11 21:43:08] Started run 218 on task 146197, dataset 'dna'.
[2018-04-11 21:43:08] Started run 219 on task 146197, dataset 'dna'.
[2018-04-11 21:43:09] Error in run 215: Run already exists in server. Run id(s): {9025226}
[2018-04-11 21:43:09] Error in run 214: Run already exists in server. Run id(s): {9025031}
[2018-04-11 21:43:09] Error in run 212: Run already exists in server. Run id(s): {9025018}
[2018-04-11 21:43:09] Error in run 213: Run already exists in server. Run id(s): {9025150}
[2018-04-11 21:43:09] Started run 220 on task 146197, dataset 'dna'.
[2018-04-11 21:43:09] Started run 221 on task 146197, dataset 'dna'.
[2018-04-11 21:43:09] Started run 222 on task 146197, dataset 'dna'.
[2018-04-11 21:43:09] Error in run 216: Run already exists in server. Run id(s): {9025292}
[2018-04-11 21:43:09] Started run 224 on task 146197, dataset 'dna'.
[2018-04-11 21:43:09] Started run 223 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Error in run 217: Run already exists in server. Run id(s): {9025194}
[2018-04-11 21:43:12] Started run 225 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Error in run 218: Run already exists in server. Run id(s): {9025296}
[2018-04-11 21:43:12] Error in run 219: Run already exists in server. Run id(s): {9025328}
[2018-04-11 21:43:12] Started run 226 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Started run 227 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Error in run 222: Run already exists in server. Run id(s): {9025315}
[2018-04-11 21:43:13] Error in run 224: Run already exists in server. Run id(s): {9025412}
[2018-04-11 21:43:13] Error in run 221: Run already exists in server. Run id(s): {9025348}
[2018-04-11 21:43:13] Error in run 220: Run already exists in server. Run id(s): {9025363}
[2018-04-11 21:43:13] Error in run 223: Run already exists in server. Run id(s): {9025483}
[2018-04-11 21:43:13] Started run 228 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Started run 230 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Started run 231 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Started run 229 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Started run 232 on task 146197, dataset 'dna'.
[2018-04-11 21:43:16] Error in run 225: Run already exists in server. Run id(s): {9025542}
[2018-04-11 21:43:16] Started run 233 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Error in run 227: Run already exists in server. Run id(s): {9025518}
[2018-04-11 21:43:17] Error in run 226: Run already exists in server. Run id(s): {9025572}
[2018-04-11 21:43:17] Started run 234 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Started run 235 on task 146197, dataset 'dna'.
[2018-04-11 21:43:18] Error in run 228: Run already exists in server. Run id(s): {9025576}
[2018-04-11 21:43:18] Error in run 231: Run already exists in server. Run id(s): {9025698}
[2018-04-11 21:43:18] Started run 236 on task 146197, dataset 'dna'.
[2018-04-11 21:43:18] Started run 237 on task 146197, dataset 'dna'.
[2018-04-11 21:43:18] Error in run 232: Run already exists in server. Run id(s): {9025730}
[2018-04-11 21:43:18] Error in run 230: Run already exists in server. Run id(s): {9025683}
[2018-04-11 21:43:18] Error in run 229: Run already exists in server. Run id(s): {9025711}
[2018-04-11 21:43:18] Started run 238 on task 146197, dataset 'dna'.
[2018-04-11 21:43:18] Started run 239 on task 146197, dataset 'dna'.
[2018-04-11 21:43:18] Started run 240 on task 146197, dataset 'dna'.
[2018-04-11 21:43:21] Error in run 233: Run already exists in server. Run id(s): {9025776}
[2018-04-11 21:43:21] Started run 241 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Error in run 234: Run already exists in server. Run id(s): {9025804}
[2018-04-11 21:43:22] Started run 242 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Error in run 235: Run already exists in server. Run id(s): {9025820}
[2018-04-11 21:43:22] Started run 243 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Error in run 237: Run already exists in server. Run id(s): {9025938}
[2018-04-11 21:43:22] Error in run 236: Run already exists in server. Run id(s): {9025775}
[2018-04-11 21:43:22] Started run 244 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Started run 245 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Error in run 238: Run already exists in server. Run id(s): {9025869}
[2018-04-11 21:43:22] Started run 246 on task 146197, dataset 'dna'.
[2018-04-11 21:43:23] Error in run 240: Run already exists in server. Run id(s): {9026045}
[2018-04-11 21:43:23] Error in run 239: Run already exists in server. Run id(s): {9025903}
[2018-04-11 21:43:23] Started run 247 on task 146197, dataset 'dna'.
[2018-04-11 21:43:23] Started run 248 on task 146197, dataset 'dna'.
[2018-04-11 21:43:25] Error in run 241: Run already exists in server. Run id(s): {9026021}
[2018-04-11 21:43:25] Started run 249 on task 146197, dataset 'dna'.
[2018-04-11 21:43:26] Error in run 242: Run already exists in server. Run id(s): {9026027}
[2018-04-11 21:43:26] Started run 250 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Error in run 243: Run already exists in server. Run id(s): {9026053}
[2018-04-11 21:43:27] Started run 251 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Error in run 244: Run already exists in server. Run id(s): {9026058}
[2018-04-11 21:43:27] Started run 252 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Error in run 245: Run already exists in server. Run id(s): {9026001}
[2018-04-11 21:43:27] Started run 253 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Error in run 246: Run already exists in server. Run id(s): {9026165}
[2018-04-11 21:43:27] Started run 254 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Error in run 247: Run already exists in server. Run id(s): {9026084}
[2018-04-11 21:43:27] Error in run 248: Run already exists in server. Run id(s): {9026209}
[2018-04-11 21:43:27] Started run 255 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Started run 256 on task 146197, dataset 'dna'.
[2018-04-11 21:43:30] Error in run 249: Run already exists in server. Run id(s): {9026339}
[2018-04-11 21:43:30] Started run 257 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Error in run 250: Run already exists in server. Run id(s): {9026275}
[2018-04-11 21:43:31] Started run 258 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Error in run 251: Run already exists in server. Run id(s): {9026248}
[2018-04-11 21:43:31] Started run 259 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Error in run 252: Run already exists in server. Run id(s): {9026172}
[2018-04-11 21:43:31] Started run 260 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Error in run 253: Run already exists in server. Run id(s): {9026300}
[2018-04-11 21:43:31] Error in run 254: Run already exists in server. Run id(s): {9026188}
[2018-04-11 21:43:31] Started run 261 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Started run 262 on task 146197, dataset 'dna'.
[2018-04-11 21:43:32] Error in run 255: Run already exists in server. Run id(s): {9026343}
[2018-04-11 21:43:32] Error in run 256: Run already exists in server. Run id(s): {9026424}
[2018-04-11 21:43:32] Started run 263 on task 146197, dataset 'dna'.
[2018-04-11 21:43:32] Started run 264 on task 146197, dataset 'dna'.
[2018-04-11 21:43:34] Error in run 257: Run already exists in server. Run id(s): {9026433}
[2018-04-11 21:43:34] Started run 265 on task 146197, dataset 'dna'.
[2018-04-11 21:43:35] Error in run 258: Run already exists in server. Run id(s): {9026403}
[2018-04-11 21:43:35] Started run 266 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Error in run 259: Run already exists in server. Run id(s): {9026492}
[2018-04-11 21:43:36] Error in run 261: Run already exists in server. Run id(s): {9026568}
[2018-04-11 21:43:36] Started run 267 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 268 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Error in run 262: Run already exists in server. Run id(s): {9026596}
[2018-04-11 21:43:36] Error in run 260: Run already exists in server. Run id(s): {9026521}
[2018-04-11 21:43:36] Started run 269 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 270 on task 146197, dataset 'dna'.
[2018-04-11 21:43:37] Error in run 264: Run already exists in server. Run id(s): {9026604}
[2018-04-11 21:43:37] Error in run 263: Run already exists in server. Run id(s): {9026588}
[2018-04-11 21:43:37] Started run 271 on task 146197, dataset 'dna'.
[2018-04-11 21:43:37] Started run 272 on task 146197, dataset 'dna'.
[2018-04-11 21:43:39] Error in run 265: Run already exists in server. Run id(s): {9026567}
[2018-04-11 21:43:39] Started run 273 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Error in run 266: Run already exists in server. Run id(s): {9026541}
[2018-04-11 21:43:40] Started run 274 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Error in run 268: Run already exists in server. Run id(s): {9026729}
[2018-04-11 21:43:40] Error in run 267: Run already exists in server. Run id(s): {9026691}
[2018-04-11 21:43:40] Started run 275 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Started run 276 on task 146197, dataset 'dna'.
[2018-04-11 21:43:41] Error in run 270: Run already exists in server. Run id(s): {9026748}
[2018-04-11 21:43:41] Error in run 269: Run already exists in server. Run id(s): {9026801}
[2018-04-11 21:43:41] Started run 277 on task 146197, dataset 'dna'.
[2018-04-11 21:43:41] Started run 278 on task 146197, dataset 'dna'.
[2018-04-11 21:43:41] Error in run 271: Run already exists in server. Run id(s): {9026791}
[2018-04-11 21:43:41] Started run 279 on task 146197, dataset 'dna'.
[2018-04-11 21:43:41] Error in run 272: Run already exists in server. Run id(s): {9026876}
[2018-04-11 21:43:41] Started run 280 on task 146197, dataset 'dna'.
[2018-04-11 21:43:44] Error in run 273: Run already exists in server. Run id(s): {9026827}
[2018-04-11 21:43:44] Started run 281 on task 146197, dataset 'dna'.
[2018-04-11 21:43:44] Error in run 274: Run already exists in server. Run id(s): {9026846}
[2018-04-11 21:43:44] Started run 282 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Error in run 276: Run already exists in server. Run id(s): {9026978}
[2018-04-11 21:43:45] Error in run 275: Run already exists in server. Run id(s): {9027018}
[2018-04-11 21:43:45] Started run 283 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Started run 284 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Error in run 277: Run already exists in server. Run id(s): {9026932}
[2018-04-11 21:43:45] Started run 285 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Error in run 278: Run already exists in server. Run id(s): {9026931}
[2018-04-11 21:43:45] Started run 286 on task 146197, dataset 'dna'.
[2018-04-11 21:43:46] Error in run 279: Run already exists in server. Run id(s): {9027047}
[2018-04-11 21:43:46] Started run 287 on task 146197, dataset 'dna'.
[2018-04-11 21:43:46] Error in run 280: Run already exists in server. Run id(s): {9026924}
[2018-04-11 21:43:46] Started run 288 on task 146197, dataset 'dna'.
[2018-04-11 21:43:48] Error in run 281: Run already exists in server. Run id(s): {9027081}
[2018-04-11 21:43:48] Started run 289 on task 146197, dataset 'dna'.
[2018-04-11 21:43:49] Error in run 282: Run already exists in server. Run id(s): {9027115}
[2018-04-11 21:43:49] Started run 290 on task 146197, dataset 'dna'.
[2018-04-11 21:43:49] Error in run 283: Run already exists in server. Run id(s): {9027015}
[2018-04-11 21:43:49] Error in run 284: Run already exists in server. Run id(s): {9027166}
[2018-04-11 21:43:49] Started run 291 on task 146197, dataset 'dna'.
[2018-04-11 21:43:49] Started run 292 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Error in run 285: Run already exists in server. Run id(s): {9027172}
[2018-04-11 21:43:50] Started run 293 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Error in run 286: Run already exists in server. Run id(s): {9027236}
[2018-04-11 21:43:50] Started run 294 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Error in run 287: Run already exists in server. Run id(s): {9027248}
[2018-04-11 21:43:50] Started run 295 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Error in run 288: Run already exists in server. Run id(s): {9027251}
[2018-04-11 21:43:50] Started run 296 on task 146197, dataset 'dna'.
[2018-04-11 21:43:53] Error in run 289: Run already exists in server. Run id(s): {9027296}
[2018-04-11 21:43:53] Started run 297 on task 146197, dataset 'dna'.
[2018-04-11 21:43:54] Error in run 290: Run already exists in server. Run id(s): {9027332}
[2018-04-11 21:43:54] Started run 298 on task 146197, dataset 'dna'.
[2018-04-11 21:43:54] Error in run 291: Run already exists in server. Run id(s): {9027320}
[2018-04-11 21:43:54] Error in run 292: Run already exists in server. Run id(s): {9027487}
[2018-04-11 21:43:54] Started run 299 on task 146197, dataset 'dna'.
[2018-04-11 21:43:54] Started run 300 on task 146197, dataset 'dna'.
[2018-04-11 21:43:54] Error in run 293: Run already exists in server. Run id(s): {9027425}
[2018-04-11 21:43:54] Started run 301 on task 146197, dataset 'dna'.
[2018-04-11 21:43:54] Error in run 294: Run already exists in server. Run id(s): {9027354}
[2018-04-11 21:43:54] Started run 302 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Error in run 295: Run already exists in server. Run id(s): {9027495}
[2018-04-11 21:43:55] Started run 303 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Error in run 296: Run already exists in server. Run id(s): {9027504}
[2018-04-11 21:43:55] Started run 304 on task 146197, dataset 'dna'.
[2018-04-11 21:43:57] Error in run 297: Run already exists in server. Run id(s): {9027547}
[2018-04-11 21:43:57] Started run 305 on task 146197, dataset 'dna'.
[2018-04-11 21:43:58] Error in run 298: Run already exists in server. Run id(s): {9027576}
[2018-04-11 21:43:58] Started run 306 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Error in run 299: Run already exists in server. Run id(s): {9027477}
[2018-04-11 21:43:59] Error in run 301: Run already exists in server. Run id(s): {9027574}
[2018-04-11 21:43:59] Error in run 300: Run already exists in server. Run id(s): {9027631}
[2018-04-11 21:43:59] Started run 307 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Started run 309 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Started run 308 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Error in run 302: Run already exists in server. Run id(s): {9027605}
[2018-04-11 21:43:59] Started run 310 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Error in run 303: Run already exists in server. Run id(s): {9027690}
[2018-04-11 21:43:59] Started run 311 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Error in run 304: Run already exists in server. Run id(s): {9027747}
[2018-04-11 21:43:59] Started run 312 on task 146197, dataset 'dna'.
[2018-04-11 21:44:02] Error in run 305: Run already exists in server. Run id(s): {9027703}
[2018-04-11 21:44:02] Started run 313 on task 146197, dataset 'dna'.
[2018-04-11 21:44:02] Error in run 306: Run already exists in server. Run id(s): {9027705}
[2018-04-11 21:44:02] Started run 314 on task 146197, dataset 'dna'.
[2018-04-11 21:44:03] Error in run 307: Run already exists in server. Run id(s): {9027757}
[2018-04-11 21:44:03] Error in run 309: Run already exists in server. Run id(s): {9027852}
[2018-04-11 21:44:03] Error in run 310: Run already exists in server. Run id(s): {9027798}
[2018-04-11 21:44:03] Error in run 308: Run already exists in server. Run id(s): {9027821}
[2018-04-11 21:44:03] Started run 315 on task 146197, dataset 'dna'.
[2018-04-11 21:44:03] Started run 318 on task 146197, dataset 'dna'.
[2018-04-11 21:44:03] Started run 316 on task 146197, dataset 'dna'.
[2018-04-11 21:44:03] Started run 317 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Error in run 312: Run already exists in server. Run id(s): {9027904}
[2018-04-11 21:44:04] Error in run 311: Run already exists in server. Run id(s): {9027982}
[2018-04-11 21:44:04] Started run 319 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Started run 320 on task 146197, dataset 'dna'.
[2018-04-11 21:44:06] Error in run 313: Run already exists in server. Run id(s): {9027950}
[2018-04-11 21:44:06] Started run 321 on task 146197, dataset 'dna'.
[2018-04-11 21:44:07] Error in run 314: Run already exists in server. Run id(s): {9027999}
[2018-04-11 21:44:07] Started run 322 on task 146197, dataset 'dna'.
[2018-04-11 21:44:08] Error in run 318: Run already exists in server. Run id(s): {9028105}
[2018-04-11 21:44:08] Error in run 315: Run already exists in server. Run id(s): {9028005}
[2018-04-11 21:44:08] Error in run 317: Run already exists in server. Run id(s): {9028064}
[2018-04-11 21:44:08] Started run 323 on task 146197, dataset 'dna'.
[2018-04-11 21:44:08] Error in run 316: Run already exists in server. Run id(s): {9027986}
[2018-04-11 21:44:08] Started run 324 on task 146197, dataset 'dna'.
[2018-04-11 21:44:08] Started run 325 on task 146197, dataset 'dna'.
[2018-04-11 21:44:08] Started run 326 on task 146197, dataset 'dna'.
[2018-04-11 21:44:09] Error in run 319: Run already exists in server. Run id(s): {9028149}
[2018-04-11 21:44:09] Error in run 320: Run already exists in server. Run id(s): {9028054}
[2018-04-11 21:44:09] Started run 327 on task 146197, dataset 'dna'.
[2018-04-11 21:44:09] Started run 328 on task 146197, dataset 'dna'.
[2018-04-11 21:44:11] Error in run 321: Run already exists in server. Run id(s): {9028225}
[2018-04-11 21:44:11] Started run 329 on task 146197, dataset 'dna'.
[2018-04-11 21:44:12] Error in run 322: Run already exists in server. Run id(s): {9028228}
[2018-04-11 21:44:12] Started run 330 on task 146197, dataset 'dna'.
[2018-04-11 21:44:12] Error in run 323: Run already exists in server. Run id(s): {9028102}
[2018-04-11 21:44:12] Started run 331 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 324: Run already exists in server. Run id(s): {9028244}
[2018-04-11 21:44:13] Error in run 326: Run already exists in server. Run id(s): {9028318}
[2018-04-11 21:44:13] Error in run 325: Run already exists in server. Run id(s): {9028253}
[2018-04-11 21:44:13] Started run 332 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Started run 334 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Started run 333 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 327: Run already exists in server. Run id(s): {9028362}
[2018-04-11 21:44:13] Started run 335 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 328: Run already exists in server. Run id(s): {9028272}
[2018-04-11 21:44:13] Started run 336 on task 146197, dataset 'dna'.
[2018-04-11 21:44:16] Error in run 329: Run already exists in server. Run id(s): {9028263}
[2018-04-11 21:44:16] Started run 337 on task 146197, dataset 'dna'.
[2018-04-11 21:44:16] Error in run 330: Run already exists in server. Run id(s): {9028464}
[2018-04-11 21:44:16] Started run 338 on task 146197, dataset 'dna'.
[2018-04-11 21:44:17] Error in run 331: Run already exists in server. Run id(s): {9028499}
[2018-04-11 21:44:17] Started run 339 on task 146197, dataset 'dna'.
[2018-04-11 21:44:17] Error in run 332: Run already exists in server. Run id(s): {9028567}
[2018-04-11 21:44:17] Started run 340 on task 146197, dataset 'dna'.
[2018-04-11 21:44:17] Error in run 333: Run already exists in server. Run id(s): {9028470}
[2018-04-11 21:44:17] Error in run 334: Run already exists in server. Run id(s): {9028511}
[2018-04-11 21:44:17] Started run 341 on task 146197, dataset 'dna'.
[2018-04-11 21:44:17] Started run 342 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Error in run 335: Run already exists in server. Run id(s): {9028468}
[2018-04-11 21:44:18] Started run 343 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Error in run 336: Run already exists in server. Run id(s): {9028569}
[2018-04-11 21:44:18] Started run 344 on task 146197, dataset 'dna'.
[2018-04-11 21:44:20] Error in run 337: Run already exists in server. Run id(s): {9028610}
[2018-04-11 21:44:20] Started run 345 on task 146197, dataset 'dna'.
[2018-04-11 21:44:21] Error in run 338: Run already exists in server. Run id(s): {9028720}
[2018-04-11 21:44:21] Started run 346 on task 146197, dataset 'dna'.
[2018-04-11 21:44:21] Error in run 339: Run already exists in server. Run id(s): {9028678}
[2018-04-11 21:44:21] Started run 347 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 340: Run already exists in server. Run id(s): {9028723}
[2018-04-11 21:44:22] Started run 348 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 341: Run already exists in server. Run id(s): {9028753}
[2018-04-11 21:44:22] Started run 349 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 342: Run already exists in server. Run id(s): {9028715}
[2018-04-11 21:44:22] Started run 350 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 343: Run already exists in server. Run id(s): {9028775}
[2018-04-11 21:44:22] Started run 351 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 344: Run already exists in server. Run id(s): {9028819}
[2018-04-11 21:44:22] Started run 352 on task 146197, dataset 'dna'.
[2018-04-11 21:44:25] Error in run 345: Run already exists in server. Run id(s): {9028874}
[2018-04-11 21:44:25] Started run 353 on task 146197, dataset 'dna'.
[2018-04-11 21:44:25] Error in run 346: Run already exists in server. Run id(s): {9028931}
[2018-04-11 21:44:25] Started run 354 on task 146197, dataset 'dna'.
[2018-04-11 21:44:26] Error in run 347: Run already exists in server. Run id(s): {9028963}
[2018-04-11 21:44:26] Started run 355 on task 146197, dataset 'dna'.
[2018-04-11 21:44:26] Error in run 348: Run already exists in server. Run id(s): {9028833}
[2018-04-11 21:44:26] Started run 356 on task 146197, dataset 'dna'.
[2018-04-11 21:44:26] Error in run 349: Run already exists in server. Run id(s): {9028969}
[2018-04-11 21:44:26] Started run 357 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Error in run 350: Run already exists in server. Run id(s): {9028993}
[2018-04-11 21:44:27] Started run 358 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Error in run 351: Run already exists in server. Run id(s): {9029018}
[2018-04-11 21:44:27] Started run 359 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Error in run 352: Run already exists in server. Run id(s): {9028951}
[2018-04-11 21:44:27] Started run 360 on task 146197, dataset 'dna'.
[2018-04-11 21:44:29] Error in run 353: Run already exists in server. Run id(s): {9029236}
[2018-04-11 21:44:29] Started run 361 on task 146197, dataset 'dna'.
[2018-04-11 21:44:30] Error in run 354: Run already exists in server. Run id(s): {9029127}
[2018-04-11 21:44:30] Started run 362 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 355: Run already exists in server. Run id(s): {9029192}
[2018-04-11 21:44:31] Started run 363 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 356: Run already exists in server. Run id(s): {9029197}
[2018-04-11 21:44:31] Started run 364 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 357: Run already exists in server. Run id(s): {9029082}
[2018-04-11 21:44:31] Started run 365 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 358: Run already exists in server. Run id(s): {9029170}
[2018-04-11 21:44:31] Started run 366 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 359: Run already exists in server. Run id(s): {9029206}
[2018-04-11 21:44:31] Started run 367 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 360: Run already exists in server. Run id(s): {9029267}
[2018-04-11 21:44:31] Started run 368 on task 146197, dataset 'dna'.
[2018-04-11 21:44:34] Error in run 361: Run already exists in server. Run id(s): {9029332}
[2018-04-11 21:44:34] Started run 369 on task 146197, dataset 'dna'.
[2018-04-11 21:44:35] Error in run 362: Run already exists in server. Run id(s): {9029380}
[2018-04-11 21:44:35] Started run 370 on task 146197, dataset 'dna'.
[2018-04-11 21:44:35] Error in run 363: Run already exists in server. Run id(s): {9029452}
[2018-04-11 21:44:35] Started run 371 on task 146197, dataset 'dna'.
[2018-04-11 21:44:35] Error in run 364: Run already exists in server. Run id(s): {9029442}
[2018-04-11 21:44:35] Error in run 365: Run already exists in server. Run id(s): {9029446}
[2018-04-11 21:44:35] Started run 372 on task 146197, dataset 'dna'.
[2018-04-11 21:44:35] Started run 373 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Error in run 366: Run already exists in server. Run id(s): {9029450}
[2018-04-11 21:44:36] Started run 374 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Error in run 367: Run already exists in server. Run id(s): {9029491}
[2018-04-11 21:44:36] Started run 375 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Error in run 368: Run already exists in server. Run id(s): {9029468}
[2018-04-11 21:44:36] Started run 376 on task 146197, dataset 'dna'.
[2018-04-11 21:44:38] Error in run 369: Run already exists in server. Run id(s): {9029528}
[2018-04-11 21:44:38] Started run 377 on task 146197, dataset 'dna'.
[2018-04-11 21:44:39] Error in run 370: Run already exists in server. Run id(s): {9029640}
[2018-04-11 21:44:39] Started run 378 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 371: Run already exists in server. Run id(s): {9029764}
[2018-04-11 21:44:40] Started run 379 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 372: Run already exists in server. Run id(s): {9029670}
[2018-04-11 21:44:40] Started run 380 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 373: Run already exists in server. Run id(s): {9029700}
[2018-04-11 21:44:40] Started run 381 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 374: Run already exists in server. Run id(s): {9029701}
[2018-04-11 21:44:40] Started run 382 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 375: Run already exists in server. Run id(s): {9029662}
[2018-04-11 21:44:40] Started run 383 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 376: Run already exists in server. Run id(s): {9029735}
[2018-04-11 21:44:40] Started run 384 on task 146197, dataset 'dna'.
[2018-04-11 21:44:43] Error in run 377: Run already exists in server. Run id(s): {9029811}
[2018-04-11 21:44:43] Started run 385 on task 146197, dataset 'dna'.
[2018-04-11 21:44:44] Error in run 378: Run already exists in server. Run id(s): {9029854}
[2018-04-11 21:44:44] Started run 386 on task 146197, dataset 'dna'.
[2018-04-11 21:44:44] Error in run 379: Run already exists in server. Run id(s): {9029877}
[2018-04-11 21:44:44] Started run 387 on task 146197, dataset 'dna'.
[2018-04-11 21:44:44] Error in run 380: Run already exists in server. Run id(s): {9029971}
[2018-04-11 21:44:44] Started run 388 on task 146197, dataset 'dna'.
[2018-04-11 21:44:44] Error in run 381: Run already exists in server. Run id(s): {9029839}
[2018-04-11 21:44:44] Started run 389 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Error in run 382: Run already exists in server. Run id(s): {9029933}
[2018-04-11 21:44:45] Started run 390 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Error in run 383: Run already exists in server. Run id(s): {9029995}
[2018-04-11 21:44:45] Started run 391 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Error in run 384: Run already exists in server. Run id(s): {9030018}
[2018-04-11 21:44:45] Started run 392 on task 146197, dataset 'dna'.
[2018-04-11 21:44:47] Error in run 385: Run already exists in server. Run id(s): {9029925}
[2018-04-11 21:44:47] Started run 393 on task 146197, dataset 'dna'.
[2018-04-11 21:44:48] Error in run 386: Run already exists in server. Run id(s): {9029942}
[2018-04-11 21:44:48] Started run 394 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 387: Run already exists in server. Run id(s): {9030090}
[2018-04-11 21:44:49] Error in run 388: Run already exists in server. Run id(s): {9030123}
[2018-04-11 21:44:49] Started run 395 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 389: Run already exists in server. Run id(s): {9030134}
[2018-04-11 21:44:49] Started run 396 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Started run 397 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 390: Run already exists in server. Run id(s): {9030104}
[2018-04-11 21:44:49] Started run 398 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 391: Run already exists in server. Run id(s): {9030210}
[2018-04-11 21:44:49] Started run 399 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 392: Run already exists in server. Run id(s): {9030163}
[2018-04-11 21:44:49] Started run 400 on task 146197, dataset 'dna'.
[2018-04-11 21:44:52] Error in run 393: Run already exists in server. Run id(s): {9030288}
[2018-04-11 21:44:52] Started run 401 on task 146197, dataset 'dna'.
[2018-04-11 21:44:53] Error in run 394: Run already exists in server. Run id(s): {9030266}
[2018-04-11 21:44:53] Started run 402 on task 146197, dataset 'dna'.
[2018-04-11 21:44:53] Error in run 395: Run already exists in server. Run id(s): {9030196}
[2018-04-11 21:44:53] Error in run 397: Run already exists in server. Run id(s): {9030322}
[2018-04-11 21:44:53] Started run 403 on task 146197, dataset 'dna'.
[2018-04-11 21:44:53] Error in run 396: Run already exists in server. Run id(s): {9030433}
[2018-04-11 21:44:53] Started run 405 on task 146197, dataset 'dna'.
[2018-04-11 21:44:53] Started run 404 on task 146197, dataset 'dna'.
[2018-04-11 21:44:54] Error in run 398: Run already exists in server. Run id(s): {9030243}
[2018-04-11 21:44:54] Started run 406 on task 146197, dataset 'dna'.
[2018-04-11 21:44:54] Error in run 399: Run already exists in server. Run id(s): {9030398}
[2018-04-11 21:44:54] Started run 407 on task 146197, dataset 'dna'.
[2018-04-11 21:44:54] Error in run 400: Run already exists in server. Run id(s): {9030438}
[2018-04-11 21:44:54] Started run 408 on task 146197, dataset 'dna'.
[2018-04-11 21:44:56] Error in run 401: Run already exists in server. Run id(s): {9030498, 9030446}
[2018-04-11 21:44:56] Started run 409 on task 146197, dataset 'dna'.
[2018-04-11 21:44:57] Error in run 402: Run already exists in server. Run id(s): {9030477}
[2018-04-11 21:44:57] Started run 410 on task 146197, dataset 'dna'.
[2018-04-11 21:44:58] Error in run 403: Run already exists in server. Run id(s): {9030547}
[2018-04-11 21:44:58] Started run 411 on task 146197, dataset 'dna'.
[2018-04-11 21:44:58] Error in run 404: Run already exists in server. Run id(s): {9030553}
[2018-04-11 21:44:58] Error in run 405: Run already exists in server. Run id(s): {9030592}
[2018-04-11 21:44:58] Started run 412 on task 146197, dataset 'dna'.
[2018-04-11 21:44:58] Started run 413 on task 146197, dataset 'dna'.
[2018-04-11 21:44:58] Error in run 406: Run already exists in server. Run id(s): {9030591}
[2018-04-11 21:44:58] Started run 414 on task 146197, dataset 'dna'.
[2018-04-11 21:44:59] Error in run 407: Run already exists in server. Run id(s): {9030531}
[2018-04-11 21:44:59] Started run 415 on task 146197, dataset 'dna'.
[2018-04-11 21:44:59] Error in run 408: Run already exists in server. Run id(s): {9030675}
[2018-04-11 21:44:59] Started run 416 on task 146197, dataset 'dna'.
[2018-04-11 21:45:01] Error in run 409: Run already exists in server. Run id(s): {9030709}
[2018-04-11 21:45:01] Started run 417 on task 146197, dataset 'dna'.
[2018-04-11 21:45:02] Error in run 410: Run already exists in server. Run id(s): {9030672}
[2018-04-11 21:45:02] Started run 418 on task 146197, dataset 'dna'.
[2018-04-11 21:45:02] Error in run 411: Run already exists in server. Run id(s): {9030628}
[2018-04-11 21:45:02] Started run 419 on task 146197, dataset 'dna'.
[2018-04-11 21:45:02] Error in run 412: Run already exists in server. Run id(s): {9030782}
[2018-04-11 21:45:03] Error in run 413: Run already exists in server. Run id(s): {9030745}
[2018-04-11 21:45:02] Started run 420 on task 146197, dataset 'dna'.
[2018-04-11 21:45:03] Started run 421 on task 146197, dataset 'dna'.
[2018-04-11 21:45:03] Error in run 414: Run already exists in server. Run id(s): {9030798}
[2018-04-11 21:45:03] Started run 422 on task 146197, dataset 'dna'.
[2018-04-11 21:45:03] Error in run 415: Run already exists in server. Run id(s): {9030789}
[2018-04-11 21:45:03] Started run 423 on task 146197, dataset 'dna'.
[2018-04-11 21:45:03] Error in run 416: Run already exists in server. Run id(s): {9030739}
[2018-04-11 21:45:03] Started run 424 on task 146197, dataset 'dna'.
[2018-04-11 21:45:06] Error in run 417: Run already exists in server. Run id(s): {9030863}
[2018-04-11 21:45:06] Started run 425 on task 146197, dataset 'dna'.
[2018-04-11 21:45:06] Error in run 418: Run already exists in server. Run id(s): {9030905}
[2018-04-11 21:45:06] Started run 426 on task 146197, dataset 'dna'.
[2018-04-11 21:45:07] Error in run 419: Run already exists in server. Run id(s): {9030907}
[2018-04-11 21:45:07] Started run 427 on task 146197, dataset 'dna'.
[2018-04-11 21:45:07] Error in run 420: Run already exists in server. Run id(s): {9030979}
[2018-04-11 21:45:07] Started run 428 on task 146197, dataset 'dna'.
[2018-04-11 21:45:07] Error in run 421: Run already exists in server. Run id(s): {9030990}
[2018-04-11 21:45:07] Started run 429 on task 146197, dataset 'dna'.
[2018-04-11 21:45:07] Error in run 422: Run already exists in server. Run id(s): {9030882}
[2018-04-11 21:45:07] Started run 430 on task 146197, dataset 'dna'.
[2018-04-11 21:45:08] Error in run 423: Run already exists in server. Run id(s): {9030889}
[2018-04-11 21:45:08] Started run 431 on task 146197, dataset 'dna'.
[2018-04-11 21:45:08] Error in run 424: Run already exists in server. Run id(s): {9031041}
[2018-04-11 21:45:08] Started run 432 on task 146197, dataset 'dna'.
[2018-04-11 21:45:10] Error in run 425: Run already exists in server. Run id(s): {9031032}
[2018-04-11 21:45:10] Started run 433 on task 146197, dataset 'dna'.
[2018-04-11 21:45:11] Error in run 426: Run already exists in server. Run id(s): {9031095}
[2018-04-11 21:45:11] Started run 434 on task 146197, dataset 'dna'.
[2018-04-11 21:45:11] Error in run 427: Run already exists in server. Run id(s): {9031114}
[2018-04-11 21:45:11] Started run 435 on task 146197, dataset 'dna'.
[2018-04-11 21:45:11] Error in run 428: Run already exists in server. Run id(s): {9031121}
[2018-04-11 21:45:11] Started run 436 on task 146197, dataset 'dna'.
[2018-04-11 21:45:12] Error in run 429: Run already exists in server. Run id(s): {9031019}
[2018-04-11 21:45:12] Started run 437 on task 146197, dataset 'dna'.
[2018-04-11 21:45:12] Error in run 430: Run already exists in server. Run id(s): {9031066}
[2018-04-11 21:45:12] Started run 438 on task 146197, dataset 'dna'.
[2018-04-11 21:45:12] Error in run 431: Run already exists in server. Run id(s): {9031109}
[2018-04-11 21:45:12] Started run 439 on task 146197, dataset 'dna'.
[2018-04-11 21:45:12] Error in run 432: Run already exists in server. Run id(s): {9031233}
[2018-04-11 21:45:12] Started run 440 on task 146197, dataset 'dna'.
[2018-04-11 21:45:14] Error in run 433: Run already exists in server. Run id(s): {9031141}
[2018-04-11 21:45:15] Started run 441 on task 146197, dataset 'dna'.
[2018-04-11 21:45:15] Error in run 434: Run already exists in server. Run id(s): {9031145}
[2018-04-11 21:45:15] Started run 442 on task 146197, dataset 'dna'.
[2018-04-11 21:45:16] Error in run 435: Run already exists in server. Run id(s): {9031282}
[2018-04-11 21:45:16] Started run 443 on task 146197, dataset 'dna'.
[2018-04-11 21:45:16] Error in run 436: Run already exists in server. Run id(s): {9031235}
[2018-04-11 21:45:16] Started run 444 on task 146197, dataset 'dna'.
[2018-04-11 21:45:16] Error in run 437: Run already exists in server. Run id(s): {9031329}
[2018-04-11 21:45:16] Started run 445 on task 146197, dataset 'dna'.
[2018-04-11 21:45:16] Error in run 438: Run already exists in server. Run id(s): {9031332}
[2018-04-11 21:45:16] Started run 446 on task 146197, dataset 'dna'.
[2018-04-11 21:45:17] Error in run 439: Run already exists in server. Run id(s): {9031242}
[2018-04-11 21:45:17] Error in run 440: Run already exists in server. Run id(s): {9031361}
[2018-04-11 21:45:17] Started run 447 on task 146197, dataset 'dna'.
[2018-04-11 21:45:17] Started run 448 on task 146197, dataset 'dna'.
[2018-04-11 21:45:19] Error in run 441: Run already exists in server. Run id(s): {9031247}
[2018-04-11 21:45:19] Started run 449 on task 146197, dataset 'dna'.
[2018-04-11 21:45:20] Error in run 442: Run already exists in server. Run id(s): {9031450}
[2018-04-11 21:45:20] Started run 450 on task 146197, dataset 'dna'.
[2018-04-11 21:45:20] Error in run 443: Run already exists in server. Run id(s): {9031446}
[2018-04-11 21:45:20] Started run 451 on task 146197, dataset 'dna'.
[2018-04-11 21:45:20] Error in run 444: Run already exists in server. Run id(s): {9031341}
[2018-04-11 21:45:20] Started run 452 on task 146197, dataset 'dna'.
[2018-04-11 21:45:21] Error in run 445: Run already exists in server. Run id(s): {9031461}
[2018-04-11 21:45:21] Started run 453 on task 146197, dataset 'dna'.
[2018-04-11 21:45:21] Error in run 446: Run already exists in server. Run id(s): {9031495}
[2018-04-11 21:45:21] Started run 454 on task 146197, dataset 'dna'.
[2018-04-11 21:45:21] Error in run 448: Run already exists in server. Run id(s): {9031543}
[2018-04-11 21:45:21] Error in run 447: Run already exists in server. Run id(s): {9031529}
[2018-04-11 21:45:21] Started run 455 on task 146197, dataset 'dna'.
[2018-04-11 21:45:21] Started run 456 on task 146197, dataset 'dna'.
[2018-04-11 21:45:24] Error in run 449: Run already exists in server. Run id(s): {9031504}
[2018-04-11 21:45:24] Started run 457 on task 146197, dataset 'dna'.
[2018-04-11 21:45:25] Error in run 450: Run already exists in server. Run id(s): {9031482}
[2018-04-11 21:45:25] Error in run 451: Run already exists in server. Run id(s): {9031656}
[2018-04-11 21:45:25] Started run 458 on task 146197, dataset 'dna'.
[2018-04-11 21:45:25] Started run 459 on task 146197, dataset 'dna'.
[2018-04-11 21:45:25] Error in run 452: Run already exists in server. Run id(s): {9031605}
[2018-04-11 21:45:25] Started run 460 on task 146197, dataset 'dna'.
[2018-04-11 21:45:25] Error in run 454: Run already exists in server. Run id(s): {9031562}
[2018-04-11 21:45:25] Error in run 453: Run already exists in server. Run id(s): {9031677}
[2018-04-11 21:45:25] Started run 461 on task 146197, dataset 'dna'.
[2018-04-11 21:45:25] Started run 462 on task 146197, dataset 'dna'.
[2018-04-11 21:45:26] Error in run 456: Run already exists in server. Run id(s): {9031713}
[2018-04-11 21:45:26] Error in run 455: Run already exists in server. Run id(s): {9031707}
[2018-04-11 21:45:26] Started run 463 on task 146197, dataset 'dna'.
[2018-04-11 21:45:26] Started run 464 on task 146197, dataset 'dna'.
[2018-04-11 21:45:28] Error in run 457: Run already exists in server. Run id(s): {9031744}
[2018-04-11 21:45:28] Started run 465 on task 146197, dataset 'dna'.
[2018-04-11 21:45:29] Error in run 459: Run already exists in server. Run id(s): {9031774}
[2018-04-11 21:45:29] Started run 466 on task 146197, dataset 'dna'.
[2018-04-11 21:45:29] Error in run 458: Run already exists in server. Run id(s): {9031715}
[2018-04-11 21:45:29] Started run 467 on task 146197, dataset 'dna'.
[2018-04-11 21:45:29] Error in run 460: Run already exists in server. Run id(s): {9031824}
[2018-04-11 21:45:29] Started run 468 on task 146197, dataset 'dna'.
[2018-04-11 21:45:30] Error in run 462: Run already exists in server. Run id(s): {9031760}
[2018-04-11 21:45:30] Error in run 461: Run already exists in server. Run id(s): {9031796}
[2018-04-11 21:45:30] Started run 469 on task 146197, dataset 'dna'.
[2018-04-11 21:45:30] Started run 470 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Error in run 463: Run already exists in server. Run id(s): {9031925}
[2018-04-11 21:45:31] Started run 471 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Error in run 464: Run already exists in server. Run id(s): {9031889}
[2018-04-11 21:45:31] Started run 472 on task 146197, dataset 'dna'.
[2018-04-11 21:45:33] Error in run 465: Run already exists in server. Run id(s): {9031803}
[2018-04-11 21:45:33] Started run 473 on task 146197, dataset 'dna'.
[2018-04-11 21:45:34] Error in run 466: Run already exists in server. Run id(s): {9031874}
[2018-04-11 21:45:34] Error in run 467: Run already exists in server. Run id(s): {9031855}
[2018-04-11 21:45:34] Error in run 468: Run already exists in server. Run id(s): {9032004}
[2018-04-11 21:45:34] Started run 474 on task 146197, dataset 'dna'.
[2018-04-11 21:45:34] Started run 476 on task 146197, dataset 'dna'.
[2018-04-11 21:45:34] Started run 475 on task 146197, dataset 'dna'.
[2018-04-11 21:45:35] Error in run 469: Run already exists in server. Run id(s): {9032021}
[2018-04-11 21:45:35] Error in run 470: Run already exists in server. Run id(s): {9032034}
[2018-04-11 21:45:35] Started run 477 on task 146197, dataset 'dna'.
[2018-04-11 21:45:35] Started run 478 on task 146197, dataset 'dna'.
[2018-04-11 21:45:35] Error in run 471: Run already exists in server. Run id(s): {9032015}
[2018-04-11 21:45:35] Started run 479 on task 146197, dataset 'dna'.
[2018-04-11 21:45:35] Error in run 472: Run already exists in server. Run id(s): {9032090}
[2018-04-11 21:45:35] Started run 480 on task 146197, dataset 'dna'.
[2018-04-11 21:45:37] Error in run 473: Run already exists in server. Run id(s): {9032111}
[2018-04-11 21:45:37] Started run 481 on task 146197, dataset 'dna'.
[2018-04-11 21:45:38] Error in run 474: Run already exists in server. Run id(s): {9032119}
[2018-04-11 21:45:38] Started run 482 on task 146197, dataset 'dna'.
[2018-04-11 21:45:39] Error in run 475: Run already exists in server. Run id(s): {9032072}
[2018-04-11 21:45:39] Error in run 476: Run already exists in server. Run id(s): {9032246}
[2018-04-11 21:45:39] Started run 483 on task 146197, dataset 'dna'.
[2018-04-11 21:45:39] Started run 484 on task 146197, dataset 'dna'.
[2018-04-11 21:45:39] Error in run 477: Run already exists in server. Run id(s): {9032210}
[2018-04-11 21:45:39] Error in run 478: Run already exists in server. Run id(s): {9032274}
[2018-04-11 21:45:39] Started run 485 on task 146197, dataset 'dna'.
[2018-04-11 21:45:39] Started run 486 on task 146197, dataset 'dna'.
[2018-04-11 21:45:40] Error in run 479: Run already exists in server. Run id(s): {9032278}
[2018-04-11 21:45:40] Started run 487 on task 146197, dataset 'dna'.
[2018-04-11 21:45:40] Error in run 480: Run already exists in server. Run id(s): {9032312}
[2018-04-11 21:45:40] Started run 488 on task 146197, dataset 'dna'.
[2018-04-11 21:45:42] Error in run 481: Run already exists in server. Run id(s): {9032273}
[2018-04-11 21:45:42] Started run 489 on task 146197, dataset 'dna'.
[2018-04-11 21:45:43] Error in run 482: Run already exists in server. Run id(s): {9032354}
[2018-04-11 21:45:43] Started run 490 on task 146197, dataset 'dna'.
[2018-04-11 21:45:43] Error in run 483: Run already exists in server. Run id(s): {9032316}
[2018-04-11 21:45:43] Started run 491 on task 146197, dataset 'dna'.
[2018-04-11 21:45:43] Error in run 484: Run already exists in server. Run id(s): {9032451}
[2018-04-11 21:45:43] Started run 492 on task 146197, dataset 'dna'.
[2018-04-11 21:45:44] Error in run 486: Run already exists in server. Run id(s): {9032467}
[2018-04-11 21:45:44] Error in run 485: Run already exists in server. Run id(s): {9032371}
[2018-04-11 21:45:44] Started run 493 on task 146197, dataset 'dna'.
[2018-04-11 21:45:44] Started run 494 on task 146197, dataset 'dna'.
[2018-04-11 21:45:44] Error in run 487: Run already exists in server. Run id(s): {9032366}
[2018-04-11 21:45:44] Started run 495 on task 146197, dataset 'dna'.
[2018-04-11 21:45:44] Error in run 488: Run already exists in server. Run id(s): {9032476}
[2018-04-11 21:45:44] Started run 496 on task 146197, dataset 'dna'.
[2018-04-11 21:45:46] Error in run 489: Run already exists in server. Run id(s): {9032510}
[2018-04-11 21:45:46] Started run 497 on task 146197, dataset 'dna'.
[2018-04-11 21:45:47] Error in run 490: Run already exists in server. Run id(s): {9032551}
[2018-04-11 21:45:47] Started run 498 on task 146197, dataset 'dna'.
[2018-04-11 21:45:48] Error in run 491: Run already exists in server. Run id(s): {9032656}
[2018-04-11 21:45:48] Started run 499 on task 146197, dataset 'dna'.
[2018-04-11 21:45:48] Error in run 492: Run already exists in server. Run id(s): {9032645}
[2018-04-11 21:45:48] Started run 500 on task 146197, dataset 'dna'.
[2018-04-11 21:45:48] Error in run 493: Run already exists in server. Run id(s): {9032619}
[2018-04-11 21:45:48] Started run 501 on task 146197, dataset 'dna'.
[2018-04-11 21:45:48] Error in run 494: Run already exists in server. Run id(s): {9032690}
[2018-04-11 21:45:48] Started run 502 on task 146197, dataset 'dna'.
[2018-04-11 21:45:49] Error in run 495: Run already exists in server. Run id(s): {9032697}
[2018-04-11 21:45:49] Started run 503 on task 146197, dataset 'dna'.
[2018-04-11 21:45:49] Error in run 496: Run already exists in server. Run id(s): {9032643}
[2018-04-11 21:45:49] Started run 504 on task 146197, dataset 'dna'.
[2018-04-11 21:45:51] Error in run 497: Run already exists in server. Run id(s): {9032694}
[2018-04-11 21:45:51] Started run 505 on task 146197, dataset 'dna'.
[2018-04-11 21:45:52] Error in run 498: Run already exists in server. Run id(s): {9032787}
[2018-04-11 21:45:52] Started run 506 on task 146197, dataset 'dna'.
[2018-04-11 21:45:52] Error in run 499: Run already exists in server. Run id(s): {9032703}
[2018-04-11 21:45:52] Started run 507 on task 146197, dataset 'dna'.
[2018-04-11 21:45:52] Error in run 500: Run already exists in server. Run id(s): {9032881}
[2018-04-11 21:45:52] Started run 508 on task 146197, dataset 'dna'.
[2018-04-11 21:45:53] Error in run 502: Run already exists in server. Run id(s): {9032751}
[2018-04-11 21:45:53] Error in run 501: Run already exists in server. Run id(s): {9032878}
[2018-04-11 21:45:53] Started run 509 on task 146197, dataset 'dna'.
[2018-04-11 21:45:53] Started run 510 on task 146197, dataset 'dna'.
[2018-04-11 21:45:53] Error in run 503: Run already exists in server. Run id(s): {9032925}
[2018-04-11 21:45:53] Started run 511 on task 146197, dataset 'dna'.
[2018-04-11 21:45:53] Error in run 504: Run already exists in server. Run id(s): {9032915}
[2018-04-11 21:45:53] Started run 512 on task 146197, dataset 'dna'.
[2018-04-11 21:45:55] Error in run 505: Run already exists in server. Run id(s): {9032918}
[2018-04-11 21:45:55] Started run 513 on task 146197, dataset 'dna'.
[2018-04-11 21:45:57] Error in run 506: Run already exists in server. Run id(s): {9032947}
[2018-04-11 21:45:57] Error in run 507: Run already exists in server. Run id(s): {9032886}
[2018-04-11 21:45:57] Error in run 508: Run already exists in server. Run id(s): {9033019}
[2018-04-11 21:45:57] Started run 514 on task 146197, dataset 'dna'.
[2018-04-11 21:45:57] Started run 516 on task 146197, dataset 'dna'.
[2018-04-11 21:45:57] Started run 515 on task 146197, dataset 'dna'.
[2018-04-11 21:45:57] Error in run 509: Run already exists in server. Run id(s): {9033118}
[2018-04-11 21:45:57] Started run 517 on task 146197, dataset 'dna'.
[2018-04-11 21:45:57] Error in run 510: Run already exists in server. Run id(s): {9033119}
[2018-04-11 21:45:57] Started run 518 on task 146197, dataset 'dna'.
[2018-04-11 21:45:58] Error in run 511: Run already exists in server. Run id(s): {9033068}
[2018-04-11 21:45:58] Started run 519 on task 146197, dataset 'dna'.
[2018-04-11 21:45:58] Error in run 512: Run already exists in server. Run id(s): {9033123}
[2018-04-11 21:45:58] Started run 520 on task 146197, dataset 'dna'.
[2018-04-11 21:46:00] Error in run 513: Run already exists in server. Run id(s): {9033144}
[2018-04-11 21:46:00] Started run 521 on task 146197, dataset 'dna'.
[2018-04-11 21:46:01] Error in run 514: Run already exists in server. Run id(s): {9033157}
[2018-04-11 21:46:01] Started run 522 on task 146197, dataset 'dna'.
[2018-04-11 21:46:01] Error in run 516: Run already exists in server. Run id(s): {9033245}
[2018-04-11 21:46:01] Error in run 515: Run already exists in server. Run id(s): {9033189}
[2018-04-11 21:46:01] Started run 523 on task 146197, dataset 'dna'.
[2018-04-11 21:46:01] Started run 524 on task 146197, dataset 'dna'.
[2018-04-11 21:46:02] Error in run 517: Run already exists in server. Run id(s): {9033303}
[2018-04-11 21:46:02] Started run 525 on task 146197, dataset 'dna'.
[2018-04-11 21:46:02] Error in run 518: Run already exists in server. Run id(s): {9033348}
[2018-04-11 21:46:02] Started run 526 on task 146197, dataset 'dna'.
[2018-04-11 21:46:02] Error in run 519: Run already exists in server. Run id(s): {9033242}
[2018-04-11 21:46:02] Started run 527 on task 146197, dataset 'dna'.
[2018-04-11 21:46:02] Error in run 520: Run already exists in server. Run id(s): {9033326}
[2018-04-11 21:46:02] Started run 528 on task 146197, dataset 'dna'.
[2018-04-11 21:46:05] Error in run 521: Run already exists in server. Run id(s): {9033391}
[2018-04-11 21:46:05] Started run 529 on task 146197, dataset 'dna'.
[2018-04-11 21:46:06] Error in run 522: Run already exists in server. Run id(s): {9033383}
[2018-04-11 21:46:06] Started run 530 on task 146197, dataset 'dna'.
[2018-04-11 21:46:06] Error in run 523: Run already exists in server. Run id(s): {9033424}
[2018-04-11 21:46:06] Started run 531 on task 146197, dataset 'dna'.
[2018-04-11 21:46:06] Error in run 524: Run already exists in server. Run id(s): {9033460}
[2018-04-11 21:46:06] Started run 532 on task 146197, dataset 'dna'.
[2018-04-11 21:46:06] Error in run 525: Run already exists in server. Run id(s): {9033412}
[2018-04-11 21:46:06] Started run 533 on task 146197, dataset 'dna'.
[2018-04-11 21:46:06] Error in run 526: Run already exists in server. Run id(s): {9033486}
[2018-04-11 21:46:06] Started run 534 on task 146197, dataset 'dna'.
[2018-04-11 21:46:07] Error in run 527: Run already exists in server. Run id(s): {9033547}
[2018-04-11 21:46:07] Error in run 528: Run already exists in server. Run id(s): {9033587}
[2018-04-11 21:46:07] Started run 535 on task 146197, dataset 'dna'.
[2018-04-11 21:46:07] Started run 536 on task 146197, dataset 'dna'.
[2018-04-11 21:46:09] Error in run 529: Run already exists in server. Run id(s): {9033612}
[2018-04-11 21:46:09] Started run 537 on task 146197, dataset 'dna'.
[2018-04-11 21:46:10] Error in run 530: Run already exists in server. Run id(s): {9033581}
[2018-04-11 21:46:10] Started run 538 on task 146197, dataset 'dna'.
[2018-04-11 21:46:10] Error in run 531: Run already exists in server. Run id(s): {9033638}
[2018-04-11 21:46:10] Started run 539 on task 146197, dataset 'dna'.
[2018-04-11 21:46:11] Error in run 532: Run already exists in server. Run id(s): {9033608}
[2018-04-11 21:46:11] Error in run 533: Run already exists in server. Run id(s): {9033651}
[2018-04-11 21:46:11] Started run 540 on task 146197, dataset 'dna'.
[2018-04-11 21:46:11] Started run 541 on task 146197, dataset 'dna'.
[2018-04-11 21:46:11] Error in run 534: Run already exists in server. Run id(s): {9033583}
[2018-04-11 21:46:11] Started run 542 on task 146197, dataset 'dna'.
[2018-04-11 21:46:11] Error in run 535: Run already exists in server. Run id(s): {9033847}
[2018-04-11 21:46:11] Started run 543 on task 146197, dataset 'dna'.
[2018-04-11 21:46:12] Error in run 536: Run already exists in server. Run id(s): {9033693}
[2018-04-11 21:46:12] Started run 544 on task 146197, dataset 'dna'.
[2018-04-11 21:46:13] Error in run 537: Run already exists in server. Run id(s): {9033769}
[2018-04-11 21:46:13] Started run 545 on task 146197, dataset 'dna'.
[2018-04-11 21:46:15] Error in run 538: Run already exists in server. Run id(s): {9033732}
[2018-04-11 21:46:15] Started run 546 on task 146197, dataset 'dna'.
[2018-04-11 21:46:15] Error in run 539: Run already exists in server. Run id(s): {9033745}
[2018-04-11 21:46:15] Started run 547 on task 146197, dataset 'dna'.
[2018-04-11 21:46:15] Error in run 541: Run already exists in server. Run id(s): {9033878}
[2018-04-11 21:46:15] Started run 548 on task 146197, dataset 'dna'.
[2018-04-11 21:46:16] Error in run 542: Run already exists in server. Run id(s): {9033886}
[2018-04-11 21:46:16] Error in run 540: Run already exists in server. Run id(s): {9033811}
[2018-04-11 21:46:16] Started run 549 on task 146197, dataset 'dna'.
[2018-04-11 21:46:16] Started run 550 on task 146197, dataset 'dna'.
[2018-04-11 21:46:16] Error in run 543: Run already exists in server. Run id(s): {9033931}
[2018-04-11 21:46:16] Started run 551 on task 146197, dataset 'dna'.
[2018-04-11 21:46:16] Error in run 544: Run already exists in server. Run id(s): {9033850, 9033831}
[2018-04-11 21:46:16] Started run 552 on task 146197, dataset 'dna'.
[2018-04-11 21:46:18] Error in run 545: Run already exists in server. Run id(s): {9033983}
[2018-04-11 21:46:18] Started run 553 on task 146197, dataset 'dna'.
[2018-04-11 21:46:19] Error in run 546: Run already exists in server. Run id(s): {9033864}
[2018-04-11 21:46:19] Started run 554 on task 146197, dataset 'dna'.
[2018-04-11 21:46:19] Error in run 547: Run already exists in server. Run id(s): {9034052}
[2018-04-11 21:46:19] Started run 555 on task 146197, dataset 'dna'.
[2018-04-11 21:46:20] Error in run 548: Run already exists in server. Run id(s): {9034074}
[2018-04-11 21:46:20] Started run 556 on task 146197, dataset 'dna'.
[2018-04-11 21:46:20] Error in run 550: Run already exists in server. Run id(s): {9034062}
[2018-04-11 21:46:20] Error in run 549: Run already exists in server. Run id(s): {9033947}
[2018-04-11 21:46:20] Started run 557 on task 146197, dataset 'dna'.
[2018-04-11 21:46:20] Started run 558 on task 146197, dataset 'dna'.
[2018-04-11 21:46:20] Error in run 551: Run already exists in server. Run id(s): {9034107}
[2018-04-11 21:46:20] Started run 559 on task 146197, dataset 'dna'.
[2018-04-11 21:46:21] Error in run 552: Run already exists in server. Run id(s): {9034061}
[2018-04-11 21:46:21] Started run 560 on task 146197, dataset 'dna'.
[2018-04-11 21:46:23] Error in run 553: Run already exists in server. Run id(s): {9034120}
[2018-04-11 21:46:23] Started run 561 on task 146197, dataset 'dna'.
[2018-04-11 21:46:24] Error in run 555: Run already exists in server. Run id(s): {9034202}
[2018-04-11 21:46:24] Error in run 554: Run already exists in server. Run id(s): {9034177}
[2018-04-11 21:46:24] Started run 562 on task 146197, dataset 'dna'.
[2018-04-11 21:46:24] Started run 563 on task 146197, dataset 'dna'.
[2018-04-11 21:46:24] Error in run 556: Run already exists in server. Run id(s): {9034144}
[2018-04-11 21:46:24] Started run 564 on task 146197, dataset 'dna'.
[2018-04-11 21:46:25] Error in run 557: Run already exists in server. Run id(s): {9034224}
[2018-04-11 21:46:25] Error in run 558: Run already exists in server. Run id(s): {9034275}
[2018-04-11 21:46:25] Error in run 559: Run already exists in server. Run id(s): {9034279}
[2018-04-11 21:46:25] Started run 565 on task 146197, dataset 'dna'.
[2018-04-11 21:46:25] Started run 566 on task 146197, dataset 'dna'.
[2018-04-11 21:46:25] Started run 567 on task 146197, dataset 'dna'.
[2018-04-11 21:46:26] Error in run 560: Run already exists in server. Run id(s): {9034260}
[2018-04-11 21:46:26] Started run 568 on task 146197, dataset 'dna'.
[2018-04-11 21:46:27] Error in run 561: Run already exists in server. Run id(s): {9034299}
[2018-04-11 21:46:27] Started run 569 on task 146197, dataset 'dna'.
[2018-04-11 21:46:29] Error in run 563: Run already exists in server. Run id(s): {9034384}
[2018-04-11 21:46:29] Error in run 562: Run already exists in server. Run id(s): {9034359}
[2018-04-11 21:46:29] Started run 570 on task 146197, dataset 'dna'.
[2018-04-11 21:46:29] Started run 571 on task 146197, dataset 'dna'.
[2018-04-11 21:46:29] Error in run 564: Run already exists in server. Run id(s): {9034453}
[2018-04-11 21:46:29] Started run 572 on task 146197, dataset 'dna'.
[2018-04-11 21:46:30] Error in run 565: Run already exists in server. Run id(s): {9034335}
[2018-04-11 21:46:30] Error in run 566: Run already exists in server. Run id(s): {9034480}
[2018-04-11 21:46:30] Error in run 567: Run already exists in server. Run id(s): {9034419}
[2018-04-11 21:46:30] Started run 573 on task 146197, dataset 'dna'.
[2018-04-11 21:46:30] Started run 575 on task 146197, dataset 'dna'.
[2018-04-11 21:46:30] Started run 574 on task 146197, dataset 'dna'.
[2018-04-11 21:46:30] Error in run 568: Run already exists in server. Run id(s): {9034532}
[2018-04-11 21:46:30] Started run 576 on task 146197, dataset 'dna'.
[2018-04-11 21:46:32] Error in run 569: Run already exists in server. Run id(s): {9034526}
[2018-04-11 21:46:32] Started run 577 on task 146197, dataset 'dna'.
[2018-04-11 21:46:33] Error in run 570: Run already exists in server. Run id(s): {9034535}
[2018-04-11 21:46:33] Error in run 571: Run already exists in server. Run id(s): {9034583}
[2018-04-11 21:46:33] Error in run 572: Run already exists in server. Run id(s): {9034613}
[2018-04-11 21:46:33] Started run 578 on task 146197, dataset 'dna'.
[2018-04-11 21:46:33] Started run 579 on task 146197, dataset 'dna'.
[2018-04-11 21:46:33] Started run 580 on task 146197, dataset 'dna'.
[2018-04-11 21:46:34] Error in run 574: Run already exists in server. Run id(s): {9034675}
[2018-04-11 21:46:34] Error in run 575: Run already exists in server. Run id(s): {9034568}
[2018-04-11 21:46:34] Error in run 573: Run already exists in server. Run id(s): {9034648}
[2018-04-11 21:46:34] Started run 581 on task 146197, dataset 'dna'.
[2018-04-11 21:46:34] Started run 582 on task 146197, dataset 'dna'.
[2018-04-11 21:46:34] Started run 583 on task 146197, dataset 'dna'.
[2018-04-11 21:46:35] Error in run 576: Run already exists in server. Run id(s): {9034694}
[2018-04-11 21:46:35] Started run 584 on task 146197, dataset 'dna'.
[2018-04-11 21:46:37] Error in run 577: Run already exists in server. Run id(s): {9034742}
[2018-04-11 21:46:37] Started run 585 on task 146197, dataset 'dna'.
[2018-04-11 21:46:38] Error in run 578: Run already exists in server. Run id(s): {9034739}
[2018-04-11 21:46:38] Error in run 580: Run already exists in server. Run id(s): {9034749}
[2018-04-11 21:46:38] Error in run 579: Run already exists in server. Run id(s): {9034663}
[2018-04-11 21:46:38] Started run 586 on task 146197, dataset 'dna'.
[2018-04-11 21:46:38] Started run 588 on task 146197, dataset 'dna'.
[2018-04-11 21:46:38] Started run 587 on task 146197, dataset 'dna'.
[2018-04-11 21:46:39] Error in run 583: Run already exists in server. Run id(s): {9034743}
[2018-04-11 21:46:39] Error in run 582: Run already exists in server. Run id(s): {9034835}
[2018-04-11 21:46:39] Started run 589 on task 146197, dataset 'dna'.
[2018-04-11 21:46:39] Error in run 581: Run already exists in server. Run id(s): {9034807}
[2018-04-11 21:46:39] Started run 591 on task 146197, dataset 'dna'.
[2018-04-11 21:46:39] Started run 590 on task 146197, dataset 'dna'.
[2018-04-11 21:46:40] Error in run 584: Run already exists in server. Run id(s): {9034850}
[2018-04-11 21:46:40] Started run 592 on task 146197, dataset 'dna'.
[2018-04-11 21:46:41] Error in run 585: Run already exists in server. Run id(s): {9034870}
[2018-04-11 21:46:41] Started run 593 on task 146197, dataset 'dna'.
[2018-04-11 21:46:43] Error in run 587: Run already exists in server. Run id(s): {9034911}
[2018-04-11 21:46:43] Error in run 588: Run already exists in server. Run id(s): {9034813}
[2018-04-11 21:46:43] Started run 594 on task 146197, dataset 'dna'.
[2018-04-11 21:46:43] Error in run 586: Run already exists in server. Run id(s): {9034905}
[2018-04-11 21:46:43] Started run 596 on task 146197, dataset 'dna'.
[2018-04-11 21:46:43] Started run 595 on task 146197, dataset 'dna'.
[2018-04-11 21:46:44] Error in run 590: Run already exists in server. Run id(s): {9034977}
[2018-04-11 21:46:44] Error in run 589: Run already exists in server. Run id(s): {9034916}
[2018-04-11 21:46:44] Error in run 591: Run already exists in server. Run id(s): {9034996}
[2018-04-11 21:46:44] Started run 597 on task 146197, dataset 'dna'.
[2018-04-11 21:46:44] Started run 598 on task 146197, dataset 'dna'.
[2018-04-11 21:46:44] Started run 599 on task 146197, dataset 'dna'.
[2018-04-11 21:46:44] Error in run 592: Run already exists in server. Run id(s): {9035004}
[2018-04-11 21:46:44] Started run 600 on task 146197, dataset 'dna'.
[2018-04-11 21:46:46] Error in run 593: Run already exists in server. Run id(s): {9034921}
[2018-04-11 21:46:46] Started run 601 on task 146197, dataset 'dna'.
[2018-04-11 21:46:48] Error in run 595: Run already exists in server. Run id(s): {9035067}
[2018-04-11 21:46:48] Error in run 596: Run already exists in server. Run id(s): {9035051}
[2018-04-11 21:46:48] Error in run 594: Run already exists in server. Run id(s): {9034939}
[2018-04-11 21:46:48] Started run 602 on task 146197, dataset 'dna'.
[2018-04-11 21:46:48] Started run 603 on task 146197, dataset 'dna'.
[2018-04-11 21:46:48] Started run 604 on task 146197, dataset 'dna'.
[2018-04-11 21:46:48] Error in run 598: Run already exists in server. Run id(s): {9035084}
[2018-04-11 21:46:48] Error in run 597: Run already exists in server. Run id(s): {9035049}
[2018-04-11 21:46:48] Error in run 599: Run already exists in server. Run id(s): {9035011}
[2018-04-11 21:46:48] Started run 605 on task 146197, dataset 'dna'.
[2018-04-11 21:46:48] Started run 606 on task 146197, dataset 'dna'.
[2018-04-11 21:46:48] Started run 607 on task 146197, dataset 'dna'.
[2018-04-11 21:46:49] Error in run 600: Run already exists in server. Run id(s): {9035118}
[2018-04-11 21:46:49] Started run 608 on task 146197, dataset 'dna'.
[2018-04-11 21:46:50] Error in run 601: Run already exists in server. Run id(s): {9035134}
[2018-04-11 21:46:50] Started run 609 on task 146197, dataset 'dna'.
[2018-04-11 21:46:52] Error in run 602: Run already exists in server. Run id(s): {9035126}
[2018-04-11 21:46:52] Error in run 603: Run already exists in server. Run id(s): {9035146}
[2018-04-11 21:46:52] Error in run 604: Run already exists in server. Run id(s): {9035221}
[2018-04-11 21:46:52] Started run 610 on task 146197, dataset 'dna'.
[2018-04-11 21:46:52] Started run 611 on task 146197, dataset 'dna'.
[2018-04-11 21:46:52] Started run 612 on task 146197, dataset 'dna'.
[2018-04-11 21:46:53] Error in run 605: Run already exists in server. Run id(s): {9035152}
[2018-04-11 21:46:53] Error in run 607: Run already exists in server. Run id(s): {9035235}
[2018-04-11 21:46:53] Error in run 606: Run already exists in server. Run id(s): {9035240}
[2018-04-11 21:46:53] Started run 613 on task 146197, dataset 'dna'.
[2018-04-11 21:46:53] Started run 614 on task 146197, dataset 'dna'.
[2018-04-11 21:46:53] Started run 615 on task 146197, dataset 'dna'.
[2018-04-11 21:46:54] Error in run 608: Run already exists in server. Run id(s): {9035278}
[2018-04-11 21:46:54] Started run 616 on task 146197, dataset 'dna'.
[2018-04-11 21:46:55] Error in run 609: Run already exists in server. Run id(s): {9035287}
[2018-04-11 21:46:55] Started run 617 on task 146197, dataset 'dna'.
[2018-04-11 21:46:57] Error in run 612: Run already exists in server. Run id(s): {9035325}
[2018-04-11 21:46:57] Error in run 611: Run already exists in server. Run id(s): {9035317}
[2018-04-11 21:46:57] Error in run 610: Run already exists in server. Run id(s): {9035301}
[2018-04-11 21:46:57] Started run 618 on task 146197, dataset 'dna'.
[2018-04-11 21:46:57] Started run 619 on task 146197, dataset 'dna'.
[2018-04-11 21:46:57] Started run 620 on task 146197, dataset 'dna'.
[2018-04-11 21:46:58] Error in run 615: Run already exists in server. Run id(s): {9035366}
[2018-04-11 21:46:58] Error in run 614: Run already exists in server. Run id(s): {9035351}
[2018-04-11 21:46:58] Error in run 613: Run already exists in server. Run id(s): {9035281}
[2018-04-11 21:46:58] Started run 621 on task 146197, dataset 'dna'.
[2018-04-11 21:46:58] Started run 623 on task 146197, dataset 'dna'.
[2018-04-11 21:46:58] Started run 622 on task 146197, dataset 'dna'.
[2018-04-11 21:46:58] Error in run 616: Run already exists in server. Run id(s): {9035413}
[2018-04-11 21:46:58] Started run 624 on task 146197, dataset 'dna'.
[2018-04-11 21:46:59] Error in run 617: Run already exists in server. Run id(s): {9035420}
[2018-04-11 21:46:59] Started run 625 on task 146197, dataset 'dna'.
[2018-04-11 21:47:01] Error in run 618: Run already exists in server. Run id(s): {9035397}
[2018-04-11 21:47:01] Started run 626 on task 146197, dataset 'dna'.
[2018-04-11 21:47:02] Error in run 619: Run already exists in server. Run id(s): {9035433}
[2018-04-11 21:47:02] Started run 627 on task 146197, dataset 'dna'.
[2018-04-11 21:47:02] Error in run 620: Run already exists in server. Run id(s): {9035447}
[2018-04-11 21:47:02] Started run 628 on task 146197, dataset 'dna'.
[2018-04-11 21:47:02] Error in run 621: Run already exists in server. Run id(s): {9035451}
[2018-04-11 21:47:02] Started run 629 on task 146197, dataset 'dna'.
[2018-04-11 21:47:02] Error in run 622: Run already exists in server. Run id(s): {9035488}
[2018-04-11 21:47:02] Started run 630 on task 146197, dataset 'dna'.
[2018-04-11 21:47:02] Error in run 623: Run already exists in server. Run id(s): {9035497}
[2018-04-11 21:47:02] Started run 631 on task 146197, dataset 'dna'.
[2018-04-11 21:47:03] Error in run 624: Run already exists in server. Run id(s): {9035535}
[2018-04-11 21:47:03] Started run 632 on task 146197, dataset 'dna'.
[2018-04-11 21:47:04] Error in run 625: Run already exists in server. Run id(s): {9035478}
[2018-04-11 21:47:04] Started run 633 on task 146197, dataset 'dna'.
[2018-04-11 21:47:06] Error in run 626: Run already exists in server. Run id(s): {9035560}
[2018-04-11 21:47:06] Started run 634 on task 146197, dataset 'dna'.
[2018-04-11 21:47:06] Error in run 628: Run already exists in server. Run id(s): {9035585}
[2018-04-11 21:47:06] Error in run 627: Run already exists in server. Run id(s): {9035550}
[2018-04-11 21:47:06] Started run 635 on task 146197, dataset 'dna'.
[2018-04-11 21:47:06] Started run 636 on task 146197, dataset 'dna'.
[2018-04-11 21:47:07] Error in run 629: Run already exists in server. Run id(s): {9035596}
[2018-04-11 21:47:07] Started run 637 on task 146197, dataset 'dna'.
[2018-04-11 21:47:07] Error in run 630: Run already exists in server. Run id(s): {9035616}
[2018-04-11 21:47:07] Started run 638 on task 146197, dataset 'dna'.
[2018-04-11 21:47:07] Error in run 631: Run already exists in server. Run id(s): {9035620}
[2018-04-11 21:47:07] Started run 639 on task 146197, dataset 'dna'.
[2018-04-11 21:47:08] Error in run 632: Run already exists in server. Run id(s): {9035612}
[2018-04-11 21:47:08] Started run 640 on task 146197, dataset 'dna'.
[2018-04-11 21:47:09] Error in run 633: Run already exists in server. Run id(s): {9035669}
[2018-04-11 21:47:09] Started run 641 on task 146197, dataset 'dna'.
[2018-04-11 21:47:10] Error in run 634: Run already exists in server. Run id(s): {9035683}
[2018-04-11 21:47:10] Started run 642 on task 146197, dataset 'dna'.
[2018-04-11 21:47:11] Error in run 635: Run already exists in server. Run id(s): {9035697}
[2018-04-11 21:47:11] Started run 643 on task 146197, dataset 'dna'.
[2018-04-11 21:47:11] Error in run 636: Run already exists in server. Run id(s): {9035695}
[2018-04-11 21:47:11] Started run 644 on task 146197, dataset 'dna'.
[2018-04-11 21:47:11] Error in run 637: Run already exists in server. Run id(s): {9035680}
[2018-04-11 21:47:11] Started run 645 on task 146197, dataset 'dna'.
[2018-04-11 21:47:11] Error in run 638: Run already exists in server. Run id(s): {9035725}
[2018-04-11 21:47:11] Started run 646 on task 146197, dataset 'dna'.
[2018-04-11 21:47:12] Error in run 639: Run already exists in server. Run id(s): {9035708}
[2018-04-11 21:47:12] Started run 647 on task 146197, dataset 'dna'.
[2018-04-11 21:47:13] Error in run 640: Run already exists in server. Run id(s): {9035741}
[2018-04-11 21:47:13] Started run 648 on task 146197, dataset 'dna'.
[2018-04-11 21:47:13] Error in run 641: Run already exists in server. Run id(s): {9035779}
[2018-04-11 21:47:13] Started run 649 on task 146197, dataset 'dna'.
[2018-04-11 21:47:15] Error in run 642: Run already exists in server. Run id(s): {9035723}
[2018-04-11 21:47:15] Started run 650 on task 146197, dataset 'dna'.
[2018-04-11 21:47:15] Error in run 643: Run already exists in server. Run id(s): {9035763}
[2018-04-11 21:47:15] Started run 651 on task 146197, dataset 'dna'.
[2018-04-11 21:47:16] Error in run 645: Run already exists in server. Run id(s): {9035769}
[2018-04-11 21:47:16] Error in run 644: Run already exists in server. Run id(s): {9035746}
[2018-04-11 21:47:16] Started run 652 on task 146197, dataset 'dna'.
[2018-04-11 21:47:16] Error in run 646: Run already exists in server. Run id(s): {9035805}
[2018-04-11 21:47:16] Started run 653 on task 146197, dataset 'dna'.
[2018-04-11 21:47:16] Started run 654 on task 146197, dataset 'dna'.
[2018-04-11 21:47:16] Error in run 647: Run already exists in server. Run id(s): {9035797}
[2018-04-11 21:47:16] Started run 655 on task 146197, dataset 'dna'.
[2018-04-11 21:47:17] Error in run 648: Run already exists in server. Run id(s): {9035788}
[2018-04-11 21:47:17] Started run 656 on task 146197, dataset 'dna'.
[2018-04-11 21:47:18] Error in run 649: Run already exists in server. Run id(s): {9035849}
[2018-04-11 21:47:18] Started run 657 on task 146197, dataset 'dna'.
[2018-04-11 21:47:20] Error in run 650: Run already exists in server. Run id(s): {9035855}
[2018-04-11 21:47:20] Started run 658 on task 146197, dataset 'dna'.
[2018-04-11 21:47:20] Error in run 651: Run already exists in server. Run id(s): {9035808}
[2018-04-11 21:47:20] Started run 659 on task 146197, dataset 'dna'.
[2018-04-11 21:47:20] Error in run 652: Run already exists in server. Run id(s): {9035859}
[2018-04-11 21:47:20] Started run 660 on task 146197, dataset 'dna'.
[2018-04-11 21:47:20] Error in run 653: Run already exists in server. Run id(s): {9035870}
[2018-04-11 21:47:20] Error in run 654: Run already exists in server. Run id(s): {9035872}
[2018-04-11 21:47:20] Started run 661 on task 146197, dataset 'dna'.
[2018-04-11 21:47:20] Started run 662 on task 146197, dataset 'dna'.
[2018-04-11 21:47:21] Error in run 655: Run already exists in server. Run id(s): {9035883}
[2018-04-11 21:47:21] Started run 663 on task 146197, dataset 'dna'.
[2018-04-11 21:47:22] Error in run 656: Run already exists in server. Run id(s): {9035914}
[2018-04-11 21:47:22] Started run 664 on task 146197, dataset 'dna'.
[2018-04-11 21:47:22] Error in run 657: Run already exists in server. Run id(s): {9035863}
[2018-04-11 21:47:22] Started run 665 on task 146197, dataset 'dna'.
[2018-04-11 21:47:24] Error in run 658: Run already exists in server. Run id(s): {9035930}
[2018-04-11 21:47:24] Error in run 659: Run already exists in server. Run id(s): {9035906}
[2018-04-11 21:47:24] Started run 666 on task 146197, dataset 'dna'.
[2018-04-11 21:47:24] Started run 667 on task 146197, dataset 'dna'.
[2018-04-11 21:47:25] Error in run 660: Run already exists in server. Run id(s): {9035973}
[2018-04-11 21:47:25] Started run 668 on task 146197, dataset 'dna'.
[2018-04-11 21:47:25] Error in run 661: Run already exists in server. Run id(s): {9035958}
[2018-04-11 21:47:25] Error in run 662: Run already exists in server. Run id(s): {9035974}
[2018-04-11 21:47:25] Error in run 663: Run already exists in server. Run id(s): {9035970}
[2018-04-11 21:47:25] Started run 669 on task 146197, dataset 'dna'.
[2018-04-11 21:47:25] Started run 670 on task 146197, dataset 'dna'.
[2018-04-11 21:47:25] Started run 671 on task 146197, dataset 'dna'.
[2018-04-11 21:47:26] Error in run 664: Run already exists in server. Run id(s): {9035988}
[2018-04-11 21:47:26] Started run 672 on task 146197, dataset 'dna'.
[2018-04-11 21:47:27] Error in run 665: Run already exists in server. Run id(s): {9035942}
[2018-04-11 21:47:27] Started run 673 on task 146197, dataset 'dna'.
[2018-04-11 21:47:29] Error in run 667: Run already exists in server. Run id(s): {9036026}
[2018-04-11 21:47:29] Error in run 666: Run already exists in server. Run id(s): {9036012}
[2018-04-11 21:47:29] Started run 674 on task 146197, dataset 'dna'.
[2018-04-11 21:47:29] Started run 675 on task 146197, dataset 'dna'.
[2018-04-11 21:47:29] Error in run 668: Run already exists in server. Run id(s): {9036048}
[2018-04-11 21:47:29] Started run 676 on task 146197, dataset 'dna'.
[2018-04-11 21:47:30] Error in run 669: Run already exists in server. Run id(s): {9036070}
[2018-04-11 21:47:30] Started run 677 on task 146197, dataset 'dna'.
[2018-04-11 21:47:30] Error in run 671: Run already exists in server. Run id(s): {9036078}
[2018-04-11 21:47:30] Error in run 670: Run already exists in server. Run id(s): {9036055}
[2018-04-11 21:47:30] Started run 678 on task 146197, dataset 'dna'.
[2018-04-11 21:47:30] Started run 679 on task 146197, dataset 'dna'.
[2018-04-11 21:47:31] Error in run 672: Run already exists in server. Run id(s): {9036080}
[2018-04-11 21:47:31] Started run 680 on task 146197, dataset 'dna'.
[2018-04-11 21:47:31] Error in run 673: Run already exists in server. Run id(s): {9036039}
[2018-04-11 21:47:31] Started run 681 on task 146197, dataset 'dna'.
[2018-04-11 21:47:34] Error in run 675: Run already exists in server. Run id(s): {9036102}
[2018-04-11 21:47:34] Error in run 674: Run already exists in server. Run id(s): {9036109}
[2018-04-11 21:47:34] Error in run 676: Run already exists in server. Run id(s): {9036133}
[2018-04-11 21:47:34] Started run 682 on task 146197, dataset 'dna'.
[2018-04-11 21:47:34] Started run 683 on task 146197, dataset 'dna'.
[2018-04-11 21:47:34] Started run 684 on task 146197, dataset 'dna'.
[2018-04-11 21:47:34] Error in run 677: Run already exists in server. Run id(s): {9036111}
[2018-04-11 21:47:34] Started run 685 on task 146197, dataset 'dna'.
[2018-04-11 21:47:34] Error in run 679: Run already exists in server. Run id(s): {9036129}
[2018-04-11 21:47:35] Error in run 678: Run already exists in server. Run id(s): {9036132}
[2018-04-11 21:47:34] Started run 686 on task 146197, dataset 'dna'.
[2018-04-11 21:47:35] Started run 687 on task 146197, dataset 'dna'.
[2018-04-11 21:47:35] Error in run 680: Run already exists in server. Run id(s): {9036150}
[2018-04-11 21:47:35] Started run 688 on task 146197, dataset 'dna'.
[2018-04-11 21:47:36] Error in run 681: Run already exists in server. Run id(s): {9036143}
[2018-04-11 21:47:36] Started run 689 on task 146197, dataset 'dna'.
[2018-04-11 21:47:38] Error in run 684: Run already exists in server. Run id(s): {9036222}
[2018-04-11 21:47:38] Error in run 683: Run already exists in server. Run id(s): {9036167}
[2018-04-11 21:47:38] Error in run 682: Run already exists in server. Run id(s): {9036209}
[2018-04-11 21:47:38] Started run 690 on task 146197, dataset 'dna'.
[2018-04-11 21:47:38] Started run 691 on task 146197, dataset 'dna'.
[2018-04-11 21:47:38] Started run 692 on task 146197, dataset 'dna'.
[2018-04-11 21:47:39] Error in run 685: Run already exists in server. Run id(s): {9036236}
[2018-04-11 21:47:39] Started run 693 on task 146197, dataset 'dna'.
[2018-04-11 21:47:39] Error in run 686: Run already exists in server. Run id(s): {9036245}
[2018-04-11 21:47:39] Started run 694 on task 146197, dataset 'dna'.
[2018-04-11 21:47:39] Error in run 687: Run already exists in server. Run id(s): {9036220}
[2018-04-11 21:47:39] Started run 695 on task 146197, dataset 'dna'.
[2018-04-11 21:47:40] Error in run 688: Run already exists in server. Run id(s): {9036196}
[2018-04-11 21:47:40] Started run 696 on task 146197, dataset 'dna'.
[2018-04-11 21:47:41] Error in run 689: Run already exists in server. Run id(s): {9036256}
[2018-04-11 21:47:41] Started run 697 on task 146197, dataset 'dna'.
[2018-04-11 21:47:43] Error in run 690: Run already exists in server. Run id(s): {9036277}
[2018-04-11 21:47:43] Started run 698 on task 146197, dataset 'dna'.
[2018-04-11 21:47:43] Error in run 692: Run already exists in server. Run id(s): {9036299}
[2018-04-11 21:47:43] Error in run 693: Run already exists in server. Run id(s): {9036312}
[2018-04-11 21:47:43] Error in run 691: Run already exists in server. Run id(s): {9036280}
[2018-04-11 21:47:43] Started run 699 on task 146197, dataset 'dna'.
[2018-04-11 21:47:43] Started run 701 on task 146197, dataset 'dna'.
[2018-04-11 21:47:43] Started run 700 on task 146197, dataset 'dna'.
[2018-04-11 21:47:43] Error in run 694: Run already exists in server. Run id(s): {9036330}
[2018-04-11 21:47:43] Started run 702 on task 146197, dataset 'dna'.
[2018-04-11 21:47:44] Error in run 695: Run already exists in server. Run id(s): {9036294}
[2018-04-11 21:47:44] Started run 703 on task 146197, dataset 'dna'.
[2018-04-11 21:47:45] Error in run 696: Run already exists in server. Run id(s): {9036287}
[2018-04-11 21:47:45] Started run 704 on task 146197, dataset 'dna'.
[2018-04-11 21:47:45] Error in run 697: Run already exists in server. Run id(s): {9036302}
[2018-04-11 21:47:45] Started run 705 on task 146197, dataset 'dna'.
[2018-04-11 21:47:47] Error in run 698: Run already exists in server. Run id(s): {9036389}
[2018-04-11 21:47:47] Started run 706 on task 146197, dataset 'dna'.
[2018-04-11 21:47:48] Error in run 699: Run already exists in server. Run id(s): {9036334}
[2018-04-11 21:47:48] Error in run 701: Run already exists in server. Run id(s): {9036410}
[2018-04-11 21:47:48] Error in run 700: Run already exists in server. Run id(s): {9036396}
[2018-04-11 21:47:48] Started run 707 on task 146197, dataset 'dna'.
[2018-04-11 21:47:48] Started run 709 on task 146197, dataset 'dna'.
[2018-04-11 21:47:48] Started run 708 on task 146197, dataset 'dna'.
[2018-04-11 21:47:48] Error in run 702: Run already exists in server. Run id(s): {9036406}
[2018-04-11 21:47:48] Started run 710 on task 146197, dataset 'dna'.
[2018-04-11 21:47:48] Error in run 703: Run already exists in server. Run id(s): {9036409}
[2018-04-11 21:47:48] Started run 711 on task 146197, dataset 'dna'.
[2018-04-11 21:47:49] Error in run 704: Run already exists in server. Run id(s): {9036414}
[2018-04-11 21:47:49] Started run 712 on task 146197, dataset 'dna'.
[2018-04-11 21:47:50] Error in run 705: Run already exists in server. Run id(s): {9036429}
[2018-04-11 21:47:50] Started run 713 on task 146197, dataset 'dna'.
[2018-04-11 21:47:52] Error in run 706: Run already exists in server. Run id(s): {9036432}
[2018-04-11 21:47:52] Started run 714 on task 146197, dataset 'dna'.
[2018-04-11 21:47:52] Error in run 707: Run already exists in server. Run id(s): {9036448}
[2018-04-11 21:47:52] Started run 715 on task 146197, dataset 'dna'.
[2018-04-11 21:47:53] Error in run 708: Run already exists in server. Run id(s): {9036467}
[2018-04-11 21:47:53] Error in run 711: Run already exists in server. Run id(s): {9036508}
[2018-04-11 21:47:53] Error in run 710: Run already exists in server. Run id(s): {9036502}
[2018-04-11 21:47:53] Error in run 709: Run already exists in server. Run id(s): {9036498}
[2018-04-11 21:47:53] Started run 716 on task 146197, dataset 'dna'.
[2018-04-11 21:47:53] Started run 717 on task 146197, dataset 'dna'.
[2018-04-11 21:47:53] Started run 718 on task 146197, dataset 'dna'.
[2018-04-11 21:47:53] Started run 719 on task 146197, dataset 'dna'.
[2018-04-11 21:47:54] Error in run 712: Run already exists in server. Run id(s): {9036446}
[2018-04-11 21:47:54] Started run 720 on task 146197, dataset 'dna'.
[2018-04-11 21:47:54] Error in run 713: Run already exists in server. Run id(s): {9036506}
[2018-04-11 21:47:54] Started run 721 on task 146197, dataset 'dna'.
[2018-04-11 21:47:56] Error in run 714: Run already exists in server. Run id(s): {9036536}
[2018-04-11 21:47:56] Started run 722 on task 146197, dataset 'dna'.
[2018-04-11 21:47:57] Error in run 715: Run already exists in server. Run id(s): {9036550}
[2018-04-11 21:47:57] Started run 723 on task 146197, dataset 'dna'.
[2018-04-11 21:47:57] Error in run 718: Run already exists in server. Run id(s): {9036572}
[2018-04-11 21:47:57] Error in run 717: Run already exists in server. Run id(s): {9036568}
[2018-04-11 21:47:57] Error in run 719: Run already exists in server. Run id(s): {9036583}
[2018-04-11 21:47:57] Error in run 716: Run already exists in server. Run id(s): {9036543}
[2018-04-11 21:47:57] Started run 724 on task 146197, dataset 'dna'.
[2018-04-11 21:47:57] Started run 725 on task 146197, dataset 'dna'.
[2018-04-11 21:47:57] Started run 727 on task 146197, dataset 'dna'.
[2018-04-11 21:47:57] Started run 726 on task 146197, dataset 'dna'.
[2018-04-11 21:47:58] Error in run 720: Run already exists in server. Run id(s): {9036602}
[2018-04-11 21:47:58] Started run 728 on task 146197, dataset 'dna'.
[2018-04-11 21:47:59] Error in run 721: Run already exists in server. Run id(s): {9036590}
[2018-04-11 21:47:59] Started run 729 on task 146197, dataset 'dna'.
[2018-04-11 21:48:01] Error in run 722: Run already exists in server. Run id(s): {9036627}
[2018-04-11 21:48:01] Started run 730 on task 146197, dataset 'dna'.
[2018-04-11 21:48:01] Error in run 723: Run already exists in server. Run id(s): {9036638}
[2018-04-11 21:48:01] Started run 731 on task 146197, dataset 'dna'.
[2018-04-11 21:48:02] Error in run 726: Run already exists in server. Run id(s): {9036660}
[2018-04-11 21:48:02] Error in run 727: Run already exists in server. Run id(s): {9036664}
[2018-04-11 21:48:02] Error in run 724: Run already exists in server. Run id(s): {9036595}
[2018-04-11 21:48:02] Error in run 725: Run already exists in server. Run id(s): {9036645}
[2018-04-11 21:48:02] Started run 732 on task 146197, dataset 'dna'.
[2018-04-11 21:48:02] Started run 733 on task 146197, dataset 'dna'.
[2018-04-11 21:48:02] Started run 734 on task 146197, dataset 'dna'.
[2018-04-11 21:48:02] Started run 735 on task 146197, dataset 'dna'.
[2018-04-11 21:48:03] Error in run 728: Run already exists in server. Run id(s): {9036643}
[2018-04-11 21:48:03] Started run 736 on task 146197, dataset 'dna'.
[2018-04-11 21:48:03] Error in run 729: Run already exists in server. Run id(s): {9036673}
[2018-04-11 21:48:03] Started run 737 on task 146197, dataset 'dna'.
[2018-04-11 21:48:06] Error in run 730: Run already exists in server. Run id(s): {9036682}
[2018-04-11 21:48:06] Error in run 731: Run already exists in server. Run id(s): {9036698}
[2018-04-11 21:48:06] Started run 738 on task 146197, dataset 'dna'.
[2018-04-11 21:48:06] Started run 739 on task 146197, dataset 'dna'.
[2018-04-11 21:48:07] Error in run 732: Run already exists in server. Run id(s): {9036661}
[2018-04-11 21:48:07] Error in run 734: Run already exists in server. Run id(s): {9036671}
[2018-04-11 21:48:07] Error in run 733: Run already exists in server. Run id(s): {9036703}
[2018-04-11 21:48:07] Error in run 735: Run already exists in server. Run id(s): {9036730}
[2018-04-11 21:48:07] Started run 740 on task 146197, dataset 'dna'.
[2018-04-11 21:48:07] Started run 741 on task 146197, dataset 'dna'.
[2018-04-11 21:48:07] Started run 742 on task 146197, dataset 'dna'.
[2018-04-11 21:48:07] Started run 743 on task 146197, dataset 'dna'.
[2018-04-11 21:48:07] Error in run 736: Run already exists in server. Run id(s): {9036696}
[2018-04-11 21:48:07] Started run 744 on task 146197, dataset 'dna'.
[2018-04-11 21:48:08] Error in run 737: Run already exists in server. Run id(s): {9036739}
[2018-04-11 21:48:08] Started run 745 on task 146197, dataset 'dna'.
[2018-04-11 21:48:10] Error in run 739: Run already exists in server. Run id(s): {9036731}
[2018-04-11 21:48:10] Started run 746 on task 146197, dataset 'dna'.
[2018-04-11 21:48:11] Error in run 738: Run already exists in server. Run id(s): {9036723}
[2018-04-11 21:48:11] Started run 747 on task 146197, dataset 'dna'.
[2018-04-11 21:48:11] Error in run 741: Run already exists in server. Run id(s): {9036760}
[2018-04-11 21:48:11] Started run 748 on task 146197, dataset 'dna'.
[2018-04-11 21:48:11] Error in run 743: Run already exists in server. Run id(s): {9036766}
[2018-04-11 21:48:11] Error in run 742: Run already exists in server. Run id(s): {9036724}
[2018-04-11 21:48:11] Error in run 740: Run already exists in server. Run id(s): {9036721}
[2018-04-11 21:48:11] Started run 749 on task 146197, dataset 'dna'.
[2018-04-11 21:48:11] Started run 750 on task 146197, dataset 'dna'.
[2018-04-11 21:48:11] Started run 751 on task 146197, dataset 'dna'.
[2018-04-11 21:48:12] Error in run 744: Run already exists in server. Run id(s): {9036778}
[2018-04-11 21:48:12] Started run 752 on task 146197, dataset 'dna'.
[2018-04-11 21:48:13] Error in run 745: Run already exists in server. Run id(s): {9036809}
[2018-04-11 21:48:13] Started run 753 on task 146197, dataset 'dna'.
[2018-04-11 21:48:15] Error in run 746: Run already exists in server. Run id(s): {9036790}
[2018-04-11 21:48:15] Error in run 747: Run already exists in server. Run id(s): {9036815}
[2018-04-11 21:48:15] Started run 754 on task 146197, dataset 'dna'.
[2018-04-11 21:48:15] Started run 755 on task 146197, dataset 'dna'.
[2018-04-11 21:48:16] Error in run 748: Run already exists in server. Run id(s): {9036799}
[2018-04-11 21:48:16] Started run 756 on task 146197, dataset 'dna'.
[2018-04-11 21:48:16] Error in run 751: Run already exists in server. Run id(s): {9036804}
[2018-04-11 21:48:16] Error in run 749: Run already exists in server. Run id(s): {9036822}
[2018-04-11 21:48:16] Error in run 750: Run already exists in server. Run id(s): {9036805}
[2018-04-11 21:48:16] Started run 757 on task 146197, dataset 'dna'.
[2018-04-11 21:48:16] Started run 758 on task 146197, dataset 'dna'.
[2018-04-11 21:48:16] Started run 759 on task 146197, dataset 'dna'.
[2018-04-11 21:48:17] Error in run 752: Run already exists in server. Run id(s): {9036858}
[2018-04-11 21:48:17] Started run 760 on task 146197, dataset 'dna'.
[2018-04-11 21:48:18] Error in run 753: Run already exists in server. Run id(s): {9036857}
[2018-04-11 21:48:18] Started run 761 on task 146197, dataset 'dna'.
[2018-04-11 21:48:20] Error in run 755: Run already exists in server. Run id(s): {9036879}
[2018-04-11 21:48:20] Started run 762 on task 146197, dataset 'dna'.
[2018-04-11 21:48:20] Error in run 754: Run already exists in server. Run id(s): {9036827}
[2018-04-11 21:48:20] Started run 763 on task 146197, dataset 'dna'.
[2018-04-11 21:48:20] Error in run 756: Run already exists in server. Run id(s): {9036868}
[2018-04-11 21:48:20] Started run 764 on task 146197, dataset 'dna'.
[2018-04-11 21:48:21] Error in run 759: Run already exists in server. Run id(s): {9036871}
[2018-04-11 21:48:21] Error in run 758: Run already exists in server. Run id(s): {9036888}
[2018-04-11 21:48:21] Started run 765 on task 146197, dataset 'dna'.
[2018-04-11 21:48:21] Error in run 757: Run already exists in server. Run id(s): {9036884}
[2018-04-11 21:48:21] Started run 767 on task 146197, dataset 'dna'.
[2018-04-11 21:48:21] Started run 766 on task 146197, dataset 'dna'.
[2018-04-11 21:48:21] Error in run 760: Run already exists in server. Run id(s): {9036901}
[2018-04-11 21:48:21] Started run 768 on task 146197, dataset 'dna'.
[2018-04-11 21:48:22] Error in run 761: Run already exists in server. Run id(s): {9036913}
[2018-04-11 21:48:22] Started run 769 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Error in run 763: Run already exists in server. Run id(s): {9036945}
[2018-04-11 21:48:25] Error in run 762: Run already exists in server. Run id(s): {9036935}
[2018-04-11 21:48:25] Started run 770 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Started run 771 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Error in run 764: Run already exists in server. Run id(s): {9036989, 9036950}
[2018-04-11 21:48:25] Started run 772 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Error in run 765: Run already exists in server. Run id(s): {9036906}
[2018-04-11 21:48:25] Error in run 767: Run already exists in server. Run id(s): {9036966}
[2018-04-11 21:48:25] Error in run 766: Run already exists in server. Run id(s): {9036976}
[2018-04-11 21:48:25] Started run 773 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Started run 774 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Started run 775 on task 146197, dataset 'dna'.
[2018-04-11 21:48:26] Error in run 768: Run already exists in server. Run id(s): {9036968}
[2018-04-11 21:48:26] Started run 776 on task 146197, dataset 'dna'.
[2018-04-11 21:48:27] Error in run 769: Run already exists in server. Run id(s): {9036981}
[2018-04-11 21:48:27] Started run 777 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Error in run 770: Run already exists in server. Run id(s): {9036974}
[2018-04-11 21:48:29] Error in run 771: Run already exists in server. Run id(s): {9036979}
[2018-04-11 21:48:29] Started run 778 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Error in run 772: Run already exists in server. Run id(s): {9037030}
[2018-04-11 21:48:29] Started run 780 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Started run 779 on task 146197, dataset 'dna'.
[2018-04-11 21:48:30] Error in run 774: Run already exists in server. Run id(s): {9037048}
[2018-04-11 21:48:30] Error in run 773: Run already exists in server. Run id(s): {9037041}
[2018-04-11 21:48:30] Error in run 775: Run already exists in server. Run id(s): {9037031}
[2018-04-11 21:48:30] Started run 781 on task 146197, dataset 'dna'.
[2018-04-11 21:48:30] Started run 782 on task 146197, dataset 'dna'.
[2018-04-11 21:48:30] Started run 783 on task 146197, dataset 'dna'.
[2018-04-11 21:48:31] Error in run 776: Run already exists in server. Run id(s): {9037055}
[2018-04-11 21:48:31] Started run 784 on task 146197, dataset 'dna'.
[2018-04-11 21:48:32] Error in run 777: Run already exists in server. Run id(s): {9037058}
[2018-04-11 21:48:32] Started run 785 on task 146197, dataset 'dna'.
[2018-04-11 21:48:34] Error in run 779: Run already exists in server. Run id(s): {9037071}
[2018-04-11 21:48:34] Error in run 778: Run already exists in server. Run id(s): {9037057}
[2018-04-11 21:48:34] Error in run 780: Run already exists in server. Run id(s): {9037116}
[2018-04-11 21:48:34] Started run 786 on task 146197, dataset 'dna'.
[2018-04-11 21:48:34] Started run 787 on task 146197, dataset 'dna'.
[2018-04-11 21:48:34] Started run 788 on task 146197, dataset 'dna'.
[2018-04-11 21:48:35] Error in run 783: Run already exists in server. Run id(s): {9037117}
[2018-04-11 21:48:35] Error in run 782: Run already exists in server. Run id(s): {9037111}
[2018-04-11 21:48:35] Started run 789 on task 146197, dataset 'dna'.
[2018-04-11 21:48:35] Error in run 781: Run already exists in server. Run id(s): {9037078}
[2018-04-11 21:48:35] Started run 790 on task 146197, dataset 'dna'.
[2018-04-11 21:48:35] Started run 791 on task 146197, dataset 'dna'.
[2018-04-11 21:48:35] Error in run 784: Run already exists in server. Run id(s): {9037083}
[2018-04-11 21:48:35] Started run 792 on task 146197, dataset 'dna'.
[2018-04-11 21:48:36] Error in run 785: Run already exists in server. Run id(s): {9037100}
[2018-04-11 21:48:36] Started run 793 on task 146197, dataset 'dna'.
[2018-04-11 21:48:39] Error in run 787: Run already exists in server. Run id(s): {9037154}
[2018-04-11 21:48:39] Error in run 788: Run already exists in server. Run id(s): {9037158, 9037175}
[2018-04-11 21:48:39] Error in run 786: Run already exists in server. Run id(s): {9037139}
[2018-04-11 21:48:39] Started run 794 on task 146197, dataset 'dna'.
[2018-04-11 21:48:39] Started run 796 on task 146197, dataset 'dna'.
[2018-04-11 21:48:39] Started run 795 on task 146197, dataset 'dna'.
[2018-04-11 21:48:39] Error in run 791: Run already exists in server. Run id(s): {9037173}
[2018-04-11 21:48:39] Error in run 790: Run already exists in server. Run id(s): {9037180}
[2018-04-11 21:48:39] Error in run 789: Run already exists in server. Run id(s): {9037115}
[2018-04-11 21:48:39] Started run 797 on task 146197, dataset 'dna'.
[2018-04-11 21:48:39] Started run 799 on task 146197, dataset 'dna'.
[2018-04-11 21:48:39] Started run 798 on task 146197, dataset 'dna'.
[2018-04-11 21:48:40] Error in run 792: Run already exists in server. Run id(s): {9037152}
[2018-04-11 21:48:40] Started run 800 on task 146197, dataset 'dna'.
[2018-04-11 21:48:41] Error in run 793: Run already exists in server. Run id(s): {9037199}
[2018-04-11 21:48:41] Started run 801 on task 146197, dataset 'dna'.
[2018-04-11 21:48:43] Error in run 796: Run already exists in server. Run id(s): {9037183}
[2018-04-11 21:48:43] Error in run 795: Run already exists in server. Run id(s): {9037224}
[2018-04-11 21:48:43] Error in run 794: Run already exists in server. Run id(s): {9037195}
[2018-04-11 21:48:43] Started run 802 on task 146197, dataset 'dna'.
[2018-04-11 21:48:43] Started run 803 on task 146197, dataset 'dna'.
[2018-04-11 21:48:43] Started run 804 on task 146197, dataset 'dna'.
[2018-04-11 21:48:44] Error in run 799: Run already exists in server. Run id(s): {9037260}
[2018-04-11 21:48:44] Error in run 797: Run already exists in server. Run id(s): {9037235}
[2018-04-11 21:48:44] Error in run 798: Run already exists in server. Run id(s): {9037252}
[2018-04-11 21:48:44] Started run 805 on task 146197, dataset 'dna'.
[2018-04-11 21:48:44] Started run 807 on task 146197, dataset 'dna'.
[2018-04-11 21:48:44] Started run 806 on task 146197, dataset 'dna'.
[2018-04-11 21:48:45] Error in run 800: Run already exists in server. Run id(s): {9037264}
[2018-04-11 21:48:45] Started run 808 on task 146197, dataset 'dna'.
[2018-04-11 21:48:46] Error in run 801: Run already exists in server. Run id(s): {9037272}
[2018-04-11 21:48:46] Started run 809 on task 146197, dataset 'dna'.
[2018-04-11 21:48:48] Error in run 802: Run already exists in server. Run id(s): {9037240}
[2018-04-11 21:48:48] Started run 810 on task 146197, dataset 'dna'.
[2018-04-11 21:48:48] Error in run 803: Run already exists in server. Run id(s): {9037292}
[2018-04-11 21:48:48] Error in run 804: Run already exists in server. Run id(s): {9037310}
[2018-04-11 21:48:48] Started run 811 on task 146197, dataset 'dna'.
[2018-04-11 21:48:48] Started run 812 on task 146197, dataset 'dna'.
[2018-04-11 21:48:49] Error in run 806: Run already exists in server. Run id(s): {9037320}
[2018-04-11 21:48:49] Error in run 807: Run already exists in server. Run id(s): {9037326}
[2018-04-11 21:48:49] Error in run 805: Run already exists in server. Run id(s): {9037317}
[2018-04-11 21:48:49] Started run 813 on task 146197, dataset 'dna'.
[2018-04-11 21:48:49] Started run 814 on task 146197, dataset 'dna'.
[2018-04-11 21:48:49] Started run 815 on task 146197, dataset 'dna'.
[2018-04-11 21:48:50] Error in run 808: Run already exists in server. Run id(s): {9037315}
[2018-04-11 21:48:50] Started run 816 on task 146197, dataset 'dna'.
[2018-04-11 21:48:50] Error in run 809: Run already exists in server. Run id(s): {9037327}
[2018-04-11 21:48:50] Started run 817 on task 146197, dataset 'dna'.
[2018-04-11 21:48:52] Error in run 810: Run already exists in server. Run id(s): {9037350}
[2018-04-11 21:48:52] Started run 818 on task 146197, dataset 'dna'.
[2018-04-11 21:48:53] Error in run 812: Run already exists in server. Run id(s): {9037386}
[2018-04-11 21:48:53] Error in run 811: Run already exists in server. Run id(s): {9037324}
[2018-04-11 21:48:53] Started run 819 on task 146197, dataset 'dna'.
[2018-04-11 21:48:53] Started run 820 on task 146197, dataset 'dna'.
[2018-04-11 21:48:53] Error in run 813: Run already exists in server. Run id(s): {9037394}
[2018-04-11 21:48:53] Error in run 814: Run already exists in server. Run id(s): {9037353}
[2018-04-11 21:48:53] Error in run 815: Run already exists in server. Run id(s): {9037398}
[2018-04-11 21:48:53] Started run 821 on task 146197, dataset 'dna'.
[2018-04-11 21:48:53] Started run 823 on task 146197, dataset 'dna'.
[2018-04-11 21:48:53] Started run 822 on task 146197, dataset 'dna'.
[2018-04-11 21:48:54] Error in run 816: Run already exists in server. Run id(s): {9037411}
[2018-04-11 21:48:54] Started run 824 on task 146197, dataset 'dna'.
[2018-04-11 21:48:55] Error in run 817: Run already exists in server. Run id(s): {9037410}
[2018-04-11 21:48:55] Started run 825 on task 146197, dataset 'dna'.
[2018-04-11 21:48:57] Error in run 818: Run already exists in server. Run id(s): {9037414}
[2018-04-11 21:48:57] Started run 826 on task 146197, dataset 'dna'.
[2018-04-11 21:48:57] Error in run 820: Run already exists in server. Run id(s): {9037387}
[2018-04-11 21:48:57] Started run 827 on task 146197, dataset 'dna'.
[2018-04-11 21:48:57] Error in run 819: Run already exists in server. Run id(s): {9037433}
[2018-04-11 21:48:57] Started run 828 on task 146197, dataset 'dna'.
[2018-04-11 21:48:58] Error in run 821: Run already exists in server. Run id(s): {9037461}
[2018-04-11 21:48:58] Started run 829 on task 146197, dataset 'dna'.
[2018-04-11 21:48:58] Error in run 822: Run already exists in server. Run id(s): {9037468}
[2018-04-11 21:48:58] Error in run 823: Run already exists in server. Run id(s): {9037482}
[2018-04-11 21:48:58] Started run 830 on task 146197, dataset 'dna'.
[2018-04-11 21:48:58] Started run 831 on task 146197, dataset 'dna'.
[2018-04-11 21:48:59] Error in run 824: Run already exists in server. Run id(s): {9037436}
[2018-04-11 21:48:59] Started run 832 on task 146197, dataset 'dna'.
[2018-04-11 21:49:00] Error in run 825: Run already exists in server. Run id(s): {9037444}
[2018-04-11 21:49:00] Started run 833 on task 146197, dataset 'dna'.
[2018-04-11 21:49:01] Error in run 826: Run already exists in server. Run id(s): {9037490}
[2018-04-11 21:49:01] Started run 834 on task 146197, dataset 'dna'.
[2018-04-11 21:49:02] Error in run 828: Run already exists in server. Run id(s): {9037494}
[2018-04-11 21:49:02] Started run 835 on task 146197, dataset 'dna'.
[2018-04-11 21:49:02] Error in run 827: Run already exists in server. Run id(s): {9037496}
[2018-04-11 21:49:02] Started run 836 on task 146197, dataset 'dna'.
[2018-04-11 21:49:02] Error in run 829: Run already exists in server. Run id(s): {9037517}
[2018-04-11 21:49:02] Started run 837 on task 146197, dataset 'dna'.
[2018-04-11 21:49:03] Error in run 830: Run already exists in server. Run id(s): {9037508}
[2018-04-11 21:49:03] Error in run 831: Run already exists in server. Run id(s): {9037527}
[2018-04-11 21:49:03] Started run 838 on task 146197, dataset 'dna'.
[2018-04-11 21:49:03] Started run 839 on task 146197, dataset 'dna'.
[2018-04-11 21:49:04] Error in run 832: Run already exists in server. Run id(s): {9037570}
[2018-04-11 21:49:04] Started run 840 on task 146197, dataset 'dna'.
[2018-04-11 21:49:04] Error in run 833: Run already exists in server. Run id(s): {9037580}
[2018-04-11 21:49:04] Started run 841 on task 146197, dataset 'dna'.
[2018-04-11 21:49:06] Error in run 834: Run already exists in server. Run id(s): {9037590}
[2018-04-11 21:49:06] Started run 842 on task 146197, dataset 'dna'.
[2018-04-11 21:49:07] Error in run 836: Run already exists in server. Run id(s): {9037593}
[2018-04-11 21:49:07] Error in run 835: Run already exists in server. Run id(s): {9037597}
[2018-04-11 21:49:07] Started run 843 on task 146197, dataset 'dna'.
[2018-04-11 21:49:07] Started run 844 on task 146197, dataset 'dna'.
[2018-04-11 21:49:07] Error in run 837: Run already exists in server. Run id(s): {9037607}
[2018-04-11 21:49:07] Started run 845 on task 146197, dataset 'dna'.
[2018-04-11 21:49:07] Error in run 839: Run already exists in server. Run id(s): {9037633}
[2018-04-11 21:49:07] Started run 846 on task 146197, dataset 'dna'.
[2018-04-11 21:49:08] Error in run 838: Run already exists in server. Run id(s): {9037582}
[2018-04-11 21:49:08] Started run 847 on task 146197, dataset 'dna'.
[2018-04-11 21:49:08] Error in run 840: Run already exists in server. Run id(s): {9037653}
[2018-04-11 21:49:08] Started run 848 on task 146197, dataset 'dna'.
[2018-04-11 21:49:09] Error in run 841: Run already exists in server. Run id(s): {9037661}
[2018-04-11 21:49:09] Started run 849 on task 146197, dataset 'dna'.
[2018-04-11 21:49:10] Error in run 842: Run already exists in server. Run id(s): {9037640}
[2018-04-11 21:49:10] Started run 850 on task 146197, dataset 'dna'.
[2018-04-11 21:49:11] Error in run 843: Run already exists in server. Run id(s): {9037670}
[2018-04-11 21:49:11] Error in run 845: Run already exists in server. Run id(s): {9037671}
[2018-04-11 21:49:11] Error in run 844: Run already exists in server. Run id(s): {9037658}
[2018-04-11 21:49:11] Started run 851 on task 146197, dataset 'dna'.
[2018-04-11 21:49:11] Started run 852 on task 146197, dataset 'dna'.
[2018-04-11 21:49:11] Started run 853 on task 146197, dataset 'dna'.
[2018-04-11 21:49:12] Error in run 846: Run already exists in server. Run id(s): {9037689}
[2018-04-11 21:49:12] Started run 854 on task 146197, dataset 'dna'.
[2018-04-11 21:49:12] Error in run 847: Run already exists in server. Run id(s): {9037728}
[2018-04-11 21:49:12] Started run 855 on task 146197, dataset 'dna'.
[2018-04-11 21:49:13] Error in run 848: Run already exists in server. Run id(s): {9037731}
[2018-04-11 21:49:13] Started run 856 on task 146197, dataset 'dna'.
[2018-04-11 21:49:14] Error in run 849: Run already exists in server. Run id(s): {9037710}
[2018-04-11 21:49:14] Started run 857 on task 146197, dataset 'dna'.
[2018-04-11 21:49:15] Error in run 850: Run already exists in server. Run id(s): {9037716}
[2018-04-11 21:49:15] Started run 858 on task 146197, dataset 'dna'.
[2018-04-11 21:49:16] Error in run 851: Run already exists in server. Run id(s): {9037760}
[2018-04-11 21:49:16] Error in run 852: Run already exists in server. Run id(s): {9037769}
[2018-04-11 21:49:16] Started run 859 on task 146197, dataset 'dna'.
[2018-04-11 21:49:16] Error in run 853: Run already exists in server. Run id(s): {9037772}
[2018-04-11 21:49:16] Started run 861 on task 146197, dataset 'dna'.
[2018-04-11 21:49:16] Started run 860 on task 146197, dataset 'dna'.
[2018-04-11 21:49:16] Error in run 854: Run already exists in server. Run id(s): {9037739}
[2018-04-11 21:49:16] Started run 862 on task 146197, dataset 'dna'.
[2018-04-11 21:49:17] Error in run 855: Run already exists in server. Run id(s): {9037744}
[2018-04-11 21:49:17] Started run 863 on task 146197, dataset 'dna'.
[2018-04-11 21:49:17] Error in run 856: Run already exists in server. Run id(s): {9037763}
[2018-04-11 21:49:17] Started run 864 on task 146197, dataset 'dna'.
[2018-04-11 21:49:18] Error in run 857: Run already exists in server. Run id(s): {9037788}
[2018-04-11 21:49:18] Started run 865 on task 146197, dataset 'dna'.
[2018-04-11 21:49:19] Error in run 858: Run already exists in server. Run id(s): {9037805}
[2018-04-11 21:49:19] Started run 866 on task 146197, dataset 'dna'.
[2018-04-11 21:49:21] Error in run 861: Run already exists in server. Run id(s): {9037803}
[2018-04-11 21:49:21] Error in run 859: Run already exists in server. Run id(s): {9037825}
[2018-04-11 21:49:21] Error in run 860: Run already exists in server. Run id(s): {9037829}
[2018-04-11 21:49:21] Started run 867 on task 146197, dataset 'dna'.
[2018-04-11 21:49:21] Started run 868 on task 146197, dataset 'dna'.
[2018-04-11 21:49:21] Started run 869 on task 146197, dataset 'dna'.
[2018-04-11 21:49:21] Error in run 862: Run already exists in server. Run id(s): {9037843}
[2018-04-11 21:49:21] Started run 870 on task 146197, dataset 'dna'.
[2018-04-11 21:49:22] Error in run 863: Run already exists in server. Run id(s): {9037833}
[2018-04-11 21:49:22] Started run 871 on task 146197, dataset 'dna'.
[2018-04-11 21:49:22] Error in run 864: Run already exists in server. Run id(s): {9037859}
[2018-04-11 21:49:22] Started run 872 on task 146197, dataset 'dna'.
[2018-04-11 21:49:23] Error in run 865: Run already exists in server. Run id(s): {9037873}
[2018-04-11 21:49:23] Started run 873 on task 146197, dataset 'dna'.
[2018-04-11 21:49:24] Error in run 866: Run already exists in server. Run id(s): {9037869}
[2018-04-11 21:49:24] Started run 874 on task 146197, dataset 'dna'.
[2018-04-11 21:49:25] Error in run 870: Run already exists in server. Run id(s): {9037908}
[2018-04-11 21:49:25] Error in run 867: Run already exists in server. Run id(s): {9037881}
[2018-04-11 21:49:25] Error in run 869: Run already exists in server. Run id(s): {9037911}
[2018-04-11 21:49:25] Error in run 868: Run already exists in server. Run id(s): {9037871}
[2018-04-11 21:49:25] Started run 875 on task 146197, dataset 'dna'.
[2018-04-11 21:49:25] Started run 876 on task 146197, dataset 'dna'.
[2018-04-11 21:49:25] Started run 877 on task 146197, dataset 'dna'.
[2018-04-11 21:49:25] Started run 878 on task 146197, dataset 'dna'.
[2018-04-11 21:49:26] Error in run 872: Run already exists in server. Run id(s): {9037887}
[2018-04-11 21:49:26] Error in run 871: Run already exists in server. Run id(s): {9037876}
[2018-04-11 21:49:26] Started run 879 on task 146197, dataset 'dna'.
[2018-04-11 21:49:26] Started run 880 on task 146197, dataset 'dna'.
[2018-04-11 21:49:28] Error in run 873: Run already exists in server. Run id(s): {9037952}
[2018-04-11 21:49:28] Started run 881 on task 146197, dataset 'dna'.
[2018-04-11 21:49:29] Error in run 874: Run already exists in server. Run id(s): {9037930}
[2018-04-11 21:49:29] Started run 882 on task 146197, dataset 'dna'.
[2018-04-11 21:49:30] Error in run 876: Run already exists in server. Run id(s): {9037960}
[2018-04-11 21:49:30] Error in run 878: Run already exists in server. Run id(s): {9037945}
[2018-04-11 21:49:30] Error in run 875: Run already exists in server. Run id(s): {9037950}
[2018-04-11 21:49:30] Error in run 877: Run already exists in server. Run id(s): {9037947}
[2018-04-11 21:49:30] Started run 883 on task 146197, dataset 'dna'.
[2018-04-11 21:49:30] Started run 886 on task 146197, dataset 'dna'.
[2018-04-11 21:49:30] Started run 884 on task 146197, dataset 'dna'.
[2018-04-11 21:49:30] Started run 885 on task 146197, dataset 'dna'.
[2018-04-11 21:49:31] Error in run 879: Run already exists in server. Run id(s): {9037990}
[2018-04-11 21:49:31] Error in run 880: Run already exists in server. Run id(s): {9037996}
[2018-04-11 21:49:31] Started run 887 on task 146197, dataset 'dna'.
[2018-04-11 21:49:31] Started run 888 on task 146197, dataset 'dna'.
[2018-04-11 21:49:33] Error in run 881: Run already exists in server. Run id(s): {9037995}
[2018-04-11 21:49:33] Started run 889 on task 146197, dataset 'dna'.
[2018-04-11 21:49:33] Error in run 882: Run already exists in server. Run id(s): {9037992}
[2018-04-11 21:49:33] Started run 890 on task 146197, dataset 'dna'.
[2018-04-11 21:49:35] Error in run 886: Run already exists in server. Run id(s): {9038068}
[2018-04-11 21:49:35] Error in run 885: Run already exists in server. Run id(s): {9038055}
[2018-04-11 21:49:35] Error in run 884: Run already exists in server. Run id(s): {9038056}
[2018-04-11 21:49:35] Error in run 883: Run already exists in server. Run id(s): {9038059}
[2018-04-11 21:49:35] Started run 891 on task 146197, dataset 'dna'.
[2018-04-11 21:49:35] Started run 892 on task 146197, dataset 'dna'.
[2018-04-11 21:49:35] Started run 894 on task 146197, dataset 'dna'.
[2018-04-11 21:49:35] Started run 893 on task 146197, dataset 'dna'.
[2018-04-11 21:49:36] Error in run 887: Run already exists in server. Run id(s): {9038084}
[2018-04-11 21:49:36] Error in run 888: Run already exists in server. Run id(s): {9038087}
[2018-04-11 21:49:36] Started run 895 on task 146197, dataset 'dna'.
[2018-04-11 21:49:36] Started run 896 on task 146197, dataset 'dna'.
[2018-04-11 21:49:37] Error in run 889: Run already exists in server. Run id(s): {9038057}
[2018-04-11 21:49:37] Started run 897 on task 146197, dataset 'dna'.
[2018-04-11 21:49:38] Error in run 890: Run already exists in server. Run id(s): {9038037}
[2018-04-11 21:49:38] Started run 898 on task 146197, dataset 'dna'.
[2018-04-11 21:49:40] Error in run 894: Run already exists in server. Run id(s): {9038134}
[2018-04-11 21:49:40] Error in run 893: Run already exists in server. Run id(s): {9038133}
[2018-04-11 21:49:40] Error in run 892: Run already exists in server. Run id(s): {9038132}
[2018-04-11 21:49:40] Error in run 891: Run already exists in server. Run id(s): {9038093}
[2018-04-11 21:49:40] Started run 899 on task 146197, dataset 'dna'.
[2018-04-11 21:49:40] Started run 901 on task 146197, dataset 'dna'.
[2018-04-11 21:49:40] Started run 902 on task 146197, dataset 'dna'.
[2018-04-11 21:49:40] Started run 900 on task 146197, dataset 'dna'.
[2018-04-11 21:49:40] Error in run 895: Run already exists in server. Run id(s): {9038135}
[2018-04-11 21:49:40] Error in run 896: Run already exists in server. Run id(s): {9038137}
[2018-04-11 21:49:40] Started run 903 on task 146197, dataset 'dna'.
[2018-04-11 21:49:40] Started run 904 on task 146197, dataset 'dna'.
[2018-04-11 21:49:42] Error in run 897: Run already exists in server. Run id(s): {9038158}
[2018-04-11 21:49:42] Started run 905 on task 146197, dataset 'dna'.
[2018-04-11 21:49:43] Error in run 898: Run already exists in server. Run id(s): {9038165}
[2018-04-11 21:49:43] Started run 906 on task 146197, dataset 'dna'.
[2018-04-11 21:49:44] Error in run 899: Run already exists in server. Run id(s): {9038167}
[2018-04-11 21:49:44] Started run 907 on task 146197, dataset 'dna'.
[2018-04-11 21:49:44] Error in run 901: Run already exists in server. Run id(s): {9038221}
[2018-04-11 21:49:44] Error in run 900: Run already exists in server. Run id(s): {9038197}
[2018-04-11 21:49:44] Error in run 902: Run already exists in server. Run id(s): {9038229}
[2018-04-11 21:49:44] Started run 908 on task 146197, dataset 'dna'.
[2018-04-11 21:49:44] Started run 909 on task 146197, dataset 'dna'.
[2018-04-11 21:49:44] Started run 910 on task 146197, dataset 'dna'.
[2018-04-11 21:49:45] Error in run 904: Run already exists in server. Run id(s): {9038170}
[2018-04-11 21:49:45] Error in run 903: Run already exists in server. Run id(s): {9038224}
[2018-04-11 21:49:45] Started run 911 on task 146197, dataset 'dna'.
[2018-04-11 21:49:45] Started run 912 on task 146197, dataset 'dna'.
[2018-04-11 21:49:47] Error in run 905: Run already exists in server. Run id(s): {9038237}
[2018-04-11 21:49:47] Started run 913 on task 146197, dataset 'dna'.
[2018-04-11 21:49:47] Error in run 906: Run already exists in server. Run id(s): {9038216}
[2018-04-11 21:49:47] Started run 914 on task 146197, dataset 'dna'.
[2018-04-11 21:49:49] Error in run 910: Run already exists in server. Run id(s): {9038305}
[2018-04-11 21:49:49] Error in run 908: Run already exists in server. Run id(s): {9038263}
[2018-04-11 21:49:49] Error in run 907: Run already exists in server. Run id(s): {9038246}
[2018-04-11 21:49:49] Error in run 909: Run already exists in server. Run id(s): {9038288}
[2018-04-11 21:49:49] Started run 915 on task 146197, dataset 'dna'.
[2018-04-11 21:49:49] Started run 916 on task 146197, dataset 'dna'.
[2018-04-11 21:49:49] Started run 917 on task 146197, dataset 'dna'.
[2018-04-11 21:49:49] Started run 918 on task 146197, dataset 'dna'.
[2018-04-11 21:49:50] Error in run 911: Run already exists in server. Run id(s): {9038311}
[2018-04-11 21:49:50] Error in run 912: Run already exists in server. Run id(s): {9038259}
[2018-04-11 21:49:50] Started run 919 on task 146197, dataset 'dna'.
[2018-04-11 21:49:50] Started run 920 on task 146197, dataset 'dna'.
[2018-04-11 21:49:51] Error in run 913: Run already exists in server. Run id(s): {9038312}
[2018-04-11 21:49:51] Started run 921 on task 146197, dataset 'dna'.
[2018-04-11 21:49:52] Error in run 914: Run already exists in server. Run id(s): {9038304}
[2018-04-11 21:49:52] Started run 922 on task 146197, dataset 'dna'.
[2018-04-11 21:49:54] Error in run 915: Run already exists in server. Run id(s): {9038319}
[2018-04-11 21:49:54] Error in run 917: Run already exists in server. Run id(s): {9038300}
[2018-04-11 21:49:54] Started run 923 on task 146197, dataset 'dna'.
[2018-04-11 21:49:54] Error in run 916: Run already exists in server. Run id(s): {9038340}
[2018-04-11 21:49:54] Error in run 918: Run already exists in server. Run id(s): {9038369}
[2018-04-11 21:49:54] Started run 925 on task 146197, dataset 'dna'.
[2018-04-11 21:49:54] Started run 924 on task 146197, dataset 'dna'.
[2018-04-11 21:49:54] Started run 926 on task 146197, dataset 'dna'.
[2018-04-11 21:49:54] Error in run 920: Run already exists in server. Run id(s): {9038389}
[2018-04-11 21:49:54] Error in run 919: Run already exists in server. Run id(s): {9038323}
[2018-04-11 21:49:54] Started run 927 on task 146197, dataset 'dna'.
[2018-04-11 21:49:54] Started run 928 on task 146197, dataset 'dna'.
[2018-04-11 21:49:56] Error in run 921: Run already exists in server. Run id(s): {9038335}
[2018-04-11 21:49:56] Started run 929 on task 146197, dataset 'dna'.
[2018-04-11 21:49:56] Error in run 922: Run already exists in server. Run id(s): {9038393}
[2018-04-11 21:49:56] Started run 930 on task 146197, dataset 'dna'.
[2018-04-11 21:49:58] Error in run 923: Run already exists in server. Run id(s): {9038343}
[2018-04-11 21:49:58] Error in run 926: Run already exists in server. Run id(s): {9038372}
[2018-04-11 21:49:58] Error in run 925: Run already exists in server. Run id(s): {9038409}
[2018-04-11 21:49:58] Error in run 924: Run already exists in server. Run id(s): {9038357}
[2018-04-11 21:49:58] Started run 931 on task 146197, dataset 'dna'.
[2018-04-11 21:49:58] Started run 934 on task 146197, dataset 'dna'.
[2018-04-11 21:49:58] Started run 932 on task 146197, dataset 'dna'.
[2018-04-11 21:49:58] Started run 933 on task 146197, dataset 'dna'.
[2018-04-11 21:49:59] Error in run 928: Run already exists in server. Run id(s): {9038382}
[2018-04-11 21:49:59] Error in run 927: Run already exists in server. Run id(s): {9038373}
[2018-04-11 21:49:59] Started run 935 on task 146197, dataset 'dna'.
[2018-04-11 21:49:59] Started run 936 on task 146197, dataset 'dna'.
[2018-04-11 21:50:01] Error in run 930: Run already exists in server. Run id(s): {9038444}
[2018-04-11 21:50:01] Error in run 929: Run already exists in server. Run id(s): {9038430}
[2018-04-11 21:50:01] Started run 937 on task 146197, dataset 'dna'.
[2018-04-11 21:50:01] Started run 938 on task 146197, dataset 'dna'.
[2018-04-11 21:50:03] Error in run 931: Run already exists in server. Run id(s): {9038429}
[2018-04-11 21:50:03] Started run 939 on task 146197, dataset 'dna'.
[2018-04-11 21:50:03] Error in run 932: Run already exists in server. Run id(s): {9038453}
[2018-04-11 21:50:03] Error in run 933: Run already exists in server. Run id(s): {9038438}
[2018-04-11 21:50:03] Started run 940 on task 146197, dataset 'dna'.
[2018-04-11 21:50:03] Error in run 934: Run already exists in server. Run id(s): {9038447}
[2018-04-11 21:50:03] Started run 941 on task 146197, dataset 'dna'.
[2018-04-11 21:50:03] Started run 942 on task 146197, dataset 'dna'.
[2018-04-11 21:50:04] Error in run 935: Run already exists in server. Run id(s): {9038464}
[2018-04-11 21:50:04] Error in run 936: Run already exists in server. Run id(s): {9038492}
[2018-04-11 21:50:04] Started run 943 on task 146197, dataset 'dna'.
[2018-04-11 21:50:04] Started run 944 on task 146197, dataset 'dna'.
[2018-04-11 21:50:05] Error in run 937: Run already exists in server. Run id(s): {9038515}
[2018-04-11 21:50:05] Error in run 938: Run already exists in server. Run id(s): {9038517}
[2018-04-11 21:50:05] Started run 945 on task 146197, dataset 'dna'.
[2018-04-11 21:50:05] Started run 946 on task 146197, dataset 'dna'.
[2018-04-11 21:50:07] Error in run 939: Run already exists in server. Run id(s): {9038499}
[2018-04-11 21:50:07] Started run 947 on task 146197, dataset 'dna'.
[2018-04-11 21:50:08] Error in run 941: Run already exists in server. Run id(s): {9038529}
[2018-04-11 21:50:08] Error in run 940: Run already exists in server. Run id(s): {9038472}
[2018-04-11 21:50:08] Started run 948 on task 146197, dataset 'dna'.
[2018-04-11 21:50:08] Error in run 942: Run already exists in server. Run id(s): {9038518}
[2018-04-11 21:50:08] Started run 949 on task 146197, dataset 'dna'.
[2018-04-11 21:50:08] Started run 950 on task 146197, dataset 'dna'.
[2018-04-11 21:50:08] Error in run 943: Run already exists in server. Run id(s): {9038557}
[2018-04-11 21:50:08] Error in run 944: Run already exists in server. Run id(s): {9038564}
[2018-04-11 21:50:08] Started run 951 on task 146197, dataset 'dna'.
[2018-04-11 21:50:08] Started run 952 on task 146197, dataset 'dna'.
[2018-04-11 21:50:10] Error in run 946: Run already exists in server. Run id(s): {9038533}
[2018-04-11 21:50:10] Error in run 945: Run already exists in server. Run id(s): {9038563}
[2018-04-11 21:50:10] Started run 953 on task 146197, dataset 'dna'.
[2018-04-11 21:50:10] Started run 954 on task 146197, dataset 'dna'.
[2018-04-11 21:50:12] Error in run 947: Run already exists in server. Run id(s): {9038581}
[2018-04-11 21:50:12] Started run 955 on task 146197, dataset 'dna'.
[2018-04-11 21:50:12] Error in run 949: Run already exists in server. Run id(s): {9038565}
[2018-04-11 21:50:12] Error in run 948: Run already exists in server. Run id(s): {9038552}
[2018-04-11 21:50:12] Error in run 950: Run already exists in server. Run id(s): {9038612}
[2018-04-11 21:50:12] Started run 956 on task 146197, dataset 'dna'.
[2018-04-11 21:50:12] Started run 957 on task 146197, dataset 'dna'.
[2018-04-11 21:50:12] Started run 958 on task 146197, dataset 'dna'.
[2018-04-11 21:50:13] Error in run 952: Run already exists in server. Run id(s): {9038641}
[2018-04-11 21:50:13] Error in run 951: Run already exists in server. Run id(s): {9038661}
[2018-04-11 21:50:13] Started run 959 on task 146197, dataset 'dna'.
[2018-04-11 21:50:13] Started run 960 on task 146197, dataset 'dna'.
[2018-04-11 21:50:15] Error in run 953: Run already exists in server. Run id(s): {9038629}
[2018-04-11 21:50:15] Error in run 954: Run already exists in server. Run id(s): {9038618}
[2018-04-11 21:50:15] Started run 961 on task 146197, dataset 'dna'.
[2018-04-11 21:50:15] Started run 962 on task 146197, dataset 'dna'.
[2018-04-11 21:50:16] Error in run 955: Run already exists in server. Run id(s): {9038604}
[2018-04-11 21:50:16] Started run 963 on task 146197, dataset 'dna'.
[2018-04-11 21:50:17] Error in run 957: Run already exists in server. Run id(s): {9038614}
[2018-04-11 21:50:17] Error in run 958: Run already exists in server. Run id(s): {9038662}
[2018-04-11 21:50:17] Error in run 956: Run already exists in server. Run id(s): {9038601}
[2018-04-11 21:50:17] Started run 964 on task 146197, dataset 'dna'.
[2018-04-11 21:50:17] Started run 966 on task 146197, dataset 'dna'.
[2018-04-11 21:50:17] Started run 965 on task 146197, dataset 'dna'.
[2018-04-11 21:50:18] Error in run 959: Run already exists in server. Run id(s): {9038733}
[2018-04-11 21:50:18] Error in run 960: Run already exists in server. Run id(s): {9038649}
[2018-04-11 21:50:18] Started run 967 on task 146197, dataset 'dna'.
[2018-04-11 21:50:18] Started run 968 on task 146197, dataset 'dna'.
[2018-04-11 21:50:19] Error in run 961: Run already exists in server. Run id(s): {9038720}
[2018-04-11 21:50:19] Error in run 962: Run already exists in server. Run id(s): {9038741}
[2018-04-11 21:50:19] Started run 969 on task 146197, dataset 'dna'.
[2018-04-11 21:50:19] Started run 970 on task 146197, dataset 'dna'.
[2018-04-11 21:50:21] Error in run 963: Run already exists in server. Run id(s): {9038732}
[2018-04-11 21:50:21] Started run 971 on task 146197, dataset 'dna'.
[2018-04-11 21:50:22] Error in run 964: Run already exists in server. Run id(s): {9038701}
[2018-04-11 21:50:22] Error in run 965: Run already exists in server. Run id(s): {9038756}
[2018-04-11 21:50:22] Error in run 966: Run already exists in server. Run id(s): {9038735}
[2018-04-11 21:50:22] Started run 972 on task 146197, dataset 'dna'.
[2018-04-11 21:50:22] Started run 973 on task 146197, dataset 'dna'.
[2018-04-11 21:50:22] Started run 974 on task 146197, dataset 'dna'.
[2018-04-11 21:50:23] Error in run 968: Run already exists in server. Run id(s): {9038803}
[2018-04-11 21:50:23] Error in run 967: Run already exists in server. Run id(s): {9038766}
[2018-04-11 21:50:23] Started run 975 on task 146197, dataset 'dna'.
[2018-04-11 21:50:23] Started run 976 on task 146197, dataset 'dna'.
[2018-04-11 21:50:24] Error in run 970: Run already exists in server. Run id(s): {9038824}
[2018-04-11 21:50:24] Error in run 969: Run already exists in server. Run id(s): {9038830}
[2018-04-11 21:50:24] Started run 977 on task 146197, dataset 'dna'.
[2018-04-11 21:50:24] Started run 978 on task 146197, dataset 'dna'.
[2018-04-11 21:50:26] Error in run 971: Run already exists in server. Run id(s): {9038782}
[2018-04-11 21:50:26] Started run 979 on task 146197, dataset 'dna'.
[2018-04-11 21:50:26] Error in run 973: Run already exists in server. Run id(s): {9038792}
[2018-04-11 21:50:26] Error in run 974: Run already exists in server. Run id(s): {9038825}
[2018-04-11 21:50:26] Error in run 972: Run already exists in server. Run id(s): {9038810}
[2018-04-11 21:50:26] Started run 980 on task 146197, dataset 'dna'.
[2018-04-11 21:50:26] Started run 981 on task 146197, dataset 'dna'.
[2018-04-11 21:50:26] Started run 982 on task 146197, dataset 'dna'.
[2018-04-11 21:50:27] Error in run 975: Run already exists in server. Run id(s): {9038880}
[2018-04-11 21:50:27] Started run 983 on task 146197, dataset 'dna'.
[2018-04-11 21:50:27] Error in run 976: Run already exists in server. Run id(s): {9038828}
[2018-04-11 21:50:27] Started run 984 on task 146197, dataset 'dna'.
[2018-04-11 21:50:29] Error in run 977: Run already exists in server. Run id(s): {9038876}
[2018-04-11 21:50:29] Error in run 978: Run already exists in server. Run id(s): {9038879}
[2018-04-11 21:50:29] Started run 985 on task 146197, dataset 'dna'.
[2018-04-11 21:50:29] Started run 986 on task 146197, dataset 'dna'.
[2018-04-11 21:50:30] Error in run 979: Run already exists in server. Run id(s): {9038872}
[2018-04-11 21:50:30] Started run 987 on task 146197, dataset 'dna'.
[2018-04-11 21:50:31] Error in run 980: Run already exists in server. Run id(s): {9038892}
[2018-04-11 21:50:31] Error in run 982: Run already exists in server. Run id(s): {9038865}
[2018-04-11 21:50:31] Started run 988 on task 146197, dataset 'dna'.
[2018-04-11 21:50:31] Error in run 981: Run already exists in server. Run id(s): {9038903}
[2018-04-11 21:50:31] Started run 990 on task 146197, dataset 'dna'.
[2018-04-11 21:50:31] Started run 989 on task 146197, dataset 'dna'.
[2018-04-11 21:50:32] Error in run 983: Run already exists in server. Run id(s): {9038890}
[2018-04-11 21:50:32] Error in run 984: Run already exists in server. Run id(s): {9038914}
[2018-04-11 21:50:32] Started run 991 on task 146197, dataset 'dna'.
[2018-04-11 21:50:32] Started run 992 on task 146197, dataset 'dna'.
[2018-04-11 21:50:33] Error in run 985: Run already exists in server. Run id(s): {9038946}
[2018-04-11 21:50:33] Error in run 986: Run already exists in server. Run id(s): {9038951}
[2018-04-11 21:50:33] Started run 993 on task 146197, dataset 'dna'.
[2018-04-11 21:50:33] Started run 994 on task 146197, dataset 'dna'.
[2018-04-11 21:50:35] Error in run 987: Run already exists in server. Run id(s): {9038959}
[2018-04-11 21:50:35] Started run 995 on task 146197, dataset 'dna'.
[2018-04-11 21:50:36] Error in run 989: Run already exists in server. Run id(s): {9038921}
[2018-04-11 21:50:36] Started run 996 on task 146197, dataset 'dna'.
[2018-04-11 21:50:36] Error in run 988: Run already exists in server. Run id(s): {9038960}
[2018-04-11 21:50:36] Error in run 990: Run already exists in server. Run id(s): {9038981}
[2018-04-11 21:50:36] Started run 997 on task 146197, dataset 'dna'.
[2018-04-11 21:50:36] Started run 998 on task 146197, dataset 'dna'.
[2018-04-11 21:50:37] Error in run 991: Run already exists in server. Run id(s): {9038991}
[2018-04-11 21:50:37] Error in run 992: Run already exists in server. Run id(s): {9038985}
[2018-04-11 21:50:37] Started run 999 on task 146197, dataset 'dna'.
[2018-04-11 21:50:37] Started run 1000 on task 146197, dataset 'dna'.
[2018-04-11 21:50:38] Error in run 994: Run already exists in server. Run id(s): {9039037}
[2018-04-11 21:50:38] Error in run 993: Run already exists in server. Run id(s): {9038974}
[2018-04-11 21:50:40] Error in run 995: Run already exists in server. Run id(s): {9039021}
[2018-04-11 21:50:40] Error in run 996: Run already exists in server. Run id(s): {9039004}
[2018-04-11 21:50:40] Error in run 998: Run already exists in server. Run id(s): {9039067}
[2018-04-11 21:50:40] Error in run 997: Run already exists in server. Run id(s): {9039050}
[2018-04-11 21:50:41] Error in run 999: Run already exists in server. Run id(s): {9039011}
[2018-04-11 21:50:41] Error in run 1000: Run already exists in server. Run id(s): {9039077}
