declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00027/certs"
declare -x AZ_BATCH_JOB_ID="random_forest"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_10-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00027"
declare -x AZ_BATCH_TASK_ID="task-00027"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00027/wd"
declare -x HOME="/mnt/batch/tasks/workitems/random_forest/job-1/task-00027/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/random_forest/job-1/task-00027/wd"
declare -x PWD="/mnt/batch/tasks/workitems/random_forest/job-1/task-00027/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 21:50:46] Results will not be logged locally.
[2018-04-11 21:50:46] Retrieving tasks...
[2018-04-11 21:50:46] Tasks will be retrieved based on provided task ids.
[2018-04-11 21:50:46] The following tasks were retrieved: [9985].
[2018-04-11 21:50:53] Downloaded task 9985.
[2018-04-11 21:50:54] Prepared pipelines.
[2018-04-11 21:50:54] Started run 1 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:54] Started run 3 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:54] Started run 2 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:54] Started run 4 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:54] Started run 5 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:54] Started run 6 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:54] Started run 7 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:54] Started run 8 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:58] Error in run 1: Run already exists in server. Run id(s): {9011868}
[2018-04-11 21:50:58] Started run 9 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:58] Error in run 3: Run already exists in server. Run id(s): {9027123}
[2018-04-11 21:50:58] Error in run 2: Run already exists in server. Run id(s): {9026962}
[2018-04-11 21:50:58] Started run 10 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:58] Started run 11 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:58] Error in run 4: Run already exists in server. Run id(s): {9027152}
[2018-04-11 21:50:58] Started run 12 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:58] Error in run 5: Run already exists in server. Run id(s): {9028453}
[2018-04-11 21:50:58] Started run 13 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:58] Error in run 6: Run already exists in server. Run id(s): {9029492}
[2018-04-11 21:50:58] Started run 14 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:58] Error in run 7: Run already exists in server. Run id(s): {9028549}
[2018-04-11 21:50:58] Started run 15 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:50:59] Error in run 8: Run already exists in server. Run id(s): {9026591}
[2018-04-11 21:50:59] Started run 16 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Error in run 11: Run already exists in server. Run id(s): {9027173}
[2018-04-11 21:51:03] Error in run 9: Run already exists in server. Run id(s): {9028457}
[2018-04-11 21:51:03] Error in run 10: Run already exists in server. Run id(s): {9027635}
[2018-04-11 21:51:03] Error in run 12: Run already exists in server. Run id(s): {9027562}
[2018-04-11 21:51:03] Started run 17 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Started run 19 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Started run 18 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Error in run 13: Run already exists in server. Run id(s): {9029277}
[2018-04-11 21:51:03] Started run 21 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Started run 20 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Error in run 14: Run already exists in server. Run id(s): {9027450}
[2018-04-11 21:51:03] Started run 22 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Error in run 15: Run already exists in server. Run id(s): {9028885}
[2018-04-11 21:51:03] Started run 23 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:03] Error in run 16: Run already exists in server. Run id(s): {9027981}
[2018-04-11 21:51:03] Started run 24 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:07] Error in run 17: Run already exists in server. Run id(s): {9029660}
[2018-04-11 21:51:07] Error in run 18: Run already exists in server. Run id(s): {9029438}
[2018-04-11 21:51:07] Error in run 21: Run already exists in server. Run id(s): {9028907}
[2018-04-11 21:51:07] Started run 25 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:07] Error in run 19: Run already exists in server. Run id(s): {9029147}
[2018-04-11 21:51:07] Started run 26 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:07] Started run 28 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:07] Started run 27 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:08] Error in run 20: Run already exists in server. Run id(s): {9012956}
[2018-04-11 21:51:08] Started run 29 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:08] Error in run 22: Run already exists in server. Run id(s): {9028762}
[2018-04-11 21:51:08] Started run 30 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:08] Error in run 23: Run already exists in server. Run id(s): {9029427}
[2018-04-11 21:51:08] Started run 31 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:08] Error in run 24: Run already exists in server. Run id(s): {9031031}
[2018-04-11 21:51:08] Started run 32 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:12] Error in run 25: Run already exists in server. Run id(s): {9030119}
[2018-04-11 21:51:12] Error in run 26: Run already exists in server. Run id(s): {9031160}
[2018-04-11 21:51:12] Started run 33 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:12] Error in run 28: Run already exists in server. Run id(s): {9031229}
[2018-04-11 21:51:12] Error in run 27: Run already exists in server. Run id(s): {9032411}
[2018-04-11 21:51:12] Started run 34 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:12] Started run 35 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:12] Started run 36 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:12] Error in run 29: Run already exists in server. Run id(s): {9031664}
[2018-04-11 21:51:12] Started run 37 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:12] Error in run 30: Run already exists in server. Run id(s): {9029989}
[2018-04-11 21:51:12] Started run 38 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:12] Error in run 31: Run already exists in server. Run id(s): {9029813}
[2018-04-11 21:51:12] Started run 39 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:13] Error in run 32: Run already exists in server. Run id(s): {9030354}
[2018-04-11 21:51:13] Started run 40 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Error in run 33: Run already exists in server. Run id(s): {9030407}
[2018-04-11 21:51:17] Error in run 34: Run already exists in server. Run id(s): {9030299}
[2018-04-11 21:51:17] Started run 41 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Error in run 35: Run already exists in server. Run id(s): {9033491}
[2018-04-11 21:51:17] Started run 42 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Error in run 36: Run already exists in server. Run id(s): {9031654}
[2018-04-11 21:51:17] Started run 44 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Started run 43 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Error in run 37: Run already exists in server. Run id(s): {9030758}
[2018-04-11 21:51:17] Started run 45 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Error in run 38: Run already exists in server. Run id(s): {9031930}
[2018-04-11 21:51:17] Started run 46 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Error in run 39: Run already exists in server. Run id(s): {9031127}
[2018-04-11 21:51:17] Started run 47 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:17] Error in run 40: Run already exists in server. Run id(s): {9031240}
[2018-04-11 21:51:17] Started run 48 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:21] Error in run 41: Run already exists in server. Run id(s): {9032017}
[2018-04-11 21:51:21] Error in run 46: Run already exists in server. Run id(s): {9032982}
[2018-04-11 21:51:21] Started run 49 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:21] Error in run 43: Run already exists in server. Run id(s): {9031942}
[2018-04-11 21:51:21] Error in run 44: Run already exists in server. Run id(s): {9032840}
[2018-04-11 21:51:21] Error in run 45: Run already exists in server. Run id(s): {9031781}
[2018-04-11 21:51:21] Error in run 42: Run already exists in server. Run id(s): {9032575}
[2018-04-11 21:51:21] Started run 50 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:21] Started run 54 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:21] Error in run 47: Run already exists in server. Run id(s): {9032630}
[2018-04-11 21:51:21] Started run 55 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:21] Started run 52 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:21] Started run 51 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:21] Started run 53 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:22] Error in run 48: Run already exists in server. Run id(s): {9032741}
[2018-04-11 21:51:22] Started run 56 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:26] Error in run 52: Run already exists in server. Run id(s): {9033753}
[2018-04-11 21:51:26] Error in run 51: Run already exists in server. Run id(s): {9033963}
[2018-04-11 21:51:26] Started run 57 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:26] Error in run 54: Run already exists in server. Run id(s): {9034461}
[2018-04-11 21:51:26] Error in run 53: Run already exists in server. Run id(s): {9033231}
[2018-04-11 21:51:26] Error in run 50: Run already exists in server. Run id(s): {9033239}
[2018-04-11 21:51:26] Error in run 49: Run already exists in server. Run id(s): {9033046}
[2018-04-11 21:51:26] Error in run 55: Run already exists in server. Run id(s): {9034792}
[2018-04-11 21:51:26] Started run 59 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:26] Started run 60 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:26] Started run 61 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:26] Started run 58 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:26] Started run 62 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:26] Started run 63 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:27] Error in run 56: Run already exists in server. Run id(s): {9033296}
[2018-04-11 21:51:27] Started run 64 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:30] Error in run 57: Run already exists in server. Run id(s): {9035310}
[2018-04-11 21:51:30] Started run 65 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:31] Error in run 63: Run already exists in server. Run id(s): {9035158}
[2018-04-11 21:51:31] Error in run 62: Run already exists in server. Run id(s): {9034414}
[2018-04-11 21:51:31] Error in run 58: Run already exists in server. Run id(s): {9034692}
[2018-04-11 21:51:31] Error in run 60: Run already exists in server. Run id(s): {9034627}
[2018-04-11 21:51:31] Started run 66 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:31] Error in run 59: Run already exists in server. Run id(s): {9033522}
[2018-04-11 21:51:31] Error in run 61: Run already exists in server. Run id(s): {9036052}
[2018-04-11 21:51:31] Started run 70 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:31] Started run 71 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:31] Started run 67 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:31] Started run 68 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:31] Started run 69 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:31] Error in run 64: Run already exists in server. Run id(s): {9034940}
[2018-04-11 21:51:31] Started run 72 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:35] Error in run 65: Run already exists in server. Run id(s): {9034666}
[2018-04-11 21:51:35] Started run 73 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:35] Error in run 67: Run already exists in server. Run id(s): {9035572}
[2018-04-11 21:51:35] Error in run 66: Run already exists in server. Run id(s): {9034891}
[2018-04-11 21:51:35] Error in run 69: Run already exists in server. Run id(s): {9036639}
[2018-04-11 21:51:35] Error in run 68: Run already exists in server. Run id(s): {9036459}
[2018-04-11 21:51:35] Error in run 71: Run already exists in server. Run id(s): {9035026}
[2018-04-11 21:51:35] Started run 74 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:35] Error in run 70: Run already exists in server. Run id(s): {9035273}
[2018-04-11 21:51:35] Started run 76 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:35] Started run 77 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:35] Started run 75 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:35] Started run 78 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:35] Started run 79 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:36] Error in run 72: Run already exists in server. Run id(s): {9035378}
[2018-04-11 21:51:36] Started run 80 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:39] Error in run 73: Run already exists in server. Run id(s): {9036289}
[2018-04-11 21:51:39] Started run 81 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:40] Error in run 74: Run already exists in server. Run id(s): {9035480}
[2018-04-11 21:51:40] Started run 82 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:40] Error in run 78: Run already exists in server. Run id(s): {9035878}
[2018-04-11 21:51:40] Error in run 75: Run already exists in server. Run id(s): {9035454}
[2018-04-11 21:51:40] Started run 83 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:40] Error in run 77: Run already exists in server. Run id(s): {9035579}
[2018-04-11 21:51:40] Error in run 76: Run already exists in server. Run id(s): {9035652, 9035701}
[2018-04-11 21:51:40] Error in run 79: Run already exists in server. Run id(s): {9036835}
[2018-04-11 21:51:40] Started run 85 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:40] Started run 87 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:40] Started run 86 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:40] Started run 84 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:41] Error in run 80: Run already exists in server. Run id(s): {9036630}
[2018-04-11 21:51:41] Started run 88 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:44] Error in run 81: Run already exists in server. Run id(s): {9036755}
[2018-04-11 21:51:44] Started run 89 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:44] Error in run 82: Run already exists in server. Run id(s): {9035980}
[2018-04-11 21:51:44] Started run 90 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:45] Error in run 87: Run already exists in server. Run id(s): {9037974}
[2018-04-11 21:51:45] Error in run 85: Run already exists in server. Run id(s): {9037309}
[2018-04-11 21:51:45] Error in run 86: Run already exists in server. Run id(s): {9037209}
[2018-04-11 21:51:45] Error in run 84: Run already exists in server. Run id(s): {9036843}
[2018-04-11 21:51:45] Started run 91 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:45] Started run 92 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:45] Error in run 83: Run already exists in server. Run id(s): {9036525}
[2018-04-11 21:51:45] Started run 95 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:45] Started run 93 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:45] Started run 94 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:45] Error in run 88: Run already exists in server. Run id(s): {9036887}
[2018-04-11 21:51:45] Started run 96 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:49] Error in run 89: Run already exists in server. Run id(s): {9038292}
[2018-04-11 21:51:49] Started run 97 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:49] Error in run 90: Run already exists in server. Run id(s): {9036924}
[2018-04-11 21:51:49] Started run 98 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:49] Error in run 95: Run already exists in server. Run id(s): {9037743}
[2018-04-11 21:51:49] Error in run 92: Run already exists in server. Run id(s): {9038122}
[2018-04-11 21:51:49] Error in run 93: Run already exists in server. Run id(s): {9036916}
[2018-04-11 21:51:49] Error in run 91: Run already exists in server. Run id(s): {9037425}
[2018-04-11 21:51:49] Error in run 94: Run already exists in server. Run id(s): {9037251}
[2018-04-11 21:51:49] Started run 99 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:49] Started run 103 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:49] Started run 100 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:49] Started run 101 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:49] Started run 102 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:50] Error in run 96: Run already exists in server. Run id(s): {9037979}
[2018-04-11 21:51:50] Started run 104 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:53] Error in run 98: Run already exists in server. Run id(s): {9038514}
[2018-04-11 21:51:53] Error in run 97: Run already exists in server. Run id(s): {9037560}
[2018-04-11 21:51:53] Started run 105 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:53] Started run 106 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:54] Error in run 100: Run already exists in server. Run id(s): {9037715}
[2018-04-11 21:51:54] Error in run 102: Run already exists in server. Run id(s): {9038385}
[2018-04-11 21:51:54] Error in run 101: Run already exists in server. Run id(s): {9038635}
[2018-04-11 21:51:54] Started run 107 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:54] Error in run 103: Run already exists in server. Run id(s): {9038503}
[2018-04-11 21:51:54] Error in run 99: Run already exists in server. Run id(s): {9037884}
[2018-04-11 21:51:54] Started run 109 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:54] Started run 110 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:54] Started run 111 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:54] Started run 108 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:54] Error in run 104: Run already exists in server. Run id(s): {9038737}
[2018-04-11 21:51:54] Started run 112 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:58] Error in run 106: Run already exists in server. Run id(s): {9038449}
[2018-04-11 21:51:58] Error in run 105: Run already exists in server. Run id(s): {9038762}
[2018-04-11 21:51:58] Started run 113 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:58] Started run 114 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:58] Error in run 107: Run already exists in server. Run id(s): {9038659}
[2018-04-11 21:51:59] Started run 115 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:59] Error in run 110: Run already exists in server. Run id(s): {9038558}
[2018-04-11 21:51:59] Error in run 108: Run already exists in server. Run id(s): {9039488}
[2018-04-11 21:51:59] Started run 116 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:59] Error in run 111: Run already exists in server. Run id(s): {9038634}
[2018-04-11 21:51:59] Error in run 109: Run already exists in server. Run id(s): {9038592}
[2018-04-11 21:51:59] Error in run 112: Run already exists in server. Run id(s): {9038936}
[2018-04-11 21:51:59] Started run 117 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:59] Started run 118 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:59] Started run 119 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:51:59] Started run 120 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:02] Error in run 113: Run already exists in server. Run id(s): {9038821}
[2018-04-11 21:52:02] Error in run 114: Run already exists in server. Run id(s): {9038691}
[2018-04-11 21:52:02] Started run 121 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:02] Started run 122 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:03] Error in run 115: Run already exists in server. Run id(s): {9038708}
[2018-04-11 21:52:03] Started run 123 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:03] Error in run 116: Run already exists in server. Run id(s): {9039046}
[2018-04-11 21:52:03] Started run 124 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:03] Error in run 118: Run already exists in server. Run id(s): {9038968}
[2018-04-11 21:52:03] Error in run 119: Run already exists in server. Run id(s): {9038927}
[2018-04-11 21:52:03] Error in run 117: Run already exists in server. Run id(s): {9038849}
[2018-04-11 21:52:03] Error in run 120: Run already exists in server. Run id(s): {9038937}
[2018-04-11 21:52:03] Started run 125 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:03] Started run 127 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:03] Started run 126 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:03] Started run 128 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:07] Error in run 121: Run already exists in server. Run id(s): {9039236}
[2018-04-11 21:52:07] Error in run 122: Run already exists in server. Run id(s): {9038992}
[2018-04-11 21:52:07] Started run 129 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:07] Started run 130 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:07] Error in run 123: Run already exists in server. Run id(s): {9039750}
[2018-04-11 21:52:07] Started run 131 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:08] Error in run 124: Run already exists in server. Run id(s): {9039171}
[2018-04-11 21:52:08] Started run 132 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:08] Error in run 126: Run already exists in server. Run id(s): {9039304}
[2018-04-11 21:52:08] Error in run 127: Run already exists in server. Run id(s): {9039063}
[2018-04-11 21:52:08] Started run 133 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:08] Error in run 125: Run already exists in server. Run id(s): {9039289}
[2018-04-11 21:52:08] Started run 135 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:08] Error in run 128: Run already exists in server. Run id(s): {9039220}
[2018-04-11 21:52:08] Started run 136 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:08] Started run 134 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:11] Error in run 129: Run already exists in server. Run id(s): {9040099}
[2018-04-11 21:52:11] Started run 137 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:11] Error in run 130: Run already exists in server. Run id(s): {9039683}
[2018-04-11 21:52:11] Started run 138 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:12] Error in run 131: Run already exists in server. Run id(s): {9039482}
[2018-04-11 21:52:12] Started run 139 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:12] Error in run 132: Run already exists in server. Run id(s): {9040411, 9040405}
[2018-04-11 21:52:12] Started run 140 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:13] Error in run 135: Run already exists in server. Run id(s): {9039596}
[2018-04-11 21:52:13] Error in run 134: Run already exists in server. Run id(s): {9039511}
[2018-04-11 21:52:13] Error in run 133: Run already exists in server. Run id(s): {9039628}
[2018-04-11 21:52:13] Error in run 136: Run already exists in server. Run id(s): {9039738}
[2018-04-11 21:52:13] Started run 141 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:13] Started run 142 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:13] Started run 143 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:13] Started run 144 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:16] Error in run 137: Run already exists in server. Run id(s): {9039589}
[2018-04-11 21:52:16] Error in run 138: Run already exists in server. Run id(s): {9040065}
[2018-04-11 21:52:16] Started run 145 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:16] Started run 146 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:17] Error in run 140: Run already exists in server. Run id(s): {9039839}
[2018-04-11 21:52:17] Started run 147 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:17] Error in run 139: Run already exists in server. Run id(s): {9039798}
[2018-04-11 21:52:17] Started run 148 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:17] Error in run 143: Run already exists in server. Run id(s): {9039776}
[2018-04-11 21:52:17] Error in run 142: Run already exists in server. Run id(s): {9039942}
[2018-04-11 21:52:17] Error in run 144: Run already exists in server. Run id(s): {9040287}
[2018-04-11 21:52:17] Error in run 141: Run already exists in server. Run id(s): {9039817}
[2018-04-11 21:52:17] Started run 149 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:17] Started run 151 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:17] Started run 150 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:17] Started run 152 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:21] Error in run 146: Run already exists in server. Run id(s): {9040100}
[2018-04-11 21:52:21] Started run 153 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:21] Error in run 145: Run already exists in server. Run id(s): {9040270}
[2018-04-11 21:52:21] Started run 154 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:21] Error in run 147: Run already exists in server. Run id(s): {9040235}
[2018-04-11 21:52:21] Error in run 148: Run already exists in server. Run id(s): {9040981}
[2018-04-11 21:52:21] Started run 155 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:21] Started run 156 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:22] Error in run 151: Run already exists in server. Run id(s): {9040481}
[2018-04-11 21:52:22] Error in run 150: Run already exists in server. Run id(s): {9041332}
[2018-04-11 21:52:22] Started run 157 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:22] Error in run 149: Run already exists in server. Run id(s): {9040454}
[2018-04-11 21:52:22] Started run 158 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:22] Error in run 152: Run already exists in server. Run id(s): {9040475}
[2018-04-11 21:52:22] Started run 160 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:22] Started run 159 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:25] Error in run 153: Run already exists in server. Run id(s): {9041462}
[2018-04-11 21:52:25] Error in run 154: Run already exists in server. Run id(s): {9040334}
[2018-04-11 21:52:25] Started run 161 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:25] Started run 162 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:26] Error in run 156: Run already exists in server. Run id(s): {9040489}
[2018-04-11 21:52:26] Started run 163 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:26] Error in run 155: Run already exists in server. Run id(s): {9040444}
[2018-04-11 21:52:26] Started run 164 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:27] Error in run 159: Run already exists in server. Run id(s): {9040670}
[2018-04-11 21:52:27] Error in run 157: Run already exists in server. Run id(s): {9040661}
[2018-04-11 21:52:27] Started run 165 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:27] Error in run 158: Run already exists in server. Run id(s): {9040582}
[2018-04-11 21:52:27] Error in run 160: Run already exists in server. Run id(s): {9040650}
[2018-04-11 21:52:27] Started run 166 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:27] Started run 167 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:27] Started run 168 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:30] Error in run 161: Run already exists in server. Run id(s): {9040812}
[2018-04-11 21:52:30] Started run 169 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:30] Error in run 162: Run already exists in server. Run id(s): {9041260}
[2018-04-11 21:52:30] Started run 170 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:31] Error in run 163: Run already exists in server. Run id(s): {9040994}
[2018-04-11 21:52:31] Started run 171 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:31] Error in run 164: Run already exists in server. Run id(s): {9040723}
[2018-04-11 21:52:31] Started run 172 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:32] Error in run 166: Run already exists in server. Run id(s): {9040763}
[2018-04-11 21:52:32] Error in run 168: Run already exists in server. Run id(s): {9041304}
[2018-04-11 21:52:32] Error in run 165: Run already exists in server. Run id(s): {9040750}
[2018-04-11 21:52:32] Error in run 167: Run already exists in server. Run id(s): {9041990}
[2018-04-11 21:52:32] Started run 173 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:32] Started run 174 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:32] Started run 175 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:32] Started run 176 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:34] Error in run 169: Run already exists in server. Run id(s): {9040880}
[2018-04-11 21:52:34] Started run 177 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:35] Error in run 170: Run already exists in server. Run id(s): {9041080}
[2018-04-11 21:52:35] Started run 178 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:35] Error in run 171: Run already exists in server. Run id(s): {9041223}
[2018-04-11 21:52:35] Started run 179 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:35] Error in run 172: Run already exists in server. Run id(s): {9041045}
[2018-04-11 21:52:35] Started run 180 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:36] Error in run 174: Run already exists in server. Run id(s): {9041935}
[2018-04-11 21:52:36] Error in run 173: Run already exists in server. Run id(s): {9041113}
[2018-04-11 21:52:36] Started run 181 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:36] Started run 182 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:36] Error in run 176: Run already exists in server. Run id(s): {9041683}
[2018-04-11 21:52:36] Error in run 175: Run already exists in server. Run id(s): {9041832}
[2018-04-11 21:52:36] Started run 183 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:36] Started run 184 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:39] Error in run 177: Run already exists in server. Run id(s): {9041629}
[2018-04-11 21:52:39] Started run 185 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:39] Error in run 178: Run already exists in server. Run id(s): {9041393}
[2018-04-11 21:52:39] Started run 186 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:40] Error in run 179: Run already exists in server. Run id(s): {9041420}
[2018-04-11 21:52:40] Started run 187 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:40] Error in run 180: Run already exists in server. Run id(s): {9041493}
[2018-04-11 21:52:40] Started run 188 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:41] Error in run 182: Run already exists in server. Run id(s): {9042293}
[2018-04-11 21:52:41] Error in run 181: Run already exists in server. Run id(s): {9041571}
[2018-04-11 21:52:41] Started run 189 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:41] Started run 190 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:41] Error in run 183: Run already exists in server. Run id(s): {9041960}
[2018-04-11 21:52:41] Started run 191 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:41] Error in run 184: Run already exists in server. Run id(s): {9041912}
[2018-04-11 21:52:41] Started run 192 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:43] Error in run 185: Run already exists in server. Run id(s): {9041812}
[2018-04-11 21:52:43] Started run 193 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:44] Error in run 186: Run already exists in server. Run id(s): {9042541}
[2018-04-11 21:52:44] Started run 194 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:44] Error in run 187: Run already exists in server. Run id(s): {9042139}
[2018-04-11 21:52:44] Started run 195 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:45] Error in run 188: Run already exists in server. Run id(s): {9042520}
[2018-04-11 21:52:45] Started run 196 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:45] Error in run 190: Run already exists in server. Run id(s): {9042246}
[2018-04-11 21:52:45] Started run 197 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:45] Error in run 189: Run already exists in server. Run id(s): {9042523}
[2018-04-11 21:52:45] Started run 198 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:45] Error in run 191: Run already exists in server. Run id(s): {9042516}
[2018-04-11 21:52:45] Started run 199 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:45] Error in run 192: Run already exists in server. Run id(s): {9042174}
[2018-04-11 21:52:45] Started run 200 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:48] Error in run 193: Run already exists in server. Run id(s): {9042282}
[2018-04-11 21:52:48] Started run 201 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:48] Error in run 194: Run already exists in server. Run id(s): {9042643}
[2018-04-11 21:52:48] Started run 202 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:49] Error in run 195: Run already exists in server. Run id(s): {9042358}
[2018-04-11 21:52:49] Started run 203 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:49] Error in run 196: Run already exists in server. Run id(s): {9042423}
[2018-04-11 21:52:49] Started run 204 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:50] Error in run 197: Run already exists in server. Run id(s): {9042686}
[2018-04-11 21:52:50] Error in run 198: Run already exists in server. Run id(s): {9042618}
[2018-04-11 21:52:50] Started run 205 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:50] Started run 206 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:50] Error in run 199: Run already exists in server. Run id(s): {9042494}
[2018-04-11 21:52:50] Started run 207 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:50] Error in run 200: Run already exists in server. Run id(s): {9043243}
[2018-04-11 21:52:50] Started run 208 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:52] Error in run 201: Run already exists in server. Run id(s): {9042755}
[2018-04-11 21:52:52] Started run 209 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:53] Error in run 202: Run already exists in server. Run id(s): {9042592}
[2018-04-11 21:52:53] Started run 210 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:53] Error in run 203: Run already exists in server. Run id(s): {9042683}
[2018-04-11 21:52:53] Started run 211 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:54] Error in run 204: Run already exists in server. Run id(s): {9042875}
[2018-04-11 21:52:54] Started run 212 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:54] Error in run 206: Run already exists in server. Run id(s): {9042894}
[2018-04-11 21:52:54] Started run 213 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:54] Error in run 205: Run already exists in server. Run id(s): {9042827}
[2018-04-11 21:52:54] Started run 214 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:54] Error in run 207: Run already exists in server. Run id(s): {9042826}
[2018-04-11 21:52:54] Error in run 208: Run already exists in server. Run id(s): {9042774}
[2018-04-11 21:52:54] Started run 215 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:54] Started run 216 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:57] Error in run 209: Run already exists in server. Run id(s): {9042845}
[2018-04-11 21:52:57] Started run 217 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:57] Error in run 210: Run already exists in server. Run id(s): {9042939}
[2018-04-11 21:52:57] Started run 218 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:58] Error in run 211: Run already exists in server. Run id(s): {9043595}
[2018-04-11 21:52:58] Started run 219 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:58] Error in run 212: Run already exists in server. Run id(s): {9043528}
[2018-04-11 21:52:58] Started run 220 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:59] Error in run 213: Run already exists in server. Run id(s): {9043103}
[2018-04-11 21:52:59] Error in run 214: Run already exists in server. Run id(s): {9042998}
[2018-04-11 21:52:59] Error in run 215: Run already exists in server. Run id(s): {9042951}
[2018-04-11 21:52:59] Error in run 216: Run already exists in server. Run id(s): {9043038}
[2018-04-11 21:52:59] Started run 221 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:59] Started run 224 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:59] Started run 222 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:52:59] Started run 223 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:01] Error in run 217: Run already exists in server. Run id(s): {9043322}
[2018-04-11 21:53:01] Started run 225 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:02] Error in run 218: Run already exists in server. Run id(s): {9043002}
[2018-04-11 21:53:02] Started run 226 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:02] Error in run 219: Run already exists in server. Run id(s): {9043154}
[2018-04-11 21:53:02] Started run 227 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:03] Error in run 220: Run already exists in server. Run id(s): {9043189}
[2018-04-11 21:53:03] Started run 228 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:04] Error in run 224: Run already exists in server. Run id(s): {9043219}
[2018-04-11 21:53:04] Error in run 222: Run already exists in server. Run id(s): {9043354}
[2018-04-11 21:53:04] Started run 229 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:04] Error in run 221: Run already exists in server. Run id(s): {9043562}
[2018-04-11 21:53:04] Started run 231 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:04] Started run 230 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:04] Error in run 223: Run already exists in server. Run id(s): {9043560}
[2018-04-11 21:53:04] Started run 232 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:06] Error in run 225: Run already exists in server. Run id(s): {9043470}
[2018-04-11 21:53:06] Started run 233 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:06] Error in run 226: Run already exists in server. Run id(s): {9043680}
[2018-04-11 21:53:06] Started run 234 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:07] Error in run 227: Run already exists in server. Run id(s): {9043604}
[2018-04-11 21:53:07] Started run 235 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:07] Error in run 228: Run already exists in server. Run id(s): {9043512}
[2018-04-11 21:53:07] Started run 236 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:08] Error in run 231: Run already exists in server. Run id(s): {9043734}
[2018-04-11 21:53:08] Error in run 229: Run already exists in server. Run id(s): {9043613}
[2018-04-11 21:53:08] Error in run 230: Run already exists in server. Run id(s): {9043932}
[2018-04-11 21:53:08] Error in run 232: Run already exists in server. Run id(s): {9043953}
[2018-04-11 21:53:08] Started run 237 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:08] Started run 238 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:08] Started run 239 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:08] Started run 240 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:10] Error in run 233: Run already exists in server. Run id(s): {9043659}
[2018-04-11 21:53:10] Started run 241 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:11] Error in run 234: Run already exists in server. Run id(s): {9043707}
[2018-04-11 21:53:11] Started run 242 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:11] Error in run 235: Run already exists in server. Run id(s): {9043793}
[2018-04-11 21:53:11] Started run 243 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:12] Error in run 236: Run already exists in server. Run id(s): {9043765}
[2018-04-11 21:53:12] Started run 244 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:13] Error in run 240: Run already exists in server. Run id(s): {9044033}
[2018-04-11 21:53:13] Error in run 239: Run already exists in server. Run id(s): {9043794}
[2018-04-11 21:53:13] Started run 245 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:13] Error in run 238: Run already exists in server. Run id(s): {9043994}
[2018-04-11 21:53:13] Error in run 237: Run already exists in server. Run id(s): {9043740}
[2018-04-11 21:53:13] Started run 246 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:13] Started run 247 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:13] Started run 248 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:15] Error in run 241: Run already exists in server. Run id(s): {9043827}
[2018-04-11 21:53:15] Started run 249 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:15] Error in run 242: Run already exists in server. Run id(s): {9044761}
[2018-04-11 21:53:15] Started run 250 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:16] Error in run 243: Run already exists in server. Run id(s): {9044788}
[2018-04-11 21:53:16] Started run 251 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:17] Error in run 244: Run already exists in server. Run id(s): {9043822}
[2018-04-11 21:53:17] Started run 252 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:17] Error in run 245: Run already exists in server. Run id(s): {9043879}
[2018-04-11 21:53:17] Started run 253 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:17] Error in run 246: Run already exists in server. Run id(s): {9044015}
[2018-04-11 21:53:17] Started run 254 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:18] Error in run 247: Run already exists in server. Run id(s): {9043993}
[2018-04-11 21:53:18] Started run 255 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:18] Error in run 248: Run already exists in server. Run id(s): {9043987}
[2018-04-11 21:53:18] Started run 256 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:19] Error in run 249: Run already exists in server. Run id(s): {9044051}
[2018-04-11 21:53:19] Started run 257 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:20] Error in run 250: Run already exists in server. Run id(s): {9044266}
[2018-04-11 21:53:20] Started run 258 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:20] Error in run 251: Run already exists in server. Run id(s): {9044250}
[2018-04-11 21:53:20] Started run 259 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:21] Error in run 252: Run already exists in server. Run id(s): {9044300}
[2018-04-11 21:53:21] Started run 260 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:22] Error in run 253: Run already exists in server. Run id(s): {9044148}
[2018-04-11 21:53:22] Started run 261 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:22] Error in run 254: Run already exists in server. Run id(s): {9044212}
[2018-04-11 21:53:22] Started run 262 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:22] Error in run 255: Run already exists in server. Run id(s): {9044572}
[2018-04-11 21:53:22] Started run 263 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:22] Error in run 256: Run already exists in server. Run id(s): {9044286}
[2018-04-11 21:53:22] Started run 264 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:24] Error in run 257: Run already exists in server. Run id(s): {9044402}
[2018-04-11 21:53:24] Started run 265 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:24] Error in run 258: Run already exists in server. Run id(s): {9044427}
[2018-04-11 21:53:24] Started run 266 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:25] Error in run 259: Run already exists in server. Run id(s): {9044370}
[2018-04-11 21:53:25] Started run 267 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:26] Error in run 260: Run already exists in server. Run id(s): {9044472}
[2018-04-11 21:53:26] Started run 268 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:26] Error in run 261: Run already exists in server. Run id(s): {9044851}
[2018-04-11 21:53:26] Started run 269 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:26] Error in run 262: Run already exists in server. Run id(s): {9044949}
[2018-04-11 21:53:26] Started run 270 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:27] Error in run 263: Run already exists in server. Run id(s): {9044445}
[2018-04-11 21:53:27] Started run 271 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:27] Error in run 264: Run already exists in server. Run id(s): {9044648}
[2018-04-11 21:53:27] Started run 272 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:29] Error in run 265: Run already exists in server. Run id(s): {9044471}
[2018-04-11 21:53:29] Started run 273 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:29] Error in run 266: Run already exists in server. Run id(s): {9044618}
[2018-04-11 21:53:29] Started run 274 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:29] Error in run 267: Run already exists in server. Run id(s): {9044765}
[2018-04-11 21:53:29] Started run 275 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:30] Error in run 268: Run already exists in server. Run id(s): {9045150}
[2018-04-11 21:53:30] Started run 276 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:31] Error in run 269: Run already exists in server. Run id(s): {9044649}
[2018-04-11 21:53:31] Error in run 270: Run already exists in server. Run id(s): {9044695}
[2018-04-11 21:53:31] Started run 277 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:31] Started run 278 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:31] Error in run 271: Run already exists in server. Run id(s): {9045036}
[2018-04-11 21:53:31] Started run 279 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:31] Error in run 272: Run already exists in server. Run id(s): {9044724}
[2018-04-11 21:53:31] Started run 280 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:33] Error in run 273: Run already exists in server. Run id(s): {9044848}
[2018-04-11 21:53:33] Started run 281 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:33] Error in run 274: Run already exists in server. Run id(s): {9045032}
[2018-04-11 21:53:33] Started run 282 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:34] Error in run 275: Run already exists in server. Run id(s): {9045333}
[2018-04-11 21:53:34] Started run 283 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:35] Error in run 276: Run already exists in server. Run id(s): {9045323}
[2018-04-11 21:53:35] Started run 284 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:35] Error in run 277: Run already exists in server. Run id(s): {9044917}
[2018-04-11 21:53:35] Started run 285 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:36] Error in run 278: Run already exists in server. Run id(s): {9045153}
[2018-04-11 21:53:36] Error in run 279: Run already exists in server. Run id(s): {9045084}
[2018-04-11 21:53:36] Started run 286 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:36] Started run 287 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:36] Error in run 280: Run already exists in server. Run id(s): {9045305}
[2018-04-11 21:53:36] Started run 288 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:38] Error in run 281: Run already exists in server. Run id(s): {9045062}
[2018-04-11 21:53:38] Started run 289 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:38] Error in run 282: Run already exists in server. Run id(s): {9045210}
[2018-04-11 21:53:38] Started run 290 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:39] Error in run 283: Run already exists in server. Run id(s): {9045374}
[2018-04-11 21:53:39] Started run 291 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:39] Error in run 284: Run already exists in server. Run id(s): {9045309}
[2018-04-11 21:53:39] Started run 292 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:40] Error in run 285: Run already exists in server. Run id(s): {9045834}
[2018-04-11 21:53:40] Started run 293 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:40] Error in run 288: Run already exists in server. Run id(s): {9045706}
[2018-04-11 21:53:40] Error in run 286: Run already exists in server. Run id(s): {9045315}
[2018-04-11 21:53:40] Started run 294 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:40] Started run 295 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:40] Error in run 287: Run already exists in server. Run id(s): {9045393}
[2018-04-11 21:53:40] Started run 296 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:42] Error in run 289: Run already exists in server. Run id(s): {9045422}
[2018-04-11 21:53:42] Started run 297 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:42] Error in run 290: Run already exists in server. Run id(s): {9045457}
[2018-04-11 21:53:42] Started run 298 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:43] Error in run 291: Run already exists in server. Run id(s): {9045463}
[2018-04-11 21:53:43] Started run 299 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:44] Error in run 292: Run already exists in server. Run id(s): {9045351}
[2018-04-11 21:53:44] Started run 300 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:44] Error in run 293: Run already exists in server. Run id(s): {9045469}
[2018-04-11 21:53:44] Started run 301 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:45] Error in run 294: Run already exists in server. Run id(s): {9045583}
[2018-04-11 21:53:45] Started run 302 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:45] Error in run 295: Run already exists in server. Run id(s): {9045644}
[2018-04-11 21:53:45] Started run 303 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:45] Error in run 296: Run already exists in server. Run id(s): {9045495}
[2018-04-11 21:53:45] Started run 304 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:47] Error in run 297: Run already exists in server. Run id(s): {9045492}
[2018-04-11 21:53:47] Started run 305 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:47] Error in run 298: Run already exists in server. Run id(s): {9045742}
[2018-04-11 21:53:47] Started run 306 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:48] Error in run 299: Run already exists in server. Run id(s): {9045614}
[2018-04-11 21:53:48] Started run 307 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:48] Error in run 300: Run already exists in server. Run id(s): {9045825}
[2018-04-11 21:53:48] Started run 308 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:49] Error in run 301: Run already exists in server. Run id(s): {9045725}
[2018-04-11 21:53:49] Started run 309 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:49] Error in run 302: Run already exists in server. Run id(s): {9045708}
[2018-04-11 21:53:49] Started run 310 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:50] Error in run 303: Run already exists in server. Run id(s): {9045836}
[2018-04-11 21:53:50] Error in run 304: Run already exists in server. Run id(s): {9045684}
[2018-04-11 21:53:50] Started run 311 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:50] Started run 312 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:51] Error in run 305: Run already exists in server. Run id(s): {9045780}
[2018-04-11 21:53:51] Started run 313 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:51] Error in run 306: Run already exists in server. Run id(s): {9045793}
[2018-04-11 21:53:51] Started run 314 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:52] Error in run 307: Run already exists in server. Run id(s): {9045951}
[2018-04-11 21:53:52] Started run 315 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:53] Error in run 308: Run already exists in server. Run id(s): {9045738}
[2018-04-11 21:53:53] Started run 316 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:54] Error in run 309: Run already exists in server. Run id(s): {9045929}
[2018-04-11 21:53:54] Started run 317 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:54] Error in run 310: Run already exists in server. Run id(s): {9045805}
[2018-04-11 21:53:54] Started run 318 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:54] Error in run 311: Run already exists in server. Run id(s): {9046198}
[2018-04-11 21:53:54] Started run 319 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:54] Error in run 312: Run already exists in server. Run id(s): {9045820}
[2018-04-11 21:53:54] Started run 320 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:56] Error in run 313: Run already exists in server. Run id(s): {9045870}
[2018-04-11 21:53:56] Started run 321 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:56] Error in run 314: Run already exists in server. Run id(s): {9046118}
[2018-04-11 21:53:56] Started run 322 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:57] Error in run 315: Run already exists in server. Run id(s): {9045854}
[2018-04-11 21:53:57] Started run 323 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:57] Error in run 316: Run already exists in server. Run id(s): {9045865}
[2018-04-11 21:53:57] Started run 324 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:58] Error in run 317: Run already exists in server. Run id(s): {9045963}
[2018-04-11 21:53:58] Started run 325 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:58] Error in run 318: Run already exists in server. Run id(s): {9046291}
[2018-04-11 21:53:58] Started run 326 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:59] Error in run 319: Run already exists in server. Run id(s): {9045902}
[2018-04-11 21:53:59] Started run 327 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:53:59] Error in run 320: Run already exists in server. Run id(s): {9045941}
[2018-04-11 21:53:59] Started run 328 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:00] Error in run 321: Run already exists in server. Run id(s): {9046009}
[2018-04-11 21:54:00] Started run 329 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:00] Error in run 322: Run already exists in server. Run id(s): {9046001}
[2018-04-11 21:54:00] Started run 330 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:01] Error in run 323: Run already exists in server. Run id(s): {9045966}
[2018-04-11 21:54:01] Started run 331 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:02] Error in run 324: Run already exists in server. Run id(s): {9046071}
[2018-04-11 21:54:02] Started run 332 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:03] Error in run 325: Run already exists in server. Run id(s): {9046202}
[2018-04-11 21:54:03] Started run 333 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:03] Error in run 326: Run already exists in server. Run id(s): {9046051}
[2018-04-11 21:54:03] Started run 334 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:03] Error in run 327: Run already exists in server. Run id(s): {9046125}
[2018-04-11 21:54:03] Started run 335 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:03] Error in run 328: Run already exists in server. Run id(s): {9046187}
[2018-04-11 21:54:03] Started run 336 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:05] Error in run 329: Run already exists in server. Run id(s): {9046119}
[2018-04-11 21:54:05] Started run 337 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:05] Error in run 330: Run already exists in server. Run id(s): {9046090}
[2018-04-11 21:54:05] Started run 338 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:06] Error in run 331: Run already exists in server. Run id(s): {9046478}
[2018-04-11 21:54:06] Started run 339 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:06] Error in run 332: Run already exists in server. Run id(s): {9046242}
[2018-04-11 21:54:06] Started run 340 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:07] Error in run 333: Run already exists in server. Run id(s): {9046163}
[2018-04-11 21:54:07] Started run 341 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:08] Error in run 335: Run already exists in server. Run id(s): {9046189}
[2018-04-11 21:54:08] Error in run 334: Run already exists in server. Run id(s): {9046169}
[2018-04-11 21:54:08] Started run 342 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:08] Started run 343 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:08] Error in run 336: Run already exists in server. Run id(s): {9046305}
[2018-04-11 21:54:08] Started run 344 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:09] Error in run 337: Run already exists in server. Run id(s): {9046273}
[2018-04-11 21:54:09] Started run 345 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:09] Error in run 338: Run already exists in server. Run id(s): {9046247}
[2018-04-11 21:54:09] Started run 346 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:11] Error in run 340: Run already exists in server. Run id(s): {9046338}
[2018-04-11 21:54:11] Error in run 339: Run already exists in server. Run id(s): {9046316}
[2018-04-11 21:54:11] Started run 347 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:11] Started run 348 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:12] Error in run 341: Run already exists in server. Run id(s): {9046269}
[2018-04-11 21:54:12] Started run 349 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:12] Error in run 342: Run already exists in server. Run id(s): {9046309}
[2018-04-11 21:54:12] Started run 350 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:12] Error in run 343: Run already exists in server. Run id(s): {9046358}
[2018-04-11 21:54:12] Started run 351 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:12] Error in run 344: Run already exists in server. Run id(s): {9046347}
[2018-04-11 21:54:12] Started run 352 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:14] Error in run 346: Run already exists in server. Run id(s): {9046344}
[2018-04-11 21:54:14] Started run 353 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:14] Error in run 345: Run already exists in server. Run id(s): {9046328}
[2018-04-11 21:54:14] Started run 354 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:15] Error in run 347: Run already exists in server. Run id(s): {9046390}
[2018-04-11 21:54:15] Error in run 348: Run already exists in server. Run id(s): {9046452}
[2018-04-11 21:54:15] Started run 355 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:15] Started run 356 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:16] Error in run 349: Run already exists in server. Run id(s): {9046451}
[2018-04-11 21:54:16] Started run 357 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:17] Error in run 350: Run already exists in server. Run id(s): {9046459}
[2018-04-11 21:54:17] Started run 358 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:17] Error in run 352: Run already exists in server. Run id(s): {9046560}
[2018-04-11 21:54:17] Error in run 351: Run already exists in server. Run id(s): {9046365}
[2018-04-11 21:54:17] Started run 359 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:17] Started run 360 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:18] Error in run 353: Run already exists in server. Run id(s): {9046721}
[2018-04-11 21:54:18] Started run 361 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:19] Error in run 354: Run already exists in server. Run id(s): {9046382}
[2018-04-11 21:54:19] Started run 362 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:20] Error in run 355: Run already exists in server. Run id(s): {9046604}
[2018-04-11 21:54:20] Started run 363 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:20] Error in run 356: Run already exists in server. Run id(s): {9046527}
[2018-04-11 21:54:20] Started run 364 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:21] Error in run 357: Run already exists in server. Run id(s): {9046635}
[2018-04-11 21:54:21] Started run 365 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:21] Error in run 358: Run already exists in server. Run id(s): {9046747}
[2018-04-11 21:54:21] Started run 366 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:22] Error in run 360: Run already exists in server. Run id(s): {9046783}
[2018-04-11 21:54:22] Error in run 359: Run already exists in server. Run id(s): {9046555}
[2018-04-11 21:54:22] Started run 367 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:22] Started run 368 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:23] Error in run 361: Run already exists in server. Run id(s): {9046724}
[2018-04-11 21:54:23] Started run 369 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:23] Error in run 362: Run already exists in server. Run id(s): {9046778}
[2018-04-11 21:54:23] Started run 370 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:24] Error in run 363: Run already exists in server. Run id(s): {9046905}
[2018-04-11 21:54:24] Started run 371 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:25] Error in run 364: Run already exists in server. Run id(s): {9046727}
[2018-04-11 21:54:25] Started run 372 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:25] Error in run 365: Run already exists in server. Run id(s): {9046731}
[2018-04-11 21:54:25] Started run 373 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:26] Error in run 366: Run already exists in server. Run id(s): {9046740}
[2018-04-11 21:54:26] Started run 374 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:26] Error in run 367: Run already exists in server. Run id(s): {9046850}
[2018-04-11 21:54:26] Error in run 368: Run already exists in server. Run id(s): {9046745}
[2018-04-11 21:54:26] Started run 375 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:27] Started run 376 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:28] Error in run 369: Run already exists in server. Run id(s): {9046852}
[2018-04-11 21:54:28] Started run 377 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:28] Error in run 370: Run already exists in server. Run id(s): {9046840}
[2018-04-11 21:54:28] Started run 378 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:29] Error in run 371: Run already exists in server. Run id(s): {9046788}
[2018-04-11 21:54:29] Started run 379 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:30] Error in run 372: Run already exists in server. Run id(s): {9046805}
[2018-04-11 21:54:30] Started run 380 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:30] Error in run 373: Run already exists in server. Run id(s): {9046794}
[2018-04-11 21:54:30] Started run 381 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:30] Error in run 374: Run already exists in server. Run id(s): {9046830}
[2018-04-11 21:54:30] Started run 382 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:31] Error in run 375: Run already exists in server. Run id(s): {9046798}
[2018-04-11 21:54:31] Started run 383 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:31] Error in run 376: Run already exists in server. Run id(s): {9047030}
[2018-04-11 21:54:31] Started run 384 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:32] Error in run 377: Run already exists in server. Run id(s): {9047011}
[2018-04-11 21:54:32] Started run 385 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:33] Error in run 378: Run already exists in server. Run id(s): {9046940}
[2018-04-11 21:54:33] Started run 386 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:34] Error in run 379: Run already exists in server. Run id(s): {9046921}
[2018-04-11 21:54:34] Started run 387 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:34] Error in run 380: Run already exists in server. Run id(s): {9047070}
[2018-04-11 21:54:34] Started run 388 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:34] Error in run 381: Run already exists in server. Run id(s): {9046909}
[2018-04-11 21:54:34] Started run 389 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:35] Error in run 382: Run already exists in server. Run id(s): {9046900}
[2018-04-11 21:54:35] Started run 390 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:36] Error in run 383: Run already exists in server. Run id(s): {9046932}
[2018-04-11 21:54:36] Started run 391 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:36] Error in run 384: Run already exists in server. Run id(s): {9046998}
[2018-04-11 21:54:36] Started run 392 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:37] Error in run 385: Run already exists in server. Run id(s): {9046918}
[2018-04-11 21:54:37] Started run 393 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:37] Error in run 386: Run already exists in server. Run id(s): {9047104}
[2018-04-11 21:54:37] Started run 394 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:38] Error in run 387: Run already exists in server. Run id(s): {9047114}
[2018-04-11 21:54:38] Started run 395 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:39] Error in run 388: Run already exists in server. Run id(s): {9047017}
[2018-04-11 21:54:39] Started run 396 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:39] Error in run 389: Run already exists in server. Run id(s): {9047039}
[2018-04-11 21:54:39] Started run 397 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:40] Error in run 390: Run already exists in server. Run id(s): {9047018}
[2018-04-11 21:54:40] Started run 398 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:40] Error in run 391: Run already exists in server. Run id(s): {9047319}
[2018-04-11 21:54:40] Started run 399 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:40] Error in run 392: Run already exists in server. Run id(s): {9047157}
[2018-04-11 21:54:40] Started run 400 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:41] Error in run 393: Run already exists in server. Run id(s): {9047103}
[2018-04-11 21:54:41] Started run 401 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:42] Error in run 394: Run already exists in server. Run id(s): {9047123}
[2018-04-11 21:54:42] Started run 402 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:43] Error in run 395: Run already exists in server. Run id(s): {9047093}
[2018-04-11 21:54:43] Started run 403 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:43] Error in run 396: Run already exists in server. Run id(s): {9047172}
[2018-04-11 21:54:43] Started run 404 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:44] Error in run 397: Run already exists in server. Run id(s): {9047106}
[2018-04-11 21:54:44] Started run 405 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:44] Error in run 398: Run already exists in server. Run id(s): {9047169}
[2018-04-11 21:54:44] Started run 406 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:45] Error in run 399: Run already exists in server. Run id(s): {9047289}
[2018-04-11 21:54:45] Started run 407 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:45] Error in run 400: Run already exists in server. Run id(s): {9047115}
[2018-04-11 21:54:45] Started run 408 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:46] Error in run 401: Run already exists in server. Run id(s): {9047420}
[2018-04-11 21:54:46] Started run 409 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:46] Error in run 402: Run already exists in server. Run id(s): {9047226}
[2018-04-11 21:54:46] Started run 410 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:47] Error in run 403: Run already exists in server. Run id(s): {9047170}
[2018-04-11 21:54:47] Started run 411 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:48] Error in run 404: Run already exists in server. Run id(s): {9047220}
[2018-04-11 21:54:48] Started run 412 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:48] Error in run 405: Run already exists in server. Run id(s): {9047235}
[2018-04-11 21:54:48] Started run 413 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:49] Error in run 406: Run already exists in server. Run id(s): {9047218}
[2018-04-11 21:54:49] Started run 414 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:49] Error in run 407: Run already exists in server. Run id(s): {9047284}
[2018-04-11 21:54:49] Started run 415 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:50] Error in run 408: Run already exists in server. Run id(s): {9047247}
[2018-04-11 21:54:50] Started run 416 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:51] Error in run 409: Run already exists in server. Run id(s): {9047280}
[2018-04-11 21:54:51] Started run 417 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:51] Error in run 410: Run already exists in server. Run id(s): {9047353}
[2018-04-11 21:54:51] Started run 418 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:52] Error in run 411: Run already exists in server. Run id(s): {9047252}
[2018-04-11 21:54:52] Started run 419 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:52] Error in run 412: Run already exists in server. Run id(s): {9047276}
[2018-04-11 21:54:52] Started run 420 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:52] Error in run 413: Run already exists in server. Run id(s): {9047505}
[2018-04-11 21:54:52] Started run 421 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:53] Error in run 414: Run already exists in server. Run id(s): {9047562}
[2018-04-11 21:54:53] Started run 422 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:54] Error in run 415: Run already exists in server. Run id(s): {9047325}
[2018-04-11 21:54:54] Started run 423 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:54] Error in run 416: Run already exists in server. Run id(s): {9047552}
[2018-04-11 21:54:54] Started run 424 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:55] Error in run 417: Run already exists in server. Run id(s): {9047300}
[2018-04-11 21:54:55] Started run 425 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:55] Error in run 418: Run already exists in server. Run id(s): {9047480}
[2018-04-11 21:54:55] Started run 426 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:56] Error in run 419: Run already exists in server. Run id(s): {9047377}
[2018-04-11 21:54:56] Started run 427 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:57] Error in run 420: Run already exists in server. Run id(s): {9047387}
[2018-04-11 21:54:57] Started run 428 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:57] Error in run 421: Run already exists in server. Run id(s): {9047433}
[2018-04-11 21:54:57] Started run 429 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:58] Error in run 422: Run already exists in server. Run id(s): {9047427}
[2018-04-11 21:54:58] Started run 430 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:59] Error in run 423: Run already exists in server. Run id(s): {9047440}
[2018-04-11 21:54:59] Started run 431 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:54:59] Error in run 424: Run already exists in server. Run id(s): {9047527}
[2018-04-11 21:54:59] Started run 432 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:00] Error in run 425: Run already exists in server. Run id(s): {9047720}
[2018-04-11 21:55:00] Started run 433 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:00] Error in run 426: Run already exists in server. Run id(s): {9047445}
[2018-04-11 21:55:00] Started run 434 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:01] Error in run 427: Run already exists in server. Run id(s): {9047540}
[2018-04-11 21:55:01] Started run 435 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:01] Error in run 428: Run already exists in server. Run id(s): {9047545}
[2018-04-11 21:55:01] Started run 436 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:02] Error in run 429: Run already exists in server. Run id(s): {9047529}
[2018-04-11 21:55:02] Started run 437 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:02] Error in run 430: Run already exists in server. Run id(s): {9047531}
[2018-04-11 21:55:02] Started run 438 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:03] Error in run 431: Run already exists in server. Run id(s): {9047811}
[2018-04-11 21:55:03] Error in run 432: Run already exists in server. Run id(s): {9047539}
[2018-04-11 21:55:03] Started run 439 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:03] Started run 440 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:04] Error in run 433: Run already exists in server. Run id(s): {9047650}
[2018-04-11 21:55:04] Started run 441 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:04] Error in run 434: Run already exists in server. Run id(s): {9047617}
[2018-04-11 21:55:04] Started run 442 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:06] Error in run 435: Run already exists in server. Run id(s): {9047587}
[2018-04-11 21:55:06] Started run 443 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:06] Error in run 436: Run already exists in server. Run id(s): {9047761}
[2018-04-11 21:55:06] Started run 444 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:06] Error in run 437: Run already exists in server. Run id(s): {9047561}
[2018-04-11 21:55:06] Started run 445 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:07] Error in run 438: Run already exists in server. Run id(s): {9047593}
[2018-04-11 21:55:07] Started run 446 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:08] Error in run 440: Run already exists in server. Run id(s): {9047609}
[2018-04-11 21:55:08] Error in run 439: Run already exists in server. Run id(s): {9047573}
[2018-04-11 21:55:08] Started run 447 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:08] Started run 448 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:09] Error in run 441: Run already exists in server. Run id(s): {9047808}
[2018-04-11 21:55:09] Started run 449 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:09] Error in run 442: Run already exists in server. Run id(s): {9047655}
[2018-04-11 21:55:09] Started run 450 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:10] Error in run 444: Run already exists in server. Run id(s): {9047634}
[2018-04-11 21:55:10] Error in run 443: Run already exists in server. Run id(s): {9047645}
[2018-04-11 21:55:10] Started run 451 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:10] Started run 452 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:11] Error in run 445: Run already exists in server. Run id(s): {9047795}
[2018-04-11 21:55:11] Started run 453 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:12] Error in run 446: Run already exists in server. Run id(s): {9047663}
[2018-04-11 21:55:12] Started run 454 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:12] Error in run 447: Run already exists in server. Run id(s): {9047695}
[2018-04-11 21:55:12] Started run 455 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:13] Error in run 448: Run already exists in server. Run id(s): {9047742}
[2018-04-11 21:55:13] Started run 456 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:13] Error in run 449: Run already exists in server. Run id(s): {9047692}
[2018-04-11 21:55:13] Started run 457 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:13] Error in run 450: Run already exists in server. Run id(s): {9047753}
[2018-04-11 21:55:13] Started run 458 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:15] Error in run 452: Run already exists in server. Run id(s): {9047859}
[2018-04-11 21:55:15] Error in run 451: Run already exists in server. Run id(s): {9047708}
[2018-04-11 21:55:15] Started run 459 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:15] Started run 460 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:15] Error in run 453: Run already exists in server. Run id(s): {9047928}
[2018-04-11 21:55:15] Started run 461 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:16] Error in run 454: Run already exists in server. Run id(s): {9047791}
[2018-04-11 21:55:16] Started run 462 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:17] Error in run 455: Run already exists in server. Run id(s): {9047829}
[2018-04-11 21:55:17] Started run 463 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:17] Error in run 456: Run already exists in server. Run id(s): {9047835}
[2018-04-11 21:55:17] Started run 464 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:18] Error in run 457: Run already exists in server. Run id(s): {9047802}
[2018-04-11 21:55:18] Started run 465 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:18] Error in run 458: Run already exists in server. Run id(s): {9047826}
[2018-04-11 21:55:18] Started run 466 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:19] Error in run 459: Run already exists in server. Run id(s): {9047879}
[2018-04-11 21:55:19] Started run 467 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:20] Error in run 460: Run already exists in server. Run id(s): {9047820}
[2018-04-11 21:55:20] Started run 468 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:20] Error in run 461: Run already exists in server. Run id(s): {9047969}
[2018-04-11 21:55:20] Started run 469 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:21] Error in run 462: Run already exists in server. Run id(s): {9047847}
[2018-04-11 21:55:21] Started run 470 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:21] Error in run 463: Run already exists in server. Run id(s): {9047893}
[2018-04-11 21:55:21] Started run 471 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:22] Error in run 464: Run already exists in server. Run id(s): {9047890}
[2018-04-11 21:55:22] Started run 472 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:22] Error in run 465: Run already exists in server. Run id(s): {9047904}
[2018-04-11 21:55:22] Started run 473 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:23] Error in run 466: Run already exists in server. Run id(s): {9047853}
[2018-04-11 21:55:23] Started run 474 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:24] Error in run 467: Run already exists in server. Run id(s): {9048050}
[2018-04-11 21:55:24] Started run 475 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:24] Error in run 468: Run already exists in server. Run id(s): {9047900}
[2018-04-11 21:55:24] Started run 476 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:24] Error in run 469: Run already exists in server. Run id(s): {9047922}
[2018-04-11 21:55:24] Started run 477 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:25] Error in run 470: Run already exists in server. Run id(s): {9047966}
[2018-04-11 21:55:25] Started run 478 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:26] Error in run 471: Run already exists in server. Run id(s): {9047902}
[2018-04-11 21:55:26] Started run 479 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:27] Error in run 473: Run already exists in server. Run id(s): {9048080}
[2018-04-11 21:55:27] Error in run 472: Run already exists in server. Run id(s): {9047968}
[2018-04-11 21:55:27] Started run 480 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:27] Started run 481 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:27] Error in run 474: Run already exists in server. Run id(s): {9047912}
[2018-04-11 21:55:27] Started run 482 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:28] Error in run 475: Run already exists in server. Run id(s): {9047963}
[2018-04-11 21:55:28] Started run 483 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:29] Error in run 476: Run already exists in server. Run id(s): {9047942}
[2018-04-11 21:55:29] Error in run 477: Run already exists in server. Run id(s): {9047941}
[2018-04-11 21:55:29] Started run 484 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:29] Started run 485 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:30] Error in run 478: Run already exists in server. Run id(s): {9048043}
[2018-04-11 21:55:30] Started run 486 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:31] Error in run 479: Run already exists in server. Run id(s): {9047965}
[2018-04-11 21:55:31] Started run 487 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:31] Error in run 481: Run already exists in server. Run id(s): {9048008}
[2018-04-11 21:55:31] Error in run 480: Run already exists in server. Run id(s): {9048089}
[2018-04-11 21:55:31] Started run 488 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:31] Started run 489 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:32] Error in run 482: Run already exists in server. Run id(s): {9048169}
[2018-04-11 21:55:32] Started run 490 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:33] Error in run 483: Run already exists in server. Run id(s): {9048033}
[2018-04-11 21:55:33] Started run 491 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:34] Error in run 484: Run already exists in server. Run id(s): {9048011}
[2018-04-11 21:55:34] Error in run 485: Run already exists in server. Run id(s): {9048019}
[2018-04-11 21:55:34] Started run 492 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:34] Started run 493 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:34] Error in run 486: Run already exists in server. Run id(s): {9048095}
[2018-04-11 21:55:34] Started run 494 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:35] Error in run 487: Run already exists in server. Run id(s): {9048152}
[2018-04-11 21:55:35] Started run 495 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:36] Error in run 488: Run already exists in server. Run id(s): {9048128}
[2018-04-11 21:55:36] Error in run 489: Run already exists in server. Run id(s): {9048083}
[2018-04-11 21:55:36] Started run 496 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:36] Started run 497 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:37] Error in run 490: Run already exists in server. Run id(s): {9048146}
[2018-04-11 21:55:37] Started run 498 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:38] Error in run 491: Run already exists in server. Run id(s): {9048206}
[2018-04-11 21:55:38] Started run 499 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:38] Error in run 492: Run already exists in server. Run id(s): {9048134}
[2018-04-11 21:55:38] Started run 500 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:38] Error in run 493: Run already exists in server. Run id(s): {9048142}
[2018-04-11 21:55:38] Started run 501 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:39] Error in run 494: Run already exists in server. Run id(s): {9048105}
[2018-04-11 21:55:39] Started run 502 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:40] Error in run 495: Run already exists in server. Run id(s): {9048153}
[2018-04-11 21:55:40] Started run 503 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:41] Error in run 496: Run already exists in server. Run id(s): {9048141}
[2018-04-11 21:55:41] Started run 504 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:41] Error in run 497: Run already exists in server. Run id(s): {9048172}
[2018-04-11 21:55:41] Started run 505 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:41] Error in run 498: Run already exists in server. Run id(s): {9048187}
[2018-04-11 21:55:41] Started run 506 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:42] Error in run 499: Run already exists in server. Run id(s): {9048151}
[2018-04-11 21:55:42] Started run 507 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:43] Error in run 500: Run already exists in server. Run id(s): {9048197}
[2018-04-11 21:55:43] Started run 508 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:43] Error in run 501: Run already exists in server. Run id(s): {9048399}
[2018-04-11 21:55:43] Started run 509 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:44] Error in run 502: Run already exists in server. Run id(s): {9048294}
[2018-04-11 21:55:44] Started run 510 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:45] Error in run 503: Run already exists in server. Run id(s): {9048249}
[2018-04-11 21:55:45] Started run 511 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:46] Error in run 504: Run already exists in server. Run id(s): {9048193, 9048196}
[2018-04-11 21:55:46] Started run 512 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:46] Error in run 505: Run already exists in server. Run id(s): {9048245}
[2018-04-11 21:55:46] Started run 513 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:47] Error in run 506: Run already exists in server. Run id(s): {9048209}
[2018-04-11 21:55:47] Started run 514 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:48] Error in run 507: Run already exists in server. Run id(s): {9048275}
[2018-04-11 21:55:48] Started run 515 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:48] Error in run 508: Run already exists in server. Run id(s): {9048256}
[2018-04-11 21:55:48] Started run 516 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:48] Error in run 509: Run already exists in server. Run id(s): {9048237}
[2018-04-11 21:55:48] Started run 517 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:49] Error in run 510: Run already exists in server. Run id(s): {9048259}
[2018-04-11 21:55:49] Started run 518 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:50] Error in run 511: Run already exists in server. Run id(s): {9048261}
[2018-04-11 21:55:50] Started run 519 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:50] Error in run 512: Run already exists in server. Run id(s): {9048352}
[2018-04-11 21:55:50] Started run 520 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:51] Error in run 513: Run already exists in server. Run id(s): {9048268}
[2018-04-11 21:55:51] Started run 521 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:51] Error in run 514: Run already exists in server. Run id(s): {9048292}
[2018-04-11 21:55:51] Started run 522 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:52] Error in run 515: Run already exists in server. Run id(s): {9048316}
[2018-04-11 21:55:52] Started run 523 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:53] Error in run 516: Run already exists in server. Run id(s): {9048309}
[2018-04-11 21:55:53] Started run 524 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:53] Error in run 517: Run already exists in server. Run id(s): {9048403}
[2018-04-11 21:55:53] Started run 525 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:53] Error in run 518: Run already exists in server. Run id(s): {9048333}
[2018-04-11 21:55:53] Started run 526 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:54] Error in run 519: Run already exists in server. Run id(s): {9048326}
[2018-04-11 21:55:54] Started run 527 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:55] Error in run 520: Run already exists in server. Run id(s): {9048322}
[2018-04-11 21:55:55] Started run 528 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:55] Error in run 521: Run already exists in server. Run id(s): {9048336}
[2018-04-11 21:55:55] Started run 529 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:56] Error in run 522: Run already exists in server. Run id(s): {9048459}
[2018-04-11 21:55:56] Started run 530 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:57] Error in run 523: Run already exists in server. Run id(s): {9048369}
[2018-04-11 21:55:57] Started run 531 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:57] Error in run 524: Run already exists in server. Run id(s): {9048347}
[2018-04-11 21:55:57] Started run 532 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:57] Error in run 525: Run already exists in server. Run id(s): {9048373}
[2018-04-11 21:55:57] Started run 533 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:58] Error in run 526: Run already exists in server. Run id(s): {9048420}
[2018-04-11 21:55:58] Started run 534 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:59] Error in run 527: Run already exists in server. Run id(s): {9048411}
[2018-04-11 21:55:59] Started run 535 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:59] Error in run 528: Run already exists in server. Run id(s): {9048458}
[2018-04-11 21:55:59] Started run 536 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:55:59] Error in run 529: Run already exists in server. Run id(s): {9048419}
[2018-04-11 21:55:59] Started run 537 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:00] Error in run 530: Run already exists in server. Run id(s): {9048379}
[2018-04-11 21:56:00] Started run 538 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:01] Error in run 531: Run already exists in server. Run id(s): {9048389}
[2018-04-11 21:56:01] Started run 539 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:02] Error in run 532: Run already exists in server. Run id(s): {9048531}
[2018-04-11 21:56:02] Started run 540 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:02] Error in run 533: Run already exists in server. Run id(s): {9048468}
[2018-04-11 21:56:02] Started run 541 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:02] Error in run 534: Run already exists in server. Run id(s): {9048536}
[2018-04-11 21:56:02] Started run 542 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:03] Error in run 535: Run already exists in server. Run id(s): {9048428}
[2018-04-11 21:56:03] Started run 543 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:04] Error in run 536: Run already exists in server. Run id(s): {9048525}
[2018-04-11 21:56:04] Started run 544 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:04] Error in run 537: Run already exists in server. Run id(s): {9048448}
[2018-04-11 21:56:04] Started run 545 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:05] Error in run 538: Run already exists in server. Run id(s): {9048476}
[2018-04-11 21:56:05] Started run 546 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:05] Error in run 539: Run already exists in server. Run id(s): {9048627}
[2018-04-11 21:56:05] Started run 547 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:06] Error in run 540: Run already exists in server. Run id(s): {9048495}
[2018-04-11 21:56:06] Started run 548 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:06] Error in run 541: Run already exists in server. Run id(s): {9048485}
[2018-04-11 21:56:06] Started run 549 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:07] Error in run 542: Run already exists in server. Run id(s): {9048540}
[2018-04-11 21:56:07] Started run 550 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:08] Error in run 543: Run already exists in server. Run id(s): {9048494}
[2018-04-11 21:56:08] Started run 551 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:08] Error in run 544: Run already exists in server. Run id(s): {9048635}
[2018-04-11 21:56:08] Started run 552 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:09] Error in run 545: Run already exists in server. Run id(s): {9048658}
[2018-04-11 21:56:09] Started run 553 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:09] Error in run 546: Run already exists in server. Run id(s): {9048544}
[2018-04-11 21:56:09] Started run 554 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:10] Error in run 547: Run already exists in server. Run id(s): {9048535}
[2018-04-11 21:56:10] Started run 555 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:11] Error in run 548: Run already exists in server. Run id(s): {9048557}
[2018-04-11 21:56:11] Started run 556 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:11] Error in run 549: Run already exists in server. Run id(s): {9048559}
[2018-04-11 21:56:11] Started run 557 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:11] Error in run 550: Run already exists in server. Run id(s): {9048688}
[2018-04-11 21:56:11] Started run 558 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:12] Error in run 551: Run already exists in server. Run id(s): {9048690}
[2018-04-11 21:56:12] Started run 559 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:13] Error in run 552: Run already exists in server. Run id(s): {9048654}
[2018-04-11 21:56:13] Started run 560 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:13] Error in run 553: Run already exists in server. Run id(s): {9048588}
[2018-04-11 21:56:13] Started run 561 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:14] Error in run 554: Run already exists in server. Run id(s): {9048662}
[2018-04-11 21:56:14] Started run 562 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:15] Error in run 555: Run already exists in server. Run id(s): {9048634}
[2018-04-11 21:56:15] Started run 563 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:15] Error in run 556: Run already exists in server. Run id(s): {9048665}
[2018-04-11 21:56:15] Started run 564 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:15] Error in run 557: Run already exists in server. Run id(s): {9048710}
[2018-04-11 21:56:15] Started run 565 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:16] Error in run 558: Run already exists in server. Run id(s): {9048668}
[2018-04-11 21:56:16] Started run 566 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:17] Error in run 559: Run already exists in server. Run id(s): {9048687}
[2018-04-11 21:56:17] Started run 567 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:17] Error in run 560: Run already exists in server. Run id(s): {9048713}
[2018-04-11 21:56:17] Started run 568 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:18] Error in run 561: Run already exists in server. Run id(s): {9048680}
[2018-04-11 21:56:18] Started run 569 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:18] Error in run 562: Run already exists in server. Run id(s): {9048672}
[2018-04-11 21:56:18] Started run 570 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:19] Error in run 563: Run already exists in server. Run id(s): {9048705}
[2018-04-11 21:56:19] Started run 571 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:20] Error in run 564: Run already exists in server. Run id(s): {9048683}
[2018-04-11 21:56:20] Started run 572 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:20] Error in run 565: Run already exists in server. Run id(s): {9049606, 9050441, 9050571, 9049774, 9050063, 9050162, 9050099, 9050610, 9050743, 9050265, 9049690, 9049914}
[2018-04-11 21:56:20] Started run 573 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:21] Error in run 566: Run already exists in server. Run id(s): {9048701}
[2018-04-11 21:56:21] Started run 574 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:21] Error in run 567: Run already exists in server. Run id(s): {9050304, 9049834, 9050156, 9050030, 9049934, 9050224, 9050736, 9050452, 9050133, 9049784, 9050075, 9050493, 9050622}
[2018-04-11 21:56:21] Started run 575 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:22] Error in run 568: Run already exists in server. Run id(s): {9048714}
[2018-04-11 21:56:22] Started run 576 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:22] Error in run 569: Run already exists in server. Run id(s): {9050180, 9050206, 9050439, 9049672, 9050397, 9050631, 9049771, 9050712, 9049969, 9049655, 9049944, 9050073, 9050238, 9050334, 9049886}
[2018-04-11 21:56:22] Started run 577 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:23] Error in run 570: Run already exists in server. Run id(s): {9048867}
[2018-04-11 21:56:23] Started run 578 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:24] Error in run 571: Run already exists in server. Run id(s): {9048822}
[2018-04-11 21:56:24] Started run 579 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:24] Error in run 573: Run already exists in server. Run id(s): {9048890}
[2018-04-11 21:56:24] Started run 580 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:24] Error in run 572: Run already exists in server. Run id(s): {9048821}
[2018-04-11 21:56:24] Started run 581 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:25] Error in run 574: Run already exists in server. Run id(s): {9048931}
[2018-04-11 21:56:25] Started run 582 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:26] Error in run 575: Run already exists in server. Run id(s): {9048955}
[2018-04-11 21:56:26] Started run 583 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:27] Error in run 576: Run already exists in server. Run id(s): {9048759}
[2018-04-11 21:56:27] Error in run 577: Run already exists in server. Run id(s): {9048878}
[2018-04-11 21:56:27] Started run 584 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:27] Started run 585 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:27] Error in run 578: Run already exists in server. Run id(s): {9048969}
[2018-04-11 21:56:27] Started run 586 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:28] Error in run 579: Run already exists in server. Run id(s): {9048843}
[2018-04-11 21:56:28] Started run 587 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:29] Error in run 580: Run already exists in server. Run id(s): {9048835}
[2018-04-11 21:56:29] Error in run 581: Run already exists in server. Run id(s): {9048840}
[2018-04-11 21:56:29] Started run 588 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:29] Started run 589 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:29] Error in run 582: Run already exists in server. Run id(s): {9048907}
[2018-04-11 21:56:29] Started run 590 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:30] Error in run 583: Run already exists in server. Run id(s): {9048805}
[2018-04-11 21:56:30] Started run 591 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:31] Error in run 584: Run already exists in server. Run id(s): {9048861}
[2018-04-11 21:56:31] Error in run 585: Run already exists in server. Run id(s): {9048809}
[2018-04-11 21:56:31] Started run 592 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:31] Started run 593 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:32] Error in run 586: Run already exists in server. Run id(s): {9048800}
[2018-04-11 21:56:32] Started run 594 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:33] Error in run 587: Run already exists in server. Run id(s): {9048830}
[2018-04-11 21:56:33] Started run 595 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:34] Error in run 588: Run already exists in server. Run id(s): {9048795}
[2018-04-11 21:56:34] Started run 596 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:34] Error in run 589: Run already exists in server. Run id(s): {9048855}
[2018-04-11 21:56:34] Started run 597 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:34] Error in run 590: Run already exists in server. Run id(s): {9049092, 9049989, 9049226, 9050515, 9049110, 9049367, 9049494, 9050140, 9049249, 9050281, 9049259, 9049794, 9049676, 9049165, 9050191, 9049552, 9050328, 9049049, 9050077, 9049309, 9050464, 9049442, 9049954, 9050599, 9050731, 9049068, 9049849}
[2018-04-11 21:56:34] Started run 598 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:35] Error in run 591: Run already exists in server. Run id(s): {9048922}
[2018-04-11 21:56:35] Started run 599 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:36] Error in run 592: Run already exists in server. Run id(s): {9048776}
[2018-04-11 21:56:36] Started run 600 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:36] Error in run 593: Run already exists in server. Run id(s): {9048814}
[2018-04-11 21:56:36] Started run 601 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:36] Error in run 594: Run already exists in server. Run id(s): {9049732, 9050246, 9049614, 9050518, 9050396, 9049889, 9049254, 9049406, 9049939, 9049559, 9049176, 9050713, 9049435, 9050587, 9049189, 9049318, 9049702, 9049959, 9050470, 9050351, 9049462, 9050103, 9049851}
[2018-04-11 21:56:36] Started run 602 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:37] Error in run 595: Run already exists in server. Run id(s): {9048915}
[2018-04-11 21:56:37] Started run 603 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:39] Error in run 597: Run already exists in server. Run id(s): {9048850}
[2018-04-11 21:56:39] Error in run 596: Run already exists in server. Run id(s): {9048876}
[2018-04-11 21:56:39] Error in run 598: Run already exists in server. Run id(s): {9048992}
[2018-04-11 21:56:39] Started run 604 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:39] Started run 606 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:39] Started run 605 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:39] Error in run 599: Run already exists in server. Run id(s): {9048750}
[2018-04-11 21:56:39] Started run 607 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:40] Error in run 600: Run already exists in server. Run id(s): {9048797}
[2018-04-11 21:56:40] Started run 608 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:40] Error in run 601: Run already exists in server. Run id(s): {9048764}
[2018-04-11 21:56:40] Started run 609 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:41] Error in run 602: Run already exists in server. Run id(s): {9048831}
[2018-04-11 21:56:41] Started run 610 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:42] Error in run 603: Run already exists in server. Run id(s): {9048916}
[2018-04-11 21:56:42] Started run 611 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:43] Error in run 606: Run already exists in server. Run id(s): {9049441, 9049508, 9049636, 9049926, 9049383, 9050202, 9050598, 9050726, 9049547, 9050573, 9049807, 9050321, 9050354, 9049333, 9049370, 9049307, 9049692, 9050079}
[2018-04-11 21:56:43] Error in run 604: Run already exists in server. Run id(s): {9050019, 9050500, 9049637, 9050661, 9049799, 9050756, 9050135, 9050392, 9050329, 9050234, 9049725, 9049887}
[2018-04-11 21:56:43] Started run 612 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:43] Started run 613 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:43] Error in run 605: Run already exists in server. Run id(s): {9048828}
[2018-04-11 21:56:43] Started run 614 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:44] Error in run 607: Run already exists in server. Run id(s): {9048997}
[2018-04-11 21:56:44] Started run 615 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:45] Error in run 609: Run already exists in server. Run id(s): {9048883}
[2018-04-11 21:56:45] Started run 616 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:45] Error in run 608: Run already exists in server. Run id(s): {9050789}
[2018-04-11 21:56:45] Started run 617 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:46] Error in run 610: Run already exists in server. Run id(s): {9051066}
[2018-04-11 21:56:46] Started run 618 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:46] Error in run 611: Run already exists in server. Run id(s): {9048928}
[2018-04-11 21:56:46] Started run 619 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:47] Error in run 613: Run already exists in server. Run id(s): {9048786}
[2018-04-11 21:56:47] Error in run 612: Run already exists in server. Run id(s): {9048782}
[2018-04-11 21:56:47] Started run 620 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:47] Started run 621 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:48] Error in run 614: Run already exists in server. Run id(s): {9050560, 9050624, 9050691, 9050505, 9050476, 9050125, 9050287, 9050384, 9049684, 9050042, 9050332, 9049917, 9049790}
[2018-04-11 21:56:48] Started run 622 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:48] Error in run 615: Run already exists in server. Run id(s): {9048812}
[2018-04-11 21:56:48] Started run 623 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:49] Error in run 616: Run already exists in server. Run id(s): {9048763}
[2018-04-11 21:56:49] Started run 624 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:49] Error in run 617: Run already exists in server. Run id(s): {9048842}
[2018-04-11 21:56:49] Started run 625 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:50] Error in run 618: Run already exists in server. Run id(s): {9050698, 9050462, 9050647}
[2018-04-11 21:56:50] Started run 626 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:51] Error in run 619: Run already exists in server. Run id(s): {9048774}
[2018-04-11 21:56:51] Started run 627 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:52] Error in run 620: Run already exists in server. Run id(s): {9048848}
[2018-04-11 21:56:52] Started run 628 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:52] Error in run 621: Run already exists in server. Run id(s): {9048962}
[2018-04-11 21:56:52] Started run 629 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:52] Error in run 622: Run already exists in server. Run id(s): {9050112, 9050241, 9049666, 9050529, 9050404, 9050653, 9049478, 9050759, 9050569, 9050154, 9049451, 9049720, 9049549, 9049613, 9049848, 9049586, 9050322, 9049560, 9049949, 9050047}
[2018-04-11 21:56:52] Started run 630 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:53] Error in run 623: Run already exists in server. Run id(s): {9048912}
[2018-04-11 21:56:53] Started run 631 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:54] Error in run 624: Run already exists in server. Run id(s): {9048781}
[2018-04-11 21:56:54] Error in run 625: Run already exists in server. Run id(s): {9048882}
[2018-04-11 21:56:54] Started run 632 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:54] Started run 633 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:55] Error in run 626: Run already exists in server. Run id(s): {9048810}
[2018-04-11 21:56:55] Started run 634 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:56] Error in run 627: Run already exists in server. Run id(s): {9049729, 9050597, 9049830, 9050247, 9050024, 9049865, 9050438, 9050502, 9050729, 9050542, 9049650, 9050005, 9049756, 9050110}
[2018-04-11 21:56:56] Started run 635 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:57] Error in run 628: Run already exists in server. Run id(s): {9048793}
[2018-04-11 21:56:57] Error in run 629: Run already exists in server. Run id(s): {9048857}
[2018-04-11 21:56:57] Started run 636 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:57] Started run 637 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:57] Error in run 630: Run already exists in server. Run id(s): {9048986}
[2018-04-11 21:56:57] Started run 638 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:57] Error in run 631: Run already exists in server. Run id(s): {9048959}
[2018-04-11 21:56:57] Started run 639 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:59] Error in run 632: Run already exists in server. Run id(s): {9048940}
[2018-04-11 21:56:59] Started run 640 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:59] Error in run 633: Run already exists in server. Run id(s): {9048768}
[2018-04-11 21:56:59] Started run 641 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:56:59] Error in run 634: Run already exists in server. Run id(s): {9048985}
[2018-04-11 21:56:59] Started run 642 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:00] Error in run 635: Run already exists in server. Run id(s): {9048757}
[2018-04-11 21:57:00] Started run 643 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:01] Error in run 638: Run already exists in server. Run id(s): {9049480, 9050376, 9049084, 9050130, 9049237, 9049624, 9049883, 9049372, 9049132, 9049901, 9049519, 9049393, 9050683, 9049788, 9049277, 9050176, 9050309, 9049929, 9049175, 9049567, 9050208, 9049704, 9050091, 9049070, 9050606, 9049460, 9050489, 9049596, 9049343}
[2018-04-11 21:57:01] Error in run 636: Run already exists in server. Run id(s): {9048833}
[2018-04-11 21:57:01] Started run 644 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:01] Error in run 637: Run already exists in server. Run id(s): {9049761, 9050242, 9050213, 9050342, 9050794, 9050478, 9050064, 9050611, 9049782, 9049686, 9050014, 9049919}
[2018-04-11 21:57:01] Started run 646 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:01] Started run 645 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:02] Error in run 639: Run already exists in server. Run id(s): {9048837}
[2018-04-11 21:57:02] Started run 647 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:03] Error in run 640: Run already exists in server. Run id(s): {9048967}
[2018-04-11 21:57:03] Started run 648 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:03] Error in run 641: Run already exists in server. Run id(s): {9048815}
[2018-04-11 21:57:03] Started run 649 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:04] Error in run 642: Run already exists in server. Run id(s): {9048801}
[2018-04-11 21:57:04] Started run 650 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:05] Error in run 643: Run already exists in server. Run id(s): {9048785}
[2018-04-11 21:57:05] Started run 651 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:06] Error in run 644: Run already exists in server. Run id(s): {9048889}
[2018-04-11 21:57:06] Started run 652 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:06] Error in run 645: Run already exists in server. Run id(s): {9048847}
[2018-04-11 21:57:06] Started run 653 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:06] Error in run 646: Run already exists in server. Run id(s): {9048858}
[2018-04-11 21:57:06] Started run 654 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:07] Error in run 647: Run already exists in server. Run id(s): {9048998}
[2018-04-11 21:57:07] Started run 655 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:08] Error in run 648: Run already exists in server. Run id(s): {9049664, 9050048, 9050240, 9050465, 9050562, 9049566, 9049797, 9049224, 9049897, 9050704, 9049265, 9049617, 9050098, 9049876, 9050359, 9049402, 9049501, 9049342}
[2018-04-11 21:57:08] Started run 656 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:08] Error in run 649: Run already exists in server. Run id(s): {9048825}
[2018-04-11 21:57:08] Started run 657 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:08] Error in run 650: Run already exists in server. Run id(s): {9050017, 9049958, 9050412, 9049842, 9049810, 9050131, 9050226, 9050771, 9050327, 9050492, 9050652}
[2018-04-11 21:57:08] Started run 658 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:09] Error in run 651: Run already exists in server. Run id(s): {9048938}
[2018-04-11 21:57:09] Started run 659 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:10] Error in run 652: Run already exists in server. Run id(s): {9048893}
[2018-04-11 21:57:10] Started run 660 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:10] Error in run 653: Run already exists in server. Run id(s): {9048864}
[2018-04-11 21:57:10] Error in run 654: Run already exists in server. Run id(s): {9050114, 9049731, 9049820, 9049763, 9050786, 9050379, 9050635, 9049709, 9050575, 9050263, 9050296, 9049948}
[2018-04-11 21:57:10] Started run 661 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:10] Started run 662 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:11] Error in run 655: Run already exists in server. Run id(s): {9048862}
[2018-04-11 21:57:11] Started run 663 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:12] Error in run 656: Run already exists in server. Run id(s): {9049861, 9049957, 9050633, 9050447, 9050160, 9050353, 9049748, 9049622, 9050071, 9050428, 9050777, 9050236}
[2018-04-11 21:57:12] Started run 664 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:12] Error in run 657: Run already exists in server. Run id(s): {9048918}
[2018-04-11 21:57:12] Started run 665 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:13] Error in run 658: Run already exists in server. Run id(s): {9048949}
[2018-04-11 21:57:13] Started run 666 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:14] Error in run 659: Run already exists in server. Run id(s): {9048851}
[2018-04-11 21:57:14] Started run 667 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:15] Error in run 660: Run already exists in server. Run id(s): {9048978}
[2018-04-11 21:57:15] Started run 668 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:15] Error in run 662: Run already exists in server. Run id(s): {9049607, 9050760, 9049097, 9050388, 9049503, 9049381, 9049015, 9050040, 9049147, 9049276, 9049918, 9049026, 9050434, 9050184, 9049034, 9050314, 9050072, 9049432, 9049182, 9049058, 9050467, 9049841, 9049591, 9049721, 9050618, 9049340, 9049214}
[2018-04-11 21:57:15] Started run 669 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:15] Error in run 661: Run already exists in server. Run id(s): {9048972}
[2018-04-11 21:57:15] Started run 670 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:15] Error in run 663: Run already exists in server. Run id(s): {9049696, 9049859, 9050088, 9050457, 9050539, 9050348, 9050668, 9049999, 9050228, 9050174, 9049753, 9049726}
[2018-04-11 21:57:15] Started run 671 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:17] Error in run 664: Run already exists in server. Run id(s): {9048948}
[2018-04-11 21:57:17] Started run 672 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:17] Error in run 665: Run already exists in server. Run id(s): {9048897}
[2018-04-11 21:57:17] Started run 673 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:17] Error in run 666: Run already exists in server. Run id(s): {9049952, 9050724, 9049789, 9050056, 9050215, 9050279, 9050159, 9050512, 9049747, 9049972, 9050451, 9050106, 9050651, 9049661, 9049854}
[2018-04-11 21:57:17] Started run 674 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:18] Error in run 667: Run already exists in server. Run id(s): {9048872}
[2018-04-11 21:57:18] Started run 675 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:19] Error in run 668: Run already exists in server. Run id(s): {9048852}
[2018-04-11 21:57:19] Started run 676 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:19] Error in run 669: Run already exists in server. Run id(s): {9049350, 9049223, 9049479, 9049743, 9049871, 9050639, 9049106, 9050134, 9050262, 9049117, 9050015, 9049642, 9050798, 9049394, 9049014, 9050426, 9049025, 9049546, 9050059, 9049037, 9050317, 9049298, 9049426, 9049174, 9049052, 9049057, 9049826, 9049589, 9049212, 9049599}
[2018-04-11 21:57:19] Started run 677 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:19] Error in run 670: Run already exists in server. Run id(s): {9048933}
[2018-04-11 21:57:19] Started run 678 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:20] Error in run 671: Run already exists in server. Run id(s): {9048873}
[2018-04-11 21:57:20] Started run 679 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:21] Error in run 672: Run already exists in server. Run id(s): {9049361, 9049745, 9049629, 9049118, 9049504, 9050400, 9049128, 9050153, 9050538, 9050666, 9049516, 9049773, 9049905, 9050293, 9049658, 9049288, 9049306, 9049053, 9049059, 9049188, 9049443, 9049197, 9050096, 9049974, 9050487, 9049592, 9049465, 9049210, 9049083, 9050365}
[2018-04-11 21:57:21] Started run 680 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:21] Error in run 673: Run already exists in server. Run id(s): {9048913}
[2018-04-11 21:57:21] Started run 681 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:22] Error in run 674: Run already exists in server. Run id(s): {9049795, 9049895, 9050697, 9049770, 9049644, 9050061, 9050252, 9050509, 9050481, 9050036, 9049845, 9050358, 9050204, 9049695}
[2018-04-11 21:57:22] Started run 682 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:23] Error in run 675: Run already exists in server. Run id(s): {9048952}
[2018-04-11 21:57:23] Started run 683 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:24] Error in run 676: Run already exists in server. Run id(s): {9048917}
[2018-04-11 21:57:24] Started run 684 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:24] Error in run 677: Run already exists in server. Run id(s): {9048877}
[2018-04-11 21:57:24] Error in run 678: Run already exists in server. Run id(s): {9048894}
[2018-04-11 21:57:24] Started run 685 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:24] Started run 686 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:25] Error in run 679: Run already exists in server. Run id(s): {9049088, 9049482, 9050380, 9050008, 9049374, 9049759, 9049891, 9049126, 9050546, 9049283, 9049031, 9050313, 9050187, 9049164, 9050699, 9049042, 9049942, 9049051, 9050081, 9049698, 9049326, 9049583, 9049204, 9049464}
[2018-04-11 21:57:25] Started run 687 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:26] Error in run 680: Run already exists in server. Run id(s): {9049985, 9049922, 9050275, 9050436, 9050564, 9050690, 9050225, 9050609, 9050196, 9050037, 9050356}
[2018-04-11 21:57:26] Started run 688 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:26] Error in run 681: Run already exists in server. Run id(s): {9048886}
[2018-04-11 21:57:26] Started run 689 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:26] Error in run 682: Run already exists in server. Run id(s): {9048880}
[2018-04-11 21:57:26] Started run 690 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:27] Error in run 683: Run already exists in server. Run id(s): {9048937}
[2018-04-11 21:57:27] Started run 691 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:28] Error in run 684: Run already exists in server. Run id(s): {9048939}
[2018-04-11 21:57:28] Started run 692 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:28] Error in run 686: Run already exists in server. Run id(s): {9048896}
[2018-04-11 21:57:28] Started run 693 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:28] Error in run 685: Run already exists in server. Run id(s): {9050517, 9050703}
[2018-04-11 21:57:28] Started run 694 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:29] Error in run 687: Run already exists in server. Run id(s): {9051036}
[2018-04-11 21:57:29] Started run 695 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:30] Error in run 688: Run already exists in server. Run id(s): {9048903}
[2018-04-11 21:57:30] Started run 696 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:30] Error in run 689: Run already exists in server. Run id(s): {9050673, 9050626}
[2018-04-11 21:57:30] Started run 697 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:31] Error in run 690: Run already exists in server. Run id(s): {9048921}
[2018-04-11 21:57:31] Started run 698 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:32] Error in run 691: Run already exists in server. Run id(s): {9048908}
[2018-04-11 21:57:32] Started run 699 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:33] Error in run 692: Run already exists in server. Run id(s): {9049474, 9049603, 9049221, 9049101, 9049750, 9049239, 9049631, 9049007, 9050289, 9050545, 9049011, 9049143, 9049019, 9049153, 9049923, 9050693, 9049414, 9050183, 9049032, 9050445, 9049813, 9050070, 9049561, 9049434, 9049050, 9049316, 9049063, 9049074, 9049331, 9049594}
[2018-04-11 21:57:33] Started run 700 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:33] Error in run 693: Run already exists in server. Run id(s): {9050593, 9049699, 9049062, 9049353, 9049837, 9049422, 9049518, 9049968, 9050094, 9050257, 9049299, 9049236, 9049173, 9050294, 9049111, 9050550, 9049817, 9050716}
[2018-04-11 21:57:33] Error in run 694: Run already exists in server. Run id(s): {9049001}
[2018-04-11 21:57:33] Started run 701 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:33] Started run 702 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:34] Error in run 695: Run already exists in server. Run id(s): {9048910}
[2018-04-11 21:57:34] Started run 703 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:35] Error in run 696: Run already exists in server. Run id(s): {9048914}
[2018-04-11 21:57:35] Error in run 697: Run already exists in server. Run id(s): {9048925}
[2018-04-11 21:57:35] Started run 704 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:35] Started run 705 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:35] Error in run 698: Run already exists in server. Run id(s): {9048926}
[2018-04-11 21:57:35] Started run 706 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:36] Error in run 699: Run already exists in server. Run id(s): {9048996}
[2018-04-11 21:57:36] Started run 707 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:37] Error in run 700: Run already exists in server. Run id(s): {9048906}
[2018-04-11 21:57:37] Started run 708 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:37] Error in run 701: Run already exists in server. Run id(s): {9050145, 9050170, 9050027, 9050221, 9050649, 9050422, 9050521, 9050074, 9050363, 9050781}
[2018-04-11 21:57:37] Error in run 702: Run already exists in server. Run id(s): {9050720, 9049507, 9050371, 9049447, 9050343, 9049688, 9049805, 9049998, 9050093, 9050253, 9049950, 9049363, 9050579, 9049557, 9049621, 9049304, 9049246}
[2018-04-11 21:57:37] Started run 709 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:37] Started run 710 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:38] Error in run 703: Run already exists in server. Run id(s): {9050503, 9049615, 9049491, 9050266, 9049123, 9050147, 9049768, 9049003, 9049387, 9049135, 9049520, 9050420, 9049013, 9050676, 9050041, 9049021, 9049279, 9049028, 9049677, 9050455, 9049440, 9049185, 9049061, 9049574, 9049835, 9049971, 9049338, 9049211, 9049085, 9049470}
[2018-04-11 21:57:38] Started run 711 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:39] Error in run 705: Run already exists in server. Run id(s): {9049346, 9049988, 9050632, 9049513, 9049291, 9050687, 9049870, 9049264, 9050320, 9050259, 9050100, 9049461, 9049749, 9049399, 9049528, 9049303, 9050523, 9050364, 9049662, 9050010}
[2018-04-11 21:57:39] Error in run 704: Run already exists in server. Run id(s): {9050776, 9050574, 9050641, 9050520, 9050429}
[2018-04-11 21:57:39] Started run 712 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:39] Started run 713 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:40] Error in run 706: Run already exists in server. Run id(s): {9049857, 9050245, 9049094, 9049352, 9050765, 9049619, 9049752, 9049497, 9049256, 9050536, 9049645, 9049400, 9050430, 9049663, 9049154, 9049290, 9049424, 9049554, 9050083, 9049458, 9049209, 9049978}
[2018-04-11 21:57:40] Started run 714 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:41] Error in run 707: Run already exists in server. Run id(s): {9048956}
[2018-04-11 21:57:41] Started run 715 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:42] Error in run 708: Run already exists in server. Run id(s): {9049475, 9050115, 9050382, 9050003, 9049240, 9049252, 9049765, 9049391, 9049136, 9049009, 9049527, 9049915, 9050555, 9049024, 9049036, 9050702, 9049168, 9050199, 9049821, 9049054, 9049693, 9049569, 9049195, 9049707, 9049328, 9049086}
[2018-04-11 21:57:42] Started run 716 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:42] Error in run 709: Run already exists in server. Run id(s): {9048983}
[2018-04-11 21:57:42] Error in run 710: Run already exists in server. Run id(s): {9049760, 9050179, 9049639, 9049801, 9049739, 9049675, 9049612, 9050031, 9049840, 9050288, 9050739, 9049912, 9050585, 9050399}
[2018-04-11 21:57:42] Started run 717 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:42] Started run 718 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:43] Error in run 711: Run already exists in server. Run id(s): {9050657, 9050151, 9050409, 9050012, 9050737, 9050326, 9050556}
[2018-04-11 21:57:43] Started run 719 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:44] Error in run 712: Run already exists in server. Run id(s): {9048974}
[2018-04-11 21:57:44] Error in run 713: Run already exists in server. Run id(s): {9049792, 9050369, 9050020, 9050533, 9049734, 9050282, 9049643, 9049965, 9049679, 9049874, 9050261, 9050423, 9050171, 9050685}
[2018-04-11 21:57:44] Started run 720 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:44] Started run 721 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:44] Error in run 714: Run already exists in server. Run id(s): {9048989}
[2018-04-11 21:57:44] Started run 722 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:45] Error in run 715: Run already exists in server. Run id(s): {9050497, 9049222, 9050374, 9050250, 9049355, 9049755, 9049115, 9049505, 9049127, 9049471, 9049855, 9050675, 9050308, 9049413, 9049671, 9049292, 9049167, 9049564, 9050210, 9050596, 9050087, 9049588, 9049979, 9049727}
[2018-04-11 21:57:45] Started run 723 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:46] Error in run 716: Run already exists in server. Run id(s): {9049349, 9049735, 9049096, 9049234, 9050386, 9049620, 9050269, 9050149, 9049389, 9050548, 9049274, 9049146, 9049029, 9050695, 9049041, 9049183, 9049573, 9049961, 9049071, 9049200, 9049843, 9049469, 9049982}
[2018-04-11 21:57:46] Started run 724 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:47] Error in run 717: Run already exists in server. Run id(s): {9050212, 9050311, 9050475, 9050700, 9050554}
[2018-04-11 21:57:47] Error in run 718: Run already exists in server. Run id(s): {9048964}
[2018-04-11 21:57:47] Started run 725 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:47] Started run 726 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:47] Error in run 719: Run already exists in server. Run id(s): {9048973}
[2018-04-11 21:57:47] Started run 727 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:48] Error in run 721: Run already exists in server. Run id(s): {9048966}
[2018-04-11 21:57:48] Error in run 720: Run already exists in server. Run id(s): {9048975}
[2018-04-11 21:57:48] Started run 728 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:48] Started run 729 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:49] Error in run 722: Run already exists in server. Run id(s): {9048991}
[2018-04-11 21:57:49] Started run 730 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:50] Error in run 723: Run already exists in server. Run id(s): {9049090, 9049477, 9049351, 9050638, 9050766, 9049105, 9050513, 9049754, 9050394, 9050271, 9050025, 9050671, 9049267, 9049652, 9050163, 9049532, 9049148, 9049928, 9049296, 9050195, 9050068, 9049439, 9049824, 9050468, 9049578, 9049202, 9049079, 9049335}
[2018-04-11 21:57:50] Started run 731 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:51] Error in run 724: Run already exists in server. Run id(s): {9048977}
[2018-04-11 21:57:51] Started run 732 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:51] Error in run 726: Run already exists in server. Run id(s): {9048995}
[2018-04-11 21:57:51] Error in run 725: Run already exists in server. Run id(s): {9049473, 9049093, 9049357, 9049232, 9049247, 9050528, 9050273, 9050405, 9049396, 9049909, 9049142, 9050165, 9050044, 9049280, 9049410, 9049685, 9049046, 9049814, 9050717, 9049311, 9050594, 9049577, 9049066, 9049199, 9049332, 9050357, 9049724, 9049853}
[2018-04-11 21:57:51] Started run 733 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:51] Started run 734 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:52] Error in run 727: Run already exists in server. Run id(s): {9050336, 9050049, 9050307, 9049496, 9049255, 9050654, 9049193, 9049162, 9049418, 9049324, 9050442, 9050270, 9049712, 9049651, 9049941, 9049558, 9050229, 9049368, 9049467, 9049819}
[2018-04-11 21:57:52] Started run 735 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:53] Error in run 729: Run already exists in server. Run id(s): {9049348, 9050123, 9049485, 9049628, 9049250, 9049379, 9050277, 9049900, 9049271, 9050300, 9049669, 9049543, 9050055, 9050568, 9049295, 9050707, 9050454, 9049446, 9050602, 9050223, 9049205, 9049718, 9049847, 9049215}
[2018-04-11 21:57:53] Error in run 728: Run already exists in server. Run id(s): {9050692, 9050534, 9050410, 9050285, 9050141}
[2018-04-11 21:57:53] Started run 736 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:53] Started run 737 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:53] Error in run 730: Run already exists in server. Run id(s): {9051056}
[2018-04-11 21:57:53] Started run 738 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:54] Error in run 731: Run already exists in server. Run id(s): {9050433, 9050283, 9049995, 9050158, 9050127, 9050735, 9050482, 9050617, 9049885}
[2018-04-11 21:57:54] Started run 739 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:55] Error in run 732: Run already exists in server. Run id(s): {9049336, 9049089, 9049860, 9050507, 9049245, 9050143, 9049130, 9049648, 9050292, 9049401, 9049278, 9050437, 9049542, 9050566, 9050315, 9050190, 9049186, 9049444, 9050728, 9049714, 9049976, 9050623}
[2018-04-11 21:57:55] Started run 740 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:55] Error in run 733: Run already exists in server. Run id(s): {9049986, 9049605, 9050248, 9049737, 9049229, 9050769, 9050645, 9049373, 9049506, 9049124, 9049892, 9050406, 9049138, 9050552, 9049530, 9049018, 9049404, 9050310, 9049802, 9050186, 9049421, 9049294, 9049172, 9049045, 9049180, 9049572, 9049065, 9050603, 9049708, 9050095, 9049078, 9049466}
[2018-04-11 21:57:55] Error in run 734: Run already exists in server. Run id(s): {9048982}
[2018-04-11 21:57:55] Started run 741 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:55] Started run 742 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:56] Error in run 735: Run already exists in server. Run id(s): {9050117, 9049243, 9049502, 9049122, 9049378, 9050663, 9050280, 9049131, 9049012, 9049403, 9049038, 9049937, 9049563, 9049822, 9050339, 9050086, 9049322, 9049067, 9049196, 9050732, 9049717, 9050486}
[2018-04-11 21:57:56] Started run 743 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:57] Error in run 736: Run already exists in server. Run id(s): {9050787}
[2018-04-11 21:57:57] Started run 744 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:58] Error in run 737: Run already exists in server. Run id(s): {9049984, 9049099, 9049377, 9050402, 9049894, 9049002, 9049005, 9050032, 9049395, 9049268, 9049017, 9049149, 9049158, 9050182, 9049800, 9049545, 9049040, 9049681, 9049300, 9050583, 9050711, 9049310, 9049055, 9050082, 9049579, 9049457, 9049207, 9050105, 9050366}
[2018-04-11 21:57:58] Started run 745 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:58] Error in run 738: Run already exists in server. Run id(s): {9049730, 9050120, 9049610, 9049366, 9049244, 9050659, 9050023, 9049899, 9049388, 9049524, 9050302, 9049793, 9049286, 9049673, 9049301, 9050581, 9050207, 9050723, 9050469, 9049321, 9049456, 9049590}
[2018-04-11 21:57:58] Started run 746 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:57:59] Error in run 739: Run already exists in server. Run id(s): {9050018, 9049375, 9049924, 9049956, 9050758, 9049416, 9049641, 9050346, 9049483, 9049868, 9049584, 9049459, 9050644, 9050424, 9050490, 9050139, 9049884, 9050173, 9049758, 9049535}
[2018-04-11 21:57:59] Started run 747 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:00] Error in run 740: Run already exists in server. Run id(s): {9049600, 9049109, 9049495, 9049248, 9049125, 9049385, 9049515, 9049647, 9050033, 9049140, 9049781, 9050298, 9049150, 9049022, 9049407, 9050570, 9049931, 9050062, 9050319, 9049809, 9050198, 9049431, 9049048, 9049177, 9050458, 9050718, 9049320, 9049449, 9049076, 9049593}
[2018-04-11 21:58:00] Started run 748 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:00] Error in run 742: Run already exists in server. Run id(s): {9051005}
[2018-04-11 21:58:00] Error in run 741: Run already exists in server. Run id(s): {9050970}
[2018-04-11 21:58:00] Started run 749 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:00] Started run 750 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:01] Error in run 743: Run already exists in server. Run id(s): {9048999}
[2018-04-11 21:58:01] Started run 751 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:02] Error in run 744: Run already exists in server. Run id(s): {9049121, 9049314, 9049445, 9049541, 9049191, 9049384, 9049832, 9050057, 9049867, 9050474, 9049711, 9049935, 9050674, 9049626, 9049141, 9050230, 9049242, 9050333, 9050559}
[2018-04-11 21:58:02] Started run 752 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:02] Error in run 745: Run already exists in server. Run id(s): {9050498, 9050053, 9050122, 9050413, 9050578, 9050613, 9050678, 9050168, 9050235}
[2018-04-11 21:58:02] Started run 753 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:02] Error in run 746: Run already exists in server. Run id(s): {9050969}
[2018-04-11 21:58:02] Started run 754 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:03] Error in run 747: Run already exists in server. Run id(s): {9049635, 9050615, 9050341, 9049769, 9050544, 9049523, 9049812, 9049555, 9050035, 9049943, 9050197, 9050682, 9050463}
[2018-04-11 21:58:03] Started run 755 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:04] Error in run 748: Run already exists in server. Run id(s): {9050368, 9050043, 9049710, 9050799, 9049776, 9050194, 9050007, 9050425, 9049850, 9049947, 9050619}
[2018-04-11 21:58:04] Started run 756 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:04] Error in run 749: Run already exists in server. Run id(s): {9050793}
[2018-04-11 21:58:04] Started run 757 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:05] Error in run 750: Run already exists in server. Run id(s): {9050722, 9050643, 9050491, 9050589, 9050398, 9050335}
[2018-04-11 21:58:05] Started run 758 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:05] Error in run 751: Run already exists in server. Run id(s): {9050752}
[2018-04-11 21:58:05] Started run 759 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:06] Error in run 752: Run already exists in server. Run id(s): {9050656, 9049700, 9049798, 9050792, 9050473, 9050255, 9049488, 9050128, 9049906, 9049587, 9050324, 9050389, 9050620, 9049980}
[2018-04-11 21:58:06] Started run 760 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:07] Error in run 753: Run already exists in server. Run id(s): {9050815}
[2018-04-11 21:58:07] Started run 761 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:07] Error in run 754: Run already exists in server. Run id(s): {9050837}
[2018-04-11 21:58:07] Started run 762 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:08] Error in run 755: Run already exists in server. Run id(s): {9050877}
[2018-04-11 21:58:08] Started run 763 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:09] Error in run 756: Run already exists in server. Run id(s): {9050889}
[2018-04-11 21:58:09] Started run 764 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:09] Error in run 757: Run already exists in server. Run id(s): {9050834}
[2018-04-11 21:58:09] Started run 765 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:09] Error in run 758: Run already exists in server. Run id(s): {9050780}
[2018-04-11 21:58:09] Started run 766 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:10] Error in run 759: Run already exists in server. Run id(s): {9050862}
[2018-04-11 21:58:10] Started run 767 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:11] Error in run 760: Run already exists in server. Run id(s): {9050860}
[2018-04-11 21:58:11] Started run 768 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:11] Error in run 761: Run already exists in server. Run id(s): {9050802}
[2018-04-11 21:58:11] Started run 769 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:11] Error in run 762: Run already exists in server. Run id(s): {9050828}
[2018-04-11 21:58:11] Started run 770 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:13] Error in run 763: Run already exists in server. Run id(s): {9051001}
[2018-04-11 21:58:13] Started run 771 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:13] Error in run 764: Run already exists in server. Run id(s): {9050874}
[2018-04-11 21:58:13] Started run 772 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:13] Error in run 765: Run already exists in server. Run id(s): {9050868}
[2018-04-11 21:58:13] Started run 773 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:14] Error in run 766: Run already exists in server. Run id(s): {9050933}
[2018-04-11 21:58:14] Started run 774 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:14] Error in run 767: Run already exists in server. Run id(s): {9050856}
[2018-04-11 21:58:14] Started run 775 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:16] Error in run 768: Run already exists in server. Run id(s): {9050832}
[2018-04-11 21:58:16] Error in run 770: Run already exists in server. Run id(s): {9050852}
[2018-04-11 21:58:16] Started run 776 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:16] Error in run 769: Run already exists in server. Run id(s): {9050928}
[2018-04-11 21:58:16] Started run 777 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:16] Started run 778 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:17] Error in run 771: Run already exists in server. Run id(s): {9050821}
[2018-04-11 21:58:17] Started run 779 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:18] Error in run 772: Run already exists in server. Run id(s): {9050839}
[2018-04-11 21:58:18] Started run 780 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:18] Error in run 773: Run already exists in server. Run id(s): {9050842}
[2018-04-11 21:58:18] Started run 781 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:18] Error in run 774: Run already exists in server. Run id(s): {9050935}
[2018-04-11 21:58:18] Started run 782 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:19] Error in run 775: Run already exists in server. Run id(s): {9050867}
[2018-04-11 21:58:19] Started run 783 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:20] Error in run 776: Run already exists in server. Run id(s): {9050878}
[2018-04-11 21:58:20] Started run 784 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:20] Error in run 777: Run already exists in server. Run id(s): {9051007}
[2018-04-11 21:58:20] Error in run 778: Run already exists in server. Run id(s): {9051002}
[2018-04-11 21:58:20] Started run 785 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:20] Started run 786 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:22] Error in run 779: Run already exists in server. Run id(s): {9050804}
[2018-04-11 21:58:22] Started run 787 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:22] Error in run 780: Run already exists in server. Run id(s): {9050827}
[2018-04-11 21:58:22] Started run 788 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:23] Error in run 781: Run already exists in server. Run id(s): {9050869}
[2018-04-11 21:58:23] Started run 789 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:23] Error in run 782: Run already exists in server. Run id(s): {9050921}
[2018-04-11 21:58:23] Started run 790 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:23] Error in run 783: Run already exists in server. Run id(s): {9051014}
[2018-04-11 21:58:23] Started run 791 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:25] Error in run 784: Run already exists in server. Run id(s): {9050812}
[2018-04-11 21:58:25] Started run 792 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:25] Error in run 786: Run already exists in server. Run id(s): {9050796}
[2018-04-11 21:58:25] Error in run 785: Run already exists in server. Run id(s): {9050844}
[2018-04-11 21:58:25] Started run 793 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:25] Started run 794 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:26] Error in run 787: Run already exists in server. Run id(s): {9050849}
[2018-04-11 21:58:26] Started run 795 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:27] Error in run 788: Run already exists in server. Run id(s): {9050903}
[2018-04-11 21:58:27] Started run 796 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:27] Error in run 789: Run already exists in server. Run id(s): {9050817}
[2018-04-11 21:58:27] Error in run 790: Run already exists in server. Run id(s): {9050824}
[2018-04-11 21:58:27] Started run 797 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:27] Started run 798 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:28] Error in run 791: Run already exists in server. Run id(s): {9050871}
[2018-04-11 21:58:28] Started run 799 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:29] Error in run 792: Run already exists in server. Run id(s): {9050954}
[2018-04-11 21:58:29] Started run 800 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:29] Error in run 793: Run already exists in server. Run id(s): {9050851}
[2018-04-11 21:58:29] Started run 801 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:30] Error in run 794: Run already exists in server. Run id(s): {9050993}
[2018-04-11 21:58:30] Started run 802 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:31] Error in run 795: Run already exists in server. Run id(s): {9050838}
[2018-04-11 21:58:31] Started run 803 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:31] Error in run 796: Run already exists in server. Run id(s): {9050931}
[2018-04-11 21:58:31] Started run 804 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:32] Error in run 797: Run already exists in server. Run id(s): {9050843}
[2018-04-11 21:58:32] Error in run 798: Run already exists in server. Run id(s): {9050952}
[2018-04-11 21:58:32] Started run 805 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:32] Started run 806 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:33] Error in run 799: Run already exists in server. Run id(s): {9050820}
[2018-04-11 21:58:33] Started run 807 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:34] Error in run 800: Run already exists in server. Run id(s): {9050846}
[2018-04-11 21:58:34] Started run 808 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:34] Error in run 801: Run already exists in server. Run id(s): {9050848}
[2018-04-11 21:58:34] Started run 809 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:34] Error in run 802: Run already exists in server. Run id(s): {9050836}
[2018-04-11 21:58:34] Started run 810 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:35] Error in run 803: Run already exists in server. Run id(s): {9050813}
[2018-04-11 21:58:35] Started run 811 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:36] Error in run 804: Run already exists in server. Run id(s): {9050934}
[2018-04-11 21:58:36] Started run 812 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:36] Error in run 805: Run already exists in server. Run id(s): {9050992}
[2018-04-11 21:58:36] Started run 813 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:37] Error in run 806: Run already exists in server. Run id(s): {9050819}
[2018-04-11 21:58:37] Started run 814 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:38] Error in run 807: Run already exists in server. Run id(s): {9050864}
[2018-04-11 21:58:38] Started run 815 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:38] Error in run 808: Run already exists in server. Run id(s): {9050900}
[2018-04-11 21:58:38] Started run 816 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:38] Error in run 809: Run already exists in server. Run id(s): {9050983}
[2018-04-11 21:58:38] Started run 817 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:39] Error in run 810: Run already exists in server. Run id(s): {9050830}
[2018-04-11 21:58:39] Started run 818 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:40] Error in run 811: Run already exists in server. Run id(s): {9050919}
[2018-04-11 21:58:40] Started run 819 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:40] Error in run 812: Run already exists in server. Run id(s): {9050847}
[2018-04-11 21:58:40] Started run 820 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:41] Error in run 813: Run already exists in server. Run id(s): {9050825}
[2018-04-11 21:58:41] Started run 821 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:41] Error in run 814: Run already exists in server. Run id(s): {9050816}
[2018-04-11 21:58:41] Started run 822 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:42] Error in run 815: Run already exists in server. Run id(s): {9050971}
[2018-04-11 21:58:42] Started run 823 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:43] Error in run 816: Run already exists in server. Run id(s): {9050850}
[2018-04-11 21:58:43] Started run 824 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:43] Error in run 817: Run already exists in server. Run id(s): {9050863}
[2018-04-11 21:58:43] Started run 825 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:43] Error in run 818: Run already exists in server. Run id(s): {9050945}
[2018-04-11 21:58:43] Started run 826 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:44] Error in run 819: Run already exists in server. Run id(s): {9050822}
[2018-04-11 21:58:44] Started run 827 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:45] Error in run 820: Run already exists in server. Run id(s): {9050826}
[2018-04-11 21:58:45] Started run 828 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:45] Error in run 821: Run already exists in server. Run id(s): {9050898}
[2018-04-11 21:58:45] Started run 829 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:46] Error in run 822: Run already exists in server. Run id(s): {9050875}
[2018-04-11 21:58:46] Started run 830 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:46] Error in run 823: Run already exists in server. Run id(s): {9050857}
[2018-04-11 21:58:46] Started run 831 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:47] Error in run 824: Run already exists in server. Run id(s): {9050818}
[2018-04-11 21:58:47] Started run 832 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:47] Error in run 825: Run already exists in server. Run id(s): {9050823}
[2018-04-11 21:58:47] Started run 833 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:48] Error in run 826: Run already exists in server. Run id(s): {9050841}
[2018-04-11 21:58:48] Started run 834 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:49] Error in run 827: Run already exists in server. Run id(s): {9050976}
[2018-04-11 21:58:49] Started run 835 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:49] Error in run 828: Run already exists in server. Run id(s): {9050833}
[2018-04-11 21:58:49] Started run 836 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:50] Error in run 830: Run already exists in server. Run id(s): {9050829}
[2018-04-11 21:58:50] Error in run 829: Run already exists in server. Run id(s): {9050879}
[2018-04-11 21:58:50] Started run 837 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:50] Started run 838 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:51] Error in run 831: Run already exists in server. Run id(s): {9050831}
[2018-04-11 21:58:51] Started run 839 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:52] Error in run 832: Run already exists in server. Run id(s): {9050872}
[2018-04-11 21:58:52] Started run 840 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:52] Error in run 833: Run already exists in server. Run id(s): {9050866}
[2018-04-11 21:58:52] Started run 841 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:52] Error in run 834: Run already exists in server. Run id(s): {9050858}
[2018-04-11 21:58:52] Started run 842 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:53] Error in run 835: Run already exists in server. Run id(s): {9050861}
[2018-04-11 21:58:53] Started run 843 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:54] Error in run 836: Run already exists in server. Run id(s): {9050845}
[2018-04-11 21:58:54] Started run 844 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:55] Error in run 838: Run already exists in server. Run id(s): {9050984}
[2018-04-11 21:58:55] Error in run 837: Run already exists in server. Run id(s): {9050904}
[2018-04-11 21:58:55] Started run 845 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:55] Started run 846 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:56] Error in run 839: Run already exists in server. Run id(s): {9050880}
[2018-04-11 21:58:56] Started run 847 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:56] Error in run 840: Run already exists in server. Run id(s): {9050835}
[2018-04-11 21:58:56] Error in run 841: Run already exists in server. Run id(s): {9050897}
[2018-04-11 21:58:56] Started run 848 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:56] Started run 849 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:57] Error in run 842: Run already exists in server. Run id(s): {9050854}
[2018-04-11 21:58:57] Started run 850 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:58] Error in run 843: Run already exists in server. Run id(s): {9051003}
[2018-04-11 21:58:58] Started run 851 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:58] Error in run 844: Run already exists in server. Run id(s): {9050840}
[2018-04-11 21:58:58] Started run 852 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:59] Error in run 846: Run already exists in server. Run id(s): {9050873}
[2018-04-11 21:58:59] Error in run 845: Run already exists in server. Run id(s): {9051073}
[2018-04-11 21:58:59] Started run 853 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:58:59] Started run 854 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:00] Error in run 847: Run already exists in server. Run id(s): {9050907}
[2018-04-11 21:59:00] Started run 855 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:01] Error in run 848: Run already exists in server. Run id(s): {9050965}
[2018-04-11 21:59:01] Error in run 849: Run already exists in server. Run id(s): {9051029}
[2018-04-11 21:59:01] Started run 856 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:01] Started run 857 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:02] Error in run 850: Run already exists in server. Run id(s): {9050859}
[2018-04-11 21:59:02] Started run 858 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:02] Error in run 851: Run already exists in server. Run id(s): {9050865}
[2018-04-11 21:59:02] Started run 859 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:03] Error in run 852: Run already exists in server. Run id(s): {9050855}
[2018-04-11 21:59:03] Started run 860 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:04] Error in run 853: Run already exists in server. Run id(s): {9050895}
[2018-04-11 21:59:04] Error in run 854: Run already exists in server. Run id(s): {9050913}
[2018-04-11 21:59:04] Started run 861 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:04] Started run 862 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:05] Error in run 855: Run already exists in server. Run id(s): {9050888}
[2018-04-11 21:59:05] Started run 863 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:06] Error in run 857: Run already exists in server. Run id(s): {9050891}
[2018-04-11 21:59:06] Error in run 856: Run already exists in server. Run id(s): {9050887}
[2018-04-11 21:59:06] Started run 864 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:06] Started run 865 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:06] Error in run 858: Run already exists in server. Run id(s): {9050853}
[2018-04-11 21:59:06] Started run 866 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:07] Error in run 859: Run already exists in server. Run id(s): {9050882}
[2018-04-11 21:59:07] Started run 867 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:07] Error in run 860: Run already exists in server. Run id(s): {9051081}
[2018-04-11 21:59:07] Started run 868 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:09] Error in run 862: Run already exists in server. Run id(s): {9050890}
[2018-04-11 21:59:09] Started run 869 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:09] Error in run 861: Run already exists in server. Run id(s): {9050917}
[2018-04-11 21:59:09] Started run 870 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:10] Error in run 863: Run already exists in server. Run id(s): {9050902}
[2018-04-11 21:59:10] Started run 871 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:10] Error in run 865: Run already exists in server. Run id(s): {9050901}
[2018-04-11 21:59:10] Started run 872 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:10] Error in run 864: Run already exists in server. Run id(s): {9051069}
[2018-04-11 21:59:10] Started run 873 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:11] Error in run 866: Run already exists in server. Run id(s): {9050876}
[2018-04-11 21:59:11] Error in run 867: Run already exists in server. Run id(s): {9050870}
[2018-04-11 21:59:11] Started run 874 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:11] Started run 875 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:12] Error in run 868: Run already exists in server. Run id(s): {9050908}
[2018-04-11 21:59:12] Started run 876 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:13] Error in run 869: Run already exists in server. Run id(s): {9050916}
[2018-04-11 21:59:13] Started run 877 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:14] Error in run 870: Run already exists in server. Run id(s): {9050930}
[2018-04-11 21:59:14] Started run 878 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:14] Error in run 871: Run already exists in server. Run id(s): {9051065}
[2018-04-11 21:59:14] Started run 879 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:15] Error in run 872: Run already exists in server. Run id(s): {9050936}
[2018-04-11 21:59:15] Error in run 873: Run already exists in server. Run id(s): {9050893}
[2018-04-11 21:59:15] Started run 880 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:15] Started run 881 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:16] Error in run 875: Run already exists in server. Run id(s): {9050948}
[2018-04-11 21:59:16] Error in run 874: Run already exists in server. Run id(s): {9050920}
[2018-04-11 21:59:16] Started run 882 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:16] Started run 883 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:16] Error in run 876: Run already exists in server. Run id(s): {9050892}
[2018-04-11 21:59:16] Started run 884 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:18] Error in run 877: Run already exists in server. Run id(s): {9050998}
[2018-04-11 21:59:18] Started run 885 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:18] Error in run 878: Run already exists in server. Run id(s): {9050883}
[2018-04-11 21:59:18] Started run 886 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:19] Error in run 879: Run already exists in server. Run id(s): {9050911}
[2018-04-11 21:59:19] Started run 887 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:19] Error in run 880: Run already exists in server. Run id(s): {9050896}
[2018-04-11 21:59:19] Started run 888 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:19] Error in run 881: Run already exists in server. Run id(s): {9050944}
[2018-04-11 21:59:19] Started run 889 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:21] Error in run 883: Run already exists in server. Run id(s): {9050923}
[2018-04-11 21:59:21] Error in run 882: Run already exists in server. Run id(s): {9050914}
[2018-04-11 21:59:21] Started run 890 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:21] Started run 891 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:21] Error in run 884: Run already exists in server. Run id(s): {9050881}
[2018-04-11 21:59:21] Started run 892 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:22] Error in run 885: Run already exists in server. Run id(s): {9050885}
[2018-04-11 21:59:22] Started run 893 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:23] Error in run 886: Run already exists in server. Run id(s): {9051021}
[2018-04-11 21:59:23] Started run 894 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:23] Error in run 887: Run already exists in server. Run id(s): {9050906}
[2018-04-11 21:59:23] Started run 895 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:24] Error in run 888: Run already exists in server. Run id(s): {9050910}
[2018-04-11 21:59:24] Started run 896 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:24] Error in run 889: Run already exists in server. Run id(s): {9050884}
[2018-04-11 21:59:24] Started run 897 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:25] Error in run 890: Run already exists in server. Run id(s): {9050886}
[2018-04-11 21:59:25] Error in run 891: Run already exists in server. Run id(s): {9051043}
[2018-04-11 21:59:25] Started run 898 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:25] Started run 899 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:25] Error in run 892: Run already exists in server. Run id(s): {9051020}
[2018-04-11 21:59:25] Started run 900 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:27] Error in run 893: Run already exists in server. Run id(s): {9051087}
[2018-04-11 21:59:27] Started run 901 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:27] Error in run 894: Run already exists in server. Run id(s): {9051000}
[2018-04-11 21:59:27] Started run 902 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:28] Error in run 895: Run already exists in server. Run id(s): {9050894}
[2018-04-11 21:59:28] Started run 903 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:28] Error in run 896: Run already exists in server. Run id(s): {9050899}
[2018-04-11 21:59:28] Started run 904 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:28] Error in run 897: Run already exists in server. Run id(s): {9050925}
[2018-04-11 21:59:28] Started run 905 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:30] Error in run 898: Run already exists in server. Run id(s): {9050912}
[2018-04-11 21:59:30] Started run 906 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:30] Error in run 899: Run already exists in server. Run id(s): {9050922}
[2018-04-11 21:59:30] Started run 907 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:30] Error in run 900: Run already exists in server. Run id(s): {9050943}
[2018-04-11 21:59:30] Started run 908 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:31] Error in run 901: Run already exists in server. Run id(s): {9050959}
[2018-04-11 21:59:31] Started run 909 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:32] Error in run 902: Run already exists in server. Run id(s): {9050956}
[2018-04-11 21:59:32] Started run 910 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:32] Error in run 903: Run already exists in server. Run id(s): {9051046}
[2018-04-11 21:59:32] Started run 911 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:33] Error in run 905: Run already exists in server. Run id(s): {9050909}
[2018-04-11 21:59:33] Started run 912 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:33] Error in run 904: Run already exists in server. Run id(s): {9050940}
[2018-04-11 21:59:33] Started run 913 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:34] Error in run 906: Run already exists in server. Run id(s): {9051067}
[2018-04-11 21:59:34] Started run 914 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:34] Error in run 907: Run already exists in server. Run id(s): {9050905}
[2018-04-11 21:59:34] Started run 915 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:34] Error in run 908: Run already exists in server. Run id(s): {9051026}
[2018-04-11 21:59:34] Started run 916 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:36] Error in run 909: Run already exists in server. Run id(s): {9050927}
[2018-04-11 21:59:36] Started run 917 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:36] Error in run 910: Run already exists in server. Run id(s): {9050980}
[2018-04-11 21:59:36] Started run 918 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:37] Error in run 911: Run already exists in server. Run id(s): {9050968}
[2018-04-11 21:59:37] Started run 919 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:37] Error in run 912: Run already exists in server. Run id(s): {9050918}
[2018-04-11 21:59:37] Started run 920 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:37] Error in run 913: Run already exists in server. Run id(s): {9051010}
[2018-04-11 21:59:37] Started run 921 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:39] Error in run 914: Run already exists in server. Run id(s): {9051035}
[2018-04-11 21:59:39] Error in run 915: Run already exists in server. Run id(s): {9050979}
[2018-04-11 21:59:39] Started run 922 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:39] Started run 923 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:39] Error in run 916: Run already exists in server. Run id(s): {9050915}
[2018-04-11 21:59:39] Started run 924 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:40] Error in run 917: Run already exists in server. Run id(s): {9050946}
[2018-04-11 21:59:40] Started run 925 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:41] Error in run 918: Run already exists in server. Run id(s): {9051049}
[2018-04-11 21:59:41] Started run 926 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:41] Error in run 919: Run already exists in server. Run id(s): {9050978}
[2018-04-11 21:59:41] Started run 927 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:42] Error in run 920: Run already exists in server. Run id(s): {9051098}
[2018-04-11 21:59:42] Started run 928 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:42] Error in run 921: Run already exists in server. Run id(s): {9050985}
[2018-04-11 21:59:42] Started run 929 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:43] Error in run 922: Run already exists in server. Run id(s): {9050977, 9050974}
[2018-04-11 21:59:43] Error in run 923: Run already exists in server. Run id(s): {9050963}
[2018-04-11 21:59:43] Started run 930 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:43] Started run 931 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:43] Error in run 924: Run already exists in server. Run id(s): {9050953}
[2018-04-11 21:59:43] Started run 932 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:45] Error in run 925: Run already exists in server. Run id(s): {9051042}
[2018-04-11 21:59:45] Started run 933 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:46] Error in run 926: Run already exists in server. Run id(s): {9050929}
[2018-04-11 21:59:46] Started run 934 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:46] Error in run 927: Run already exists in server. Run id(s): {9050932}
[2018-04-11 21:59:46] Started run 935 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:46] Error in run 928: Run already exists in server. Run id(s): {9050981}
[2018-04-11 21:59:46] Started run 936 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:46] Error in run 929: Run already exists in server. Run id(s): {9051059}
[2018-04-11 21:59:46] Started run 937 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:48] Error in run 930: Run already exists in server. Run id(s): {9050949}
[2018-04-11 21:59:48] Started run 938 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:48] Error in run 932: Run already exists in server. Run id(s): {9050973}
[2018-04-11 21:59:48] Error in run 931: Run already exists in server. Run id(s): {9051104}
[2018-04-11 21:59:48] Started run 939 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:48] Started run 940 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:49] Error in run 933: Run already exists in server. Run id(s): {9051048}
[2018-04-11 21:59:49] Started run 941 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:50] Error in run 934: Run already exists in server. Run id(s): {9050967}
[2018-04-11 21:59:50] Started run 942 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:50] Error in run 935: Run already exists in server. Run id(s): {9050972}
[2018-04-11 21:59:50] Started run 943 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:51] Error in run 936: Run already exists in server. Run id(s): {9050937}
[2018-04-11 21:59:51] Started run 944 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:51] Error in run 937: Run already exists in server. Run id(s): {9050958}
[2018-04-11 21:59:51] Started run 945 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:52] Error in run 938: Run already exists in server. Run id(s): {9050986}
[2018-04-11 21:59:52] Started run 946 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:52] Error in run 939: Run already exists in server. Run id(s): {9050994}
[2018-04-11 21:59:52] Started run 947 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:52] Error in run 940: Run already exists in server. Run id(s): {9050989}
[2018-04-11 21:59:52] Started run 948 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:54] Error in run 941: Run already exists in server. Run id(s): {9050991}
[2018-04-11 21:59:54] Started run 949 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:55] Error in run 942: Run already exists in server. Run id(s): {9050947}
[2018-04-11 21:59:55] Started run 950 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:55] Error in run 943: Run already exists in server. Run id(s): {9051101}
[2018-04-11 21:59:55] Started run 951 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:55] Error in run 944: Run already exists in server. Run id(s): {9050988}
[2018-04-11 21:59:55] Started run 952 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:56] Error in run 945: Run already exists in server. Run id(s): {9051039}
[2018-04-11 21:59:56] Started run 953 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:57] Error in run 946: Run already exists in server. Run id(s): {9051115}
[2018-04-11 21:59:57] Started run 954 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:57] Error in run 947: Run already exists in server. Run id(s): {9050975}
[2018-04-11 21:59:57] Started run 955 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:57] Error in run 948: Run already exists in server. Run id(s): {9051011}
[2018-04-11 21:59:57] Started run 956 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:58] Error in run 949: Run already exists in server. Run id(s): {9051109}
[2018-04-11 21:59:58] Started run 957 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 21:59:59] Error in run 950: Run already exists in server. Run id(s): {9050987}
[2018-04-11 21:59:59] Started run 958 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:00] Error in run 951: Run already exists in server. Run id(s): {9051085}
[2018-04-11 22:00:00] Started run 959 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:00] Error in run 952: Run already exists in server. Run id(s): {9051033}
[2018-04-11 22:00:00] Started run 960 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:00] Error in run 953: Run already exists in server. Run id(s): {9051022}
[2018-04-11 22:00:00] Started run 961 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:01] Error in run 954: Run already exists in server. Run id(s): {9050964}
[2018-04-11 22:00:01] Started run 962 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:01] Error in run 955: Run already exists in server. Run id(s): {9051013}
[2018-04-11 22:00:01] Started run 963 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:01] Error in run 956: Run already exists in server. Run id(s): {9050957}
[2018-04-11 22:00:01] Started run 964 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:03] Error in run 957: Run already exists in server. Run id(s): {9051102}
[2018-04-11 22:00:03] Started run 965 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:04] Error in run 958: Run already exists in server. Run id(s): {9051008}
[2018-04-11 22:00:04] Started run 966 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:04] Error in run 959: Run already exists in server. Run id(s): {9051012}
[2018-04-11 22:00:04] Started run 967 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:04] Error in run 960: Run already exists in server. Run id(s): {9051070}
[2018-04-11 22:00:04] Started run 968 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:04] Error in run 961: Run already exists in server. Run id(s): {9051004}
[2018-04-11 22:00:04] Started run 969 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:06] Error in run 963: Run already exists in server. Run id(s): {9051052}
[2018-04-11 22:00:06] Error in run 962: Run already exists in server. Run id(s): {9051037}
[2018-04-11 22:00:06] Started run 970 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:06] Error in run 964: Run already exists in server. Run id(s): {9051068}
[2018-04-11 22:00:06] Started run 972 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:06] Started run 971 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:07] Error in run 965: Run already exists in server. Run id(s): {9051105}
[2018-04-11 22:00:07] Started run 973 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:08] Error in run 966: Run already exists in server. Run id(s): {9051076}
[2018-04-11 22:00:08] Started run 974 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:09] Error in run 967: Run already exists in server. Run id(s): {9051040}
[2018-04-11 22:00:09] Started run 975 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:09] Error in run 968: Run already exists in server. Run id(s): {9051054}
[2018-04-11 22:00:09] Error in run 969: Run already exists in server. Run id(s): {9051031}
[2018-04-11 22:00:09] Started run 976 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:09] Started run 977 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:11] Error in run 971: Run already exists in server. Run id(s): {9051034}
[2018-04-11 22:00:11] Error in run 972: Run already exists in server. Run id(s): {9051017}
[2018-04-11 22:00:11] Error in run 970: Run already exists in server. Run id(s): {9051055}
[2018-04-11 22:00:11] Started run 978 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:11] Started run 979 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:11] Started run 980 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:12] Error in run 973: Run already exists in server. Run id(s): {9051024}
[2018-04-11 22:00:12] Started run 981 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:13] Error in run 974: Run already exists in server. Run id(s): {9051099}
[2018-04-11 22:00:13] Started run 982 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:13] Error in run 975: Run already exists in server. Run id(s): {9051045}
[2018-04-11 22:00:13] Started run 983 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:14] Error in run 977: Run already exists in server. Run id(s): {9051092}
[2018-04-11 22:00:14] Error in run 976: Run already exists in server. Run id(s): {9051047}
[2018-04-11 22:00:14] Started run 984 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:14] Started run 985 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:15] Error in run 979: Run already exists in server. Run id(s): {9051096}
[2018-04-11 22:00:15] Error in run 978: Run already exists in server. Run id(s): {9051089}
[2018-04-11 22:00:15] Started run 986 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:15] Error in run 980: Run already exists in server. Run id(s): {9051072}
[2018-04-11 22:00:15] Started run 988 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:15] Started run 987 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:17] Error in run 981: Run already exists in server. Run id(s): {9051086}
[2018-04-11 22:00:17] Started run 989 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:17] Error in run 982: Run already exists in server. Run id(s): {9051060}
[2018-04-11 22:00:17] Started run 990 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:18] Error in run 983: Run already exists in server. Run id(s): {9050995}
[2018-04-11 22:00:18] Started run 991 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:18] Error in run 984: Run already exists in server. Run id(s): {9051006}
[2018-04-11 22:00:18] Started run 992 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:18] Error in run 985: Run already exists in server. Run id(s): {9050999}
[2018-04-11 22:00:18] Started run 993 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:20] Error in run 986: Run already exists in server. Run id(s): {9051063}
[2018-04-11 22:00:20] Error in run 988: Run already exists in server. Run id(s): {9051027}
[2018-04-11 22:00:20] Started run 994 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:20] Started run 995 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:20] Error in run 987: Run already exists in server. Run id(s): {9051050, 9051051}
[2018-04-11 22:00:20] Started run 996 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:21] Error in run 989: Run already exists in server. Run id(s): {9051084}
[2018-04-11 22:00:21] Started run 997 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:22] Error in run 990: Run already exists in server. Run id(s): {9051016}
[2018-04-11 22:00:22] Started run 998 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:22] Error in run 991: Run already exists in server. Run id(s): {9051058}
[2018-04-11 22:00:22] Started run 999 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:23] Error in run 992: Run already exists in server. Run id(s): {9051064}
[2018-04-11 22:00:23] Started run 1000 on task 9985, dataset 'first-order-theorem-proving'.
[2018-04-11 22:00:23] Error in run 993: Run already exists in server. Run id(s): {9051015}
[2018-04-11 22:00:24] Error in run 994: Run already exists in server. Run id(s): {9051032}
[2018-04-11 22:00:24] Error in run 995: Run already exists in server. Run id(s): {9051078}
[2018-04-11 22:00:25] Error in run 996: Run already exists in server. Run id(s): {9051117}
[2018-04-11 22:00:26] Error in run 997: Run already exists in server. Run id(s): {9051075}
[2018-04-11 22:00:26] Error in run 998: Run already exists in server. Run id(s): {9051057}
[2018-04-11 22:00:27] Error in run 999: Run already exists in server. Run id(s): {9051019}
[2018-04-11 22:00:27] Error in run 1000: Run already exists in server. Run id(s): {9051095}
