declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00011/certs"
declare -x AZ_BATCH_JOB_ID="random_forest"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_8-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00011"
declare -x AZ_BATCH_TASK_ID="task-00011"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00011/wd"
declare -x HOME="/mnt/batch/tasks/workitems/random_forest/job-1/task-00011/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/random_forest/job-1/task-00011/wd"
declare -x PWD="/mnt/batch/tasks/workitems/random_forest/job-1/task-00011/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 20:12:40] Results will not be logged locally.
[2018-04-11 20:12:40] Retrieving tasks...
[2018-04-11 20:12:40] Tasks will be retrieved based on provided task ids.
[2018-04-11 20:12:40] The following tasks were retrieved: [3560].
[2018-04-11 20:12:45] Downloaded task 3560.
[2018-04-11 20:12:45] Prepared pipelines.
[2018-04-11 20:12:45] Started run 1 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:45] Started run 8 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:45] Started run 6 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:45] Started run 2 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:45] Started run 3 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:45] Started run 4 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:45] Started run 5 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:45] Started run 7 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Error in run 8: Run already exists in server. Run id(s): {9024510}
[2018-04-11 20:12:50] Error in run 2: Run already exists in server. Run id(s): {8962511}
[2018-04-11 20:12:50] Started run 9 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Started run 10 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Error in run 1: Run already exists in server. Run id(s): {8962515}
[2018-04-11 20:12:50] Error in run 6: Run already exists in server. Run id(s): {8962521}
[2018-04-11 20:12:50] Started run 11 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Started run 12 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Error in run 3: Run already exists in server. Run id(s): {8962514}
[2018-04-11 20:12:50] Started run 13 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Error in run 4: Run already exists in server. Run id(s): {9024505}
[2018-04-11 20:12:50] Started run 14 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Error in run 5: Run already exists in server. Run id(s): {8962526}
[2018-04-11 20:12:50] Started run 15 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:50] Error in run 7: Run already exists in server. Run id(s): {8962519}
[2018-04-11 20:12:50] Started run 16 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Error in run 9: Run already exists in server. Run id(s): {8962528}
[2018-04-11 20:12:55] Started run 17 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Error in run 10: Run already exists in server. Run id(s): {8962509}
[2018-04-11 20:12:55] Started run 18 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Error in run 11: Run already exists in server. Run id(s): {8962527}
[2018-04-11 20:12:55] Error in run 12: Run already exists in server. Run id(s): {9024519}
[2018-04-11 20:12:55] Error in run 13: Run already exists in server. Run id(s): {9024571}
[2018-04-11 20:12:55] Started run 19 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Error in run 14: Run already exists in server. Run id(s): {8962504}
[2018-04-11 20:12:55] Started run 22 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Started run 20 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Error in run 15: Run already exists in server. Run id(s): {9024529}
[2018-04-11 20:12:55] Started run 21 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Started run 23 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:55] Error in run 16: Run already exists in server. Run id(s): {9024530}
[2018-04-11 20:12:55] Started run 24 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:59] Error in run 17: Run already exists in server. Run id(s): {9024524}
[2018-04-11 20:12:59] Started run 25 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:12:59] Error in run 18: Run already exists in server. Run id(s): {9024525}
[2018-04-11 20:12:59] Started run 26 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:00] Error in run 22: Run already exists in server. Run id(s): {9024572}
[2018-04-11 20:13:00] Started run 27 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:00] Error in run 23: Run already exists in server. Run id(s): {9024570}
[2018-04-11 20:13:00] Error in run 19: Run already exists in server. Run id(s): {9024556}
[2018-04-11 20:13:00] Started run 28 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:00] Error in run 21: Run already exists in server. Run id(s): {9024563}
[2018-04-11 20:13:00] Error in run 20: Run already exists in server. Run id(s): {9024557}
[2018-04-11 20:13:00] Error in run 24: Run already exists in server. Run id(s): {8962517}
[2018-04-11 20:13:00] Started run 29 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:00] Started run 32 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:00] Started run 31 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:00] Started run 30 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Error in run 25: Run already exists in server. Run id(s): {8962507}
[2018-04-11 20:13:04] Started run 33 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Error in run 26: Run already exists in server. Run id(s): {9024578}
[2018-04-11 20:13:04] Started run 34 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Error in run 30: Run already exists in server. Run id(s): {9024699}
[2018-04-11 20:13:04] Error in run 31: Run already exists in server. Run id(s): {8962522}
[2018-04-11 20:13:04] Error in run 29: Run already exists in server. Run id(s): {9024713}
[2018-04-11 20:13:04] Error in run 27: Run already exists in server. Run id(s): {9024590}
[2018-04-11 20:13:04] Error in run 28: Run already exists in server. Run id(s): {9024608}
[2018-04-11 20:13:04] Started run 35 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Error in run 32: Run already exists in server. Run id(s): {9024630}
[2018-04-11 20:13:04] Started run 36 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Started run 40 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Started run 37 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Started run 38 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:04] Started run 39 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:08] Error in run 33: Run already exists in server. Run id(s): {9024632}
[2018-04-11 20:13:08] Started run 41 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:08] Error in run 34: Run already exists in server. Run id(s): {9024645}
[2018-04-11 20:13:08] Started run 42 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:09] Error in run 35: Run already exists in server. Run id(s): {8962502}
[2018-04-11 20:13:09] Started run 43 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:09] Error in run 36: Run already exists in server. Run id(s): {9024647}
[2018-04-11 20:13:09] Error in run 37: Run already exists in server. Run id(s): {9024652}
[2018-04-11 20:13:09] Started run 44 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:09] Error in run 40: Run already exists in server. Run id(s): {8962510}
[2018-04-11 20:13:09] Error in run 39: Run already exists in server. Run id(s): {9024679}
[2018-04-11 20:13:09] Started run 46 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:09] Started run 47 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:09] Error in run 38: Run already exists in server. Run id(s): {9024667}
[2018-04-11 20:13:09] Started run 48 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:09] Started run 45 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:13] Error in run 42: Run already exists in server. Run id(s): {8962499}
[2018-04-11 20:13:13] Error in run 41: Run already exists in server. Run id(s): {8962508}
[2018-04-11 20:13:13] Started run 49 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:13] Started run 50 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:13] Error in run 43: Run already exists in server. Run id(s): {9024696}
[2018-04-11 20:13:13] Started run 51 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:14] Error in run 48: Run already exists in server. Run id(s): {8962501}
[2018-04-11 20:13:14] Error in run 47: Run already exists in server. Run id(s): {9024714}
[2018-04-11 20:13:14] Error in run 46: Run already exists in server. Run id(s): {9024706}
[2018-04-11 20:13:14] Started run 52 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:14] Started run 53 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:14] Started run 54 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:14] Error in run 45: Run already exists in server. Run id(s): {8962513}
[2018-04-11 20:13:14] Started run 55 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:14] Error in run 44: Run already exists in server. Run id(s): {9024702}
[2018-04-11 20:13:14] Started run 56 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Error in run 49: Run already exists in server. Run id(s): {9024759}
[2018-04-11 20:13:18] Error in run 50: Run already exists in server. Run id(s): {8962503}
[2018-04-11 20:13:18] Started run 57 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Started run 58 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Error in run 51: Run already exists in server. Run id(s): {8962518}
[2018-04-11 20:13:18] Started run 59 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Error in run 52: Run already exists in server. Run id(s): {9024888}
[2018-04-11 20:13:18] Started run 60 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Error in run 53: Run already exists in server. Run id(s): {8962500}
[2018-04-11 20:13:18] Started run 61 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Error in run 54: Run already exists in server. Run id(s): {8962498}
[2018-04-11 20:13:18] Started run 62 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Error in run 56: Run already exists in server. Run id(s): {9024770}
[2018-04-11 20:13:18] Started run 63 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:18] Error in run 55: Run already exists in server. Run id(s): {8962520}
[2018-04-11 20:13:18] Started run 64 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:22] Error in run 58: Run already exists in server. Run id(s): {8962512}
[2018-04-11 20:13:22] Error in run 57: Run already exists in server. Run id(s): {8962495}
[2018-04-11 20:13:22] Started run 65 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:22] Error in run 59: Run already exists in server. Run id(s): {9024773}
[2018-04-11 20:13:22] Started run 67 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:22] Started run 66 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:23] Error in run 60: Run already exists in server. Run id(s): {9024775}
[2018-04-11 20:13:23] Started run 68 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:23] Error in run 61: Run already exists in server. Run id(s): {8962506}
[2018-04-11 20:13:23] Started run 69 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:23] Error in run 62: Run already exists in server. Run id(s): {8962505}
[2018-04-11 20:13:23] Started run 70 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:23] Error in run 63: Run already exists in server. Run id(s): {9024780}
[2018-04-11 20:13:23] Started run 71 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:23] Error in run 64: Run already exists in server. Run id(s): {8962496}
[2018-04-11 20:13:23] Started run 72 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:27] Error in run 67: Run already exists in server. Run id(s): {9024793}
[2018-04-11 20:13:27] Error in run 66: Run already exists in server. Run id(s): {8962524}
[2018-04-11 20:13:27] Error in run 65: Run already exists in server. Run id(s): {8962523}
[2018-04-11 20:13:27] Started run 73 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:27] Started run 74 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:27] Error in run 68: Run already exists in server. Run id(s): {8962497}
[2018-04-11 20:13:27] Started run 75 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:27] Started run 76 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:27] Error in run 69: Run already exists in server. Run id(s): {8962516}
[2018-04-11 20:13:27] Started run 77 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:27] Error in run 70: Run already exists in server. Run id(s): {8962493}
[2018-04-11 20:13:27] Started run 78 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:27] Error in run 71: Run already exists in server. Run id(s): {8962525}
[2018-04-11 20:13:27] Started run 79 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:28] Error in run 72: Run already exists in server. Run id(s): {8962494}
[2018-04-11 20:13:28] Started run 80 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Error in run 74: Run already exists in server. Run id(s): {9024835}
[2018-04-11 20:13:32] Started run 81 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Error in run 76: Run already exists in server. Run id(s): {9024873}
[2018-04-11 20:13:32] Started run 82 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Error in run 73: Run already exists in server. Run id(s): {9024828}
[2018-04-11 20:13:32] Error in run 78: Run already exists in server. Run id(s): {9024846}
[2018-04-11 20:13:32] Started run 83 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Error in run 75: Run already exists in server. Run id(s): {9024843}
[2018-04-11 20:13:32] Started run 84 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Error in run 77: Run already exists in server. Run id(s): {9024911}
[2018-04-11 20:13:32] Error in run 79: Run already exists in server. Run id(s): {9025052}
[2018-04-11 20:13:32] Started run 86 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Started run 87 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Started run 85 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:32] Error in run 80: Run already exists in server. Run id(s): {9024935}
[2018-04-11 20:13:32] Started run 88 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:36] Error in run 81: Run already exists in server. Run id(s): {9024889}
[2018-04-11 20:13:36] Started run 89 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:36] Error in run 82: Run already exists in server. Run id(s): {9024891}
[2018-04-11 20:13:36] Started run 90 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:36] Error in run 86: Run already exists in server. Run id(s): {9024943}
[2018-04-11 20:13:36] Error in run 84: Run already exists in server. Run id(s): {9024920}
[2018-04-11 20:13:36] Started run 91 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:36] Error in run 83: Run already exists in server. Run id(s): {9024902}
[2018-04-11 20:13:36] Error in run 87: Run already exists in server. Run id(s): {9024945}
[2018-04-11 20:13:36] Error in run 85: Run already exists in server. Run id(s): {9024949}
[2018-04-11 20:13:36] Started run 92 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:36] Started run 93 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:36] Started run 94 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:36] Started run 95 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:37] Error in run 88: Run already exists in server. Run id(s): {9024959}
[2018-04-11 20:13:37] Started run 96 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Error in run 89: Run already exists in server. Run id(s): {9024965}
[2018-04-11 20:13:41] Started run 97 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Error in run 90: Run already exists in server. Run id(s): {9024966}
[2018-04-11 20:13:41] Started run 98 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Error in run 92: Run already exists in server. Run id(s): {9024991}
[2018-04-11 20:13:41] Error in run 95: Run already exists in server. Run id(s): {9025003}
[2018-04-11 20:13:41] Started run 99 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Error in run 94: Run already exists in server. Run id(s): {9025001}
[2018-04-11 20:13:41] Error in run 91: Run already exists in server. Run id(s): {9025040}
[2018-04-11 20:13:41] Error in run 93: Run already exists in server. Run id(s): {9024995}
[2018-04-11 20:13:41] Started run 100 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Started run 101 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Started run 102 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Started run 103 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:41] Error in run 96: Run already exists in server. Run id(s): {9025008}
[2018-04-11 20:13:41] Started run 104 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:45] Error in run 97: Run already exists in server. Run id(s): {9025004}
[2018-04-11 20:13:45] Started run 105 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:45] Error in run 98: Run already exists in server. Run id(s): {9025036}
[2018-04-11 20:13:45] Started run 106 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:46] Error in run 103: Run already exists in server. Run id(s): {9025067}
[2018-04-11 20:13:46] Started run 107 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:46] Error in run 102: Run already exists in server. Run id(s): {9025238}
[2018-04-11 20:13:46] Error in run 101: Run already exists in server. Run id(s): {9025087}
[2018-04-11 20:13:46] Error in run 99: Run already exists in server. Run id(s): {9025083}
[2018-04-11 20:13:46] Started run 108 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:46] Error in run 100: Run already exists in server. Run id(s): {9025107}
[2018-04-11 20:13:46] Started run 110 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:46] Started run 111 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:46] Started run 109 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:46] Error in run 104: Run already exists in server. Run id(s): {9025085}
[2018-04-11 20:13:46] Started run 112 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Error in run 105: Run already exists in server. Run id(s): {9025104}
[2018-04-11 20:13:50] Started run 113 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Error in run 106: Run already exists in server. Run id(s): {9025113}
[2018-04-11 20:13:50] Started run 114 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Error in run 107: Run already exists in server. Run id(s): {9025138}
[2018-04-11 20:13:50] Started run 115 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Error in run 110: Run already exists in server. Run id(s): {9025140}
[2018-04-11 20:13:50] Started run 116 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Error in run 108: Run already exists in server. Run id(s): {9025179}
[2018-04-11 20:13:50] Error in run 109: Run already exists in server. Run id(s): {9025228}
[2018-04-11 20:13:50] Error in run 111: Run already exists in server. Run id(s): {9025152}
[2018-04-11 20:13:50] Started run 117 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Started run 118 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Started run 119 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:50] Error in run 112: Run already exists in server. Run id(s): {9025156}
[2018-04-11 20:13:50] Started run 120 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:54] Error in run 114: Run already exists in server. Run id(s): {9025376}
[2018-04-11 20:13:54] Started run 121 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:54] Error in run 113: Run already exists in server. Run id(s): {9025157}
[2018-04-11 20:13:54] Started run 122 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:55] Error in run 115: Run already exists in server. Run id(s): {9025390}
[2018-04-11 20:13:55] Started run 123 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:55] Error in run 116: Run already exists in server. Run id(s): {9025212}
[2018-04-11 20:13:55] Started run 124 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:55] Error in run 117: Run already exists in server. Run id(s): {9025204}
[2018-04-11 20:13:55] Started run 125 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:55] Error in run 118: Run already exists in server. Run id(s): {9025213}
[2018-04-11 20:13:55] Started run 126 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:55] Error in run 119: Run already exists in server. Run id(s): {9025230}
[2018-04-11 20:13:55] Error in run 120: Run already exists in server. Run id(s): {9025521}
[2018-04-11 20:13:55] Started run 127 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:55] Started run 128 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:59] Error in run 121: Run already exists in server. Run id(s): {9025264}
[2018-04-11 20:13:59] Started run 129 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:59] Error in run 122: Run already exists in server. Run id(s): {9025272}
[2018-04-11 20:13:59] Started run 130 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:13:59] Error in run 123: Run already exists in server. Run id(s): {9025364}
[2018-04-11 20:13:59] Started run 131 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:00] Error in run 124: Run already exists in server. Run id(s): {9025277}
[2018-04-11 20:14:00] Started run 132 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:00] Error in run 125: Run already exists in server. Run id(s): {9025284}
[2018-04-11 20:14:00] Started run 133 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:00] Error in run 128: Run already exists in server. Run id(s): {9025338}
[2018-04-11 20:14:00] Started run 134 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:00] Error in run 127: Run already exists in server. Run id(s): {9025367}
[2018-04-11 20:14:00] Started run 135 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:00] Error in run 126: Run already exists in server. Run id(s): {9025323}
[2018-04-11 20:14:00] Started run 136 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:04] Error in run 130: Run already exists in server. Run id(s): {9025526}
[2018-04-11 20:14:04] Started run 137 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:04] Error in run 129: Run already exists in server. Run id(s): {9025337}
[2018-04-11 20:14:04] Started run 138 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:04] Error in run 131: Run already exists in server. Run id(s): {9025395}
[2018-04-11 20:14:04] Started run 139 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:04] Error in run 132: Run already exists in server. Run id(s): {9025391}
[2018-04-11 20:14:04] Started run 140 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:04] Error in run 133: Run already exists in server. Run id(s): {9025492}
[2018-04-11 20:14:04] Started run 141 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:04] Error in run 136: Run already exists in server. Run id(s): {9025457}
[2018-04-11 20:14:04] Started run 142 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:05] Error in run 134: Run already exists in server. Run id(s): {9025426}
[2018-04-11 20:14:05] Error in run 135: Run already exists in server. Run id(s): {9025436}
[2018-04-11 20:14:05] Started run 143 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:05] Started run 144 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:08] Error in run 137: Run already exists in server. Run id(s): {9025509}
[2018-04-11 20:14:08] Started run 145 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:08] Error in run 139: Run already exists in server. Run id(s): {9025471}
[2018-04-11 20:14:08] Started run 146 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:08] Error in run 138: Run already exists in server. Run id(s): {9025445}
[2018-04-11 20:14:08] Started run 147 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:09] Error in run 141: Run already exists in server. Run id(s): {9025484}
[2018-04-11 20:14:09] Error in run 140: Run already exists in server. Run id(s): {9025480}
[2018-04-11 20:14:09] Started run 148 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:09] Started run 149 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:09] Error in run 142: Run already exists in server. Run id(s): {9025497}
[2018-04-11 20:14:09] Started run 150 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:09] Error in run 143: Run already exists in server. Run id(s): {9025508}
[2018-04-11 20:14:09] Started run 151 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:09] Error in run 144: Run already exists in server. Run id(s): {9025532}
[2018-04-11 20:14:09] Started run 152 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:13] Error in run 147: Run already exists in server. Run id(s): {9025548}
[2018-04-11 20:14:13] Started run 153 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:13] Error in run 146: Run already exists in server. Run id(s): {9025543}
[2018-04-11 20:14:13] Started run 154 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:13] Error in run 145: Run already exists in server. Run id(s): {9025534}
[2018-04-11 20:14:13] Error in run 149: Run already exists in server. Run id(s): {9025632}
[2018-04-11 20:14:13] Error in run 148: Run already exists in server. Run id(s): {9025559}
[2018-04-11 20:14:13] Started run 155 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:13] Started run 156 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:13] Started run 157 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:14] Error in run 150: Run already exists in server. Run id(s): {9025569}
[2018-04-11 20:14:14] Started run 158 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:14] Error in run 151: Run already exists in server. Run id(s): {9025570}
[2018-04-11 20:14:14] Started run 159 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:14] Error in run 152: Run already exists in server. Run id(s): {9025584}
[2018-04-11 20:14:14] Started run 160 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Error in run 155: Run already exists in server. Run id(s): {9025598}
[2018-04-11 20:14:18] Error in run 153: Run already exists in server. Run id(s): {9025582}
[2018-04-11 20:14:18] Started run 161 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Error in run 156: Run already exists in server. Run id(s): {9025822}
[2018-04-11 20:14:18] Error in run 154: Run already exists in server. Run id(s): {9025591}
[2018-04-11 20:14:18] Started run 163 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Error in run 157: Run already exists in server. Run id(s): {9025619}
[2018-04-11 20:14:18] Started run 165 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Started run 162 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Started run 164 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Error in run 158: Run already exists in server. Run id(s): {9025627}
[2018-04-11 20:14:18] Started run 166 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Error in run 159: Run already exists in server. Run id(s): {9025622}
[2018-04-11 20:14:18] Started run 167 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:18] Error in run 160: Run already exists in server. Run id(s): {9025631}
[2018-04-11 20:14:18] Started run 168 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:22] Error in run 163: Run already exists in server. Run id(s): {9025702}
[2018-04-11 20:14:22] Error in run 164: Run already exists in server. Run id(s): {9025818}
[2018-04-11 20:14:22] Started run 169 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:22] Error in run 161: Run already exists in server. Run id(s): {9025639}
[2018-04-11 20:14:22] Error in run 165: Run already exists in server. Run id(s): {9025685}
[2018-04-11 20:14:22] Started run 171 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:22] Error in run 162: Run already exists in server. Run id(s): {9025651}
[2018-04-11 20:14:22] Started run 173 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:22] Started run 170 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:22] Started run 172 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:23] Error in run 166: Run already exists in server. Run id(s): {9025681}
[2018-04-11 20:14:23] Started run 174 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:23] Error in run 167: Run already exists in server. Run id(s): {9025684}
[2018-04-11 20:14:23] Started run 175 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:23] Error in run 168: Run already exists in server. Run id(s): {9025689}
[2018-04-11 20:14:23] Started run 176 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:27] Error in run 173: Run already exists in server. Run id(s): {9025738}
[2018-04-11 20:14:27] Started run 177 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:27] Error in run 172: Run already exists in server. Run id(s): {9025743}
[2018-04-11 20:14:27] Started run 178 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:27] Error in run 169: Run already exists in server. Run id(s): {9025696}
[2018-04-11 20:14:27] Started run 179 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:27] Error in run 170: Run already exists in server. Run id(s): {9025745}
[2018-04-11 20:14:27] Error in run 171: Run already exists in server. Run id(s): {9025731}
[2018-04-11 20:14:27] Started run 180 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:27] Started run 181 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:27] Error in run 174: Run already exists in server. Run id(s): {9025747}
[2018-04-11 20:14:27] Started run 182 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:27] Error in run 175: Run already exists in server. Run id(s): {9025762}
[2018-04-11 20:14:27] Started run 183 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:28] Error in run 176: Run already exists in server. Run id(s): {9025802}
[2018-04-11 20:14:28] Started run 184 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:32] Error in run 178: Run already exists in server. Run id(s): {9025803}
[2018-04-11 20:14:32] Error in run 177: Run already exists in server. Run id(s): {9025790}
[2018-04-11 20:14:32] Started run 185 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:32] Started run 186 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:32] Error in run 182: Run already exists in server. Run id(s): {9025837}
[2018-04-11 20:14:32] Started run 187 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:32] Error in run 180: Run already exists in server. Run id(s): {9025801}
[2018-04-11 20:14:32] Error in run 181: Run already exists in server. Run id(s): {9025808}
[2018-04-11 20:14:32] Error in run 183: Run already exists in server. Run id(s): {9025840}
[2018-04-11 20:14:32] Started run 188 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:32] Error in run 179: Run already exists in server. Run id(s): {9025800}
[2018-04-11 20:14:32] Started run 191 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:32] Started run 190 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:32] Started run 189 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:33] Error in run 184: Run already exists in server. Run id(s): {9025846}
[2018-04-11 20:14:33] Started run 192 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:36] Error in run 185: Run already exists in server. Run id(s): {9025839}
[2018-04-11 20:14:36] Started run 193 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:36] Error in run 186: Run already exists in server. Run id(s): {9025842}
[2018-04-11 20:14:36] Started run 194 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:36] Error in run 187: Run already exists in server. Run id(s): {9025850}
[2018-04-11 20:14:36] Started run 195 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:36] Error in run 191: Run already exists in server. Run id(s): {9025901}
[2018-04-11 20:14:36] Error in run 188: Run already exists in server. Run id(s): {9025865}
[2018-04-11 20:14:36] Error in run 190: Run already exists in server. Run id(s): {9025887}
[2018-04-11 20:14:36] Started run 196 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:36] Started run 197 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:36] Started run 198 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:37] Error in run 189: Run already exists in server. Run id(s): {9025866}
[2018-04-11 20:14:37] Started run 199 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:37] Error in run 192: Run already exists in server. Run id(s): {9025896}
[2018-04-11 20:14:37] Started run 200 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:41] Error in run 194: Run already exists in server. Run id(s): {9025906}
[2018-04-11 20:14:41] Started run 201 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:41] Error in run 193: Run already exists in server. Run id(s): {9025899}
[2018-04-11 20:14:41] Started run 202 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:41] Error in run 195: Run already exists in server. Run id(s): {9025902}
[2018-04-11 20:14:41] Started run 203 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:41] Error in run 196: Run already exists in server. Run id(s): {9025920}
[2018-04-11 20:14:41] Error in run 197: Run already exists in server. Run id(s): {9025922}
[2018-04-11 20:14:41] Started run 204 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:41] Error in run 198: Run already exists in server. Run id(s): {9026151}
[2018-04-11 20:14:41] Error in run 199: Run already exists in server. Run id(s): {9025955}
[2018-04-11 20:14:41] Started run 205 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:41] Started run 206 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:41] Started run 207 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:42] Error in run 200: Run already exists in server. Run id(s): {9025951}
[2018-04-11 20:14:42] Started run 208 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:45] Error in run 201: Run already exists in server. Run id(s): {9025950}
[2018-04-11 20:14:45] Started run 209 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:45] Error in run 202: Run already exists in server. Run id(s): {9025956}
[2018-04-11 20:14:45] Started run 210 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:45] Error in run 203: Run already exists in server. Run id(s): {9025969}
[2018-04-11 20:14:45] Started run 211 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:46] Error in run 204: Run already exists in server. Run id(s): {9025970}
[2018-04-11 20:14:46] Error in run 207: Run already exists in server. Run id(s): {9026008}
[2018-04-11 20:14:46] Started run 212 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:46] Error in run 206: Run already exists in server. Run id(s): {9025999}
[2018-04-11 20:14:46] Error in run 205: Run already exists in server. Run id(s): {9025974}
[2018-04-11 20:14:46] Started run 214 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:46] Started run 215 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:46] Started run 213 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:47] Error in run 208: Run already exists in server. Run id(s): {9026006}
[2018-04-11 20:14:47] Started run 216 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:50] Error in run 209: Run already exists in server. Run id(s): {9026013}
[2018-04-11 20:14:50] Started run 217 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:50] Error in run 211: Run already exists in server. Run id(s): {9026024}
[2018-04-11 20:14:50] Started run 218 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:50] Error in run 210: Run already exists in server. Run id(s): {9026018}
[2018-04-11 20:14:50] Started run 219 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:51] Error in run 214: Run already exists in server. Run id(s): {9026061}
[2018-04-11 20:14:51] Started run 220 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:51] Error in run 215: Run already exists in server. Run id(s): {9026057}
[2018-04-11 20:14:51] Error in run 213: Run already exists in server. Run id(s): {9026049}
[2018-04-11 20:14:51] Started run 221 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:51] Error in run 212: Run already exists in server. Run id(s): {9026023}
[2018-04-11 20:14:51] Started run 223 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:51] Started run 222 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:51] Error in run 216: Run already exists in server. Run id(s): {9026070}
[2018-04-11 20:14:51] Started run 224 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:54] Error in run 217: Run already exists in server. Run id(s): {9026071}
[2018-04-11 20:14:54] Started run 225 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:54] Error in run 219: Run already exists in server. Run id(s): {9026077}
[2018-04-11 20:14:54] Started run 226 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:54] Error in run 218: Run already exists in server. Run id(s): {9026074}
[2018-04-11 20:14:54] Started run 227 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:55] Error in run 220: Run already exists in server. Run id(s): {9026221}
[2018-04-11 20:14:55] Started run 228 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:55] Error in run 221: Run already exists in server. Run id(s): {9026105}
[2018-04-11 20:14:55] Started run 229 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:55] Error in run 222: Run already exists in server. Run id(s): {9026111}
[2018-04-11 20:14:55] Error in run 223: Run already exists in server. Run id(s): {9026114}
[2018-04-11 20:14:55] Started run 230 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:55] Started run 231 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:56] Error in run 224: Run already exists in server. Run id(s): {9026116}
[2018-04-11 20:14:56] Started run 232 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:59] Error in run 225: Run already exists in server. Run id(s): {9026117}
[2018-04-11 20:14:59] Started run 233 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:59] Error in run 227: Run already exists in server. Run id(s): {9026148}
[2018-04-11 20:14:59] Error in run 226: Run already exists in server. Run id(s): {9026119}
[2018-04-11 20:14:59] Started run 234 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:14:59] Started run 235 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:00] Error in run 228: Run already exists in server. Run id(s): {9026156}
[2018-04-11 20:15:00] Started run 236 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:00] Error in run 229: Run already exists in server. Run id(s): {9026154}
[2018-04-11 20:15:00] Error in run 231: Run already exists in server. Run id(s): {9026164}
[2018-04-11 20:15:00] Error in run 230: Run already exists in server. Run id(s): {9026162}
[2018-04-11 20:15:00] Started run 237 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:00] Started run 238 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:00] Started run 239 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:01] Error in run 232: Run already exists in server. Run id(s): {9026159}
[2018-04-11 20:15:01] Started run 240 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:03] Error in run 233: Run already exists in server. Run id(s): {9026219}
[2018-04-11 20:15:03] Started run 241 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:04] Error in run 234: Run already exists in server. Run id(s): {9026205}
[2018-04-11 20:15:04] Started run 242 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:04] Error in run 235: Run already exists in server. Run id(s): {9026203}
[2018-04-11 20:15:04] Started run 243 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:04] Error in run 236: Run already exists in server. Run id(s): {9026208}
[2018-04-11 20:15:04] Started run 244 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:05] Error in run 237: Run already exists in server. Run id(s): {9026213}
[2018-04-11 20:15:05] Error in run 239: Run already exists in server. Run id(s): {9026220}
[2018-04-11 20:15:05] Started run 245 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:05] Started run 246 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:05] Error in run 238: Run already exists in server. Run id(s): {9026218}
[2018-04-11 20:15:05] Started run 247 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:05] Error in run 240: Run already exists in server. Run id(s): {9026255}
[2018-04-11 20:15:05] Started run 248 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:08] Error in run 241: Run already exists in server. Run id(s): {9026259}
[2018-04-11 20:15:08] Started run 249 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:08] Error in run 242: Run already exists in server. Run id(s): {9026254}
[2018-04-11 20:15:08] Started run 250 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:08] Error in run 243: Run already exists in server. Run id(s): {9026265}
[2018-04-11 20:15:08] Started run 251 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:09] Error in run 244: Run already exists in server. Run id(s): {9026263}
[2018-04-11 20:15:09] Started run 252 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:09] Error in run 245: Run already exists in server. Run id(s): {9026268}
[2018-04-11 20:15:09] Started run 253 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:09] Error in run 247: Run already exists in server. Run id(s): {9026273}
[2018-04-11 20:15:09] Error in run 246: Run already exists in server. Run id(s): {9026276}
[2018-04-11 20:15:09] Started run 254 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:09] Started run 255 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:10] Error in run 248: Run already exists in server. Run id(s): {9026301}
[2018-04-11 20:15:10] Started run 256 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:12] Error in run 249: Run already exists in server. Run id(s): {9026311}
[2018-04-11 20:15:12] Started run 257 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:13] Error in run 252: Run already exists in server. Run id(s): {9026314}
[2018-04-11 20:15:13] Started run 258 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:13] Error in run 251: Run already exists in server. Run id(s): {9026310}
[2018-04-11 20:15:13] Started run 259 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:13] Error in run 250: Run already exists in server. Run id(s): {9026304}
[2018-04-11 20:15:13] Started run 260 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:14] Error in run 253: Run already exists in server. Run id(s): {9026323}
[2018-04-11 20:15:14] Started run 261 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:14] Error in run 255: Run already exists in server. Run id(s): {9026317}
[2018-04-11 20:15:14] Started run 262 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:14] Error in run 254: Run already exists in server. Run id(s): {9026319}
[2018-04-11 20:15:14] Started run 263 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:15] Error in run 256: Run already exists in server. Run id(s): {9026354}
[2018-04-11 20:15:15] Started run 264 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:17] Error in run 257: Run already exists in server. Run id(s): {9026363}
[2018-04-11 20:15:17] Started run 265 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:18] Error in run 259: Run already exists in server. Run id(s): {9026364}
[2018-04-11 20:15:18] Error in run 260: Run already exists in server. Run id(s): {9026373}
[2018-04-11 20:15:18] Error in run 258: Run already exists in server. Run id(s): {9026358}
[2018-04-11 20:15:18] Started run 266 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:18] Started run 267 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:18] Started run 268 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:18] Error in run 261: Run already exists in server. Run id(s): {9026375}
[2018-04-11 20:15:18] Started run 269 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:19] Error in run 263: Run already exists in server. Run id(s): {9026374}
[2018-04-11 20:15:19] Error in run 262: Run already exists in server. Run id(s): {9026370}
[2018-04-11 20:15:19] Started run 270 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:19] Started run 271 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:19] Error in run 264: Run already exists in server. Run id(s): {9026396}
[2018-04-11 20:15:19] Started run 272 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:22] Error in run 265: Run already exists in server. Run id(s): {9026405}
[2018-04-11 20:15:22] Started run 273 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:23] Error in run 267: Run already exists in server. Run id(s): {9026416}
[2018-04-11 20:15:23] Error in run 269: Run already exists in server. Run id(s): {9026420}
[2018-04-11 20:15:23] Started run 274 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:23] Error in run 268: Run already exists in server. Run id(s): {9026419}
[2018-04-11 20:15:23] Started run 275 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:23] Error in run 266: Run already exists in server. Run id(s): {9026408}
[2018-04-11 20:15:23] Started run 277 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:23] Started run 276 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:23] Error in run 270: Run already exists in server. Run id(s): {9026423}
[2018-04-11 20:15:23] Started run 278 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:23] Error in run 271: Run already exists in server. Run id(s): {9026429}
[2018-04-11 20:15:23] Started run 279 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:24] Error in run 272: Run already exists in server. Run id(s): {9026474}
[2018-04-11 20:15:24] Started run 280 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:27] Error in run 273: Run already exists in server. Run id(s): {9026456}
[2018-04-11 20:15:27] Started run 281 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:27] Error in run 274: Run already exists in server. Run id(s): {9026463}
[2018-04-11 20:15:27] Started run 282 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:27] Error in run 277: Run already exists in server. Run id(s): {9026472}
[2018-04-11 20:15:27] Started run 283 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:27] Error in run 275: Run already exists in server. Run id(s): {9026465}
[2018-04-11 20:15:27] Started run 284 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:27] Error in run 276: Run already exists in server. Run id(s): {9026471}
[2018-04-11 20:15:27] Started run 285 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:28] Error in run 279: Run already exists in server. Run id(s): {9026473}
[2018-04-11 20:15:28] Error in run 278: Run already exists in server. Run id(s): {9026475}
[2018-04-11 20:15:28] Started run 286 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:28] Started run 287 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:28] Error in run 280: Run already exists in server. Run id(s): {9026512}
[2018-04-11 20:15:28] Started run 288 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:31] Error in run 281: Run already exists in server. Run id(s): {9026516}
[2018-04-11 20:15:31] Started run 289 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:32] Error in run 284: Run already exists in server. Run id(s): {9026526}
[2018-04-11 20:15:32] Error in run 283: Run already exists in server. Run id(s): {9026528}
[2018-04-11 20:15:32] Started run 291 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:32] Error in run 282: Run already exists in server. Run id(s): {9026519}
[2018-04-11 20:15:32] Started run 292 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:32] Error in run 285: Run already exists in server. Run id(s): {9026524}
[2018-04-11 20:15:32] Started run 290 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:32] Started run 293 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:33] Error in run 287: Run already exists in server. Run id(s): {9026534}
[2018-04-11 20:15:33] Started run 294 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:33] Error in run 286: Run already exists in server. Run id(s): {9026527}
[2018-04-11 20:15:33] Started run 295 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:33] Error in run 288: Run already exists in server. Run id(s): {9026555}
[2018-04-11 20:15:33] Started run 296 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:36] Error in run 289: Run already exists in server. Run id(s): {9026565}
[2018-04-11 20:15:36] Started run 297 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:37] Error in run 291: Run already exists in server. Run id(s): {9026571}
[2018-04-11 20:15:37] Error in run 290: Run already exists in server. Run id(s): {9026569}
[2018-04-11 20:15:37] Started run 298 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:37] Error in run 293: Run already exists in server. Run id(s): {9026574}
[2018-04-11 20:15:37] Error in run 292: Run already exists in server. Run id(s): {9026572}
[2018-04-11 20:15:37] Started run 300 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:37] Started run 301 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:37] Started run 299 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:37] Error in run 294: Run already exists in server. Run id(s): {9026577}
[2018-04-11 20:15:38] Error in run 295: Run already exists in server. Run id(s): {9026579}
[2018-04-11 20:15:37] Started run 302 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:38] Error in run 296: Run already exists in server. Run id(s): {9026595}
[2018-04-11 20:15:38] Started run 304 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:38] Started run 303 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:41] Error in run 297: Run already exists in server. Run id(s): {9026602}
[2018-04-11 20:15:41] Started run 305 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:41] Error in run 299: Run already exists in server. Run id(s): {9026626}
[2018-04-11 20:15:41] Error in run 300: Run already exists in server. Run id(s): {9026618}
[2018-04-11 20:15:41] Started run 306 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:41] Error in run 298: Run already exists in server. Run id(s): {9026621}
[2018-04-11 20:15:41] Error in run 301: Run already exists in server. Run id(s): {9026616}
[2018-04-11 20:15:41] Started run 308 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:41] Started run 309 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:41] Started run 307 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:42] Error in run 304: Run already exists in server. Run id(s): {9026640}
[2018-04-11 20:15:42] Error in run 303: Run already exists in server. Run id(s): {9026629}
[2018-04-11 20:15:42] Started run 310 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:42] Error in run 302: Run already exists in server. Run id(s): {9026627}
[2018-04-11 20:15:42] Started run 312 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:42] Started run 311 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:45] Error in run 305: Run already exists in server. Run id(s): {9026652}
[2018-04-11 20:15:45] Started run 313 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:46] Error in run 307: Run already exists in server. Run id(s): {9026657}
[2018-04-11 20:15:46] Error in run 306: Run already exists in server. Run id(s): {9026658}
[2018-04-11 20:15:46] Started run 314 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:46] Error in run 309: Run already exists in server. Run id(s): {9026672}
[2018-04-11 20:15:46] Error in run 308: Run already exists in server. Run id(s): {9026665}
[2018-04-11 20:15:46] Started run 316 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:46] Started run 317 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:46] Started run 315 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:47] Error in run 312: Run already exists in server. Run id(s): {9026673}
[2018-04-11 20:15:47] Started run 318 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:47] Error in run 310: Run already exists in server. Run id(s): {9026662}
[2018-04-11 20:15:47] Error in run 311: Run already exists in server. Run id(s): {9026668}
[2018-04-11 20:15:47] Started run 319 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:47] Started run 320 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:50] Error in run 313: Run already exists in server. Run id(s): {9026692}
[2018-04-11 20:15:50] Started run 321 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:51] Error in run 314: Run already exists in server. Run id(s): {9026707}
[2018-04-11 20:15:51] Started run 322 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:51] Error in run 316: Run already exists in server. Run id(s): {9026703}
[2018-04-11 20:15:51] Started run 323 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:51] Error in run 317: Run already exists in server. Run id(s): {9026712}
[2018-04-11 20:15:51] Started run 324 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:51] Error in run 315: Run already exists in server. Run id(s): {9026713}
[2018-04-11 20:15:51] Started run 325 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:51] Error in run 318: Run already exists in server. Run id(s): {9026762, 9026711}
[2018-04-11 20:15:51] Started run 326 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:52] Error in run 320: Run already exists in server. Run id(s): {9026726}
[2018-04-11 20:15:52] Started run 327 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:52] Error in run 319: Run already exists in server. Run id(s): {9026714}
[2018-04-11 20:15:52] Started run 328 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:55] Error in run 321: Run already exists in server. Run id(s): {9026823}
[2018-04-11 20:15:55] Started run 329 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:55] Error in run 325: Run already exists in server. Run id(s): {9026761}
[2018-04-11 20:15:55] Error in run 322: Run already exists in server. Run id(s): {9026750}
[2018-04-11 20:15:55] Error in run 323: Run already exists in server. Run id(s): {9026755}
[2018-04-11 20:15:55] Started run 330 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:55] Started run 332 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:55] Error in run 324: Run already exists in server. Run id(s): {9026767}
[2018-04-11 20:15:55] Started run 333 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:55] Started run 331 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:56] Error in run 327: Run already exists in server. Run id(s): {9026769}
[2018-04-11 20:15:56] Error in run 328: Run already exists in server. Run id(s): {9026795}
[2018-04-11 20:15:56] Started run 334 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:56] Error in run 326: Run already exists in server. Run id(s): {9026758}
[2018-04-11 20:15:56] Started run 335 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:56] Started run 336 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:15:59] Error in run 329: Run already exists in server. Run id(s): {9026790}
[2018-04-11 20:15:59] Started run 337 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:00] Error in run 332: Run already exists in server. Run id(s): {9026807}
[2018-04-11 20:16:00] Started run 338 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:00] Error in run 333: Run already exists in server. Run id(s): {9026810}
[2018-04-11 20:16:00] Error in run 331: Run already exists in server. Run id(s): {9026797}
[2018-04-11 20:16:00] Started run 339 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:00] Error in run 330: Run already exists in server. Run id(s): {9026794}
[2018-04-11 20:16:00] Started run 341 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:00] Started run 340 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:01] Error in run 335: Run already exists in server. Run id(s): {9026836}
[2018-04-11 20:16:01] Error in run 336: Run already exists in server. Run id(s): {9026841}
[2018-04-11 20:16:01] Error in run 334: Run already exists in server. Run id(s): {9026813}
[2018-04-11 20:16:01] Started run 342 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:01] Started run 343 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:01] Started run 344 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:04] Error in run 337: Run already exists in server. Run id(s): {9026854}
[2018-04-11 20:16:04] Started run 345 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:05] Error in run 341: Run already exists in server. Run id(s): {9026861}
[2018-04-11 20:16:05] Error in run 338: Run already exists in server. Run id(s): {9026845}
[2018-04-11 20:16:05] Error in run 339: Run already exists in server. Run id(s): {9026862}
[2018-04-11 20:16:05] Error in run 340: Run already exists in server. Run id(s): {9026858}
[2018-04-11 20:16:05] Started run 346 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:05] Started run 347 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:05] Started run 348 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:05] Started run 349 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:06] Error in run 343: Run already exists in server. Run id(s): {9026878}
[2018-04-11 20:16:06] Error in run 344: Run already exists in server. Run id(s): {9026888}
[2018-04-11 20:16:06] Started run 350 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:06] Started run 351 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:06] Error in run 342: Run already exists in server. Run id(s): {9026872}
[2018-04-11 20:16:06] Started run 352 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:09] Error in run 345: Run already exists in server. Run id(s): {9026896}
[2018-04-11 20:16:09] Started run 353 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:09] Error in run 349: Run already exists in server. Run id(s): {9026912}
[2018-04-11 20:16:09] Started run 354 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:10] Error in run 346: Run already exists in server. Run id(s): {9026923}
[2018-04-11 20:16:10] Started run 355 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:10] Error in run 347: Run already exists in server. Run id(s): {9026909}
[2018-04-11 20:16:10] Error in run 348: Run already exists in server. Run id(s): {9026981}
[2018-04-11 20:16:10] Started run 356 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:10] Started run 357 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:10] Error in run 350: Run already exists in server. Run id(s): {9026915}
[2018-04-11 20:16:10] Error in run 351: Run already exists in server. Run id(s): {9026930}
[2018-04-11 20:16:10] Started run 358 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:10] Error in run 352: Run already exists in server. Run id(s): {9026944}
[2018-04-11 20:16:10] Started run 360 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:10] Started run 359 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:13] Error in run 353: Run already exists in server. Run id(s): {9026943}
[2018-04-11 20:16:13] Started run 361 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:14] Error in run 354: Run already exists in server. Run id(s): {9026945}
[2018-04-11 20:16:14] Started run 362 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:14] Error in run 355: Run already exists in server. Run id(s): {9026953}
[2018-04-11 20:16:14] Started run 363 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:14] Error in run 356: Run already exists in server. Run id(s): {9026951}
[2018-04-11 20:16:14] Started run 364 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:14] Error in run 357: Run already exists in server. Run id(s): {9026960}
[2018-04-11 20:16:14] Started run 365 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:15] Error in run 358: Run already exists in server. Run id(s): {9026976}
[2018-04-11 20:16:15] Started run 366 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:15] Error in run 360: Run already exists in server. Run id(s): {9026987}
[2018-04-11 20:16:15] Error in run 359: Run already exists in server. Run id(s): {9026988}
[2018-04-11 20:16:15] Started run 367 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:15] Started run 368 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:18] Error in run 361: Run already exists in server. Run id(s): {9026994}
[2018-04-11 20:16:18] Started run 369 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:18] Error in run 362: Run already exists in server. Run id(s): {9026997}
[2018-04-11 20:16:18] Started run 370 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:19] Error in run 363: Run already exists in server. Run id(s): {9027001}
[2018-04-11 20:16:19] Error in run 365: Run already exists in server. Run id(s): {9027020}
[2018-04-11 20:16:19] Started run 371 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:19] Error in run 364: Run already exists in server. Run id(s): {9027002}
[2018-04-11 20:16:19] Started run 373 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:19] Started run 372 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:19] Error in run 366: Run already exists in server. Run id(s): {9027027}
[2018-04-11 20:16:19] Started run 374 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:20] Error in run 367: Run already exists in server. Run id(s): {9027030}
[2018-04-11 20:16:20] Started run 375 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:20] Error in run 368: Run already exists in server. Run id(s): {9027029}
[2018-04-11 20:16:20] Started run 376 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:23] Error in run 369: Run already exists in server. Run id(s): {9027039}
[2018-04-11 20:16:23] Started run 377 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:23] Error in run 370: Run already exists in server. Run id(s): {9027037}
[2018-04-11 20:16:23] Started run 378 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:24] Error in run 373: Run already exists in server. Run id(s): {9027057}
[2018-04-11 20:16:24] Started run 379 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:24] Error in run 371: Run already exists in server. Run id(s): {9027043}
[2018-04-11 20:16:24] Error in run 372: Run already exists in server. Run id(s): {9027050}
[2018-04-11 20:16:24] Started run 380 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:24] Started run 381 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:24] Error in run 374: Run already exists in server. Run id(s): {9027073}
[2018-04-11 20:16:24] Started run 382 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:24] Error in run 376: Run already exists in server. Run id(s): {9027078}
[2018-04-11 20:16:24] Error in run 375: Run already exists in server. Run id(s): {9027075}
[2018-04-11 20:16:24] Started run 383 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:24] Started run 384 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:27] Error in run 377: Run already exists in server. Run id(s): {9027082}
[2018-04-11 20:16:27] Started run 385 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:28] Error in run 378: Run already exists in server. Run id(s): {9027086}
[2018-04-11 20:16:28] Started run 386 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:28] Error in run 380: Run already exists in server. Run id(s): {9027099}
[2018-04-11 20:16:28] Error in run 379: Run already exists in server. Run id(s): {9027087}
[2018-04-11 20:16:28] Started run 387 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:28] Error in run 381: Run already exists in server. Run id(s): {9027106}
[2018-04-11 20:16:28] Started run 388 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:28] Started run 389 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:28] Error in run 382: Run already exists in server. Run id(s): {9027114}
[2018-04-11 20:16:28] Started run 390 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:29] Error in run 384: Run already exists in server. Run id(s): {9027126}
[2018-04-11 20:16:29] Started run 391 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:29] Error in run 383: Run already exists in server. Run id(s): {9027131}
[2018-04-11 20:16:29] Started run 392 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:32] Error in run 385: Run already exists in server. Run id(s): {9027130}
[2018-04-11 20:16:32] Started run 393 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:32] Error in run 386: Run already exists in server. Run id(s): {9027133}
[2018-04-11 20:16:32] Started run 394 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:33] Error in run 388: Run already exists in server. Run id(s): {9027144}
[2018-04-11 20:16:33] Error in run 389: Run already exists in server. Run id(s): {9027153}
[2018-04-11 20:16:33] Started run 395 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:33] Error in run 387: Run already exists in server. Run id(s): {9027145}
[2018-04-11 20:16:33] Started run 397 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:33] Started run 396 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:33] Error in run 390: Run already exists in server. Run id(s): {9027158}
[2018-04-11 20:16:33] Started run 398 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:34] Error in run 391: Run already exists in server. Run id(s): {9027170}
[2018-04-11 20:16:34] Started run 399 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:34] Error in run 392: Run already exists in server. Run id(s): {9027178}
[2018-04-11 20:16:34] Started run 400 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:37] Error in run 394: Run already exists in server. Run id(s): {9027185}
[2018-04-11 20:16:37] Started run 401 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:37] Error in run 393: Run already exists in server. Run id(s): {9027187}
[2018-04-11 20:16:37] Started run 402 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:38] Error in run 397: Run already exists in server. Run id(s): {9027204}
[2018-04-11 20:16:38] Error in run 395: Run already exists in server. Run id(s): {9027193}
[2018-04-11 20:16:38] Started run 403 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:38] Error in run 398: Run already exists in server. Run id(s): {9027211}
[2018-04-11 20:16:38] Started run 404 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:38] Error in run 396: Run already exists in server. Run id(s): {9027189}
[2018-04-11 20:16:38] Started run 406 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:38] Started run 405 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:38] Error in run 399: Run already exists in server. Run id(s): {9027223}
[2018-04-11 20:16:38] Started run 407 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:38] Error in run 400: Run already exists in server. Run id(s): {9027226}
[2018-04-11 20:16:38] Started run 408 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:41] Error in run 401: Run already exists in server. Run id(s): {9027232}
[2018-04-11 20:16:41] Started run 409 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:41] Error in run 402: Run already exists in server. Run id(s): {9027229}
[2018-04-11 20:16:41] Started run 410 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:42] Error in run 405: Run already exists in server. Run id(s): {9027253}
[2018-04-11 20:16:42] Error in run 406: Run already exists in server. Run id(s): {9027260}
[2018-04-11 20:16:42] Error in run 404: Run already exists in server. Run id(s): {9027245}
[2018-04-11 20:16:42] Started run 411 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:42] Started run 412 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:42] Started run 413 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:42] Error in run 403: Run already exists in server. Run id(s): {9027235}
[2018-04-11 20:16:42] Started run 414 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:43] Error in run 407: Run already exists in server. Run id(s): {9027272}
[2018-04-11 20:16:43] Started run 415 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:43] Error in run 408: Run already exists in server. Run id(s): {9027279}
[2018-04-11 20:16:43] Started run 416 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:46] Error in run 410: Run already exists in server. Run id(s): {9027283}
[2018-04-11 20:16:46] Started run 417 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:46] Error in run 409: Run already exists in server. Run id(s): {9027276}
[2018-04-11 20:16:46] Started run 418 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:47] Error in run 413: Run already exists in server. Run id(s): {9027309}
[2018-04-11 20:16:47] Error in run 412: Run already exists in server. Run id(s): {9027294}
[2018-04-11 20:16:47] Started run 419 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:47] Error in run 411: Run already exists in server. Run id(s): {9027282}
[2018-04-11 20:16:47] Error in run 414: Run already exists in server. Run id(s): {9027314}
[2018-04-11 20:16:47] Started run 421 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:47] Started run 422 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:47] Started run 420 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:47] Error in run 415: Run already exists in server. Run id(s): {9027335}
[2018-04-11 20:16:47] Started run 423 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:48] Error in run 416: Run already exists in server. Run id(s): {9027334}
[2018-04-11 20:16:48] Started run 424 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:51] Error in run 417: Run already exists in server. Run id(s): {9027330}
[2018-04-11 20:16:51] Started run 425 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:51] Error in run 418: Run already exists in server. Run id(s): {9027413}
[2018-04-11 20:16:51] Started run 426 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:52] Error in run 422: Run already exists in server. Run id(s): {9027372}
[2018-04-11 20:16:52] Started run 427 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:52] Error in run 419: Run already exists in server. Run id(s): {9027356}
[2018-04-11 20:16:52] Error in run 420: Run already exists in server. Run id(s): {9027348}
[2018-04-11 20:16:52] Error in run 421: Run already exists in server. Run id(s): {9027368}
[2018-04-11 20:16:52] Started run 428 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:52] Started run 429 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:52] Started run 430 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:52] Error in run 423: Run already exists in server. Run id(s): {9027377}
[2018-04-11 20:16:52] Started run 431 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:52] Error in run 424: Run already exists in server. Run id(s): {9027399}
[2018-04-11 20:16:52] Started run 432 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:56] Error in run 425: Run already exists in server. Run id(s): {9027387}
[2018-04-11 20:16:56] Started run 433 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:56] Error in run 426: Run already exists in server. Run id(s): {9027461}
[2018-04-11 20:16:56] Started run 434 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:56] Error in run 429: Run already exists in server. Run id(s): {9027420}
[2018-04-11 20:16:56] Error in run 430: Run already exists in server. Run id(s): {9027429}
[2018-04-11 20:16:56] Started run 435 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:56] Error in run 428: Run already exists in server. Run id(s): {9027412}
[2018-04-11 20:16:56] Started run 437 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:56] Error in run 427: Run already exists in server. Run id(s): {9027404}
[2018-04-11 20:16:56] Started run 438 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:56] Started run 436 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:56] Error in run 431: Run already exists in server. Run id(s): {9027434}
[2018-04-11 20:16:56] Started run 439 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:16:57] Error in run 432: Run already exists in server. Run id(s): {9027439}
[2018-04-11 20:16:57] Started run 440 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:00] Error in run 433: Run already exists in server. Run id(s): {9027444}
[2018-04-11 20:17:00] Started run 441 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:00] Error in run 434: Run already exists in server. Run id(s): {9027465}
[2018-04-11 20:17:00] Started run 442 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:01] Error in run 435: Run already exists in server. Run id(s): {9027462}
[2018-04-11 20:17:01] Started run 443 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:01] Error in run 438: Run already exists in server. Run id(s): {8962529}
[2018-04-11 20:17:01] Started run 444 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:01] Error in run 437: Run already exists in server. Run id(s): {9027480}
[2018-04-11 20:17:01] Started run 445 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:01] Error in run 439: Run already exists in server. Run id(s): {9027491}
[2018-04-11 20:17:01] Started run 446 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:01] Error in run 436: Run already exists in server. Run id(s): {9027469}
[2018-04-11 20:17:01] Started run 447 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:02] Error in run 440: Run already exists in server. Run id(s): {9027492}
[2018-04-11 20:17:02] Started run 448 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:05] Error in run 441: Run already exists in server. Run id(s): {9027493}
[2018-04-11 20:17:05] Started run 449 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:05] Error in run 442: Run already exists in server. Run id(s): {9027556, 9027511}
[2018-04-11 20:17:05] Started run 450 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:05] Error in run 444: Run already exists in server. Run id(s): {9027509}
[2018-04-11 20:17:05] Started run 451 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:05] Error in run 443: Run already exists in server. Run id(s): {9027510}
[2018-04-11 20:17:05] Started run 452 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:05] Error in run 445: Run already exists in server. Run id(s): {8962531}
[2018-04-11 20:17:05] Started run 453 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:06] Error in run 446: Run already exists in server. Run id(s): {9027523}
[2018-04-11 20:17:06] Started run 454 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:06] Error in run 447: Run already exists in server. Run id(s): {9027526}
[2018-04-11 20:17:06] Started run 455 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:06] Error in run 448: Run already exists in server. Run id(s): {9027544}
[2018-04-11 20:17:06] Started run 456 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:09] Error in run 449: Run already exists in server. Run id(s): {9027541}
[2018-04-11 20:17:09] Started run 457 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:09] Error in run 450: Run already exists in server. Run id(s): {9027542}
[2018-04-11 20:17:09] Started run 458 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:10] Error in run 452: Run already exists in server. Run id(s): {9027560}
[2018-04-11 20:17:10] Started run 459 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:10] Error in run 451: Run already exists in server. Run id(s): {9027559}
[2018-04-11 20:17:10] Started run 460 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:10] Error in run 453: Run already exists in server. Run id(s): {9027580}
[2018-04-11 20:17:10] Started run 461 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:10] Error in run 454: Run already exists in server. Run id(s): {9027579}
[2018-04-11 20:17:10] Started run 462 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:10] Error in run 455: Run already exists in server. Run id(s): {9027587}
[2018-04-11 20:17:10] Started run 463 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:11] Error in run 456: Run already exists in server. Run id(s): {9027595}
[2018-04-11 20:17:11] Started run 464 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:14] Error in run 458: Run already exists in server. Run id(s): {9027604}
[2018-04-11 20:17:14] Started run 465 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:14] Error in run 457: Run already exists in server. Run id(s): {9027601}
[2018-04-11 20:17:14] Started run 466 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:14] Error in run 459: Run already exists in server. Run id(s): {9027608}
[2018-04-11 20:17:14] Started run 467 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:14] Error in run 460: Run already exists in server. Run id(s): {9027609}
[2018-04-11 20:17:14] Started run 468 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:15] Error in run 461: Run already exists in server. Run id(s): {9027626}
[2018-04-11 20:17:15] Started run 469 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:15] Error in run 462: Run already exists in server. Run id(s): {9027629}
[2018-04-11 20:17:15] Started run 470 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:15] Error in run 463: Run already exists in server. Run id(s): {9027639}
[2018-04-11 20:17:15] Started run 471 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:16] Error in run 464: Run already exists in server. Run id(s): {9027645}
[2018-04-11 20:17:16] Started run 472 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:18] Error in run 466: Run already exists in server. Run id(s): {9027653}
[2018-04-11 20:17:18] Started run 473 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:18] Error in run 465: Run already exists in server. Run id(s): {9027654}
[2018-04-11 20:17:18] Started run 474 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:19] Error in run 468: Run already exists in server. Run id(s): {9027656}
[2018-04-11 20:17:19] Started run 475 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:19] Error in run 467: Run already exists in server. Run id(s): {9027658}
[2018-04-11 20:17:19] Started run 476 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:19] Error in run 469: Run already exists in server. Run id(s): {9027674}
[2018-04-11 20:17:19] Started run 477 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:20] Error in run 470: Run already exists in server. Run id(s): {9027681}
[2018-04-11 20:17:20] Started run 478 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:20] Error in run 471: Run already exists in server. Run id(s): {9027692}
[2018-04-11 20:17:20] Started run 479 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:20] Error in run 472: Run already exists in server. Run id(s): {9027695}
[2018-04-11 20:17:20] Started run 480 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:23] Error in run 473: Run already exists in server. Run id(s): {9027714}
[2018-04-11 20:17:23] Started run 481 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:23] Error in run 474: Run already exists in server. Run id(s): {9027710}
[2018-04-11 20:17:23] Started run 482 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:24] Error in run 476: Run already exists in server. Run id(s): {9027715}
[2018-04-11 20:17:24] Started run 483 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:24] Error in run 475: Run already exists in server. Run id(s): {8962541}
[2018-04-11 20:17:24] Started run 484 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:24] Error in run 477: Run already exists in server. Run id(s): {9027721}
[2018-04-11 20:17:24] Started run 485 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:24] Error in run 478: Run already exists in server. Run id(s): {9027724}
[2018-04-11 20:17:24] Started run 486 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:25] Error in run 479: Run already exists in server. Run id(s): {9027732}
[2018-04-11 20:17:25] Started run 487 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:25] Error in run 480: Run already exists in server. Run id(s): {9027746}
[2018-04-11 20:17:25] Started run 488 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:28] Error in run 481: Run already exists in server. Run id(s): {9027759}
[2018-04-11 20:17:28] Started run 489 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:28] Error in run 482: Run already exists in server. Run id(s): {9027758}
[2018-04-11 20:17:28] Started run 490 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:29] Error in run 483: Run already exists in server. Run id(s): {8962530}
[2018-04-11 20:17:29] Started run 491 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:29] Error in run 484: Run already exists in server. Run id(s): {9027765}
[2018-04-11 20:17:29] Started run 492 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:29] Error in run 485: Run already exists in server. Run id(s): {9027766}
[2018-04-11 20:17:29] Started run 493 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:29] Error in run 486: Run already exists in server. Run id(s): {9027772}
[2018-04-11 20:17:29] Started run 494 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:29] Error in run 487: Run already exists in server. Run id(s): {9027787}
[2018-04-11 20:17:29] Started run 495 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:30] Error in run 488: Run already exists in server. Run id(s): {9027799}
[2018-04-11 20:17:30] Started run 496 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:32] Error in run 490: Run already exists in server. Run id(s): {9027873}
[2018-04-11 20:17:32] Started run 497 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:32] Error in run 489: Run already exists in server. Run id(s): {9027840}
[2018-04-11 20:17:32] Started run 498 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:33] Error in run 492: Run already exists in server. Run id(s): {9027816}
[2018-04-11 20:17:33] Started run 499 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:33] Error in run 491: Run already exists in server. Run id(s): {8962539}
[2018-04-11 20:17:33] Started run 500 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:33] Error in run 493: Run already exists in server. Run id(s): {8962537}
[2018-04-11 20:17:33] Started run 501 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:34] Error in run 494: Run already exists in server. Run id(s): {8962540}
[2018-04-11 20:17:34] Started run 502 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:34] Error in run 495: Run already exists in server. Run id(s): {9027827}
[2018-04-11 20:17:34] Started run 503 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:34] Error in run 496: Run already exists in server. Run id(s): {8962535}
[2018-04-11 20:17:34] Started run 504 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:37] Error in run 497: Run already exists in server. Run id(s): {8962543}
[2018-04-11 20:17:37] Started run 505 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:37] Error in run 498: Run already exists in server. Run id(s): {8962548}
[2018-04-11 20:17:37] Started run 506 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:38] Error in run 500: Run already exists in server. Run id(s): {8962556}
[2018-04-11 20:17:38] Started run 507 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:38] Error in run 501: Run already exists in server. Run id(s): {8962549}
[2018-04-11 20:17:38] Error in run 499: Run already exists in server. Run id(s): {8962544}
[2018-04-11 20:17:38] Started run 508 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:38] Started run 509 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:38] Error in run 502: Run already exists in server. Run id(s): {9027856}
[2018-04-11 20:17:38] Started run 510 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:39] Error in run 503: Run already exists in server. Run id(s): {9027863}
[2018-04-11 20:17:39] Started run 511 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:39] Error in run 504: Run already exists in server. Run id(s): {8962532}
[2018-04-11 20:17:39] Started run 512 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:42] Error in run 505: Run already exists in server. Run id(s): {8962534}
[2018-04-11 20:17:42] Started run 513 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:42] Error in run 506: Run already exists in server. Run id(s): {8962559}
[2018-04-11 20:17:42] Started run 514 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:43] Error in run 507: Run already exists in server. Run id(s): {8962533}
[2018-04-11 20:17:43] Started run 515 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:43] Error in run 508: Run already exists in server. Run id(s): {9027872}
[2018-04-11 20:17:43] Started run 516 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:43] Error in run 509: Run already exists in server. Run id(s): {8962538}
[2018-04-11 20:17:43] Started run 517 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:43] Error in run 510: Run already exists in server. Run id(s): {8962558}
[2018-04-11 20:17:43] Started run 518 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:44] Error in run 511: Run already exists in server. Run id(s): {8962552}
[2018-04-11 20:17:44] Started run 519 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:44] Error in run 512: Run already exists in server. Run id(s): {8962551}
[2018-04-11 20:17:44] Started run 520 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:47] Error in run 514: Run already exists in server. Run id(s): {8962557}
[2018-04-11 20:17:47] Started run 521 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:47] Error in run 513: Run already exists in server. Run id(s): {8962555}
[2018-04-11 20:17:47] Started run 522 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:47] Error in run 515: Run already exists in server. Run id(s): {9027891}
[2018-04-11 20:17:47] Started run 523 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:47] Error in run 517: Run already exists in server. Run id(s): {8962546}
[2018-04-11 20:17:47] Started run 524 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:48] Error in run 516: Run already exists in server. Run id(s): {9027905}
[2018-04-11 20:17:48] Started run 525 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:48] Error in run 518: Run already exists in server. Run id(s): {9027913}
[2018-04-11 20:17:48] Started run 526 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:48] Error in run 520: Run already exists in server. Run id(s): {9028006}
[2018-04-11 20:17:48] Started run 527 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:48] Error in run 519: Run already exists in server. Run id(s): {9027912}
[2018-04-11 20:17:48] Started run 528 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:51] Error in run 521: Run already exists in server. Run id(s): {9027931}
[2018-04-11 20:17:51] Started run 529 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:51] Error in run 522: Run already exists in server. Run id(s): {8962550}
[2018-04-11 20:17:51] Started run 530 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:52] Error in run 523: Run already exists in server. Run id(s): {8962547}
[2018-04-11 20:17:52] Started run 531 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:52] Error in run 524: Run already exists in server. Run id(s): {8962545}
[2018-04-11 20:17:52] Started run 532 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:52] Error in run 525: Run already exists in server. Run id(s): {8962554}
[2018-04-11 20:17:52] Started run 533 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:52] Error in run 526: Run already exists in server. Run id(s): {8962542}
[2018-04-11 20:17:52] Started run 534 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:53] Error in run 527: Run already exists in server. Run id(s): {8962536}
[2018-04-11 20:17:53] Started run 535 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:53] Error in run 528: Run already exists in server. Run id(s): {9027959}
[2018-04-11 20:17:53] Started run 536 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:56] Error in run 530: Run already exists in server. Run id(s): {9027965}
[2018-04-11 20:17:56] Started run 537 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:56] Error in run 529: Run already exists in server. Run id(s): {9027956}
[2018-04-11 20:17:56] Started run 538 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:57] Error in run 531: Run already exists in server. Run id(s): {8962553}
[2018-04-11 20:17:57] Started run 539 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:57] Error in run 533: Run already exists in server. Run id(s): {9027970}
[2018-04-11 20:17:57] Started run 540 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:57] Error in run 532: Run already exists in server. Run id(s): {8962561}
[2018-04-11 20:17:57] Started run 541 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:57] Error in run 534: Run already exists in server. Run id(s): {9027973}
[2018-04-11 20:17:57] Started run 542 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:58] Error in run 535: Run already exists in server. Run id(s): {8962562}
[2018-04-11 20:17:58] Started run 543 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:17:58] Error in run 536: Run already exists in server. Run id(s): {9027987}
[2018-04-11 20:17:58] Started run 544 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:01] Error in run 538: Run already exists in server. Run id(s): {8962560}
[2018-04-11 20:18:01] Started run 545 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:01] Error in run 537: Run already exists in server. Run id(s): {9028008}
[2018-04-11 20:18:01] Started run 546 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:01] Error in run 539: Run already exists in server. Run id(s): {9028013}
[2018-04-11 20:18:01] Started run 547 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:02] Error in run 541: Run already exists in server. Run id(s): {9028017}
[2018-04-11 20:18:02] Started run 548 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:02] Error in run 540: Run already exists in server. Run id(s): {9028014}
[2018-04-11 20:18:02] Started run 549 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:02] Error in run 542: Run already exists in server. Run id(s): {9028022}
[2018-04-11 20:18:02] Started run 550 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:03] Error in run 543: Run already exists in server. Run id(s): {9028034}
[2018-04-11 20:18:03] Started run 551 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:03] Error in run 544: Run already exists in server. Run id(s): {9028036}
[2018-04-11 20:18:03] Started run 552 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:05] Error in run 545: Run already exists in server. Run id(s): {9028049}
[2018-04-11 20:18:05] Started run 553 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:06] Error in run 546: Run already exists in server. Run id(s): {9028050}
[2018-04-11 20:18:06] Started run 554 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:06] Error in run 547: Run already exists in server. Run id(s): {9028066}
[2018-04-11 20:18:06] Started run 555 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:06] Error in run 548: Run already exists in server. Run id(s): {9028065}
[2018-04-11 20:18:06] Error in run 549: Run already exists in server. Run id(s): {9028069}
[2018-04-11 20:18:06] Started run 556 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:06] Started run 557 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:06] Error in run 550: Run already exists in server. Run id(s): {9028073}
[2018-04-11 20:18:06] Started run 558 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:07] Error in run 551: Run already exists in server. Run id(s): {9028083}
[2018-04-11 20:18:07] Started run 559 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:07] Error in run 552: Run already exists in server. Run id(s): {9028092}
[2018-04-11 20:18:07] Started run 560 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:10] Error in run 553: Run already exists in server. Run id(s): {8962563}
[2018-04-11 20:18:10] Started run 561 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:10] Error in run 554: Run already exists in server. Run id(s): {9028104}
[2018-04-11 20:18:10] Started run 562 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:11] Error in run 555: Run already exists in server. Run id(s): {9028101}
[2018-04-11 20:18:11] Started run 563 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:11] Error in run 558: Run already exists in server. Run id(s): {9028127}
[2018-04-11 20:18:11] Started run 564 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:11] Error in run 557: Run already exists in server. Run id(s): {9028119}
[2018-04-11 20:18:11] Started run 565 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:11] Error in run 556: Run already exists in server. Run id(s): {9028117}
[2018-04-11 20:18:11] Started run 566 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:12] Error in run 560: Run already exists in server. Run id(s): {9028159}
[2018-04-11 20:18:12] Started run 567 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:12] Error in run 559: Run already exists in server. Run id(s): {9028123}
[2018-04-11 20:18:12] Started run 568 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:15] Error in run 561: Run already exists in server. Run id(s): {9028163}
[2018-04-11 20:18:15] Started run 569 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:15] Error in run 562: Run already exists in server. Run id(s): {9028174}
[2018-04-11 20:18:15] Started run 570 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:16] Error in run 563: Run already exists in server. Run id(s): {9028172}
[2018-04-11 20:18:16] Started run 571 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:16] Error in run 565: Run already exists in server. Run id(s): {9028173}
[2018-04-11 20:18:16] Started run 572 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:16] Error in run 564: Run already exists in server. Run id(s): {9028175}
[2018-04-11 20:18:16] Started run 573 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:16] Error in run 566: Run already exists in server. Run id(s): {9028176}
[2018-04-11 20:18:16] Started run 574 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:17] Error in run 567: Run already exists in server. Run id(s): {9028177}
[2018-04-11 20:18:17] Started run 575 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:17] Error in run 568: Run already exists in server. Run id(s): {9028216}
[2018-04-11 20:18:17] Started run 576 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:20] Error in run 569: Run already exists in server. Run id(s): {9028298}
[2018-04-11 20:18:20] Started run 577 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:20] Error in run 570: Run already exists in server. Run id(s): {9028220}
[2018-04-11 20:18:20] Started run 578 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:20] Error in run 571: Run already exists in server. Run id(s): {9028218}
[2018-04-11 20:18:20] Started run 579 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:21] Error in run 573: Run already exists in server. Run id(s): {9028219}
[2018-04-11 20:18:21] Started run 580 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:21] Error in run 572: Run already exists in server. Run id(s): {9028221}
[2018-04-11 20:18:21] Started run 581 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:21] Error in run 574: Run already exists in server. Run id(s): {9028223}
[2018-04-11 20:18:21] Started run 582 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:21] Error in run 576: Run already exists in server. Run id(s): {9028268}
[2018-04-11 20:18:21] Started run 583 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:21] Error in run 575: Run already exists in server. Run id(s): {9028227}
[2018-04-11 20:18:21] Started run 584 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:24] Error in run 577: Run already exists in server. Run id(s): {9028260}
[2018-04-11 20:18:24] Started run 585 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:25] Error in run 578: Run already exists in server. Run id(s): {9028270}
[2018-04-11 20:18:25] Started run 586 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:25] Error in run 580: Run already exists in server. Run id(s): {9028275}
[2018-04-11 20:18:25] Started run 587 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:25] Error in run 579: Run already exists in server. Run id(s): {9028264}
[2018-04-11 20:18:25] Started run 588 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:25] Error in run 582: Run already exists in server. Run id(s): {9028276}
[2018-04-11 20:18:25] Started run 589 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:25] Error in run 581: Run already exists in server. Run id(s): {9028273}
[2018-04-11 20:18:25] Started run 590 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:26] Error in run 584: Run already exists in server. Run id(s): {9028317}
[2018-04-11 20:18:26] Started run 591 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:26] Error in run 583: Run already exists in server. Run id(s): {9028305}
[2018-04-11 20:18:26] Started run 592 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:29] Error in run 585: Run already exists in server. Run id(s): {9028321}
[2018-04-11 20:18:29] Started run 593 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:29] Error in run 586: Run already exists in server. Run id(s): {9028323}
[2018-04-11 20:18:29] Started run 594 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:30] Error in run 587: Run already exists in server. Run id(s): {9028329}
[2018-04-11 20:18:30] Started run 595 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:30] Error in run 588: Run already exists in server. Run id(s): {9028322}
[2018-04-11 20:18:30] Started run 596 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:30] Error in run 590: Run already exists in server. Run id(s): {9028346}
[2018-04-11 20:18:30] Started run 597 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:30] Error in run 589: Run already exists in server. Run id(s): {9028328}
[2018-04-11 20:18:30] Started run 598 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:31] Error in run 591: Run already exists in server. Run id(s): {9028361}
[2018-04-11 20:18:31] Started run 599 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:31] Error in run 592: Run already exists in server. Run id(s): {9028364}
[2018-04-11 20:18:31] Started run 600 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:34] Error in run 593: Run already exists in server. Run id(s): {9028369}
[2018-04-11 20:18:34] Started run 601 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:34] Error in run 594: Run already exists in server. Run id(s): {9028368}
[2018-04-11 20:18:34] Started run 602 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:35] Error in run 596: Run already exists in server. Run id(s): {9028379}
[2018-04-11 20:18:35] Started run 603 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:35] Error in run 595: Run already exists in server. Run id(s): {9028372}
[2018-04-11 20:18:35] Started run 604 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:35] Error in run 597: Run already exists in server. Run id(s): {9028378}
[2018-04-11 20:18:35] Started run 605 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:35] Error in run 598: Run already exists in server. Run id(s): {9028401}
[2018-04-11 20:18:35] Started run 606 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:35] Error in run 599: Run already exists in server. Run id(s): {9028413}
[2018-04-11 20:18:35] Started run 607 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:35] Error in run 600: Run already exists in server. Run id(s): {9028415}
[2018-04-11 20:18:35] Started run 608 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:39] Error in run 601: Run already exists in server. Run id(s): {9028491}
[2018-04-11 20:18:39] Started run 609 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:39] Error in run 602: Run already exists in server. Run id(s): {9028424}
[2018-04-11 20:18:39] Started run 610 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:39] Error in run 604: Run already exists in server. Run id(s): {9028431}
[2018-04-11 20:18:39] Error in run 603: Run already exists in server. Run id(s): {9028437}
[2018-04-11 20:18:39] Started run 611 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:39] Started run 612 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:39] Error in run 605: Run already exists in server. Run id(s): {9028433}
[2018-04-11 20:18:39] Started run 613 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:40] Error in run 606: Run already exists in server. Run id(s): {9028452}
[2018-04-11 20:18:40] Started run 614 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:40] Error in run 607: Run already exists in server. Run id(s): {9028466}
[2018-04-11 20:18:40] Started run 615 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:40] Error in run 608: Run already exists in server. Run id(s): {9028467}
[2018-04-11 20:18:40] Started run 616 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:43] Error in run 609: Run already exists in server. Run id(s): {9028477}
[2018-04-11 20:18:43] Started run 617 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:44] Error in run 610: Run already exists in server. Run id(s): {9028480}
[2018-04-11 20:18:44] Started run 618 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:44] Error in run 613: Run already exists in server. Run id(s): {9028566}
[2018-04-11 20:18:44] Started run 619 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:44] Error in run 611: Run already exists in server. Run id(s): {9028481}
[2018-04-11 20:18:44] Started run 620 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:44] Error in run 612: Run already exists in server. Run id(s): {9028532}
[2018-04-11 20:18:44] Started run 621 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:44] Error in run 614: Run already exists in server. Run id(s): {9028512, 9028543}
[2018-04-11 20:18:44] Started run 622 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:45] Error in run 615: Run already exists in server. Run id(s): {9028529}
[2018-04-11 20:18:45] Started run 623 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:45] Error in run 616: Run already exists in server. Run id(s): {9028518}
[2018-04-11 20:18:45] Started run 624 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:48] Error in run 618: Run already exists in server. Run id(s): {9028517}
[2018-04-11 20:18:48] Started run 625 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:48] Error in run 617: Run already exists in server. Run id(s): {9028525}
[2018-04-11 20:18:48] Started run 626 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:49] Error in run 620: Run already exists in server. Run id(s): {9028578}
[2018-04-11 20:18:49] Started run 627 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:49] Error in run 619: Run already exists in server. Run id(s): {9028533}
[2018-04-11 20:18:49] Started run 628 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:49] Error in run 621: Run already exists in server. Run id(s): {9028573}
[2018-04-11 20:18:49] Started run 629 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:49] Error in run 622: Run already exists in server. Run id(s): {9028583}
[2018-04-11 20:18:49] Started run 630 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:49] Error in run 624: Run already exists in server. Run id(s): {9028586}
[2018-04-11 20:18:49] Started run 631 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:50] Error in run 623: Run already exists in server. Run id(s): {9028582}
[2018-04-11 20:18:50] Started run 632 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:53] Error in run 625: Run already exists in server. Run id(s): {9028736}
[2018-04-11 20:18:53] Started run 633 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:53] Error in run 626: Run already exists in server. Run id(s): {9028597}
[2018-04-11 20:18:53] Started run 634 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:54] Error in run 627: Run already exists in server. Run id(s): {9028616}
[2018-04-11 20:18:54] Started run 635 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:54] Error in run 628: Run already exists in server. Run id(s): {9028625}
[2018-04-11 20:18:54] Started run 636 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:54] Error in run 629: Run already exists in server. Run id(s): {9028632}
[2018-04-11 20:18:54] Started run 637 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:54] Error in run 630: Run already exists in server. Run id(s): {9028641}
[2018-04-11 20:18:54] Started run 638 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:54] Error in run 631: Run already exists in server. Run id(s): {9028637}
[2018-04-11 20:18:54] Started run 639 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:54] Error in run 632: Run already exists in server. Run id(s): {9028661}
[2018-04-11 20:18:54] Started run 640 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:57] Error in run 633: Run already exists in server. Run id(s): {9028649}
[2018-04-11 20:18:57] Started run 641 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:58] Error in run 634: Run already exists in server. Run id(s): {9028669}
[2018-04-11 20:18:58] Started run 642 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:58] Error in run 636: Run already exists in server. Run id(s): {9028680}
[2018-04-11 20:18:58] Started run 643 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:58] Error in run 635: Run already exists in server. Run id(s): {9028685}
[2018-04-11 20:18:58] Started run 644 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:58] Error in run 637: Run already exists in server. Run id(s): {9028688}
[2018-04-11 20:18:58] Started run 645 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:59] Error in run 638: Run already exists in server. Run id(s): {9028693}
[2018-04-11 20:18:59] Started run 646 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:59] Error in run 639: Run already exists in server. Run id(s): {9028705}
[2018-04-11 20:18:59] Started run 647 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:18:59] Error in run 640: Run already exists in server. Run id(s): {9028709}
[2018-04-11 20:18:59] Started run 648 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:02] Error in run 641: Run already exists in server. Run id(s): {9028788}
[2018-04-11 20:19:02] Started run 649 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:02] Error in run 642: Run already exists in server. Run id(s): {9028733}
[2018-04-11 20:19:02] Started run 650 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:03] Error in run 643: Run already exists in server. Run id(s): {9028738}
[2018-04-11 20:19:03] Started run 651 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:03] Error in run 644: Run already exists in server. Run id(s): {9028744}
[2018-04-11 20:19:03] Started run 652 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:03] Error in run 645: Run already exists in server. Run id(s): {9028751}
[2018-04-11 20:19:03] Started run 653 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:03] Error in run 646: Run already exists in server. Run id(s): {9028765}
[2018-04-11 20:19:03] Started run 654 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:04] Error in run 647: Run already exists in server. Run id(s): {9028767}
[2018-04-11 20:19:04] Started run 655 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:04] Error in run 648: Run already exists in server. Run id(s): {9028861}
[2018-04-11 20:19:04] Started run 656 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:07] Error in run 649: Run already exists in server. Run id(s): {9028790}
[2018-04-11 20:19:07] Started run 657 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:07] Error in run 650: Run already exists in server. Run id(s): {9028797}
[2018-04-11 20:19:07] Started run 658 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:07] Error in run 651: Run already exists in server. Run id(s): {9028807}
[2018-04-11 20:19:07] Started run 659 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:08] Error in run 652: Run already exists in server. Run id(s): {9028796}
[2018-04-11 20:19:08] Started run 660 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:08] Error in run 653: Run already exists in server. Run id(s): {9028810}
[2018-04-11 20:19:08] Started run 661 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:08] Error in run 654: Run already exists in server. Run id(s): {9028812}
[2018-04-11 20:19:08] Started run 662 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:08] Error in run 655: Run already exists in server. Run id(s): {9028831}
[2018-04-11 20:19:08] Started run 663 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:08] Error in run 656: Run already exists in server. Run id(s): {9028846}
[2018-04-11 20:19:08] Started run 664 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:12] Error in run 658: Run already exists in server. Run id(s): {9028850}
[2018-04-11 20:19:12] Error in run 657: Run already exists in server. Run id(s): {9028839}
[2018-04-11 20:19:12] Started run 665 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:12] Started run 666 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:12] Error in run 659: Run already exists in server. Run id(s): {9028864}
[2018-04-11 20:19:12] Started run 667 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:12] Error in run 660: Run already exists in server. Run id(s): {9028863}
[2018-04-11 20:19:12] Started run 668 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:13] Error in run 661: Run already exists in server. Run id(s): {9028962}
[2018-04-11 20:19:13] Started run 669 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:13] Error in run 662: Run already exists in server. Run id(s): {9028890}
[2018-04-11 20:19:13] Started run 670 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:13] Error in run 663: Run already exists in server. Run id(s): {9028902}
[2018-04-11 20:19:13] Started run 671 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:13] Error in run 664: Run already exists in server. Run id(s): {9028899}
[2018-04-11 20:19:13] Started run 672 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:16] Error in run 666: Run already exists in server. Run id(s): {9028914}
[2018-04-11 20:19:16] Started run 673 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:16] Error in run 665: Run already exists in server. Run id(s): {9028901}
[2018-04-11 20:19:16] Started run 674 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:17] Error in run 668: Run already exists in server. Run id(s): {9028923}
[2018-04-11 20:19:17] Started run 675 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:17] Error in run 667: Run already exists in server. Run id(s): {9028913}
[2018-04-11 20:19:17] Started run 676 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:17] Error in run 669: Run already exists in server. Run id(s): {9028938}
[2018-04-11 20:19:17] Started run 677 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:17] Error in run 670: Run already exists in server. Run id(s): {9028950}
[2018-04-11 20:19:17] Started run 678 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:18] Error in run 671: Run already exists in server. Run id(s): {9028953}
[2018-04-11 20:19:18] Started run 679 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:18] Error in run 672: Run already exists in server. Run id(s): {9028955}
[2018-04-11 20:19:18] Started run 680 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:21] Error in run 673: Run already exists in server. Run id(s): {9028965}
[2018-04-11 20:19:21] Started run 681 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:21] Error in run 674: Run already exists in server. Run id(s): {9028964}
[2018-04-11 20:19:21] Started run 682 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:22] Error in run 676: Run already exists in server. Run id(s): {9028978}
[2018-04-11 20:19:22] Started run 683 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:22] Error in run 675: Run already exists in server. Run id(s): {9029017}
[2018-04-11 20:19:22] Started run 684 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:22] Error in run 678: Run already exists in server. Run id(s): {9029002}
[2018-04-11 20:19:22] Started run 685 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:22] Error in run 677: Run already exists in server. Run id(s): {9028997}
[2018-04-11 20:19:22] Started run 686 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:22] Error in run 679: Run already exists in server. Run id(s): {9028989}
[2018-04-11 20:19:22] Started run 687 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:23] Error in run 680: Run already exists in server. Run id(s): {9029006}
[2018-04-11 20:19:23] Started run 688 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:26] Error in run 681: Run already exists in server. Run id(s): {9029008}
[2018-04-11 20:19:26] Started run 689 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:26] Error in run 682: Run already exists in server. Run id(s): {9029003}
[2018-04-11 20:19:26] Started run 690 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:26] Error in run 683: Run already exists in server. Run id(s): {9029028}
[2018-04-11 20:19:26] Started run 691 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:27] Error in run 685: Run already exists in server. Run id(s): {9029056}
[2018-04-11 20:19:27] Started run 692 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:27] Error in run 684: Run already exists in server. Run id(s): {9029037}
[2018-04-11 20:19:27] Started run 693 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:27] Error in run 686: Run already exists in server. Run id(s): {9029077}
[2018-04-11 20:19:27] Started run 694 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:27] Error in run 687: Run already exists in server. Run id(s): {9029053}
[2018-04-11 20:19:27] Started run 695 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:27] Error in run 688: Run already exists in server. Run id(s): {9029055}
[2018-04-11 20:19:27] Started run 696 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:30] Error in run 689: Run already exists in server. Run id(s): {9029062}
[2018-04-11 20:19:30] Started run 697 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:30] Error in run 690: Run already exists in server. Run id(s): {9029071}
[2018-04-11 20:19:30] Started run 698 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:31] Error in run 691: Run already exists in server. Run id(s): {9029079}
[2018-04-11 20:19:31] Started run 699 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:31] Error in run 692: Run already exists in server. Run id(s): {9029096}
[2018-04-11 20:19:31] Started run 700 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:32] Error in run 694: Run already exists in server. Run id(s): {9029109}
[2018-04-11 20:19:32] Started run 701 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:32] Error in run 693: Run already exists in server. Run id(s): {9029103}
[2018-04-11 20:19:32] Started run 702 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:32] Error in run 695: Run already exists in server. Run id(s): {9029100}
[2018-04-11 20:19:32] Started run 703 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:32] Error in run 696: Run already exists in server. Run id(s): {9029116}
[2018-04-11 20:19:32] Started run 704 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:35] Error in run 697: Run already exists in server. Run id(s): {9029121}
[2018-04-11 20:19:35] Started run 705 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:35] Error in run 698: Run already exists in server. Run id(s): {9029131}
[2018-04-11 20:19:35] Started run 706 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:36] Error in run 699: Run already exists in server. Run id(s): {9029129}
[2018-04-11 20:19:36] Started run 707 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:36] Error in run 701: Run already exists in server. Run id(s): {9029159}
[2018-04-11 20:19:36] Started run 708 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:36] Error in run 702: Run already exists in server. Run id(s): {9029157}
[2018-04-11 20:19:36] Started run 709 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:36] Error in run 700: Run already exists in server. Run id(s): {9029143}
[2018-04-11 20:19:36] Started run 710 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:36] Error in run 703: Run already exists in server. Run id(s): {9029158}
[2018-04-11 20:19:36] Started run 711 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:37] Error in run 704: Run already exists in server. Run id(s): {9029166}
[2018-04-11 20:19:37] Started run 712 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:40] Error in run 705: Run already exists in server. Run id(s): {9029178}
[2018-04-11 20:19:40] Started run 713 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:40] Error in run 706: Run already exists in server. Run id(s): {9029187}
[2018-04-11 20:19:40] Started run 714 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:40] Error in run 707: Run already exists in server. Run id(s): {9029185}
[2018-04-11 20:19:40] Started run 715 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:41] Error in run 709: Run already exists in server. Run id(s): {9029237}
[2018-04-11 20:19:41] Started run 716 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:41] Error in run 708: Run already exists in server. Run id(s): {9029195}
[2018-04-11 20:19:41] Started run 717 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:41] Error in run 710: Run already exists in server. Run id(s): {9029319}
[2018-04-11 20:19:41] Started run 718 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:41] Error in run 711: Run already exists in server. Run id(s): {9029293}
[2018-04-11 20:19:41] Started run 719 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:41] Error in run 712: Run already exists in server. Run id(s): {9029283}
[2018-04-11 20:19:41] Started run 720 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:44] Error in run 713: Run already exists in server. Run id(s): {9029224}
[2018-04-11 20:19:44] Started run 721 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:44] Error in run 714: Run already exists in server. Run id(s): {9029235}
[2018-04-11 20:19:44] Started run 722 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:45] Error in run 715: Run already exists in server. Run id(s): {9029229}
[2018-04-11 20:19:45] Started run 723 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:45] Error in run 716: Run already exists in server. Run id(s): {9029242}
[2018-04-11 20:19:45] Started run 724 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:46] Error in run 717: Run already exists in server. Run id(s): {9029271}
[2018-04-11 20:19:46] Started run 725 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:46] Error in run 718: Run already exists in server. Run id(s): {9029281}
[2018-04-11 20:19:46] Started run 726 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:46] Error in run 719: Run already exists in server. Run id(s): {9029282}
[2018-04-11 20:19:46] Started run 727 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:46] Error in run 720: Run already exists in server. Run id(s): {9029291}
[2018-04-11 20:19:46] Started run 728 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:49] Error in run 721: Run already exists in server. Run id(s): {9029285}
[2018-04-11 20:19:49] Started run 729 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:49] Error in run 722: Run already exists in server. Run id(s): {9029316}
[2018-04-11 20:19:49] Started run 730 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:50] Error in run 723: Run already exists in server. Run id(s): {9029338}
[2018-04-11 20:19:50] Started run 731 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:50] Error in run 725: Run already exists in server. Run id(s): {9029348}
[2018-04-11 20:19:50] Started run 732 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:50] Error in run 726: Run already exists in server. Run id(s): {9029343}
[2018-04-11 20:19:50] Started run 733 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:50] Error in run 724: Run already exists in server. Run id(s): {9029340}
[2018-04-11 20:19:50] Started run 734 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:51] Error in run 727: Run already exists in server. Run id(s): {9029349}
[2018-04-11 20:19:51] Started run 735 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:51] Error in run 728: Run already exists in server. Run id(s): {9029352}
[2018-04-11 20:19:51] Started run 736 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:54] Error in run 730: Run already exists in server. Run id(s): {9029375}
[2018-04-11 20:19:54] Started run 737 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:54] Error in run 729: Run already exists in server. Run id(s): {9029398}
[2018-04-11 20:19:54] Started run 738 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:54] Error in run 731: Run already exists in server. Run id(s): {9029394}
[2018-04-11 20:19:54] Started run 739 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:55] Error in run 734: Run already exists in server. Run id(s): {9029405}
[2018-04-11 20:19:55] Started run 740 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:55] Error in run 732: Run already exists in server. Run id(s): {9029393}
[2018-04-11 20:19:55] Started run 741 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:55] Error in run 733: Run already exists in server. Run id(s): {9029412}
[2018-04-11 20:19:55] Started run 742 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:55] Error in run 735: Run already exists in server. Run id(s): {9029409}
[2018-04-11 20:19:55] Started run 743 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:56] Error in run 736: Run already exists in server. Run id(s): {9029413}
[2018-04-11 20:19:56] Started run 744 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:58] Error in run 738: Run already exists in server. Run id(s): {9029478}
[2018-04-11 20:19:58] Started run 745 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:58] Error in run 737: Run already exists in server. Run id(s): {9029429}
[2018-04-11 20:19:58] Started run 746 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:19:59] Error in run 739: Run already exists in server. Run id(s): {9029515}
[2018-04-11 20:19:59] Started run 747 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:00] Error in run 740: Run already exists in server. Run id(s): {9029455}
[2018-04-11 20:20:00] Started run 748 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:00] Error in run 741: Run already exists in server. Run id(s): {9029461}
[2018-04-11 20:20:00] Started run 749 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:00] Error in run 742: Run already exists in server. Run id(s): {9029562}
[2018-04-11 20:20:00] Started run 750 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:00] Error in run 743: Run already exists in server. Run id(s): {9029464}
[2018-04-11 20:20:00] Started run 751 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:00] Error in run 744: Run already exists in server. Run id(s): {9029542}
[2018-04-11 20:20:00] Started run 752 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:03] Error in run 745: Run already exists in server. Run id(s): {9029475}
[2018-04-11 20:20:03] Started run 753 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:03] Error in run 746: Run already exists in server. Run id(s): {9029507}
[2018-04-11 20:20:03] Started run 754 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:04] Error in run 747: Run already exists in server. Run id(s): {9029511}
[2018-04-11 20:20:04] Started run 755 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:04] Error in run 748: Run already exists in server. Run id(s): {9029506}
[2018-04-11 20:20:04] Started run 756 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:04] Error in run 749: Run already exists in server. Run id(s): {9029523}
[2018-04-11 20:20:04] Started run 757 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:05] Error in run 750: Run already exists in server. Run id(s): {9029550}
[2018-04-11 20:20:05] Started run 758 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:05] Error in run 751: Run already exists in server. Run id(s): {9029559}
[2018-04-11 20:20:05] Started run 759 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:05] Error in run 752: Run already exists in server. Run id(s): {9029561}
[2018-04-11 20:20:05] Started run 760 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:08] Error in run 753: Run already exists in server. Run id(s): {9029565}
[2018-04-11 20:20:08] Started run 761 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:08] Error in run 754: Run already exists in server. Run id(s): {9029567}
[2018-04-11 20:20:08] Started run 762 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:09] Error in run 755: Run already exists in server. Run id(s): {9029572}
[2018-04-11 20:20:09] Started run 763 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:09] Error in run 756: Run already exists in server. Run id(s): {9029589}
[2018-04-11 20:20:09] Started run 764 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:09] Error in run 757: Run already exists in server. Run id(s): {9029602}
[2018-04-11 20:20:09] Started run 765 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:09] Error in run 758: Run already exists in server. Run id(s): {9029605}
[2018-04-11 20:20:09] Started run 766 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:09] Error in run 759: Run already exists in server. Run id(s): {9029608}
[2018-04-11 20:20:09] Started run 767 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:10] Error in run 760: Run already exists in server. Run id(s): {9029604}
[2018-04-11 20:20:10] Started run 768 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:13] Error in run 761: Run already exists in server. Run id(s): {9029620}
[2018-04-11 20:20:13] Started run 769 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:13] Error in run 762: Run already exists in server. Run id(s): {9029613}
[2018-04-11 20:20:13] Started run 770 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:13] Error in run 763: Run already exists in server. Run id(s): {9029616}
[2018-04-11 20:20:13] Started run 771 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:14] Error in run 765: Run already exists in server. Run id(s): {9029656}
[2018-04-11 20:20:14] Started run 772 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:14] Error in run 764: Run already exists in server. Run id(s): {9029644}
[2018-04-11 20:20:14] Started run 773 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:14] Error in run 766: Run already exists in server. Run id(s): {9029749}
[2018-04-11 20:20:14] Started run 774 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:14] Error in run 767: Run already exists in server. Run id(s): {9029740}
[2018-04-11 20:20:14] Started run 775 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:15] Error in run 768: Run already exists in server. Run id(s): {9029663}
[2018-04-11 20:20:15] Started run 776 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:17] Error in run 769: Run already exists in server. Run id(s): {9029659}
[2018-04-11 20:20:17] Started run 777 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:18] Error in run 770: Run already exists in server. Run id(s): {9029686}
[2018-04-11 20:20:18] Started run 778 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:18] Error in run 771: Run already exists in server. Run id(s): {9029677}
[2018-04-11 20:20:18] Started run 779 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:18] Error in run 772: Run already exists in server. Run id(s): {9029757}
[2018-04-11 20:20:18] Started run 780 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:18] Error in run 773: Run already exists in server. Run id(s): {9029705}
[2018-04-11 20:20:18] Started run 781 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:19] Error in run 775: Run already exists in server. Run id(s): {9029756}
[2018-04-11 20:20:19] Started run 782 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:19] Error in run 774: Run already exists in server. Run id(s): {9029714}
[2018-04-11 20:20:19] Started run 783 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:19] Error in run 776: Run already exists in server. Run id(s): {9029720}
[2018-04-11 20:20:19] Started run 784 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:22] Error in run 777: Run already exists in server. Run id(s): {9029731}
[2018-04-11 20:20:22] Started run 785 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:22] Error in run 778: Run already exists in server. Run id(s): {9029738}
[2018-04-11 20:20:22] Started run 786 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:23] Error in run 779: Run already exists in server. Run id(s): {9029759}
[2018-04-11 20:20:23] Started run 787 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:23] Error in run 781: Run already exists in server. Run id(s): {9029784}
[2018-04-11 20:20:23] Started run 788 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:23] Error in run 780: Run already exists in server. Run id(s): {9029771}
[2018-04-11 20:20:23] Started run 789 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:24] Error in run 782: Run already exists in server. Run id(s): {9029818}
[2018-04-11 20:20:24] Started run 790 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:24] Error in run 783: Run already exists in server. Run id(s): {9029836}
[2018-04-11 20:20:24] Started run 791 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:24] Error in run 784: Run already exists in server. Run id(s): {9029803}
[2018-04-11 20:20:24] Started run 792 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:27] Error in run 785: Run already exists in server. Run id(s): {9029806}
[2018-04-11 20:20:27] Started run 793 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:27] Error in run 786: Run already exists in server. Run id(s): {9029812}
[2018-04-11 20:20:27] Started run 794 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:28] Error in run 787: Run already exists in server. Run id(s): {8962571}
[2018-04-11 20:20:28] Started run 795 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:28] Error in run 788: Run already exists in server. Run id(s): {9029822}
[2018-04-11 20:20:28] Started run 796 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:28] Error in run 789: Run already exists in server. Run id(s): {9029825}
[2018-04-11 20:20:28] Started run 797 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:28] Error in run 790: Run already exists in server. Run id(s): {9029829}
[2018-04-11 20:20:28] Started run 798 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:29] Error in run 791: Run already exists in server. Run id(s): {9029858}
[2018-04-11 20:20:29] Error in run 792: Run already exists in server. Run id(s): {9029856}
[2018-04-11 20:20:29] Started run 799 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:29] Started run 800 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:31] Error in run 793: Run already exists in server. Run id(s): {9029865}
[2018-04-11 20:20:31] Started run 801 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:32] Error in run 794: Run already exists in server. Run id(s): {9029863}
[2018-04-11 20:20:32] Started run 802 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:32] Error in run 795: Run already exists in server. Run id(s): {9029870}
[2018-04-11 20:20:32] Started run 803 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:32] Error in run 797: Run already exists in server. Run id(s): {9029874}
[2018-04-11 20:20:32] Started run 804 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:32] Error in run 796: Run already exists in server. Run id(s): {9029871}
[2018-04-11 20:20:32] Started run 805 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:33] Error in run 798: Run already exists in server. Run id(s): {9029878}
[2018-04-11 20:20:33] Started run 806 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:33] Error in run 800: Run already exists in server. Run id(s): {9029904}
[2018-04-11 20:20:33] Started run 807 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:33] Error in run 799: Run already exists in server. Run id(s): {9029905}
[2018-04-11 20:20:33] Started run 808 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:36] Error in run 801: Run already exists in server. Run id(s): {9029908}
[2018-04-11 20:20:36] Started run 809 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:36] Error in run 802: Run already exists in server. Run id(s): {9029912}
[2018-04-11 20:20:36] Started run 810 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:37] Error in run 803: Run already exists in server. Run id(s): {9029919}
[2018-04-11 20:20:37] Started run 811 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:37] Error in run 805: Run already exists in server. Run id(s): {9029927}
[2018-04-11 20:20:37] Started run 812 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:37] Error in run 804: Run already exists in server. Run id(s): {9029921}
[2018-04-11 20:20:37] Started run 813 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:38] Error in run 806: Run already exists in server. Run id(s): {8962566}
[2018-04-11 20:20:38] Started run 814 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:38] Error in run 808: Run already exists in server. Run id(s): {9030029}
[2018-04-11 20:20:38] Error in run 807: Run already exists in server. Run id(s): {9029948}
[2018-04-11 20:20:38] Started run 815 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:38] Started run 816 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:41] Error in run 809: Run already exists in server. Run id(s): {9029959}
[2018-04-11 20:20:41] Started run 817 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:41] Error in run 810: Run already exists in server. Run id(s): {9029961}
[2018-04-11 20:20:41] Started run 818 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:42] Error in run 812: Run already exists in server. Run id(s): {9029970}
[2018-04-11 20:20:42] Started run 819 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:42] Error in run 813: Run already exists in server. Run id(s): {9029977}
[2018-04-11 20:20:42] Started run 820 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:42] Error in run 811: Run already exists in server. Run id(s): {9029962}
[2018-04-11 20:20:42] Started run 821 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:43] Error in run 814: Run already exists in server. Run id(s): {9030030}
[2018-04-11 20:20:43] Started run 822 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:43] Error in run 815: Run already exists in server. Run id(s): {9029990}
[2018-04-11 20:20:43] Started run 823 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:43] Error in run 816: Run already exists in server. Run id(s): {9030004}
[2018-04-11 20:20:43] Started run 824 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:46] Error in run 817: Run already exists in server. Run id(s): {9030012}
[2018-04-11 20:20:46] Started run 825 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:46] Error in run 818: Run already exists in server. Run id(s): {9030001}
[2018-04-11 20:20:46] Started run 826 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:47] Error in run 819: Run already exists in server. Run id(s): {9030020}
[2018-04-11 20:20:47] Started run 827 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:47] Error in run 820: Run already exists in server. Run id(s): {9030024}
[2018-04-11 20:20:47] Started run 828 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:47] Error in run 821: Run already exists in server. Run id(s): {9030036}
[2018-04-11 20:20:47] Started run 829 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:47] Error in run 822: Run already exists in server. Run id(s): {9030049}
[2018-04-11 20:20:47] Started run 830 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:47] Error in run 823: Run already exists in server. Run id(s): {9030047}
[2018-04-11 20:20:47] Started run 831 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:48] Error in run 824: Run already exists in server. Run id(s): {9030058}
[2018-04-11 20:20:48] Started run 832 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:50] Error in run 825: Run already exists in server. Run id(s): {9030076}
[2018-04-11 20:20:50] Started run 833 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:50] Error in run 826: Run already exists in server. Run id(s): {9030063}
[2018-04-11 20:20:50] Started run 834 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:51] Error in run 827: Run already exists in server. Run id(s): {9030065}
[2018-04-11 20:20:51] Started run 835 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:51] Error in run 829: Run already exists in server. Run id(s): {9030087}
[2018-04-11 20:20:51] Error in run 828: Run already exists in server. Run id(s): {9030073}
[2018-04-11 20:20:51] Started run 836 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:51] Started run 837 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:52] Error in run 830: Run already exists in server. Run id(s): {9030097}
[2018-04-11 20:20:52] Started run 838 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:52] Error in run 831: Run already exists in server. Run id(s): {9030098}
[2018-04-11 20:20:52] Started run 839 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:52] Error in run 832: Run already exists in server. Run id(s): {9030115}
[2018-04-11 20:20:52] Started run 840 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:55] Error in run 833: Run already exists in server. Run id(s): {9030122}
[2018-04-11 20:20:55] Started run 841 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:55] Error in run 834: Run already exists in server. Run id(s): {9030125}
[2018-04-11 20:20:55] Started run 842 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:56] Error in run 835: Run already exists in server. Run id(s): {9030130}
[2018-04-11 20:20:56] Started run 843 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:56] Error in run 837: Run already exists in server. Run id(s): {9030152}
[2018-04-11 20:20:56] Error in run 836: Run already exists in server. Run id(s): {9030139}
[2018-04-11 20:20:56] Started run 844 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:56] Started run 845 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:57] Error in run 838: Run already exists in server. Run id(s): {9030151}
[2018-04-11 20:20:57] Started run 846 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:57] Error in run 839: Run already exists in server. Run id(s): {9030225}
[2018-04-11 20:20:57] Started run 847 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:20:57] Error in run 840: Run already exists in server. Run id(s): {9030168}
[2018-04-11 20:20:57] Started run 848 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:00] Error in run 841: Run already exists in server. Run id(s): {9030171}
[2018-04-11 20:21:00] Started run 849 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:00] Error in run 842: Run already exists in server. Run id(s): {9030173}
[2018-04-11 20:21:00] Started run 850 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:01] Error in run 844: Run already exists in server. Run id(s): {9030191}
[2018-04-11 20:21:01] Started run 851 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:01] Error in run 843: Run already exists in server. Run id(s): {9030178}
[2018-04-11 20:21:01] Started run 852 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:01] Error in run 845: Run already exists in server. Run id(s): {9030202}
[2018-04-11 20:21:01] Started run 853 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:01] Error in run 846: Run already exists in server. Run id(s): {9030286}
[2018-04-11 20:21:01] Started run 854 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:02] Error in run 847: Run already exists in server. Run id(s): {9030224}
[2018-04-11 20:21:02] Started run 855 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:02] Error in run 848: Run already exists in server. Run id(s): {9030222}
[2018-04-11 20:21:02] Started run 856 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:04] Error in run 849: Run already exists in server. Run id(s): {9030229}
[2018-04-11 20:21:04] Started run 857 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:05] Error in run 850: Run already exists in server. Run id(s): {9030240}
[2018-04-11 20:21:05] Started run 858 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:05] Error in run 852: Run already exists in server. Run id(s): {9030256}
[2018-04-11 20:21:05] Started run 859 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:06] Error in run 851: Run already exists in server. Run id(s): {9030245}
[2018-04-11 20:21:06] Started run 860 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:06] Error in run 853: Run already exists in server. Run id(s): {9030270}
[2018-04-11 20:21:06] Started run 861 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:06] Error in run 854: Run already exists in server. Run id(s): {8962567}
[2018-04-11 20:21:06] Started run 862 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:06] Error in run 855: Run already exists in server. Run id(s): {8962565}
[2018-04-11 20:21:06] Started run 863 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:06] Error in run 856: Run already exists in server. Run id(s): {8962564}
[2018-04-11 20:21:06] Started run 864 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:09] Error in run 857: Run already exists in server. Run id(s): {9030284}
[2018-04-11 20:21:09] Started run 865 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:09] Error in run 858: Run already exists in server. Run id(s): {9030290}
[2018-04-11 20:21:09] Started run 866 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:10] Error in run 861: Run already exists in server. Run id(s): {9030300}
[2018-04-11 20:21:10] Started run 867 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:10] Error in run 859: Run already exists in server. Run id(s): {9030293}
[2018-04-11 20:21:10] Started run 868 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:10] Error in run 860: Run already exists in server. Run id(s): {9030296}
[2018-04-11 20:21:10] Started run 869 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:11] Error in run 862: Run already exists in server. Run id(s): {9030364}
[2018-04-11 20:21:11] Started run 870 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:11] Error in run 863: Run already exists in server. Run id(s): {9030316}
[2018-04-11 20:21:11] Started run 871 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:11] Error in run 864: Run already exists in server. Run id(s): {9030369}
[2018-04-11 20:21:11] Started run 872 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:14] Error in run 865: Run already exists in server. Run id(s): {9030327}
[2018-04-11 20:21:14] Started run 873 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:14] Error in run 866: Run already exists in server. Run id(s): {9030325}
[2018-04-11 20:21:14] Started run 874 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:15] Error in run 867: Run already exists in server. Run id(s): {9030332}
[2018-04-11 20:21:15] Started run 875 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:15] Error in run 869: Run already exists in server. Run id(s): {9030339}
[2018-04-11 20:21:15] Started run 876 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:15] Error in run 868: Run already exists in server. Run id(s): {9030340}
[2018-04-11 20:21:15] Started run 877 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:16] Error in run 871: Run already exists in server. Run id(s): {9030360}
[2018-04-11 20:21:16] Started run 878 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:16] Error in run 870: Run already exists in server. Run id(s): {8962573}
[2018-04-11 20:21:16] Started run 879 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:16] Error in run 872: Run already exists in server. Run id(s): {9030372}
[2018-04-11 20:21:16] Started run 880 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:19] Error in run 873: Run already exists in server. Run id(s): {9030381}
[2018-04-11 20:21:19] Started run 881 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:19] Error in run 874: Run already exists in server. Run id(s): {9030380}
[2018-04-11 20:21:19] Started run 882 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:20] Error in run 876: Run already exists in server. Run id(s): {9030393}
[2018-04-11 20:21:20] Started run 883 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:20] Error in run 875: Run already exists in server. Run id(s): {9030388}
[2018-04-11 20:21:20] Started run 884 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:20] Error in run 877: Run already exists in server. Run id(s): {9030411}
[2018-04-11 20:21:20] Started run 885 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:20] Error in run 878: Run already exists in server. Run id(s): {9030415}
[2018-04-11 20:21:20] Started run 886 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:20] Error in run 879: Run already exists in server. Run id(s): {9030420}
[2018-04-11 20:21:20] Started run 887 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:21] Error in run 880: Run already exists in server. Run id(s): {9030419}
[2018-04-11 20:21:21] Started run 888 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:23] Error in run 881: Run already exists in server. Run id(s): {9030468}
[2018-04-11 20:21:23] Started run 889 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:24] Error in run 882: Run already exists in server. Run id(s): {9030434}
[2018-04-11 20:21:24] Started run 890 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:24] Error in run 884: Run already exists in server. Run id(s): {9030444}
[2018-04-11 20:21:24] Started run 891 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:24] Error in run 883: Run already exists in server. Run id(s): {9030454}
[2018-04-11 20:21:24] Started run 892 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:24] Error in run 885: Run already exists in server. Run id(s): {9030460}
[2018-04-11 20:21:24] Started run 893 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:25] Error in run 887: Run already exists in server. Run id(s): {9030467}
[2018-04-11 20:21:25] Started run 894 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:25] Error in run 886: Run already exists in server. Run id(s): {9030461}
[2018-04-11 20:21:25] Started run 895 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:25] Error in run 888: Run already exists in server. Run id(s): {8962569}
[2018-04-11 20:21:25] Started run 896 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:28] Error in run 889: Run already exists in server. Run id(s): {9030479}
[2018-04-11 20:21:28] Started run 897 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:28] Error in run 890: Run already exists in server. Run id(s): {9030484}
[2018-04-11 20:21:28] Started run 898 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:29] Error in run 891: Run already exists in server. Run id(s): {9030487}
[2018-04-11 20:21:29] Started run 899 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:29] Error in run 892: Run already exists in server. Run id(s): {9030507}
[2018-04-11 20:21:29] Started run 900 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:29] Error in run 893: Run already exists in server. Run id(s): {9030512}
[2018-04-11 20:21:29] Started run 901 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:30] Error in run 894: Run already exists in server. Run id(s): {9030519}
[2018-04-11 20:21:30] Started run 902 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:30] Error in run 895: Run already exists in server. Run id(s): {9030514}
[2018-04-11 20:21:30] Started run 903 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:30] Error in run 896: Run already exists in server. Run id(s): {9030521}
[2018-04-11 20:21:30] Started run 904 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:33] Error in run 897: Run already exists in server. Run id(s): {8962570}
[2018-04-11 20:21:33] Started run 905 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:33] Error in run 898: Run already exists in server. Run id(s): {9030534}
[2018-04-11 20:21:33] Started run 906 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:34] Error in run 899: Run already exists in server. Run id(s): {9030545}
[2018-04-11 20:21:34] Started run 907 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:34] Error in run 900: Run already exists in server. Run id(s): {8962577}
[2018-04-11 20:21:34] Started run 908 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:34] Error in run 902: Run already exists in server. Run id(s): {9030554}
[2018-04-11 20:21:34] Started run 909 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:34] Error in run 901: Run already exists in server. Run id(s): {8962572}
[2018-04-11 20:21:34] Started run 910 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:35] Error in run 903: Run already exists in server. Run id(s): {9030557}
[2018-04-11 20:21:35] Started run 911 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:35] Error in run 904: Run already exists in server. Run id(s): {8962568}
[2018-04-11 20:21:35] Started run 912 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:37] Error in run 905: Run already exists in server. Run id(s): {9030565}
[2018-04-11 20:21:37] Started run 913 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:38] Error in run 906: Run already exists in server. Run id(s): {9030567}
[2018-04-11 20:21:38] Started run 914 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:38] Error in run 907: Run already exists in server. Run id(s): {9030642}
[2018-04-11 20:21:38] Started run 915 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:39] Error in run 908: Run already exists in server. Run id(s): {8962574}
[2018-04-11 20:21:39] Started run 916 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:39] Error in run 909: Run already exists in server. Run id(s): {9030589}
[2018-04-11 20:21:39] Started run 917 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:39] Error in run 910: Run already exists in server. Run id(s): {8962575}
[2018-04-11 20:21:39] Started run 918 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:39] Error in run 911: Run already exists in server. Run id(s): {9030602}
[2018-04-11 20:21:39] Started run 919 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:39] Error in run 912: Run already exists in server. Run id(s): {9030603}
[2018-04-11 20:21:39] Started run 920 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:42] Error in run 913: Run already exists in server. Run id(s): {9030597}
[2018-04-11 20:21:42] Started run 921 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:42] Error in run 914: Run already exists in server. Run id(s): {9030605}
[2018-04-11 20:21:42] Started run 922 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:43] Error in run 915: Run already exists in server. Run id(s): {9030607}
[2018-04-11 20:21:43] Started run 923 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:43] Error in run 916: Run already exists in server. Run id(s): {9030633}
[2018-04-11 20:21:43] Started run 924 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:44] Error in run 917: Run already exists in server. Run id(s): {9030651}
[2018-04-11 20:21:44] Started run 925 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:44] Error in run 918: Run already exists in server. Run id(s): {9030656}
[2018-04-11 20:21:44] Started run 926 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:44] Error in run 919: Run already exists in server. Run id(s): {9030652}
[2018-04-11 20:21:44] Started run 927 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:44] Error in run 920: Run already exists in server. Run id(s): {9030657}
[2018-04-11 20:21:44] Started run 928 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:47] Error in run 921: Run already exists in server. Run id(s): {9030654}
[2018-04-11 20:21:47] Started run 929 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:47] Error in run 922: Run already exists in server. Run id(s): {8962576}
[2018-04-11 20:21:47] Started run 930 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:48] Error in run 923: Run already exists in server. Run id(s): {9030662}
[2018-04-11 20:21:48] Started run 931 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:48] Error in run 924: Run already exists in server. Run id(s): {9030719}
[2018-04-11 20:21:48] Started run 932 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:48] Error in run 925: Run already exists in server. Run id(s): {9030715}
[2018-04-11 20:21:48] Started run 933 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:49] Error in run 927: Run already exists in server. Run id(s): {8962583}
[2018-04-11 20:21:49] Started run 934 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:49] Error in run 926: Run already exists in server. Run id(s): {8962579}
[2018-04-11 20:21:49] Started run 935 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:49] Error in run 928: Run already exists in server. Run id(s): {9030695}
[2018-04-11 20:21:49] Started run 936 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:52] Error in run 930: Run already exists in server. Run id(s): {9030698}
[2018-04-11 20:21:52] Started run 937 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:52] Error in run 929: Run already exists in server. Run id(s): {8962581}
[2018-04-11 20:21:52] Started run 938 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:52] Error in run 931: Run already exists in server. Run id(s): {8962582}
[2018-04-11 20:21:52] Started run 939 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:53] Error in run 932: Run already exists in server. Run id(s): {9030699}
[2018-04-11 20:21:53] Started run 940 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:53] Error in run 933: Run already exists in server. Run id(s): {9030703}
[2018-04-11 20:21:53] Started run 941 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:53] Error in run 935: Run already exists in server. Run id(s): {9030707}
[2018-04-11 20:21:53] Started run 942 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:53] Error in run 934: Run already exists in server. Run id(s): {9030705}
[2018-04-11 20:21:53] Started run 943 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:54] Error in run 936: Run already exists in server. Run id(s): {9030736}
[2018-04-11 20:21:54] Started run 944 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:56] Error in run 937: Run already exists in server. Run id(s): {9030747}
[2018-04-11 20:21:56] Started run 945 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:56] Error in run 938: Run already exists in server. Run id(s): {9030748}
[2018-04-11 20:21:56] Started run 946 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:57] Error in run 939: Run already exists in server. Run id(s): {9030762}
[2018-04-11 20:21:57] Started run 947 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:57] Error in run 940: Run already exists in server. Run id(s): {8962578}
[2018-04-11 20:21:57] Started run 948 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:58] Error in run 941: Run already exists in server. Run id(s): {9030757}
[2018-04-11 20:21:58] Started run 949 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:58] Error in run 943: Run already exists in server. Run id(s): {9030769}
[2018-04-11 20:21:58] Started run 950 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:58] Error in run 942: Run already exists in server. Run id(s): {9030759}
[2018-04-11 20:21:58] Started run 951 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:21:59] Error in run 944: Run already exists in server. Run id(s): {9030775}
[2018-04-11 20:21:59] Started run 952 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:01] Error in run 946: Run already exists in server. Run id(s): {8962588}
[2018-04-11 20:22:01] Started run 953 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:01] Error in run 945: Run already exists in server. Run id(s): {9030846}
[2018-04-11 20:22:01] Started run 954 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:02] Error in run 947: Run already exists in server. Run id(s): {9030803}
[2018-04-11 20:22:02] Started run 955 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:02] Error in run 948: Run already exists in server. Run id(s): {9030808}
[2018-04-11 20:22:02] Started run 956 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:02] Error in run 949: Run already exists in server. Run id(s): {9030806}
[2018-04-11 20:22:02] Started run 957 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:03] Error in run 950: Run already exists in server. Run id(s): {8962589}
[2018-04-11 20:22:03] Started run 958 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:03] Error in run 951: Run already exists in server. Run id(s): {9030810}
[2018-04-11 20:22:03] Started run 959 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:03] Error in run 952: Run already exists in server. Run id(s): {8962596}
[2018-04-11 20:22:03] Started run 960 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:06] Error in run 953: Run already exists in server. Run id(s): {9030812}
[2018-04-11 20:22:06] Started run 961 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:06] Error in run 954: Run already exists in server. Run id(s): {8962591}
[2018-04-11 20:22:06] Started run 962 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:06] Error in run 955: Run already exists in server. Run id(s): {9030822}
[2018-04-11 20:22:06] Started run 963 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:07] Error in run 957: Run already exists in server. Run id(s): {9030851}
[2018-04-11 20:22:07] Started run 964 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:07] Error in run 956: Run already exists in server. Run id(s): {9030825}
[2018-04-11 20:22:07] Started run 965 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:08] Error in run 958: Run already exists in server. Run id(s): {8962586}
[2018-04-11 20:22:08] Error in run 959: Run already exists in server. Run id(s): {8962585}
[2018-04-11 20:22:08] Started run 966 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:08] Started run 967 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:08] Error in run 960: Run already exists in server. Run id(s): {8962580}
[2018-04-11 20:22:08] Started run 968 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:10] Error in run 961: Run already exists in server. Run id(s): {8962584}
[2018-04-11 20:22:10] Started run 969 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:10] Error in run 962: Run already exists in server. Run id(s): {9030855}
[2018-04-11 20:22:10] Started run 970 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:11] Error in run 963: Run already exists in server. Run id(s): {8962595}
[2018-04-11 20:22:11] Started run 971 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:12] Error in run 965: Run already exists in server. Run id(s): {9030861}
[2018-04-11 20:22:12] Started run 972 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:12] Error in run 964: Run already exists in server. Run id(s): {9030862}
[2018-04-11 20:22:12] Started run 973 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:12] Error in run 966: Run already exists in server. Run id(s): {8962590}
[2018-04-11 20:22:12] Started run 974 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:12] Error in run 968: Run already exists in server. Run id(s): {8962599}
[2018-04-11 20:22:12] Started run 975 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:13] Error in run 967: Run already exists in server. Run id(s): {8962593}
[2018-04-11 20:22:13] Started run 976 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:15] Error in run 970: Run already exists in server. Run id(s): {8962598}
[2018-04-11 20:22:15] Started run 977 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:15] Error in run 969: Run already exists in server. Run id(s): {8962587}
[2018-04-11 20:22:15] Started run 978 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:16] Error in run 971: Run already exists in server. Run id(s): {9030894}
[2018-04-11 20:22:16] Started run 979 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:16] Error in run 972: Run already exists in server. Run id(s): {9030885}
[2018-04-11 20:22:16] Started run 980 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:17] Error in run 973: Run already exists in server. Run id(s): {8962592}
[2018-04-11 20:22:17] Started run 981 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:17] Error in run 974: Run already exists in server. Run id(s): {8962597}
[2018-04-11 20:22:17] Started run 982 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:17] Error in run 976: Run already exists in server. Run id(s): {9030899}
[2018-04-11 20:22:17] Started run 983 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:17] Error in run 975: Run already exists in server. Run id(s): {8962594}
[2018-04-11 20:22:17] Started run 984 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:20] Error in run 977: Run already exists in server. Run id(s): {9030897}
[2018-04-11 20:22:20] Started run 985 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:20] Error in run 978: Run already exists in server. Run id(s): {8962600}
[2018-04-11 20:22:20] Started run 986 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:21] Error in run 979: Run already exists in server. Run id(s): {9030901}
[2018-04-11 20:22:21] Started run 987 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:21] Error in run 980: Run already exists in server. Run id(s): {9030906}
[2018-04-11 20:22:21] Started run 988 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:21] Error in run 981: Run already exists in server. Run id(s): {9030913}
[2018-04-11 20:22:21] Started run 989 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:22] Error in run 982: Run already exists in server. Run id(s): {8962602}
[2018-04-11 20:22:22] Started run 990 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:22] Error in run 983: Run already exists in server. Run id(s): {8962604}
[2018-04-11 20:22:22] Started run 991 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:22] Error in run 984: Run already exists in server. Run id(s): {9030934}
[2018-04-11 20:22:22] Started run 992 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:24] Error in run 986: Run already exists in server. Run id(s): {9030944}
[2018-04-11 20:22:24] Error in run 985: Run already exists in server. Run id(s): {9030937}
[2018-04-11 20:22:24] Started run 993 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:24] Started run 994 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:25] Error in run 987: Run already exists in server. Run id(s): {9030970}
[2018-04-11 20:22:25] Started run 995 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:26] Error in run 988: Run already exists in server. Run id(s): {8962603}
[2018-04-11 20:22:26] Started run 996 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:26] Error in run 989: Run already exists in server. Run id(s): {9030951}
[2018-04-11 20:22:26] Started run 997 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:26] Error in run 990: Run already exists in server. Run id(s): {9030958}
[2018-04-11 20:22:26] Started run 998 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:27] Error in run 992: Run already exists in server. Run id(s): {9030963}
[2018-04-11 20:22:27] Started run 999 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:27] Error in run 991: Run already exists in server. Run id(s): {9030977}
[2018-04-11 20:22:27] Started run 1000 on task 3560, dataset 'analcatdata_dmft'.
[2018-04-11 20:22:29] Error in run 994: Run already exists in server. Run id(s): {8962601}
[2018-04-11 20:22:29] Error in run 993: Run already exists in server. Run id(s): {9030987}
[2018-04-11 20:22:30] Error in run 995: Run already exists in server. Run id(s): {9030991}
[2018-04-11 20:22:31] Error in run 996: Run already exists in server. Run id(s): {9030995}
[2018-04-11 20:22:31] Error in run 997: Run already exists in server. Run id(s): {9030998}
[2018-04-11 20:22:31] Error in run 998: Run already exists in server. Run id(s): {9031011}
[2018-04-11 20:22:31] Error in run 999: Run already exists in server. Run id(s): {9031013}
[2018-04-11 20:22:32] Error in run 1000: Run already exists in server. Run id(s): {9031088}
