declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/random_forest2/job-1/task-00000/certs"
declare -x AZ_BATCH_JOB_ID="random_forest2"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/random_forest2/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest2/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_1-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/random_forest2/job-1/task-00000"
declare -x AZ_BATCH_TASK_ID="task-00000"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest2/job-1/task-00000/wd"
declare -x HOME="/mnt/batch/tasks/workitems/random_forest2/job-1/task-00000/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/random_forest2/job-1/task-00000/wd"
declare -x PWD="/mnt/batch/tasks/workitems/random_forest2/job-1/task-00000/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 21:41:44] Results will not be logged locally.
[2018-04-11 21:41:44] Retrieving tasks...
[2018-04-11 21:41:44] Tasks will be retrieved based on provided task ids.
[2018-04-11 21:41:44] The following tasks were retrieved: [146197].
[2018-04-11 21:41:52] Downloaded task 146197.
[2018-04-11 21:41:52] Prepared pipelines.
[2018-04-11 21:41:52] Started run 1 on task 146197, dataset 'dna'.
[2018-04-11 21:41:52] Started run 2 on task 146197, dataset 'dna'.
[2018-04-11 21:41:52] Started run 3 on task 146197, dataset 'dna'.
[2018-04-11 21:41:52] Started run 4 on task 146197, dataset 'dna'.
[2018-04-11 21:41:52] Started run 5 on task 146197, dataset 'dna'.
[2018-04-11 21:41:52] Started run 6 on task 146197, dataset 'dna'.
[2018-04-11 21:41:52] Started run 7 on task 146197, dataset 'dna'.
[2018-04-11 21:41:52] Started run 8 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Error in run 1: Run already exists in server. Run id(s): {9007485}
[2018-04-11 21:41:57] Error in run 2: Run already exists in server. Run id(s): {9007727}
[2018-04-11 21:41:57] Started run 9 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Error in run 3: Run already exists in server. Run id(s): {9007529}
[2018-04-11 21:41:57] Started run 10 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Error in run 4: Run already exists in server. Run id(s): {9007651}
[2018-04-11 21:41:57] Started run 11 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Started run 12 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Error in run 5: Run already exists in server. Run id(s): {9007666}
[2018-04-11 21:41:57] Started run 13 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Error in run 6: Run already exists in server. Run id(s): {9007521}
[2018-04-11 21:41:57] Started run 14 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Error in run 8: Run already exists in server. Run id(s): {9007624}
[2018-04-11 21:41:57] Started run 15 on task 146197, dataset 'dna'.
[2018-04-11 21:41:57] Error in run 7: Run already exists in server. Run id(s): {9007391}
[2018-04-11 21:41:57] Started run 16 on task 146197, dataset 'dna'.
[2018-04-11 21:42:01] Error in run 9: Run already exists in server. Run id(s): {9007669}
[2018-04-11 21:42:01] Error in run 10: Run already exists in server. Run id(s): {9007679}
[2018-04-11 21:42:01] Error in run 11: Run already exists in server. Run id(s): {9007689}
[2018-04-11 21:42:01] Started run 17 on task 146197, dataset 'dna'.
[2018-04-11 21:42:01] Error in run 12: Run already exists in server. Run id(s): {9007979}
[2018-04-11 21:42:01] Started run 18 on task 146197, dataset 'dna'.
[2018-04-11 21:42:01] Error in run 13: Run already exists in server. Run id(s): {9007751}
[2018-04-11 21:42:01] Started run 19 on task 146197, dataset 'dna'.
[2018-04-11 21:42:01] Started run 20 on task 146197, dataset 'dna'.
[2018-04-11 21:42:01] Started run 21 on task 146197, dataset 'dna'.
[2018-04-11 21:42:02] Error in run 14: Run already exists in server. Run id(s): {9007977}
[2018-04-11 21:42:02] Started run 22 on task 146197, dataset 'dna'.
[2018-04-11 21:42:02] Error in run 15: Run already exists in server. Run id(s): {9007763}
[2018-04-11 21:42:02] Started run 23 on task 146197, dataset 'dna'.
[2018-04-11 21:42:02] Error in run 16: Run already exists in server. Run id(s): {9007829}
[2018-04-11 21:42:02] Started run 24 on task 146197, dataset 'dna'.
[2018-04-11 21:42:06] Error in run 19: Run already exists in server. Run id(s): {9007741}
[2018-04-11 21:42:06] Error in run 20: Run already exists in server. Run id(s): {9007806}
[2018-04-11 21:42:06] Error in run 18: Run already exists in server. Run id(s): {9007923}
[2018-04-11 21:42:06] Error in run 17: Run already exists in server. Run id(s): {9007701}
[2018-04-11 21:42:06] Error in run 22: Run already exists in server. Run id(s): {9007879}
[2018-04-11 21:42:06] Error in run 21: Run already exists in server. Run id(s): {9007770}
[2018-04-11 21:42:06] Started run 25 on task 146197, dataset 'dna'.
[2018-04-11 21:42:06] Started run 30 on task 146197, dataset 'dna'.
[2018-04-11 21:42:06] Started run 26 on task 146197, dataset 'dna'.
[2018-04-11 21:42:06] Started run 27 on task 146197, dataset 'dna'.
[2018-04-11 21:42:06] Started run 28 on task 146197, dataset 'dna'.
[2018-04-11 21:42:06] Started run 29 on task 146197, dataset 'dna'.
[2018-04-11 21:42:06] Error in run 23: Run already exists in server. Run id(s): {9007840}
[2018-04-11 21:42:06] Started run 31 on task 146197, dataset 'dna'.
[2018-04-11 21:42:07] Error in run 24: Run already exists in server. Run id(s): {9008044}
[2018-04-11 21:42:07] Started run 32 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Error in run 29: Run already exists in server. Run id(s): {9008082}
[2018-04-11 21:42:11] Error in run 27: Run already exists in server. Run id(s): {9007952}
[2018-04-11 21:42:11] Error in run 30: Run already exists in server. Run id(s): {9008096}
[2018-04-11 21:42:11] Error in run 28: Run already exists in server. Run id(s): {9008099}
[2018-04-11 21:42:11] Error in run 26: Run already exists in server. Run id(s): {9007859}
[2018-04-11 21:42:11] Error in run 31: Run already exists in server. Run id(s): {9008131}
[2018-04-11 21:42:11] Error in run 25: Run already exists in server. Run id(s): {9007947}
[2018-04-11 21:42:11] Started run 33 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Started run 39 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Started run 36 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Started run 35 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Started run 34 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Started run 37 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Error in run 32: Run already exists in server. Run id(s): {9008052}
[2018-04-11 21:42:11] Started run 38 on task 146197, dataset 'dna'.
[2018-04-11 21:42:11] Started run 40 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Error in run 36: Run already exists in server. Run id(s): {9008236}
[2018-04-11 21:42:16] Error in run 39: Run already exists in server. Run id(s): {9008304}
[2018-04-11 21:42:16] Error in run 34: Run already exists in server. Run id(s): {9008187}
[2018-04-11 21:42:16] Error in run 33: Run already exists in server. Run id(s): {9008129}
[2018-04-11 21:42:16] Started run 41 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Started run 42 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Error in run 35: Run already exists in server. Run id(s): {9008384}
[2018-04-11 21:42:16] Started run 45 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Error in run 37: Run already exists in server. Run id(s): {9008256}
[2018-04-11 21:42:16] Started run 46 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Started run 44 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Error in run 38: Run already exists in server. Run id(s): {9008135}
[2018-04-11 21:42:16] Started run 47 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Error in run 40: Run already exists in server. Run id(s): {9008277}
[2018-04-11 21:42:16] Started run 48 on task 146197, dataset 'dna'.
[2018-04-11 21:42:16] Started run 43 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Error in run 44: Run already exists in server. Run id(s): {9008544}
[2018-04-11 21:42:20] Error in run 41: Run already exists in server. Run id(s): {9008406}
[2018-04-11 21:42:20] Error in run 42: Run already exists in server. Run id(s): {9008239}
[2018-04-11 21:42:20] Error in run 47: Run already exists in server. Run id(s): {9008345}
[2018-04-11 21:42:20] Error in run 43: Run already exists in server. Run id(s): {9008367}
[2018-04-11 21:42:20] Started run 49 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Error in run 46: Run already exists in server. Run id(s): {9008522}
[2018-04-11 21:42:20] Error in run 48: Run already exists in server. Run id(s): {9008541}
[2018-04-11 21:42:20] Error in run 45: Run already exists in server. Run id(s): {9008322}
[2018-04-11 21:42:20] Started run 50 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Started run 53 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Started run 54 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Started run 55 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Started run 51 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Started run 52 on task 146197, dataset 'dna'.
[2018-04-11 21:42:20] Started run 56 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Error in run 50: Run already exists in server. Run id(s): {9008548}
[2018-04-11 21:42:25] Error in run 55: Run already exists in server. Run id(s): {9008799}
[2018-04-11 21:42:25] Error in run 51: Run already exists in server. Run id(s): {9008424}
[2018-04-11 21:42:25] Error in run 49: Run already exists in server. Run id(s): {9008493}
[2018-04-11 21:42:25] Error in run 53: Run already exists in server. Run id(s): {9008662}
[2018-04-11 21:42:25] Started run 57 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Error in run 54: Run already exists in server. Run id(s): {9008962}
[2018-04-11 21:42:25] Error in run 52: Run already exists in server. Run id(s): {9008480}
[2018-04-11 21:42:25] Started run 61 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Started run 63 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Started run 60 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Started run 62 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Error in run 56: Run already exists in server. Run id(s): {9008722}
[2018-04-11 21:42:25] Started run 64 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Started run 58 on task 146197, dataset 'dna'.
[2018-04-11 21:42:25] Started run 59 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Error in run 64: Run already exists in server. Run id(s): {9009190}
[2018-04-11 21:42:30] Error in run 59: Run already exists in server. Run id(s): {9008763}
[2018-04-11 21:42:30] Error in run 61: Run already exists in server. Run id(s): {9008783}
[2018-04-11 21:42:30] Error in run 63: Run already exists in server. Run id(s): {9009389}
[2018-04-11 21:42:30] Error in run 57: Run already exists in server. Run id(s): {9008823}
[2018-04-11 21:42:30] Error in run 60: Run already exists in server. Run id(s): {9008635}
[2018-04-11 21:42:30] Error in run 58: Run already exists in server. Run id(s): {9009217}
[2018-04-11 21:42:30] Error in run 62: Run already exists in server. Run id(s): {9008726}
[2018-04-11 21:42:30] Started run 65 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Started run 70 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Started run 71 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Started run 68 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Started run 66 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Started run 67 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Started run 69 on task 146197, dataset 'dna'.
[2018-04-11 21:42:30] Started run 72 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Error in run 65: Run already exists in server. Run id(s): {9009043}
[2018-04-11 21:42:35] Error in run 70: Run already exists in server. Run id(s): {9009210}
[2018-04-11 21:42:35] Error in run 71: Run already exists in server. Run id(s): {9009330}
[2018-04-11 21:42:35] Error in run 67: Run already exists in server. Run id(s): {9008973}
[2018-04-11 21:42:35] Error in run 66: Run already exists in server. Run id(s): {9008928}
[2018-04-11 21:42:35] Error in run 69: Run already exists in server. Run id(s): {9009055}
[2018-04-11 21:42:35] Error in run 68: Run already exists in server. Run id(s): {9009112}
[2018-04-11 21:42:35] Started run 73 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Started run 76 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Started run 78 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Started run 77 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Error in run 72: Run already exists in server. Run id(s): {9009108}
[2018-04-11 21:42:35] Started run 74 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Started run 80 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Started run 75 on task 146197, dataset 'dna'.
[2018-04-11 21:42:35] Started run 79 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Error in run 77: Run already exists in server. Run id(s): {9009301}
[2018-04-11 21:42:39] Error in run 78: Run already exists in server. Run id(s): {9009514}
[2018-04-11 21:42:39] Error in run 79: Run already exists in server. Run id(s): {9009600}
[2018-04-11 21:42:39] Error in run 76: Run already exists in server. Run id(s): {9009507}
[2018-04-11 21:42:39] Error in run 80: Run already exists in server. Run id(s): {9009873}
[2018-04-11 21:42:39] Error in run 73: Run already exists in server. Run id(s): {9009364}
[2018-04-11 21:42:39] Error in run 75: Run already exists in server. Run id(s): {9009666}
[2018-04-11 21:42:39] Error in run 74: Run already exists in server. Run id(s): {9009332}
[2018-04-11 21:42:39] Started run 81 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Started run 86 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Started run 88 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Started run 83 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Started run 82 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Started run 84 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Started run 85 on task 146197, dataset 'dna'.
[2018-04-11 21:42:39] Started run 87 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Error in run 81: Run already exists in server. Run id(s): {9009788}
[2018-04-11 21:42:44] Started run 89 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Error in run 82: Run already exists in server. Run id(s): {9009509}
[2018-04-11 21:42:44] Error in run 88: Run already exists in server. Run id(s): {9009793}
[2018-04-11 21:42:44] Error in run 83: Run already exists in server. Run id(s): {9009888}
[2018-04-11 21:42:44] Error in run 84: Run already exists in server. Run id(s): {9009967}
[2018-04-11 21:42:44] Started run 90 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Error in run 86: Run already exists in server. Run id(s): {9009884}
[2018-04-11 21:42:44] Started run 93 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Error in run 85: Run already exists in server. Run id(s): {9009779}
[2018-04-11 21:42:44] Started run 94 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Started run 95 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Error in run 87: Run already exists in server. Run id(s): {9009836}
[2018-04-11 21:42:44] Started run 92 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Started run 96 on task 146197, dataset 'dna'.
[2018-04-11 21:42:44] Started run 91 on task 146197, dataset 'dna'.
[2018-04-11 21:42:48] Error in run 89: Run already exists in server. Run id(s): {9010240}
[2018-04-11 21:42:48] Started run 97 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Error in run 92: Run already exists in server. Run id(s): {9009858}
[2018-04-11 21:42:49] Error in run 90: Run already exists in server. Run id(s): {9009918}
[2018-04-11 21:42:49] Error in run 91: Run already exists in server. Run id(s): {9009861}
[2018-04-11 21:42:49] Error in run 94: Run already exists in server. Run id(s): {9010212}
[2018-04-11 21:42:49] Error in run 95: Run already exists in server. Run id(s): {9010108}
[2018-04-11 21:42:49] Started run 98 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Error in run 96: Run already exists in server. Run id(s): {9010089}
[2018-04-11 21:42:49] Error in run 93: Run already exists in server. Run id(s): {9010148}
[2018-04-11 21:42:49] Started run 102 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Started run 103 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Started run 104 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Started run 100 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Started run 99 on task 146197, dataset 'dna'.
[2018-04-11 21:42:49] Started run 101 on task 146197, dataset 'dna'.
[2018-04-11 21:42:53] Error in run 97: Run already exists in server. Run id(s): {9010034}
[2018-04-11 21:42:53] Started run 105 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Error in run 98: Run already exists in server. Run id(s): {9010117}
[2018-04-11 21:42:54] Error in run 99: Run already exists in server. Run id(s): {9010303}
[2018-04-11 21:42:54] Error in run 100: Run already exists in server. Run id(s): {9010428}
[2018-04-11 21:42:54] Error in run 103: Run already exists in server. Run id(s): {9010354}
[2018-04-11 21:42:54] Started run 106 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Error in run 102: Run already exists in server. Run id(s): {9010271}
[2018-04-11 21:42:54] Error in run 104: Run already exists in server. Run id(s): {9010294}
[2018-04-11 21:42:54] Error in run 101: Run already exists in server. Run id(s): {9010157}
[2018-04-11 21:42:54] Started run 110 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Started run 108 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Started run 107 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Started run 111 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Started run 109 on task 146197, dataset 'dna'.
[2018-04-11 21:42:54] Started run 112 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Error in run 105: Run already exists in server. Run id(s): {9010283}
[2018-04-11 21:42:58] Started run 113 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Error in run 109: Run already exists in server. Run id(s): {9010631}
[2018-04-11 21:42:58] Error in run 110: Run already exists in server. Run id(s): {9010642}
[2018-04-11 21:42:58] Started run 114 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Started run 115 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Error in run 106: Run already exists in server. Run id(s): {9010588}
[2018-04-11 21:42:58] Error in run 112: Run already exists in server. Run id(s): {9010480}
[2018-04-11 21:42:58] Started run 116 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Error in run 111: Run already exists in server. Run id(s): {9010415}
[2018-04-11 21:42:58] Error in run 107: Run already exists in server. Run id(s): {9010433}
[2018-04-11 21:42:58] Error in run 108: Run already exists in server. Run id(s): {9010395}
[2018-04-11 21:42:58] Started run 118 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Started run 117 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Started run 119 on task 146197, dataset 'dna'.
[2018-04-11 21:42:58] Started run 120 on task 146197, dataset 'dna'.
[2018-04-11 21:43:02] Error in run 113: Run already exists in server. Run id(s): {9010568}
[2018-04-11 21:43:02] Started run 121 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Error in run 115: Run already exists in server. Run id(s): {9035471}
[2018-04-11 21:43:03] Error in run 114: Run already exists in server. Run id(s): {9035704}
[2018-04-11 21:43:03] Started run 122 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Started run 123 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Error in run 116: Run already exists in server. Run id(s): {9010585}
[2018-04-11 21:43:03] Started run 124 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Error in run 117: Run already exists in server. Run id(s): {9010562}
[2018-04-11 21:43:03] Error in run 120: Run already exists in server. Run id(s): {9010709}
[2018-04-11 21:43:03] Error in run 119: Run already exists in server. Run id(s): {9010724}
[2018-04-11 21:43:03] Error in run 118: Run already exists in server. Run id(s): {9035651}
[2018-04-11 21:43:03] Started run 125 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Started run 127 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Started run 126 on task 146197, dataset 'dna'.
[2018-04-11 21:43:03] Started run 128 on task 146197, dataset 'dna'.
[2018-04-11 21:43:07] Error in run 121: Run already exists in server. Run id(s): {9035384}
[2018-04-11 21:43:07] Started run 129 on task 146197, dataset 'dna'.
[2018-04-11 21:43:07] Error in run 122: Run already exists in server. Run id(s): {9035198}
[2018-04-11 21:43:07] Started run 130 on task 146197, dataset 'dna'.
[2018-04-11 21:43:07] Error in run 123: Run already exists in server. Run id(s): {9010751}
[2018-04-11 21:43:07] Started run 131 on task 146197, dataset 'dna'.
[2018-04-11 21:43:07] Error in run 124: Run already exists in server. Run id(s): {9035481}
[2018-04-11 21:43:07] Started run 132 on task 146197, dataset 'dna'.
[2018-04-11 21:43:08] Error in run 125: Run already exists in server. Run id(s): {9035010}
[2018-04-11 21:43:08] Started run 133 on task 146197, dataset 'dna'.
[2018-04-11 21:43:08] Error in run 126: Run already exists in server. Run id(s): {9035424}
[2018-04-11 21:43:08] Error in run 127: Run already exists in server. Run id(s): {9035499}
[2018-04-11 21:43:08] Error in run 128: Run already exists in server. Run id(s): {9035511}
[2018-04-11 21:43:08] Started run 134 on task 146197, dataset 'dna'.
[2018-04-11 21:43:08] Started run 135 on task 146197, dataset 'dna'.
[2018-04-11 21:43:08] Started run 136 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Error in run 129: Run already exists in server. Run id(s): {9035852}
[2018-04-11 21:43:12] Error in run 130: Run already exists in server. Run id(s): {9036229}
[2018-04-11 21:43:12] Error in run 131: Run already exists in server. Run id(s): {9035934}
[2018-04-11 21:43:12] Started run 137 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Error in run 132: Run already exists in server. Run id(s): {9036021}
[2018-04-11 21:43:12] Started run 140 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Started run 138 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Started run 139 on task 146197, dataset 'dna'.
[2018-04-11 21:43:12] Error in run 133: Run already exists in server. Run id(s): {9035728}
[2018-04-11 21:43:12] Started run 141 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Error in run 135: Run already exists in server. Run id(s): {9035613}
[2018-04-11 21:43:13] Error in run 136: Run already exists in server. Run id(s): {9035999}
[2018-04-11 21:43:13] Started run 142 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Error in run 134: Run already exists in server. Run id(s): {9035577}
[2018-04-11 21:43:13] Started run 143 on task 146197, dataset 'dna'.
[2018-04-11 21:43:13] Started run 144 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Error in run 140: Run already exists in server. Run id(s): {9036164}
[2018-04-11 21:43:17] Error in run 137: Run already exists in server. Run id(s): {9035899}
[2018-04-11 21:43:17] Started run 145 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Started run 146 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Error in run 139: Run already exists in server. Run id(s): {9035749}
[2018-04-11 21:43:17] Error in run 138: Run already exists in server. Run id(s): {9035990}
[2018-04-11 21:43:17] Error in run 141: Run already exists in server. Run id(s): {9036038}
[2018-04-11 21:43:17] Started run 147 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Started run 148 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Started run 149 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Error in run 142: Run already exists in server. Run id(s): {9036224}
[2018-04-11 21:43:17] Error in run 144: Run already exists in server. Run id(s): {9036433}
[2018-04-11 21:43:17] Error in run 143: Run already exists in server. Run id(s): {9035959}
[2018-04-11 21:43:17] Started run 150 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Started run 151 on task 146197, dataset 'dna'.
[2018-04-11 21:43:17] Started run 152 on task 146197, dataset 'dna'.
[2018-04-11 21:43:21] Error in run 147: Run already exists in server. Run id(s): {9036201}
[2018-04-11 21:43:21] Error in run 148: Run already exists in server. Run id(s): {9036512}
[2018-04-11 21:43:21] Error in run 145: Run already exists in server. Run id(s): {9036488}
[2018-04-11 21:43:21] Error in run 149: Run already exists in server. Run id(s): {9036340}
[2018-04-11 21:43:21] Error in run 146: Run already exists in server. Run id(s): {9036333}
[2018-04-11 21:43:21] Started run 153 on task 146197, dataset 'dna'.
[2018-04-11 21:43:21] Started run 155 on task 146197, dataset 'dna'.
[2018-04-11 21:43:21] Started run 157 on task 146197, dataset 'dna'.
[2018-04-11 21:43:21] Started run 156 on task 146197, dataset 'dna'.
[2018-04-11 21:43:21] Started run 154 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Error in run 151: Run already exists in server. Run id(s): {9036466}
[2018-04-11 21:43:22] Error in run 152: Run already exists in server. Run id(s): {9036407}
[2018-04-11 21:43:22] Started run 158 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Error in run 150: Run already exists in server. Run id(s): {9036475}
[2018-04-11 21:43:22] Started run 160 on task 146197, dataset 'dna'.
[2018-04-11 21:43:22] Started run 159 on task 146197, dataset 'dna'.
[2018-04-11 21:43:26] Error in run 154: Run already exists in server. Run id(s): {9036863}
[2018-04-11 21:43:26] Error in run 153: Run already exists in server. Run id(s): {9036561}
[2018-04-11 21:43:26] Error in run 157: Run already exists in server. Run id(s): {9036912}
[2018-04-11 21:43:26] Error in run 155: Run already exists in server. Run id(s): {9036564}
[2018-04-11 21:43:26] Error in run 156: Run already exists in server. Run id(s): {9036756}
[2018-04-11 21:43:26] Started run 161 on task 146197, dataset 'dna'.
[2018-04-11 21:43:26] Started run 162 on task 146197, dataset 'dna'.
[2018-04-11 21:43:26] Started run 163 on task 146197, dataset 'dna'.
[2018-04-11 21:43:26] Started run 164 on task 146197, dataset 'dna'.
[2018-04-11 21:43:26] Started run 165 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Error in run 158: Run already exists in server. Run id(s): {9036932}
[2018-04-11 21:43:27] Error in run 159: Run already exists in server. Run id(s): {9036576}
[2018-04-11 21:43:27] Error in run 160: Run already exists in server. Run id(s): {9036685}
[2018-04-11 21:43:27] Started run 166 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Started run 167 on task 146197, dataset 'dna'.
[2018-04-11 21:43:27] Started run 168 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Error in run 162: Run already exists in server. Run id(s): {9036679}
[2018-04-11 21:43:31] Error in run 161: Run already exists in server. Run id(s): {9036668}
[2018-04-11 21:43:31] Error in run 163: Run already exists in server. Run id(s): {9036881}
[2018-04-11 21:43:31] Error in run 165: Run already exists in server. Run id(s): {9036894}
[2018-04-11 21:43:31] Error in run 164: Run already exists in server. Run id(s): {9036897}
[2018-04-11 21:43:31] Started run 169 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Started run 173 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Started run 172 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Started run 170 on task 146197, dataset 'dna'.
[2018-04-11 21:43:31] Started run 171 on task 146197, dataset 'dna'.
[2018-04-11 21:43:32] Error in run 167: Run already exists in server. Run id(s): {9037005}
[2018-04-11 21:43:32] Error in run 168: Run already exists in server. Run id(s): {9037303}
[2018-04-11 21:43:32] Error in run 166: Run already exists in server. Run id(s): {9036928}
[2018-04-11 21:43:32] Started run 174 on task 146197, dataset 'dna'.
[2018-04-11 21:43:32] Started run 175 on task 146197, dataset 'dna'.
[2018-04-11 21:43:32] Started run 176 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Error in run 169: Run already exists in server. Run id(s): {9036991}
[2018-04-11 21:43:36] Error in run 172: Run already exists in server. Run id(s): {9037306}
[2018-04-11 21:43:36] Error in run 170: Run already exists in server. Run id(s): {9037322}
[2018-04-11 21:43:36] Error in run 171: Run already exists in server. Run id(s): {9037249}
[2018-04-11 21:43:36] Error in run 173: Run already exists in server. Run id(s): {9037297}
[2018-04-11 21:43:36] Started run 177 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 179 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 181 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 178 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 180 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Error in run 176: Run already exists in server. Run id(s): {9037088}
[2018-04-11 21:43:36] Error in run 174: Run already exists in server. Run id(s): {9037248}
[2018-04-11 21:43:36] Error in run 175: Run already exists in server. Run id(s): {9037299}
[2018-04-11 21:43:36] Started run 182 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 183 on task 146197, dataset 'dna'.
[2018-04-11 21:43:36] Started run 184 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Error in run 179: Run already exists in server. Run id(s): {9037427}
[2018-04-11 21:43:40] Error in run 178: Run already exists in server. Run id(s): {9037619}
[2018-04-11 21:43:40] Error in run 180: Run already exists in server. Run id(s): {9037706}
[2018-04-11 21:43:40] Error in run 181: Run already exists in server. Run id(s): {9037392}
[2018-04-11 21:43:40] Error in run 177: Run already exists in server. Run id(s): {9037510}
[2018-04-11 21:43:40] Started run 185 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Started run 189 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Started run 186 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Started run 187 on task 146197, dataset 'dna'.
[2018-04-11 21:43:40] Started run 188 on task 146197, dataset 'dna'.
[2018-04-11 21:43:41] Error in run 184: Run already exists in server. Run id(s): {9037373}
[2018-04-11 21:43:41] Error in run 183: Run already exists in server. Run id(s): {9037457}
[2018-04-11 21:43:41] Started run 190 on task 146197, dataset 'dna'.
[2018-04-11 21:43:41] Error in run 182: Run already exists in server. Run id(s): {9037681}
[2018-04-11 21:43:41] Started run 192 on task 146197, dataset 'dna'.
[2018-04-11 21:43:41] Started run 191 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Error in run 189: Run already exists in server. Run id(s): {9037602}
[2018-04-11 21:43:45] Error in run 186: Run already exists in server. Run id(s): {9037801}
[2018-04-11 21:43:45] Error in run 188: Run already exists in server. Run id(s): {9037782}
[2018-04-11 21:43:45] Error in run 185: Run already exists in server. Run id(s): {9037767}
[2018-04-11 21:43:45] Error in run 187: Run already exists in server. Run id(s): {9037742}
[2018-04-11 21:43:45] Started run 193 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Started run 195 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Started run 197 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Started run 194 on task 146197, dataset 'dna'.
[2018-04-11 21:43:45] Started run 196 on task 146197, dataset 'dna'.
[2018-04-11 21:43:46] Error in run 191: Run already exists in server. Run id(s): {9037857}
[2018-04-11 21:43:46] Error in run 190: Run already exists in server. Run id(s): {9037989}
[2018-04-11 21:43:46] Error in run 192: Run already exists in server. Run id(s): {9038022}
[2018-04-11 21:43:46] Started run 198 on task 146197, dataset 'dna'.
[2018-04-11 21:43:46] Started run 199 on task 146197, dataset 'dna'.
[2018-04-11 21:43:46] Started run 200 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Error in run 195: Run already exists in server. Run id(s): {9038005}
[2018-04-11 21:43:50] Error in run 193: Run already exists in server. Run id(s): {9038021}
[2018-04-11 21:43:50] Error in run 194: Run already exists in server. Run id(s): {9038104}
[2018-04-11 21:43:50] Error in run 197: Run already exists in server. Run id(s): {9037985}
[2018-04-11 21:43:50] Error in run 196: Run already exists in server. Run id(s): {9038210}
[2018-04-11 21:43:50] Started run 201 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Started run 203 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Started run 204 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Started run 205 on task 146197, dataset 'dna'.
[2018-04-11 21:43:50] Started run 202 on task 146197, dataset 'dna'.
[2018-04-11 21:43:51] Error in run 198: Run already exists in server. Run id(s): {9038051}
[2018-04-11 21:43:51] Error in run 199: Run already exists in server. Run id(s): {9038077}
[2018-04-11 21:43:51] Error in run 200: Run already exists in server. Run id(s): {9038297}
[2018-04-11 21:43:51] Started run 206 on task 146197, dataset 'dna'.
[2018-04-11 21:43:51] Started run 207 on task 146197, dataset 'dna'.
[2018-04-11 21:43:51] Started run 208 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Error in run 202: Run already exists in server. Run id(s): {9038375}
[2018-04-11 21:43:55] Started run 209 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Error in run 201: Run already exists in server. Run id(s): {9038169}
[2018-04-11 21:43:55] Error in run 205: Run already exists in server. Run id(s): {9038225}
[2018-04-11 21:43:55] Error in run 203: Run already exists in server. Run id(s): {9038258}
[2018-04-11 21:43:55] Error in run 204: Run already exists in server. Run id(s): {9038081}
[2018-04-11 21:43:55] Started run 210 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Started run 213 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Started run 211 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Started run 212 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Error in run 208: Run already exists in server. Run id(s): {9038424}
[2018-04-11 21:43:55] Error in run 206: Run already exists in server. Run id(s): {9038212}
[2018-04-11 21:43:55] Started run 214 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Started run 215 on task 146197, dataset 'dna'.
[2018-04-11 21:43:55] Error in run 207: Run already exists in server. Run id(s): {9038423}
[2018-04-11 21:43:55] Started run 216 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Error in run 209: Run already exists in server. Run id(s): {9038587}
[2018-04-11 21:43:59] Started run 217 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Error in run 213: Run already exists in server. Run id(s): {9038527}
[2018-04-11 21:43:59] Error in run 210: Run already exists in server. Run id(s): {9038324}
[2018-04-11 21:43:59] Error in run 212: Run already exists in server. Run id(s): {9038386}
[2018-04-11 21:43:59] Error in run 211: Run already exists in server. Run id(s): {9038603, 9038573}
[2018-04-11 21:43:59] Started run 218 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Started run 220 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Started run 221 on task 146197, dataset 'dna'.
[2018-04-11 21:43:59] Started run 219 on task 146197, dataset 'dna'.
[2018-04-11 21:44:00] Error in run 214: Run already exists in server. Run id(s): {9038434}
[2018-04-11 21:44:00] Started run 222 on task 146197, dataset 'dna'.
[2018-04-11 21:44:00] Error in run 215: Run already exists in server. Run id(s): {9038588}
[2018-04-11 21:44:00] Started run 223 on task 146197, dataset 'dna'.
[2018-04-11 21:44:00] Error in run 216: Run already exists in server. Run id(s): {9038669}
[2018-04-11 21:44:00] Started run 224 on task 146197, dataset 'dna'.
[2018-04-11 21:44:03] Error in run 217: Run already exists in server. Run id(s): {9038540}
[2018-04-11 21:44:03] Started run 225 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Error in run 218: Run already exists in server. Run id(s): {9038693}
[2018-04-11 21:44:04] Started run 226 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Error in run 220: Run already exists in server. Run id(s): {9038797}
[2018-04-11 21:44:04] Started run 227 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Error in run 221: Run already exists in server. Run id(s): {9038637}
[2018-04-11 21:44:04] Error in run 219: Run already exists in server. Run id(s): {9038794}
[2018-04-11 21:44:04] Error in run 222: Run already exists in server. Run id(s): {9038742}
[2018-04-11 21:44:04] Started run 228 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Error in run 223: Run already exists in server. Run id(s): {9038816}
[2018-04-11 21:44:04] Started run 229 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Started run 230 on task 146197, dataset 'dna'.
[2018-04-11 21:44:04] Started run 231 on task 146197, dataset 'dna'.
[2018-04-11 21:44:05] Error in run 224: Run already exists in server. Run id(s): {9038842}
[2018-04-11 21:44:05] Started run 232 on task 146197, dataset 'dna'.
[2018-04-11 21:44:08] Error in run 225: Run already exists in server. Run id(s): {9038941}
[2018-04-11 21:44:08] Started run 233 on task 146197, dataset 'dna'.
[2018-04-11 21:44:08] Error in run 226: Run already exists in server. Run id(s): {9038734}
[2018-04-11 21:44:08] Started run 234 on task 146197, dataset 'dna'.
[2018-04-11 21:44:08] Error in run 227: Run already exists in server. Run id(s): {9038754}
[2018-04-11 21:44:08] Started run 235 on task 146197, dataset 'dna'.
[2018-04-11 21:44:09] Error in run 228: Run already exists in server. Run id(s): {9039097, 9039102}
[2018-04-11 21:44:09] Started run 236 on task 146197, dataset 'dna'.
[2018-04-11 21:44:09] Error in run 229: Run already exists in server. Run id(s): {9038994}
[2018-04-11 21:44:09] Error in run 231: Run already exists in server. Run id(s): {9038990}
[2018-04-11 21:44:09] Error in run 230: Run already exists in server. Run id(s): {9038916}
[2018-04-11 21:44:09] Started run 237 on task 146197, dataset 'dna'.
[2018-04-11 21:44:09] Started run 238 on task 146197, dataset 'dna'.
[2018-04-11 21:44:09] Started run 239 on task 146197, dataset 'dna'.
[2018-04-11 21:44:09] Error in run 232: Run already exists in server. Run id(s): {9039211}
[2018-04-11 21:44:09] Started run 240 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 233: Run already exists in server. Run id(s): {9039042}
[2018-04-11 21:44:13] Started run 241 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 234: Run already exists in server. Run id(s): {9038911}
[2018-04-11 21:44:13] Started run 242 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 235: Run already exists in server. Run id(s): {9039312}
[2018-04-11 21:44:13] Started run 243 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 236: Run already exists in server. Run id(s): {9039018}
[2018-04-11 21:44:13] Started run 244 on task 146197, dataset 'dna'.
[2018-04-11 21:44:13] Error in run 237: Run already exists in server. Run id(s): {9039200}
[2018-04-11 21:44:13] Started run 245 on task 146197, dataset 'dna'.
[2018-04-11 21:44:14] Error in run 239: Run already exists in server. Run id(s): {9039064}
[2018-04-11 21:44:14] Started run 246 on task 146197, dataset 'dna'.
[2018-04-11 21:44:14] Error in run 238: Run already exists in server. Run id(s): {9039142}
[2018-04-11 21:44:14] Error in run 240: Run already exists in server. Run id(s): {9039193}
[2018-04-11 21:44:14] Started run 247 on task 146197, dataset 'dna'.
[2018-04-11 21:44:14] Started run 248 on task 146197, dataset 'dna'.
[2018-04-11 21:44:17] Error in run 241: Run already exists in server. Run id(s): {9039394}
[2018-04-11 21:44:17] Started run 249 on task 146197, dataset 'dna'.
[2018-04-11 21:44:17] Error in run 242: Run already exists in server. Run id(s): {9039333}
[2018-04-11 21:44:17] Started run 250 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Error in run 243: Run already exists in server. Run id(s): {9039313}
[2018-04-11 21:44:18] Error in run 244: Run already exists in server. Run id(s): {9039405}
[2018-04-11 21:44:18] Started run 251 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Started run 252 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Error in run 245: Run already exists in server. Run id(s): {9039294}
[2018-04-11 21:44:18] Started run 253 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Error in run 246: Run already exists in server. Run id(s): {9039467}
[2018-04-11 21:44:18] Started run 254 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Error in run 247: Run already exists in server. Run id(s): {9039335}
[2018-04-11 21:44:18] Started run 255 on task 146197, dataset 'dna'.
[2018-04-11 21:44:18] Error in run 248: Run already exists in server. Run id(s): {9039349}
[2018-04-11 21:44:18] Started run 256 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 249: Run already exists in server. Run id(s): {9039548}
[2018-04-11 21:44:22] Started run 257 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 250: Run already exists in server. Run id(s): {9039501}
[2018-04-11 21:44:22] Started run 258 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 251: Run already exists in server. Run id(s): {9039420}
[2018-04-11 21:44:22] Error in run 252: Run already exists in server. Run id(s): {9039461}
[2018-04-11 21:44:22] Started run 259 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Started run 260 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 253: Run already exists in server. Run id(s): {9039714}
[2018-04-11 21:44:22] Started run 261 on task 146197, dataset 'dna'.
[2018-04-11 21:44:22] Error in run 254: Run already exists in server. Run id(s): {9039553}
[2018-04-11 21:44:22] Started run 262 on task 146197, dataset 'dna'.
[2018-04-11 21:44:23] Error in run 255: Run already exists in server. Run id(s): {9039520}
[2018-04-11 21:44:23] Started run 263 on task 146197, dataset 'dna'.
[2018-04-11 21:44:23] Error in run 256: Run already exists in server. Run id(s): {9039680}
[2018-04-11 21:44:23] Started run 264 on task 146197, dataset 'dna'.
[2018-04-11 21:44:26] Error in run 257: Run already exists in server. Run id(s): {9039780}
[2018-04-11 21:44:26] Started run 265 on task 146197, dataset 'dna'.
[2018-04-11 21:44:26] Error in run 258: Run already exists in server. Run id(s): {9039542}
[2018-04-11 21:44:26] Started run 266 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Error in run 259: Run already exists in server. Run id(s): {9039882}
[2018-04-11 21:44:27] Started run 267 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Error in run 260: Run already exists in server. Run id(s): {9039860}
[2018-04-11 21:44:27] Started run 268 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Error in run 261: Run already exists in server. Run id(s): {9039797}
[2018-04-11 21:44:27] Error in run 262: Run already exists in server. Run id(s): {9039795}
[2018-04-11 21:44:27] Started run 269 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Started run 270 on task 146197, dataset 'dna'.
[2018-04-11 21:44:27] Error in run 263: Run already exists in server. Run id(s): {9039822}
[2018-04-11 21:44:27] Started run 271 on task 146197, dataset 'dna'.
[2018-04-11 21:44:28] Error in run 264: Run already exists in server. Run id(s): {9039726}
[2018-04-11 21:44:28] Started run 272 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 265: Run already exists in server. Run id(s): {9039863}
[2018-04-11 21:44:31] Started run 273 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 266: Run already exists in server. Run id(s): {9039850}
[2018-04-11 21:44:31] Error in run 267: Run already exists in server. Run id(s): {9039827}
[2018-04-11 21:44:31] Error in run 268: Run already exists in server. Run id(s): {9039861}
[2018-04-11 21:44:31] Started run 274 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Started run 275 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Started run 276 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Error in run 269: Run already exists in server. Run id(s): {9039989}
[2018-04-11 21:44:31] Error in run 270: Run already exists in server. Run id(s): {9039871}
[2018-04-11 21:44:31] Started run 277 on task 146197, dataset 'dna'.
[2018-04-11 21:44:31] Started run 278 on task 146197, dataset 'dna'.
[2018-04-11 21:44:32] Error in run 271: Run already exists in server. Run id(s): {9039978}
[2018-04-11 21:44:32] Started run 279 on task 146197, dataset 'dna'.
[2018-04-11 21:44:32] Error in run 272: Run already exists in server. Run id(s): {9039938}
[2018-04-11 21:44:32] Started run 280 on task 146197, dataset 'dna'.
[2018-04-11 21:44:35] Error in run 273: Run already exists in server. Run id(s): {9039967}
[2018-04-11 21:44:35] Started run 281 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Error in run 274: Run already exists in server. Run id(s): {9040206}
[2018-04-11 21:44:36] Started run 282 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Error in run 278: Run already exists in server. Run id(s): {9040082}
[2018-04-11 21:44:36] Error in run 276: Run already exists in server. Run id(s): {9040209}
[2018-04-11 21:44:36] Error in run 275: Run already exists in server. Run id(s): {9040020}
[2018-04-11 21:44:36] Error in run 277: Run already exists in server. Run id(s): {9039966}
[2018-04-11 21:44:36] Started run 283 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Started run 286 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Started run 284 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Started run 285 on task 146197, dataset 'dna'.
[2018-04-11 21:44:36] Error in run 279: Run already exists in server. Run id(s): {9040233}
[2018-04-11 21:44:36] Started run 287 on task 146197, dataset 'dna'.
[2018-04-11 21:44:37] Error in run 280: Run already exists in server. Run id(s): {9040135}
[2018-04-11 21:44:37] Started run 288 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 281: Run already exists in server. Run id(s): {9040329}
[2018-04-11 21:44:40] Started run 289 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 282: Run already exists in server. Run id(s): {9040308}
[2018-04-11 21:44:40] Started run 290 on task 146197, dataset 'dna'.
[2018-04-11 21:44:40] Error in run 283: Run already exists in server. Run id(s): {9040168}
[2018-04-11 21:44:40] Started run 291 on task 146197, dataset 'dna'.
[2018-04-11 21:44:41] Error in run 284: Run already exists in server. Run id(s): {9040388}
[2018-04-11 21:44:41] Error in run 286: Run already exists in server. Run id(s): {9040546}
[2018-04-11 21:44:41] Started run 292 on task 146197, dataset 'dna'.
[2018-04-11 21:44:41] Error in run 285: Run already exists in server. Run id(s): {9040415}
[2018-04-11 21:44:41] Started run 294 on task 146197, dataset 'dna'.
[2018-04-11 21:44:41] Started run 293 on task 146197, dataset 'dna'.
[2018-04-11 21:44:41] Error in run 287: Run already exists in server. Run id(s): {9040574}
[2018-04-11 21:44:41] Started run 295 on task 146197, dataset 'dna'.
[2018-04-11 21:44:41] Error in run 288: Run already exists in server. Run id(s): {9040494}
[2018-04-11 21:44:41] Started run 296 on task 146197, dataset 'dna'.
[2018-04-11 21:44:44] Error in run 289: Run already exists in server. Run id(s): {9040565}
[2018-04-11 21:44:44] Started run 297 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Error in run 290: Run already exists in server. Run id(s): {9040616}
[2018-04-11 21:44:45] Started run 298 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Error in run 291: Run already exists in server. Run id(s): {9040412}
[2018-04-11 21:44:45] Started run 299 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Error in run 293: Run already exists in server. Run id(s): {9040621}
[2018-04-11 21:44:45] Error in run 294: Run already exists in server. Run id(s): {9040522}
[2018-04-11 21:44:45] Error in run 292: Run already exists in server. Run id(s): {9040635}
[2018-04-11 21:44:45] Started run 300 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Started run 302 on task 146197, dataset 'dna'.
[2018-04-11 21:44:46] Error in run 295: Run already exists in server. Run id(s): {9040900}
[2018-04-11 21:44:46] Started run 303 on task 146197, dataset 'dna'.
[2018-04-11 21:44:45] Started run 301 on task 146197, dataset 'dna'.
[2018-04-11 21:44:46] Error in run 296: Run already exists in server. Run id(s): {9040879}
[2018-04-11 21:44:46] Started run 304 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 297: Run already exists in server. Run id(s): {9040779}
[2018-04-11 21:44:49] Started run 305 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 298: Run already exists in server. Run id(s): {9040828}
[2018-04-11 21:44:49] Started run 306 on task 146197, dataset 'dna'.
[2018-04-11 21:44:49] Error in run 299: Run already exists in server. Run id(s): {9040701}
[2018-04-11 21:44:49] Started run 307 on task 146197, dataset 'dna'.
[2018-04-11 21:44:50] Error in run 300: Run already exists in server. Run id(s): {9040776}
[2018-04-11 21:44:50] Error in run 303: Run already exists in server. Run id(s): {9040752}
[2018-04-11 21:44:50] Started run 308 on task 146197, dataset 'dna'.
[2018-04-11 21:44:50] Error in run 301: Run already exists in server. Run id(s): {9040729}
[2018-04-11 21:44:50] Error in run 304: Run already exists in server. Run id(s): {9040870}
[2018-04-11 21:44:50] Error in run 302: Run already exists in server. Run id(s): {9040695}
[2018-04-11 21:44:50] Started run 310 on task 146197, dataset 'dna'.
[2018-04-11 21:44:50] Started run 312 on task 146197, dataset 'dna'.
[2018-04-11 21:44:50] Started run 309 on task 146197, dataset 'dna'.
[2018-04-11 21:44:50] Started run 311 on task 146197, dataset 'dna'.
[2018-04-11 21:44:53] Error in run 305: Run already exists in server. Run id(s): {9040793}
[2018-04-11 21:44:53] Started run 313 on task 146197, dataset 'dna'.
[2018-04-11 21:44:54] Error in run 306: Run already exists in server. Run id(s): {9040846}
[2018-04-11 21:44:54] Started run 314 on task 146197, dataset 'dna'.
[2018-04-11 21:44:54] Error in run 307: Run already exists in server. Run id(s): {9040851}
[2018-04-11 21:44:54] Started run 315 on task 146197, dataset 'dna'.
[2018-04-11 21:44:55] Error in run 308: Run already exists in server. Run id(s): {9041006}
[2018-04-11 21:44:55] Started run 316 on task 146197, dataset 'dna'.
[2018-04-11 21:44:55] Error in run 310: Run already exists in server. Run id(s): {9040904}
[2018-04-11 21:44:55] Started run 317 on task 146197, dataset 'dna'.
[2018-04-11 21:44:55] Error in run 311: Run already exists in server. Run id(s): {9041035}
[2018-04-11 21:44:55] Started run 318 on task 146197, dataset 'dna'.
[2018-04-11 21:44:55] Error in run 312: Run already exists in server. Run id(s): {9040892}
[2018-04-11 21:44:55] Error in run 309: Run already exists in server. Run id(s): {9040948}
[2018-04-11 21:44:55] Started run 319 on task 146197, dataset 'dna'.
[2018-04-11 21:44:55] Started run 320 on task 146197, dataset 'dna'.
[2018-04-11 21:44:58] Error in run 313: Run already exists in server. Run id(s): {9041094}
[2018-04-11 21:44:58] Started run 321 on task 146197, dataset 'dna'.
[2018-04-11 21:44:58] Error in run 314: Run already exists in server. Run id(s): {9041037}
[2018-04-11 21:44:58] Started run 322 on task 146197, dataset 'dna'.
[2018-04-11 21:44:59] Error in run 315: Run already exists in server. Run id(s): {9041206}
[2018-04-11 21:44:59] Started run 323 on task 146197, dataset 'dna'.
[2018-04-11 21:44:59] Error in run 316: Run already exists in server. Run id(s): {9041010}
[2018-04-11 21:44:59] Started run 324 on task 146197, dataset 'dna'.
[2018-04-11 21:44:59] Error in run 317: Run already exists in server. Run id(s): {9041115}
[2018-04-11 21:44:59] Started run 325 on task 146197, dataset 'dna'.
[2018-04-11 21:44:59] Error in run 318: Run already exists in server. Run id(s): {9041152}
[2018-04-11 21:44:59] Started run 326 on task 146197, dataset 'dna'.
[2018-04-11 21:45:00] Error in run 320: Run already exists in server. Run id(s): {9041107}
[2018-04-11 21:45:00] Error in run 319: Run already exists in server. Run id(s): {9041221}
[2018-04-11 21:45:00] Started run 327 on task 146197, dataset 'dna'.
[2018-04-11 21:45:00] Started run 328 on task 146197, dataset 'dna'.
[2018-04-11 21:45:02] Error in run 321: Run already exists in server. Run id(s): {9041222}
[2018-04-11 21:45:02] Started run 329 on task 146197, dataset 'dna'.
[2018-04-11 21:45:03] Error in run 322: Run already exists in server. Run id(s): {9041214}
[2018-04-11 21:45:03] Started run 330 on task 146197, dataset 'dna'.
[2018-04-11 21:45:03] Error in run 323: Run already exists in server. Run id(s): {9041197}
[2018-04-11 21:45:03] Started run 331 on task 146197, dataset 'dna'.
[2018-04-11 21:45:04] Error in run 324: Run already exists in server. Run id(s): {9041362}
[2018-04-11 21:45:04] Started run 332 on task 146197, dataset 'dna'.
[2018-04-11 21:45:04] Error in run 325: Run already exists in server. Run id(s): {9041161}
[2018-04-11 21:45:04] Started run 333 on task 146197, dataset 'dna'.
[2018-04-11 21:45:04] Error in run 326: Run already exists in server. Run id(s): {9041409}
[2018-04-11 21:45:04] Started run 334 on task 146197, dataset 'dna'.
[2018-04-11 21:45:04] Error in run 327: Run already exists in server. Run id(s): {9041411}
[2018-04-11 21:45:04] Started run 335 on task 146197, dataset 'dna'.
[2018-04-11 21:45:04] Error in run 328: Run already exists in server. Run id(s): {9041356}
[2018-04-11 21:45:04] Started run 336 on task 146197, dataset 'dna'.
[2018-04-11 21:45:07] Error in run 329: Run already exists in server. Run id(s): {9041299}
[2018-04-11 21:45:07] Started run 337 on task 146197, dataset 'dna'.
[2018-04-11 21:45:07] Error in run 330: Run already exists in server. Run id(s): {9041384}
[2018-04-11 21:45:07] Started run 338 on task 146197, dataset 'dna'.
[2018-04-11 21:45:08] Error in run 331: Run already exists in server. Run id(s): {9041467}
[2018-04-11 21:45:08] Started run 339 on task 146197, dataset 'dna'.
[2018-04-11 21:45:08] Error in run 332: Run already exists in server. Run id(s): {9041513}
[2018-04-11 21:45:08] Started run 340 on task 146197, dataset 'dna'.
[2018-04-11 21:45:08] Error in run 333: Run already exists in server. Run id(s): {9041350}
[2018-04-11 21:45:08] Error in run 334: Run already exists in server. Run id(s): {9041601}
[2018-04-11 21:45:08] Started run 341 on task 146197, dataset 'dna'.
[2018-04-11 21:45:08] Started run 342 on task 146197, dataset 'dna'.
[2018-04-11 21:45:09] Error in run 335: Run already exists in server. Run id(s): {9041433}
[2018-04-11 21:45:09] Started run 343 on task 146197, dataset 'dna'.
[2018-04-11 21:45:09] Error in run 336: Run already exists in server. Run id(s): {9041563}
[2018-04-11 21:45:09] Started run 344 on task 146197, dataset 'dna'.
[2018-04-11 21:45:11] Error in run 337: Run already exists in server. Run id(s): {9041565}
[2018-04-11 21:45:11] Started run 345 on task 146197, dataset 'dna'.
[2018-04-11 21:45:12] Error in run 338: Run already exists in server. Run id(s): {9041647}
[2018-04-11 21:45:12] Started run 346 on task 146197, dataset 'dna'.
[2018-04-11 21:45:12] Error in run 339: Run already exists in server. Run id(s): {9041561}
[2018-04-11 21:45:12] Started run 347 on task 146197, dataset 'dna'.
[2018-04-11 21:45:13] Error in run 340: Run already exists in server. Run id(s): {9041696}
[2018-04-11 21:45:13] Started run 348 on task 146197, dataset 'dna'.
[2018-04-11 21:45:13] Error in run 341: Run already exists in server. Run id(s): {9041761}
[2018-04-11 21:45:13] Started run 349 on task 146197, dataset 'dna'.
[2018-04-11 21:45:13] Error in run 342: Run already exists in server. Run id(s): {9041553}
[2018-04-11 21:45:13] Started run 350 on task 146197, dataset 'dna'.
[2018-04-11 21:45:13] Error in run 343: Run already exists in server. Run id(s): {9041615}
[2018-04-11 21:45:13] Started run 351 on task 146197, dataset 'dna'.
[2018-04-11 21:45:13] Error in run 344: Run already exists in server. Run id(s): {9041732}
[2018-04-11 21:45:13] Started run 352 on task 146197, dataset 'dna'.
[2018-04-11 21:45:16] Error in run 345: Run already exists in server. Run id(s): {9041795}
[2018-04-11 21:45:16] Started run 353 on task 146197, dataset 'dna'.
[2018-04-11 21:45:16] Error in run 346: Run already exists in server. Run id(s): {9041719}
[2018-04-11 21:45:16] Started run 354 on task 146197, dataset 'dna'.
[2018-04-11 21:45:17] Error in run 347: Run already exists in server. Run id(s): {9041805}
[2018-04-11 21:45:17] Started run 355 on task 146197, dataset 'dna'.
[2018-04-11 21:45:17] Error in run 348: Run already exists in server. Run id(s): {9041681}
[2018-04-11 21:45:17] Started run 356 on task 146197, dataset 'dna'.
[2018-04-11 21:45:17] Error in run 349: Run already exists in server. Run id(s): {9042009}
[2018-04-11 21:45:17] Started run 357 on task 146197, dataset 'dna'.
[2018-04-11 21:45:18] Error in run 350: Run already exists in server. Run id(s): {9041887}
[2018-04-11 21:45:18] Started run 358 on task 146197, dataset 'dna'.
[2018-04-11 21:45:18] Error in run 351: Run already exists in server. Run id(s): {9041947}
[2018-04-11 21:45:18] Started run 359 on task 146197, dataset 'dna'.
[2018-04-11 21:45:18] Error in run 352: Run already exists in server. Run id(s): {9041814}
[2018-04-11 21:45:18] Started run 360 on task 146197, dataset 'dna'.
[2018-04-11 21:45:20] Error in run 353: Run already exists in server. Run id(s): {9042036}
[2018-04-11 21:45:20] Started run 361 on task 146197, dataset 'dna'.
[2018-04-11 21:45:21] Error in run 354: Run already exists in server. Run id(s): {9041905}
[2018-04-11 21:45:21] Started run 362 on task 146197, dataset 'dna'.
[2018-04-11 21:45:22] Error in run 355: Run already exists in server. Run id(s): {9041830}
[2018-04-11 21:45:22] Started run 363 on task 146197, dataset 'dna'.
[2018-04-11 21:45:22] Error in run 356: Run already exists in server. Run id(s): {9042066}
[2018-04-11 21:45:22] Error in run 357: Run already exists in server. Run id(s): {9041984}
[2018-04-11 21:45:22] Started run 364 on task 146197, dataset 'dna'.
[2018-04-11 21:45:22] Started run 365 on task 146197, dataset 'dna'.
[2018-04-11 21:45:22] Error in run 358: Run already exists in server. Run id(s): {9041856}
[2018-04-11 21:45:22] Started run 366 on task 146197, dataset 'dna'.
[2018-04-11 21:45:22] Error in run 359: Run already exists in server. Run id(s): {9041874}
[2018-04-11 21:45:22] Started run 367 on task 146197, dataset 'dna'.
[2018-04-11 21:45:23] Error in run 360: Run already exists in server. Run id(s): {9042087}
[2018-04-11 21:45:23] Started run 368 on task 146197, dataset 'dna'.
[2018-04-11 21:45:25] Error in run 361: Run already exists in server. Run id(s): {9042064}
[2018-04-11 21:45:25] Started run 369 on task 146197, dataset 'dna'.
[2018-04-11 21:45:26] Error in run 362: Run already exists in server. Run id(s): {9042147}
[2018-04-11 21:45:26] Started run 370 on task 146197, dataset 'dna'.
[2018-04-11 21:45:26] Error in run 363: Run already exists in server. Run id(s): {9042150}
[2018-04-11 21:45:26] Started run 371 on task 146197, dataset 'dna'.
[2018-04-11 21:45:27] Error in run 364: Run already exists in server. Run id(s): {9042218}
[2018-04-11 21:45:27] Error in run 365: Run already exists in server. Run id(s): {9042320}
[2018-04-11 21:45:27] Error in run 366: Run already exists in server. Run id(s): {9042162}
[2018-04-11 21:45:27] Started run 372 on task 146197, dataset 'dna'.
[2018-04-11 21:45:27] Started run 373 on task 146197, dataset 'dna'.
[2018-04-11 21:45:27] Error in run 367: Run already exists in server. Run id(s): {9042302}
[2018-04-11 21:45:27] Started run 374 on task 146197, dataset 'dna'.
[2018-04-11 21:45:27] Started run 375 on task 146197, dataset 'dna'.
[2018-04-11 21:45:28] Error in run 368: Run already exists in server. Run id(s): {9042128}
[2018-04-11 21:45:28] Started run 376 on task 146197, dataset 'dna'.
[2018-04-11 21:45:30] Error in run 369: Run already exists in server. Run id(s): {9042207}
[2018-04-11 21:45:30] Started run 377 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Error in run 371: Run already exists in server. Run id(s): {9042338}
[2018-04-11 21:45:31] Error in run 370: Run already exists in server. Run id(s): {9042295}
[2018-04-11 21:45:31] Started run 378 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Started run 379 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Error in run 372: Run already exists in server. Run id(s): {9042287}
[2018-04-11 21:45:31] Error in run 373: Run already exists in server. Run id(s): {9042468}
[2018-04-11 21:45:31] Started run 380 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Error in run 374: Run already exists in server. Run id(s): {9042443}
[2018-04-11 21:45:31] Error in run 375: Run already exists in server. Run id(s): {9042267}
[2018-04-11 21:45:31] Started run 382 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Started run 383 on task 146197, dataset 'dna'.
[2018-04-11 21:45:31] Started run 381 on task 146197, dataset 'dna'.
[2018-04-11 21:45:32] Error in run 376: Run already exists in server. Run id(s): {9042419}
[2018-04-11 21:45:32] Started run 384 on task 146197, dataset 'dna'.
[2018-04-11 21:45:35] Error in run 377: Run already exists in server. Run id(s): {9042485}
[2018-04-11 21:45:35] Started run 385 on task 146197, dataset 'dna'.
[2018-04-11 21:45:35] Error in run 378: Run already exists in server. Run id(s): {9042455}
[2018-04-11 21:45:35] Error in run 379: Run already exists in server. Run id(s): {9042396}
[2018-04-11 21:45:35] Started run 386 on task 146197, dataset 'dna'.
[2018-04-11 21:45:35] Started run 387 on task 146197, dataset 'dna'.
[2018-04-11 21:45:36] Error in run 383: Run already exists in server. Run id(s): {9042487}
[2018-04-11 21:45:36] Error in run 382: Run already exists in server. Run id(s): {9042536}
[2018-04-11 21:45:36] Error in run 380: Run already exists in server. Run id(s): {9042622}
[2018-04-11 21:45:36] Error in run 381: Run already exists in server. Run id(s): {9042450}
[2018-04-11 21:45:36] Started run 388 on task 146197, dataset 'dna'.
[2018-04-11 21:45:36] Started run 390 on task 146197, dataset 'dna'.
[2018-04-11 21:45:36] Started run 389 on task 146197, dataset 'dna'.
[2018-04-11 21:45:36] Started run 391 on task 146197, dataset 'dna'.
[2018-04-11 21:45:37] Error in run 384: Run already exists in server. Run id(s): {9042675}
[2018-04-11 21:45:37] Started run 392 on task 146197, dataset 'dna'.
[2018-04-11 21:45:39] Error in run 385: Run already exists in server. Run id(s): {9042549}
[2018-04-11 21:45:39] Started run 393 on task 146197, dataset 'dna'.
[2018-04-11 21:45:40] Error in run 386: Run already exists in server. Run id(s): {9042524}
[2018-04-11 21:45:40] Error in run 387: Run already exists in server. Run id(s): {9042609}
[2018-04-11 21:45:40] Started run 394 on task 146197, dataset 'dna'.
[2018-04-11 21:45:40] Started run 395 on task 146197, dataset 'dna'.
[2018-04-11 21:45:41] Error in run 389: Run already exists in server. Run id(s): {9042533}
[2018-04-11 21:45:41] Error in run 391: Run already exists in server. Run id(s): {9042696}
[2018-04-11 21:45:41] Error in run 388: Run already exists in server. Run id(s): {9042633}
[2018-04-11 21:45:41] Error in run 390: Run already exists in server. Run id(s): {9042627}
[2018-04-11 21:45:41] Started run 396 on task 146197, dataset 'dna'.
[2018-04-11 21:45:41] Started run 398 on task 146197, dataset 'dna'.
[2018-04-11 21:45:41] Started run 399 on task 146197, dataset 'dna'.
[2018-04-11 21:45:41] Started run 397 on task 146197, dataset 'dna'.
[2018-04-11 21:45:42] Error in run 392: Run already exists in server. Run id(s): {9042579}
[2018-04-11 21:45:42] Started run 400 on task 146197, dataset 'dna'.
[2018-04-11 21:45:44] Error in run 393: Run already exists in server. Run id(s): {9042573}
[2018-04-11 21:45:44] Started run 401 on task 146197, dataset 'dna'.
[2018-04-11 21:45:45] Error in run 394: Run already exists in server. Run id(s): {9042723}
[2018-04-11 21:45:45] Started run 402 on task 146197, dataset 'dna'.
[2018-04-11 21:45:45] Error in run 395: Run already exists in server. Run id(s): {9042695}
[2018-04-11 21:45:45] Started run 403 on task 146197, dataset 'dna'.
[2018-04-11 21:45:46] Error in run 398: Run already exists in server. Run id(s): {9042738}
[2018-04-11 21:45:46] Error in run 399: Run already exists in server. Run id(s): {9042787}
[2018-04-11 21:45:46] Error in run 397: Run already exists in server. Run id(s): {9042653}
[2018-04-11 21:45:46] Error in run 396: Run already exists in server. Run id(s): {9042756}
[2018-04-11 21:45:46] Started run 404 on task 146197, dataset 'dna'.
[2018-04-11 21:45:46] Started run 405 on task 146197, dataset 'dna'.
[2018-04-11 21:45:46] Started run 406 on task 146197, dataset 'dna'.
[2018-04-11 21:45:46] Started run 407 on task 146197, dataset 'dna'.
[2018-04-11 21:45:47] Error in run 400: Run already exists in server. Run id(s): {9042959}
[2018-04-11 21:45:47] Started run 408 on task 146197, dataset 'dna'.
[2018-04-11 21:45:48] Error in run 401: Run already exists in server. Run id(s): {9042846}
[2018-04-11 21:45:48] Started run 409 on task 146197, dataset 'dna'.
[2018-04-11 21:45:49] Error in run 402: Run already exists in server. Run id(s): {9042991}
[2018-04-11 21:45:49] Started run 410 on task 146197, dataset 'dna'.
[2018-04-11 21:45:50] Error in run 403: Run already exists in server. Run id(s): {9043012}
[2018-04-11 21:45:50] Started run 411 on task 146197, dataset 'dna'.
[2018-04-11 21:45:50] Error in run 404: Run already exists in server. Run id(s): {9042742}
[2018-04-11 21:45:50] Started run 412 on task 146197, dataset 'dna'.
[2018-04-11 21:45:50] Error in run 407: Run already exists in server. Run id(s): {9042851}
[2018-04-11 21:45:50] Error in run 405: Run already exists in server. Run id(s): {9042976}
[2018-04-11 21:45:50] Error in run 406: Run already exists in server. Run id(s): {9042782}
[2018-04-11 21:45:50] Started run 413 on task 146197, dataset 'dna'.
[2018-04-11 21:45:50] Started run 414 on task 146197, dataset 'dna'.
[2018-04-11 21:45:50] Started run 415 on task 146197, dataset 'dna'.
[2018-04-11 21:45:51] Error in run 408: Run already exists in server. Run id(s): {9042906}
[2018-04-11 21:45:51] Started run 416 on task 146197, dataset 'dna'.
[2018-04-11 21:45:53] Error in run 409: Run already exists in server. Run id(s): {9043022}
[2018-04-11 21:45:53] Started run 417 on task 146197, dataset 'dna'.
[2018-04-11 21:45:54] Error in run 410: Run already exists in server. Run id(s): {9042974}
[2018-04-11 21:45:54] Started run 418 on task 146197, dataset 'dna'.
[2018-04-11 21:45:54] Error in run 411: Run already exists in server. Run id(s): {9042949}
[2018-04-11 21:45:54] Started run 419 on task 146197, dataset 'dna'.
[2018-04-11 21:45:55] Error in run 412: Run already exists in server. Run id(s): {9043082}
[2018-04-11 21:45:55] Started run 420 on task 146197, dataset 'dna'.
[2018-04-11 21:45:55] Error in run 415: Run already exists in server. Run id(s): {9043005}
[2018-04-11 21:45:55] Error in run 414: Run already exists in server. Run id(s): {9043098}
[2018-04-11 21:45:55] Error in run 413: Run already exists in server. Run id(s): {9042973}
[2018-04-11 21:45:55] Started run 421 on task 146197, dataset 'dna'.
[2018-04-11 21:45:55] Started run 423 on task 146197, dataset 'dna'.
[2018-04-11 21:45:55] Started run 422 on task 146197, dataset 'dna'.
[2018-04-11 21:45:56] Error in run 416: Run already exists in server. Run id(s): {9043055}
[2018-04-11 21:45:56] Started run 424 on task 146197, dataset 'dna'.
[2018-04-11 21:45:58] Error in run 417: Run already exists in server. Run id(s): {9043033}
[2018-04-11 21:45:58] Started run 425 on task 146197, dataset 'dna'.
[2018-04-11 21:45:58] Error in run 418: Run already exists in server. Run id(s): {9043188}
[2018-04-11 21:45:58] Started run 426 on task 146197, dataset 'dna'.
[2018-04-11 21:45:59] Error in run 419: Run already exists in server. Run id(s): {9043049}
[2018-04-11 21:45:59] Started run 427 on task 146197, dataset 'dna'.
[2018-04-11 21:45:59] Error in run 420: Run already exists in server. Run id(s): {9043242}
[2018-04-11 21:45:59] Started run 428 on task 146197, dataset 'dna'.
[2018-04-11 21:46:00] Error in run 421: Run already exists in server. Run id(s): {9043198}
[2018-04-11 21:46:00] Started run 429 on task 146197, dataset 'dna'.
[2018-04-11 21:46:00] Error in run 422: Run already exists in server. Run id(s): {9043148}
[2018-04-11 21:46:00] Error in run 424: Run already exists in server. Run id(s): {9043218}
[2018-04-11 21:46:00] Error in run 423: Run already exists in server. Run id(s): {9043157}
[2018-04-11 21:46:00] Started run 430 on task 146197, dataset 'dna'.
[2018-04-11 21:46:00] Started run 431 on task 146197, dataset 'dna'.
[2018-04-11 21:46:00] Started run 432 on task 146197, dataset 'dna'.
[2018-04-11 21:46:02] Error in run 425: Run already exists in server. Run id(s): {9043177}
[2018-04-11 21:46:02] Started run 433 on task 146197, dataset 'dna'.
[2018-04-11 21:46:03] Error in run 426: Run already exists in server. Run id(s): {9043248}
[2018-04-11 21:46:03] Started run 434 on task 146197, dataset 'dna'.
[2018-04-11 21:46:03] Error in run 427: Run already exists in server. Run id(s): {9043414}
[2018-04-11 21:46:03] Started run 435 on task 146197, dataset 'dna'.
[2018-04-11 21:46:04] Error in run 428: Run already exists in server. Run id(s): {9043321}
[2018-04-11 21:46:04] Started run 436 on task 146197, dataset 'dna'.
[2018-04-11 21:46:04] Error in run 429: Run already exists in server. Run id(s): {9043285}
[2018-04-11 21:46:04] Started run 437 on task 146197, dataset 'dna'.
[2018-04-11 21:46:04] Error in run 430: Run already exists in server. Run id(s): {9043268}
[2018-04-11 21:46:04] Started run 438 on task 146197, dataset 'dna'.
[2018-04-11 21:46:05] Error in run 431: Run already exists in server. Run id(s): {9043259}
[2018-04-11 21:46:05] Started run 439 on task 146197, dataset 'dna'.
[2018-04-11 21:46:05] Error in run 432: Run already exists in server. Run id(s): {9043474}
[2018-04-11 21:46:05] Started run 440 on task 146197, dataset 'dna'.
[2018-04-11 21:46:07] Error in run 433: Run already exists in server. Run id(s): {9043339}
[2018-04-11 21:46:07] Started run 441 on task 146197, dataset 'dna'.
[2018-04-11 21:46:07] Error in run 434: Run already exists in server. Run id(s): {9043344}
[2018-04-11 21:46:07] Started run 442 on task 146197, dataset 'dna'.
[2018-04-11 21:46:08] Error in run 435: Run already exists in server. Run id(s): {9043505}
[2018-04-11 21:46:08] Started run 443 on task 146197, dataset 'dna'.
[2018-04-11 21:46:09] Error in run 436: Run already exists in server. Run id(s): {9043403}
[2018-04-11 21:46:09] Started run 444 on task 146197, dataset 'dna'.
[2018-04-11 21:46:09] Error in run 437: Run already exists in server. Run id(s): {9043469}
[2018-04-11 21:46:09] Started run 445 on task 146197, dataset 'dna'.
[2018-04-11 21:46:09] Error in run 438: Run already exists in server. Run id(s): {9043511}
[2018-04-11 21:46:09] Started run 446 on task 146197, dataset 'dna'.
[2018-04-11 21:46:09] Error in run 439: Run already exists in server. Run id(s): {9043426}
[2018-04-11 21:46:09] Started run 447 on task 146197, dataset 'dna'.
[2018-04-11 21:46:10] Error in run 440: Run already exists in server. Run id(s): {9043503}
[2018-04-11 21:46:10] Started run 448 on task 146197, dataset 'dna'.
[2018-04-11 21:46:11] Error in run 441: Run already exists in server. Run id(s): {9043500}
[2018-04-11 21:46:11] Started run 449 on task 146197, dataset 'dna'.
[2018-04-11 21:46:12] Error in run 442: Run already exists in server. Run id(s): {9043583}
[2018-04-11 21:46:12] Started run 450 on task 146197, dataset 'dna'.
[2018-04-11 21:46:12] Error in run 443: Run already exists in server. Run id(s): {9043705}
[2018-04-11 21:46:12] Started run 451 on task 146197, dataset 'dna'.
[2018-04-11 21:46:13] Error in run 444: Run already exists in server. Run id(s): {9043568}
[2018-04-11 21:46:13] Started run 452 on task 146197, dataset 'dna'.
[2018-04-11 21:46:13] Error in run 445: Run already exists in server. Run id(s): {9043720}
[2018-04-11 21:46:13] Error in run 446: Run already exists in server. Run id(s): {9043667}
[2018-04-11 21:46:13] Started run 453 on task 146197, dataset 'dna'.
[2018-04-11 21:46:13] Started run 454 on task 146197, dataset 'dna'.
[2018-04-11 21:46:14] Error in run 447: Run already exists in server. Run id(s): {9043777}
[2018-04-11 21:46:14] Started run 455 on task 146197, dataset 'dna'.
[2018-04-11 21:46:14] Error in run 448: Run already exists in server. Run id(s): {9043736}
[2018-04-11 21:46:14] Started run 456 on task 146197, dataset 'dna'.
[2018-04-11 21:46:16] Error in run 449: Run already exists in server. Run id(s): {9043581}
[2018-04-11 21:46:16] Started run 457 on task 146197, dataset 'dna'.
[2018-04-11 21:46:17] Error in run 451: Run already exists in server. Run id(s): {9043747}
[2018-04-11 21:46:17] Error in run 450: Run already exists in server. Run id(s): {9043664}
[2018-04-11 21:46:17] Started run 458 on task 146197, dataset 'dna'.
[2018-04-11 21:46:17] Started run 459 on task 146197, dataset 'dna'.
[2018-04-11 21:46:18] Error in run 452: Run already exists in server. Run id(s): {9043644}
[2018-04-11 21:46:18] Started run 460 on task 146197, dataset 'dna'.
[2018-04-11 21:46:18] Error in run 453: Run already exists in server. Run id(s): {9043783}
[2018-04-11 21:46:18] Started run 461 on task 146197, dataset 'dna'.
[2018-04-11 21:46:18] Error in run 454: Run already exists in server. Run id(s): {9043751}
[2018-04-11 21:46:18] Error in run 455: Run already exists in server. Run id(s): {9043864}
[2018-04-11 21:46:18] Started run 462 on task 146197, dataset 'dna'.
[2018-04-11 21:46:18] Started run 463 on task 146197, dataset 'dna'.
[2018-04-11 21:46:19] Error in run 456: Run already exists in server. Run id(s): {9043955}
[2018-04-11 21:46:19] Started run 464 on task 146197, dataset 'dna'.
[2018-04-11 21:46:20] Error in run 457: Run already exists in server. Run id(s): {9043915}
[2018-04-11 21:46:20] Started run 465 on task 146197, dataset 'dna'.
[2018-04-11 21:46:21] Error in run 459: Run already exists in server. Run id(s): {9044047}
[2018-04-11 21:46:21] Started run 466 on task 146197, dataset 'dna'.
[2018-04-11 21:46:21] Error in run 458: Run already exists in server. Run id(s): {9043760}
[2018-04-11 21:46:21] Started run 467 on task 146197, dataset 'dna'.
[2018-04-11 21:46:22] Error in run 460: Run already exists in server. Run id(s): {9043956}
[2018-04-11 21:46:22] Started run 468 on task 146197, dataset 'dna'.
[2018-04-11 21:46:23] Error in run 461: Run already exists in server. Run id(s): {9043823}
[2018-04-11 21:46:23] Started run 469 on task 146197, dataset 'dna'.
[2018-04-11 21:46:23] Error in run 462: Run already exists in server. Run id(s): {9043853}
[2018-04-11 21:46:23] Started run 470 on task 146197, dataset 'dna'.
[2018-04-11 21:46:23] Error in run 463: Run already exists in server. Run id(s): {9043950}
[2018-04-11 21:46:23] Started run 471 on task 146197, dataset 'dna'.
[2018-04-11 21:46:23] Error in run 464: Run already exists in server. Run id(s): {9043869}
[2018-04-11 21:46:23] Started run 472 on task 146197, dataset 'dna'.
[2018-04-11 21:46:25] Error in run 465: Run already exists in server. Run id(s): {9043972}
[2018-04-11 21:46:25] Started run 473 on task 146197, dataset 'dna'.
[2018-04-11 21:46:26] Error in run 466: Run already exists in server. Run id(s): {9043942}
[2018-04-11 21:46:26] Started run 474 on task 146197, dataset 'dna'.
[2018-04-11 21:46:26] Error in run 467: Run already exists in server. Run id(s): {9043966}
[2018-04-11 21:46:26] Started run 475 on task 146197, dataset 'dna'.
[2018-04-11 21:46:27] Error in run 468: Run already exists in server. Run id(s): {9044179}
[2018-04-11 21:46:27] Error in run 469: Run already exists in server. Run id(s): {9044123}
[2018-04-11 21:46:27] Started run 476 on task 146197, dataset 'dna'.
[2018-04-11 21:46:27] Started run 477 on task 146197, dataset 'dna'.
[2018-04-11 21:46:28] Error in run 471: Run already exists in server. Run id(s): {9044055}
[2018-04-11 21:46:28] Started run 478 on task 146197, dataset 'dna'.
[2018-04-11 21:46:28] Error in run 470: Run already exists in server. Run id(s): {9044136}
[2018-04-11 21:46:28] Error in run 472: Run already exists in server. Run id(s): {9044191}
[2018-04-11 21:46:28] Started run 479 on task 146197, dataset 'dna'.
[2018-04-11 21:46:28] Started run 480 on task 146197, dataset 'dna'.
[2018-04-11 21:46:29] Error in run 473: Run already exists in server. Run id(s): {9044129}
[2018-04-11 21:46:29] Started run 481 on task 146197, dataset 'dna'.
[2018-04-11 21:46:30] Error in run 474: Run already exists in server. Run id(s): {9044160}
[2018-04-11 21:46:30] Started run 482 on task 146197, dataset 'dna'.
[2018-04-11 21:46:31] Error in run 475: Run already exists in server. Run id(s): {9044106}
[2018-04-11 21:46:31] Started run 483 on task 146197, dataset 'dna'.
[2018-04-11 21:46:32] Error in run 477: Run already exists in server. Run id(s): {9044141}
[2018-04-11 21:46:32] Started run 484 on task 146197, dataset 'dna'.
[2018-04-11 21:46:32] Error in run 476: Run already exists in server. Run id(s): {9044359}
[2018-04-11 21:46:32] Started run 485 on task 146197, dataset 'dna'.
[2018-04-11 21:46:32] Error in run 478: Run already exists in server. Run id(s): {9044426}
[2018-04-11 21:46:32] Started run 486 on task 146197, dataset 'dna'.
[2018-04-11 21:46:33] Error in run 479: Run already exists in server. Run id(s): {9044274}
[2018-04-11 21:46:33] Error in run 480: Run already exists in server. Run id(s): {9044308}
[2018-04-11 21:46:33] Started run 487 on task 146197, dataset 'dna'.
[2018-04-11 21:46:33] Started run 488 on task 146197, dataset 'dna'.
[2018-04-11 21:46:34] Error in run 481: Run already exists in server. Run id(s): {9044216}
[2018-04-11 21:46:34] Started run 489 on task 146197, dataset 'dna'.
[2018-04-11 21:46:35] Error in run 482: Run already exists in server. Run id(s): {9044342}
[2018-04-11 21:46:35] Started run 490 on task 146197, dataset 'dna'.
[2018-04-11 21:46:36] Error in run 483: Run already exists in server. Run id(s): {9044232}
[2018-04-11 21:46:36] Started run 491 on task 146197, dataset 'dna'.
[2018-04-11 21:46:37] Error in run 485: Run already exists in server. Run id(s): {9044276}
[2018-04-11 21:46:37] Error in run 484: Run already exists in server. Run id(s): {9044393}
[2018-04-11 21:46:37] Started run 492 on task 146197, dataset 'dna'.
[2018-04-11 21:46:37] Started run 493 on task 146197, dataset 'dna'.
[2018-04-11 21:46:37] Error in run 486: Run already exists in server. Run id(s): {9044260}
[2018-04-11 21:46:37] Started run 494 on task 146197, dataset 'dna'.
[2018-04-11 21:46:37] Error in run 487: Run already exists in server. Run id(s): {9044332}
[2018-04-11 21:46:37] Error in run 488: Run already exists in server. Run id(s): {9044425}
[2018-04-11 21:46:37] Started run 495 on task 146197, dataset 'dna'.
[2018-04-11 21:46:37] Started run 496 on task 146197, dataset 'dna'.
[2018-04-11 21:46:39] Error in run 489: Run already exists in server. Run id(s): {9044380}
[2018-04-11 21:46:39] Started run 497 on task 146197, dataset 'dna'.
[2018-04-11 21:46:40] Error in run 490: Run already exists in server. Run id(s): {9044483}
[2018-04-11 21:46:40] Started run 498 on task 146197, dataset 'dna'.
[2018-04-11 21:46:41] Error in run 491: Run already exists in server. Run id(s): {9044564}
[2018-04-11 21:46:41] Started run 499 on task 146197, dataset 'dna'.
[2018-04-11 21:46:41] Error in run 494: Run already exists in server. Run id(s): {9044509}
[2018-04-11 21:46:41] Error in run 492: Run already exists in server. Run id(s): {9044532}
[2018-04-11 21:46:41] Error in run 493: Run already exists in server. Run id(s): {9044474}
[2018-04-11 21:46:41] Started run 500 on task 146197, dataset 'dna'.
[2018-04-11 21:46:41] Started run 501 on task 146197, dataset 'dna'.
[2018-04-11 21:46:41] Started run 502 on task 146197, dataset 'dna'.
[2018-04-11 21:46:42] Error in run 495: Run already exists in server. Run id(s): {9044641}
[2018-04-11 21:46:42] Error in run 496: Run already exists in server. Run id(s): {9044504}
[2018-04-11 21:46:42] Started run 503 on task 146197, dataset 'dna'.
[2018-04-11 21:46:42] Started run 504 on task 146197, dataset 'dna'.
[2018-04-11 21:46:44] Error in run 497: Run already exists in server. Run id(s): {9044487}
[2018-04-11 21:46:44] Started run 505 on task 146197, dataset 'dna'.
[2018-04-11 21:46:44] Error in run 498: Run already exists in server. Run id(s): {9044576}
[2018-04-11 21:46:44] Started run 506 on task 146197, dataset 'dna'.
[2018-04-11 21:46:45] Error in run 499: Run already exists in server. Run id(s): {9044571}
[2018-04-11 21:46:45] Started run 507 on task 146197, dataset 'dna'.
[2018-04-11 21:46:46] Error in run 501: Run already exists in server. Run id(s): {9044693, 9044702}
[2018-04-11 21:46:46] Error in run 500: Run already exists in server. Run id(s): {9044699}
[2018-04-11 21:46:46] Error in run 502: Run already exists in server. Run id(s): {9044602}
[2018-04-11 21:46:46] Started run 508 on task 146197, dataset 'dna'.
[2018-04-11 21:46:46] Started run 510 on task 146197, dataset 'dna'.
[2018-04-11 21:46:46] Started run 509 on task 146197, dataset 'dna'.
[2018-04-11 21:46:47] Error in run 503: Run already exists in server. Run id(s): {9044646}
[2018-04-11 21:46:47] Error in run 504: Run already exists in server. Run id(s): {9044876}
[2018-04-11 21:46:47] Started run 511 on task 146197, dataset 'dna'.
[2018-04-11 21:46:47] Started run 512 on task 146197, dataset 'dna'.
[2018-04-11 21:46:48] Error in run 505: Run already exists in server. Run id(s): {9044698}
[2018-04-11 21:46:48] Started run 513 on task 146197, dataset 'dna'.
[2018-04-11 21:46:49] Error in run 506: Run already exists in server. Run id(s): {9044720}
[2018-04-11 21:46:49] Started run 514 on task 146197, dataset 'dna'.
[2018-04-11 21:46:50] Error in run 507: Run already exists in server. Run id(s): {9044715}
[2018-04-11 21:46:50] Started run 515 on task 146197, dataset 'dna'.
[2018-04-11 21:46:51] Error in run 510: Run already exists in server. Run id(s): {9044858}
[2018-04-11 21:46:51] Error in run 509: Run already exists in server. Run id(s): {9044881}
[2018-04-11 21:46:51] Error in run 508: Run already exists in server. Run id(s): {9044773}
[2018-04-11 21:46:51] Started run 516 on task 146197, dataset 'dna'.
[2018-04-11 21:46:51] Started run 517 on task 146197, dataset 'dna'.
[2018-04-11 21:46:51] Started run 518 on task 146197, dataset 'dna'.
[2018-04-11 21:46:52] Error in run 512: Run already exists in server. Run id(s): {9044850}
[2018-04-11 21:46:52] Error in run 511: Run already exists in server. Run id(s): {9044733}
[2018-04-11 21:46:52] Started run 519 on task 146197, dataset 'dna'.
[2018-04-11 21:46:52] Started run 520 on task 146197, dataset 'dna'.
[2018-04-11 21:46:53] Error in run 513: Run already exists in server. Run id(s): {9045030}
[2018-04-11 21:46:53] Started run 521 on task 146197, dataset 'dna'.
[2018-04-11 21:46:54] Error in run 514: Run already exists in server. Run id(s): {9044849}
[2018-04-11 21:46:54] Started run 522 on task 146197, dataset 'dna'.
[2018-04-11 21:46:55] Error in run 515: Run already exists in server. Run id(s): {9044920}
[2018-04-11 21:46:55] Started run 523 on task 146197, dataset 'dna'.
[2018-04-11 21:46:55] Error in run 516: Run already exists in server. Run id(s): {9044936}
[2018-04-11 21:46:55] Started run 524 on task 146197, dataset 'dna'.
[2018-04-11 21:46:56] Error in run 518: Run already exists in server. Run id(s): {9045044}
[2018-04-11 21:46:56] Error in run 517: Run already exists in server. Run id(s): {9045087}
[2018-04-11 21:46:56] Started run 525 on task 146197, dataset 'dna'.
[2018-04-11 21:46:56] Started run 526 on task 146197, dataset 'dna'.
[2018-04-11 21:46:56] Error in run 520: Run already exists in server. Run id(s): {9044912}
[2018-04-11 21:46:56] Error in run 519: Run already exists in server. Run id(s): {9044962}
[2018-04-11 21:46:56] Started run 527 on task 146197, dataset 'dna'.
[2018-04-11 21:46:56] Started run 528 on task 146197, dataset 'dna'.
[2018-04-11 21:46:58] Error in run 521: Run already exists in server. Run id(s): {9045042}
[2018-04-11 21:46:58] Started run 529 on task 146197, dataset 'dna'.
[2018-04-11 21:46:59] Error in run 522: Run already exists in server. Run id(s): {9045089}
[2018-04-11 21:46:59] Started run 530 on task 146197, dataset 'dna'.
[2018-04-11 21:46:59] Error in run 523: Run already exists in server. Run id(s): {9045151}
[2018-04-11 21:46:59] Started run 531 on task 146197, dataset 'dna'.
[2018-04-11 21:47:00] Error in run 524: Run already exists in server. Run id(s): {9045152}
[2018-04-11 21:47:00] Started run 532 on task 146197, dataset 'dna'.
[2018-04-11 21:47:00] Error in run 525: Run already exists in server. Run id(s): {9045008}
[2018-04-11 21:47:00] Error in run 526: Run already exists in server. Run id(s): {9045055}
[2018-04-11 21:47:00] Started run 533 on task 146197, dataset 'dna'.
[2018-04-11 21:47:00] Started run 534 on task 146197, dataset 'dna'.
[2018-04-11 21:47:01] Error in run 527: Run already exists in server. Run id(s): {9045316}
[2018-04-11 21:47:01] Started run 535 on task 146197, dataset 'dna'.
[2018-04-11 21:47:01] Error in run 528: Run already exists in server. Run id(s): {9045229}
[2018-04-11 21:47:01] Started run 536 on task 146197, dataset 'dna'.
[2018-04-11 21:47:03] Error in run 529: Run already exists in server. Run id(s): {9045307}
[2018-04-11 21:47:03] Started run 537 on task 146197, dataset 'dna'.
[2018-04-11 21:47:04] Error in run 530: Run already exists in server. Run id(s): {9045108}
[2018-04-11 21:47:04] Started run 538 on task 146197, dataset 'dna'.
[2018-04-11 21:47:04] Error in run 531: Run already exists in server. Run id(s): {9045339}
[2018-04-11 21:47:04] Started run 539 on task 146197, dataset 'dna'.
[2018-04-11 21:47:04] Error in run 532: Run already exists in server. Run id(s): {9045161}
[2018-04-11 21:47:04] Started run 540 on task 146197, dataset 'dna'.
[2018-04-11 21:47:05] Error in run 534: Run already exists in server. Run id(s): {9045204}
[2018-04-11 21:47:05] Error in run 533: Run already exists in server. Run id(s): {9045141}
[2018-04-11 21:47:05] Started run 541 on task 146197, dataset 'dna'.
[2018-04-11 21:47:05] Started run 542 on task 146197, dataset 'dna'.
[2018-04-11 21:47:05] Error in run 535: Run already exists in server. Run id(s): {9045331}
[2018-04-11 21:47:05] Started run 543 on task 146197, dataset 'dna'.
[2018-04-11 21:47:06] Error in run 536: Run already exists in server. Run id(s): {9045234}
[2018-04-11 21:47:06] Started run 544 on task 146197, dataset 'dna'.
[2018-04-11 21:47:07] Error in run 537: Run already exists in server. Run id(s): {9045209}
[2018-04-11 21:47:07] Started run 545 on task 146197, dataset 'dna'.
[2018-04-11 21:47:08] Error in run 538: Run already exists in server. Run id(s): {9045341}
[2018-04-11 21:47:08] Error in run 539: Run already exists in server. Run id(s): {9045317}
[2018-04-11 21:47:08] Started run 546 on task 146197, dataset 'dna'.
[2018-04-11 21:47:08] Started run 547 on task 146197, dataset 'dna'.
[2018-04-11 21:47:09] Error in run 540: Run already exists in server. Run id(s): {9045267}
[2018-04-11 21:47:09] Started run 548 on task 146197, dataset 'dna'.
[2018-04-11 21:47:10] Error in run 542: Run already exists in server. Run id(s): {9045450}
[2018-04-11 21:47:10] Error in run 541: Run already exists in server. Run id(s): {9045438}
[2018-04-11 21:47:10] Started run 549 on task 146197, dataset 'dna'.
[2018-04-11 21:47:10] Error in run 543: Run already exists in server. Run id(s): {9045408}
[2018-04-11 21:47:10] Started run 551 on task 146197, dataset 'dna'.
[2018-04-11 21:47:10] Started run 550 on task 146197, dataset 'dna'.
[2018-04-11 21:47:11] Error in run 544: Run already exists in server. Run id(s): {9045377}
[2018-04-11 21:47:11] Started run 552 on task 146197, dataset 'dna'.
[2018-04-11 21:47:12] Error in run 545: Run already exists in server. Run id(s): {9045471}
[2018-04-11 21:47:12] Started run 553 on task 146197, dataset 'dna'.
[2018-04-11 21:47:13] Error in run 546: Run already exists in server. Run id(s): {9045434}
[2018-04-11 21:47:13] Error in run 547: Run already exists in server. Run id(s): {9045485}
[2018-04-11 21:47:13] Started run 554 on task 146197, dataset 'dna'.
[2018-04-11 21:47:13] Started run 555 on task 146197, dataset 'dna'.
[2018-04-11 21:47:14] Error in run 548: Run already exists in server. Run id(s): {9045460}
[2018-04-11 21:47:14] Started run 556 on task 146197, dataset 'dna'.
[2018-04-11 21:47:15] Error in run 550: Run already exists in server. Run id(s): {9045424}
[2018-04-11 21:47:15] Error in run 549: Run already exists in server. Run id(s): {9045452}
[2018-04-11 21:47:15] Error in run 551: Run already exists in server. Run id(s): {9045538}
[2018-04-11 21:47:15] Started run 557 on task 146197, dataset 'dna'.
[2018-04-11 21:47:15] Started run 558 on task 146197, dataset 'dna'.
[2018-04-11 21:47:15] Started run 559 on task 146197, dataset 'dna'.
[2018-04-11 21:47:15] Error in run 552: Run already exists in server. Run id(s): {9045486}
[2018-04-11 21:47:15] Started run 560 on task 146197, dataset 'dna'.
[2018-04-11 21:47:16] Error in run 553: Run already exists in server. Run id(s): {9045454}
[2018-04-11 21:47:16] Started run 561 on task 146197, dataset 'dna'.
[2018-04-11 21:47:18] Error in run 554: Run already exists in server. Run id(s): {9045573}
[2018-04-11 21:47:18] Error in run 555: Run already exists in server. Run id(s): {9045530}
[2018-04-11 21:47:18] Started run 562 on task 146197, dataset 'dna'.
[2018-04-11 21:47:18] Started run 563 on task 146197, dataset 'dna'.
[2018-04-11 21:47:19] Error in run 556: Run already exists in server. Run id(s): {9045491}
[2018-04-11 21:47:19] Started run 564 on task 146197, dataset 'dna'.
[2018-04-11 21:47:19] Error in run 557: Run already exists in server. Run id(s): {9045498}
[2018-04-11 21:47:19] Started run 565 on task 146197, dataset 'dna'.
[2018-04-11 21:47:19] Error in run 559: Run already exists in server. Run id(s): {9045609}
[2018-04-11 21:47:19] Error in run 558: Run already exists in server. Run id(s): {9045600}
[2018-04-11 21:47:19] Started run 566 on task 146197, dataset 'dna'.
[2018-04-11 21:47:19] Started run 567 on task 146197, dataset 'dna'.
[2018-04-11 21:47:20] Error in run 560: Run already exists in server. Run id(s): {9045552}
[2018-04-11 21:47:20] Started run 568 on task 146197, dataset 'dna'.
[2018-04-11 21:47:21] Error in run 561: Run already exists in server. Run id(s): {9045518}
[2018-04-11 21:47:21] Started run 569 on task 146197, dataset 'dna'.
[2018-04-11 21:47:23] Error in run 563: Run already exists in server. Run id(s): {9045608}
[2018-04-11 21:47:23] Error in run 562: Run already exists in server. Run id(s): {9045618}
[2018-04-11 21:47:23] Started run 570 on task 146197, dataset 'dna'.
[2018-04-11 21:47:23] Started run 571 on task 146197, dataset 'dna'.
[2018-04-11 21:47:23] Error in run 564: Run already exists in server. Run id(s): {9045643}
[2018-04-11 21:47:23] Started run 572 on task 146197, dataset 'dna'.
[2018-04-11 21:47:24] Error in run 565: Run already exists in server. Run id(s): {9045586}
[2018-04-11 21:47:24] Started run 573 on task 146197, dataset 'dna'.
[2018-04-11 21:47:24] Error in run 567: Run already exists in server. Run id(s): {9045646}
[2018-04-11 21:47:24] Error in run 566: Run already exists in server. Run id(s): {9045629}
[2018-04-11 21:47:24] Started run 574 on task 146197, dataset 'dna'.
[2018-04-11 21:47:24] Started run 575 on task 146197, dataset 'dna'.
[2018-04-11 21:47:25] Error in run 568: Run already exists in server. Run id(s): {9045712}
[2018-04-11 21:47:25] Started run 576 on task 146197, dataset 'dna'.
[2018-04-11 21:47:26] Error in run 569: Run already exists in server. Run id(s): {9045692}
[2018-04-11 21:47:26] Started run 577 on task 146197, dataset 'dna'.
[2018-04-11 21:47:27] Error in run 571: Run already exists in server. Run id(s): {9045743}
[2018-04-11 21:47:27] Error in run 570: Run already exists in server. Run id(s): {9045665}
[2018-04-11 21:47:27] Started run 578 on task 146197, dataset 'dna'.
[2018-04-11 21:47:27] Started run 579 on task 146197, dataset 'dna'.
[2018-04-11 21:47:28] Error in run 572: Run already exists in server. Run id(s): {9045704}
[2018-04-11 21:47:28] Started run 580 on task 146197, dataset 'dna'.
[2018-04-11 21:47:28] Error in run 573: Run already exists in server. Run id(s): {9045801}
[2018-04-11 21:47:28] Started run 581 on task 146197, dataset 'dna'.
[2018-04-11 21:47:29] Error in run 575: Run already exists in server. Run id(s): {9045700}
[2018-04-11 21:47:29] Error in run 574: Run already exists in server. Run id(s): {9045740}
[2018-04-11 21:47:29] Started run 582 on task 146197, dataset 'dna'.
[2018-04-11 21:47:29] Started run 583 on task 146197, dataset 'dna'.
[2018-04-11 21:47:30] Error in run 576: Run already exists in server. Run id(s): {9045711}
[2018-04-11 21:47:30] Started run 584 on task 146197, dataset 'dna'.
[2018-04-11 21:47:31] Error in run 577: Run already exists in server. Run id(s): {9045775}
[2018-04-11 21:47:31] Started run 585 on task 146197, dataset 'dna'.
[2018-04-11 21:47:32] Error in run 578: Run already exists in server. Run id(s): {9045842}
[2018-04-11 21:47:32] Started run 586 on task 146197, dataset 'dna'.
[2018-04-11 21:47:32] Error in run 579: Run already exists in server. Run id(s): {9045763}
[2018-04-11 21:47:32] Started run 587 on task 146197, dataset 'dna'.
[2018-04-11 21:47:32] Error in run 580: Run already exists in server. Run id(s): {9045730}
[2018-04-11 21:47:32] Started run 588 on task 146197, dataset 'dna'.
[2018-04-11 21:47:33] Error in run 581: Run already exists in server. Run id(s): {9045869}
[2018-04-11 21:47:33] Started run 589 on task 146197, dataset 'dna'.
[2018-04-11 21:47:34] Error in run 583: Run already exists in server. Run id(s): {9045804}
[2018-04-11 21:47:34] Error in run 582: Run already exists in server. Run id(s): {9045808}
[2018-04-11 21:47:34] Started run 590 on task 146197, dataset 'dna'.
[2018-04-11 21:47:34] Started run 591 on task 146197, dataset 'dna'.
[2018-04-11 21:47:35] Error in run 584: Run already exists in server. Run id(s): {9045905}
[2018-04-11 21:47:35] Started run 592 on task 146197, dataset 'dna'.
[2018-04-11 21:47:35] Error in run 585: Run already exists in server. Run id(s): {9045850}
[2018-04-11 21:47:35] Started run 593 on task 146197, dataset 'dna'.
[2018-04-11 21:47:37] Error in run 586: Run already exists in server. Run id(s): {9045882}
[2018-04-11 21:47:37] Started run 594 on task 146197, dataset 'dna'.
[2018-04-11 21:47:37] Error in run 588: Run already exists in server. Run id(s): {9045840}
[2018-04-11 21:47:37] Started run 595 on task 146197, dataset 'dna'.
[2018-04-11 21:47:37] Error in run 587: Run already exists in server. Run id(s): {9045946}
[2018-04-11 21:47:37] Started run 596 on task 146197, dataset 'dna'.
[2018-04-11 21:47:38] Error in run 589: Run already exists in server. Run id(s): {9045978}
[2018-04-11 21:47:38] Started run 597 on task 146197, dataset 'dna'.
[2018-04-11 21:47:38] Error in run 590: Run already exists in server. Run id(s): {9046015}
[2018-04-11 21:47:38] Error in run 591: Run already exists in server. Run id(s): {9045928}
[2018-04-11 21:47:38] Started run 598 on task 146197, dataset 'dna'.
[2018-04-11 21:47:38] Started run 599 on task 146197, dataset 'dna'.
[2018-04-11 21:47:39] Error in run 592: Run already exists in server. Run id(s): {9045970}
[2018-04-11 21:47:39] Started run 600 on task 146197, dataset 'dna'.
[2018-04-11 21:47:40] Error in run 593: Run already exists in server. Run id(s): {9045917}
[2018-04-11 21:47:40] Started run 601 on task 146197, dataset 'dna'.
[2018-04-11 21:47:41] Error in run 594: Run already exists in server. Run id(s): {9045925}
[2018-04-11 21:47:41] Started run 602 on task 146197, dataset 'dna'.
[2018-04-11 21:47:41] Error in run 595: Run already exists in server. Run id(s): {9046004}
[2018-04-11 21:47:41] Started run 603 on task 146197, dataset 'dna'.
[2018-04-11 21:47:42] Error in run 596: Run already exists in server. Run id(s): {9045937}
[2018-04-11 21:47:42] Started run 604 on task 146197, dataset 'dna'.
[2018-04-11 21:47:42] Error in run 597: Run already exists in server. Run id(s): {9045961}
[2018-04-11 21:47:42] Started run 605 on task 146197, dataset 'dna'.
[2018-04-11 21:47:43] Error in run 599: Run already exists in server. Run id(s): {9046007}
[2018-04-11 21:47:43] Error in run 598: Run already exists in server. Run id(s): {9045996}
[2018-04-11 21:47:43] Started run 606 on task 146197, dataset 'dna'.
[2018-04-11 21:47:43] Started run 607 on task 146197, dataset 'dna'.
[2018-04-11 21:47:44] Error in run 600: Run already exists in server. Run id(s): {9045950}
[2018-04-11 21:47:44] Started run 608 on task 146197, dataset 'dna'.
[2018-04-11 21:47:44] Error in run 601: Run already exists in server. Run id(s): {9045982}
[2018-04-11 21:47:44] Started run 609 on task 146197, dataset 'dna'.
[2018-04-11 21:47:46] Error in run 602: Run already exists in server. Run id(s): {9046023}
[2018-04-11 21:47:46] Started run 610 on task 146197, dataset 'dna'.
[2018-04-11 21:47:46] Error in run 603: Run already exists in server. Run id(s): {9046000}
[2018-04-11 21:47:46] Started run 611 on task 146197, dataset 'dna'.
[2018-04-11 21:47:47] Error in run 605: Run already exists in server. Run id(s): {9046028}
[2018-04-11 21:47:47] Error in run 604: Run already exists in server. Run id(s): {9046043}
[2018-04-11 21:47:47] Started run 612 on task 146197, dataset 'dna'.
[2018-04-11 21:47:47] Started run 613 on task 146197, dataset 'dna'.
[2018-04-11 21:47:47] Error in run 606: Run already exists in server. Run id(s): {9046081}
[2018-04-11 21:47:47] Error in run 607: Run already exists in server. Run id(s): {9046013}
[2018-04-11 21:47:47] Started run 614 on task 146197, dataset 'dna'.
[2018-04-11 21:47:47] Started run 615 on task 146197, dataset 'dna'.
[2018-04-11 21:47:48] Error in run 608: Run already exists in server. Run id(s): {9046130}
[2018-04-11 21:47:48] Started run 616 on task 146197, dataset 'dna'.
[2018-04-11 21:47:49] Error in run 609: Run already exists in server. Run id(s): {9046107}
[2018-04-11 21:47:49] Started run 617 on task 146197, dataset 'dna'.
[2018-04-11 21:47:50] Error in run 610: Run already exists in server. Run id(s): {9046094}
[2018-04-11 21:47:50] Error in run 611: Run already exists in server. Run id(s): {9046158}
[2018-04-11 21:47:50] Started run 618 on task 146197, dataset 'dna'.
[2018-04-11 21:47:50] Started run 619 on task 146197, dataset 'dna'.
[2018-04-11 21:47:51] Error in run 613: Run already exists in server. Run id(s): {9046110}
[2018-04-11 21:47:51] Error in run 612: Run already exists in server. Run id(s): {9046088}
[2018-04-11 21:47:51] Started run 620 on task 146197, dataset 'dna'.
[2018-04-11 21:47:51] Started run 621 on task 146197, dataset 'dna'.
[2018-04-11 21:47:52] Error in run 614: Run already exists in server. Run id(s): {9046086}
[2018-04-11 21:47:52] Error in run 615: Run already exists in server. Run id(s): {9046102}
[2018-04-11 21:47:52] Started run 622 on task 146197, dataset 'dna'.
[2018-04-11 21:47:52] Started run 623 on task 146197, dataset 'dna'.
[2018-04-11 21:47:53] Error in run 616: Run already exists in server. Run id(s): {9046217}
[2018-04-11 21:47:53] Started run 624 on task 146197, dataset 'dna'.
[2018-04-11 21:47:54] Error in run 617: Run already exists in server. Run id(s): {9046172}
[2018-04-11 21:47:54] Started run 625 on task 146197, dataset 'dna'.
[2018-04-11 21:47:55] Error in run 619: Run already exists in server. Run id(s): {9046190}
[2018-04-11 21:47:55] Error in run 618: Run already exists in server. Run id(s): {9046120}
[2018-04-11 21:47:55] Started run 626 on task 146197, dataset 'dna'.
[2018-04-11 21:47:55] Started run 627 on task 146197, dataset 'dna'.
[2018-04-11 21:47:56] Error in run 621: Run already exists in server. Run id(s): {9046175}
[2018-04-11 21:47:56] Error in run 620: Run already exists in server. Run id(s): {9046179}
[2018-04-11 21:47:56] Started run 628 on task 146197, dataset 'dna'.
[2018-04-11 21:47:56] Started run 629 on task 146197, dataset 'dna'.
[2018-04-11 21:47:57] Error in run 622: Run already exists in server. Run id(s): {9046188}
[2018-04-11 21:47:57] Error in run 623: Run already exists in server. Run id(s): {9046200}
[2018-04-11 21:47:57] Started run 630 on task 146197, dataset 'dna'.
[2018-04-11 21:47:57] Started run 631 on task 146197, dataset 'dna'.
[2018-04-11 21:47:58] Error in run 624: Run already exists in server. Run id(s): {9046235}
[2018-04-11 21:47:58] Started run 632 on task 146197, dataset 'dna'.
[2018-04-11 21:47:58] Error in run 625: Run already exists in server. Run id(s): {9046211}
[2018-04-11 21:47:58] Started run 633 on task 146197, dataset 'dna'.
[2018-04-11 21:48:00] Error in run 626: Run already exists in server. Run id(s): {9046280}
[2018-04-11 21:48:00] Started run 634 on task 146197, dataset 'dna'.
[2018-04-11 21:48:00] Error in run 627: Run already exists in server. Run id(s): {9046203}
[2018-04-11 21:48:00] Started run 635 on task 146197, dataset 'dna'.
[2018-04-11 21:48:00] Error in run 628: Run already exists in server. Run id(s): {9046297}
[2018-04-11 21:48:00] Error in run 629: Run already exists in server. Run id(s): {9046298}
[2018-04-11 21:48:00] Started run 636 on task 146197, dataset 'dna'.
[2018-04-11 21:48:00] Started run 637 on task 146197, dataset 'dna'.
[2018-04-11 21:48:01] Error in run 630: Run already exists in server. Run id(s): {9046324}
[2018-04-11 21:48:01] Error in run 631: Run already exists in server. Run id(s): {9046320}
[2018-04-11 21:48:01] Started run 638 on task 146197, dataset 'dna'.
[2018-04-11 21:48:01] Started run 639 on task 146197, dataset 'dna'.
[2018-04-11 21:48:02] Error in run 632: Run already exists in server. Run id(s): {9046229, 9046239}
[2018-04-11 21:48:02] Started run 640 on task 146197, dataset 'dna'.
[2018-04-11 21:48:03] Error in run 633: Run already exists in server. Run id(s): {9046287}
[2018-04-11 21:48:03] Started run 641 on task 146197, dataset 'dna'.
[2018-04-11 21:48:04] Error in run 634: Run already exists in server. Run id(s): {9046403}
[2018-04-11 21:48:04] Started run 642 on task 146197, dataset 'dna'.
[2018-04-11 21:48:04] Error in run 635: Run already exists in server. Run id(s): {9046341}
[2018-04-11 21:48:04] Started run 643 on task 146197, dataset 'dna'.
[2018-04-11 21:48:05] Error in run 636: Run already exists in server. Run id(s): {9046300}
[2018-04-11 21:48:05] Error in run 637: Run already exists in server. Run id(s): {9046333}
[2018-04-11 21:48:05] Started run 644 on task 146197, dataset 'dna'.
[2018-04-11 21:48:05] Started run 645 on task 146197, dataset 'dna'.
[2018-04-11 21:48:06] Error in run 638: Run already exists in server. Run id(s): {9046350}
[2018-04-11 21:48:06] Started run 646 on task 146197, dataset 'dna'.
[2018-04-11 21:48:06] Error in run 639: Run already exists in server. Run id(s): {9046368}
[2018-04-11 21:48:06] Started run 647 on task 146197, dataset 'dna'.
[2018-04-11 21:48:06] Error in run 640: Run already exists in server. Run id(s): {9046392}
[2018-04-11 21:48:06] Started run 648 on task 146197, dataset 'dna'.
[2018-04-11 21:48:07] Error in run 641: Run already exists in server. Run id(s): {9046415}
[2018-04-11 21:48:07] Started run 649 on task 146197, dataset 'dna'.
[2018-04-11 21:48:09] Error in run 642: Run already exists in server. Run id(s): {9046388}
[2018-04-11 21:48:09] Started run 650 on task 146197, dataset 'dna'.
[2018-04-11 21:48:09] Error in run 643: Run already exists in server. Run id(s): {9046346}
[2018-04-11 21:48:09] Started run 651 on task 146197, dataset 'dna'.
[2018-04-11 21:48:09] Error in run 645: Run already exists in server. Run id(s): {9046396}
[2018-04-11 21:48:09] Error in run 644: Run already exists in server. Run id(s): {9046410}
[2018-04-11 21:48:09] Started run 652 on task 146197, dataset 'dna'.
[2018-04-11 21:48:09] Started run 653 on task 146197, dataset 'dna'.
[2018-04-11 21:48:10] Error in run 646: Run already exists in server. Run id(s): {9046469}
[2018-04-11 21:48:10] Error in run 647: Run already exists in server. Run id(s): {9046393}
[2018-04-11 21:48:10] Started run 654 on task 146197, dataset 'dna'.
[2018-04-11 21:48:10] Started run 655 on task 146197, dataset 'dna'.
[2018-04-11 21:48:11] Error in run 648: Run already exists in server. Run id(s): {9046435}
[2018-04-11 21:48:11] Started run 656 on task 146197, dataset 'dna'.
[2018-04-11 21:48:12] Error in run 649: Run already exists in server. Run id(s): {9046457}
[2018-04-11 21:48:12] Started run 657 on task 146197, dataset 'dna'.
[2018-04-11 21:48:13] Error in run 650: Run already exists in server. Run id(s): {9046471}
[2018-04-11 21:48:13] Started run 658 on task 146197, dataset 'dna'.
[2018-04-11 21:48:14] Error in run 651: Run already exists in server. Run id(s): {9046442}
[2018-04-11 21:48:14] Started run 659 on task 146197, dataset 'dna'.
[2018-04-11 21:48:14] Error in run 652: Run already exists in server. Run id(s): {9046430}
[2018-04-11 21:48:14] Error in run 653: Run already exists in server. Run id(s): {9046416}
[2018-04-11 21:48:14] Started run 660 on task 146197, dataset 'dna'.
[2018-04-11 21:48:14] Started run 661 on task 146197, dataset 'dna'.
[2018-04-11 21:48:15] Error in run 654: Run already exists in server. Run id(s): {9046443}
[2018-04-11 21:48:15] Error in run 655: Run already exists in server. Run id(s): {9046437}
[2018-04-11 21:48:15] Started run 662 on task 146197, dataset 'dna'.
[2018-04-11 21:48:15] Started run 663 on task 146197, dataset 'dna'.
[2018-04-11 21:48:16] Error in run 656: Run already exists in server. Run id(s): {9046500}
[2018-04-11 21:48:16] Started run 664 on task 146197, dataset 'dna'.
[2018-04-11 21:48:17] Error in run 657: Run already exists in server. Run id(s): {9046485}
[2018-04-11 21:48:17] Started run 665 on task 146197, dataset 'dna'.
[2018-04-11 21:48:18] Error in run 659: Run already exists in server. Run id(s): {9046502}
[2018-04-11 21:48:18] Error in run 658: Run already exists in server. Run id(s): {9046462}
[2018-04-11 21:48:18] Started run 666 on task 146197, dataset 'dna'.
[2018-04-11 21:48:18] Started run 667 on task 146197, dataset 'dna'.
[2018-04-11 21:48:19] Error in run 660: Run already exists in server. Run id(s): {9046551}
[2018-04-11 21:48:19] Error in run 661: Run already exists in server. Run id(s): {9046580}
[2018-04-11 21:48:19] Started run 668 on task 146197, dataset 'dna'.
[2018-04-11 21:48:19] Started run 669 on task 146197, dataset 'dna'.
[2018-04-11 21:48:20] Error in run 662: Run already exists in server. Run id(s): {9046585}
[2018-04-11 21:48:20] Error in run 663: Run already exists in server. Run id(s): {9046568}
[2018-04-11 21:48:20] Started run 670 on task 146197, dataset 'dna'.
[2018-04-11 21:48:20] Started run 671 on task 146197, dataset 'dna'.
[2018-04-11 21:48:20] Error in run 664: Run already exists in server. Run id(s): {9046545}
[2018-04-11 21:48:20] Started run 672 on task 146197, dataset 'dna'.
[2018-04-11 21:48:21] Error in run 665: Run already exists in server. Run id(s): {9046526}
[2018-04-11 21:48:21] Started run 673 on task 146197, dataset 'dna'.
[2018-04-11 21:48:23] Error in run 666: Run already exists in server. Run id(s): {9046575}
[2018-04-11 21:48:23] Error in run 667: Run already exists in server. Run id(s): {9046608}
[2018-04-11 21:48:23] Started run 674 on task 146197, dataset 'dna'.
[2018-04-11 21:48:23] Started run 675 on task 146197, dataset 'dna'.
[2018-04-11 21:48:24] Error in run 669: Run already exists in server. Run id(s): {9046598}
[2018-04-11 21:48:24] Error in run 668: Run already exists in server. Run id(s): {9046615}
[2018-04-11 21:48:24] Started run 676 on task 146197, dataset 'dna'.
[2018-04-11 21:48:24] Started run 677 on task 146197, dataset 'dna'.
[2018-04-11 21:48:24] Error in run 670: Run already exists in server. Run id(s): {9046562}
[2018-04-11 21:48:24] Started run 678 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Error in run 671: Run already exists in server. Run id(s): {9046618}
[2018-04-11 21:48:25] Started run 679 on task 146197, dataset 'dna'.
[2018-04-11 21:48:25] Error in run 672: Run already exists in server. Run id(s): {9046651}
[2018-04-11 21:48:25] Started run 680 on task 146197, dataset 'dna'.
[2018-04-11 21:48:26] Error in run 673: Run already exists in server. Run id(s): {9046620}
[2018-04-11 21:48:26] Started run 681 on task 146197, dataset 'dna'.
[2018-04-11 21:48:27] Error in run 674: Run already exists in server. Run id(s): {9046626}
[2018-04-11 21:48:27] Started run 682 on task 146197, dataset 'dna'.
[2018-04-11 21:48:28] Error in run 675: Run already exists in server. Run id(s): {9046602}
[2018-04-11 21:48:28] Started run 683 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Error in run 676: Run already exists in server. Run id(s): {9046681}
[2018-04-11 21:48:29] Error in run 677: Run already exists in server. Run id(s): {9046631}
[2018-04-11 21:48:29] Started run 684 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Started run 685 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Error in run 678: Run already exists in server. Run id(s): {9046621}
[2018-04-11 21:48:29] Started run 686 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Error in run 679: Run already exists in server. Run id(s): {9046659}
[2018-04-11 21:48:29] Started run 687 on task 146197, dataset 'dna'.
[2018-04-11 21:48:29] Error in run 680: Run already exists in server. Run id(s): {9046641}
[2018-04-11 21:48:29] Started run 688 on task 146197, dataset 'dna'.
[2018-04-11 21:48:30] Error in run 681: Run already exists in server. Run id(s): {9046634}
[2018-04-11 21:48:30] Started run 689 on task 146197, dataset 'dna'.
[2018-04-11 21:48:32] Error in run 682: Run already exists in server. Run id(s): {9046676}
[2018-04-11 21:48:32] Started run 690 on task 146197, dataset 'dna'.
[2018-04-11 21:48:32] Error in run 683: Run already exists in server. Run id(s): {9046662}
[2018-04-11 21:48:32] Started run 691 on task 146197, dataset 'dna'.
[2018-04-11 21:48:33] Error in run 684: Run already exists in server. Run id(s): {9046675}
[2018-04-11 21:48:33] Started run 692 on task 146197, dataset 'dna'.
[2018-04-11 21:48:33] Error in run 685: Run already exists in server. Run id(s): {9046728}
[2018-04-11 21:48:33] Error in run 686: Run already exists in server. Run id(s): {9046716}
[2018-04-11 21:48:33] Started run 693 on task 146197, dataset 'dna'.
[2018-04-11 21:48:33] Started run 694 on task 146197, dataset 'dna'.
[2018-04-11 21:48:34] Error in run 687: Run already exists in server. Run id(s): {9046660}
[2018-04-11 21:48:34] Started run 695 on task 146197, dataset 'dna'.
[2018-04-11 21:48:34] Error in run 688: Run already exists in server. Run id(s): {9046696}
[2018-04-11 21:48:34] Started run 696 on task 146197, dataset 'dna'.
[2018-04-11 21:48:35] Error in run 689: Run already exists in server. Run id(s): {9046707}
[2018-04-11 21:48:35] Started run 697 on task 146197, dataset 'dna'.
[2018-04-11 21:48:37] Error in run 690: Run already exists in server. Run id(s): {9046752}
[2018-04-11 21:48:37] Started run 698 on task 146197, dataset 'dna'.
[2018-04-11 21:48:37] Error in run 691: Run already exists in server. Run id(s): {9046705}
[2018-04-11 21:48:37] Started run 699 on task 146197, dataset 'dna'.
[2018-04-11 21:48:37] Error in run 692: Run already exists in server. Run id(s): {9046687}
[2018-04-11 21:48:37] Started run 700 on task 146197, dataset 'dna'.
[2018-04-11 21:48:38] Error in run 693: Run already exists in server. Run id(s): {9046686}
[2018-04-11 21:48:38] Started run 701 on task 146197, dataset 'dna'.
[2018-04-11 21:48:38] Error in run 694: Run already exists in server. Run id(s): {9046790}
[2018-04-11 21:48:38] Started run 702 on task 146197, dataset 'dna'.
[2018-04-11 21:48:38] Error in run 695: Run already exists in server. Run id(s): {9046715}
[2018-04-11 21:48:38] Started run 703 on task 146197, dataset 'dna'.
[2018-04-11 21:48:38] Error in run 696: Run already exists in server. Run id(s): {9046739}
[2018-04-11 21:48:38] Started run 704 on task 146197, dataset 'dna'.
[2018-04-11 21:48:40] Error in run 697: Run already exists in server. Run id(s): {9046748}
[2018-04-11 21:48:40] Started run 705 on task 146197, dataset 'dna'.
[2018-04-11 21:48:41] Error in run 698: Run already exists in server. Run id(s): {9046763}
[2018-04-11 21:48:41] Started run 706 on task 146197, dataset 'dna'.
[2018-04-11 21:48:41] Error in run 699: Run already exists in server. Run id(s): {9046779}
[2018-04-11 21:48:41] Started run 707 on task 146197, dataset 'dna'.
[2018-04-11 21:48:42] Error in run 700: Run already exists in server. Run id(s): {9046757}
[2018-04-11 21:48:42] Started run 708 on task 146197, dataset 'dna'.
[2018-04-11 21:48:42] Error in run 701: Run already exists in server. Run id(s): {9046824}
[2018-04-11 21:48:42] Started run 709 on task 146197, dataset 'dna'.
[2018-04-11 21:48:43] Error in run 702: Run already exists in server. Run id(s): {9046821}
[2018-04-11 21:48:43] Started run 710 on task 146197, dataset 'dna'.
[2018-04-11 21:48:43] Error in run 703: Run already exists in server. Run id(s): {9046814}
[2018-04-11 21:48:43] Started run 711 on task 146197, dataset 'dna'.
[2018-04-11 21:48:43] Error in run 704: Run already exists in server. Run id(s): {9046870}
[2018-04-11 21:48:43] Started run 712 on task 146197, dataset 'dna'.
[2018-04-11 21:48:44] Error in run 705: Run already exists in server. Run id(s): {9046835}
[2018-04-11 21:48:44] Started run 713 on task 146197, dataset 'dna'.
[2018-04-11 21:48:46] Error in run 706: Run already exists in server. Run id(s): {9046857}
[2018-04-11 21:48:46] Started run 714 on task 146197, dataset 'dna'.
[2018-04-11 21:48:46] Error in run 707: Run already exists in server. Run id(s): {9046804}
[2018-04-11 21:48:46] Started run 715 on task 146197, dataset 'dna'.
[2018-04-11 21:48:47] Error in run 709: Run already exists in server. Run id(s): {9046861}
[2018-04-11 21:48:47] Error in run 708: Run already exists in server. Run id(s): {9046795}
[2018-04-11 21:48:47] Started run 716 on task 146197, dataset 'dna'.
[2018-04-11 21:48:47] Started run 717 on task 146197, dataset 'dna'.
[2018-04-11 21:48:47] Error in run 710: Run already exists in server. Run id(s): {9046862}
[2018-04-11 21:48:47] Started run 718 on task 146197, dataset 'dna'.
[2018-04-11 21:48:47] Error in run 712: Run already exists in server. Run id(s): {9046864}
[2018-04-11 21:48:47] Error in run 711: Run already exists in server. Run id(s): {9046923}
[2018-04-11 21:48:47] Started run 719 on task 146197, dataset 'dna'.
[2018-04-11 21:48:47] Started run 720 on task 146197, dataset 'dna'.
[2018-04-11 21:48:49] Error in run 713: Run already exists in server. Run id(s): {9046846}
[2018-04-11 21:48:49] Started run 721 on task 146197, dataset 'dna'.
[2018-04-11 21:48:50] Error in run 714: Run already exists in server. Run id(s): {9046915}
[2018-04-11 21:48:50] Started run 722 on task 146197, dataset 'dna'.
[2018-04-11 21:48:50] Error in run 715: Run already exists in server. Run id(s): {9046916}
[2018-04-11 21:48:50] Started run 723 on task 146197, dataset 'dna'.
[2018-04-11 21:48:51] Error in run 716: Run already exists in server. Run id(s): {9046906}
[2018-04-11 21:48:51] Started run 724 on task 146197, dataset 'dna'.
[2018-04-11 21:48:51] Error in run 717: Run already exists in server. Run id(s): {9046912}
[2018-04-11 21:48:51] Started run 725 on task 146197, dataset 'dna'.
[2018-04-11 21:48:52] Error in run 718: Run already exists in server. Run id(s): {9046880}
[2018-04-11 21:48:52] Started run 726 on task 146197, dataset 'dna'.
[2018-04-11 21:48:52] Error in run 719: Run already exists in server. Run id(s): {9046878}
[2018-04-11 21:48:52] Started run 727 on task 146197, dataset 'dna'.
[2018-04-11 21:48:52] Error in run 720: Run already exists in server. Run id(s): {9046920}
[2018-04-11 21:48:52] Started run 728 on task 146197, dataset 'dna'.
[2018-04-11 21:48:53] Error in run 721: Run already exists in server. Run id(s): {9046883}
[2018-04-11 21:48:53] Started run 729 on task 146197, dataset 'dna'.
[2018-04-11 21:48:55] Error in run 722: Run already exists in server. Run id(s): {9046983}
[2018-04-11 21:48:55] Error in run 723: Run already exists in server. Run id(s): {9046937}
[2018-04-11 21:48:55] Started run 730 on task 146197, dataset 'dna'.
[2018-04-11 21:48:55] Started run 731 on task 146197, dataset 'dna'.
[2018-04-11 21:48:56] Error in run 724: Run already exists in server. Run id(s): {9046948}
[2018-04-11 21:48:56] Error in run 725: Run already exists in server. Run id(s): {9046935}
[2018-04-11 21:48:56] Started run 732 on task 146197, dataset 'dna'.
[2018-04-11 21:48:56] Started run 733 on task 146197, dataset 'dna'.
[2018-04-11 21:48:56] Error in run 726: Run already exists in server. Run id(s): {9046997}
[2018-04-11 21:48:56] Error in run 728: Run already exists in server. Run id(s): {9046953}
[2018-04-11 21:48:56] Error in run 727: Run already exists in server. Run id(s): {9046988}
[2018-04-11 21:48:56] Started run 734 on task 146197, dataset 'dna'.
[2018-04-11 21:48:56] Started run 735 on task 146197, dataset 'dna'.
[2018-04-11 21:48:56] Started run 736 on task 146197, dataset 'dna'.
[2018-04-11 21:48:58] Error in run 729: Run already exists in server. Run id(s): {9047010}
[2018-04-11 21:48:58] Started run 737 on task 146197, dataset 'dna'.
[2018-04-11 21:49:00] Error in run 730: Run already exists in server. Run id(s): {9046974}
[2018-04-11 21:49:00] Error in run 731: Run already exists in server. Run id(s): {9047031}
[2018-04-11 21:49:00] Started run 738 on task 146197, dataset 'dna'.
[2018-04-11 21:49:00] Started run 739 on task 146197, dataset 'dna'.
[2018-04-11 21:49:00] Error in run 732: Run already exists in server. Run id(s): {9046981}
[2018-04-11 21:49:00] Error in run 733: Run already exists in server. Run id(s): {9047036}
[2018-04-11 21:49:00] Started run 740 on task 146197, dataset 'dna'.
[2018-04-11 21:49:00] Started run 741 on task 146197, dataset 'dna'.
[2018-04-11 21:49:01] Error in run 736: Run already exists in server. Run id(s): {9047029}
[2018-04-11 21:49:01] Error in run 734: Run already exists in server. Run id(s): {9047028}
[2018-04-11 21:49:01] Error in run 735: Run already exists in server. Run id(s): {9047087}
[2018-04-11 21:49:01] Started run 742 on task 146197, dataset 'dna'.
[2018-04-11 21:49:01] Started run 744 on task 146197, dataset 'dna'.
[2018-04-11 21:49:01] Started run 743 on task 146197, dataset 'dna'.
[2018-04-11 21:49:03] Error in run 737: Run already exists in server. Run id(s): {9047090}
[2018-04-11 21:49:03] Started run 745 on task 146197, dataset 'dna'.
[2018-04-11 21:49:04] Error in run 738: Run already exists in server. Run id(s): {9047013}
[2018-04-11 21:49:04] Error in run 739: Run already exists in server. Run id(s): {9047024}
[2018-04-11 21:49:04] Started run 746 on task 146197, dataset 'dna'.
[2018-04-11 21:49:04] Started run 747 on task 146197, dataset 'dna'.
[2018-04-11 21:49:05] Error in run 741: Run already exists in server. Run id(s): {9047034}
[2018-04-11 21:49:05] Error in run 740: Run already exists in server. Run id(s): {9047040}
[2018-04-11 21:49:05] Started run 748 on task 146197, dataset 'dna'.
[2018-04-11 21:49:05] Started run 749 on task 146197, dataset 'dna'.
[2018-04-11 21:49:06] Error in run 742: Run already exists in server. Run id(s): {9047081}
[2018-04-11 21:49:06] Started run 750 on task 146197, dataset 'dna'.
[2018-04-11 21:49:06] Error in run 744: Run already exists in server. Run id(s): {9047059}
[2018-04-11 21:49:06] Error in run 743: Run already exists in server. Run id(s): {9047078}
[2018-04-11 21:49:06] Started run 751 on task 146197, dataset 'dna'.
[2018-04-11 21:49:06] Started run 752 on task 146197, dataset 'dna'.
[2018-04-11 21:49:07] Error in run 745: Run already exists in server. Run id(s): {9047161}
[2018-04-11 21:49:07] Started run 753 on task 146197, dataset 'dna'.
[2018-04-11 21:49:09] Error in run 747: Run already exists in server. Run id(s): {9047112}
[2018-04-11 21:49:09] Error in run 746: Run already exists in server. Run id(s): {9047072}
[2018-04-11 21:49:09] Started run 754 on task 146197, dataset 'dna'.
[2018-04-11 21:49:09] Started run 755 on task 146197, dataset 'dna'.
[2018-04-11 21:49:10] Error in run 748: Run already exists in server. Run id(s): {9047073}
[2018-04-11 21:49:10] Error in run 749: Run already exists in server. Run id(s): {9047141}
[2018-04-11 21:49:10] Started run 756 on task 146197, dataset 'dna'.
[2018-04-11 21:49:10] Started run 757 on task 146197, dataset 'dna'.
[2018-04-11 21:49:10] Error in run 750: Run already exists in server. Run id(s): {9047094}
[2018-04-11 21:49:10] Started run 758 on task 146197, dataset 'dna'.
[2018-04-11 21:49:11] Error in run 751: Run already exists in server. Run id(s): {9047119}
[2018-04-11 21:49:11] Error in run 752: Run already exists in server. Run id(s): {9047149}
[2018-04-11 21:49:11] Started run 759 on task 146197, dataset 'dna'.
[2018-04-11 21:49:11] Started run 760 on task 146197, dataset 'dna'.
[2018-04-11 21:49:12] Error in run 753: Run already exists in server. Run id(s): {9047092}
[2018-04-11 21:49:12] Started run 761 on task 146197, dataset 'dna'.
[2018-04-11 21:49:14] Error in run 754: Run already exists in server. Run id(s): {9047121}
[2018-04-11 21:49:14] Error in run 755: Run already exists in server. Run id(s): {9047158}
[2018-04-11 21:49:14] Started run 762 on task 146197, dataset 'dna'.
[2018-04-11 21:49:14] Started run 763 on task 146197, dataset 'dna'.
[2018-04-11 21:49:14] Error in run 756: Run already exists in server. Run id(s): {9047108}
[2018-04-11 21:49:14] Started run 764 on task 146197, dataset 'dna'.
[2018-04-11 21:49:15] Error in run 757: Run already exists in server. Run id(s): {9047225}
[2018-04-11 21:49:15] Started run 765 on task 146197, dataset 'dna'.
[2018-04-11 21:49:15] Error in run 758: Run already exists in server. Run id(s): {9047199}
[2018-04-11 21:49:15] Started run 766 on task 146197, dataset 'dna'.
[2018-04-11 21:49:15] Error in run 759: Run already exists in server. Run id(s): {9047143}
[2018-04-11 21:49:15] Started run 767 on task 146197, dataset 'dna'.
[2018-04-11 21:49:15] Error in run 760: Run already exists in server. Run id(s): {9047239}
[2018-04-11 21:49:15] Started run 768 on task 146197, dataset 'dna'.
[2018-04-11 21:49:17] Error in run 761: Run already exists in server. Run id(s): {9047162}
[2018-04-11 21:49:17] Started run 769 on task 146197, dataset 'dna'.
[2018-04-11 21:49:19] Error in run 762: Run already exists in server. Run id(s): {9047211}
[2018-04-11 21:49:19] Error in run 763: Run already exists in server. Run id(s): {9047264}
[2018-04-11 21:49:19] Started run 770 on task 146197, dataset 'dna'.
[2018-04-11 21:49:19] Started run 771 on task 146197, dataset 'dna'.
[2018-04-11 21:49:19] Error in run 764: Run already exists in server. Run id(s): {9047206}
[2018-04-11 21:49:19] Started run 772 on task 146197, dataset 'dna'.
[2018-04-11 21:49:19] Error in run 765: Run already exists in server. Run id(s): {9047195}
[2018-04-11 21:49:19] Started run 773 on task 146197, dataset 'dna'.
[2018-04-11 21:49:19] Error in run 766: Run already exists in server. Run id(s): {9047222}
[2018-04-11 21:49:19] Started run 774 on task 146197, dataset 'dna'.
[2018-04-11 21:49:20] Error in run 767: Run already exists in server. Run id(s): {9047212}
[2018-04-11 21:49:20] Started run 775 on task 146197, dataset 'dna'.
[2018-04-11 21:49:20] Error in run 768: Run already exists in server. Run id(s): {9047229}
[2018-04-11 21:49:20] Started run 776 on task 146197, dataset 'dna'.
[2018-04-11 21:49:22] Error in run 769: Run already exists in server. Run id(s): {9047231}
[2018-04-11 21:49:22] Started run 777 on task 146197, dataset 'dna'.
[2018-04-11 21:49:23] Error in run 770: Run already exists in server. Run id(s): {9047260}
[2018-04-11 21:49:23] Started run 778 on task 146197, dataset 'dna'.
[2018-04-11 21:49:23] Error in run 771: Run already exists in server. Run id(s): {9047248}
[2018-04-11 21:49:23] Started run 779 on task 146197, dataset 'dna'.
[2018-04-11 21:49:23] Error in run 772: Run already exists in server. Run id(s): {9047278}
[2018-04-11 21:49:23] Started run 780 on task 146197, dataset 'dna'.
[2018-04-11 21:49:24] Error in run 773: Run already exists in server. Run id(s): {9047306}
[2018-04-11 21:49:24] Started run 781 on task 146197, dataset 'dna'.
[2018-04-11 21:49:24] Error in run 774: Run already exists in server. Run id(s): {9047275}
[2018-04-11 21:49:24] Started run 782 on task 146197, dataset 'dna'.
[2018-04-11 21:49:24] Error in run 775: Run already exists in server. Run id(s): {9047249}
[2018-04-11 21:49:24] Started run 783 on task 146197, dataset 'dna'.
[2018-04-11 21:49:25] Error in run 776: Run already exists in server. Run id(s): {9047320}
[2018-04-11 21:49:25] Started run 784 on task 146197, dataset 'dna'.
[2018-04-11 21:49:26] Error in run 777: Run already exists in server. Run id(s): {9047307}
[2018-04-11 21:49:26] Started run 785 on task 146197, dataset 'dna'.
[2018-04-11 21:49:28] Error in run 778: Run already exists in server. Run id(s): {9047315}
[2018-04-11 21:49:28] Started run 786 on task 146197, dataset 'dna'.
[2018-04-11 21:49:28] Error in run 779: Run already exists in server. Run id(s): {9047311}
[2018-04-11 21:49:28] Started run 787 on task 146197, dataset 'dna'.
[2018-04-11 21:49:28] Error in run 780: Run already exists in server. Run id(s): {9047373}
[2018-04-11 21:49:28] Started run 788 on task 146197, dataset 'dna'.
[2018-04-11 21:49:28] Error in run 781: Run already exists in server. Run id(s): {9047298}
[2018-04-11 21:49:28] Started run 789 on task 146197, dataset 'dna'.
[2018-04-11 21:49:28] Error in run 782: Run already exists in server. Run id(s): {9047291}
[2018-04-11 21:49:28] Started run 790 on task 146197, dataset 'dna'.
[2018-04-11 21:49:29] Error in run 783: Run already exists in server. Run id(s): {9047295}
[2018-04-11 21:49:29] Started run 791 on task 146197, dataset 'dna'.
[2018-04-11 21:49:29] Error in run 784: Run already exists in server. Run id(s): {9047340}
[2018-04-11 21:49:29] Started run 792 on task 146197, dataset 'dna'.
[2018-04-11 21:49:31] Error in run 785: Run already exists in server. Run id(s): {9047339}
[2018-04-11 21:49:31] Started run 793 on task 146197, dataset 'dna'.
[2018-04-11 21:49:32] Error in run 786: Run already exists in server. Run id(s): {9047407}
[2018-04-11 21:49:32] Started run 794 on task 146197, dataset 'dna'.
[2018-04-11 21:49:32] Error in run 787: Run already exists in server. Run id(s): {9047395}
[2018-04-11 21:49:32] Started run 795 on task 146197, dataset 'dna'.
[2018-04-11 21:49:33] Error in run 788: Run already exists in server. Run id(s): {9047388}
[2018-04-11 21:49:33] Started run 796 on task 146197, dataset 'dna'.
[2018-04-11 21:49:33] Error in run 790: Run already exists in server. Run id(s): {9047378}
[2018-04-11 21:49:33] Error in run 789: Run already exists in server. Run id(s): {9047347}
[2018-04-11 21:49:33] Started run 797 on task 146197, dataset 'dna'.
[2018-04-11 21:49:33] Started run 798 on task 146197, dataset 'dna'.
[2018-04-11 21:49:33] Error in run 791: Run already exists in server. Run id(s): {9047363}
[2018-04-11 21:49:33] Started run 799 on task 146197, dataset 'dna'.
[2018-04-11 21:49:34] Error in run 792: Run already exists in server. Run id(s): {9047383}
[2018-04-11 21:49:34] Started run 800 on task 146197, dataset 'dna'.
[2018-04-11 21:49:35] Error in run 793: Run already exists in server. Run id(s): {9047415}
[2018-04-11 21:49:35] Started run 801 on task 146197, dataset 'dna'.
[2018-04-11 21:49:37] Error in run 794: Run already exists in server. Run id(s): {9047454}
[2018-04-11 21:49:37] Error in run 795: Run already exists in server. Run id(s): {9047412}
[2018-04-11 21:49:37] Started run 802 on task 146197, dataset 'dna'.
[2018-04-11 21:49:37] Started run 803 on task 146197, dataset 'dna'.
[2018-04-11 21:49:37] Error in run 796: Run already exists in server. Run id(s): {9047405}
[2018-04-11 21:49:37] Started run 804 on task 146197, dataset 'dna'.
[2018-04-11 21:49:38] Error in run 797: Run already exists in server. Run id(s): {9047435}
[2018-04-11 21:49:38] Error in run 798: Run already exists in server. Run id(s): {9047432}
[2018-04-11 21:49:38] Started run 805 on task 146197, dataset 'dna'.
[2018-04-11 21:49:38] Started run 806 on task 146197, dataset 'dna'.
[2018-04-11 21:49:38] Error in run 799: Run already exists in server. Run id(s): {9047453, 9047447}
[2018-04-11 21:49:38] Started run 807 on task 146197, dataset 'dna'.
[2018-04-11 21:49:38] Error in run 800: Run already exists in server. Run id(s): {9047478}
[2018-04-11 21:49:38] Started run 808 on task 146197, dataset 'dna'.
[2018-04-11 21:49:40] Error in run 801: Run already exists in server. Run id(s): {9047464}
[2018-04-11 21:49:40] Started run 809 on task 146197, dataset 'dna'.
[2018-04-11 21:49:42] Error in run 802: Run already exists in server. Run id(s): {9047442}
[2018-04-11 21:49:42] Error in run 803: Run already exists in server. Run id(s): {9047479}
[2018-04-11 21:49:42] Started run 810 on task 146197, dataset 'dna'.
[2018-04-11 21:49:42] Error in run 804: Run already exists in server. Run id(s): {9047488}
[2018-04-11 21:49:42] Started run 811 on task 146197, dataset 'dna'.
[2018-04-11 21:49:42] Started run 812 on task 146197, dataset 'dna'.
[2018-04-11 21:49:42] Error in run 806: Run already exists in server. Run id(s): {9047548}
[2018-04-11 21:49:42] Error in run 805: Run already exists in server. Run id(s): {9047546}
[2018-04-11 21:49:42] Error in run 807: Run already exists in server. Run id(s): {9047559}
[2018-04-11 21:49:42] Started run 813 on task 146197, dataset 'dna'.
[2018-04-11 21:49:42] Started run 814 on task 146197, dataset 'dna'.
[2018-04-11 21:49:42] Started run 815 on task 146197, dataset 'dna'.
[2018-04-11 21:49:43] Error in run 808: Run already exists in server. Run id(s): {9047471}
[2018-04-11 21:49:43] Started run 816 on task 146197, dataset 'dna'.
[2018-04-11 21:49:45] Error in run 809: Run already exists in server. Run id(s): {9047525}
[2018-04-11 21:49:45] Started run 817 on task 146197, dataset 'dna'.
[2018-04-11 21:49:46] Error in run 810: Run already exists in server. Run id(s): {9047554}
[2018-04-11 21:49:46] Error in run 812: Run already exists in server. Run id(s): {9047565}
[2018-04-11 21:49:46] Error in run 811: Run already exists in server. Run id(s): {9047516}
[2018-04-11 21:49:46] Started run 818 on task 146197, dataset 'dna'.
[2018-04-11 21:49:46] Started run 820 on task 146197, dataset 'dna'.
[2018-04-11 21:49:46] Started run 819 on task 146197, dataset 'dna'.
[2018-04-11 21:49:47] Error in run 815: Run already exists in server. Run id(s): {9047605}
[2018-04-11 21:49:47] Error in run 813: Run already exists in server. Run id(s): {9047566}
[2018-04-11 21:49:47] Error in run 814: Run already exists in server. Run id(s): {9047556}
[2018-04-11 21:49:47] Started run 821 on task 146197, dataset 'dna'.
[2018-04-11 21:49:47] Started run 822 on task 146197, dataset 'dna'.
[2018-04-11 21:49:47] Started run 823 on task 146197, dataset 'dna'.
[2018-04-11 21:49:48] Error in run 816: Run already exists in server. Run id(s): {9047618}
[2018-04-11 21:49:48] Started run 824 on task 146197, dataset 'dna'.
[2018-04-11 21:49:49] Error in run 817: Run already exists in server. Run id(s): {9047614}
[2018-04-11 21:49:49] Started run 825 on task 146197, dataset 'dna'.
[2018-04-11 21:49:51] Error in run 819: Run already exists in server. Run id(s): {9047597}
[2018-04-11 21:49:51] Error in run 818: Run already exists in server. Run id(s): {9047603}
[2018-04-11 21:49:51] Error in run 820: Run already exists in server. Run id(s): {9047589}
[2018-04-11 21:49:51] Started run 826 on task 146197, dataset 'dna'.
[2018-04-11 21:49:51] Started run 828 on task 146197, dataset 'dna'.
[2018-04-11 21:49:51] Started run 827 on task 146197, dataset 'dna'.
[2018-04-11 21:49:52] Error in run 821: Run already exists in server. Run id(s): {9047658}
[2018-04-11 21:49:52] Error in run 823: Run already exists in server. Run id(s): {9047637}
[2018-04-11 21:49:52] Error in run 822: Run already exists in server. Run id(s): {9047670}
[2018-04-11 21:49:52] Started run 829 on task 146197, dataset 'dna'.
[2018-04-11 21:49:52] Started run 830 on task 146197, dataset 'dna'.
[2018-04-11 21:49:52] Started run 831 on task 146197, dataset 'dna'.
[2018-04-11 21:49:53] Error in run 824: Run already exists in server. Run id(s): {9047623}
[2018-04-11 21:49:53] Started run 832 on task 146197, dataset 'dna'.
[2018-04-11 21:49:54] Error in run 825: Run already exists in server. Run id(s): {9047627}
[2018-04-11 21:49:54] Started run 833 on task 146197, dataset 'dna'.
[2018-04-11 21:49:56] Error in run 828: Run already exists in server. Run id(s): {9047638}
[2018-04-11 21:49:56] Error in run 827: Run already exists in server. Run id(s): {9047649}
[2018-04-11 21:49:56] Error in run 826: Run already exists in server. Run id(s): {9047705}
[2018-04-11 21:49:56] Started run 834 on task 146197, dataset 'dna'.
[2018-04-11 21:49:56] Started run 836 on task 146197, dataset 'dna'.
[2018-04-11 21:49:56] Started run 835 on task 146197, dataset 'dna'.
[2018-04-11 21:49:57] Error in run 831: Run already exists in server. Run id(s): {9047671}
[2018-04-11 21:49:57] Error in run 830: Run already exists in server. Run id(s): {9047689}
[2018-04-11 21:49:57] Error in run 829: Run already exists in server. Run id(s): {9047712}
[2018-04-11 21:49:57] Started run 837 on task 146197, dataset 'dna'.
[2018-04-11 21:49:57] Started run 838 on task 146197, dataset 'dna'.
[2018-04-11 21:49:57] Started run 839 on task 146197, dataset 'dna'.
[2018-04-11 21:49:57] Error in run 832: Run already exists in server. Run id(s): {9047698}
[2018-04-11 21:49:57] Started run 840 on task 146197, dataset 'dna'.
[2018-04-11 21:49:59] Error in run 833: Run already exists in server. Run id(s): {9047700}
[2018-04-11 21:49:59] Started run 841 on task 146197, dataset 'dna'.
[2018-04-11 21:50:00] Error in run 835: Run already exists in server. Run id(s): {9047724}
[2018-04-11 21:50:00] Started run 842 on task 146197, dataset 'dna'.
[2018-04-11 21:50:01] Error in run 836: Run already exists in server. Run id(s): {9047746}
[2018-04-11 21:50:01] Started run 843 on task 146197, dataset 'dna'.
[2018-04-11 21:50:01] Error in run 834: Run already exists in server. Run id(s): {9047730}
[2018-04-11 21:50:01] Started run 844 on task 146197, dataset 'dna'.
[2018-04-11 21:50:01] Error in run 839: Run already exists in server. Run id(s): {9047759}
[2018-04-11 21:50:01] Error in run 838: Run already exists in server. Run id(s): {9047740}
[2018-04-11 21:50:01] Error in run 837: Run already exists in server. Run id(s): {9047747}
[2018-04-11 21:50:01] Started run 845 on task 146197, dataset 'dna'.
[2018-04-11 21:50:01] Started run 847 on task 146197, dataset 'dna'.
[2018-04-11 21:50:01] Started run 846 on task 146197, dataset 'dna'.
[2018-04-11 21:50:02] Error in run 840: Run already exists in server. Run id(s): {9047780}
[2018-04-11 21:50:02] Started run 848 on task 146197, dataset 'dna'.
[2018-04-11 21:50:04] Error in run 841: Run already exists in server. Run id(s): {9047778}
[2018-04-11 21:50:04] Started run 849 on task 146197, dataset 'dna'.
[2018-04-11 21:50:05] Error in run 842: Run already exists in server. Run id(s): {9047756}
[2018-04-11 21:50:05] Started run 850 on task 146197, dataset 'dna'.
[2018-04-11 21:50:05] Error in run 843: Run already exists in server. Run id(s): {9047770}
[2018-04-11 21:50:05] Error in run 844: Run already exists in server. Run id(s): {9047748}
[2018-04-11 21:50:05] Started run 851 on task 146197, dataset 'dna'.
[2018-04-11 21:50:05] Started run 852 on task 146197, dataset 'dna'.
[2018-04-11 21:50:06] Error in run 846: Run already exists in server. Run id(s): {9047839}
[2018-04-11 21:50:06] Error in run 847: Run already exists in server. Run id(s): {9047807}
[2018-04-11 21:50:06] Error in run 845: Run already exists in server. Run id(s): {9047831}
[2018-04-11 21:50:06] Started run 853 on task 146197, dataset 'dna'.
[2018-04-11 21:50:06] Started run 854 on task 146197, dataset 'dna'.
[2018-04-11 21:50:06] Started run 855 on task 146197, dataset 'dna'.
[2018-04-11 21:50:07] Error in run 848: Run already exists in server. Run id(s): {9047865}
[2018-04-11 21:50:07] Started run 856 on task 146197, dataset 'dna'.
[2018-04-11 21:50:09] Error in run 849: Run already exists in server. Run id(s): {9047786}
[2018-04-11 21:50:09] Started run 857 on task 146197, dataset 'dna'.
[2018-04-11 21:50:10] Error in run 850: Run already exists in server. Run id(s): {9047798}
[2018-04-11 21:50:10] Started run 858 on task 146197, dataset 'dna'.
[2018-04-11 21:50:10] Error in run 851: Run already exists in server. Run id(s): {9047842}
[2018-04-11 21:50:10] Error in run 852: Run already exists in server. Run id(s): {9047861}
[2018-04-11 21:50:10] Started run 859 on task 146197, dataset 'dna'.
[2018-04-11 21:50:10] Started run 860 on task 146197, dataset 'dna'.
[2018-04-11 21:50:11] Error in run 854: Run already exists in server. Run id(s): {9047828}
[2018-04-11 21:50:11] Error in run 853: Run already exists in server. Run id(s): {9047851}
[2018-04-11 21:50:11] Error in run 855: Run already exists in server. Run id(s): {9047848}
[2018-04-11 21:50:11] Started run 861 on task 146197, dataset 'dna'.
[2018-04-11 21:50:11] Started run 862 on task 146197, dataset 'dna'.
[2018-04-11 21:50:11] Started run 863 on task 146197, dataset 'dna'.
[2018-04-11 21:50:12] Error in run 856: Run already exists in server. Run id(s): {9047882}
[2018-04-11 21:50:12] Started run 864 on task 146197, dataset 'dna'.
[2018-04-11 21:50:13] Error in run 857: Run already exists in server. Run id(s): {9047858}
[2018-04-11 21:50:13] Started run 865 on task 146197, dataset 'dna'.
[2018-04-11 21:50:14] Error in run 858: Run already exists in server. Run id(s): {9047856}
[2018-04-11 21:50:14] Started run 866 on task 146197, dataset 'dna'.
[2018-04-11 21:50:15] Error in run 860: Run already exists in server. Run id(s): {9047909}
[2018-04-11 21:50:15] Error in run 859: Run already exists in server. Run id(s): {9047913}
[2018-04-11 21:50:15] Started run 867 on task 146197, dataset 'dna'.
[2018-04-11 21:50:15] Started run 868 on task 146197, dataset 'dna'.
[2018-04-11 21:50:16] Error in run 861: Run already exists in server. Run id(s): {9047891}
[2018-04-11 21:50:16] Started run 869 on task 146197, dataset 'dna'.
[2018-04-11 21:50:16] Error in run 862: Run already exists in server. Run id(s): {9047905}
[2018-04-11 21:50:16] Error in run 863: Run already exists in server. Run id(s): {9047880}
[2018-04-11 21:50:16] Started run 871 on task 146197, dataset 'dna'.
[2018-04-11 21:50:16] Started run 870 on task 146197, dataset 'dna'.
[2018-04-11 21:50:16] Error in run 864: Run already exists in server. Run id(s): {9047920}
[2018-04-11 21:50:16] Started run 872 on task 146197, dataset 'dna'.
[2018-04-11 21:50:18] Error in run 865: Run already exists in server. Run id(s): {9047953}
[2018-04-11 21:50:18] Started run 873 on task 146197, dataset 'dna'.
[2018-04-11 21:50:19] Error in run 866: Run already exists in server. Run id(s): {9047927}
[2018-04-11 21:50:19] Started run 874 on task 146197, dataset 'dna'.
[2018-04-11 21:50:19] Error in run 868: Run already exists in server. Run id(s): {9047919}
[2018-04-11 21:50:19] Started run 875 on task 146197, dataset 'dna'.
[2018-04-11 21:50:20] Error in run 867: Run already exists in server. Run id(s): {9047952}
[2018-04-11 21:50:20] Started run 876 on task 146197, dataset 'dna'.
[2018-04-11 21:50:20] Error in run 869: Run already exists in server. Run id(s): {9047945}
[2018-04-11 21:50:20] Error in run 870: Run already exists in server. Run id(s): {9047937}
[2018-04-11 21:50:20] Error in run 871: Run already exists in server. Run id(s): {9047933}
[2018-04-11 21:50:20] Started run 877 on task 146197, dataset 'dna'.
[2018-04-11 21:50:20] Started run 878 on task 146197, dataset 'dna'.
[2018-04-11 21:50:20] Started run 879 on task 146197, dataset 'dna'.
[2018-04-11 21:50:21] Error in run 872: Run already exists in server. Run id(s): {9047949}
[2018-04-11 21:50:21] Started run 880 on task 146197, dataset 'dna'.
[2018-04-11 21:50:22] Error in run 873: Run already exists in server. Run id(s): {9047979}
[2018-04-11 21:50:22] Started run 881 on task 146197, dataset 'dna'.
[2018-04-11 21:50:24] Error in run 874: Run already exists in server. Run id(s): {9047932}
[2018-04-11 21:50:24] Started run 882 on task 146197, dataset 'dna'.
[2018-04-11 21:50:24] Error in run 875: Run already exists in server. Run id(s): {9047987}
[2018-04-11 21:50:24] Started run 883 on task 146197, dataset 'dna'.
[2018-04-11 21:50:24] Error in run 876: Run already exists in server. Run id(s): {9047982}
[2018-04-11 21:50:24] Started run 884 on task 146197, dataset 'dna'.
[2018-04-11 21:50:25] Error in run 878: Run already exists in server. Run id(s): {9047970}
[2018-04-11 21:50:25] Error in run 877: Run already exists in server. Run id(s): {9047951}
[2018-04-11 21:50:25] Error in run 879: Run already exists in server. Run id(s): {9047958}
[2018-04-11 21:50:25] Started run 885 on task 146197, dataset 'dna'.
[2018-04-11 21:50:25] Started run 887 on task 146197, dataset 'dna'.
[2018-04-11 21:50:25] Started run 886 on task 146197, dataset 'dna'.
[2018-04-11 21:50:25] Error in run 880: Run already exists in server. Run id(s): {9047993}
[2018-04-11 21:50:25] Started run 888 on task 146197, dataset 'dna'.
[2018-04-11 21:50:27] Error in run 881: Run already exists in server. Run id(s): {9047992}
[2018-04-11 21:50:27] Started run 889 on task 146197, dataset 'dna'.
[2018-04-11 21:50:28] Error in run 882: Run already exists in server. Run id(s): {9047974}
[2018-04-11 21:50:28] Started run 890 on task 146197, dataset 'dna'.
[2018-04-11 21:50:29] Error in run 883: Run already exists in server. Run id(s): {9048010}
[2018-04-11 21:50:29] Started run 891 on task 146197, dataset 'dna'.
[2018-04-11 21:50:29] Error in run 884: Run already exists in server. Run id(s): {9048009}
[2018-04-11 21:50:29] Started run 892 on task 146197, dataset 'dna'.
[2018-04-11 21:50:30] Error in run 885: Run already exists in server. Run id(s): {9048024}
[2018-04-11 21:50:30] Error in run 887: Run already exists in server. Run id(s): {9048038}
[2018-04-11 21:50:30] Error in run 888: Run already exists in server. Run id(s): {9048018}
[2018-04-11 21:50:30] Error in run 886: Run already exists in server. Run id(s): {9048014}
[2018-04-11 21:50:30] Started run 893 on task 146197, dataset 'dna'.
[2018-04-11 21:50:30] Started run 895 on task 146197, dataset 'dna'.
[2018-04-11 21:50:30] Started run 894 on task 146197, dataset 'dna'.
[2018-04-11 21:50:30] Started run 896 on task 146197, dataset 'dna'.
[2018-04-11 21:50:32] Error in run 889: Run already exists in server. Run id(s): {9048007}
[2018-04-11 21:50:32] Started run 897 on task 146197, dataset 'dna'.
[2018-04-11 21:50:33] Error in run 890: Run already exists in server. Run id(s): {9048013}
[2018-04-11 21:50:33] Error in run 891: Run already exists in server. Run id(s): {9048016}
[2018-04-11 21:50:33] Started run 898 on task 146197, dataset 'dna'.
[2018-04-11 21:50:33] Started run 899 on task 146197, dataset 'dna'.
[2018-04-11 21:50:34] Error in run 892: Run already exists in server. Run id(s): {9048066}
[2018-04-11 21:50:34] Started run 900 on task 146197, dataset 'dna'.
[2018-04-11 21:50:35] Error in run 895: Run already exists in server. Run id(s): {9048077}
[2018-04-11 21:50:35] Error in run 893: Run already exists in server. Run id(s): {9048082}
[2018-04-11 21:50:35] Error in run 896: Run already exists in server. Run id(s): {9048072}
[2018-04-11 21:50:35] Error in run 894: Run already exists in server. Run id(s): {9048063}
[2018-04-11 21:50:35] Started run 901 on task 146197, dataset 'dna'.
[2018-04-11 21:50:35] Started run 902 on task 146197, dataset 'dna'.
[2018-04-11 21:50:35] Started run 903 on task 146197, dataset 'dna'.
[2018-04-11 21:50:35] Started run 904 on task 146197, dataset 'dna'.
[2018-04-11 21:50:36] Error in run 897: Run already exists in server. Run id(s): {9048070}
[2018-04-11 21:50:36] Started run 905 on task 146197, dataset 'dna'.
[2018-04-11 21:50:38] Error in run 898: Run already exists in server. Run id(s): {9048056}
[2018-04-11 21:50:38] Error in run 899: Run already exists in server. Run id(s): {9048100}
[2018-04-11 21:50:38] Started run 906 on task 146197, dataset 'dna'.
[2018-04-11 21:50:38] Started run 907 on task 146197, dataset 'dna'.
[2018-04-11 21:50:39] Error in run 900: Run already exists in server. Run id(s): {9048068}
[2018-04-11 21:50:39] Started run 908 on task 146197, dataset 'dna'.
[2018-04-11 21:50:39] Error in run 903: Run already exists in server. Run id(s): {9048118}
[2018-04-11 21:50:39] Error in run 904: Run already exists in server. Run id(s): {9048085}
[2018-04-11 21:50:39] Error in run 901: Run already exists in server. Run id(s): {9048108}
[2018-04-11 21:50:39] Error in run 902: Run already exists in server. Run id(s): {9048143}
[2018-04-11 21:50:39] Started run 909 on task 146197, dataset 'dna'.
[2018-04-11 21:50:39] Started run 911 on task 146197, dataset 'dna'.
[2018-04-11 21:50:39] Started run 910 on task 146197, dataset 'dna'.
[2018-04-11 21:50:39] Started run 912 on task 146197, dataset 'dna'.
[2018-04-11 21:50:41] Error in run 905: Run already exists in server. Run id(s): {9048092}
[2018-04-11 21:50:41] Started run 913 on task 146197, dataset 'dna'.
[2018-04-11 21:50:43] Error in run 907: Run already exists in server. Run id(s): {9048104}
[2018-04-11 21:50:43] Error in run 906: Run already exists in server. Run id(s): {9048096}
[2018-04-11 21:50:43] Started run 914 on task 146197, dataset 'dna'.
[2018-04-11 21:50:43] Started run 915 on task 146197, dataset 'dna'.
[2018-04-11 21:50:43] Error in run 908: Run already exists in server. Run id(s): {9048139}
[2018-04-11 21:50:43] Started run 916 on task 146197, dataset 'dna'.
[2018-04-11 21:50:44] Error in run 911: Run already exists in server. Run id(s): {9048173}
[2018-04-11 21:50:44] Error in run 909: Run already exists in server. Run id(s): {9048165}
[2018-04-11 21:50:44] Error in run 910: Run already exists in server. Run id(s): {9048180}
[2018-04-11 21:50:44] Error in run 912: Run already exists in server. Run id(s): {9048138}
[2018-04-11 21:50:44] Started run 917 on task 146197, dataset 'dna'.
[2018-04-11 21:50:44] Started run 920 on task 146197, dataset 'dna'.
[2018-04-11 21:50:44] Started run 918 on task 146197, dataset 'dna'.
[2018-04-11 21:50:44] Started run 919 on task 146197, dataset 'dna'.
[2018-04-11 21:50:46] Error in run 913: Run already exists in server. Run id(s): {9048155}
[2018-04-11 21:50:46] Started run 921 on task 146197, dataset 'dna'.
[2018-04-11 21:50:47] Error in run 914: Run already exists in server. Run id(s): {9048162}
[2018-04-11 21:50:47] Error in run 915: Run already exists in server. Run id(s): {9048178}
[2018-04-11 21:50:47] Started run 922 on task 146197, dataset 'dna'.
[2018-04-11 21:50:47] Started run 923 on task 146197, dataset 'dna'.
[2018-04-11 21:50:48] Error in run 916: Run already exists in server. Run id(s): {9048192}
[2018-04-11 21:50:48] Started run 924 on task 146197, dataset 'dna'.
[2018-04-11 21:50:49] Error in run 917: Run already exists in server. Run id(s): {9048163}
[2018-04-11 21:50:49] Error in run 920: Run already exists in server. Run id(s): {9048200}
[2018-04-11 21:50:49] Error in run 919: Run already exists in server. Run id(s): {9048181}
[2018-04-11 21:50:49] Error in run 918: Run already exists in server. Run id(s): {9048210}
[2018-04-11 21:50:49] Started run 925 on task 146197, dataset 'dna'.
[2018-04-11 21:50:49] Started run 926 on task 146197, dataset 'dna'.
[2018-04-11 21:50:49] Started run 927 on task 146197, dataset 'dna'.
[2018-04-11 21:50:49] Started run 928 on task 146197, dataset 'dna'.
[2018-04-11 21:50:51] Error in run 921: Run already exists in server. Run id(s): {9048191}
[2018-04-11 21:50:51] Started run 929 on task 146197, dataset 'dna'.
[2018-04-11 21:50:52] Error in run 922: Run already exists in server. Run id(s): {9048252}
[2018-04-11 21:50:52] Started run 930 on task 146197, dataset 'dna'.
[2018-04-11 21:50:52] Error in run 923: Run already exists in server. Run id(s): {9048203}
[2018-04-11 21:50:52] Started run 931 on task 146197, dataset 'dna'.
[2018-04-11 21:50:53] Error in run 924: Run already exists in server. Run id(s): {9048207}
[2018-04-11 21:50:53] Started run 932 on task 146197, dataset 'dna'.
[2018-04-11 21:50:54] Error in run 926: Run already exists in server. Run id(s): {9048231}
[2018-04-11 21:50:54] Error in run 925: Run already exists in server. Run id(s): {9048236}
[2018-04-11 21:50:54] Error in run 928: Run already exists in server. Run id(s): {9048229}
[2018-04-11 21:50:54] Error in run 927: Run already exists in server. Run id(s): {9048223}
[2018-04-11 21:50:54] Started run 933 on task 146197, dataset 'dna'.
[2018-04-11 21:50:54] Started run 936 on task 146197, dataset 'dna'.
[2018-04-11 21:50:54] Started run 934 on task 146197, dataset 'dna'.
[2018-04-11 21:50:54] Started run 935 on task 146197, dataset 'dna'.
[2018-04-11 21:50:55] Error in run 929: Run already exists in server. Run id(s): {9048277}
[2018-04-11 21:50:55] Started run 937 on task 146197, dataset 'dna'.
[2018-04-11 21:50:57] Error in run 931: Run already exists in server. Run id(s): {9048240}
[2018-04-11 21:50:57] Error in run 930: Run already exists in server. Run id(s): {9048272}
[2018-04-11 21:50:57] Started run 938 on task 146197, dataset 'dna'.
[2018-04-11 21:50:57] Started run 939 on task 146197, dataset 'dna'.
[2018-04-11 21:50:58] Error in run 932: Run already exists in server. Run id(s): {9048267}
[2018-04-11 21:50:58] Started run 940 on task 146197, dataset 'dna'.
[2018-04-11 21:50:58] Error in run 933: Run already exists in server. Run id(s): {9048262}
[2018-04-11 21:50:58] Error in run 936: Run already exists in server. Run id(s): {9048270}
[2018-04-11 21:50:58] Error in run 934: Run already exists in server. Run id(s): {9048244}
[2018-04-11 21:50:58] Started run 941 on task 146197, dataset 'dna'.
[2018-04-11 21:50:58] Started run 943 on task 146197, dataset 'dna'.
[2018-04-11 21:50:58] Started run 942 on task 146197, dataset 'dna'.
[2018-04-11 21:50:59] Error in run 935: Run already exists in server. Run id(s): {9048264}
[2018-04-11 21:50:59] Started run 944 on task 146197, dataset 'dna'.
[2018-04-11 21:51:00] Error in run 937: Run already exists in server. Run id(s): {9048302}
[2018-04-11 21:51:00] Started run 945 on task 146197, dataset 'dna'.
[2018-04-11 21:51:02] Error in run 938: Run already exists in server. Run id(s): {9048282}
[2018-04-11 21:51:02] Error in run 939: Run already exists in server. Run id(s): {9048285}
[2018-04-11 21:51:02] Started run 946 on task 146197, dataset 'dna'.
[2018-04-11 21:51:02] Started run 947 on task 146197, dataset 'dna'.
[2018-04-11 21:51:02] Error in run 940: Run already exists in server. Run id(s): {9048283}
[2018-04-11 21:51:02] Started run 948 on task 146197, dataset 'dna'.
[2018-04-11 21:51:03] Error in run 942: Run already exists in server. Run id(s): {9048279}
[2018-04-11 21:51:03] Error in run 943: Run already exists in server. Run id(s): {9048295}
[2018-04-11 21:51:03] Error in run 944: Run already exists in server. Run id(s): {9048325}
[2018-04-11 21:51:03] Error in run 941: Run already exists in server. Run id(s): {9048304}
[2018-04-11 21:51:03] Started run 949 on task 146197, dataset 'dna'.
[2018-04-11 21:51:03] Started run 952 on task 146197, dataset 'dna'.
[2018-04-11 21:51:03] Started run 950 on task 146197, dataset 'dna'.
[2018-04-11 21:51:03] Started run 951 on task 146197, dataset 'dna'.
[2018-04-11 21:51:05] Error in run 945: Run already exists in server. Run id(s): {9048287}
[2018-04-11 21:51:05] Started run 953 on task 146197, dataset 'dna'.
[2018-04-11 21:51:07] Error in run 947: Run already exists in server. Run id(s): {9048298}
[2018-04-11 21:51:07] Error in run 946: Run already exists in server. Run id(s): {9048307}
[2018-04-11 21:51:07] Started run 954 on task 146197, dataset 'dna'.
[2018-04-11 21:51:07] Started run 955 on task 146197, dataset 'dna'.
[2018-04-11 21:51:07] Error in run 948: Run already exists in server. Run id(s): {9048321}
[2018-04-11 21:51:07] Started run 956 on task 146197, dataset 'dna'.
[2018-04-11 21:51:08] Error in run 949: Run already exists in server. Run id(s): {9048314}
[2018-04-11 21:51:08] Error in run 951: Run already exists in server. Run id(s): {9048337}
[2018-04-11 21:51:08] Error in run 950: Run already exists in server. Run id(s): {9048354}
[2018-04-11 21:51:08] Error in run 952: Run already exists in server. Run id(s): {9048312}
[2018-04-11 21:51:08] Started run 957 on task 146197, dataset 'dna'.
[2018-04-11 21:51:08] Started run 958 on task 146197, dataset 'dna'.
[2018-04-11 21:51:08] Started run 959 on task 146197, dataset 'dna'.
[2018-04-11 21:51:08] Started run 960 on task 146197, dataset 'dna'.
[2018-04-11 21:51:10] Error in run 953: Run already exists in server. Run id(s): {9048357}
[2018-04-11 21:51:10] Started run 961 on task 146197, dataset 'dna'.
[2018-04-11 21:51:11] Error in run 955: Run already exists in server. Run id(s): {9048340}
[2018-04-11 21:51:11] Error in run 954: Run already exists in server. Run id(s): {9048320}
[2018-04-11 21:51:11] Started run 962 on task 146197, dataset 'dna'.
[2018-04-11 21:51:11] Started run 963 on task 146197, dataset 'dna'.
[2018-04-11 21:51:12] Error in run 956: Run already exists in server. Run id(s): {9048345}
[2018-04-11 21:51:12] Started run 964 on task 146197, dataset 'dna'.
[2018-04-11 21:51:13] Error in run 959: Run already exists in server. Run id(s): {9048351}
[2018-04-11 21:51:13] Error in run 957: Run already exists in server. Run id(s): {9048359}
[2018-04-11 21:51:13] Error in run 960: Run already exists in server. Run id(s): {9048348}
[2018-04-11 21:51:13] Error in run 958: Run already exists in server. Run id(s): {9048324}
[2018-04-11 21:51:13] Started run 965 on task 146197, dataset 'dna'.
[2018-04-11 21:51:13] Started run 966 on task 146197, dataset 'dna'.
[2018-04-11 21:51:13] Started run 967 on task 146197, dataset 'dna'.
[2018-04-11 21:51:13] Started run 968 on task 146197, dataset 'dna'.
[2018-04-11 21:51:14] Error in run 961: Run already exists in server. Run id(s): {9048416}
[2018-04-11 21:51:14] Started run 969 on task 146197, dataset 'dna'.
[2018-04-11 21:51:16] Error in run 962: Run already exists in server. Run id(s): {9048344}
[2018-04-11 21:51:16] Started run 970 on task 146197, dataset 'dna'.
[2018-04-11 21:51:16] Error in run 963: Run already exists in server. Run id(s): {9048355}
[2018-04-11 21:51:16] Started run 971 on task 146197, dataset 'dna'.
[2018-04-11 21:51:17] Error in run 964: Run already exists in server. Run id(s): {9048374}
[2018-04-11 21:51:17] Started run 972 on task 146197, dataset 'dna'.
[2018-04-11 21:51:18] Error in run 965: Run already exists in server. Run id(s): {9048412}
[2018-04-11 21:51:18] Error in run 967: Run already exists in server. Run id(s): {9048386}
[2018-04-11 21:51:18] Error in run 968: Run already exists in server. Run id(s): {9048394}
[2018-04-11 21:51:18] Error in run 966: Run already exists in server. Run id(s): {9048368}
[2018-04-11 21:51:18] Started run 973 on task 146197, dataset 'dna'.
[2018-04-11 21:51:18] Started run 976 on task 146197, dataset 'dna'.
[2018-04-11 21:51:18] Started run 974 on task 146197, dataset 'dna'.
[2018-04-11 21:51:18] Started run 975 on task 146197, dataset 'dna'.
[2018-04-11 21:51:19] Error in run 969: Run already exists in server. Run id(s): {9048434}
[2018-04-11 21:51:19] Started run 977 on task 146197, dataset 'dna'.
[2018-04-11 21:51:20] Error in run 970: Run already exists in server. Run id(s): {9048423}
[2018-04-11 21:51:20] Started run 978 on task 146197, dataset 'dna'.
[2018-04-11 21:51:21] Error in run 971: Run already exists in server. Run id(s): {9048388}
[2018-04-11 21:51:21] Started run 979 on task 146197, dataset 'dna'.
[2018-04-11 21:51:22] Error in run 972: Run already exists in server. Run id(s): {9048384}
[2018-04-11 21:51:22] Started run 980 on task 146197, dataset 'dna'.
[2018-04-11 21:51:22] Error in run 974: Run already exists in server. Run id(s): {9048392}
[2018-04-11 21:51:22] Started run 981 on task 146197, dataset 'dna'.
[2018-04-11 21:51:22] Error in run 976: Run already exists in server. Run id(s): {9048425}
[2018-04-11 21:51:22] Started run 982 on task 146197, dataset 'dna'.
[2018-04-11 21:51:23] Error in run 973: Run already exists in server. Run id(s): {9048414}
[2018-04-11 21:51:23] Error in run 975: Run already exists in server. Run id(s): {9048440}
[2018-04-11 21:51:23] Started run 983 on task 146197, dataset 'dna'.
[2018-04-11 21:51:23] Started run 984 on task 146197, dataset 'dna'.
[2018-04-11 21:51:23] Error in run 977: Run already exists in server. Run id(s): {9048467}
[2018-04-11 21:51:23] Started run 985 on task 146197, dataset 'dna'.
[2018-04-11 21:51:25] Error in run 978: Run already exists in server. Run id(s): {9048472}
[2018-04-11 21:51:25] Started run 986 on task 146197, dataset 'dna'.
[2018-04-11 21:51:26] Error in run 979: Run already exists in server. Run id(s): {9048426}
[2018-04-11 21:51:26] Started run 987 on task 146197, dataset 'dna'.
[2018-04-11 21:51:26] Error in run 980: Run already exists in server. Run id(s): {9048444}
[2018-04-11 21:51:26] Started run 988 on task 146197, dataset 'dna'.
[2018-04-11 21:51:27] Error in run 981: Run already exists in server. Run id(s): {9048477}
[2018-04-11 21:51:27] Error in run 984: Run already exists in server. Run id(s): {9048453}
[2018-04-11 21:51:27] Started run 989 on task 146197, dataset 'dna'.
[2018-04-11 21:51:27] Error in run 983: Run already exists in server. Run id(s): {9048437}
[2018-04-11 21:51:27] Started run 991 on task 146197, dataset 'dna'.
[2018-04-11 21:51:27] Error in run 982: Run already exists in server. Run id(s): {9048452}
[2018-04-11 21:51:27] Started run 992 on task 146197, dataset 'dna'.
[2018-04-11 21:51:27] Started run 990 on task 146197, dataset 'dna'.
[2018-04-11 21:51:28] Error in run 985: Run already exists in server. Run id(s): {9048510}
[2018-04-11 21:51:28] Started run 993 on task 146197, dataset 'dna'.
[2018-04-11 21:51:30] Error in run 986: Run already exists in server. Run id(s): {9048474}
[2018-04-11 21:51:30] Started run 994 on task 146197, dataset 'dna'.
[2018-04-11 21:51:30] Error in run 987: Run already exists in server. Run id(s): {9048490}
[2018-04-11 21:51:30] Started run 995 on task 146197, dataset 'dna'.
[2018-04-11 21:51:31] Error in run 988: Run already exists in server. Run id(s): {9048501}
[2018-04-11 21:51:31] Started run 996 on task 146197, dataset 'dna'.
[2018-04-11 21:51:32] Error in run 989: Run already exists in server. Run id(s): {9048469}
[2018-04-11 21:51:32] Started run 997 on task 146197, dataset 'dna'.
[2018-04-11 21:51:32] Error in run 990: Run already exists in server. Run id(s): {9048529}
[2018-04-11 21:51:32] Error in run 992: Run already exists in server. Run id(s): {9048486}
[2018-04-11 21:51:32] Error in run 991: Run already exists in server. Run id(s): {9048518}
[2018-04-11 21:51:32] Started run 998 on task 146197, dataset 'dna'.
[2018-04-11 21:51:32] Started run 999 on task 146197, dataset 'dna'.
[2018-04-11 21:51:32] Started run 1000 on task 146197, dataset 'dna'.
[2018-04-11 21:51:33] Error in run 993: Run already exists in server. Run id(s): {9048509}
[2018-04-11 21:51:34] Error in run 994: Run already exists in server. Run id(s): {9048543}
[2018-04-11 21:51:35] Error in run 995: Run already exists in server. Run id(s): {9048506}
[2018-04-11 21:51:35] Error in run 996: Run already exists in server. Run id(s): {9048514}
[2018-04-11 21:51:36] Error in run 997: Run already exists in server. Run id(s): {9048555}
[2018-04-11 21:51:37] Error in run 999: Run already exists in server. Run id(s): {9048530}
[2018-04-11 21:51:37] Error in run 1000: Run already exists in server. Run id(s): {9048550}
[2018-04-11 21:51:37] Error in run 998: Run already exists in server. Run id(s): {9048570}
